### ISSUE TITLE
quadric decimation gone?

### ISSUE THREAD

**Issue by jo-mueller** [marcomusy/vedo#1003]
Hi @marcomusy ,

I just realized together with @maleehahassan that the current vedo API doesn't provide the `quadric` option anymore but there's a new `decimate_binning` function. Does this contain the old functionality or has the quadric decimation been deprecated alltogether?

Best, Johannes

**Comment by marcomusy** [comment]
Hi @jo-mueller in the development version I split the `decimate` into `mesh.decimate()`, `mesh.decimate_pro()` and `mesh.decimate_binned()` as per #992
So the "quadric" is still the default (just remove the keyword in `decimate()`).
