### ISSUE TITLE
example slab_vol.py crashes on AttributeError: 'Volume' object has no attribute 'slab'

### ISSUE THREAD

**Issue by blooop** [marcomusy/vedo#1006]
I tried to run the slab_vol.py from the gallery but it crashes with:

```
slab = vol.slab([45,55], axis='z', operation='mean')
AttributeError: 'Volume' object has no attribute 'slab'
```

This is from a pip install vedo==2023.5.0

The slab function still appears to be in vedo so not sure what's happening:
https://github.com/marcomusy/vedo/blob/a84da7dbbae173212a2e6f983c506c71dc6d9295/vedo/volume.py#L459

**Comment by blooop** [comment]
On further investigation volume.py from pip install does not have slab() so that must be a new function that has not made it to a pip release yet.

**Comment by marcomusy** [comment]
Hi - yes - you need to install the dev version with

```
pip install -U git+https://github.com/marcomusy/vedo.git
```
