### ISSUE TITLE
collapse_edges() not preserving celldata

### ISSUE THREAD

**Issue by marcomusy** [marcomusy/vedo#1007]
I have a similar issue: 

I have a mesh with custom data per face, stored in mesh.celldata["mydata"]
I now iteratively collapse edges of the mesh and call mesh.clean() after each iteration to update topology (a slightly modified version of vedo.Mesh.collapse_edges()). While mesh.clean() correctly removes faces, e.g. when a triangle edge is collapsed, it does not update the celldata array. Is there any way to update the celldata, or e.g. get a map from input to output cells when calling mesh.clean()?

NB: the trick to move "mydata" to pointdata before mesh.clean() and then back does not work, because I do not want to interpolate "mydata".

_Originally posted by @raphaelsulzer in https://github.com/marcomusy/vedo/issues/992#issuecomment-1881098489_

**Comment by marcomusy** [comment]
Hi @raphaelsulzer this works for me
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then

```py
from vedo import *
np.random.seed(2)
grid1 = Grid().add_gaussian_noise(0.8).triangulate().lw(1)
grid1.celldata['scalar'] = grid1.cell_centers[:,1]
grid2 = grid1.clone().collapse_edges(0.1)
show(grid1, grid2, N=2, axes=1)
```
![Screenshot from 2024-01-08 16-40-30](https://github.com/marcomusy/vedo/assets/32848391/68d186b3-70ce-4189-8205-29dc0e00abd2)

**Comment by raphaelsulzer** [comment]
After updating with `pip install -U git+https://github.com/marcomusy/vedo.git` it works like a charm. I guess I had an old version installed.

Thank you so much for the quick response and for your work on this library in general. It is a really great tool!
