### ISSUE TITLE
distance_to produces error if the point cloud does not contain faces

### ISSUE THREAD

**Issue by baba-yaga** [marcomusy/vedo#1012]
```
p = Point((0,0,1))
C=Cube()
p.distance_to(C)

```
works fine. But 
```
pc = Points(C.vertices)
p.distance_to(pc)

```
produces error:
    pcloud.point_locator.SetDataSet(pcloud)
TypeError: SetDataSet argument 1: method requires a VTK object

Making it a mesh by adding an edge (or a face) makes it work again:
```
pm = Mesh([C.vertices, [[0,1]]])
p.distance_to(pm)

```

**Comment by marcomusy** [comment]
Hi, this was already fixed in the master, will be in the next release, just update with
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by baba-yaga** [comment]
Thank you, Marco! The second code is now fixed and gives the correct answer: sqrt(3)*0.5 = 0.8660254

But the third code above (I am adding an edge between points [[-0.5, -0.5, -0.5],
       [-0.5, -0.5,  0.5]] ) gives a wrong value 1.73205081 (the distance should still be sqrt(3)*0.5) and complains
```
2024-01-10 12:12:35.807 ( 136.918s) [          18CF7C]     vtkCellLocator.cxx:737    ERR| vtkCellLocator (0x7fe11f94bf30): No cells to subdivide
2024-01-10 12:12:35.807 ( 136.918s) [          18CF7C]vtkImplicitPolyDataDist:144    ERR| vtkImplicitPolyDataDistance (0x7fe11f950aa0): No polygons to evaluate function!
2024-01-10 12:12:35.807 ( 136.918s) [          18CF7C]vtkImplicitPolyDataDist:144    ERR| vtkImplicitPolyDataDistance (0x7fe11f950aa0): No polygons to evaluate function!

```

**Comment by marcomusy** [comment]
Hi Sergei, you are not creating the mesh correctly! (the second item in the list should be a polygon):
```py
from vedo import *

p = Point((0,0,1))
C = Cube().alpha(0.25).lighting('off')
show(p, C, C.labels("id"),axes=1).close()

p.distance_to(C)
print(p.pointdata["Distance"])

pc = Points(C.vertices)
p.distance_to(pc)
print(p.pointdata["Distance"])

pm = Mesh([C.vertices, [[20,21,23,22]]])
p.distance_to(pm)
print(p.pointdata["Distance"])
```

![Screenshot from 2024-01-10 13-34-02](https://github.com/marcomusy/vedo/assets/32848391/b41af160-545e-4e1a-b8bb-69af7cf6fbcf)

**Comment by baba-yaga** [comment]
Aye... Sorry, Marco!
