### ISSUE TITLE
Feature Request: mesh.show() to not permanently stay in plot

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1013]
It would be nice for mesh.show() to not cause mesh to be rendered in all future plots. Instead I need to write the below several times to be able to visualise and debug multiple meshes:
```
plotter = vedo.Plotter(axes=1)
plotter.show()
```

If mesh.show() could be equivalent and create a copy of the plotter each time, that would be nice.

**Comment by marcomusy** [comment]
Just add `close()` to create a new one, eg
```
from vedo import *
Cube().show().print().close()
Sphere().show().print().close()
```

Context manager also does it:
```
with Plotter() as plt:
    plt.show(Circle())
```

Note that a simple call to `show()` also generates and returns a `Plotter` instance:
```
from vedo import show
print(show(Sphere()))
print(show(Cube(), new=True))
```
