### ISSUE TITLE
Saving slice from volume.slice_plane() as array

### ISSUE THREAD

**Issue by IsabellaPa** [marcomusy/vedo#1018]
Hello,
I found the slice_plane() function and it's amazing! I would like to save the the image on the slicer plane as an array and found that I can do that with arr = vslice.pointdata[0]. The only problem is that I cannot find the according dimensions to reshape the image as the array is returned as a 1D array.
Did I miss the dimensions somewhere or is there a way to get them? Sure it's easy when the plane is not tilted, then I can use the volume dimensions, but as soon as I change the normal to something more adventurous that doesn't work anymore. 

Cheers

**Comment by marcomusy** [comment]
I just added it:

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then

```py
from vedo import *

vol = Volume(dataurl+'embryo.slc')
vol.cmap('Set1_r').alpha([0,0,0.8])

vslice = vol.slice_plane(vol.center(), (0,1,1), autocrop=False).cmap('Set1_r')
# tinv = vslice.transform.compute_inverse()
# vslice.apply_transform(tinv)
# print(vslice.metadata["original_bounds"])

arr = vslice.pointdata[0] # retrieve vertex array data
arr_shape = vslice.metadata["shape"]

img = Image(arr.reshape(arr_shape)).cmap("Set1_r")
# img.write("img.png")

show([[vol, vslice], img], N=2, sharecam=False, axes=1)
```

![Screenshot from 2024-01-15 18-07-53](https://github.com/marcomusy/vedo/assets/32848391/77188526-8803-4793-bc6a-391982cd3588)

**Comment by IsabellaPa** [comment]
Thank you that works great! :)
