### ISSUE TITLE
Abrupt termination when calling plotter.show

### ISSUE THREAD

**Issue by kirilllzaitsev** [marcomusy/vedo#1021]
I'm using `vedo` version 2023.4.6 and the following code works on my local machine:
```
plotter.show(
                pointcloud,
                legend,
                **{'at': 0, 'axes': {'c': 'black', 'xyShift': 0.5, 'numberOfDivisions': 10}, 'title': 'train/sample', 'camera': {'position': (...)}, 'interactive': False, 'resetcam': True, 'elevation': -10}
            )
```
The problem appears when I'm running `vedo` on a remote machine (without display access). The following message is displayed in the console and the application gets shutdown:
```
/opt/miniconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by marcomusy** [comment]
Hi I suggest to upgrade your version! Then check out
https://vedo.embl.es/docs/vedo.html#running-on-a-server

**Comment by kirilllzaitsev** [comment]
Thanks a lot, I missed the `/etc/rc.local` part of the server instructions. Worked like a charm in my `2023.4.6` version
