### ISSUE TITLE
smooth shading

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#1024]
When vis. mesh with uv coords, the smooth shading cannot work: `vedo SMPL_A.obj`

[SMPL_A.txt](https://github.com/marcomusy/vedo/files/13959894/SMPL_A.txt)
[SMPL_A0.txt](https://github.com/marcomusy/vedo/files/13959895/SMPL_A0.txt)

**Comment by marcomusy** [comment]
You need to compute_normals().

**Comment by LogWell** [comment]
Yes, neither of these two meshes have normals saved, but why can `SMPL_A0` be displayed smoothly but `SMPL_A` cannot?

**Comment by marcomusy** [comment]
**In your first message this is not explained at all, please explain the issue clearly.**

In 
```
vedo.mesh.Mesh at (0x2ffb5a0)                                              
file name     : /home/musy/Downloads/SMPL_A0.obj
elements      : vertices=6,890 polygons=13,776 lines=0
```

whereas in
```
vedo.mesh.Mesh at (0x5e15160)                                              
file name     : /home/musy/Downloads/SMPL_A.obj
elements      : vertices=41,328 polygons=13,776 lines=0
```

so there all vertices are duplicated in SMPL_A.

Removing them allows the phong algorithm to work:
```py
Mesh("SMPL_A.obj").clean().phong().show()
```
![Screenshot from 2024-01-19 18-38-50](https://github.com/marcomusy/vedo/assets/32848391/6290c6fb-255b-405b-af05-22f994f8b730)
