### ISSUE TITLE
Error Thrown: Process finished with exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by Zud0taki** [marcomusy/vedo#1028]
Hello,

I am facing a problem with vedo, when I try to load a Mesh via the library like so: 

`msh = Mesh(random_pick).rotate_x(x).rotate_y(y).rotate_z(z).pos(0, 0, -380)`

The only message that is given is: Process finished with exit code -1073740791 (0xC0000409)
I have researched that error and it seems to connect to PyQT but my code crashes when loading the mesh so I think it has to come from somewhere else.

Sometimes it throws that error, sometimes it works. I am just at a loss right now. The `random_pick` variable is an .obj-file from a list of these. Here sometimes for example number 4 of the list works and sometimes it doesn´t.

I would appreciate pointers or any help you can provide.

Greetings

**Comment by marcomusy** [comment]
Uhm what is the error message?

**Comment by Zud0taki** [comment]
I am sorry I forgot to mention in the issue. The only error thrown is: Process finished with exit code -1073740791 (0xC0000409)
There is no specific error which is odd.

I should have clarified earlier... have you ever heard of that message before in connection with vedo?

**Comment by marcomusy** [comment]
Not really... Are you doing it on a server by any chance?
what is the output of command line
```
vedo
```
should give some info about your specs.

**Comment by Zud0taki** [comment]
The output for `vedo` is the following:

vedo version                : 2024.5.0+dev26  (https://vedo.embl.es)
vtk version                   : 9.3.0
numpy version            : 1.24.4
python version           : 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
python interpreter      : C:\Users\Enihcam\anaconda3\envs\SynthHumans\python.exe
installation point        : C:\Users\Enihcam\anaconda3\envs\SynthHumans\lib\site-packages\vedo
system                        : Windows 10 nt AMD64

I am running the package in one of my projects in a venv (Python 3.8 on a Win10 System

**Comment by marcomusy** [comment]
If sometimes it works and sometimes it doesnt it must due to some instability of your system and/or the vtk library itself.. 
I don't see anything problematic in your specs .. sorry! :(
Maybe you can write a minimalistic test to see if it crashes like
```py
from vedo import Mesh
for file in files:
    m = Mesh(file)
    print(m)
```

**Comment by Zud0taki** [comment]
Thanks for the input! 
I will try to use the minimalistic test and see, if it makes any difference.

If that works I think I will try to upgrade to PyQt6.
I will update you on whether either of the approaches resolves the problem. Just in case in the future someone else runs into this problem.

**Comment by Zud0taki** [comment]
Ok so I tried both options and neither of them resolved the issue. I tried an older version of my project and there it works.
I will dig through the code of older versions of my project and test with them, see what I changed and maybe its obvious.
I´ll keep trying and if I find a solution I`ll reopen this issue. Thank you for your time.

**Comment by marcomusy** [comment]
No problem - let me know how it goes :)
