### ISSUE TITLE
Plotter's mode=1 strange behaviour

### ISSUE THREAD

**Issue by sergei9838** [marcomusy/vedo#1046]
### Discussed in https://github.com/marcomusy/vedo/discussions/1045

<div type='discussions-op-text'>

<sup>Originally posted by **sergei9838** February  8, 2024</sup>
Hi, Marco,
This is what I have discovered in the development version of vedo.

mode=1 option in Plotter is supposed to be rotating the actor. Rotate the cube in the renderer somehow and save the camera position:
```
from vedo import *
C = Cube()
cam1 = show(C, mode=1).camera
close()

```
Get the camera position:
```
cam1.GetPosition()
# (0.0, 0.0, 3.3460652149512318)
```
The camera is in the default position, as expected for mode=1. The view of the cube is as expected too:

```
show(C).close()
```
<img width="475" alt="Screenshot 2024-02-08 at 22 15 39" src="https://github.com/marcomusy/vedo/assets/105316522/451c2074-809c-4219-b256-c29d46f61480">

BUT: the vertices of the cube are at the initial position!

```
C.vertices
# array([[-0.5, -0.5, -0.5],
#       [-0.5, -0.5,  0.5],
#       [-0.5,  0.5, -0.5],
...
```
So what figure does the plotter show then?! 
Moreover, let's clone the cube and display both:

```
C1 = C.clone()
show(C, C1.c("yellow"), axes=1).close()

```
<img width="414" alt="Screenshot 2024-02-08 at 22 25 37" src="https://github.com/marcomusy/vedo/assets/105316522/2e6e2fd4-0924-4fc5-9db4-8bb4a9be0be2">

So C1 is the correct copy of the initial cube. And not of the rotated C shown in the plotter.
This does not happen in vedo 2023.4.6: `C.points()` show rotated positions.
I am puzzled )
Cheers,
Sergei</div>

**Comment by marcomusy** [comment]
Resolved in #1045
