### ISSUE TITLE
*(Question) Not an Issue

### ISSUE THREAD

**Issue by vladyslavnUA** [marcomusy/vedo#1048]
Hi Marco, 

First of all, thank you so much for developing and continuing to maintain this library, the features it yields are astonishing. I have a question (wasn't able to find it anywhere in the documentation/no previous issue correlates) regarding the very useful options to interact with the 3D scene (the keyboard commands -> A, K, L, etc.), is there any way to hide them/toggle them off? (For the less experienced users of the program that might get confused if they accidently click a button on their keyboard). 

Thank you!

**Comment by marcomusy** [comment]
Thanks Vladyslav! Yes, you can add in your script:
```py
from vedo import settings
...
settings.enable_default_keyboard_callbacks = False
settings.enable_default_mouse_callbacks = False
...
```

**Comment by vladyslavnUA** [comment]
Thank you so much, Marco!
