### ISSUE TITLE
slice method returns None for mesh from stl model

### ISSUE THREAD

**Issue by dan-david** [marcomusy/vedo#1051]
vedo: v2014.5.1
python: v3.9.18

Why the slice method returns a `None` object for the _.stl_ model?

```python
from vedo import *
msh = Mesh("sample.stl").alpha(0.1).wireframe()
mslice = msh.slice(normal=[0,1,0], origin=[0,0,0])
mslice.c('purple5')
show(msh, mslice, axes=1)
```

I am using the following file:

[sample.stl.zip](https://github.com/marcomusy/vedo/files/14302198/sample.stl.zip)

Thanks!

**Comment by marcomusy** [comment]
It returns None because the plane is not hitting the mesh, this works:
```py
from vedo import *
msh = Mesh("sample.stl").alpha(0.1).wireframe()
mslice = msh.slice(normal=[0,1,0], origin=[0,2,0])
mslice.c('purple5')
show(msh, mslice, axes=1)
```
![Screenshot from 2024-02-15 21-50-45](https://github.com/marcomusy/vedo/assets/32848391/7e8a0c7a-9a6b-406d-bde9-a833e78b3feb)
