### ISSUE TITLE
Resolving a non-watertight mesh

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1052]
[data.zip](https://github.com/marcomusy/vedo/files/14303549/data.zip)

As an extension of #1043, I want to use the floor at the top and bottom, as well as the walls. I get the top floor by shifting the floor determined in 1043 to the max height of the walls.

The goal is to have an Assembly that when joined together, is watertight so boolean operations can then be done.

It looks like the inner wall is both higher and lower than the outer wall (hence the `cut_with_plane`). Interestingly, `cut_with_plane` ADDS vertices without `extrude` beforehand (with `clean` ran beforehand).

It looks like there may be an issue when handling 3dp and onwards but I'm unsure if that's related.

This is what I have so far:

```
import numpy as np
import vedo

base = vedo.load("base.vtk")
internal = vedo.load("internal.vtk")
walls = vedo.load("walls.vtk")

*_, zmin, zmax = base.bounds()

walls = walls.extrude(-10)
walls = walls.extrude(10)
walls = walls.cut_with_plane(origin=(0, 0, zmax), normal=(0, 0, 1), invert=True)
walls = walls.cut_with_plane(origin=(0, 0, zmin), normal=(0, 0, 1), invert=False)


def get_floor(base, internal):
    base_boundaries = get_bottom_surface(boundaries=base.copy().boundaries())
    internal_boundaries = get_bottom_surface(boundaries=internal.copy().boundaries())

    # Set to 0 to enable triangulation to work correctly with VTK
    temp_base_z = base_boundaries.vertices.copy()[:, -1]
    temp_internal_z = internal_boundaries.vertices.copy()[:, -1]
    base_boundaries.vertices[:, -1] = 0.0
    internal_boundaries.vertices[:, -1] = 0.0
    floor = vedo.merge(base_boundaries, internal_boundaries).triangulate()
    floor.vertices[:, -1] = np.hstack([temp_base_z, temp_internal_z])

    floor.clean()
    return floor


def get_bottom_surface(boundaries: vedo.Mesh) -> vedo.Mesh:
    *_, zmin, zmax = boundaries.bounds()
    above_midheight_cond = boundaries.vertices[:, -1] > (zmax + zmin) / 2
    boundaries = boundaries.delete_cells_by_point_index(np.nonzero(above_midheight_cond)[0])
    # boundaries = boundaries.triangulate()
    return boundaries


bottom_floor = get_floor(base=base.copy(), internal=internal.copy())
# top_floor = get_floor(base=base.copy().rotate_y(180), internal=internal.copy().rotate_y(180))
# top_floor = top_floor.rotate_y(180)
top_floor = bottom_floor.copy().shift(dz=zmax - zmin).clean()  # TODO closed ends up being false :(

bottom_floor.name = "bottom_floor"
top_floor.name = "top_floor"
walls.name = "walls"
thickened_base = vedo.Assembly(walls.clean(), bottom_floor.clean(), top_floor.clean())

m = vedo.merge(thickened_base.copy().unpack()).triangulate().join().clean()

if not m.is_manifold():
    print("NOT MANIFOLD")
if not m.is_closed():
    print("NOT CLOSED")
if m.npoints != m.copy().non_manifold_faces().clean().npoints:
    print("NON MANIFOLD FACES EXIST")
```

Note that extruding upwards from the floor to the height of the wall and attaching the mesh that's above also is not closed.

**Comment by marcomusy** [comment]
You need to use `merge()` not Assembly to "fuse" the separate parts into one single watertight mesh.
Keep in mind that the one of the 2 floors might need to be flipped (with eg `reverse()`) for the surface to be consistent.

**Comment by JeffreyWardman** [comment]
Isn't that what's being done in the line after?

`m = vedo.merge(thickened_base.copy().unpack()).triangulate().join().clean()`

**Comment by marcomusy** [comment]
Consider:

```py
from vedo import *

walls = Mesh("walls.vtk")

boundaries = walls.boundaries().split()
# show(boundaries, N=len(boundaries)).close()

# enforce coplanarity
e, i = boundaries[0], boundaries[2]
e.vertices[:, -1] = 0.
i.vertices[:, -1] = 0.

m = merge(e.join().join_segments(), i.join().join_segments())
m.triangulate().c("blue9")
mex = m.extrude(5, cap=True).pickable(True)

ismanyfold = mex.is_manifold()
isclosed = mex.is_closed()
printc("is manifold:", ismanyfold, c=ismanyfold)
printc("is closed:", isclosed, c=isclosed)

show(walls, mex, axes=1).close()
```
![Screenshot from 2024-02-18 17-29-42](https://github.com/marcomusy/vedo/assets/32848391/c93d9ca4-733c-45b9-aa33-a029515f12f1)

dont forget to reset the z-values to the desired ones.

PS: do not use `load` (that is for multiple files, and you don't get auto-completion)

**Comment by JeffreyWardman** [comment]
I'm confused why it doesn't work without extrude. For instance, why doesn't this work?

```
import vedo

walls = vedo.Mesh("walls.vtk")
boundaries = walls.boundaries().split()

# enforce coplanarity
e, i = boundaries[0], boundaries[2]
e_vertices_original = e.vertices.copy()[:, -1]
i_vertices_original = i.vertices.copy()[:, -1]
e.vertices[:, -1] = 0.0
i.vertices[:, -1] = 0.0
top_floor = vedo.merge(e.join().join_segments(), i.join().join_segments())
top_floor.triangulate().c("blue9")
top_floor.vertices[:, -1] = np.hstack([e_vertices_original, i_vertices_original])

# enforce coplanarity
f, g = boundaries[1], boundaries[3]
f_vertices_original = f.vertices.copy()[:, -1]
g_vertices_original = g.vertices.copy()[:, -1]
f.vertices[:, -1] = 0.0
g.vertices[:, -1] = 0.0

bottom_floor = vedo.merge(f.join().join_segments(), g.join().join_segments())
bottom_floor.triangulate().c("blue9")
bottom_floor.vertices[:, -1] = np.hstack([f_vertices_original, g_vertices_original])

m = vedo.merge(top_floor, bottom_floor, walls).join().clean()
```


If I follow your approach, remove one of the floors and do `vedo.merge(mesh_thickened, mex_no_cover, top_floor).join().is_closed()` outputs False. Where `mex_no_cover = top_floor.extrude(-(zmax - zmin), cap=False).pickable(True)`.

**Comment by JeffreyWardman** [comment]
(While what you said works, reattaching it to a mesh via vedo.join then stops it from being closed). If you'd like the mesh data I can send it privately.

**Comment by JeffreyWardman** [comment]
An example where if you have a rectangle and remove one floor, then do vedo.merge(floor, rectangle_remainder) and show that it's closed would be helpful. Something resolving this:

```
rect = vedo.Rectangle().extrude(1).delete_cells([0,1])
boundaries = rect.boundaries()
floor = boundaries.triangulate()
joint = vedo.merge(floor, rect)

assert joint.is_closed()
vedo.show(joint, axes=1).close()
```

**Comment by JeffreyWardman** [comment]
SOLVED: Realised that I forgot to clean the duplicate points. Adding `joint.clean()` resolved my issue and then allowed me to produce a watertight mesh.

**Comment by marcomusy** [comment]
hi @JeffreyWardman good to hear that - sorry for not being very helpful on this! :)

**Comment by JeffreyWardman** [comment]
You helped tremendously! boundaries().split() reduced the compute time significantly as it avoided my initial approach to delete cells by index. It also simplified the code by a lot. Thanks!
