### ISSUE TITLE
Error Encountered While Decimating Mesh with Default Function (Quadric)

### ISSUE THREAD

**Issue by maleehahassan** [marcomusy/vedo#1055]
Hi @marcomusy ,

I hope you remember me from the POLBIAS 2023 conference in Dresden last year. I work with @jo-mueller and @haesleinhuepf.

I am encountering an error when attempting to decimate my mesh using the default function, which employs quadric decimation. Below is the traceback of the error:

AttributeError: 'vtkmodules.vtkFiltersCore.vtkQuadricDecimation' object has no attribute 'MapPointDataOn'

This happened yesterday after I upgraded to the latest version of Vedo. Below is the line of code that throws the error:

decimated_mesh = mesh.decimate(n=10000)

Any insights or suggestions on resolving this issue would be greatly appreciated.

Best,
Maleeha

**Comment by drew-parsons** [comment]
This error also shows up in the tests for vedo 2024.5.1
```
$ pytest-3 tests/common/test_core1.py 
================================================================================================================================== test session starts ===================================================================================================================================
platform linux -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0
rootdir: /projects/vedo
plugins: remotedata-0.4.1, asyncio-0.20.3, hypothesis-6.98.4, filter-subpackage-0.1.2, doctestplus-1.1.0, flaky-3.7.0, arraydiff-0.6.1, xvfb-3.0.0, astropy-0.11.0, mpi-0.6, astropy-header-0.2.2, cov-4.1.0, mock-3.12.0, openfiles-0.5.0
asyncio: mode=Mode.STRICT
collected 0 items / 1 error                                                                                                                                                                                                                                                              

========================================================================================================================================= ERRORS =========================================================================================================================================
______________________________________________________________________________________________________________________ ERROR collecting tests/common/test_core1.py _______________________________________________________________________________________________________________________
tests/common/test_core1.py:273: in <module>
    s2 = sphere.clone().decimate(0.2)
/usr/lib/python3/dist-packages/vedo/mesh.py:1080: in decimate
    decimate.MapPointDataOn()
E   AttributeError: 'vtkmodules.vtkFiltersCore.vtkQuadricDecimation' object has no attribute 'MapPointDataOn'
```

**Comment by marcomusy** [comment]
Ouch.. that is because VTK 9.1 doesn't have `MapPointDataOn()` method, which is new in vtk 9.3

@maleehahassan try:
```
pip install vtk -U
```

@drew-parsons I will add a check for vtk version in `mesh.decimate()`

**Comment by maleehahassan** [comment]
@marcomusy does not help :(

**Comment by marcomusy** [comment]
What is the output of 
```bash
vedo -i
```

**Comment by maleehahassan** [comment]
vedo version   : 2024.5.1
vtk version       : 9.2.5
numpy version     : 1.26.4
python version    : 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)]
python interpreter: C:\Users\maha810d\AppData\Local\miniforge3\envs\my_thes_env\python.exe
installation point: C:\Users\maha810d\AppData\Local\miniforge3\envs\my_thes_env\lib\site-p
system            : Windows 10 nt AMD64
💡 No input files? Try:
 vedo https://vedo.embl.es/examples/data/panther.stl.gz

**Comment by marcomusy** [comment]
OK. Try:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by jo-mueller** [comment]
@maleehahassan consider closing the issue if it's solved ;)
