### ISSUE TITLE
Get transformation matrix for orienting plane to xy

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1068]
I'm trying to find a simple solution within vedo to rotate multiple objects such that a plane lays on the XY plane at z=0.

This is my current approach:
```
rotated_mesh = mesh.copy().reorient(initaxis=-plane.normal, newaxis=(0, 0, 1), xyplane=True)
rotated_plane = plane.copy().reorient(initaxis=-plane.normal, newaxis=(0, 0, 1), xyplane=True)
rotated_point = point.copy().reorient(initaxis=-plane.normal, newaxis=(0, 0, 1), xyplane=True)
```

However, the point doesn't seem to rotate. Once this orientation is done, I want to rotate again such that the point is facing the -Y direction but that is simple to solve as it's just `rotate_z(angle)`.

**Comment by JeffreyWardman** [comment]
Making the point a `vedo.Line` with the below seems to resolve it, although not the most straightforward approach:

```
line = vedo.Line(p0=point.vertices.copy()[0], p1=plane.box().pos())
rotated_line = line.copy().reorient(initaxis=-plane.normal, newaxis=(0, 0, 1), xyplane=True)
rotated_point = vedo.Point(rotated_line.vertices[0].copy())
```

**Comment by marcomusy** [comment]
What about this:

```py
from vedo import *

plane = Plane().rotate_x(20)
mesh = Cube().c("green5").alpha(0.2)
point = Point([3, 2, 1]).c("blue5")

T = LinearTransform().reorient(plane.normal, (0, 0, 1), xyplane=True)
rotated_mesh = mesh.copy().apply_transform(T)
rotated_point = point.copy().apply_transform(T)
rotated_plane = plane.copy().apply_transform(T)

show(rotated_mesh, rotated_plane, rotated_point, Point(), axes=1)
```

**Comment by JeffreyWardman** [comment]
Once again, absolutely insane turn around! Tested it out and works like a charm. Much cleaner approach too. I knew my initial approach could be simplified but wasn't sure how!

**Comment by marcomusy** [comment]
I'm glad you like this solution, keep in mind that any operation or combination of transformations is stored in `.transform` property for all vedo objects (when applicable). Eg
```
print(rotated_mesh.transform)
```
should yield T.

**Comment by JeffreyWardman** [comment]
Great, thanks for the recommendation. I've been using vedo for almost a year now and still learn something new everyday :smile:
