### ISSUE TITLE
change assembly obj to mesh

### ISSUE THREAD

**Issue by priyabiswas12** [marcomusy/vedo#1069]
Hello,

May i know how to change an assemply object to a mesh object and save it? 
Thank you

**Comment by marcomusy** [comment]
Try
```py
merge(my_assembly.unpack()).write("mymesh.stl")
```

**Comment by JeffreyWardman** [comment]
I'd recommend adding `.clean()` after merging in case there are overlapping points as well :)

```
vedo.merge(my_assembly.unpack()).clean().write("mymesh.stl")
```

**Comment by priyabiswas12** [comment]
Ah okay,  thank you so much!
