### ISSUE TITLE
add_scalarbar3d not working anymore

### ISSUE THREAD

**Issue by ilsemeijer99** [marcomusy/vedo#1071]
Hi marcomusy!

I was using the code below to create a 3d mesh with categorical colorbar. However, the colorbar does not appear anymore. Any thoughts what might have caused this?

lut_table = [(1, 1, 1, "Septal"), (2, 2, 1, "Inferior"), (3, 3, 1, "Lateral"), (4, 6, 1, "Anterior"), (5, 5, 1, "Posterior")] 
lut = build_lut(lut_table)
vmesh.cmap(lut, c, on="cells").add_scalarbar3d(title="Regions", categories=lut_table)

Thanks! Ilse

**Comment by marcomusy** [comment]
Hi! After:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

Try out this example:
```py
import vedo

vedo.settings.default_font = "Kanopus"

lut_table = [
    #value, color, alpha, category_label
    ( 1, 'cyan',       1, "Cond 1"),
    ( 2, 'skyblue',    1, "Cond 2"),
    ( 3, 'dodgerblue', 1, "Cond 3"),
    ( 4, 'blue',       1, "Cond 4"),
    ( 5, 'k5',         1, "Over 5"),
    ( 6, 'green5',     1, "Layer 6"),
    ( 7, 'green7',     1, "Layer 7"),
    ( 8, 'red5',       1, "Layer 8"),
    ( 9, 'red6',       1, "Layer 9"),
    (10, 'yellow5',    1, "Layer10"),
    (11, 'yellow7',    1, "Layer11"), 
    (12, 'orange5',    1, "Layer12"),
    (13, 'orange4',    1, "Layer13"),  
    (14, 'orange3',    1, "Layer14"),
    (15, 'orange2',    1, "Layer15"),
]
lut = vedo.build_lut(lut_table)

tet = vedo.TetMesh(vedo.dataurl + "earth_model.vtu")
msh = tet.tomesh(shrink=0.95, fill=True)
msh.cmap(lut, "cell_scalars", on="cells")

# Use clone2d() to create a 2D scalarbar from the 3D one
msh.add_scalarbar3d(categories=lut_table)
msh.scalarbar = msh.scalarbar.clone2d("center-right", size=0.15)

vedo.show(msh, axes=1, viewup="z").close()
```

![Screenshot from 2024-03-10 18-39-14](https://github.com/marcomusy/vedo/assets/32848391/ec4a39dc-d553-4964-ad09-868b7a5ff11b)

Let me know if you can reproduce it!

**Comment by ilsemeijer99** [comment]
So sorry to waste your time! I can reproduce it and realized afterwards that I add the mesh to the plot before I add the scalarbar to the mesh. My bad! Thank you
