### ISSUE TITLE
Close the console

### ISSUE THREAD

**Issue by nimei66** [marcomusy/vedo#1072]
Hi
There's a question that's been bothering me for a long time.
To build the exe, set console=True Otherwise, an error will be reported。{AttributeError: 'NoneType' object has no attribute 'flush'}
There is no setting to turn off the console?

**Comment by marcomusy** [comment]
Sorry i'm not very familiar with that... you should ask this question to `pyinstaller` support.

**Comment by nimei66** [comment]
> 抱歉，我对此不太熟悉...您应该提出这个问题来`pyinstaller`支持。

Thank you for your reply. I'll think of something else

**Comment by nimei66** [comment]
> 抱歉，我对此不太熟悉...您应该提出这个问题来`pyinstaller`支持。

I think I found the problem. What is it
File "vedo init_.py", line 119, in <module AttributeError: 'NoneType' object has no attribute 'flush'

logger = logging.getLogger("vedo")

_chsh = logging.StreamHandler()
**if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")**
_chsh.flush = sys.stdout.flush
_chsh.setLevel(logging.DEBUG)
_chsh.setFormatter(_LoggingCustomFormatter())
logger.addHandler(_chsh)
logger.setLevel(logging.INFO)

Just add the above code

**Comment by marcomusy** [comment]
OK! Thank you very much!
