### ISSUE TITLE
Feature request: extract_largest_regions(n)

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1074]
I'd like to extract the n largest regions.

**Comment by marcomusy** [comment]
Isn't that `.split()` ?

**Comment by JeffreyWardman** [comment]
Is split guaranteed to be done by the number of points though? I didn't want to rely on this unless that's the case. Or is split ordering done via nearest distance of a submesh to top left position for instance?

**Comment by marcomusy** [comment]
Uhm no, split is done by connectivity and ordering by surface area.
https://vedo.embl.es/autodocs/content/vedo/vedo/mesh.html#Mesh.split

**Comment by JeffreyWardman** [comment]
Ah, thanks for linking the documentation. I overlooked `maxdepth=1000` and `sort_by_area=True`. Thanks!

**Comment by JeffreyWardman** [comment]
Hi @marcomusy, reopening this issue. I have an example where for some reason, the second mesh contains multiple pieces. I want to get the first and second largest meshes (after accommodating for the removal of their pieces).

**Comment by marcomusy** [comment]
Sorry I don't understand the question..

**Comment by JeffreyWardman** [comment]
My bad. So I have a large mesh that is a combination of others. I run `mesh.split()` and it outputs 3 submeshes: A, B, C.

B actually contains 5 blobs. The main blob and some junk.

I guess what I'm asking for is an arg to run the below:

```
outputs = [submesh.split() for submesh in mesh.split()]
# Reorder now again based on npoints for all split submeshes
```

**Comment by marcomusy** [comment]
..this is a python question :)
https://stackoverflow.com/questions/20183069/how-to-sort-multidimensional-array-by-column

`mesh.npoints` will give you the number of points.

**Comment by JeffreyWardman** [comment]
Great idea. Thanks!
