### ISSUE TITLE
How does compute_clustering work?

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1075]
Does `compute_clustering` use normals and other `pointdata` information? It seems to be ignoring the x axis for the example I'm investigating and I believe this is a possible reason.

If it's just points being used, the radius doesn't seem to work regardless if set to 1 for an object with a bounding box of e.g. [-20, 20, -20, 20, -20, 20]. Is it a fraction?

My ideal clustering approach:
- Points only
- radius is a hard-coded distance

**Comment by marcomusy** [comment]
I don´t understand what you mean.. it uses no pointdata information nor normals, the way it works is this
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.compute_clustering

**Comment by JeffreyWardman** [comment]
Ah thanks. So it uses just positional coordinates as inputs. Not sure why I was getting clusters on my U-shaped object where both ends of the U had the same labels (as though the x-axis wasn't considered).
