### ISSUE TITLE
Loses transformation information in assembly

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1076]
When indexing the assembly, it loses transformations. Is there a way to retain this information when collecting items from the assembly?

```
assembly2 = vedo.Assembly({"box": vedo.Box()})
assembly2.bounds()  # (-0.5, 0.5, -1.0, 1.0, -1.5, 1.5)
a = assembly2.shift(dx=5)
a.bounds()  # (4.5, 5.5, -1.0, 1.0, -1.5, 1.5)
a["box"].bounds()  # array([-0.5,  0.5, -1. ,  1. , -1.5,  1.5], dtype=float32)
```

**Comment by marcomusy** [comment]
Hi. the `assembly2.transform` will give you that!
Note that `.shift()` is an in-place operation.

**Comment by JeffreyWardman** [comment]
What I'm after is to have the content of the assembly be manipulated collectively, rather than having to use apply_transform for each individually.

**Comment by marcomusy** [comment]
There cannot be an automatic way because that would mess up the assembly:

```py
from vedo import *
asse = Assembly({"sphere1": Sphere(), "sphere2": Sphere(c="blue5").shift(dx=3)})
asse.shift(dx=5)
# note that this will screw up the assembly (unless you clone() the objects):
# for key in [obj.name for obj in asse.objects]:
#     asse[key].apply_transform(asse.transform)
print(asse.xbounds())
print(asse["sphere2"].xbounds())
show(asse, axes=1)
```

![Screenshot from 2024-03-25 23-44-38](https://github.com/marcomusy/vedo/assets/32848391/1e74ff63-b465-4b7e-bdf7-a87cb5596330)

**Comment by JeffreyWardman** [comment]
No worries. In that case, I'll close the issue. The information here will be enough for someone wanting to apply the same approach in the future.
