### ISSUE TITLE
mesh.split() is not sorted correctly for boundary lines

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1078]
`mesh.boundaries().split()` does not sort the submeshes by area as expected.

In this case, it could be done by total edge length.

**Comment by marcomusy** [comment]
True but it would be a bit tricky to implement.. You can try with
https://vedo.embl.es/autodocs/content/vedo/vedo/mesh.html#Mesh.join_segments
and summing up the segnents distances?
