### ISSUE TITLE
Term colors changed after printing a DataFrame with a Mesh

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#1080]
Hi Marco!

This may be something very simple to solve, but i've been a bit stuck with it for a while...

If i put mesh objects in a pandas df column and i print it on the python repl, all the background color of my texts get changed to green from that point forward. Here is a screenshot:

![image](https://github.com/marcomusy/vedo/assets/93348782/a4361fb1-c7f1-4ee3-8ef7-94ece46a3b24)

Any idea what could it be or how could it be changed?

Thanks in advance!

**Comment by marcomusy** [comment]
Hi @ManuGraiph I guess something going wrong with stripping the string.... two options:

```py
# disable printc
vedo.settings.enable_print_color = False

# or add this after printing the dataframe:
print(vedo.colors.reset)
```

**Comment by ManuGraiph** [comment]
Went for the first one, it worked perfect (i don't like in general the color output).

Thanks a lot!

Manu
