### ISSUE TITLE
Bug: mesh.thumbnail hangs in docker container

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1086]
I cannot run a pipeline in a docker container that takes a screenshot of the mesh.

**Comment by marcomusy** [comment]
Have you started the xvffb?
https://vedo.embl.es/autodocs/content/vedo/vedo/settings.html#Settings.start_xvfb

**Comment by JeffreyWardman** [comment]
```
starting xvfb (can take a minute) .../usr/bin/Xvfb
 xvfb started.
2024-04-08 02:23:28.772 (   4.613s) [    7F1F70AE9000]vtkXOpenGLRenderWindow.:456    ERR| vtkXOpenGLRenderWindow (0x55a69c64b300): bad X server connection. DISPLAY=99.0. Aborting.
```

It looks like running it in VSCode in debug mode doesn't work because set_xvfb.sh does not store the information in the debugger when it's run as a prelaunch task

**Comment by marcomusy** [comment]
to be honest I'm not familiar enough with the xvbf machinery ... :(
