### ISSUE TITLE
Compute outward normals for pointdata

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#1087]
Hi @marcomusy ,

I am trying to compute normals of point data.

 ```
       pts = Points(self.get_pcloud_edge)
        msh = pts.generate_delaunay2d(mode='xy').c('w').lc('o').lw(1)
        msh.add_ids()
        out = msh.compute_normals(points=True, cells=False).clean().linewidth(0.1).dataset
        print(out)
        print(type((msh.pointdata["Normals"])))
        print(msh.pointdata["Normals"])
        # print(msh.vertex_normals)
        vplt.show(pts, out) #, msh.pointdata["Normals"]

 ```

![image](https://github.com/marcomusy/vedo/assets/29662579/c2b2ba0e-9744-42d2-8ac5-d7a7997cbae4)

I am not sure how to visualize the outward normals of just the vertices. I see the entire surface.

![image](https://github.com/marcomusy/vedo/assets/29662579/e4078c22-40c7-4fec-9e53-edc64630d12e)

Could you please help?

I am looking for the normals just at the vertices (please see e.g. below)

![image](https://github.com/marcomusy/vedo/assets/29662579/815c0962-a35c-4b77-9f1f-8ae098ffd27a)

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

The issue was due to the arrow size.

I scaled it down and it's ok now.

`arrows = Arrows(pts, pts + normals * scale).c('red5')
`
There are a few more issues, I will post here again

**Comment by marcomusy** [comment]
Ok good ! I close the issue for the moment then.
