### ISSUE TITLE
Exit without error reporting, when no NVIDIA driver is available

### ISSUE THREAD

**Issue by youka-sar** [marcomusy/vedo#1088]
Earlier I tried vedo demo code.

```
import vedo
vedo.Cone().show(axes=1)
```

It just gives me a black window, and the python exits unexpectedly without an error report.
After a long error checking, I found it was because the Nivida driver was missing.

I think there should be a `assert` about the GPU driver, in case of an abnormal exit.

**Comment by marcomusy** [comment]
Hi thanks for reporting - unfortunately this seems a problem from the upstream VTK library and we cannot do much downstream in vedo i'm afraid...

**Comment by youka-sar** [comment]
> Hi thanks for reporting - unfortunately this seems a problem from the upstream VTK library and we cannot do much downstream in vedo i'm afraid...

OK get it. Thank you for your reply!
