### ISSUE TITLE
jupyter notebook kernal keeps crashing after calling plt.show()

### ISSUE THREAD

**Issue by priyabiswas12** [marcomusy/vedo#1090]
Hello, 

I have used the following code to display my mesh, and although it shows it, once i close the window, the kernal hangs and I always need to keep restarting it. Do you know why this is happening? Thank you

settings.default_backend = 'vtk'
plt = Plotter(axes=1)
plt.add(new_pt)
plt.show(u_tooth,l_tooth)
plt.interactive()
plt.close()

**Comment by marcomusy** [comment]
try to use the dev version with
```
pip install -U git+https://github.com/marcomusy/vedo.git
```
