### ISSUE TITLE
Reusing intersection points

### ISSUE THREAD

**Issue by IsabellaPa** [marcomusy/vedo#1096]
Hello,
I have a 3D mesh and a plane. I can draw the intersection line by using the contour returned by intersect_with and it works lovely.
But I want to reuse the contour for further calculations. When I try to turn the contour into a Tube(contour.vertices) the sequence of points is not always correct and I tend to get a spiderweb like Tube instead of a circle. 
I could alternatively use a Mesh version but mesh= Mesh([contour.vertices, contour.lines]) obviously doesn't draw any triangles. 

In this specific case I want to layer different closed intersection lines and determine their common area.

Any help is appreciated!

**Comment by marcomusy** [comment]
Hello, have a look at the methods `.join()`
https://vedo.embl.es/autodocs/content/vedo/vedo.html?search=join

**Comment by IsabellaPa** [comment]
Thank you, that was exactly was I was searching for!
