### ISSUE TITLE
Rounded Line generates warning, displays incorrectly

### ISSUE THREAD

**Issue by PinkMushroom** [marcomusy/vedo#1102]
python3.10/site-packages/vedo/shapes.py:971: RuntimeWarning: invalid value encountered in arccos

![Screenshot from 2024-04-22 19-15-03](https://github.com/marcomusy/vedo/assets/12112452/ce765d9b-6c3a-4876-bdeb-d17d655ed59b)

In the image , the RoundedLine is on the left and a Line is on the right.

I will look closely at the data and see if I can figure out why it may be doing this.

---
Caught it in the act:

> 
> u [116.42391429   0.           0.        ] v [240.26706128   0.           0.        ]
> np.dot(u,v) 27972.831748915956 du 116.42391428905057 dv 240.2670612797524
> np.dot(u,v)/du/dv 1.0000000000000002

Because the argument is > 1.0 np.arccos returns a 'nan' causing the rounded line to be drawn incorrectly.

**Comment by marcomusy** [comment]
Thanks @PinkMushroom feel free to make PR to fix the issue the way you think it's best!

**Comment by PinkMushroom** [comment]
Done. @marcomusy . I sure hope it worked.
I'm a noobie when it comes to making PRs...
