### ISSUE TITLE
Feature: Determine visible cells from point

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1107]
I want to determine which mesh points/cells are visible from the z/-z direction. It looks like this is possible with VTK:
https://learnopengl.com/Guest-Articles/2021/Scene/Frustum-Culling
https://vtk.org/doc/nightly/html/classvtkFrustumCoverageCuller.html

**Comment by ZiguoAtGitHub** [comment]
Hi Jeffrey, 
Take a look on https://github.com/marcomusy/vedo/discussions/904, maybe there is what you want.

**Comment by marcomusy** [comment]
In addition to Ziguo's you can try something like this
```py
from vedo import *

s = Ellipsoid().rotate_y(30).lw(1)

plt = Plotter(interactive=False)
cam_opts = dict(pos=(0,0,5), focal_point=(0,0,0))
plt.show(s, camera=cam_opts)

visc = CellCenters(s).add_ids().visible_points()
print(visc)
print(visc.pointdata["PointID"])
plt.add(visc)
# plt.add(visc.labels("PointID"), s.labels("cellid").c("r"))

plt.interactive().close()
```

**Comment by JeffreyWardman** [comment]
Great, thank you both!
