### ISSUE TITLE
How to disable these buttons shortcut in vedo ?

### ISSUE THREAD

**Issue by OhmPuchiss** [marcomusy/vedo#1110]
I want to use the keyboard to control other function defined by myself how do I close and stop these function from interacting ? 

![image](https://github.com/marcomusy/vedo/assets/71385431/d9b5c318-abc1-4a00-9c97-ca60dfa85764)

**Comment by ZiguoAtGitHub** [comment]
Hi,
you can take a look at class Settings in API document.
If I am not wrong, the setting is enable_default_keyboard_callbacks= False.

**Comment by OhmPuchiss** [comment]
That works Thanks
