### ISSUE TITLE
Rounding when saving/reading an obj

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#1119]
Hi Marco!

I'm having an issue when saving/reading a mesh as an obj file..

When i create a mesh and i save it as a .obj file and then i read it again, at some point, the vertices coordinates are getting "internally" converted to scientific notation and rounded to the 4th decimal place (I'm not entirely sure if this behaviour is in numpy, vedo, or both). I've tried converting the points to int32, int64, etc. before saving the obj, but the result is the same.

This causes some issues when the order of coordinates is more than 4-5, like, when working with UTM coordinates.

Any idea how to prevent this?

Thanks in advance!
Manu

**Comment by marcomusy** [comment]
Hi - I just increased the precision in the dev version.

**Comment by ManuGraiph** [comment]
Thanks a lot!

I ended up "patching" it myself writing a new write function for .obj. I'm gonna leave it here in case it's useful for anyone.

```
def writeObj(mesh,filename):
    with open(filename, 'w') as f:
        for k in range(len(mesh.points())):
            a = list(mesh.points()[k,:])
            line = "v "+str(a[0])+" "+str(a[1])+" "+str(a[2])
            f.write(line+'\n')
        for k in range(len(mesh.cells)):
            a = list(mesh.cells[k])
            line = "f "+str(a[0])+" "+str(a[1])+" "+str(a[2])
            f.write(line+'\n')
```

So it just writes the array values as text.

Thanks again!

**Comment by ManuGraiph** [comment]
Sorry, i'm gonna use this post and ask another thing, so i don't open another one. I'm not sure if i asked this before, i apologize if i did, but, it's possible to create quad elements in vedo? (an element with 4 verts. instead of 3)

**Comment by marcomusy** [comment]
Yes sure in fact any polygon. You need to mind about coplanatity.

**Comment by ManuGraiph** [comment]
Great! Thanks a lot! I think at some point i tried but failed and after that i basically kept making quads combining 2 triangles.

Thanks!
