### ISSUE TITLE
Smooth boundary line of a mesh

### ISSUE THREAD

**Issue by sean-d-zydex** [marcomusy/vedo#1121]
Hi, I'm looking to smooth just the boundary line of a mesh (not the entire mesh), I was wondering if there's any functionality in vedo to achieve this? Thanks!

**Comment by marcomusy** [comment]
Yes although that is kind of a dangerous operation... Have a look at  method smooth_mls2d().

**Comment by marcomusy** [comment]
Sorry i meant smooth_mls1d() after using boundaries().
