### ISSUE TITLE
How to open two seperate windows in vedo ?

### ISSUE THREAD

**Issue by OhmPuchiss** [marcomusy/vedo#1122]
I want to open two vedo windows.

**Comment by ZiguoAtGitHub** [comment]
Creating two instances of Plotter?
Maybe like this:

plt1=Plotter()
plt2=Plotter()
...
plt1.show(,,interactive=False)
plt2.show(,,interactive=False)

**Comment by OhmPuchiss** [comment]
<img width="742" alt="image" src="https://github.com/marcomusy/vedo/assets/71385431/0cd81b0e-aef9-4823-92e8-7659e5e79d54">
 How to open these two windows ? I want one window to open opencv window and one for vedo. Two windows can communicate with one another.

**Comment by OhmPuchiss** [comment]
Or how to further run the script after the plt.show() is used.

**Comment by marcomusy** [comment]
Try
```
vedo --search multi

vedo --run multiwindows1
vedo --run multiwindows2
```
```
