### ISSUE TITLE
How to show import window in multiple renderer ?

### ISSUE THREAD

**Issue by OhmPuchiss** [marcomusy/vedo#1126]
![image](https://github.com/marcomusy/vedo/assets/71385431/09fe0458-3767-4eaa-b839-13d5fbf5bfbf)
I try to import the windowfrom npz file and I want to show it on the plt.at(1). What should I do ?

**Comment by OhmPuchiss** [comment]
I got it. Use get_mesh and extract it to plt.at(1)

**Comment by OhmPuchiss** [comment]
How to add axis to specific plot like plt.at(1) ?

**Comment by marcomusy** [comment]
You can create an Axes object explicitly and add it to the renderer you like:
```py
axes = Axes(some_mesh)
plt.at(1).add(axes)
plt.show()
```
