### ISSUE TITLE
How to generate mask from surface?

### ISSUE THREAD

**Issue by NeuZhangQiang** [marcomusy/vedo#113]
Hi marcomusy, the vtkplotter is really a very good tool. 

I have a question, how can I obtain the mask from a mesh?

For example, 
```
import numpy as np
from vtkplotter import *

cs = []
for i in range(-10, 10):
    r = 10 / (i * i + 10)
    c = Circle(r=r).wireframe().rotateY(i*5).z(i / 10)
    cs.append(c)

rbs = []
for i in range(len(cs) - 1):
    rb = Ribbon(cs[i], cs[i + 1], res=(200, 5))
    rbs.append(rb)

mesh = merge(rbs)
show([cs, mesh], N=2, axes=1)
```
I want to generate a mask from the mesh. How can I achieve this goal?

In addition, in the above code, the circle is not closed, which make the mesh is not closed. How to generate a closed circle?

**Comment by NeuZhangQiang** [comment]
The "mask" means a volume image in which the intensity is 0 or 1. The 1 means that the pixel is contained in the surface, while 0 means the pixel is not contained in the surface.

**Comment by marcomusy** [comment]
Try:
`pip install -U vtkplotter`

then:
```python
import numpy as np
from vtkplotter import *

cs = []
for i in range(-10, 10):
    r = 10 / (i * i + 10)
    c = Circle(r=r).wireframe().rotateY(i*5).z(i / 10)
    cs.append(c)

rbs = []
for i in range(len(cs) - 1):
    rb = Ribbon(cs[i], cs[i + 1], closed=True, res=(200, 5))
    rbs.append(rb)

mesh = merge(rbs).clean().cap()

vol = mesh2Volume(mesh, spacing=(0.02, 0.02, 0.02))
vol.alpha([0,0.5]).c('blue')

show([cs, mesh, vol], N=3, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/77413007-fb90b500-6dbe-11ea-8e9a-ac42e62cd01f.png)

**Comment by NeuZhangQiang** [comment]
Thank you very much.

**Comment by NeuZhangQiang** [comment]
Dear @marcomusy , I still have a little question. After vol = mesh2Volume(mesh, spacing=(0.02, 0.02, 0.02)), we obtain the vol. However, the vol is a Volume variable. How can I get numpy matrix from the volume?

**Comment by NeuZhangQiang** [comment]
Dear @marcomusy, I have a small suggestion for the mesh2Volume function. Can I set the origin for the volume? Actually, those contours are obtained from a image. Thus, the origin of reconstructed volume should be the same as that of image. Thus, I want to set the origin in the volume. 

Currently, I modify the function as:

```
def mesh2Volume(mesh, spacing=(1, 1, 1), origin=None):
    ...
    bounds = pd.GetBounds()
    if origin != None:
        bounds = list(bounds)
        bounds[0] = origin[0]
        bounds[2] = origin[1]
        bounds[4] = origin[2]
    ...
```
Is that correct?

In addition, in the mesh2Volume function, there is a for loop as:
```
    inval = 255
    count = whiteImage.GetNumberOfPoints()
    for i in range(count):
        whiteImage.GetPointData().GetScalars().SetTuple1(i, inval)
```
What does it means? Assign 255 for all whiteImage? I find it would cost lots of time. Why don't you use the numpy_20_vtk function?

**Comment by marcomusy** [comment]
Hi @NeuZhangQiang sorry I completely forgot to get back to you on this!
about your first point: you can set or reset the origin of the Volume after creation with `vol.origin([x,y,z])`
I will change the for loop with the corresponding numpy_to_vtk method
I will also add your post processing lines in the `volume.getDataArray()` method
Thanks for drawing the attention to it!
