### ISSUE TITLE
Axisymmetric mesh with extrude

### ISSUE THREAD

**Issue by IsabellaPa** [marcomusy/vedo#1133]
Hello Marco,

I wanted to make an axisymmetric mesh and tried to use the extrude function for it, as recommended by you. I am now wondering how to 'sweep' the shape that I want to use as an outline (in my case it's a spline). If I set a single angle the outline is rotated but the connection between the two outlines is straight which then obviously doesn't lead to round meshes.
I searched for an example but couldn't find one, sorry if I missed it.

![image](https://github.com/marcomusy/vedo/assets/130475090/e35ca7ad-e23d-41a4-bd0c-b872bee8399f)
```py
from vedo import *
import vedo

plotter = Plotter(axes = 2)
points= [[0,0,15],[1,0,15],[2,0,14.5],[2.7,0,10],[1,0,1],[0.3,0,0],[0,0,0],
         [-0.3,0,0],[-0.5,0,0.2],[-2.7,0,10],[-2,0,14.5],[-1,0,15],[-0,0,15]]

spline = Spline(points)
mslices= [s.triangulate() for s in spline.join_segments()]
slice = merge(mslices).color('red')

extruded = slice.extrude(zshift=0.0,rotation=90,dr=0,cap=True,res=1).color('grey')
extruded2 = slice.extrude(zshift=0.0,rotation=170,dr=0,cap=True,res=1).color('green')

plotter.show(extruded, extruded2, slice)
```

**Comment by IsabellaPa** [comment]
Okay, so I have a spline that encloses this area:
 ![image](https://github.com/marcomusy/vedo/assets/130475090/291376b8-4f29-4135-9b62-81b71c1625bb)

I want to rotate the spline so I get an axisymmetrical 3D body, like this:
![image](https://github.com/marcomusy/vedo/assets/130475090/263698f9-aaa6-467d-a578-dba98bffdee7)

The last image was made with 

`
extruded_bodys= []
for i in range(180):
    angle = i
    extruded = slice.extrude(zshift=0.0,rotation=angle,dr=0,cap=False,res=1).color('grey')
    extruded_bodys.append(extruded)

extruded_body= merge(extruded_bodys)
`
Which is not very elegant and doesn't lead to a smooth surface ( which you will only see when you rotate it a bit).

**Comment by marcomusy** [comment]
I think the problem is ill-posed because prescribing what must happen on x-z plane is not sufficient to specify completely what must happen along the x-coordinate.
In other words there is more than 1 possible surface (in fact infinite) that have the same slice in the zx plane.

Two possible approaches:
- start with a sphere or ellipsoid and morph it ( see examples `examples/advanced/warp*.py`)
- connect the left and right spline with an interpolation of splines, something like:

```py
from vedo import *

plotter = Plotter(axes=1)
points1 = np.array([
    [0, 0, 15],
    [1, 0, 15],
    [2, 0, 14.5],
    [2.7, 0, 10],
    [1, 0, 1],
    [0.3, 0, 0],
    [0, 0, 0],
])
points2 = np.array(list(reversed([
    [0, 0, 0],
    [-0.3, 0, 0],
    [-0.5, 0, 0.2],
    [-2.7, 0, 10],
    [-2, 0, 14.5],
    [-1, 0, 15],
    [0, 0, 15],
])))

n = 100
spline1 = Spline(points1, res=n).c("r")
spline2 = Spline(points2, res=n).c("b")
spline1_pts = spline1.coordinates
spline2_pts = spline2.coordinates

alphas = np.linspace(0, np.pi, int(n/2))

splines = []
for alpha in alphas:
    pts = []
    for i in range(n):
        p, q = spline1_pts[i], spline2_pts[i]
        d = p[0]
        x = np.cos(alpha) * d 
        y = np.sin(alpha) * d
        pts.append([x, y, p[2]])
    splines.append(Spline(pts, res=n))

plotter.show(
    spline1, 
    Points(points1, r=10, c="r"),
    spline2,
    Points(points2, r=10, c="b"),
    splines,
)
```


![image](https://github.com/marcomusy/vedo/assets/32848391/f7248626-66c7-4e4b-92ea-ebc437ff6637)

This is only a starting point... You then would connect the individual slices with `Ribbon()`.

I though suggest to follow the first suggestion.

**Comment by IsabellaPa** [comment]
Okay, that makes sense. Thank you! :) I will try it out
