### ISSUE TITLE
Data type discrepancies between numpy and VTK

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1137]
Vedo primarily uses two key libraries:
- VTK, which uses doubles by default, and
- numpy, which uses float32 by default.

This discrepancy occurs in several points in the codebase. It'd be good to standardise the data type.

**Comment by marcomusy** [comment]
Hi, actually i'm not completely sure that that is the case.. e.g.
> from vedo import *
> Sphere().vertices.dtype
dtype('float32')

**Comment by JeffreyWardman** [comment]
It doesn't occur with the bunny.obj dummy example but it does occur for high fidelity meshes. For example: https://www.artec3d.com/3d-models/buggy. 

```
import vedo
import numpy as np

path = "Buggy.stl"

mesh = vedo.Mesh(path)
a = mesh.center_of_mass()
b = mesh.vertices.copy()
b.mean(axis=0)
c = b.astype(np.float64)
c.mean(axis=0)

```

# PLY:
#    A: array([-160.66834098,   23.57756032,  -87.22478219])
#    B: array([-160.66664 ,   23.578615,  -87.15967 ], dtype=float32)
#    C: array([-160.66834098,   23.57756032,  -87.22478219])
# Difference between B and A/C is floating point precision.

Note that vedo's definition of center of mass is actually just the mean for x, y and z (another topic).

As you can see from the above, computations are done in float64 in VTK but the data type outputted is float32. Therefore, any usage of numpy without explicitly setting the data type may result in this issue.

**Comment by JeffreyWardman** [comment]
There are several areas within the codebase where numpy is used within functions, with np.array(x) or np.array().float(), without specifying the data type. I've had to accommodate for this difference in a few areas. There are a few spots in my codebase where I round to 6 dp for comparisons and recently realised it's due to this issue. 

For instance:
- https://github.com/marcomusy/vedo/blob/db0c0bfdd9ce3116bb9baec0e254b557e1bc241a/vedo/utils.py#L791
- Vertices being converted to float32 here: https://github.com/marcomusy/vedo/blob/db0c0bfdd9ce3116bb9baec0e254b557e1bc241a/vedo/file_io.py#L1435
- Possibly here too https://github.com/marcomusy/vedo/blob/db0c0bfdd9ce3116bb9baec0e254b557e1bc241a/vedo/backends.py#L203

**Comment by marcomusy** [comment]
Hi, the `vtk2numpy()` function is not overriding the input type so it looks to me it's doing the right thing(?)

The other ones in file_io and backends are rather innocuous.

Note that you should not compare floats to floats and doubles to doubles directly without declaring a tolerance.

**Comment by JeffreyWardman** [comment]
Fair. It isn't explicitly mentioned for users developing with vedo that VTK uses doubles by default. Could maybe throw something into the getting started section of the documents but regardless, will close this issue.

**Comment by JeffreyWardman** [comment]
This is still causing me problems. Here's a useful example:

```
a = vedo.Mesh([np.array([[1.5146416416146161461, 2.464164164164161461254, 3145315134513465161441]], dtype=np.float64), [], []])
print(a.vertices)
# array([[1.5146416e+00, 2.4641643e+00, 3.1453151e+21]], dtype=float32)
```

**Comment by marcomusy** [comment]
I see why that happens. Would this be an acceptable solution?
```py
settings.force_single_precision_points = False

a = vedo.Mesh([np.array([[1.5146416416146161461, 2.464164164164161461254, 3.145315134513465161441]], dtype=np.float64), [], []])
print(a.vertices.dtype)
# float64
```

**Comment by JeffreyWardman** [comment]
Yep, that's perfect! Thanks!

**Comment by sean-d-zydex** [comment]
Hi, currently running into a problem with this solution:
`from vedo import Axes, Box, show
settings.force_single_precision_points = False
box = Box(pos=(1,2,3), length=8, width=9, height=7).alpha(0.1)
axs = Axes(box, c='k')`
Running this gives: "TypeError: Could not find a suitable VTK type for float16". From what I can tell it looks like a problem with the Axes -- specifically it seems that the mesh for the fonts has its vertices in Float16 which now don't get converted into Float32 anymore.

**Comment by marcomusy** [comment]
Thanks for spotting the bug, This should now be fixed in master.
