### ISSUE TITLE
vtkplotter.show() not working on Jupyter Notebook

### ISSUE THREAD

**Issue by gyanendra-d-tripathi** [marcomusy/vedo#114]
I am doing a robotics project in UC Berkeley. I am trying to use vtkplotter.show() for plotting a 3-d mesh and some points in 3-d. Everything is working well except vtkplotter.show() does not show anything at all.

I did research in various link and imported k3d still it does not work. Can you please help?

**Comment by marcomusy** [comment]
Hi, have you tried the options:
```python
from vtkplotter import *

embedWindow('k3d') # or panel, itkwidgets, or False

# my code 
```

**Comment by gyanendra-d-tripathi** [comment]
Thanks for your response. I tried with embedWindow('k3d')
It does not produce any output but jupyter Notebook throws an error '-xsrf' argument missing from POST

**Comment by marcomusy** [comment]
oh... this sounds very mysterious .. what operative system are you using?

**Comment by gyanendra-d-tripathi** [comment]
I am using windows 10

**Comment by marcomusy** [comment]
I will see if I can reproduce this on windows..

**Comment by gyanendra-d-tripathi** [comment]
thanks a lot. I am using Jupyter Notebook on Windows10 laptop.

Regards

Gyanendra
