### ISSUE TITLE
How to load multiple Volumes in 1 3D interactive plane

### ISSUE THREAD

**Issue by ivishalanand** [marcomusy/vedo#1141]
I have multiple .nii files of different parts of body ( from a CT scan segmentation job) and I want to load all of them in a 3D interactive plane at their respective positions. How can I achieve that. I am also looking at how can I get something out so that there can be a toggle to hide or show each individual .nii files based on some selector.

I am able to do it in 3D Slicer, but not sure how I can combine multiple .nii files in one 3D interactive view with toggle to turn on and off each volume?
<img width="719" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/f88d2b53-7622-41dc-9e94-4e8ece6ef939">

These are the format of the .nii files for different parts
<img width="554" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/cdfa6d57-ecb9-4be5-ba60-b1031d428944">

**Comment by ivishalanand** [comment]
I think this works
```
volumes = []
volumes.append(path_a)
volumes.append(path_b)
volumes.append(path_c)
show(*volumes, axes=1, interactive=True)
```

**Comment by ivishalanand** [comment]
Is there a way I can interactively toggle each segment ( nifti file) on the composite interactive display??

**Comment by marcomusy** [comment]
> Is there a way I can interactively toggle each segment ( nifti file) on the composite interactive display out of the box??

Try:

```py
from vedo import *

settings.default_font = "Antares"
settings.enable_default_keyboard_callbacks = False

def func(event):
    global toggled

    if event.keypress == "z":
        if event.object:
            toggled = event.object
        if toggled:
            toggled.toggle()
        plt.render()

    elif event.keypress == "q":
        plt.close()
        exit()

toggled = None
vol1 = Volume(dataurl+"embryo.slc")
vol2 = Volume(dataurl+"embryo.tif").spacing([1,1,1])

plt = Plotter(axes=1)
plt.add_callback("key press", func)
plt.add(vol1, vol2, "Press z to toggle visibility of volumes on hovering")
plt.show()
```

![image](https://github.com/marcomusy/vedo/assets/32848391/f6fcf6de-4b55-45f2-a47d-7f51d8084367)

**Comment by ivishalanand** [comment]
Thanks @marcomusy, this works!

I'm wondering if there's a way to have buttons on the side representing each volume, allowing users to click and toggle them on and off, instead of having to hover and click.
