### ISSUE TITLE
Segmentation and Visualization of CT Scan Structures Based on Density in Vedo

### ISSUE THREAD

**Issue by ivishalanand** [marcomusy/vedo#1142]
Hi @marcomusy 
I am new to Vedo and have found it to be a very powerful tool for visualization. However, I have a specific visualisation probelem that I am trying to solve with Vedo and would appreciate some guidance.

# Objective
I need to segment CT scans and visualize objects based on their density or brightness levels. Specifically, I aim to identify and group similar organs, glands, blood vessels, nerves, and fat based on their intensity values in NIFTI files for each slice. My goal is to effectively segment and cluster these structures to provide clear and meaningful visualizations.

Based on the clustering/segmentation based on thresholds etc. I want to be able to segment organs, glands, blood vessels, nerves, and fat. Since most of them have a different intensity on CT scan.

### IsoSurfaceBrowser
- Useful for visualizing bones and skin.
- Struggles to clearly depict structures in between these two, such as soft tissues, organs, and glands.
Example images:
<img width="720" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/0b2b7198-76c6-4e96-84cf-b2c84d9f27f2">
<img width="702" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/d4617471-4754-48f6-b06b-1b7bafcb52bb">

### RayCastPlotter
- Effective for visualizing bone structures.
- Example image:
<img width="679" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/9dab1261-04ad-474e-b9b1-a0e9476b748c">

### RayCastPlotter with Composite Setting
- Provides limited details of organs beneath the skin.
- Example image:
<img width="613" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/f7d32877-de44-4b43-9bf6-b0b36f82b3b6">

## Desired Outcome
I am looking for a method to:

### Group Similar Density Sections:
- Automatically cluster similar density regions together to represent different anatomical structures.
- Use the intensity values to segment organs, glands, blood vessels, nerves, and fat.

# Questions
-What would be the best practices in Vedo for implementing such a clustering / segmentation approach?
-Are there any existing tools or methods within Vedo that can help achieve this objective more efficiently?
-Can you provide examples or documentation that might help in understanding how to apply these techniques within Vedo?

[Find the link of the Ct scan .nii.gz file HERE for testing purpose.
](https://drive.google.com/file/d/1PDUcozsWbQm_Xyx_INQEmW-qhqua0KLH/view?usp=sharing)

**Comment by marcomusy** [comment]
Thanks for the clear explanation of the issue.
Unfortunately the task is not a trivial one at all if by segmentation you mean assigning labels to spatially separated regions of voxels which may have similar scalar value. Or you already have such a labeling/segmentation (maybe in the form of different files for different structures?)
If you still have to work out the segmentation I would definitely look into [3D Slicer](https://www.slicer.org/) first.

> -What would be the best practices in Vedo for implementing such a clustering / segmentation approach? 

> -Are there any existing tools or methods within Vedo that can help achieve this objective more efficiently? 

> -Can you provide examples or documentation that might help in understanding how to apply these techniques within Vedo?


A trivial way to segment a volume would be the one based on the scalar value.
I suggest you look at examples:
```
examples/volumetric/colorize_volume.py
examples/volumetric/read_volume1.py
examples/volumetric/interpolate_volume.py
```

**Comment by ivishalanand** [comment]
At this point, I don't want to label anything specifically. I just want to separate regions of voxels that have similar scalar values. Let's say we choose a scalar value of S and a threshold of ±s. For a preliminary test, I want to plot the 3D representation of all volumes that have a scalar value within S±s.  ( assuming that similar organs/nerves/ glands will have their different S and s.  values

Also I saw some compute_clustering() function that can be done via vedo. Is there any way I can get these S values by some clustering algorithm already implemented vedo?

> If you still have to work out the segmentation I would definitely look into [3D Slicer](https://www.slicer.org/) first.

- I did look up 3d slicer, and was able to get to get the segmentation parts via some AI model. But the problem with that is its still not precision perfect and the edges may be smoothened which doesn't give very good insights. It can give a good insight about the overall rough approximated segmentation, But for my use case, the precision of exactly where one organ meets another or where any blood vessels touch something else is imp. this info is lost in Ai predicted stuff.

I therefore came through vedo, which doesn't loose much info while modeling in 3D. 
here is my experience with 3D Slcier for my case. Its not very accurate in AI modeling
<img width="584" alt="image" src="https://github.com/marcomusy/vedo/assets/23634159/9a6a9055-9d2a-48dd-bf9d-4e4547c81d28">

**Comment by marcomusy** [comment]
> For a preliminary test, I want to plot the 3D representation of all volumes that have a scalar value within S±s. ( assuming that similar organs/nerves/ glands will have their different S and s. values

Sorry for the late reply (i'm on a conference this week). 
In principle that should be very easy, you should be able to do it by thresholding (creating a volume that has only pass a specific value and setting all the rest to zero (or any other value).
The method is called `threshold()` and `examples/volumetric/interpolate_volume.py` shows how to use it.

**Comment by ivishalanand** [comment]
Thanks! :)
