### ISSUE TITLE
Issue with `mask` Function Example and Request for Assistance with `hide_voxels()` Function

### ISSUE THREAD

**Issue by ivishalanand** [marcomusy/vedo#1146]
The example provided in the `mask` function seems to be not working. Here is the error I encountered while trying the example script:

````
Traceback (most recent call last):
  File "/Users/vishalanand/Desktop/ThirdEyeVision/ML/visualisation/thresholding.py", line 10, in <module>
    vol = Volume(data_matrix, mapper='gpu').cmap(['white', 'b', 'g', 'r'])
TypeError: Volume.__init__() got an unexpected keyword argument 'mapper'
````

### Current `mask` Function

```python
def mask(self, data) -> Self:
    """
    Mask a volume visualization with a binary value.
    Needs to specify keyword mapper='gpu'.

    Example:
    ```python
        from vedo import np, Volume, show
        data_matrix = np.zeros([75, 75, 75], dtype=np.uint8)
        # all voxels have value zero except:
        data_matrix[0:35,   0:35,  0:35] = 1
        data_matrix[35:55, 35:55, 35:55] = 2
        data_matrix[55:74, 55:74, 55:74] = 3
        vol = Volume(data_matrix, c=['white','b','g','r'], mapper='gpu')
        data_mask = np.zeros_like(data_matrix)
        data_mask[10:65, 10:45, 20:75] = 1
        vol.mask(data_mask)
        show(vol, axes=1).close()
    ```
    See also:
        `volume.hide_voxels()`
    """
    mask = vedo.Volume(data.astype(np.uint8))
    try:
        self.mapper.SetMaskTypeToBinary()
        self.mapper.SetMaskInput(mask.dataset)
    except AttributeError:
        vedo.logger.error("volume.mask() must create the volume with Volume(..., mapper='gpu')")
    return self
```

### Issue

Can you help in understanding how to use the `mask` function properly?

Thank you!
```

**Comment by ivishalanand** [comment]
I think for the second  `hide_voxels()` part i managed to figure out how to do it. Do let me know if there is a better way to do it.
```
from vedo import Points, show, Volume, dataurl
import numpy as np

# Load the volume data and apply a color map
vol = Volume(dataurl + "embryo.slc").cmap("gold")

# Function to get all voxel IDs within the volume bounds
def get_all_voxel_ids(vol):
    dims = vol.dimensions()  # Get the dimensions of the volume
    print("Volume dimensions:", dims)
    voxel_ids = []
    
    # Iterate through each voxel coordinate in the volume
    for i in range(dims[0]):
        for j in range(dims[1]):
            for k in range(dims[2]):
                voxel_id = vol.get_point_from_ijk([i, j, k])
                voxel_ids.append(voxel_id)
    
    return voxel_ids

# Get all voxel IDs
voxel_ids = list(set(get_all_voxel_ids(vol)))

# Hide half of the voxels in the volume
vol.hide_voxels(voxel_ids[:int(len(voxel_ids) / 2)])

# Display the volume with axes
show(vol, axes=1).close()
```

**Comment by ivishalanand** [comment]
Sure, here's a revised version of your request with code examples for clarity:

### Problem Statement

Is there a way to pass another smaller volume `v` and hide that from a bigger volume `V`?
So,
- `V` = Bigger Volume
- `v` = Smaller Volume (which is inside the bigger volume)

How can I:
1. Show `V - v` (everything in `V` except the overlapping regions with `v`).
2. Show the inverse, `V & v` (only the overlapping regions between `V` and `v`).

Also, is there a way to know the scalar value at a particular voxel given its voxel ID? For example, `voxel_id = vol.get_point_from_ijk([i, j, k])`.

**Comment by marcomusy** [comment]
What about this:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then

```py

from vedo import *
from vedo.pyplot import histogram


def set_mask_by_thresholds(thresholds):
    vol_arrc = np.zeros_like(vol_arr, dtype=np.uint8)
    vol_arrc[(vol_arr > thresholds[0]) & (vol_arr < thresholds[1])] = 1
    vol.mask(vol_arrc)

def slider1(w, e):
    if slid1.value > slid2.value:
        slid1.value = slid2.value
    set_mask_by_thresholds([slid1.value, slid2.value])

def slider2(w, e):
    if slid2.value < slid1.value:
        slid2.value = slid1.value
    set_mask_by_thresholds([slid1.value, slid2.value])


vol = Volume("data/ct.nii")
vol.mapper = "gpu"
vol.cmap("rainbow").alpha([0, 0, 0, 0.1, 0.2, 0.3, 0.4, 0.8, 1])
vol_arr = vol.tonumpy()

histo = histogram(vol, bins=25, c="rainbow", logscale=True, ytitle="")
histo = histo.clone2d(size=0.5)

plt = Plotter(axes=7)
rng = vol.scalar_range()

slid2 = plt.add_slider(
    slider2,
    xmin=rng[0],
    xmax=rng[1],
    value=rng[1],
    slider_length=0.02,
    slider_width=0.06,
    alpha=0.75,
    c="red2",
    delayed=True, # update only when mouse is released
)
slid1 = plt.add_slider(
    slider1,
    xmin=rng[0],
    xmax=rng[1],
    value=rng[0],
    slider_length=0.01,
    slider_width=0.05,
    alpha=0.75,
    tube_width=0.0015,
    c="blue2",
    delayed=True,
)

plt.show(vol, histo)
plt.close()
```

![image](https://github.com/marcomusy/vedo/assets/32848391/b618a4ec-8f93-4c8e-afb7-12f78b6f3b95)

**Comment by ivishalanand** [comment]
Thanks @marcomusy  for such a quick fix and being so active with the issues and developing this really useful package. Appreciate all the efforts.

**Comment by ivishalanand** [comment]
Bdw


> Also, is there a way to know the scalar value at a particular voxel given its voxel ID?
>> Yes:
>>https://vedo.embl.es/autodocs/content/vedo/vedo.html?search=get_cell_from_ijk


@marcomusy 
-I think this returns the voxel at that point, and not the scalar value of that voxel at that particular location.
As in the documentation it says [Get the voxel id number at the given ijk coordinates](https://vedo.embl.es/autodocs/content/vedo/vedo/volume.html#Volume.get_cell_from_ijk).
I got a workaround to get the scalar values of the volume at a particular voxel by this method

pts = vol.topoints()
scalars_array = pts.pointdata[0]

and then map this scalars_array to each point

**Comment by ivishalanand** [comment]
However I also got these 2 working 
- Show V - v (everything in V except the overlapping regions with v).
- Show the inverse, V & v (only the overlapping regions between V and v).

Below is the code for showing the overlapping regions between V and v. But its like very rough and non optimised way. But this is best I could do. Do you have any recommendations to make this computation better, I think  liver.topoints() makes it very time taking,.

```
import numpy as np
from vedo import Volume, show
from vedo.applications import IsosurfaceBrowser

# Create the volumes
CT = "CT.nii.gz"
base_path = "DATASET/TCIA-PETCT-DATA/manifest/FDG-PET-CT-Lesions-NIFTI/PETCT_1472967bef"
subject = Volume(f'{base_path}/{CT}')
# liver and subject both have same dimention [391] 
liver = Volume(f'DATASET/TCIA-PETCT-DATA/manifest/FDG-PET-CT-Lesions-SEGMENTATION/PETCT_1472967bef/segmentations-CT/liver.nii.gz') 

# Define the threshold
threshold = 0 #  the voxels where liver is present, the scalar = 1 otherwise 0

# Get the scalar values from liver volume
pts_liver = liver.topoints()
scalars_liver = pts_liver.pointdata[0]

# Determine the points in heart that meet the threshold
points_to_hide = np.where(scalars_liver == threshold)[0]

# Calculate voxel IDs corresponding to these points
def point_to_voxel_id(point_index, dims):
    z = point_index // (dims[0] * dims[1])
    y = (point_index - z * dims[0] * dims[1]) // dims[0]
    x = point_index % dims[0]
    if x >= dims[0] - 1 or y >= dims[1] - 1 or z >= dims[2] - 1:
        return None  # Skip points that do not form a voxel
    return z * (dims[0] - 1) * (dims[1] - 1) + y * (dims[0] - 1) + x

# Get the dimensions of the heart volume
dims = liver.shape
print("Dimensions: ", dims)

# Calculate voxel IDs to hide
voxel_ids_to_hide = [point_to_voxel_id(pt, dims) for pt in points_to_hide if point_to_voxel_id(pt, dims) is not None]

# Hide the corresponding voxels in volume subject
subject_intersection_liver = subject.clone().hide_voxels(voxel_ids_to_hide)

show(liver, subject, subject_intersection_liver, N=3, viewup="z")
```

**Comment by marcomusy** [comment]
> pts = vol.topoints() scalars_array = pts.pointdata[0]
> 
> and then map this scalars_array to each point

maybe easier like this?

```py
vol_arr = vol.tonumpy()
print("vol_arr", vol.shape, vol_arr[210, 210, 297])
```

**Comment by marcomusy** [comment]
> Do you have any recommendations to make this computation better, I think liver.topoints() makes it very time taking,.

It looks to me you don't need hide_voxel() if you can do it simply with mask().

**Comment by ivishalanand** [comment]
Okay, thanks @marcomusy. Appreciate all the help. Closing this !
