### ISSUE TITLE
How to flatten mesh to 2D and get its internal and external boundaries?

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#1147]
The below doesn't work:

```py
import vedo

path = "model.stl"
mesh = vedo.Mesh(path)
v = mesh.vertices
v[:, -1] = 0

boundaries = mesh.boundaries().split()
vedo.show(mesh, mesh.boundaries().c("black"), axes=1).close()
```

Likewise with:
```
mesh = mesh.project_on_plane("z")
```

**Comment by marcomusy** [comment]
Flattening a 3D mesh cannot change the boundaries. 

```py
from vedo import *

path = "data/panther.stl"
mesh = Mesh(path).cut_with_plane().c("white")
v = mesh.vertices
# v[:, -1] = 0

boundaries = mesh.boundaries().split()
pmesh = mesh.clone().project_on_plane("z")
silhouette = pmesh.silhouette([0,0,1]).lw(2)
show(mesh, pmesh, boundaries, silhouette, axes=1).close()
```

![image](https://github.com/marcomusy/vedo/assets/32848391/843ddd02-cfd8-44de-8f88-371a108380c9)

**Comment by JeffreyWardman** [comment]
How would I get the boundaries of pmesh, the projection on the z plane?

**Comment by JeffreyWardman** [comment]
Basically this: https://examples.vtk.org/site/Cxx/PolyData/ExternalContour/ assuming it also contains internal boundaries (e.g. if a cylinder was cut through the middle, creating a hole.

**Comment by marcomusy** [comment]
I dont think that is a very good way of doing it especially if you have other objects in the scene.
Also ai think this is not completely trivial.. this a possible way to go:
```py
from vedo import *

shape = Mesh(dataurl+'bunny.obj').c('blue9', 0.1)
shape.subdivide()

mx = shape.clone().project_on_plane("x")
mx.alpha(1).c("red")

msh = mx.generate_delaunay2d(mode="fit", alpha=0.003)
boundary = msh.boundaries().join().print()

show(shape, msh, boundary, axes=1)
```
<img width="349" alt="Screenshot 2024-06-28 at 00 01 17" src="https://github.com/marcomusy/vedo/assets/32848391/88c54c77-a835-4d84-ab67-38d01a9fad99">

**Comment by JeffreyWardman** [comment]
Hmm that didn't work for my use-case. Projecting on plane is great but I want it to only project the outer boundary. Too much detail gets retained and it essentially looks like canny edges. Is there a way to remove the shading information in the plotter instance when calling the silhouette function?

**Comment by JeffreyWardman** [comment]
Unfortunately this won't be accurate without thin slices, which is quite computationally costly.

**Comment by marcomusy** [comment]
In addtion to what Johannes sugested a possiblity could be to parse all the points in the sihlouette polyline and use `mesh.intersect_with_line(camerapos, meshsilhoupt)`.
If hits more than 1 you remove the cell (in this case a line segment).
