### ISSUE TITLE
How to integrate interactive volume objects on Webpage?

### ISSUE THREAD

**Issue by ivishalanand** [marcomusy/vedo#1151]
I'm looking to render the RayCastPlotter for one of my use cases and have it available as an interactive display on a webpage. Currently, I'm trying to export a sample volume using the `plt.export()` method,it seems that Volume objects can't be rendered on a webpage via this method.

Tried code
```
from vedo import Volume, dataurl
from vedo.applications import RayCastPlotter

# Load Volume data
embryo = Volume(dataurl + "embryo.slc")
embryo.mode(1).cmap("jet")  # change visual properties

# Create a Plotter instance and show
plt = RayCastPlotter(embryo, bg='black', bg2='blackboard', axes=7)
plt.show(viewup="z")
plt.export('raycastplot.x3d', binary=False)
```
Could you provide guidance for rendering RayCastPlotter/ any volume object with interactive sliders on a webpage? Are there any workarounds that would enable this functionality?

**Comment by marcomusy** [comment]
Hi, no that unfortunately is not possible. The upstream VTK relies on a openGL rendering window which is not supported in the browser. The x3d format only supports polygonal mesh objects.
Check out `examples/notebooks/` for alternative backends.
