### ISSUE TITLE
(x,y) coordinate format not working on LegendBox

### ISSUE THREAD

**Issue by GerritFischer** [marcomusy/vedo#1153]
I'm currently trying to work with a legend box and want to set its position to a custom location.
I have noticed that the constructor of the legend box does not accept the ```pos=(x,y)``` format as written in the documentation.
It has do be set manually by running ```lbox.GetPositionCoordinate().SetValue(x,y)```

**Comment by marcomusy** [comment]
Try after

```
pip install -U git+https://github.com/marcomusy/vedo.git
```
