### ISSUE TITLE
Adding item to Group

### ISSUE THREAD

**Issue by smoothumut** [marcomusy/vedo#1161]
Hi Marco, this line of code looks like it needs to be changed

in assembly>Group class

    def __iadd__(self, obj):
        """
        Add an object to the group
        """
        if not vedo.utils.is_sequence(obj):
            obj = [obj]
        for a in obj:
            if a:
                self.AddPart(a)   ### here
        return self
        
needs to be

    def __iadd__(self, obj):
        """
        Add an object to the group
        """
        if not vedo.utils.is_sequence(obj):
            obj = [obj]
        for a in obj:
            if a:
                try:
                    self.AddPart(a.actor)  ### here
                except:
                    self.AddPart(a)
        return self

like in Distance_Tool

If I come across more, I will let you know
Best Regards

**Comment by marcomusy** [comment]
Sure would you mind making a PR?

**Comment by smoothumut** [comment]
Of course I dont mind, but I havent done anything like that before : )
Please let me try and I will let you know...
