### ISSUE TITLE
seg fault on vertex normal and texture indices in obj format to off conversion

### ISSUE THREAD

**Issue by GeraldR101** [marcomusy/vedo#1178]
I need to convert an .obj file to .off format. The file has about 28850 lines of faces that look like this
`f 3879/22/22 3881/23/23 3880/24/24`
On Mac M3 MacOS 14.5 the command `vedo --convert input.obj --to off` gives `Segmentation fault: 11`
When I change all the faces to remove the normals and textures `f 3879 3881 3880` it works. Would like to skip the edit step for all the files I must process.
Awk code to fix this in an obj file:

```
/^f/	{gsub(/\/[0-9]*/, "")}
        {print}
```

Thanks

**Comment by marcomusy** [comment]
Hi, unfortunately this seems to be a problem in the upstream vtk distribution so we cannot do much for it in vedo.

**Comment by GeraldR101** [comment]
Thanks for confirming that. Meanwhile I will use the Awk cod.
