### ISSUE TITLE
Creating and visualising a mesh with more than 2 million points...

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vedo#118]
Hi Marco, 
I just started to use vtkplotter, particularly the functions delaunay2D and recoSurface to create a mesh from a cloud of points. I initially tested both functions in a segment of the object, both  worked fine and I was able to visualise it using Plotter, as described in the examples for both functions. Then I decided to test them creating the whole object which has more than 2 million points (2x10^6) and the delaunay2D function ran and created the mesh but I wasn't able to visualise it with Plotter. Instead it prompted: Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[110.225....
Is Plotter able to plot something with that number of points or am I asking too much?

I was also looking for a way to export the mesh created as a stl or obj to see how it looks using another software, but didn't find a funtion that allowed me to do that. Is there a way I can export that mesh? 

I am using Anaconda, Spyder,  and I installed the last version of vtkplotter a couple of weeks ago.

**Comment by marcomusy** [comment]
Hi Juliana,
try updating with `pip install -U vtkplotter` 
from the output i understand you're using it within a jupyter notebook (?). Does it work if you set
`embedWindow(False)`
or from a normal python script?

Any mesh or point cloud can be exported to a different format simply with 
`mesh.write('file.stl')`
You can also use the bash command:
`vtkplotter-convert afile.obj -to stl`

**Comment by jsanchez679** [comment]
Hi Marco, 
Thanks for your reply. Yes, embedWindow(False) worked!
Now I am struggling with the mesh delaunay2D is creating (I gave up trying to use the recosurface function as it was taking ages to show something, even in the segment of the object, and I couldn't tell how much longer it was going to take). As I said in the previous message, I am trying to create a mesh starting with an array of more than 2 million points, but testing different parameters in the delaunay2D function I see that the mesh created is not creating the surface I expect, but somehow trying to connect in a weird way points on one z-position with some others in another further z-position creating a needle like structure as the one you can see on the next image (mesh in blue) 
![delaunay2D](https://user-images.githubusercontent.com/10684503/77668831-d5fcda80-6f7b-11ea-9c39-fd30e6e595ff.PNG)
The mesh on the left are just the points I would like to mesh together. 

The mesh I am trying to create should look something like this: 
![MeshLab](https://user-images.githubusercontent.com/10684503/77669881-5a039200-6f7d-11ea-9c10-19f310490a68.PNG)

Maybe delaunay2D is not the best funtion to use, but has been the only one that has shown me some results so far with this number of points. I you have any other ideas or suggestions (e.g how to make recoSurface to work..), it would be really appreciated. 

Thanks, Juliana

**Comment by marcomusy** [comment]
Hi - i wouldn't aim at reconstructing directly 2M points!
My suggestion is to use e.g. `cloud.clean(tol=0.01)` to subsample the point cloud to a reasonable number, may in combination with [MLS](https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/advanced/moving_least_squares2D.py). As in this [example](https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/advanced/recosurface.py).
You cannot use delauney2d because it assumed that the geometry can be projected to a 2d plane, which doesnt seem the case for you. Let me know if you need further help.

**Comment by jsanchez679** [comment]
Hi Marco, 
Thanks for your reply. I used both functions you suggested and managed to reduce the number of points from 2M to 70,000 and even to 20,000 depending on the tolerance value used, but know I am struggling to build the mesh using the recoSurface function. The object I am trying to mesh has an inside and an outside wall(not just a single layer) but every time I reconstruc the surface the output is one layer... Is there a way I could tweak the parameters in the function to make it understand that it shouldn't merge the inside and outide walls? In the documentation you have online, one of the parameters one should add is a radius, but in the version of vtkplotter I have installed it just accepts number of bins... so I haven't been able to play with the radius parameter.
This is the result of the cleaning process...
![mslError_tol=0 005](https://user-images.githubusercontent.com/10684503/78650684-2a2a8780-78b7-11ea-9967-cccc09a3e03a.PNG)

This of the smoothing part...
![mslError_tol=0 005 and f=0 01_2](https://user-images.githubusercontent.com/10684503/78650870-6c53c900-78b7-11ea-9919-e997723dc74a.PNG)

And this of the final reconstruction 
![recosurface_tol0 005 and f=0 01](https://user-images.githubusercontent.com/10684503/78650897-75dd3100-78b7-11ea-843d-82271e2e3f39.PNG)
![recosurface_tol0 005 and f=0 01_2](https://user-images.githubusercontent.com/10684503/78650903-770e5e00-78b7-11ea-8bdb-be5cfd4f4d32.PNG)

All suggestions again more than welcome
Thanks in advance 
Juliana

**Comment by marcomusy** [comment]
Hi @jsanchez679 
this is a highly non trivial problem (at least for me..), I would first off consider if having two surfaces is indeed adding useful information to your analysis. If so, I would try something like a 2-step process where you first use the middle surface to separate the point clouds and then apply the above procedure to both and finally merge them with `merge(mesh1,mesh2)`. Consider the following test example:
```python
from vtkplotter import *

# generate test.stl
#s1 = Sphere(res=50).pos(-.5,0,0)
#s2 = Ellipsoid(res=50).rotateZ(80).pos(.5,.5,0)
#sa = booleanOperation(s1, '+', s2).alpha(0.1)
#sb = sa.clone().scale(0.85).addPos([0,0.08,0])
#s = merge(sa,sb).addGaussNoise(0.2).ps(3).clean(tol=0.01).write('test.stl')
#show(sa+sb, s, N=2, axes=1)
#exit()

pcl = load('test.stl').pointSize(2).c('k')

smoothpcl = pcl.clone().smoothMLS2D(radius=0.3).alpha(0.2)
reco = recoSurface(smoothpcl, dims=80, radius=0.3).alpha(0.2)

inpcl = reco.insidePoints(pcl).c('g').alpha(0.2)
oupcl = reco.insidePoints(pcl, invert=True).c('r').alpha(0.2)
print('#in #out:', inpcl.N(), oupcl.N())

show(reco, inpcl, oupcl, axes=1)
```
![Screenshot from 2020-04-16 00-06-47](https://user-images.githubusercontent.com/32848391/79395391-d0425580-7f79-11ea-9b1e-7173ce8e9e3d.png)

**Comment by jsanchez679** [comment]
Hi @marcomusy, 
Thanks for your reply! I'll give it a go and let you know how it goes. 
best wishes, 
Juliana
