### ISSUE TITLE
Touching objects handling in isosurface_discrete

### ISSUE THREAD

**Issue by snownontrace** [marcomusy/vedo#1180]
Thanks for making this wonderful library! I noticed that the mesh generated using isosurface_discrete from a 3D segmented image does not cover the touching objects. As a result, surface area calculation of each labeled object is underestimated. Is there a way to add a feature to enable watertight mesh around each object?

**Comment by marcomusy** [comment]
Thanks! I have just updated the [isosurface2.py example](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/isosurfaces2.py), which should provide the functionality you asked for.

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

![Screenshot from 2024-08-19 22-08-45](https://github.com/user-attachments/assets/29bc717e-bddc-48e7-8902-46d7632100b2)

**Comment by snownontrace** [comment]
Thank you so much for your rapid response! I am puzzled by that in each pair of the touching object, one of them get a flat surface that seems to be from the cap method, while the other one gets an indented concaved surface. For example, between blobs 3 and 10, blob 10 got a flat cap, while blob 3 got a concaved surface. It would be more natural to think the boundary here should be assigned to both blobs. This seems to originate from isosurface_discrete, since the label assignment was already there when I check the mesh with wireframe style (blob 10 had an opening there). 
<img width="317" alt="Screenshot 2024-08-19 171100" src="https://github.com/user-attachments/assets/3ff4a99c-7ca2-49f5-be98-c7403cc94d58">

**Comment by snownontrace** [comment]
When internal_boundaries is set True, the iso_discrete.celldata['BoundaryLabels'] does contain sufficient information for my purpose. Thank you so much!

**Comment by marcomusy** [comment]
That is strange..! Try with this latest dev.

**Comment by snownontrace** [comment]
Hi Marco, thanks so much for the quick update! With the latest dev it no longer errors out, but when the objects rotate, the closest and furthest parts were cut out. In other words, the default depth of view was shallower. See below for a comparison with plotter behavior with vedo-2024.5.2 (left) or vedo-2024.5.2-dev09 (right):
<img width="1363" alt="Screenshot 2024-08-20 at 3 42 00 PM" src="https://github.com/user-attachments/assets/d5972d7b-7e80-47b0-b6af-aba31a217a2d">

**Comment by marcomusy** [comment]
Oh, what if you call
```py
plotter.reset_clipping_range()
```

**Comment by snownontrace** [comment]
I tried adding it right before calling Video, but it remains clipped.
```Python
plotter = Plotter(bg=video_bg, size=video_size, offscreen=True)
plotter.add(msh)
plotter.show()  # important to set the camera at the right position
plotter.zoom(initial_zoom)
plotter.camera.Azimuth(90)
plotter.reset_clipping_range()
video = Video(video_file_name, duration=video_duration, fps=video_fps)
video.action(elevation=(0, 0), azimuth=(-90, 270))
video.close()  # merge all the recorded frames and write to disk
```

**Comment by marcomusy** [comment]
Thanks Shaohe for reporting, I just pushed a change to the `screenshot()` method I hope it fixes the issue.

**Comment by snownontrace** [comment]
Problem solved! Thanks again for fixing this so quickly.
