### ISSUE TITLE
Docs cannot be accessed due to certificate expiration

### ISSUE THREAD

**Issue by fluque1995** [marcomusy/vedo#1188]
HTTPS certificate for https://vedo.embl.es seems to have expired, and HSTS is activated. Due to this fact, documentation is not accessible:

![image](https://github.com/user-attachments/assets/f5b511ca-cf29-46da-a21f-a3f08c966c46)

**Comment by sergei9838** [comment]
Having the same issue when trying to load datafile:
`msh = Mesh(dataurl+'mouse_brain.stl').subdivide()`
`urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:992)>`

**Comment by marcomusy** [comment]
Thanks for reporting, this will be fixed asap!

**Comment by fluque1995** [comment]
Thanks to you for such an amazing library!

**Comment by fluque1995** [comment]
I checked, it is indeed fixed, thanks again!
