### ISSUE TITLE
refining a mesh in only one direction?

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#119]
Is there an easy way to refine a mesh in only a single direction? I need to display stresses in a beam that vary only along the x-axis. As the stresses vary quickly I want to add more geometry, but only in the x-direction:

![afbeelding](https://user-images.githubusercontent.com/34062862/77658388-eb233a80-6f76-11ea-9637-74cbcc78d929.png)

**Comment by marcomusy** [comment]
You may create a surface mesh with:
```python
from vtkplotter import CubicGrid

m = CubicGrid(n=(50,10,10), spacing=(0.04,0.1,0.1))#.triangulate()
m.lw(1).alpha(1).show()
```
![image](https://user-images.githubusercontent.com/32848391/77664749-f67a6400-6f7e-11ea-895d-c7f3289abdbe.png)
