### ISSUE TITLE
Reading DXF files.

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#1203]
Hi Marco!

Sorry if i asked this before, but, it's possible to read 2d/3d meshes from a dxf file directly into vedo?

I'm currently using `ezdxf` and manually converting it into a `vedo` mesh, but if it could be read directly, it'd be great!

Thanks in advance!

**Comment by marcomusy** [comment]
Hi @ManuGraiph no worries, if you have an example of how to you this conversion and the dxf file is not binary, in principle it could be implemeted.

**Comment by ManuGraiph** [comment]
Uhm, well, this method i'm using:

`   dxf = ezdxf.readfile(file)
    msp = dxf.modelspace()
    top = dim(np.array(msp))[0]
    verts = [item for sublist in list(msp) for item in sublist]
    verts = [i if len(i)==3 else i[0:3] for i in verts]
    faces = [f(i) for i in range(top) for f in (f1,f2)]
    mesh = vd.Mesh([verts, faces])`
    
But my question was precisely pointing to see if there was a direct method "faster" than this.

**Comment by ManuGraiph** [comment]
Thanks! Thought there may have been a way to read it directly, it's ok.

Thanks Marco!
