### ISSUE TITLE
remove method of Plotter

### ISSUE THREAD

**Issue by Poisoned** [marcomusy/vedo#1208]
```python
plt = Plotter(N=2)
s = Sphere()
plt.add(s, at=0)
plt.add(s, at=1)
plt.remove(s, at=1)
```
When I remove s from renderer at index 1, the remove method will clear the `plt.objects`. But another s is in the actors list of the renderer at index 0.

Then I show this test and the camera is not reset. But if I remove another Sphere at index 1, the parameter `resetcam=False` is useless.
```python
...
plt.remove(s, at=0)
plt.show(resetcam=False, at=1).interactive()
```
Eh, I didn't find the reason, the relation between "resetcam" and "sharecam" of Plotter is puzzling.

**Comment by Poisoned** [comment]
Reset_camera method or resetcam parameter of Plotter is not for all actors in it's instance, but the actors of the first renderer.
```python
plt = vedo.Plotter(N=2, sharecam=True)
s1 = vedo.Sphere()
s2 = vedo.Sphere(pos=(30, 30, 30))
plt.add(s1, at=0)
plt.add(s1, at=1)
plt.show().interactive()
```
When sharecam is True, the Sphere at index 1 is out of the window.

**Comment by marcomusy** [comment]
It's a bit confusing indeed because it's complicated to address many use cases (jupyter etc) so show() is doing a number of extra things... Note that `sharecam` means that all renderers share the same camera - so it's normal that in 
```py
import vedo
plt = vedo.Plotter(N=2, sharecam=True)
s1 = vedo.Cube()
s2 = vedo.Sphere(pos=(30, 30, 30)).lw(1)
plt.at(0).add(s1, vedo.Axes(s1)).reset_camera()
plt.at(1).add(s2, vedo.Axes(s2))
plt.show().interactive().close()
```
one of the 2 goes out of the window! (click and press r to manually reset the cam). Also `at=...` does not shift the focus of the current renderer, maybe using `.at().` is more convenient.

if you want to skip the show() this is maybe an option:
```py


import vedo
plt = vedo.Plotter(N=2, sharecam=False)
s1 = vedo.Cube()
s2 = vedo.Sphere(pos=(30, 30, 30)).lw(1)
plt.at(0).add(s1, vedo.Axes(s1)).reset_camera().add_renderer_frame(lw=5)
plt.at(1).add(s2, vedo.Axes(s2)).reset_camera().add_renderer_frame(lw=5)
plt.render().interactive().close()
```

**Comment by Poisoned** [comment]
Nice! Take notes. 
Method ```at``` changes the current renderer.

Thank you!

**Comment by Poisoned** [comment]
> ```python
> plt = Plotter(N=2)
> s = Sphere()
> plt.add(s, at=0)
> plt.add(s, at=1)
> plt.remove(s, at=1)
> ```
> 
> When I remove s from renderer at index 1, the remove method will clear the `plt.objects`. But another s is in the actors list of the renderer at index 0.

This question. 
The value of property `plt.objects` is changed I remove objs from a renderer, even if these objs had been added in other renderers.
So it can't even used as amount of objs in current renderer.

**Comment by marcomusy** [comment]
Thanks for pointing out this. In fact the .object attribute is quiet useless and should be revised or even eliminated..
Consider:
```py

from vedo import *
plt = Plotter(N=2)
s = Sphere().lw(1).alpha(0.8)
s.name = "MySphere"
c = Cube().alpha(0.8)
e = Ellipsoid().alpha(0.8)
plt.add(s, at=0)
plt.add(s, c, e, at=1)
plt.remove("MySphere", at=1) # you can also remove stuff by name
# print(plt.objects) # useless/wrong
print(plt.get_meshes(at=1))
plt.show().interactive()
```

**Comment by Poisoned** [comment]
Oh, let me try this method.
