### ISSUE TITLE
Cannot start vedo with wsl2 "failed to load driver: swrast"

### ISSUE THREAD

**Issue by odinsbane** [marcomusy/vedo#1211]
I created a new miniconda environment with python3.11 then installed vedo and everything seem to work but when I ran vedo I just got an error.

>libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

There are quite a few more errors involved.

After debugging quite a bit I found the issue had to do with a gcc version missmatch, I ran the following command from the conda environment I installed vedo into

>conda install -c conda-forge gcc=12

Then I could use vedo again.

**Comment by marcomusy** [comment]
Thank you for reporting this!
Very useful.
