### ISSUE TITLE
Making Video on Windows doesn't work

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#122]
Hi Marco, 

I've encountered a problem with the `Video` class: https://github.com/marcomusy/vtkplotter/blob/471ae90046f00579d6e4ad894f78a9018564224b/vtkplotter/vtkio.py#L1403

If I make a video with code similar to the one provided in the example, I get different behaviours depending on the OS:

On Mac it works fine, it creates the video and it's all good. 
On Windows it creates a video where the frames are either black or messed up. 

I've become convinced that the problem is with the `ffmpeg` command in `Video.close()`, but was unable to find a fix. It should be something about the codec and pixel format used, but I'm unsure about what the solution is.

I should also add that I've tried updating ffmpeg to the latest build but that doesn't change anything. 

I don't know if the `Video` class changed recently, but I think I was able to create videos on windows in the past, and I haven't changed anything on my machine. The only change is that I'm using a more recent version of `vtkplotter`.

**Comment by adamltyson** [comment]
FYI - works on Ubuntu too.

**Comment by FedeClaudi** [comment]
Hi, just adding this here:
if there's a problem with ffmpeg (e.g. not installed correctly), the `video.close()` method still prints "~save Video as..." even though nothing gets actually saved.

**Comment by marcomusy** [comment]
hi @FedeClaudi sorry for the late answer, i would first check if the screenshots are rendered correctly, if so the isuue must be ffmpeg as you say.
if in the meanwhile you found a better way of doing this, using opencv, we could integrate that in vtkplotter as an alternative backend option, something like `Video(use='opencv')`.

**Comment by FedeClaudi** [comment]
Hi, yep the screenshots are rendered correctly on both mac and windows, the problem seems to be with the video creation. 

Sure, if you'd like to take the code I've made for using opencv and make it part of vtkplotter that'd work. 

Do you know how much do users create animations/videos in vtkplotter? I suspect that it's going to become increasingly important for brainrender so I'd be keen to support this functionality.

**Comment by marcomusy** [comment]
it's cool that at least screenshots are doing fine :) if you have some lines of code already using opencv can you share them?
though i dont know how many users need videos, making videos is for sure one important feature and it should be fully supported in vtkplotter

**Comment by FedeClaudi** [comment]
sure, 
this is a bunch of utility functions to create videos with opencv: https://github.com/BrancoLab/BrainRender/blob/animation/brainrender/animation/video_utils.py

And this is the brainrender class that handles creating a video (mostly builds upon the vtkplotter video class): https://github.com/BrancoLab/BrainRender/blob/animation/brainrender/animation/video.py

`BasicVideoMaker.close()` uses opencv VideoCapture to create a video stream from the saved screenshots and then a VideoWriter to save them as a .mp4 or .avi video. Let me know if there's anything that is not clear.

**Comment by marcomusy** [comment]
In the latest release i include opencv support, interface is:
`video = Video("spider.mp4", duration=6, backend='ffmpeg') # backend='opencv'`
also added some semi-automated video shooting where one can specify rotations and elevation ranges, or a start to end camera positions (as either a vtkCamera or python dictionary):
```python
video.action(zoom=1.1)
#Options are:  elevation_range=(0,80),
#              azimuth_range=(0,359),
#              zoom=None,
#              cam1=None, cam2=None  # initial and final camera positions
```
check out example [here](https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/other/makeVideo.py)
M.

**Comment by FedeClaudi** [comment]
Cool, nice stuff!
