### ISSUE TITLE
Nédélec plot

### ISSUE THREAD

**Issue by wwshunan** [marcomusy/vedo#128]
Hi everyone, can vtkplotter be used to plot nedelec solution?

**Comment by marcomusy** [comment]
hi, i'm not sure ... only tested sofar with Lagrange, Discontinuous Lagrange, BDM solutions in fenics.

**Comment by wwshunan** [comment]
Thanks for your reply. Then I have to multiply the vector array of the solution with the Nédélec basis to get the solution vector at each edge point?

**Comment by marcomusy** [comment]
yes, i guess so.. eventually all you can visualize with vtkplotter in this case are vertices and faces of polygonal data and scalars or vectors associated to either of them.

**Comment by wwshunan** [comment]
Do you have any plan to support plot Nédélec element?

**Comment by marcomusy** [comment]
..that i'm afraid would go beyond the scope of the package, if you need to visualize vectors at specific positions in space you can do it "manually" it depends on what kind of information you want to visualize

**Comment by wwshunan** [comment]
Thank you
