### ISSUE TITLE
Problem with show in trimesh/section.py example

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vedo#130]
Hi @marcomusy , 
Hope this message finds you well. 
I am currently trying the trimesh/section.py example and keep getting an error in the show function that I don't know how to fix. 
` Traceback (most recent call last):

  File "<ipython-input-1-9cb4570fbaa9>", line 18, in <module>
    show([(mesh, pl), (slice_2D, txt)], N=2, sharecam=False, axes=True)

  File "D:\Applications\Anaconda3\lib\site-packages\vtkplotter\plotter.py", line 292, in show
    vp.interactor.Start()

AttributeError: 'NoneType' object has no attribute 'Start'`

I get the same error in both, spyder and jupyter notebooks. I have the lastest version of vtkplotter. 

Hope to hear from you soon,
take care
Juliana

**Comment by marcomusy** [comment]
Hi Juliana
I'm fine thanks!:) what if you try with just:
`show(slice_2D)`
because jupyter session does not support multiple rendering windows.
you can also try adding
```python
from vtkplotter import embedWindow
embedWindow('k3d')  # k3d, panel, itk, False
```
cheers, m.

**Comment by jsanchez679** [comment]
Hi @marcomusy , 
Thanks for your fast reply. It worked adding:
from vtkplotter import embedWindow
embedWindow(False) 
show(slice_2D)
but when try then to show the mesh with the plane after closing the previous window, a new window appears with an error message and I need to restart the kernel for it to work again....
Is there a way I can use Plotter to plot these kind of objects (planes, meshes and Path3D) at the same time?
best wishes, 
Juliana

**Comment by marcomusy** [comment]
Uhmm.. what error message is that? Have you tried show everything at once:
```python
plt = show(mesh1, mesh2, somePath3D, axes=1)
plt.close() # this closes the window
```
You can also specify to spawn a new plotter window along with an existing one with
`show(mesh3, newPlotter=True)`

**Comment by jsanchez679** [comment]
Hi @marcomusy, 
They way it has been working for me is to define a plot like ```vp = Plotter(N=1)``` and then add show to that plot, rather than using just the show function. I think the problem comes when I am plotting different things within the same script and whenever I forget to close the previous window and I am using show, then Spyder just collapses. 

Juliana

**Comment by marcomusy** [comment]
Hopefully this now will work
