### ISSUE TITLE
examples/other/dolfin/noplot?

### ISSUE THREAD

**Issue by gdmcbain** [marcomusy/vedo#131]
Where's [`dolfin/noplot`](https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/other/dolfin/noplot)?

I was interested by this sentence:

>  To gain more control on the property of the shown objects see the analogous examples in [noplot](https://github.com/marcomusy/vtkplotter/blob/master/vtkplotter/examples/other/dolfin/noplot).

in [vtkplotter/examples/other/dolfin/README.md](https://github.com/marcomusy/vtkplotter/blob/08e3ee37895cb382ca9f46483339e3ae9771641d/vtkplotter/examples/other/dolfin/README.md) but the link's broken.

**Comment by marcomusy** [comment]
Hi, I eventually removed those examples as they looked a bit too complicated and I felt people might be uninterested, the basic idea is that the plot() returns the `vtkplotter.Plotter` object and from that one can access various properties of the rendered meshes, e.g.:
```python
# ...
plt = plot(u)
msh = plt.actors[0]
msh.color('blue').alpha(0.5).cutWithPlane() # etc
plt.show()
```
