### ISSUE TITLE
Changing the name of objects #question

### ISSUE THREAD

**Issue by ahinoampollack** [marcomusy/vedo#134]
Hi,

Currently I'm really enjoying VTKPlotter for making fairly complex models with many objects (see image below).

Is there a way to name the objects such that when they appear in the controls they have chosen names (instead of mesh#1, mesh #2)? 
I've tried doing the following:
mobject.name = 'my chosen name'
but that doesn't seem to work.

Thanks for your help!
Noe
![image](https://user-images.githubusercontent.com/34078129/80563905-4ba3fe00-89a1-11ea-8534-d65c5b187607.png)

**Comment by marcomusy** [comment]
At the moment that is not implemented, I will see if it's possible to do (it should!) in `k3d`.

**Comment by ahinoampollack** [comment]
Wow! 
Thanks so much Marco for this!
This was super important to me and your new commit included this feature.
Really appreciate it.

![image](https://user-images.githubusercontent.com/34078129/80938416-e62f8300-8d8d-11ea-9d46-dffa43627414.png)

Would like me to make a pull request with an example notebook showing how to make the model in the image? Let me know. It will be easy.

Thank you again,

Noe

**Comment by marcomusy** [comment]
Hi Noe, the image looks amazing! Yes - please it would be great to have a notebook for the model as an example. Thanks!
