### ISSUE TITLE
vts vector field

### ISSUE THREAD

**Issue by longlong-zhang** [marcomusy/vedo#137]
Hello all,
  I met a problem when i use vtkplotter to show a vts format file.  The map i want to get is shown as below
![ppm](https://user-images.githubusercontent.com/50805242/80853140-dcf4c800-8c60-11ea-9e8c-b76df3be802b.png)
  But vtkplotter give me a map which seems lost some important message.
  
![vtkplot](https://user-images.githubusercontent.com/50805242/80853181-2218fa00-8c61-11ea-9f34-09dd548b0773.png)
  Also, i have attached my vts file in this submit.
![vts](https://user-images.githubusercontent.com/50805242/80853260-edf20900-8c61-11ea-98f1-bd8a13d501ba.png)

  Hopping for any suggesstions!

**Comment by marcomusy** [comment]
Hi, you can try out this example:
```python
from vtkplotter import load, datadir, Arrows, show

g = load(datadir+'structgrid.vts').printInfo()

coords = g.points()
vects  = g.getPointArray('Momentum') # printInfo gives the list
print('shapes are:', coords.shape, vects.shape)

# build arrows from starting points to endpoints, with colormap
arrows = Arrows(coords-vects/500, coords+vects/500, c='hot_r')

g.pointColors('Density').lineWidth(0.1).alpha(0.3)
#g.color('grey').alpha(0.3)

show(g, arrows, axes=9) # axes type 9 is a simple box
```
![sgrid](https://user-images.githubusercontent.com/32848391/80862655-04568f80-8c77-11ea-8249-5b61283e04ce.png)

**Comment by longlong-zhang** [comment]
Hello sir,
   Thanks for your suggesstion,but it seems still remain some problems,Also I have attached my eeror message in this submit. Besides I give a link to my vts file.
   
   when i try to plot my vtk file i met this problem too, so if you have any suggestions to help me get the map of this type file i would sincerely thank for your kindly help.
   
   Again, hoping for you answers!

![微信截图_20200502204215](https://user-images.githubusercontent.com/50805242/80864627-6da9c300-8cb6-11ea-9f44-84ad2edd5786.png)

[click to get my vts file](https://github.com/longlong-zhang/Python/blob/master/Link/test2.vts)
[click to get my vtk file](https://github.com/longlong-zhang/Python/blob/master/Link/test.vtk)

**Comment by marcomusy** [comment]
That's only because your array is called "m" instead of "Momentum"!
Also your mesh units is nanometers? You can scale it easily:
```python
from vtkplotter import load, Arrows, show

g = load('test2.vts').scale(1e+06).printInfo()

coords = g.points()
vects  = g.getPointArray('m')/1000 # printInfo gives the list

arrows = Arrows(coords-vects, coords+vects, c='hot_r')

g.lineWidth(0.1).alpha(0.3)
show(g, arrows, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/80866183-a71a0880-8c8d-11ea-9ee7-9e867bd2b687.png)

The second file `test.vtk` the data is associated to cells not to points so this becomes:
```python
from vtkplotter import load, Arrows, show

g = load('/home/musy/test.vtk').scale(1e+06).alpha(0.3).printInfo()

coords = g.cellCenters()
vects  = g.getCellArray('m')/1000 # printInfo gives the list
print('numpy array shapes are:', coords.shape, vects.shape)

arrows = Arrows(coords-vects, coords+vects, c='k')

g.alpha(0.3)

show(g, arrows, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/80866490-468bcb00-8c8f-11ea-9ce6-95501e5430a1.png)

![image](https://user-images.githubusercontent.com/32848391/80866479-3bd13600-8c8f-11ea-83c7-5f5b4fccb29d.png)

Let me know if you can reproduce it
Cheers

**Comment by longlong-zhang** [comment]
Hello sir,
 It wors very well this time! Thanks for your prompt help.
