### ISSUE TITLE
Cell data, threshold and created inner surface?

### ISSUE THREAD

**Issue by rc** [marcomusy/vedo#150]
Hi,

I would like to apply `Mesh.threshold()` to cell data, and simply passing `useCells=True` does not work. So I used Mesh.mapCellsToPoints() and it works (with `useCells=False`), but the resulting mesh has only the original surface - not the new (inner) surface that was created by removing points/cells with the threshold. Is it possible to display the surface of the hole created by the threshold application?

**Comment by marcomusy** [comment]
Try
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
then
```python
from vtkplotter import *

man = load(datadir+"man_low.vtk").lw(0.1)

scals = man.cellCenters()[:, 0] + 37  
man.cellColors(scals, cmap="jet").addScalarBar()
printc(man.getArrayNames())

# make a copy and threshold the mesh
cutman = man.clone().threshold('CellScalars', 36.6, 37.5, useCells=True)

# distribute the meshes on 2 renderers
show(man, cutman, N=2, elevation=-30, axes=1)
```

![image](https://user-images.githubusercontent.com/32848391/82272204-30158d00-997a-11ea-9f5b-291e6bcc9f01.png)

> Is it possible to display the surface of the hole created by the threshold application?

I 'm not sure ..it's not well defined (a contour does not define a unique surface)

**Comment by rc** [comment]
Thanks! `useCells=True` works fine now. 

As for the other question, let me explain what I want to achieve. I have a 3D tetrahedral mesh with two materials - a solid matrix (blue) and channels with a fluid (green):
![screenshot1](https://user-images.githubusercontent.com/44282/82325289-47389700-99db-11ea-9f3f-95fbfe440529.png)

When I apply the threshold, the resulting mesh is surface only:
![screenshot2](https://user-images.githubusercontent.com/44282/82325343-633c3880-99db-11ea-8807-a5b333b8ee65.png)

So, its silhouette is:
![screenshot3](https://user-images.githubusercontent.com/44282/82325361-6c2d0a00-99db-11ea-8698-a13ed3cdbfbf.png)
 
After the channels material (green) is removed (without using vtkplotter) and a new mesh file is created and loaded:
![screenshot4](https://user-images.githubusercontent.com/44282/82325524-ac8c8800-99db-11ea-80b0-c5392609acf5.png)

the silhouette is then:
![screenshot5](https://user-images.githubusercontent.com/44282/82325562-badaa400-99db-11ea-8bbe-dd3b6d932a2f.png)

Is it possible to achieve the end result with vtkplotter/vtk only, without resorting to other tools to remove the green material elements, and without having to save the intermediate mesh to a file? It looks like the threshold filter might not be the right choice for this purpose, as its output is no longer a tetrahedral (volume) mesh. Newbie questions... :)

**Comment by marcomusy** [comment]
> Is it possible to achieve the end result with vtkplotter/vtk only, without resorting to other tools to remove the green material elements, and without having to save the intermediate mesh to a file? It looks like the threshold filter might not be the right choice for this purpose, as its output is no longer a tetrahedral (volume) mesh. 

Yes. 
although vtkplotter focuses on polygonal meshes and Volumes (uniform grids of voxels) you can still use the native VTK class `vtkThreshold` to fill the intermediate step, something like:
```python
import vtk
from vtkplotter import *
tetmesh = loadUnStructuredGrid('mymesh')

thres = vtk.vtkThreshold()
thres.SetInputData(tetmesh)
asso = vtk.vtkDataObject.FIELD_ASSOCIATION_CELLS
thres.SetInputArrayToProcess(0, 0, 0, asso, 'name_of_array')
thres.ThresholdByUpper(some_value)

# if False will only show the outer surface:
# settings.visibleGridEdges = True

msh = Mesh(thres)
show(msh)
```
I cannot test the above code so it might not work :) if you have a mesh to share i can have a better look.

**Comment by marcomusy** [comment]
...I actually had a dataset to test it:
```python
from vtk import vtkThreshold
from vtkplotter import *

tetmesh = loadUnStructuredGrid(datadir+'limb_ugrid.vtk')

thres = vtkThreshold()
thres.SetInputData(tetmesh)
thres.SetInputArrayToProcess(0,0,0, 1, 'chem_0') # name of the array
thres.ThresholdByUpper(0.8)
thres.Update()
ugrid = thres.GetOutput()

# if False will only show the outer surface:
# settings.visibleGridEdges = True

msh = Mesh(ugrid).cellColors(cmap='nipy_spectral')
show(msh)
```
![image](https://user-images.githubusercontent.com/32848391/82387758-2b171300-9a38-11ea-8a64-da01fd42944a.png)

**Comment by rc** [comment]
Perfect, thank you! So the first trick was to use `loadUnStructuredGrid()` instead of just `load()`...

**Comment by marcomusy** [comment]
cool , i hope it work with your mesh too

> Perfect, thank you! So the first trick was to use `loadUnStructuredGrid()` instead of just `load()`...

yes, because `load` already transforms it into a polygonal mesh, all this makes me think i should add a class to explicitly support tet meshes

thanks for your feedback, m.

**Comment by rc** [comment]
Yes, it works for my meshes!

**Comment by marcomusy** [comment]
@rc 
with the latest version
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
you can:
```python
from vtkplotter import *

tetmesh = load(datadir+'limb_ugrid.vtk')
tetmesh.color('prism').alpha([0,1])#.printInfo()

# Threshold the tetrahedral mesh for values in the range:
tetmesh.threshold(above=0.9, below=1)
tetmesh.addScalarBar3D(title='chem_0  expression levels', c='k', italic=1)

show(tetmesh.toMesh(shrink=0.9), axes=1)
```
Run the built-in examples with:
`vtkplotter -ir tet_threshold`

![image](https://user-images.githubusercontent.com/32848391/82769103-4a94ae00-9e33-11ea-9331-58db07bf1a47.png)

More examples [here](https://github.com/marcomusy/vtkplotter/tree/master/vtkplotter/examples/tetmesh) for isosurfacing cutting and slicing.

![image](https://user-images.githubusercontent.com/32848391/82767104-25993e80-9e25-11ea-89e7-4f64a0638c15.jpg)
![image](https://user-images.githubusercontent.com/32848391/82767106-25993e80-9e25-11ea-8206-601377f1f4a5.jpg)
![image](https://user-images.githubusercontent.com/32848391/82767107-2631d500-9e25-11ea-967c-42558f98f721.jpg)
![image](https://user-images.githubusercontent.com/32848391/82769524-3ce02800-9e35-11ea-97b8-0fb30c31f74e.png)

**Comment by rc** [comment]
Very nice!

FYI: I have run `pip install -U git+https://github.com/marcomusy/vtkplotter.git`, but the new examples seem to be missing from the package:
```
vtkplotter -ir tet_threshold
No matching example found containing string: tet_threshold
```
- there is no `examples/tetmesh/` in the installed package.

**Comment by marcomusy** [comment]
I think I forgot to add the new dir to the pip manifesto.. this time should work..
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
then
`vtkplotter -ir tet_threshold`

Let me know if you find any problems using it (it's still a bit experimental!)

**Comment by rc** [comment]
No more problems, all the new examples work now.
