### ISSUE TITLE
Line actor not updated when changing number of points

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#153]
When I create a line with 2 points and later update the line using line.points() then the number of points is not updated.

In the following example I create line "red" using two points and line green using four points. I later update the red line to have the same points as the green line, so they should overlap.

What I get is that the screenshot below. The actor of the red line is not updated.

Some debugging:

- red.points() does return the updated points.
- red._polydata.GetPoints().GetNumberOfPoints()  --> 4  so the vtk points have been updated
- red.GetMapper().GetInput().GetNumberOfPoints() --> 4

It seems to me that all vtk data is set correctly but somehow the actor is not updated accordingly. Even though Modified() is called. Could be a vtk bug as well.

Using with vtk 8.2.0 / vtkplotter 2020.3.0

```
import vtkplotter as vp

pts = [(1,2,3),(4,5,6)]

red = vp.Line(pts, lw=2)

pts2 = [(1,0,0),(0,1,2.1),(1,-1,2),(1,0,0)]
red.points(pts2)
green = vp.Line(pts2, c='green')


p = vp.Plotter()

p += green
p += red

p.show()
```

![afbeelding](https://user-images.githubusercontent.com/34062862/83488015-64c23200-a4ac-11ea-8331-3f9583569142.png)

**Comment by RubendeBruin** [comment]
I think I found the source. We need to update the cell data of the line as well. I'll prepare a mr

**Comment by RubendeBruin** [comment]
I can update the Mesh.points() code as follows:

```
            if len(pts) == 3 and len(pts[0]) != 3:
                # assume plist is in the format [all_x, all_y, all_z]
                pts = np.stack((pts[0], pts[1], pts[2]), axis=1)
            vpts = self._polydata.GetPoints()
            vpts.SetData(numpy_to_vtk(np.ascontiguousarray(pts), deep=True))

            npt = len(pts)

            if self._polydata.GetNumberOfLines() != npt-1:   # number of lines has changed
                lines = vtk.vtkCellArray()  # Create the polyline
                lines.InsertNextCell(npt)
                for i in range(npt):
                    lines.InsertCellPoint(i)
                self._polydata.SetLines(lines)
                self._polydata.Modified()
            else:
                vpts.Modified()

            # reset mesh to identity matrix position/rotation:
            self.PokeMatrix(vtk.vtkMatrix4x4())

            return self
```

This will fix the example above. But I think the same issue will be present for any Mesh, so it is not a generic solve. So for a mesh with some surfaces and some lines this will not work.

@marcomusy , what do you think is the best approach here? Is a generic solution even possible? Otherwise if the number of points changes and throw a warning?

**Comment by marcomusy** [comment]
Hi @RubendeBruin this is an interesting issue.. I'm not sure how safe it is to modify the nr of vertices for an object instead of creating a brand new one.
Naively i would have guess that trying to change it would just cause crashing :)
For the moment I would throw a warning as you say.. (i'll think if can come up with a more general approach though)

**Comment by marcomusy** [comment]
I'll temporarily close this issue as i'm not sure if it's possible to implement.
