### ISSUE TITLE
Converting Point cloud to Mesh

### ISSUE THREAD

**Issue by roaasoloh** [marcomusy/vedo#155]
Hello,
I'm trying to do the following:
I have main mesh (obj, off)
trying to make some affine transformation on it, badly I had to use other source code to do this,
I wasn't able to reach exactly how to use transformations using vtkplotter,
so the point now, after applying the transformation I have points and I set them in .ply file
```
from vtkplotter import *
pcl = load("/home/roaa/Desktop/PhD/Models/OwnDatabase/cat_noise_0.0001.ply")
print("Number of vertices:",len(pcl.points()))
mesh = delaunay2D(pcl.points())
mesh.write("/home/roaa/Desktop/PhD/Models/OwnDatabase/cat_noise_0.0002.off")
mesh1 = recoSurface(pcl.points())
mesh1.write("/home/roaa/Desktop/PhD/Models/OwnDatabase/cat_noise_0.0003.obj")
print("Number of vertices: ",len(mesh1.points()))
print("Number of faces:",len(mesh1.faces()))
```
and this what I got:
```
Number of vertices: 352
 Unknown format /home/roaa/Desktop/PhD/Models/OwnDatabase/cat_noise_0.0002.off file not saved. 
Recalculating normals for 352 Points, sample size= 7
Calculating mesh from points with R = 5.278604972180709
Number of vertices:  248764
Number of faces: 147165
```
It's so weird to have a number of vertices and faces, especially that I don't want to perform anything other than getting the mesh after applying transformation on it.
What I may be doing false.

Thank you for your support.

**Comment by marcomusy** [comment]
Hi, sorry i don't understand very well what you're trying to do, but i see a few possible issues:
- `mesh.write('file.off')` is not implemented (cannot save to off file format, only read)
- `delaunay2D` creates a mesh (points and faces) from points that are at least projectable onto a plane
- `recoSurface` does the same but it is a more general algorithm in 3D
So your output is normal.

About transformations: 
you can shift and rotate any Mesh and it will be saved in its final position e.g.
`mesh.pos(1,2,3).rotateX(60).rotateZ(70).write("m.obj")`

**Comment by roaasoloh** [comment]
ok, so it will be great if I will be only able to use vtkplotter, not to use other outsources.

What I'm trying to do is affine transformations: scaling, rotation, translating, noise, resolution, and shearing. Those most probably I would like to use.

The idea is that here you mentioned for me
 `mesh.pos(1,2,3).rotateX(60).rotateZ(70).write("m.obj")`
 and previously as well you told me about 
`.applyTransform()`

All the problem is how I can configure parameters, and how I know what functions, what they take. in the documentation, I only was able to figure out
 `applyTranform(transformation=)` 
and nothing else is known what it equals.

As well here when you specified `.pos(1,2,3)` how I can know it tends to what.

I appreciate your guidance.

**Comment by roaasoloh** [comment]
I tried to follow the command,
What I did is: 
```
mesh = load("/home/roaa/Desktop/PhD/Models/OwnDatabase/CAT.obj")
mesh_Xrotated = mesh.rotateX(60).write("/home/roaa/Desktop/PhD/Models/OwnDatabase/CAT_60Xrotate.obj")
```
It works fine
when I tried to work with the new mesh I got this: 
`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

As well,

I got this message in MeshLab: 
`Error details: Bad vertex index in face` 
as well No mesh is appearing!! Number of vertices is the same as the main object, while the number of faces is 0

**Comment by marcomusy** [comment]
There is a bug in obj format saving in the last version. Try:
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
then:
```python
from vtkplotter import *

b = load(datadir+'bunny.obj').normalize().alpha(0.8)

def shear(mesh, x=0, y=0, z=0):
    import vtk
    t = vtk.vtkTransform()
    t.SetMatrix([1,x,0, 0,
                 y,1,z, 0,
                 0,0,1, 0,
                 0,0,0, 1])
    mesh.applyTransform(t)
    return mesh 

shear(b, x=0.5)
b.rotateZ(20).pos(1,2,3)
b.write('test.obj')

show(b, Point(), Point(b.pos()), axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/83968701-553b5280-a8cb-11ea-8424-8cb043a02b6c.png)

**Comment by LogWell** [comment]
Hi marcomusy, long time no see~

How to render point cloud from *sphere* to *square* like in **MeshLab** (`Shading`: `Vert`/`Dot Decorator` with `Point Size`)?

**Comment by marcomusy** [comment]
Hi, just use
```python
from vedo import settings
settings.renderPointsAsSpheres = False
```

**Comment by LogWell** [comment]
The following code does not seem to render the square, how can I solve it?
```
from vedo import *
settings.renderPointsAsSpheres = False
mesh = load("1-1-1.ply")
mesh.pointSize(2)
show(mesh)    
```

Left: `Meshlab`, Right: `vedo`:
![20210917_143901](https://user-images.githubusercontent.com/34391447/133736236-9144e200-69a0-477c-bef0-0ca758763165.png)

**Comment by marcomusy** [comment]
Sorry , what "square"?
You can play around with 
`settings.renderPointsAsSpheres = False`
and 
`mesh.lighting('default')`

**Comment by LogWell** [comment]
Meshlab(Shading: Vert)
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/34391447/133867607-f53f6c58-9a08-4585-954a-4ae7faaeffc7.png)
Meshlab(Shading: Dot Decorator)
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/34391447/133867608-b0dcc0d0-e6ab-459a-ac84-a9691fec30f9.png)
vedo
![20210918_092720](https://user-images.githubusercontent.com/34391447/133867650-e2d880c2-9b2d-4e35-a7ff-f1dc4179596e.png)
As you can see, the result is not rendered as `Vert`. I remember that we can get results similar to `meshlab` before.

**Comment by marcomusy** [comment]
Hi, sorry I forgot I disabled `settings.renderPointsAsSpheres = False`. Try instead:
```python
from vedo import *

msh = Mesh(dataurl + "teapot.vtk")

pts_actor = Points(msh.points(), r=10)

pts_actor.renderPointsAsSpheres(False)

show(pts_actor, axes=1)
```
![Screenshot from 2021-09-18 14-48-54](https://user-images.githubusercontent.com/32848391/133889378-23610765-a1e3-40b2-abc4-03cba38e21ae.png)

**Comment by LogWell** [comment]
The result for `grep -r 'splat' .` is empty in `vedo`, so how to render `splat` similar to (a) and (b)?
![tmp](https://user-images.githubusercontent.com/34391447/133913958-37d2e230-0418-4420-820c-57137e7341c0.png)

**Comment by marcomusy** [comment]
I don't think that vtk can do that , you may try something similar with glyphs
```python
from vedo import *

msh = Mesh(dataurl+"bunny.obj").computeNormals().wireframe()

cpts = msh.cellCenters()
shape = Circle(r=0.001, res=24).rotateY(90)
gl = Glyph(cpts, shape,  orientationArray=msh.celldata["Normals"])
gl.c("blue3")#.lighting('off')

show(gl, axes=1)
```
<img width="299" alt="Screenshot 2021-09-19 at 14 37 02" src="https://user-images.githubusercontent.com/32848391/133927780-cd5da5cd-c8e3-42fb-aaeb-04283bbea25f.png">

but will probably become slow for large meshes.
