### ISSUE TITLE
menu in Qt window

### ISSUE THREAD

**Issue by bistek** [marcomusy/vedo#157]
Hi, I do not understand if it is possible to have an interactive menu with objects etc. in a Qt window, like in this web example:

[https://vtkplotter.embl.es/examples/geo_scene.html](https://vtkplotter.embl.es/examples/geo_scene.html)

Or if the menu is just for the web interface.

Thanks!

**Comment by marcomusy** [comment]
Hi, no, the web page example above is the result of the `exportWindow()` command.

You can create a qt application following some ready examples, type eg.:
`vtkplotter -ir qt_window_split`
