### ISSUE TITLE
actors' original vtk objects

### ISSUE THREAD

**Issue by bistek** [marcomusy/vedo#162]
Hello, is it possible to get the original vtk object for each actor in a plotter?

Thanks very much!

**Comment by marcomusy** [comment]
They already are original! Because they _derived_ from it, e.g.:
```python
from vedo import Sphere
import vtk
print(isinstance(Sphere(), vtk.vtkActor))
```
> True

**Comment by bistek** [comment]
Sorry, I did not explained myself.

I have a collection of polydata and I add them as actors in a renderer with something like:

```
for i in polydata_collection:
    vp.add(i)
```

I repeat this a few times. Later on I would like to recover the association between a particular actor and the polydata that it represents.

I suppose that this should be returned by actor.inputdata, but for some reason I cannot figure out how to use it.

**Comment by marcomusy** [comment]
uhmm .. this should fail: `vp.add(some_vtkpolydata)`, you can only add method with arguments `Mesh(vtkActor)` objects (or Volumes..).

In any case you can compare the object returned by `mesh.inputdata()` to your list of polydatas e.g.
`print(polydatalist.index(myact.inputdata())`

**Comment by bistek** [comment]
Alternatively, or even better, it would be nice to pass a name or an id to the actor when adding it to the renderer. Something like `plotter.add(mesh, mesh_id)`. Is this possible?

**Comment by marcomusy** [comment]
Yes, it's already there. You can use `mesh.name` and also `mesh.filename`.
Most object are given a default name that you can modify at creation.

**Comment by bistek** [comment]
Thanks very much!
