### ISSUE TITLE
cannot view the documents due to 403 Forbidden 

### ISSUE THREAD

**Issue by shoKagami** [marcomusy/vedo#163]
When I looked up the API on the [documentation page](https://vtkplotter.embl.es/) in the README(e.g. Points) and clicked on the search results([URL](https://vtkplotter.embl.es/content/vedo/base.html?highlight=points#vedo.base.BaseGrid.points)), I saw the following message.

```
Forbidden
You don't have permission to access /content/vedo/base.html on this server.
```

How can I access to the API reference of vedo?

**Comment by marcomusy** [comment]
Hi
because of the name change the web page is still down.. it should be soon fixed!
In the meanwhile you can download a local copy of the documentation here:
https://www.dropbox.com/s/s4ku0pwjax574cb/vedo_docs.zip?dl=0
Thanks

**Comment by shoKagami** [comment]
Thanks for your quick response!

I downloaded the documentation and confirmed that the documentation looks fine.

**Comment by marcomusy** [comment]
Should be now up and running!
