### ISSUE TITLE
Layers in vedo for geology model

### ISSUE THREAD

**Issue by similang** [marcomusy/vedo#164]
Hi, I'm trying to follow through your sample notebook, trying to compare the usability with another package - Gempy. How can I get to have separation in color for different layers in geology notebook. 

Example from Gempy: https://www.gempy.org/tutorials

As shown in figure below, Gempy is able to identify and separate colors of different surfaces. Can it be done in Vedo? Love the package btw. Thanks!

![image](https://user-images.githubusercontent.com/7208012/84802844-bf729680-b033-11ea-9af6-303de5a68389.png)

**Comment by marcomusy** [comment]
hi, thanks!
I'm not sure what data you wish to visualize but that package seem to already have lots of tools for visualization

**Comment by similang** [comment]
Hi, sorry for not making myself clear, so in Gempy the geographical layers can be shown in distinct layers but labeling each layer. I am wondering how to do the same in Vedo, i.e.:  having X,Y,Z surface points in pandas, with additional column labeling each layer. How to differentiate across these different layers as per shown above.

**Comment by marcomusy** [comment]
Hi, if you already have a surface of points in space (I guess this is the main goal of the gempy example?) then it's very easy:
You can follow the example here:
https://github.com/marcomusy/vedo/blob/master/vedo/examples/advanced/geological_model.py

![image](https://user-images.githubusercontent.com/32848391/81397531-d2867280-9127-11ea-8cc8-0effbbbebf2d.jpg)

by reconstructing the surface you extract with panda the point of each separate layer then make a mesh:
```python
# ...
landSurface_panda   = pd.read_csv(url+"land_surface_vertices.csv")
landSurface = delaunay2D(landSurface_panda.values).color('slategray')
show(landSurface)
# ...
```

**Comment by similang** [comment]
wait - say i have 5 surfaces, i did the same for each surfaces? 

Like this?

```
landSurface_panda_1  = pd.read_csv(url+"land_surface_vertices_1.csv")
landSurface = delaunay2D(landSurface_panda_1  .values).color('slategray')

landSurface_panda_2  = pd.read_csv(url+"land_surface_vertices_2.csv")
landSurface = delaunay2D(landSurface_panda_2 .values).color('slategray')
...
landSurface_panda_5  = pd.read_csv(url+"land_surface_vertices_5.csv")
landSurface = delaunay2D(landSurface_panda_5 .values).color('slategray')

```

Then I need to combine again or how? Apologise if this is a basic question - just starting with this tool. Thanks.

**Comment by marcomusy** [comment]
yes - basically you can extract the xyz points from panda by [subsetting](https://datacarpentry.org/python-ecology-lesson/03-index-slice-subset/index.html),  e.g.
`xyz = pandadata[pandadata.layer == 3]`
then reconstruct the surface and apply any color you wish as above.

**Comment by similang** [comment]
Let me try it out. Thanks.
