### ISSUE TITLE
Lighting problem with mesh alpha

### ISSUE THREAD

**Issue by willw1** [marcomusy/vedo#165]
Hi, thanks very much for such a useful package. I have a problem when using alpha <1 on a mesh. Example below is just a simplified version of the volumetirc/isosurfaces.py example, using just one contour and setting alpha on the mesh. Rotating the figure gives a strange 'wash' effect, which I suspect is caused by lighting.

    """Generate the isosurfaces corresponding to a set of thresholds.
    (These surfaces are not separate meshes).
    """
    from vtk import vtkQuadric, vtkSampleFunction

    # Quadric definition. This is a type of implicit function.
    quadric = vtkQuadric()
    quadric.SetCoefficients(0.5, 1, 0.2, 0, 0.1, 0, 0, 0.2, 0, 0)

    # the vtkSampleFunction evaluates quadric over a volume
    sample = vtkSampleFunction()
    sample.SetSampleDimensions(40, 40, 40)
    sample.SetImplicitFunction(quadric)
    sample.Update()

    img = sample.GetOutput()  # vtkImageData

    ########################
    from vtkplotter import show, Volume

    # generate an isosurface the volume for each thresholds
    ts = [0.5]

    # Use c=None to use the default vtk color map. isos is of type Mesh
    isos = Volume(img).isosurface(threshold=ts)

    isos.color((0.5,0.5,0.5))

    isos.alpha(0.1)

    #--- These don't fix the problem
    isos.lighting('off')
    isos.lighting(ambient=1.0,diffuse=0.0)

    show(isos)

**Comment by marcomusy** [comment]
Hi, thanks :)
1. try upgrading to the latest `vedo`:
`pip uninstall vtkplotter`
`pip install vedo`
2. running the above example I don't see any strange behaviour:

![image](https://user-images.githubusercontent.com/32848391/85239466-3f35a200-b434-11ea-91ff-729ad5e51bf6.png)

3. In your case it might be due to your graphics card, if so try adding:
```python
from vedo import settings
settings.useDepthPeeling = True
```

**Comment by willw1** [comment]
Thanks, DepthPeeling fixed it. Must have been my graphics card (MacBook Air 2014 with Intel HD Graphics 5000 ).
Will
