### ISSUE TITLE
Styling axes

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#168]
Hi Marco, how's it going?

I have a question about positioning of the text on axes.
Because of how brainrender's scenes are oriented, the X axis text ends up being upside down:
![image](https://user-images.githubusercontent.com/17436313/86011970-48ff6c80-ba15-11ea-978d-0aa0e85d64d5.png)

I see options to move the title around and rotate it, but I couldn't find a way to rotate all text so that it faces the correct way. Is there a way to do that in vedo?

**Comment by marcomusy** [comment]
uhmm.. yes ..but you need to create the axes as an independent object and add it to the scene, plus a small hack:
```python

from vedo import *

s = Sphere(r=6000).pos(7000,3000,4000).alpha(.2).scale([2,1,1])

cam = dict(pos=(1.99e+4, -2.67e+4, 5.76e+4),
           focalPoint=(6.38e+3, 2.71e+3, 1.04e+3),
           viewup=(-0.0654, -0.891, -0.448),
           distance=6.51e+4,
           clippingRange=(3.79e+4, 9.95e+4))

ax = addons.buildAxes(s, xtitle='x [um]',
                      xTitleOffset=0.1, xTitleJustify='bottom-left')
for a in ax.unpack():
    if 'xtitle' in a.name:
        a.RotateZ(180)
        break

show(s, ax, camera=cam)
```
![image](https://user-images.githubusercontent.com/32848391/86019045-64bf3e80-ba26-11ea-93c1-07ab6eedf7e1.png)

**Comment by FedeClaudi** [comment]
Hi, thanks for getting back to me  so rapidly. 

That rotates the title, but the labels (e.g. `10000`) are still upside down, is there a way to rotate those as well?

Thanks, and sorry for this, there wouldn't be the need for it if the brain atlases weren't defined upside down...

**Comment by marcomusy** [comment]
..try this:
```python

ax = addons.buildAxes(s, xtitle='x [um]', xLabelOffset=.07,
                      xTitleOffset=0.1, xTitleJustify='bottom-left')
for a in ax.unpack():
    if 'xtitle' in a.name or 'xNumericLabel' in a.name:
        a.RotateZ(180)
```

**Comment by FedeClaudi** [comment]
awesome, that works like a charm. Thank you!

**Comment by marcomusy** [comment]
> awesome, that works like a charm. Thank you!

you're welcome it is actually a useful feature so i'm implementing it.
You'll just need to add a flag.

**Comment by marcomusy** [comment]
this should now work without hacks ,can make it italic too :)
```python
from vedo import Sphere, show

s = Sphere(r=6000).pos(7000,3000,4000).alpha(.2).scale([2,1,1])

show(s, axes=dict(xtitle='My long title [um]',
                  xFlipText=True,
                  xTitleOffset=0.1,
                  xTitleItalic=.5,
                 ),
     viewup='z',
     )
```

**Comment by marcomusy** [comment]
..You can see it by typing:
`vedo https://www.dropbox.com/s/en8iuwhrc2qqrag/scene.npy?dl=0`

its a new feature!

(export it by pressing `E`)
