### ISSUE TITLE
Displaying spheres inside mesh

### ISSUE THREAD

**Issue by anorak94** [marcomusy/vedo#171]
Hey marco

I have a 3d array which i have converted into a mesh. I also have the coordinates of some spheres i would like to place inside this mesh. Right now i am doing something like this.

```python
sp_list = []
for (c1, c2, c3) in coords_list:
   #print (c1, c2, c3)
   s = Sphere(pos=(c1, c2, c3), r=10, c='r', alpha=1, res=24, quads=False)
   sp_list .append(s)
show(mesh_list, sp_list)
```
but the mesh structure and the spheres appear separately when what i want is for the spheres to be displayed inside the structure is there any way to do this with vtkplotter.

<img width="808" alt="Screenshot 2020-07-01 at 17 51 31" src="https://user-images.githubusercontent.com/45297533/86283505-7ef14c00-bbe1-11ea-9272-34421746e668.png">
current output

**Comment by marcomusy** [comment]
uhm i'm not sure where is the mesh in the screenshot :)

Use `Spheres` instead of `Sphere` and meve them anywhere you like:
```python
sps = Spheres(coords_list, r=10, c="r", res=12).pos(x,y,z)
show(sps)
```

**Comment by anorak94** [comment]
The bigger structure is the mesh. Problem is i have a list of coordiantes and i want to place a sphere at each of those coordiantes. When you say move them wherever you want how will i make sure that all the spheres appear at their correct location in the mesh

**Comment by anorak94** [comment]
<img width="768" alt="Screenshot 2020-07-02 at 00 28 49" src="https://user-images.githubusercontent.com/45297533/86297233-0bf4cf00-bbfb-11ea-9894-c218211ac518.png">
current output ideally these spheres should be inside the structure from where they come

**Comment by anorak94** [comment]
thanks for the spheres tip really speeds up the rendering

**Comment by marcomusy** [comment]
> current output ideally these spheres should be inside the structure from where they come

but it looks they are NOT!
so you either moved the mesh or have the wrong coordinates for the spheres, you should double check that.. 

also if the spheres are so small and all of the same size it's maybe easier to use `Points` instead?

**Comment by anorak94** [comment]
I make the mesh from 724x403x398 volumetric data and the points come from inside this region is there a way to keep the original coordinates of the mesh and display the spheres inside because right now i just make a mesh and do

`show(mesh, spheres) 
`
separately maybe thats why i am getting this error

**Comment by marcomusy** [comment]
> I make the mesh from 724x403x398 volumetric data 

so, probably this mesh lives in the box range x=[0,724], y=[0,403] and z=[0,398]
use `show(axes=1)` to see the reference frame

> `show(mesh, spheres) `
> separately maybe thats why i am getting this error

no.. i don't see any error in that..

**Comment by anorak94** [comment]
ah thanks i saw it my coordinates were getting switched in the spheres the show axes part helped me get it
