### ISSUE TITLE
NumPy dependency is lacking in the requirements.txt

### ISSUE THREAD

**Issue by volpatto** [marcomusy/vedo#172]
Hey, Marco!

First of all, great work! `vedo` is amazing and it eases the pain to use VTK. Thanks!

I'm opening this issue due to a very minor problem I have faced. I tried `vedo` from CLI and it complained of:
```console
ModuleNotFoundError: No module named 'numpy'
```

Since you mentioned in the `README.md` that `vedo` is based on `VTK` and `numpy`, maybe including `numpy` as a requirement would make sense. What do you think? Could I submit a PR?

Cheers!
Diego

# Steps to reproduce the problem

Below I described exactly what I did to make it reproducible if you want to check (or `vedo` interested users):

**OS: Ubunutu 18.04.4**

Procedures: I installed `vedo` in the development mode. It means that I cloned your repo and executed in an isolated env:
```console
$ virtualenv .vedo
$ source .vedo/bin/activate
$ pip install -r requirements.txt
$ python setup.py install
```

Then I ran `vedo` with its command-line interface:
```console
$ vedo pore_network.vtu
```

The `.vtu` file is attached [here](https://drive.google.com/file/d/1ln49SlcPKcPmnRWt8Zw8tilc-eXpnBpj/view?usp=sharing).

**Comment by marcomusy** [comment]
Hi Diego,
sure thanks! i'm happy that you consider it useful :)

I'm not sure if 'numpy' has to be added in the setup.py only or also in the requirements.txt
(some time ago i remember that trying to do `pip -U` also updated the conda's numpy version which was unintended... but i'm not expert of pip!)

**Comment by volpatto** [comment]
> I'm not sure if 'numpy' has to be added in the setup.py only or also in the requirements.txt

Hmm... this is a good question. As pointed by [PyPA](https://packaging.python.org/discussions/install-requires-vs-requirements/), `install_requires` should contain only the very essential dependencies, while `requirements.txt` can be more extensive, maybe when some dependency is useful for a subset of use cases. In my understanding (please correct me if I'm wrong), `numpy` is essential for `vedo`, since it can compromise a big feature of `vedo` (CLI usage). So, in this case, I think that it would be appropriate to include `numpy` in both. Well, in either way, `vedo` would have only 2 dependencies, it's still tidy and clean. Are you OK with that? Please feel free to disagree :)

> (some time ago i remember that trying to do `pip -U` also updated the conda's numpy version which was unintended... but i'm not expert of pip!)

Hmm! Yes, if you have conda's python activated, and then run `pip -U`, it probably will mess with Python packages inside the conda env. But, IMHO, this is OK. Actually I think that to mix conda and pip to manage packages can be a source of problems (oh, boy... I have faced hard times, I don't recommend it), this is a not recommended practice AFAIK. Better choose only one and stick together with it until the end :wink:

**Comment by marcomusy** [comment]
Hi Diego, thanks a lot for drawing my attention to this and for the explainations! i just made a quick check (hope it makes sense) by adding the numpy in the `install_requires` then doing `pip install . -U` did _not_ mess up with the conda environment..
so I suggest we add it in the setup.py only!

**Comment by volpatto** [comment]
> Hi Diego, thanks a lot for drawing my attention to this and for the explainations! i just made a quick check (hope it makes sense) by adding the numpy in the `install_requires` then doing `pip install . -U` did _not_ mess up with the conda environment..
> so I suggest we add it in the setup.py only!

Hi Marco! Sure, I'll submit a PR ASAP!

Cheers!

**Comment by volpatto** [comment]
Sorry, closed the issue by accident.
