### ISSUE TITLE
Control over the borders between renderers?

### ISSUE THREAD

**Issue by m-albert** [marcomusy/vedo#174]
So great to see how `vedo` is evolving!

Here's a question I'm having since a while: When using several renderers, is there a way to hide the borders between them? I mean the grey lines like these ones resulting from running `advanced/moving_least_squares2D.py`.

![image](https://user-images.githubusercontent.com/12528388/86468775-6a739780-bd38-11ea-8df8-f2203a21f07e.png)

Thanks a lot for any hints!

**Comment by marcomusy** [comment]
Hi Marvin, thanks! Yes, you can disable it with
```python
from vedo import settings
settings.showRendererFrame=False
```

**Comment by m-albert** [comment]
Oh I must have missed it in `settings.py`.

Thank you so much!
