### ISSUE TITLE
Visualization in jupyter Lab slicer.py file

### ISSUE THREAD

**Issue by wangyibin0011** [marcomusy/vedo#175]
Hello, thank you for your excellent work. I have a question to ask you:
Now I want to implement advance in jupyter lab/ slicer.py When embedwindow (false), a python visualizer will pop up, but when I want to get a visualization result on jupyter lab, nothing will appear when I set embedwindow ('K3D').
The code is as follows：
~~~
from vedo import datadir, load, addons, show, Text2D
from vedo.applications import Slicer
from vedo import embedWindow

embedWindow('k3d')

filename = datadir+'embryo.slc'

vol = load(filename).alpha([0,0,1]).c('gray')    #.printInfo()

plt = Slicer(vol,
             bg='white', bg2='lightblue',
            #  cmaps=("gist_ncar_r","jet","Spectral_r","hot_r","bone_r"),
            cmaps=("gray","jet","Spectral_r","hot_r","bone_r"),
             useSlider3D=True,
             )

show(plt,vol)
~~~
The output of jupyter lab is as follows
~~~
Slicer tool
Use showInset() after first rendering the scene.
~~~
How can I get the visualization results in jupyter lab?

**Comment by wangyibin0011** [comment]
Jupyter lab and jupyter notebook get the same result

**Comment by marcomusy** [comment]
thanks @wangyibin0011 
because `vedo` delegates in notebooks the rendering to `k3d` i'm afraid that `Slicer` can only work when a pop up window is allowed.. :(

**Comment by wangyibin0011** [comment]
All right, so that's that.
I have an idea. I want to generate multiple subgraphs in one window and generate sliders for Vols in each subgraph. Do you have any good ideas? Any suggestion can be very useful. thank you！

**Comment by marcomusy** [comment]
That should be doable.. check out [this](https://github.com/marcomusy/vedo/blob/master/vedo/examples/basic/sliders2.py) example, type:
`vedo -r sliders2`

**Comment by wangyibin0011** [comment]
That's all I need. Thank you very much!

**Comment by wangyibin0011** [comment]
Now I seem to have a problem: the code is as follows:
~~~
from vedo import *
import math
import numpy as np

def sliderfunc_z(widget, event):
    """
    map2cells
    dims
    """
    i = int(widget.GetRepresentation().GetValue())
    rmin, rmax = vol.imagedata().GetScalarRange()
    msh = vol.zSlice(i).lighting('', la, ld, 0)
    msh.pointColors(cmap='gist_ncar_r', vmin=rmin, vmax=rmax)
    vp.renderer.RemoveActor(visibles[2])
    if i and i<dims[2]: vp.renderer.AddActor(msh)
    visibles[2] = msh

im_data = np.load('/Users/biomind/Biomind-Server-Tutorials/pipelines/im_data.npy',allow_pickle=True)
columns = 4
numplots = len(im_data)
rows = math.ceil(numplots / columns)
vp = Plotter(axes=False,sharecam=False,title='PreviewPridection',shape=(rows,columns))
la, ld = 0.7, 0.3

for i in range(len(im_data)):
    vol = Volume(im_data[i]).c('gray')
    dims = vol.dimensions()
    visibles = [None,None,None]
    vp.show(vol, at=i)
    vp.addSlider2D(sliderfunc_z,
                0, len(im_data[i]),
                value=0,
                pos=([0.03,0.03],  # first point of slider in the renderer
                        [0.03,0.3]))

vp.show(interactive=1)
~~~
If you run this code, you will find that no matter which slider is operated, the last Vol will be sliced. In fact, I wrote the same thing. Obviously, I want to slice the corresponding Vol when sliding each slider. I noticed our sliderfuncs_ Z is passed to addslider2d as a parameter. Is there any way to pass Vol to sliderfunc_ Z? Otherwise, what are the feasible ways to realize my plan? Looking forward to your reply, NPY file has been uploaded.Of course, there are some problems with the data, but I can solve this

![a](https://user-images.githubusercontent.com/53501301/87115704-9944bd00-c2a6-11ea-8998-e2b6331500e7.png)

[im_data.npy.zip](https://github.com/marcomusy/vedo/files/4900729/im_data.npy.zip)

**Comment by wangyibin0011** [comment]
I solved the problem：
～～～
from vedo import *
import math
import numpy as np

im_data = np.load('/Users/biomind/Biomind-Server-Tutorials/pipelines/im_data.npy',allow_pickle=True)

columns = 4
numplots = len(im_data)
rows = math.ceil(numplots / columns)


vp = Plotter(axes=False,sharecam=False,title='PreviewPridection',shape=(rows,columns))

la, ld = 0.7, 0.3

def slice_factor(index, data):
    vol = Volume(data).c('gray')
    dims = vol.dimensions()
    vp.show(vol, at=index)
    visibles = [None,None,None]
    def f(widget, event):
        vol = Volume(data).c('gray')
        i = int(widget.GetRepresentation().GetValue())
        rmin, rmax = vol.imagedata().GetScalarRange()
        msh = vol.zSlice(i).lighting('', la, ld, 0)
        msh.pointColors(cmap='gist_ncar_r', vmin=rmin, vmax=rmax)
        vp.renderer.RemoveActor(visibles[2])
        if i and i<dims[2]: vp.renderer.AddActor(msh)
        visibles[2] = msh
    return f

def add_slice(index, data):
    vp.addSlider2D(slice_factor(index, data), 0, len(data),value=0, pos=([0.03,0.03],[0.03,0.3]))


for index, data in enumerate(im_data):
    add_slice(index, data)

vp.show(interactive=1)

～～～

**Comment by marcomusy** [comment]
It's a very cool example, i've played a bit with it, consider this variation:
```python
from vedo import Plotter, Volume, Text2D
import numpy as np

im_data = np.load('im_data.npy', allow_pickle=True)

la, ld = 0.7, 0.3
alphas = [0,0,0.01,0,0]
columns = 4
numplots = len(im_data)
rows = int(numplots/columns+0.5)

vp = Plotter(axes=False,
             sharecam=False,
             title='PreviewPrediction',
             shape=(rows,columns),
             size='fullscreen',
             )

def slice_factor(index, data):
    vol = Volume(data).spacing([1,1,10]).c('gray').alpha(alphas)
    dims = vol.dimensions()
    box = vol.box().alpha(0.5)
    comment = Text2D('dataset'+str(index), font='MonospaceTypewriter', s=0.9)
    vp.show(vol, box, comment, at=index, interactorStyle=6)
    visibles = [None,None,None]
    def f(widget, event):
        i = int(widget.GetRepresentation().GetValue())
        rmin, rmax = vol.scalarRange()
        msh = vol.zSlice(i).lighting('', la, ld, 0)
        msh.pointColors(cmap='gist_ncar_r', vmin=rmin, vmax=rmax)
        vp.renderer = widget.GetCurrentRenderer()
        vp.remove(visibles[2], render=False)
        if i and i<dims[2]: vp.renderer.AddActor(msh)
        visibles[2] = msh
    return f

def add_slice(index, data):
    vp.addSlider2D(slice_factor(index, data),
                   0, len(data), value=0,
                   pos=([0.03,0.03],[0.03,0.3]),
                  )

for index, data in enumerate(im_data):
    add_slice(index, data)

vp.show(interactive=1)
```
![image](https://user-images.githubusercontent.com/32848391/87147279-a2388d00-c2ac-11ea-8ef2-518827bca061.png)

- you dont need to recreate the volume in f
- use right click to rotate scene to avoid accdentally dragging the slider `interactorStyle=6`
- use `vp.renderer = widget.GetCurrentRenderer()` to grab the current window automatically
- expand the z axis with `spacing()` and adjust transparency with `alpha()`
- add a comment for each dataset if needed

**Comment by wangyibin0011** [comment]
Thank you very much for your suggestions
