### ISSUE TITLE
vedo convert is not working on Windows version

### ISSUE THREAD

**Issue by Archan2605** [marcomusy/vedo#176]
Hi, I installed the vedo library on python3.7 using pip on my Windows machine. It installed correctly but it is not working on the command prompt when I call the following line:-
```
vedo-convert demo.obj -to stl
```

Can you please help me out

Thanks

**Comment by marcomusy** [comment]
Hi, I guess the problem is the windows PATH which needs to be set, I thought it should be already set in the anaconda terminal..

One possible way around is to write a simple 1-line script:
```python
from vedo import load
load('demo.obj').write('demo.stl').show()
```

**Comment by Archan2605** [comment]
I tried with path in windows but it is not working 
But the script you gave is working thanks
