### ISSUE TITLE
3D Volume Segmentation features

### ISSUE THREAD

**Issue by FrancoisMasson1990** [marcomusy/vedo#178]
Hello,

I have dcm files and would like to know if 3D Volume segmentation is something that will be integrated in vedo ?
(Idea : Being able to select either a 2D Slice or a 3D volume with mouse-click and associated a different color and/saving that)

**Comment by marcomusy** [comment]
Hi Francois, no ... volume segmentation is not really supported by the underlying vtk machinery.. I guess you might look for ITK instead.
By saving with different color you mean colomap? this is actually an interesting idea.
At present you can only do that through scripting.

**Comment by FrancoisMasson1990** [comment]
I had in mind that for example the volume is completely green and I can select a specific part in that volume and change it to red for exemple
