### ISSUE TITLE
importing files

### ISSUE THREAD

**Issue by bistek** [marcomusy/vedo#179]
Hello, I am trying to use your extensive list of file formats to import different files in different formats (e.g. PLY, OBJ, etc.) and convert them to VTK objects. Then I will use them for some modelling and just afterwards for visualization.

However, it looks like that Vedo makes available the imported objects already as actors or as "vtkFollower" (using `vedo.load()`).

Do you have a function to get a "physical" vtkObject, such as a vtkPolyData, vtkStructuredGrid, etc.?

Thanks very much!

**Comment by marcomusy** [comment]
Yes, just use e.g.:
```python
mesh = load('myfile.obj').rotateZ(45)
mesh.polydata() # rotated vtkPolydata

mesh.inputdata() # for the other data types
```
