### ISSUE TITLE
How to input data for Lego visualization

### ISSUE THREAD

**Issue by perecanals** [marcomusy/vedo#180]
Hi,
I want to plot the Hausdorff distance between the surface voxels of an prediction and its associated label in a segmentation task. I have a 3D numpy array with all surface voxels with some numerical value and everything else set to zero. I saved this in nifti format and then tried to open with the lego function but it returns:

`Error in legosurface(): no scalars found!`

And the plot is empty. How should I treat the data to obtain one of these nice plots? Also, I was not able to find it, but it there a quick way to display this as a mesh maintaining scalar values?

Thank you,

**Comment by marcomusy** [comment]
Hi, can you specify what 'surface voxels' mean?
can you visualize it with
```python
from vedo import Volume
Volume(my_nparray).show()
```

**Comment by perecanals** [comment]
In my array I have labeled pixels (0/1), and 1's correspond to a volume which my network has predicted/segmented. With an erosion operation (scipy.ndimage.morphology.binary_erosion) I get left with just the surface voxels of said volume. 

Nothing pops up with these lines that you have provided (I attach an image so you can have a bit more insight on the nparray called `sds`) :(

<img width="686" alt="image" src="https://user-images.githubusercontent.com/56351022/87669529-7450be00-c76e-11ea-861b-534b1e3e414c.png">

**Comment by marcomusy** [comment]
uhm.. are you inside a notebook or something?  I would first try it out from the normal anaconda terminal or otherwise try adding:
```python
from vedo import Volume, embedWindow
embedWindow(False)
Volume(my_nparray).show()
```

**Comment by perecanals** [comment]
Now I tried from terminal, and using this:

`>>> from vedo import Volume
>>> import nibabel as nib
>>> im = nib.load('/Users/pere/Downloads/fold_1/results/HD_test.nii').get_data()
>>> type(im)
<class 'numpy.ndarray'>
>>> im.shape
(512, 512, 904)
>>> import numpy as np
>>> np.unique(im)
array([ 0.        ,  0.399884  ,  0.48628342, ..., 25.00651302,
       25.0114829 , 25.05391801])
>>> Volume(im).show()`

I get this (left):

<img width="1680" alt="image2" src="https://user-images.githubusercontent.com/56351022/87673386-c399ed00-c774-11ea-8d65-12023cce7c91.png">

On the right I display what I can get with a custom function on MATLAB which is what I want to obtain with vedo.

**Comment by perecanals** [comment]
Is it possible that, since most of my voxels are close to 0, they are almost white? Cause now I think it could be possible that this this I can see in the vedo image corresponds to that red area at the top of my image on MATLAB. Is there a way to tune the colors?

**Comment by marcomusy** [comment]
Yes! You can modify the appearance of both color and transparency simply by setting
```
Volume(..).color(['r','g','b','pink',...]).alpha([0,.5,.4,1]
```
the meaning of the arrays is explained [here](https://vedo.embl.es/content/vedo/base.html?highlight=alpha#vedo.base.BaseGrid.alpha)

let me know if you manage to get something meaningful
