### ISSUE TITLE
`dolfin`-like plotting for vector fields

### ISSUE THREAD

**Issue by bhaveshshrimali** [marcomusy/vedo#184]
Hi Marco, 

Is there an example somewhere that illustrates plotting deformed meshes (with contours) when supplied with a `meshio.Mesh` object (or even otherwise)?  

In short, I am trying to plot a vector field `u` (stored as `meshio.Mesh.point_data`) as done in the [Hyperelasticity demo](https://fenicsproject.org/docs/dolfin/latest/python/demos/hyperelasticity/demo_hyperelasticity.py.html) via the following
```python3
disps = meshio.xdmf.read("disps.xdmf")
# disps.points, disps.cells, disps.point_data

# I tried 
from vedo import Mesh, show
show(Mesh([
    disps.points, np.vstack((
        cell.data for cell in disps.cells if cell.type == "tetra"
        )),
    disps.point_data["u"]
    ]))
```

I will take a look at `vedo.dolfin.py` to understand how the plotting is done there. The slightly odd workaround I have for now is to interpolate the `point_data` into a `dolfin.Function` and then use `vedo.dolfin.plot`  as-is

Thanks

**Comment by marcomusy** [comment]
Hi Bhavesh! That actually looks a clever way of doing it, if your disps.point_data["u"] are displacement vectors you can use `warpByVectors` , eg:

`pip install -U git+https://github.com/marcomusy/vedo.git`


```python
from vedo import *

b = load(datadir+'dodecahedron.vtk') # whatever vedo.Mesh

pts = b.points()*1.2+[2,3,4] # displacements numpy array

d = b.clone().warpByVectors(pts) # make a clone copy and warp it
d.lw(1).c('tomato')

a = Arrows(b.points(), d.points(), s=0.1, c='coolwarm')
a.addScalarBar3D(c='k', title='displacement in μm', titleFont='BPmonoItalics')

# or just
#a = Lines(b.points(), d.points())

show(b, d, a, axes=True)
```
![image](https://user-images.githubusercontent.com/32848391/88522560-d2936180-cff6-11ea-9d0a-119f92876331.png)

**Comment by bhaveshshrimali** [comment]
Thanks Marco. This works perfectly.
