### ISSUE TITLE
Trying to display movement of objects

### ISSUE THREAD

**Issue by RobertKoenig1337** [marcomusy/vedo#187]
Hello, I just started with vedo.
I want to display a cylinder moving through space (its just the start for a bigger simulation). 
```python
######################################################
import vedo

tool = vedo.Cylinder(alpha=0.7)
cube=vedo.Cube()
pl = vedo.Plotter(axes=1)
pl += tool
pl+=cube
p=vedo.vector(0,0,0)
v = vedo.vector(1, 1, 1)

for t in range(1,20):
    print (t)
    p=p+v
    tool.pos(p)
    pl.show()

pl.show(interactive=1)
#################################################
```
All that is happening is that the display window opens and shows me my 2 objects in the first position. Its static and nothing moves. 
When I close the Display Window the vtkOutputWindow opens and prints many lines of text very fast. When I try to interact with the window it crashes. 

In the console I can see, that t was 1 when the static display window appeared and 2 once the vtkOutputWindow appeared. 

What am I doing wrong here? I tried to simplify the gyroscope1.py example. 
Do you have a simple way to animate moving objects and add actors to the running animation? (e.g. add and delete cubes in the animation)

Thank you very much.

**Comment by marcomusy** [comment]
You only missed `Plotter(axes=1, interactive=0)`. Consider this - possibly improved - version:
```python
import vedo

world = vedo.Box(pos=(10,10,10), size=(20,20,20))
world.wireframe().alpha(0) # make it invisible
tool = vedo.Cylinder(alpha=0.7)

plt = vedo.Plotter(axes=1, interactive=0)
plt += world
plt += tool
plt += vedo.Cube()
p = vedo.vector(0,0,0)
v = vedo.vector(1,1,1)

# obtained by pressing "C":
cam = dict(pos=(74.2, -21.0, 16.2),
           focalPoint=(9.22, 9.16, 9.75),
           viewup=(-0.0759, 0.0494, 0.996),
           distance=71.9,
           clippingRange=(40.6, 112))

for t in range(1,20):
    tool.rotateX(5).pos(p)
    plt.show(camera=cam, rate=2) # 2 Hertz speed
    p += v

vedo.interactive()
```

**Comment by RobertKoenig1337** [comment]
Thank you very much. Keep up the great work :D
