### ISSUE TITLE
Updating from vtkplotter to vedo and incresing resolution of Videos

### ISSUE THREAD

**Issue by paolosanchez** [marcomusy/vedo#188]
Hi @marcomusy, 

Hope this message find you well!
I realised recently that you changed the name of the package from vtkplotter to vedo and was wondering if there is a way I can install the new version and make the change easy in my codes to it. I am not that experienced in python and wouldn't like to ruin all my working-codes making changes the way it shouldn't be done. ;) I use anaconda and mainly spyder to run all my codes. 

Finally, I wanted to ask you if there is a way I can increase the resolution of the images that make up the videos in plotter? The rendering of the plot looks very nice in my screen but whenever I record a video it doesn't look as nice as the original plot. 

Hope to hear from you soon, 
best wishes, 
Paolo

**Comment by DeepaMahm** [comment]
Hi @paolosanchez 

You could do 
`pip install -U git+https://github.com/marcomusy/vedo.git
`

**Comment by marcomusy** [comment]
Hi - in principle no modification is needed: you can keep the old vtkplotter installation and add vedo - they will stay completely independent!
If instead you wish to upgrade your existing scripts to vedo that should be relatively easy:
just change `import vtkplotter` to `import vedo`, in case there is some error message that should be easy to fix: at moment the two packages do not differ a lot.

**Comment by marcomusy** [comment]
... about the video resolution you can try with:
```python
from vedo import * 
settings.screeshotScale = 2
```
(frame generation might become slower)
