### ISSUE TITLE
Feature Request - Implement orthogonal, oblique and perspective projection on a user defined plane

### ISSUE THREAD

**Issue by zhouzq-thu** [marcomusy/vedo#191]
Example:
![Screen Shot 2020-08-11 at 11 05 31 AM](https://user-images.githubusercontent.com/9458157/89852994-bda3fa00-dbc2-11ea-803c-ff3fcd46cf29.png)
![Screen Shot 2020-08-11 at 11 05 45 AM](https://user-images.githubusercontent.com/9458157/89852995-bf6dbd80-dbc2-11ea-9465-2ce08f851952.png)

**Comment by marcomusy** [comment]
thanks @zhouzq-thu that looks nice, can you share the code that generates it?

**Comment by zhouzq-thu** [comment]
@marcomusy, please check the pull request.
