### ISSUE TITLE
saving colored mesh to .png

### ISSUE THREAD

**Issue by YimingXu1213** [marcomusy/vedo#199]
Hi Marco, thanks for this wonderful package!

We are working on a project very similar the pic below. However, after we use the `.pointColors` to successfully add colors to the region, is there any way to automatically take a 2d snapshot with it and save as .png/.jpg by script? 

![image](https://user-images.githubusercontent.com/42975821/91231281-d42d7380-e6e1-11ea-880c-808a8f834d53.png)(resource from: https://github.com/mikedh/trimesh/issues/966)

To put it into code, it works well if doing this way:
```
vtk_diff.pointColors(scal, cmap='rainbow').addScalarBar()
vtkplotter.show(vtk_diff, bg="white", axes=0, interactive=True)
```
However, when we are trying to get the 2d snapshot in the way below, it does not work:
```
plt = vedo.Plotter(shape=custom_shape)
vtk_diff.pointColors(scal, cmap='rainbow').addScalarBar()
plt.show(vtk_diff.c('lb'), interactive=False, at=0)
```
May we know what we should modify based on the current code?
Thx!

**Comment by marcomusy** [comment]
Hi Yiming,
thanks for your interest, I would try removing `.c('lb')` because it kills the effect of `pointColors()` by assigning a constant lightblue color :-) 
To generate a screenshot just use
`plt.show(vtk_diff, interactive=False, at=0).screenshot('mypic.png')`

PS: you can update your code by just substituting `import vtkplotter` to `import vedo`

**Comment by YimingXu1213** [comment]
Hi Marco, thanks so much for the reply! That works!!

**Comment by marcomusy** [comment]
fantastic!
ps1: screenshot can produce higher quality images, (e.g. setting `scale=2`)
ps2: the method pointColors() will become cmap() in version vedo 2020.4.0, but the old one will still work.

**Comment by YimingXu1213** [comment]
Hi Marco, a side question:
when we are plotting 3 pics in a row in interactive mode, sometimes it will only show 1 pic.
However, when we are taking the screenshot, all 3 will be captured.

For the code, we are doing sth like this:

```
custom_shape = [
    dict(bottomleft=(0.0, 0.0), topright=(0.30, 1.00), bg='white'),
    dict(bottomleft=(0.3, 0.0), topright=(0.60, 1.00), bg='white'),
    dict(bottomleft=(0.6, 0.0), topright=(1.00, 1.00), bg='white')
]
plt = vedo.Plotter(shape=custom_shape)

plt.show(vtk_mesh1.c('lb'), interactive=True, at=0)
plt.show(vtk_mesh2.c('lb'), interactive=True, at=1)
plt.show(vtk_mesh3, interactive=True, at=2)
```
May we know what's the cause for that and how we can fix it? Thx!

**Comment by marcomusy** [comment]
uhm, in custom_shape the first entry should be the whole canvas (even if you dont draw anything on it), try:
```python
custom_shape = [
    dict(bottomleft=(0.0, 0.0), topright=(1.00, 1.00), bg='white'), # fills the window space
    dict(bottomleft=(0.0, 0.0), topright=(0.30, 1.00), bg='white'),
    dict(bottomleft=(0.3, 0.0), topright=(0.60, 1.00), bg='white'),
    dict(bottomleft=(0.6, 0.0), topright=(1.00, 1.00), bg='white')
]
plt = vedo.Plotter(shape=custom_shape)

plt.show(vtk_mesh1.c('lb'), interactive=True, at=1)
plt.show(vtk_mesh2.c('lb'), interactive=True, at=2)
plt.show(vtk_mesh3, interactive=True, at=3)
```
Check out example:
`vedo -ir multirenderers`

**Comment by YimingXu1213** [comment]
Thanks for pointing out!

We've corrected the first custom_shape and also compared our code to the examples.

However, we still encounter such problems: only showing 1 plot for in the interactive mode.
For interactive=False, all 3 plots are shown but the window will close automatically after 1-2 sec.
But for the saved screenshot, everything looks fine.

Do you have any insights on this?

**Comment by marcomusy** [comment]
If you set `interactive=True` then you must press `q` or `enter` or `spacebar` to make the program proceed.
If `interactive=False` it will not stop so you might add at the end of the program:
```
# ...
plt.show(vtk_mesh3, at=3)
interactive()
```

**Comment by YimingXu1213** [comment]
Thanks Marco, that's really helpful!

**Comment by hhoangg** [comment]
> uhm, in custom_shape the first entry should be the whole canvas (even if you dont draw anything on it), try:
> 
> ```python
> custom_shape = [
>     dict(bottomleft=(0.0, 0.0), topright=(1.00, 1.00), bg='white'), # fills the window space
>     dict(bottomleft=(0.0, 0.0), topright=(0.30, 1.00), bg='white'),
>     dict(bottomleft=(0.3, 0.0), topright=(0.60, 1.00), bg='white'),
>     dict(bottomleft=(0.6, 0.0), topright=(1.00, 1.00), bg='white')
> ]
> plt = vedo.Plotter(shape=custom_shape)
> 
> plt.show(vtk_mesh1.c('lb'), interactive=True, at=1)
> plt.show(vtk_mesh2.c('lb'), interactive=True, at=2)
> plt.show(vtk_mesh3, interactive=True, at=3)
> ```
> 
> Check out example: `vedo -ir multirenderers`

sorry for reopening the issue
I want to output a png image with only a mesh layer and transparent background
I set bg="transparent" it output black background
can you help me to export an image with only a mesh layer and transparent background?

**Comment by marcomusy** [comment]
Hi, you need to use `settings` e.g.:
```python
from vedo import *
settings.screenshotTransparentBackground=True
s = Sphere()
s.show(axes=1).screenshot()
```
![screenshot](https://user-images.githubusercontent.com/32848391/155326666-9e0ff168-b14e-4874-bfe1-3b106134c0db.png)

**Comment by hhoangg** [comment]
> Hi, you need to use `settings` e.g.:
> 
> ```python
> from vedo import *
> settings.screenshotTransparentBackground=True
> s = Sphere()
> s.show(axes=1).screenshot()
> ```
> 
> ![screenshot](https://user-images.githubusercontent.com/32848391/155326666-9e0ff168-b14e-4874-bfe1-3b106134c0db.png)
result
![Output](https://i.imgur.com/8ScPvXj.png)
what i expect
![wish](https://i.imgur.com/1Terl04.png)

**Comment by marcomusy** [comment]
Try

`settings.useDepthPeeling = True`

I wonder if your texture has an alpha channel... that might cause the problem... but I cannot reproduce it without a data sample.

**Comment by hhoangg** [comment]
> PS; you may also try `mymesh.forceOpaque()`

I have tracked and removed the background successfully
but there is still the problem of the outer space that has not been liberated
you can see the image below, the red area is the space that needs to be removed, the blue inner area is my mesh layer, I just want to render the mesh layer without including the empty space which I colored red

Thank you for your support :D

[result](https://i.imgur.com/6PzhP8o.png)

**Comment by marcomusy** [comment]
you can remove a constant border color with PIL:
https://stackoverflow.com/questions/10615901/trim-whitespace-using-pil

**Comment by hhoangg** [comment]
> you can remove a constant border color with PIL: https://stackoverflow.com/questions/10615901/trim-whitespace-using-pil

There is a mistake somewhere
I don't want to remove the red border
That red border is what I added in photoshop, the purpose is to explain that I want to delete the empty area there
below is my sample code (sorry for missing your request for sample code)
[obj and png demo here](https://drive.google.com/file/d/1s2l0iPRAP64MUI-RlM8cqkIrSaEawwRL/view?usp=sharing)

this is a actual results after running the source code
[result.png](https://i.imgur.com/lX5kciI.png)

the result I want (Removed extra space)
[i-wish.png](https://i.imgur.com/65d7rb7.png)

```py
from vedo import settings
from vedo.mesh import Mesh
def start():
    settings.screenshotTransparentBackground = True
    glb = Mesh("test.obj").texture("test-design.png")
    glb.forceOpaque()
    glb.show(interactive=False).screenshot("result.png")
```

**Comment by marcomusy** [comment]
Hi, try one of these 2 options if they fit your needs:

```python
from vedo import Mesh, settings, show

settings.screenshotTransparentBackground = True
mesh = Mesh("test.obj").texture("test-design.png").forceOpaque()

x0,x1 = mesh.xbounds()
y0,y1 = mesh.ybounds()
size = ((x1-x0)*5, (y1-y0)*5)

# plt = show(mesh, size=size, zoom='tight', interactive=0) # or
plt = show(mesh, size=size, zoom=2) # right-click and drag to zoom then press q

plt.screenshot("result.png")
```
you can also middle-click and drag to pan the view.

**Comment by hhoangg** [comment]
thank you a lot

I use argument `zoom='tight'` but not work
Error: `TypeError: Zoom argument 1: must be real number, not str`

**Comment by marcomusy** [comment]
you must have an older version, do
`pip install vedo -U`

**Comment by hhoangg** [comment]
> you must have an older version, do `pip install vedo -U`

```sh
Updating vedo (2022.0.1 -> 2022.1.0)
```

thank you a lot, it's work
I hope it will work with my docker Linux (no interface)
