### ISSUE TITLE
Exporting graphics to primitive vector objects

### ISSUE THREAD

**Issue by shakasaki** [marcomusy/vedo#200]
Firstly, thank you for having such a great tool openly available. I am able to figure out most things out from the examples in https://vedo.embl.es/ but when I try to access the tabs **io** and **pointcloud**, from https://vedo.embl.es/content/vedo/index.html, I get a 403 error..

My question is basically how can I export objects from vedo, like a mesh, into primitive vector files such as a polygon or a line. I am looking at exporting them as vtk extensions in ascii format. 

Thanks for the help!

**Comment by marcomusy** [comment]
> Firstly, thank you for having such a great tool openly available. I am able to figure out most things out from the examples in https://vedo.embl.es/ but when I try to access the tabs **io** and **pointcloud**, from https://vedo.embl.es/content/vedo/index.html, I get a 403 error..

Thanks for your interest in the tool and for your feedback,
Yup! some weird permission problem, should be fixed now.


> My question is basically how can I export objects from vedo, like a mesh, into primitive vector files such as a polygon or a line. I am looking at exporting them as vtk extensions in ascii format.

as simple as
`mesh.write('mymesh.vtk', binary=False)`

**Comment by shakasaki** [comment]
Marco, I really appreciate the speed at which you respond. Any clue whether we will be able to access the io and pointcloud documentation soon?
Thanks again for the great work

**Comment by marcomusy** [comment]
Your're welcome - the docs links are already fixed, are you able to visualize it (try reload the page)?

**Comment by shakasaki** [comment]
Yes, the links now work, thanks. I tried exporting the file as you suggested and then reading it in with paraview but when I save as a binary it works well, but as an ascii, it is not read well by paraview. You can see the difference in the screenshot below (binary is blue points, ascii is white points).

For me its not a big deal, I can save it in binary format. Just letting you know ;)

**Comment by marcomusy** [comment]
interesting... this might point to some version mismatch btw the underlying vtk that vedo uses and the vtk used by paraview..  thanks for reporting it.
