### ISSUE TITLE
'Mesh' object has no attribute 'intersectWith'

### ISSUE THREAD

**Issue by BatYu** [marcomusy/vedo#202]
I am using the latest version of vedo (8.1.2) on macOS, and I bumped into this issue when I try to intersect two mesh with intersectWith(). I tried the given example (surfIntersect.py) but it resulted in the same warning. I wonder if this functionality still exists or the name has changed?

**Comment by BatYu** [comment]
BTW intersectWithLine() works well on my machine...

**Comment by marcomusy** [comment]
aside from the warning are you getting the expected output from surfIntersect.py ?
![image](https://user-images.githubusercontent.com/32848391/91657064-6658c180-eabe-11ea-8841-a8577a609073.png)

**Comment by BatYu** [comment]
Hi, thank you for your quick reply! Sorry I just found that I have made some unclear statements in the previous comment. I can run the example surfIntersect.py correctly and obtain the expected output. However, intersectWith() still fail with the error "'Mesh' object has no attribute 'intersectWith'", while the similar intersectWithLine() works fine on my side.

One of my mesh is loaded from a .stl file, and the other is constructed with Sphere() function. Is there any issue with the format?

**Comment by marcomusy** [comment]
that's very mysterious because the method is there in [mesh module ](https://github.com/marcomusy/vedo/blob/17196b46b3943bfbb982f2de0787e277a3cac56a/vedo/mesh.py#L2023), the format is irrelevant.
try updating with
`pip install --upgrade vedo`
otherwise can you cut and paste the exact error message and maybe an example script where it fails?
thanks!

**Comment by BatYu** [comment]
Sure would happy to. The attached code is here:

import numpy as np
from vedo import *

src_mesh = load('./src_mesh.stl')
origin = np.array([0,0,0])
sphere_mesh = Sphere(pos=origin, r=1)
line = src_mesh.intersectWith(sphere_mesh, tol=1e-06)
print(line)

Am I doing anything wrong with the coding? Any suggestion would be helpful. Thanks!

**Comment by BatYu** [comment]
And the error message is here:

`Traceback (most recent call last):
  File "aTest.py", line 7, in <module>
    line = src_mesh.intersectWith(sphere_mesh, tol=1e-06)
AttributeError: 'Mesh' object has no attribute 'intersectWith'`

**Comment by BatYu** [comment]
ok I just tried upgrading vedo as you suggested, and this issue was fixed surprisingly. I am still curious how this issue occurred and how it was fixed, but anyway I am so glad it has been fixed so easily.

Thank you again for your helpful replies!

**Comment by marcomusy** [comment]
You're welcome :) 
yet, it's soo weird that you get that type of error from having an old version (i don't quite understand that..) but anyway if it's fixed we dont need to worry i guess!
