### ISSUE TITLE
Running in Google Colab

### ISSUE THREAD

**Issue by adityaapte** [marcomusy/vedo#208]
Tried running sample notebook in Colab. For example, the following does not produce any output.

https://colab.research.google.com/drive/1-_Th_PpWIJIrAiY_rJaODCj24mt2v-wn?usp=sharing

**Comment by marcomusy** [comment]
Hi @adityaapte - sorry for the late reply - unfortunately I have no experience with colab I can investigate with the vtk experts if there is a solution to this.
