### ISSUE TITLE
Projection on volume of interest

### ISSUE THREAD

**Issue by horsto** [marcomusy/vedo#211]
Hi! I have the following problem: In my application I want to map a 2D heatmap (numpy array) onto the surface of a mesh. 
![image](https://user-images.githubusercontent.com/7548928/93115181-da4cb980-f6bb-11ea-89a3-ed66fa8c82ea.png)

As in the figure shown above I know the y / z position of that heatmap. Now what I am doing is just creating a "dummy" heatmap volume (the pink cylinder in the figure) by replicating the array in x. What I want is just the projection of my heatmap (the intersection area) on my mesh of interest (the car in the figure above). Is there a way to do this? How would go about it?

**Comment by marcomusy** [comment]
Hi @horsto I'm not exactly sure, if I understand what your aiming for, you might consider mapping your heatmap values onto a mesh by using `interpolateDataFrom()`, check out new examples:
`pip install -U git+https://github.com/marcomusy/vedo.git`

`vedo -r interpolateMeshArray`
`vedo -r interpolateScalar1`
