### ISSUE TITLE
vtkLookupTable: Bad table range

### ISSUE THREAD

**Issue by BatYu** [marcomusy/vedo#212]
Hi, thank you for your efforts on this tool! 

I am trying to accomplish functionality that combines slider with color map. Part of my code is list below:
```
def slider(widget, event):
        value = widget.GetRepresentation().GetValue() 
        my_mesh.pointColors(some_kind_of_values, vmin = value, cmap = 'jet')
plotter.addSlider2D(slider,xxxxxx)
```

But the problem is that when the slider value exceeds some threshold, it will bump into errors, and the error message is list below:
```
ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd865ae2e20): Bad table range: [0.963639, 0.892214]

ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd865ae2e20): Bad table range: [0.963639, 0.892214]

ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd86411f1e0): Bad table range: [0.957363, 0.892214]

ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd86411f1e0): Bad table range: [0.957363, 0.892214]

ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd85d586b40): Bad table range: [0.955794, 0.892214]

ERROR: In /Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkLookupTable.cxx, line 143
vtkLookupTable (0x7fd85d586b40): Bad table range: [0.955794, 0.892214]
```

I wonder how I can handle this problem. Any suggestions or examples will be helpful. Thank you in advance!

**Comment by marcomusy** [comment]
Hi @BatYu are you sure you are not inverting min and max value? 0.963639 > 0.892214
If you don't set it it's guessed from `some_kind_of_values`

**Comment by BatYu** [comment]
Thank you for your quick reply! I am almost certain that I did not invert these two values. Actually the functionality works fine if the slider value is below 0.892214, and errors will only occur if the slider value exceeds that threshold (like 0.9x shown in the message). I have no idea how this upper-limit is calculated as well.

**Comment by marcomusy** [comment]
i guess it happens because `max(some_kind_of_values)` is lower than the value you are passing with the slider with
`plt.addSlider2D(sliderfunc, xmin, xmax)`

thats' at least what the error message says

**Comment by BatYu** [comment]
Yeah ok, I got what you mean and just fixed it. Thanks!

And I have another small question. When it shows me the 3D object, I can see some faces are always in "shadow" (i.e., it is darker) however I rotate the object. I can understand that this helps to construct a 3D perception, but this brings trouble to me when I want to take screenshots for certain faces. Is there a way to fix this?

**Comment by marcomusy** [comment]
Uhm, you maybe should post a screenshot.. maybe you have wrong normals to faces (?)

**Comment by BatYu** [comment]
ok thanks, never mind. Actually I don't think this problem can be fixed, or even this is not a problem at all. I think it has something to do with my 3D model so that some places cannot be 'lit up'.

Thank you so much for your quick responses and helpful advice. Have a good day!
