### ISSUE TITLE
Fixing camera's point of view

### ISSUE THREAD

**Issue by maxvov** [marcomusy/vedo#213]
Hi @marcomusy,

There are stable and shifting objects in my simulation. Now, both of them look moving (either the camera is zooming in/out, or the objects are being scaled in some way).
I would like the image to be fixed and "anchored" to the static objects. Tried playing with `vp.camera.SetFreezeFocalPoint` and `vp.camera.GetFreezeFocalPoint` but no luck.
I solved this issue by adding a large transparent box that is larger than the area of movement of my objects, but I think this is not the most elegant way to do it. Is there a way to solve this more simple? Especially if I want some of the moving objects to go beyond the image.

Thanks!

**Comment by marcomusy** [comment]
Using an invisible box is actually a good way, maybe a better one is to fix the camera and don't let it reset when objects pass the current bounding box.. For this you can press `C` in a scene to print a code template that you can cut and paste in your program, also use `resetcam=False` in show().
