### ISSUE TITLE
Color for 3d continuos function

### ISSUE THREAD

**Issue by edmontz** [marcomusy/vedo#214]
From example plot4_fxy.py..

 I'm attempting to get more than the gold and green  colour  for the my_z(x, y)
function, without resorting to meshes.

 I've tried setting c, in the plot command, to various values without any effect.

**Comment by marcomusy** [comment]
..it a sort of bug, for the moment just add:
`c='blue', texture=None`
will be fixed in the next release, thanks for reporting it.

**Comment by edmontz** [comment]
Okay, able to change to a different, single colour.

 A range of colours, like rgb, dependent upon height.
 Possibly using something like terrain  is sought.

**Comment by marcomusy** [comment]
In the meanwhile you can do something like:
```python
def my_z(x, y): return sin(2*x*y) * cos(3*y)/2
f1 = plot(my_z, texture=None, bc=None)
f1.unpack(0).addElevationScalars().cmap('terrain')
f1.show()
```
![image](https://user-images.githubusercontent.com/32848391/93835455-93446280-fc7f-11ea-97eb-62c23f1ffeb7.png)

**Comment by edmontz** [comment]
That's quite  cool.
 Using a slightly different function, and plot limits a valid result is also  possible.

 def my_z(x, y):
	r=np.sqrt(x*x+y*y)*np.pi
	z=1
	if r > 0: z=np.sin(r)/r
	return 2*z

f1 = plot(my_z, xlim=[-4,4], ylim=[-4,4], zlim=[-1,None], texture=None, bc=None)
f1.unpack(0).addElevationScalars().cmap('terrain')
f1.show()

**Comment by marcomusy** [comment]
Yes! In your case you can also increase the resolution and give it a 'glossy' appearance with:
```python
f1 = pyplot.plot(my_z, xlim=[-4,4], ylim=[-4,4], texture=None, bc=None, bins=(500,500))
f1.unpack(0).addElevationScalars().cmap('terrain').lighting('glossy')
```
![image](https://user-images.githubusercontent.com/32848391/93870116-06c09100-fccd-11ea-90c5-2fb6fdae5377.png)
