### ISSUE TITLE
perpendicular isolines, x label  

### ISSUE THREAD

**Issue by edmontz** [marcomusy/vedo#216]
Isolines are plotted nicely, however to complete the overlay,  lines that run perpendicular
to these are required.

 Also information on the x axis is displayed behind the graph.

**Comment by marcomusy** [comment]
that's not possible (i don't think it is actually desirable..), either you use `f1.lineWidth(0.1)` or draw gradient segment lines as in `vedo/examples/basic/isolines.py`.

**Comment by edmontz** [comment]
Okay, thought that might be the instance.

  I discovered a similar situation with MayaVi and wrote an overly involved piece of python
code to overlay a grid of tubes of a selectable diameter.
