### ISSUE TITLE
How to make the iso-surface closed?

### ISSUE THREAD

**Issue by NeuZhangQiang** [marcomusy/vedo#217]
I am using ```Volume(mask).isosurface(1)``` to extract the surface from mask, and the result is show as following:

![image](https://user-images.githubusercontent.com/62534955/93984986-0dc3ce00-fdb7-11ea-87ff-370188678be1.png)

The extracted result is not closed. How can I make the surface closed?

It seems that vtkvmtkCapPolyData may help. 
```
    vtkvmtkCapPolyData - Add caps to boundaries.
    
    Superclass: vtkPolyDataAlgorithm
    
    This class closes the boundaries of a surface with a cap. Each cap is
    made of triangles sharing the boundary baricenter. Boundary
    baricenters are added to the dataset. It is possible to retrieve the
    ids of the added points with GetCapCenterIds. Boundary baricenters
    can be displaced along boundary normals through the Displacement
    parameter. Since this class is used as a preprocessing step for
    Delaunay tessellation, displacement is meant to avoid the occurence
    of degenerate tetrahedra on the caps.
```

**Comment by marcomusy** [comment]
Try `Volume(mask).isosurface(1).cap()` if that doesn't work you may try using the pymeshfix example [here](https://github.com/marcomusy/vedo/blob/master/examples/other/remesh_meshfix.py).

**Comment by NeuZhangQiang** [comment]
Thank you very much! It helps a lot.
