### ISSUE TITLE
cutWithMesh

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#221]
Dear,

I followed the example "pointsCutMesh2.py" to create a spline and ribbon to cut a mesh. However, I realized the cut results sometimes are not accurate and weird. For example, the result in "pointsCutMesh2.py" (see below). Some parts are outside of the ribbon, and it's connected to the part inside the ribbon so I cannot use the split function to remove wrong parts.

Any suggestion? Many thanks!

![mesh_cut_results](https://user-images.githubusercontent.com/9615481/94749755-93fd8880-0352-11eb-9dcb-406b11a8b62b.jpg)

**Comment by marcomusy** [comment]
Hi, I guess it is due to the imperfect closure of the ribbon and/or the normals. I cannot reproduce though the above output from the `pointsCutMesh2` example... what version of vtk do you have?
Another possibility is to use points instead of a surface to cut - this is example `pointsCutMesh1` .. but maybe you already tried it (?)

other variations to try could be:
```python
# ...

# and a ribbon-like surface using cell normals
rb = Ribbon(ptsmc).bc('green')

#cut with the ribbon and then with a yz plane
scut = s.clone().c('blue').alpha(0.7).cutWithMesh(rb, invert=True)
```

or using `KSpline(pts, closed=True)` or even `Line(pts, closed=True)` instead of `Spline()`.

**Comment by Tai-Hsien** [comment]
Hello macromusy,
My vtk version is 8.1.2. I will try your suggestions and let you know the results! Thanks!

**Comment by Tai-Hsien** [comment]
Hello macromusy,
I tried your suggestions:
1) `rb = Ribbon(ptsmc).bc('green')`
This makes the normal vectors of ribbon almost the same as the mesh (see below), so the cut results become something else and not what I expect.
![ribbon](https://user-images.githubusercontent.com/9615481/94759256-61ad5480-036d-11eb-8ef2-eecd7f82780e.jpg)

2) I also tried KSpline before, but the kspline have too many undesired connections among points and also results in undesired cut results.

3) I also tried the pointLoop. My code is as follows (in pyqt5):
```
ptsmc = self.spline.points()
self.selection = self.mesh.clone().cutWithPointLoop(ptsmc, invert=False)
```
but I always got vtk error saying "vtkSelectPolyData (000013EBA19BE00): Can't follow edge"

Is this because of my vtk version? What I actually plan to develop is a GUI program which draw a free-hand ROI on mesh. For this purpose, do you have any suggestion to achieve? Thanks!

**Comment by Tai-Hsien** [comment]
Hello marcomusy,
What's your vtk version? maybe I can try use the same one to see if I can get the right result in pointsCutMesh2.py

**Comment by marcomusy** [comment]
I use the same version! I'm investigating... It's very strange that with the same version you can't reproduce the output of the example though

`vedo -r pointsCutMesh1`

![image](https://user-images.githubusercontent.com/32848391/94818421-6706af80-03fe-11eb-925a-76242909ab24.png)

**Comment by Tai-Hsien** [comment]
`pointsCutMesh1` works for me, but when I applied this idea to my project, I got Can't follow edge error. The source code is as follow
`ptsmc = self.spline.points()`
`self.selection = self.mesh.clone().cutWithPointLoop(ptsmc, invert=False)`
where ptsmc is all spline points (e.g., 120 points). It's weird...

For `pointsCutMesh2`, the result is weird. My `pointsCutMesh2` source code is as follows:
```
"""Create a closed spline from a bunch of
random points on a sphere then create a ribbon
surface and cut through the sphere with that"""
from vedo import *

s = Sphere().computeNormals().alpha(0.2).lw(0.1)

sc = s.points()
sn = s.normals(cells=True) # cell normals

# pick a few points
pts = (sc[10], sc[15], sc[129], sc[165], sc[10])

#build the spline
# ptsm = Spline(pts, smooth=0).c('k').lw(4)
ptsm = KSpline(pts).c('k').lw(4)
ptsmc = ptsm.points()

# and a ribbon-like surface using cell normals
splinen = []
for p in ptsmc:
    iclos = s.closestPoint(p, returnIds=True)
    splinen.append(sn[iclos])
pts0 = ptsmc - 0.1*vector(splinen)
pts1 = ptsmc + 0.2*vector(splinen)
rb = Ribbon(pts0, pts1).bc('green')

#cut with the ribbon and then with a yz plane
scut = s.clone().c('blue').alpha(0.7).cutWithMesh(rb)

show(s, Points(pts), ptsm, rb, scut, __doc__, axes=1)
```
and result is as follows, where you can see the undesired part connected with the selected part.
![pointsCutMesh2](https://user-images.githubusercontent.com/9615481/94819910-d6b07680-03cd-11eb-80be-f7a8b8bf3363.png)

**Comment by Tai-Hsien** [comment]
I just realized one problem for `vtkSelectPolyData (000013EBA19BE00): Can't follow edge`.
It seems like `ptsmc` are not on the mesh surface.

**Comment by Tai-Hsien** [comment]
Hello macromusy,
I like the way you suggest, at least the ribbon is more smooth now. I need to test it more to see if it can produce correct cut every time.
As you post, there is still a undesirable part. I tried to use `splitByConnectivity` function to select the one nearest to the ribbon, as follows.

```
                    # split the meshes and select the closest one
                    meshes = self.selection.splitByConnectivity(maxdepth=500)
                    rb_cm = self.rb.centerOfMass()
                    dis = []
                    for i_mesh in meshes:
                        cm_i_mesh = i_mesh.centerOfMass()
                        dis.append(np.linalg.norm(rb_cm-cm_i_mesh))
                    dis = np.asarray(dis)
                    self.selection = meshes[np.argmin(dis)]
```
Sometime this way works to remove the undesirable part; however, sometimes I obtain an empty list of meshes. Do you have any idea why `self.selection.splitByConnectivity(maxdepth=500)` outputs empty sometimes?

**Comment by marcomusy** [comment]
..even better - maybe - you can use `cutWithPlane()` along the already calculated normal, e.g.
```python
# ...
orig = np.min(ksp.points(), axis=0)
scut.cutWithPlane(normal=vmean, origin=orig)
s.cutWithPlane(normal=vmean, origin=orig)
show(s, ksp, rb, scut, Arrow([0,0,0], vmean), axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/94846441-6df2e980-0421-11eb-889d-580e6d25dba2.png)

i'm not sure why you get empty list, i'm afraid i have no way to check..

**Comment by Tai-Hsien** [comment]
Now, I use the `vtkPolyDataConnectivityFilter` to extract the right part after `cutWithMesh`.

```
                    self.selection = self.mesh.clone().c('blue').alpha(1.0).cutWithMesh(self.rb)

                    # split by vtk
                    connect = vtk.vtkPolyDataConnectivityFilter()
                    connect.SetInputData(self.selection._polydata)
                    connect.SetExtractionModeToClosestPointRegion()
                    connect.SetClosestPoint(self.rb.centerOfMass())
                    connect.Update()

                    self.selection = Mesh(connect.GetOutput())
```

This works best based on my test right now! The discussion inspires me a lot! Many thanks!

**Comment by Tai-Hsien** [comment]
Hello macromusy,
One more question. What is the best/efficient way to refresh a Mesh object in a plotter when the Mesh has been changed (e.g., cell array represent the cell color)? Right now, I remove the old one and add a new one.

**Comment by marcomusy** [comment]
HI, if you only change the color or colormap (just to make an example) you can reuse the same Mesh object, either using the show() command or render().

**Comment by Tai-Hsien** [comment]
Sorry I didn't describe it clearly... What if I want to change an cell array based on a list of cell index (e.g., cell_index=[3, 5, 7]) in the Mesh object and use the value of cell array to represent color, as well as refresh the plotter when the value has been changed?

**Comment by marcomusy** [comment]
- just overwrite the existing array, e.g.
```python
from vedo import *
man = load(datadir+"man_low.vtk").lineWidth(0.1)

# using addCellArray (defaults to jet cmap)
scals = man.cellCenters()[:, 0]
man.addCellArray(scals, "mycellscalars")
# man.addScalarBar()
show(man)

scals = man.cellCenters()[:, 2]
man.addCellArray(scals, "mycellscalars") # same name to overwrite
show(man)

#using cmap
scals = man.cellCenters()[:, 0]
man.cmap('hot', scals, on='cells')
show(man)

scals = man.cellCenters()[:, 2]
man.cmap('bone', scals, on='cells')
show(man)
```

- does the example: `examples/basic/pca.py` work for you? (try to play with the `tol` parameter)
![image](https://user-images.githubusercontent.com/32848391/95023611-4fd5f500-067e-11eb-849b-63e89eba1a82.png)

**Comment by Tai-Hsien** [comment]
Overwriting the existing array works perfect! Thanks a lot!

I have updated my vtk to 8.2.0, and pca.py works for me, but I don't have 8.1.2 to test now. However, I ran my own project (same code) on two different computers with vtk=8.1.2 and vtk=8.2.0, and only 8.2.0 returns the correct results. Maybe the default of `tol` changed in vtk=8.2.0.
