### ISSUE TITLE
Mesh: merge vs Assembly

### ISSUE THREAD

**Issue by icemtel** [marcomusy/vedo#222]
Hi, and thank you for your package.

I had a small issue understanding why my mesh objects lose colors after I merge them. 
Apparently, only properties of the first mesh are used for the whole mesh after merging (tested with color and lineColor). Maybe this should be added to the documentation?

And I already found out the correct way to do it is to use `assembly.Assembly` instead. Below is the example (would it be useful to add it to the repo?)

```
'''
vedo mesh: `merge` vs `+` vs `Assembly`
'''

import vedo
import numpy as np

# Define geometry
verts = np.array([(50, 50, 50), (70, 40, 50), (50, 40, 80), (80, 70, 50)])
faces = np.array([(0, 1, 2), (2, 1, 3), (1, 0, 3)])

# Build the polygonal Mesh object:
mesh = vedo.Mesh([verts, faces], c='red')
# Create a copy, shift it; change color
mesh2 = vedo.Mesh([verts + 50, faces], c='blue')

# Merge creates a new mesh, color - red
mesh_all = vedo.merge(mesh, mesh2)
print(type(mesh_all))
# Show
plotter = vedo.show(mesh_all, axes=1)  # -> all red
plotter.close()

# "+" creates an Assembly
mesh_all = mesh + mesh2
print(type(mesh_all))
# Show
plotter = vedo.show(mesh_all, axes=1)  # -> red and blue
plotter.close()

# Equivalently, can call Assembly
mesh_all = vedo.assembly.Assembly(mesh, mesh2)
print(type(mesh_all))
# Show
plotter = vedo.show(mesh_all, axes=1)  # -> red and blue
plotter.close()
```

If you find it useful, I can create a pull request.

**Comment by marcomusy** [comment]
Hi @icemtel - yes you got it right! If you use merge the 2 meshes become a single one (even if they are physically disconnected) so the result only accepts a single color/transparency/lighting etc
Whereas Assembly is a "group" of meshes which maintains their individuality.

Another way to create mesh2:
`mesh2 = mesh1.clone().x(50).c('blue')`


The example script looks good to me, feel free to add it to examples/basic if you wish!
