### ISSUE TITLE
[BUG] Segmentation fault (core dumped) while setting LD_PRELOAD with libGLEW.so

### ISSUE THREAD

**Issue by TooSchoolForCool** [marcomusy/vedo#225]
Every time when I set
```bash
export LD_PRELOAD=$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/libGLEW.so
```
`vedo` will crash if I use the `vedo.Plotter`.

For example, the following code will crash, and prompt `Segmentation fault (core dumped)` if I set the `LD_PRELOAD` with `libGLEW.so`.

```python
import vedo

plt = vedo.Plotter(axes=1, interactive=False)
plt += vedo.Box(pos=(0.5, 0.5, 0.5), size=(1, 1, 1))

for i in range(100):
    print("Step {}".format(i))
    plt.show(rate=20)

vedo.interactive()
```
The program will crash at Step 0.

However if I do NOT set the variable `LD_PRELOAD` with `libGLEW.so`, everything works well.

Is it an internal bug of the `vedo` library? I was wondering how to resolve this issue, coz I do not want to manually cancel the `LD_PRELOAD` variable (another library require setting the `LD_PRELOAD` variable with `libGLEW.so`) every time before vedo.

Thanks for any info :).

**Comment by marcomusy** [comment]
Hi Zeyu
what is your OS? On my ubuntu it seems to work ok with or w/o the export.
Try if you can reproduce the problem with a pure vtk script:
```python
#!/usr/bin/env python
#
import vtk
import time

cone = vtk.vtkConeSource()
cone.SetHeight(3.0)
cone.SetRadius(1.0)
cone.SetResolution(10)

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(500, 500)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

for i in range(0, 180):
    time.sleep(0.01)
    renWin.Render()
    ren.GetActiveCamera().Azimuth(1)

iren.Start()
```

One possible workaround would be to prepend
`LD_PRELOAD='' vedo`
or 
`LD_PRELOAD='' python somescrpt.py`

**Comment by TooSchoolForCool** [comment]
Hi Marco,

The system is Ubuntu 16.04.

I tested your script, still does not work. When I set `LD_PRELOAD` with `libGLEW.so`, the whole program crashed with Segmentation fault (core dumped).

**Comment by marcomusy** [comment]
I see. It's strange though that `LD_PRELOAD='' python somescrpt.py` doesn't work (?)

If the above gives the same error it means the problem is in vtk, and it has nothing to do with `vedo`.
You might want to ask vtk experts on [discourse](https://discourse.vtk.org/).

**Comment by TooSchoolForCool** [comment]
`LD_PRELOAD='' python somescrpt.py` works, but I am looking for a solution that do not need such manual effort to cancel the `LD_PRELOAD` variable. 

Again, thank you so much, Marco :). I will look into the `vtk` then.
