### ISSUE TITLE
Convert CellArray to numpy array

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#226]
Hello macro,

In vdeo, I know to add a new CellArray by using addCellArray. What if I want to convert a CellArray to a numpy array?

Also, is there any way that we can delete an existing CellArray? Many thanks!

**Comment by marcomusy** [comment]
> What if I want to convert a CellArray to a numpy array?

you can do it with eg. `mesh.getCellArray('name_of_array')`

you can also get a list of the existing ones with `mesh.getArrayNames()`

> Also, is there any way that we can delete an existing CellArray? Many thanks!

unless you have memory issues i would not care to delete any array, there is no vedo function doing it (maybe I should add it!), anyway this line should work:
`mesh.polydata().GetPointData().RemoveArray('name_of_array')`

**Comment by Tai-Hsien** [comment]
They work perfectly! Many thanks!
