### ISSUE TITLE
Could not find example to adjust threshold

### ISSUE THREAD

**Issue by mit10000** [marcomusy/vedo#229]
First thanks for sharing this wonderful project.

I can use command line

vedo https://vedo.embl.es/examples/data/head.vti

to see head isosurface and adjust threshold. But could not find any scrip in example to do this. 
Could you please help?

**Comment by marcomusy** [comment]
Thanks for your interest :) There is already a [function](https://github.com/marcomusy/vedo/blob/2a407db8a0cfe39945d0d3bb1fb2c0f47f48daa5/vedo/applications.py#L432) that does that, but you can customize it the way you like:
```python
from vedo import Volume
from vedo.applications import IsosurfaceBrowser

vol = Volume('data/head.vti')
plt = IsosurfaceBrowser(vol, c='gold')
plt.show()
```
![image](https://user-images.githubusercontent.com/32848391/96276079-d5d53280-0fd2-11eb-9746-93c22ebd6501.png)

**Comment by mit10000** [comment]
Thanks @marcomusy !
The only thing I need to do is

from vedo import datadir
vol = Volume(datadir+'data/head.vti')

Works!

**Comment by marcomusy** [comment]
I guess it's:
```python
from vedo import Volume, datadir

vol = Volume(datadir+'head.vti')
```

**Comment by mit10000** [comment]
You are right.
