### ISSUE TITLE
using `vedo==2020.3.4 with dolfin inside Jupyter (docker container)

### ISSUE THREAD

**Issue by bhaveshshrimali** [marcomusy/vedo#231]
Hi Marco, 

I was trying to use `vedo.dolfin.plot` to make 3D plots in Jupyter inside of a [docker container](https://hub.docker.com/r/bhaveshshrimali/dolfin_superlu/tags). I have installed `k3d` using `pip` but I'm unable to render the plot. I am using an older version due to `vtk` version conflicts with `dolfin 2019.2.0` .... 

```python3
from dolfin import *
import numpy as np
from vedo.dolfin import plot as vplot, show as vShow, embedWindow
from vedo import settings
mesh  = UnitCubeMesh(5,5,5)
V = VectorFunctionSpace(mesh, "CG", 2)
u = Function(V)
u.vector()[:] = np.linspace(0,1,V.dim())
embedWindow("k3d")
vplot(u)
mesh = settings.plotter_instance.actors[0]
mesh.lw(0)
vShow(mesh, newPlotter=True, axes=1)
```

but this just gives

```
Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[0.0357292797817024…
```

Would you happen to know what could be going wrong?

**Comment by marcomusy** [comment]
Hi Bhavesh, 
the message seems to say that the graphical canvas is returned but it is not rendered as such.

does it work outside jupyter? (e.g.setting `embedWindow(False)`). Unfortunately I have no experience with docker.. at some point I had this magic recipe:
```
sudo apt install libgl1-mesa-dev xvfb

export DISPLAY=:99.0
which Xvfb
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
sleep 3
exec "$@"
```
but i'm not sure if it applies in this case.

ps: `dolfin.plot()` has many keywords, one is `lw` so this should also work
`vplot(u, lw=0, axes=1)`
also, vplot already returns the `Plotter` object.

**Comment by bhaveshshrimali** [comment]
>  at some point I had this magic recipe:

I can give this a try. Thanks!

> does it work outside jupyter?

It has worked outside Jupyter without any problems in the past (though not Docker but Singularity). 

This is a slightly esoteric way I am trying primarily to cater to windows users for a demo (who can pull the image, run fenics on jupyter (inside Docker), and vedo can render the embedded plots).
