### ISSUE TITLE
I want to get a colorful 3D reconstruction image...

### ISSUE THREAD

**Issue by hulihan-start** [marcomusy/vedo#233]
When I read the nii image, I could only get a monochrome image. However, in order to show the results of cell segmentation more clearly, I want to dye different labeled cell regions (markers exist in my file)

**Comment by marcomusy** [comment]
uhm .. not sure if I understand.. your nii file is volumetric data so what scalar do you want to colorize?
You can specify a color map with e.g. `myvolume.color([(0,'green'), (2,'blue'), (6.5,'r')])`

Try:
`pip install -U git+https://github.com/marcomusy/vedo.git` 

and check out this [example](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/colorize_volume.py).

![image](https://user-images.githubusercontent.com/32848391/96580110-1afdab00-12d8-11eb-9988-ea48be375c1a.png)

**Comment by hulihan-start** [comment]
When I use the method you suggested, I got an error like: 

if c[0] <= 1 and c[1] <= 1 and c[2] <= 1:
TypeError: '<=' not supported between instances of 'str' and 'int'

The code of my workspace is :

from vedo import *
vol = load(path)
vol.color([(0,'yellow'), 'violet', 'green', 'blue'])
vol.show()

Without numbers, it runs but just like a mixed-figure not the segmentation image I expected.

**Comment by marcomusy** [comment]
You have not done:
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by hulihan-start** [comment]
oooooo....
My Pycharm is terminated when run the program...
What's wrong with this...

**Comment by marcomusy** [comment]
try adding
```python
from vedo import embedWindow
embedWindow(False)
```
