### ISSUE TITLE
2d graphics get pixel

### ISSUE THREAD

**Issue by edmontz** [marcomusy/vedo#234]
As many of you may be aware, qbasic has 2d graphics capability.

  Having taught myself python, at least some aspects of the language,
I now use a python graphics library; plotly. I'm also learning vedo.

 Now I've encountered an instance where  I need to get information about a
point [pixel] from a graph I've drawn to a window. QBasic has such,  plotly
doesn't,  tkinter  may  as may vedo.

 How might I get the colour of a pixel using vedo.

**Comment by marcomusy** [comment]
Cool feature to implement. Try:

`pip install -U git+https://github.com/marcomusy/vedo.git`

then pressing `I` (shift-i) anywhere in the rendering window will give you the RGB color under the mouse:

![image](https://user-images.githubusercontent.com/32848391/96586908-ed1d6400-12e1-11eb-9589-adb95bf6c810.png)

**Comment by edmontz** [comment]
How might I implement this as a command from within a python script.

  Having drawn a line and then attempting to find a pixel RGBA or colour value on that line using something like c=get_pixel(x,y). Potentially x,y might not be
integer values.

**Comment by marcomusy** [comment]
try
```python
import vtk
from vtk.util.numpy_support import vtk_to_numpy
import vedo

def myfnc(key):
      x, y = plt.interactor.GetEventPosition()
      w2if = vtk.vtkWindowToImageFilter()
      w2if.SetInput(plt.window)
      w2if.ReadFrontBufferOff()
      w2if.Update()
      nx, ny = plt.window.GetSize()
      arr = vtk_to_numpy(w2if.GetOutput().GetPointData().GetScalars())
      arr = arr.reshape(ny,nx,3)
      print('Pixel =', [x,y], ' RGB =', arr[y,x].tolist())
      return arr[y,x]

plt = vedo.Plotter(axes=1)
plt.keyPressFunction = myfnc
s = vedo.Sphere()
s.cmap('jet', s.points()[:,1])
plt.show(s)
```
