### ISSUE TITLE
Vedo requires vtk<9.0.0, which is not available for Python 3.8

### ISSUE THREAD

**Issue by CMengich** [marcomusy/vedo#235]
When installing Vedo on Python 3.8, Windows 10, this error pops up (pip install vedo)

Collecting vedo
  Using cached vedo-2020.4.1.tar.gz (9.5 MB)
ERROR: Could not find a version that satisfies the requirement vtk<9.0.0 (from vedo) (from versions: 9.0.0, 9.0.1)
ERROR: No matching distribution found for vtk<9.0.0 (from vedo)

Previous version, vtk==8.1.2 has no wheels for python 3.8 and above

**Comment by marcomusy** [comment]
Thanks a lot for reporting this.
Actually `vedo` works ok also with vtk9, although there might be some transparency issues (that's the reason of the requirement).  Try
`pip install vtk`
`pip install vedo  # ignore vtk warning`

 transparency issues can be partially solved by adding:
```python
from vedo import settings
settings.useDepthPeeling= True
```

**Comment by CMengich** [comment]
Thanks. Its working fine.

**Comment by luisflarota** [comment]
Hi Marco, I'm having the same issue. However when I try:

`pip install vedo # ignore vtk warning`

It says:  Invalid requirement: '#'

**Comment by CMengich** [comment]
Use pip install vedo --no-dependencies
Then install dependencies afterwards.
Should work.

**Comment by luisflarota** [comment]
Thanks!
