### ISSUE TITLE
Python 3.8: no version for vtk<9.0.0

### ISSUE THREAD

**Issue by vigji** [marcomusy/vedo#236]
Trying to use latest vedo on a Python 3.8 env (which should be supported in principle from the setup file right?) I run into this problem:

`vedo 2020.4.1 requires vtk<9.0.0, but you'll have vtk 9.0.0 which is incompatible.`

I guess I need to work on a 3.7 env? Is there any way around this? Can I just ignore the problem? The little amount off stuff I tested seems fine.

**Comment by marcomusy** [comment]
Yes - you can ignore the warning, most of the stuff will still work.
For transparent objects you might want to add `useDepthPeeling=True`.
In the next release the restriction will be dropped.

**Comment by pmav99** [comment]
Any idea when a new version is going to be released?

**Comment by marcomusy** [comment]
about end of next week!
