### ISSUE TITLE
scalar bar size in offscreen renders

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#237]
When I embed a plotter with scalarbar in a jupyter notebook then the size of the scalarbar is tiny:

![image](https://user-images.githubusercontent.com/34062862/97984802-903ca600-1dd7-11eb-96e0-7a007718f717.png)

I assume this has something to do with the image being rendered at an inflated size and the font size of the scalarbar not being adjusted accordingly?

**Comment by marcomusy** [comment]
Are you using `embedWindow('2d')`? (it might be that the screenshot is scaled up while the `vtkActor2D` object is not)

**Comment by RubendeBruin** [comment]
Yes, using

```python
        vp.embedWindow(backend='2d')
        plotter = vp.Plotter(offscreen=True, interactive=False)
        plotter = self._fill_plotter(plotter)
        return plotter.show(camera = camera)
```

**Comment by marcomusy** [comment]
I could fix it by increasing the size of the 2d scalarbar in this way:
```python
import vedo
vedo.embedWindow('2d')
# vedo.settings.screeshotScale=-1 # reset the scaling for '2d'

plotter = vedo.Plotter()

s = vedo.Sphere().cutWithPlane(normal=(1,1,1))
scals = s.points()[:,2] # use z-coords to color vertices
s.cmap('Set3', scals)
s.addScalarBar(titleFontSize=48)
s.scalarbar.SetMaximumWidthInPixels(60*4)
s.scalarbar.SetMaximumHeightInPixels(250*4)

vedo.show(s, viewup='z', axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/97996298-ddc10f00-1de7-11eb-9aad-3a030b2f77c8.png)

one alternative option is to reset the upscaling with:
`vedo.settings.screeshotScale=-1`
(but on my ubuntu system it looks ugly because the image loses the antialiasing).
I will add the size as a keyword argument in `addScalarBar`.

**Comment by RubendeBruin** [comment]
Hi @marcomusy , thanks for the support.
For my project I fixed it by setting the screenshotScale and simply increasing the size of the offscreen plotter window.

Would you like to keep this issue open? Or do you think this is not likely to be fixed?

**Comment by marcomusy** [comment]
I'll try to have it fixed for the next release, thanks for reporting!
