### ISSUE TITLE
Creating surface from Bezier curves

### ISSUE THREAD

**Issue by LaurabelleKay** [marcomusy/vedo#238]
Hello, I am trying to create a mesh from a set of bezier curves.

I create a set of separate curves and merge them to create one mesh, then use ``` ln.triangulate().c('lightsalmon').lw(0.1)``` to create the surface, the result is:
![image](https://user-images.githubusercontent.com/17315842/98051954-d1d64c80-1de9-11eb-9255-aa690956df40.png)

Is there a way to create a surface with more uniform triangles? Something similar to this:
![image](https://user-images.githubusercontent.com/17315842/98052018-fa5e4680-1de9-11eb-8dcd-88c9c2290c9c.png)

Thanks

**Comment by marcomusy** [comment]
Hi - the method `triangulate()` is only meant to fill the inside space but it doesn't create internal vertices.
You might consider using additional libraries like e.g. [pygmesh](https://github.com/nschloe/pygmsh) for mesh generation.

**Comment by LaurabelleKay** [comment]
Oh I see, I'll give pygmesh a go. 

Thanks!
