### ISSUE TITLE
Could not implement light effect

### ISSUE THREAD

**Issue by mit10000** [marcomusy/vedo#239]
Thanks for sharing and previous quick answers. 
I tried to implement something like 

https://www.glowscript.org/#/user/GlowScriptDemos/folder/Examples/program/BoxLightTest

which is based on vpython ( it is official example of vpython.org).
Seems it's hard to define light in vedo. Could you please help on this?
Thanks.

**Comment by marcomusy** [comment]
Hi thanks for raising the issue, Indeed creating a dedicated class for scene lighting is something that would be nice to have and relatively painless, and only marginally supported in `vedo` at present.
At the moment one has to go back to native [VTK](https://vtk.org/doc/nightly/html/classvtkLight.html) methods.
I can remember we have 2 examples dealing with lights:
https://github.com/marcomusy/vedo/blob/master/examples/basic/lights.py
https://github.com/marcomusy/vedo/blob/master/examples/basic/specular.py

**Comment by mit10000** [comment]
@marcomusy Thanks for your answer. I have tried the examples you mentioned. Maybe I will try VTK lights operations.
