### ISSUE TITLE
specifying the radius of points

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#241]
Hi @marcomusy 

While generating a network, the radius of the points are specified in the following manner
`pts = Points(nxpts, r=12)`

I would like to know if this can be modified later on, for instance, while plotting the network.

```
pts1 = pts.clone().cmap('Blues', values[i], vmin=vmin, vmax=vmax)
plt.show(pts1, edg, txt, box, at=i)
```

I would like to know if there is a way to change the radii of points in pts1 e.g. from 12 to 1.

**Comment by marcomusy** [comment]
yes - you should be able to change it with eg:
`pts.pointSize(10)`

**Comment by DeepaMahm** [comment]
Thanks so much. This helps. We shall close this issue :)
