### ISSUE TITLE
Can't run/debug within vscode

### ISSUE THREAD

**Issue by jonnymaserati** [marcomusy/vedo#242]
Frustratingly, I can't get my code to run from within vscode, so I'm not able to debug within vscode which is slowing down my development...

The issue arises when I try to initiate `vedo.plotter.Plotter()` when running from vscode, when I get this error:
```
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 1223
vtkXOpenGLRenderWindow (0x5587f7b42cf0): bad X server connection. DISPLAY=Aborted (core dumped)
```
If I run the same code directly in terminal, it runs fine, so this is an issue with the way vscode is configured, but I can't find any answers online.

This seems to be an issue on all vscode installations I have running on Ubunut (in this case 20.04). Here's the vscode info:
```
Version: 1.51.0
Commit: fcac248b077b55bae4ba5bab613fd6e9156c2f0c
Date: 2020-11-05T18:16:10.374Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-52-generic snap
```
Similarly, I'm unable to open up browser windows from vscode (for example plotly `fig.show()` and selenium `driver = webdriver.Chrome(chromedriver)` won't open browser windows. I get the following error with selenium:
```
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
```
Similarly, this works fine direct from the terminal.

I'd really appreciate any help!

Jonny

**Comment by marcomusy** [comment]
Thanks for reporting the issue.
It seems to work fine though in my ubuntu when opening a terminal from inside vscode.
Does this code generate the same error?
```python
#!/usr/bin/env python
#
import vtk

cone = vtk.vtkConeSource()
cone.SetHeight(3.0)
cone.SetRadius(1.0)
cone.SetResolution(10)

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(500, 500)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

for i in range(0, 180):
    renWin.Render()
    ren.GetActiveCamera().Azimuth(1)

iren.Start()
```

**Comment by jonnymaserati** [comment]
Thanks for the reponse @marcomusy 

Yep, still get an error, at line 28 `renWin.Render()`.

```
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 273
vtkXOpenGLRenderWindow (0x55f80da75cd0): bad X server connection. DISPLAY=Aborted (core dumped)
```
Although it's not the same error... the line number in the error message is different.

It runs fine direct from the terminal/command line.

**Comment by marcomusy** [comment]
So it's unrelated to `vedo` i guess, it's the upstream vtk which is failing - it  seems it cannot find the display. You may wish to try:
`sudo apt install xvfb libgl1-mesa-dev`

**Comment by jonnymaserati** [comment]
Thanks @marcomusy. I tried installing that package but it doesn't change running in vscode unfortunately.

You're correct, this is not an issue with `vedo`.

**Comment by jonnymaserati** [comment]
Seems the issue is with the default `console` setting on vscode and changing it in `launch.json` fixed the problem, in my case to `externalTerminal` with the `Terminal > External: Linux Exec` setting set to the default  `x-terminal-emulator`.

Here's my `launch.json` settings:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "externalTerminal"
        }
    ]
}
```
Hope this helps anyone else who may be dealing with similar issues.
