### ISSUE TITLE
Moving camera in animations

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#244]
Hey Marco, 

I'm struggling with getting the camera to move nicely in animations.
I can get it to to rotate, and I can interpolate between two cameras (similar to what you proposed in https://github.com/marcomusy/vedo/issues/80), but I can't get it to pan: I'd like to move the camera between two points without it rotating or anything else changing. 

If I define two sets of camera parameters
```python
cam1 = {
    "position": (-8009, -3887, 17887),
    "focal": (6220, 3735, -8519),
    "viewup": (0, -1, 0),
    "distance": 30950,
    "clipping": (18370, 46868),
    "orientation": (-14, 28, 177),
}
cam2 = {
    "position": (-16009, -3887, 17887),
    "focal": (6220, 3735, -8519),
    "viewup": (0, -1, 0),
    "distance": 30950,
    "clipping": (18370, 46868),
    "orientation": (-14, 28, 177),
}
```

I can interpolate between the two, but changing the postion argument (with `camera.SetPosition(params["position"])`) results in the camera moving **and** rotating, so not a pan.

Is there other ways to just change the camera's position?
Alternatively, is it possible to anchor the camera to a specific mesh so that it's always in the same position relative to the mesh? if so, I could do that and just move the object as I need.

**Comment by marcomusy** [comment]
I think you need to change the `x` of Position and FocalPoint at the same time in the same way.
This is how the bunny pans (manually obtained by mouse-middle-drag and pressing `C` in 3 positions):
```python
from vedo import *

b = load(datadir+'bunny.obj').scale(100000)

cam1 = dict(pos=(2.71e+3, 1.06e+4, 4.96e+4),    
           focalPoint=(2.71e+3, 1.06e+4, -149), 
           viewup=(0, 1.00, 0),
           distance=4.98e+4,
           clippingRange=(3.71e+4, 6.58e+4))

cam2 = dict(pos=(-1.77e+3, 1.06e+4, 4.96e+4),
           focalPoint=(-1.77e+3, 1.06e+4, -149),
           viewup=(0, 1.00, 0),
           distance=4.98e+4,
           clippingRange=(3.71e+4, 6.58e+4))

cam3 = dict(pos=(-7.69e+3, 1.06e+4, 4.96e+4),
           focalPoint=(-7.69e+3, 1.06e+4, -149),
           viewup=(0, 1.00, 0),
           distance=4.98e+4,
           clippingRange=(3.71e+4, 6.58e+4))


show(b, axes=1, camera=cam1)
show(b, axes=1, camera=cam2)
show(b, axes=1, camera=cam3)
```
![image](https://user-images.githubusercontent.com/32848391/99063809-6177ba00-25a5-11eb-8859-02582ce5ecf8.png)
![image](https://user-images.githubusercontent.com/32848391/99063902-80764c00-25a5-11eb-9699-0826f76b5616.png)
![image](https://user-images.githubusercontent.com/32848391/99063987-9c79ed80-25a5-11eb-8b48-c14df40cd1b0.png)

**Comment by FedeClaudi** [comment]
Hi, 
Thanks for the help, that makes it very clear. 
It turns out that I was also passing the camera parameters as a dictionary but the keys were written differently (e.g. `position` instead of `pos`) which I *think* meant that some of them were ignored. Perhaps it might be worthwhile raising an error or warning when the user passes an incorrect set of parameters?

**Comment by abhigoku10** [comment]
@FedeClaudi @marcomusy  i am having a lidar point cloud which i want to set with proper camera can you let me know what does the camera params mean eg viewup(?,?,?)
Thanks in advance

**Comment by marcomusy** [comment]
You may find useful documentation here: https://vtk.org/doc/nightly/html/classvtkCamera.html
