### ISSUE TITLE
Where is the example code for isosurface?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#246]
The example shows a figure for isosurface:

![image](https://user-images.githubusercontent.com/29271051/99266240-872ee880-285d-11eb-9b05-4fc423b48275.png)

I wonder where can I find the code?

**Comment by marcomusy** [comment]
You can find the code (and adapt it if you wish) in the `applications` submodule.
Or use it as such with this simple script:
```python
from vedo import datadir, Volume
from vedo.applications import IsosurfaceBrowser

vol = Volume(datadir+'head.vti')

bro = IsosurfaceBrowser(vol, c='gold')

bro.show(axes=7, bg2='lb')
```
![image](https://user-images.githubusercontent.com/32848391/99268789-e7099d00-2825-11eb-923a-d1a1ba12cacd.png)

**Comment by zhang-qiang-github** [comment]
thank you very much. Where can I find the head.vti ?

**Comment by marcomusy** [comment]
> thank you very much. Where can I find the head.vti ?

you're welcome.
note that in the above example `datadir` already points to a url: https://vedo.embl.es/examples/data/

**Comment by zhang-qiang-github** [comment]
thank you very much!
