### ISSUE TITLE
How to change the interaction mode to 2D

### ISSUE THREAD

**Issue by SignificantCell2** [marcomusy/vedo#247]
Hello,
In Paraview, it's possible to change the interaction mode between 3D and 2D as shown below:

![test01](https://user-images.githubusercontent.com/67183566/99349749-0859a000-289d-11eb-85a5-261f0139f738.png)

In vedo, the interaction mode is 3D, how can I change it to 2D?

Thank you

**Comment by marcomusy** [comment]
Hi, vtk offers a number of predefined interaction styles, you can change the default in 
`settings.interactorStyle`
see https://vedo.embl.es/content/vedo/settings.html?highlight=interactor
or when calling
`show(interactorStyle=6)`
see example `vedo -ir interactionstyle`

**Comment by SignificantCell2** [comment]
Hi, 
Thank you very much for your reply.
Actually, I forgot to mention that I am using vedo to display a VTK file from the command line as follows:

```
vedo my_domain.vtk
```
I've checked the help of vedo (`vedo --help`) but I have no idea how to make the interaction only 2D (as in Paraview).

Regards

**Comment by marcomusy** [comment]
oh i see.. 
no, there is no option for 2D in the CLI, but you can easily make a script that does it, something like
```python
import vedo
a = vedo.load(args[0])
vedo.show(a, interactorStyle=6, axes=1)
```
save it as myvedo.py then use it with eg
`python myvedo.py myfile.stl`

**Comment by SignificantCell2** [comment]
Thank you :)
