### ISSUE TITLE
addLight only add lights in the pane 0

### ISSUE THREAD

**Issue by theponpon** [marcomusy/vedo#249]
Hi,

If I create a Plotter with 2 panes (shape=(1,2)) and add lights to it, only the 1st pane uses the lights in its rendering.
I would suggest that you can add lights selectively to different panes by adding the 'at' parameter to the AddLight() function.
By default, at=-1 would add the light to all the panes.

Thank you for a really great library,

Pierre

**Comment by marcomusy** [comment]
thanks a lot this a very good idea!
