### ISSUE TITLE
Axis Labels Orientation and Window Title

### ISSUE THREAD

**Issue by jonnymaserati** [marcomusy/vedo#250]
Hi there

I'm working on making a vedo viewer module for a library I'm developing.

The world I'm viewing has the z axis pointing down, which I can visualize by setting the camera appropriately. The consequence of this is that now the axis labels are mis-orientated, as they assume the viewer is looking down rather than up. Is there a way to fix this (or ideally have the labels active and change as the viewing angle changes, a la plotly)?

![image](https://user-images.githubusercontent.com/41046859/100071547-7709a100-2e3b-11eb-88f1-2cd026291de9.png)

On a separate note, is it possible to change the window title from `vedo 2020.4.1` to something else? I tried adding a `title` property to `Plotter` but that doesn't appear to do anything and the [documentation](https://vtkplotter.embl.es/content/vedo/plotter.html#id1) is missing for this property.

**Comment by marcomusy** [comment]
Hi @jonnymaserati this is what I could come up with:
```python
from vedo import *

t = Tube([[6787000,437000,0],
          [6787000,438000,1000],
          [6787000,439000,4000]],
         r=50, c='r',
    )

b = Box(pos=(6787000,438000,2000), size=(8000,4000,8000)).wireframe()

axes = Axes(b,
            xtitle='East (m) x',
            ytitle='North (m) y',
            ztitle='TVD (m) z',
            xTitleJustify='bottom-right',
            yTitleJustify='top-right',
            zTitleJustify='top-right',
            xyGrid2=True, xyGrid=False,
            zxGrid=True, yzGrid2=True,
            zxGridTransparent=True, yzGrid2Transparent=True,
            yzGrid=False,
            digits=4,
            xLabelOffset=0.06, yLabelOffset=0.04, zLabelOffset=0.03,
        )

for a in axes.unpack(): # unpack the Assembly to access its elements
    # print(a.name)
    if 'title' in a.name or 'NumericLabel' in a.name: a.mirror('y')
    if 'yNumericLabel' in a.name: a.scale(0.8)

show(t, b, axes, title='my custom window title', bg='lightgrey', bg2='lavender')
```
![image](https://user-images.githubusercontent.com/32848391/100098355-3a02d600-2e5e-11eb-9feb-8149842fec84.png)

The other obvious option is just to use the native vtk axes:
`show(t, b, axes=8, title='my custom window title', bg='lightgrey', bg2='lavender')`

**Comment by jonnymaserati** [comment]
@marcomusy thanks for the swift response!

That's better... you're a star!

![image](https://user-images.githubusercontent.com/41046859/100236846-7b62b680-2f2e-11eb-8e4b-d8b6f2f7eef2.png)

The long numbers are just convention. And the native vtk axes aren't quite what I'm looking for. It'd be nice if you could modify and combine the native options.

I actually had to uninstall and reinstall `vedo` to get this working since there was issues with the previous `vtk` version constraint, so that's why `Axes` wasn't working for me for example. All good now though.

Thank you! I'll make sure you get credit in my next update!

**Comment by marcomusy** [comment]
looks cool!

> It'd be nice if you could modify and combine the native options.

one thing we cannot implement (easily) is reorienting the axes labels towards the camera as it moves... maybe future vtk releases might make this feasible :) 

> Thank you! I'll make sure you get credit in my next update!

you're welcome - thanks for the feedback!
