### ISSUE TITLE
Save an image as vtk object to view with 3D graphics

### ISSUE THREAD

**Issue by shakasaki** [marcomusy/vedo#252]
Hello, I was wondering if there is a way to save a 2D image as a vtk object, that would act as a "logo" when loaded in paraview.
I found this [nice example](https://github.com/marcomusy/vedo/blob/master/examples/other/icon.py) but i am not able to save the output so that I can later load it with other vtk graphics in paraview.

Thanks for the feedback!

**Comment by marcomusy** [comment]
Hi Alexis, in principle you can save a Picture as a vtkImageData in vtk, but i'm not sure then how paraview can load and visualize it as an icon (vtkOrientationMarkerWidget).. I'm not very familiar with paraview.. E.g.
```python
from vedo import *
dog = Picture(datadir+'dog.jpg')
vol = Volume(dog.inputdata()).printInfo()
vol.write('dog.vti')
show(dog, vol.isosurface(), N=2)
```
![image](https://user-images.githubusercontent.com/32848391/100455628-4b96e880-30bf-11eb-8944-c996fadeae26.png)

**Comment by shakasaki** [comment]
Hello Marco,
Thank you for the quick response! I haven't managed to do it in this way, but it helped to find out the powerful Picture class of vedo. I think its not straightforward to export some graphic of this sort to a VTK format.. 
Another workaround is to create 3D text with `vedo.Text` and position accordingly!
