### ISSUE TITLE
List for Lines color parameter

### ISSUE THREAD

**Issue by jonnymaserati** [marcomusy/vedo#255]
Hello there

I'm adding lines to my scene and want to color each line based on a property. I was assuming that I could do this by passing a list of colors to the `c` parameter of `Lines`, but unfortunately this doesn't seem to work.

The work around is to append each `Line` to a list and add the color for each line this way:
```
def get_lines(clearance_mesh):
    c = clearance_mesh.SF
    colors = colorMap(c, name='hot', vmin=min(c), vmax=max(c))
    start_points, end_points = clearance_mesh.get_lines()
    lines = [
        Lines([s], [e], c=c)
        for s, e, c in zip(start_points, end_points, colors)
    ]

    return lines
```
Seems a bit of a shame though when the `startPoints` and `endPoints` can take lists. Especially since I'd also like to add a color bar, but if each mesh only has one color then I'm not sure that works?

![image](https://user-images.githubusercontent.com/41046859/100666797-e4e12b80-3359-11eb-8752-1b15f500c358.png)

**Comment by marcomusy** [comment]
The trick here is to think that the "body" of a line is a cell so you can color those as you do for any polygonal mesh:
```python
from vedo import *

l1 = Line([0,0,0], [1,1,5], res=20)
l2 = Line([1,0,0], [2,1,5], res=20)

scals = l1.points()[:,2]# make up some scalars

lines = Lines(l1, l2).lw(3).cmap('hot_r', scals, on='cells')
lines.addScalarBar()
#lines.addScalarBar3D()
show(l1,l2, lines, axes=1)
```

![image](https://user-images.githubusercontent.com/32848391/100670695-8b7bfb00-335f-11eb-9f29-f88600fffffc.png)

**Comment by jonnymaserati** [comment]
Excellent... thanks for your speedy response again!

Here's what I ended up with:
```
def get_lines(clearance_mesh):
    c = clearance_mesh.SF
    start_points, end_points = clearance_mesh.get_lines()
    lines = Lines(start_points, end_points).cmap('hot_r', c, on='cells')
    lines.addScalarBar(title='SF')

    return lines
```
I was looking for a `color` property in Lines and not the 'cells`. Anyway, it ends up looking like this, which is great!

![image](https://user-images.githubusercontent.com/41046859/100713733-09b6bc80-33b5-11eb-912f-d5b9cce05f59.png)

**Comment by marcomusy** [comment]
look very cool :) 
More ideas, you can play with color bar (probably a green-base scale would make it more visible), make it bigger,
you can change fonts, move the East upwards to improve visibility .. etc. E.g.:
```python
from vedo import *

# settings.defaultFont = 'Bongas'

t1 = Line([0,-100,600], [220,-100,1600], lw=3, c='r', res=30)
t2 = t1.clone().addPos(200,100,10).c('b')

lns = Lines(t1,t2).cmap('Greens_r', t1.points()[:,2]/10, on='cells')
lns.addScalarBar(title='SF', size=(80,400), titleFontSize=14)

b = Box(pos=(0,200,1100), size=(1300,1600,1400)).wireframe()

axes = Axes(b,
            xtitle='y: North (m)',
            ytitle='x: East (m)',
            ztitle='z: TVD (m)',
            xTitleJustify='bottom-right',
            yTitleJustify='top-right',
            zTitleJustify='top-right',
            xyGrid2=True, xyGrid=False,
            zxGrid=True, yzGrid2=True,
            zxGridTransparent=True, yzGrid2Transparent=True,
            yzGrid=False,
            xLabelOffset=0.03, yLabelOffset=-1.02, zLabelOffset=0.02,
            yTitleOffset=-1.14,
            textScale=1.1, # make all texts 10% bigger
        )

for a in axes.unpack(): # unpack the Assembly to access its elements
    if 'title' in a.name or 'NumericLabel' in a.name: a.mirror('y')

cam = dict(pos=(-3.07e+3, 2.33e+3, -3.17e+3),
           focalPoint=(59.0, 140, 904),
           viewup=(0.611, -0.307, -0.730),
           distance=5.59e+3,
           clippingRange=(2.74e+3, 9.18e+3))

show(t1, t2, lns, b, axes, title='welleng 0.1.5',
     camera=cam, size=(1000,1000),
     bg='lightgrey', bg2='cornsilk')
```
![Screenshot from 2020-12-01 13-53-05](https://user-images.githubusercontent.com/32848391/100743860-3252ac80-33dd-11eb-91ba-2631367e4e03.png)

The `on="cell"` is indeed not intuitive, I've added a specific example in `examples/basic` to address it.
