### ISSUE TITLE
Problem to implement my-self interactor

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#256]
I am implementing my-self interactor. There are some basic function for a interactor: zoom in/out, pan, rotate. 

Now, I am trying to add my-self zoom in/out for my interactor. 

A simple vedo code is:
```
from vedo import printc, Plotter, datadir
vp = Plotter()
vp.load(datadir+"teapot.vtk").c("gold")
vp.interactor.RemoveAllObservers()
vp += __doc__
vp.show()
```
And the result is:
![image](https://user-images.githubusercontent.com/29271051/100745798-c68f3480-341a-11eb-9d77-04ede13fb470.png)

Now, I want to test the zoom in/out function, and my code is:
```

from vedo import printc, Plotter, datadir
vp = Plotter()
vp.load(datadir+"teapot.vtk").c("gold")

vp.renderer.GetActiveCamera().Dolly(100)      ## copy from vtk
vp.renderer.ResetCameraClippingRange()
vp.renderer.UpdateLightsGeometryToFollowCamera()
vp.interactor.Render()
vp.renderer.Render()

vp.interactor.RemoveAllObservers()
vp += __doc__
vp.show()
```
However, the object do not change. I also test the rotate function:
```

from vedo import printc, Plotter, datadir
vp = Plotter()
vp.load(datadir+"teapot.vtk").c("gold")

vp.renderer.GetActiveCamera().Azimuth(0)
vp.renderer.GetActiveCamera().Elevation(1)
vp.renderer.GetActiveCamera().OrthogonalizeViewUp()
vp.renderer.ResetCameraClippingRange()
vp.renderer.UpdateLightsGeometryToFollowCamera()
vp.interactor.Render()

vp.interactor.RemoveAllObservers()
vp += __doc__
vp.show()
```
It also do not change anything. 
Is there anything wrong with my code?

**Comment by marcomusy** [comment]
Uhm, this seems to work as expected:
```python
from vedo import Plotter, datadir

vp = Plotter()
vp.load(datadir+"teapot.vtk")

vp.show() # first render the scene with the default vtkCamera

vp.camera.Azimuth(20) # access the active camera

vp.interactor.RemoveAllObservers()

vp.show(resetcam=False)
```
Note the `resetcam=False` at the end.

**Comment by zhang-qiang-github** [comment]
@marcomusy Actually, it do not work as expected:

```
from vedo import Plotter, datadir

vp = Plotter()
vp.load(datadir+"teapot.vtk")
vp.interactor.RemoveAllObservers()
vp.show() # first render the scene with the default vtkCamera

```
For this code, the result is:
![image](https://user-images.githubusercontent.com/29271051/100752453-98622280-3423-11eb-943d-d4b45264ef7c.png)

And this code:
```
from vedo import Plotter, datadir

vp = Plotter()
vp.load(datadir+"teapot.vtk")
vp.interactor.RemoveAllObservers()
vp.show() # first render the scene with the default vtkCamera

vp.camera.Azimuth(20) # access the active camera

vp.interactor.RemoveAllObservers()

vp.show(resetcam=False)
```
The result is:
![image](https://user-images.githubusercontent.com/29271051/100752536-b29c0080-3423-11eb-89ad-73ee8c614661.png)

The environment is:
```
win 10
python 3.7
vedo 2020.4.2
```

**Comment by marcomusy** [comment]
You should be seeing first:
![Screenshot from 2020-12-01 15-36-21](https://user-images.githubusercontent.com/32848391/100754216-17873480-33eb-11eb-98f6-5e0c67a8a06b.png)
then:
![Screenshot from 2020-12-01 15-36-32](https://user-images.githubusercontent.com/32848391/100754210-1524da80-33eb-11eb-9c3f-5552f8727a6e.png)

What is your python and vtk versions?

**Comment by marcomusy** [comment]
Very much the same as in my ubuntu.. Can you try 
`pip install -U git+https://github.com/marcomusy/vedo.git`
and try again the script?

**Comment by zhang-qiang-github** [comment]
I have update the vedo:

```
(general) C:\Users\MLoong\Desktop\vedo-master\examples\other>pip install -U git+https://github.com/marcomusy/vedo.git -i https://douban.com/simple
Looking in indexes: https://douban.com/simple
Collecting git+https://github.com/marcomusy/vedo.git
  Cloning https://github.com/marcomusy/vedo.git to c:\users\mloong\appdata\local\temp\pip-req-build-eoroqzs9
  Running command git clone -q https://github.com/marcomusy/vedo.git 'C:\Users\MLoong\AppData\Local\Temp\pip-req-build-eoroqzs9'
Requirement already satisfied, skipping upgrade: vtk in d:\anaconda3\envs\general\lib\site-packages (from vedo==2020.4.2) (8.1.2)
Requirement already satisfied, skipping upgrade: numpy in d:\anaconda3\envs\general\lib\site-packages (from vedo==2020.4.2) (1.19.2)
Building wheels for collected packages: vedo
  Building wheel for vedo (setup.py) ... done
  Created wheel for vedo: filename=vedo-2020.4.2-cp37-none-any.whl size=9274285 sha256=608646f5ac1c49428938a746ddbdf65582baac150c929342ab415e28be85527f
  Stored in directory: C:\Users\MLoong\AppData\Local\Temp\pip-ephem-wheel-cache-rjx1hpus\wheels\3c\73\98\b28d811c28de4f80337e02eefcd01fc0f9c374d6830921e670
Successfully built vedo
Installing collected packages: vedo
  Found existing installation: vedo 2020.4.2
    Uninstalling vedo-2020.4.2:
      Successfully uninstalled vedo-2020.4.2
Successfully installed vedo-2020.4.2

```

But ```vp.camera.Azimuth(20)``` still do not work. 

In addition, I wonder how to debug this kind of bug? If the result of vtk is not what I expect, I have no idea how to debug it. Because it is difficult to look into vtk code.

**Comment by marcomusy** [comment]
..does this work?
```python
import vtk

cone = vtk.vtkConeSource()

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(400, 400)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

renWin.Render()
iren.Start()

iren.RemoveAllObservers()

ren.GetActiveCamera().Azimuth(60)
renWin.Render()

iren.Start()
```
Your should see first:
![Screenshot from 2020-12-02 03-14-29](https://user-images.githubusercontent.com/32848391/100819535-a5473c00-344c-11eb-8f23-d5576bfd8c30.png)

then, pressing `q`:
![Screenshot from 2020-12-02 03-14-46](https://user-images.githubusercontent.com/32848391/100819547-ab3d1d00-344c-11eb-97e1-c52e486cfce1.png)
(then pressing `q` is no more responsive)

**Comment by zhang-qiang-github** [comment]
The result of above code give the expected result.

**Comment by marcomusy** [comment]
ok - would you try again the vedo example but adding
```
from vedo import settings
settings.allowInteraction = True
```

i'm running out of ideas :(

**Comment by zhang-qiang-github** [comment]
Sorry, but it still do not work.

**Comment by marcomusy** [comment]
the only thing I can try is to test it on a windows OS.
(does it do the same if you upgrade to  vtk 9.0.1?)

**Comment by zhang-qiang-github** [comment]
Unfortunately, it do not work.

**Comment by marcomusy** [comment]
should now be ok.
