### ISSUE TITLE
Unsupported gzip encoding for NRRD reader

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#257]
I would like to open a volume and slice it with vedo using code example provided by Marco:
```
from vedo import load, show
from vedo.applications import Slicer

file_path = './average_template_100.nrrd'
vol = load(file_path)

plt = Slicer(vol, bg='white', bg2='lightblue', useSlider3D=False)
plt.show()
```

but the code fails with this error:
```
2020-12-01 22:41:59.342 (   1.042s) [          905B63]      vtkNrrdReader.cxx:395    ERR| vtkNrrdReader (0x7fb2b8469d40): Unsupported encoding: gzip
2020-12-01 22:41:59.342 (   1.043s) [          905B63]       vtkExecutive.cxx:753    ERR| vtkCompositeDataPipeline (0x7fb2b8445e70): Algorithm vtkNrrdReader(0x7fb2b8469d40) returned failure for request: vtkInformation (0x7fb2b55e4960)
  Debug: Off
  Modified Time: 159
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_INFORMATION
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0


Slicer tool
2020-12-01 22:42:00.220 (   1.920s) [          905B63]vtkSmartVolumeMapper.cx:271    ERR| vtkSmartVolumeMapper (0x7fb2b8469fa0): Could not find the requested vtkDataArray! 0, 0, -1,
2020-12-01 22:42:00.249 (   1.949s) [          905B63]vtkSmartVolumeMapper.cx:271    ERR| vtkSmartVolumeMapper (0x7fb2b8469fa0): Could not find the requested vtkDataArray! 0, 0, -1,
```

I have loaded the same volume within Paraview (VTK) all fine.
Is it because of an older VTK version or because of how vtkNrrdReader is called? Or something else?

**Comment by marcomusy** [comment]
yes - it looks like your vtk doesn't support that encoding.

**Comment by nantille** [comment]
For the record, I tried `pip install vedo -U`

And I got 
```
Requirement already up-to-date: vedo in /opt/anaconda3/envs/iblenv/lib/python3.8/site-packages (2020.4.2)
Requirement already satisfied, skipping upgrade: vtk in /opt/anaconda3/envs/iblenv/lib/python3.8/site-packages (from vedo) (9.0.1)
Requirement already satisfied, skipping upgrade: numpy in /opt/anaconda3/envs/iblenv/lib/python3.8/site-packages (from vedo) (1.19.2)
```

**Comment by marcomusy** [comment]
The output looks normal. 
But I see you already have vtk9.. so it should be able to deal with the unzipping. 
On some other data it looks fine
```python
from vedo import load, show
from vedo.applications import Slicer
vol = load('https://gitlab.kitware.com/vtk/vtk/uploads/94d5082b1a52c07b94449e3b68bf0e15/bX3D_white_uncompressed.nrrd')
plt = Slicer(vol)
plt.show()
```

**Comment by nantille** [comment]
Looking at the VTK documentation, GZIP is supported (https://vtk.org/doc/nightly/html/classvtkNrrdReader.html), there's the ReadDataGZip() method. Is there something to specify in the load() method of vedo to get that right?

**Comment by nantille** [comment]
OK then if vedo is hooked properly, I suppose the GZIP encoding is unusual for VTK.

**Comment by marcomusy** [comment]
> Looking at the VTK documentation, GZIP is supported (https://vtk.org/doc/nightly/html/classvtkNrrdReader.html), there's the ReadDataGZip() method. Is there something to specify in the load() method of vedo to get that right?

no, vtk should figure it out. The ReadDataGZip is a virtual protected member of the class..

> Your example works because the file is uncompressed (as its name says).

yes correct.

**Comment by FedeClaudi** [comment]
@nantille  you might try using [brainio](https://github.com/adamltyson/brainio) from Adam Tyson:

```python
from branio import branio

volume = branio.load_any('path to file') # gives a 3D numpy array with volume data
```

this has worked for me in the past

**Comment by nantille** [comment]
Thanks, worth checking in this case I suppose. Note that there's a typo in your import (brainio instead of branio).

**Comment by adamltyson** [comment]
Just an FYI, `brainio` has been replaced with [imio](https://github.com/adamltyson/imio) which gives more consistent behaviour across file types. I'll archive `brainio`.

**Comment by FedeClaudi** [comment]
Sorry I keep forgetting `imio`'s name and am always to lazy to search it or to bother you about it!
