### ISSUE TITLE
How to show medical image in vedo?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#258]
vedo is a really useful tool. But I can not find an example to visualize a 2d medical image. 

After refer to the vedo.applications, I find some relative code:

```
# applications.py line 102
msh = volume.xSlice(i).alpha(alpha).lighting('', la, ld, 0)
msh.cmap(_cmap_slicer, vmin=rmin, vmax=rmax)
if map2cells: msh.mapPointsToCells()
vp.renderer.RemoveActor(visibles[0])
if i and i<dims[0]: vp.renderer.AddActor(msh)
```
And the result is:

![image](https://user-images.githubusercontent.com/29271051/100885526-b72ceb80-34ed-11eb-88ec-3f47a4852aae.png)

But this figure is not a typical medical image. Can vedo visualize a medical image and adjust the window/level, just like:

```
myImageViewer2.GetWindowLevel().SetWindow(1000);
myImageViewer2.GetWindowLevel().SetLevel(-1000);
```

I know vedo can add a vtkActor. But ```vtk.vtkImageViewer2``` is not a ```vtkActor```, and ```vp.renderer.AddActor(vtk.vtkImageViewer2())``` is wrong. Thus, I wonder how can we combine ```vtk.vtkImageViewer2``` into vedo?

**Comment by marcomusy** [comment]
> this figure is not a typical medical image

define "typical" :)

There is no integration foreseen in `vedo` for the vtkImageViewer class. 
It very much depends on what you are trying to achieve. Keep in mind that there might be easier options like [Slicer](https://www.slicer.org/), unless you need something very specific.

**Comment by zhang-qiang-github** [comment]
@marcomusy The 'typical' medical image means the colorbar is gray, and we can set the image contrast (window/level) for the image. 
I am implementing a program for myself project, and need some specific process.

**Comment by marcomusy** [comment]
you can set the colormap the way you like (e.g. '[bone](https://github.com/marcomusy/vedo/blob/master/docs/colormaps.jpg)'), and/or you can create/control the color lookup table by key binding or mouse events (to modify contrast).
keep in mind that the slicing in the above example generates a plane Mesh obj.
