### ISSUE TITLE
How to render vedo to a Panel with a slider?

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#259]
I've read in the notebook examples that you can embed vedo in Panel (https://panel.holoviz.org/). Is there a working example that shows how to enable that? I would like to have a UI with Panel driving the visualization with vedo.

**Comment by marcomusy** [comment]
you should be able to do it with
`vedo.settings.embedWindow('panel')`

You might need to add
```
import panel as pn
pn.extension('vtk')
```

**Comment by nantille** [comment]
Do you have a simple working example of a slider that interacts with a vedo window? I cannot seem to make vedo load due to the error below:
```
import panel as pn
pn.extension('vtk')

from vedo import show
from vedo import load, datadir, Sphere
from vedo import embedWindow, Plotter

# INIT
pn.extension()
pn.config.comms = 'ipywidgets'

embedWindow('panel')  # <- this will make your scene embed as a panel

actor = load(datadir + 'embryo.tif')
actor.color('green')
sphere = Sphere(r=200, res=10).color('tomato')
pn.pane.VTK(show(actor, sphere))
```
```
ERROR:
[IPKernelApp] ERROR | No such comm target registered: hv-extension-comm
[IPKernelApp] WARNING | No such comm: hv-extension-comm
```
