### ISSUE TITLE
How to create a ply point cloud to voxels?

### ISSUE THREAD

**Issue by zendevil** [marcomusy/vedo#264]
I have loaded a ply point cloud using io.load, and I want to convert that into an approximate voxel 3d reconstruction. Is there a built-in function in vedo to do that?

**Comment by marcomusy** [comment]
The question is too vague.. a point cloud has a different topology to a voxel (Volume) dataset.
Do you mean interpolating some scalar value associated to the pointcloud to a volume region? Then [this](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/interpolateVolume.py) might work for you:
`vedo -r interpolateVolume`

**Comment by zendevil** [comment]
The example works, but using the interpolateVolume function like so:

```
from vedo import *
from plot import trajectory_plot
g = load('/Users/prikshetsharma/Desktop/PLY_HQ3rdFloor_SLAM_5mm.ply')
scale = 10
offset_x = -2000
offset_y = -1200
offset_z = 0
interpolateToVolume(g)
g.scale(10)
g.pos(offset_x, offset_y, offset_z)
aline = Line([[0,0,0], [100, 200, 500], [899, 30, 10]])
aline.color('r').lineWidth(4)
show(aline, g, axes=1)

```

gives the following error:


```
traceback (most recent call last):
  file "pointcloud.py", line 8, in <module>
    interpolatetovolume(g)
  file "/usr/local/lib/python3.7/site-packages/vedo/volume.py", line 150, in interpolatetovolume
    raise runtimeerror
runtimeerror

```

**Comment by marcomusy** [comment]
You must set either `radius` or `N` to a meaningful value.
The output of the function is a `Volume` which you are not giving any name in your script.

> Basically I want to convert each point or group of nearby points to convert to voxels.

I don't understand what this means.

**Comment by zendevil** [comment]
I've already set the radius. However, it's stuck in the computation, and the vedo window isn't showing up. Here's my code:

```
from vedo import *
from plot import trajectory_plot
g = load('/Users/prikshetsharma/Desktop/PLY_HQ3rdFloor_SLAM_5mm.ply')
g = load('/Users/prikshetsharma/Desktop/bunny/reconstruction/bun_zipper.ply')
scale = 10
offset_x = -2000
offset_y = -1200
offset_z = 0

voxex = g
voxel = interpolateToVolume(g, kernel='shepard', radius=0.2, dims=(90,90,90))
voxel.scale(10)
voxel.pos(offset_x, offset_y, offset_z)
aline = Line([[0,0,0], [100, 200, 500], [899, 30, 10]])
aline.color('r').lineWidth(4)
show(aline, voxel, axes=1)

```
How to determine whether it's stuck forever, or whether it's because the computation is simply compute intensive?

**Comment by marcomusy** [comment]
You are missing the scalars to the mesh? This is a working example:
```python
from vedo import *
# from plot import trajectory_plot

# g = load('/Users/prikshetsharma/Desktop/PLY_HQ3rdFloor_SLAM_5mm.ply')
# g = load('/Users/prikshetsharma/Desktop/bunny/reconstruction/bun_zipper.ply')
g = Sphere(r=10)

zvals = g.points()[:,2] # each point of the mesh carry a scalar value
g.addPointArray(zvals, 'zvals') # <- assign values to the mesh

scale = 100
offset_x = -2000
offset_y = -1200
offset_z = 0

voxel = interpolateToVolume(g, kernel='shepard', radius=0.1, dims=(90,90,90))
voxel.addScalarBar()
voxel.mode('max-projection')
voxel.scale(scale)
voxel.pos(offset_x, offset_y, offset_z)
aline = Line([[0,0,0], [100, 200, 500], [899, 30, 10]])
aline.color('r').lineWidth(4)
show(aline, voxel, axes=1)
```

![image](https://user-images.githubusercontent.com/32848391/101800193-4d27ce00-3b0d-11eb-8c20-5907dd0e2511.png)
