### ISSUE TITLE
Invert Axis and Other Axis Options

### ISSUE THREAD

**Issue by JGarrett7** [marcomusy/vedo#266]
Vedo seems to lack many of the axis options that make it optimal for publication figures, which is sad because it is far more intuitive for their creation than Matplotlib or Matlab. Some of these options are.

- Invert Axis: The ability to have an axis direction follow numerical decrease rather than increase. Matplotlib equivalent: https://matplotlib.org/3.1.1/gallery/subplots_axes_and_figures/invert_axes.html

- Placing 3D Axis in other locations like the front of the plotting area (see figures)

- Placing Axis Planes in other locations (currently the only other option is a second zx grid I believe)

- Having Axis Titles follow the camera (this may be an option I couldn't find)

For reference, I have included a figure I created both in Matlab and Vedo. In Vedo, I had to rotate my data from its natural z-down, y-left, x-forward frame (shown in Matlab figure) to get it to not be behind the axis planes. I can rotate the X-Axis title, but it is then upside down. I cannot rotate any of the axis number labels. Ideally, Vedo would be able to produce the same axes as Matlab. Also below, are my axes code options.

![VedoPlot](https://user-images.githubusercontent.com/43509109/101996504-a8d29280-3c98-11eb-934b-16d855758902.png)
![MatlabEquivalent](https://user-images.githubusercontent.com/43509109/101996505-aa03bf80-3c98-11eb-916f-77f1c3a5cdd3.png)

`vp.show(interactive=True, axes={'zxGrid': True, 'xtitle': 'X-Axis', 'ytitle': 'Y-Axis', 'ztitle': 'Z-Axis','xTitleRotation': 270, 'xTitleOffset': 0.05, 'yLabelRotation': 90})`

**Comment by marcomusy** [comment]
Thanks @GeneralGarrett  for your suggestions for improvement. 
This seem related to issue #250 and #255 maybe something there can be of help.

About the raised points:

1. that should be fairly easy to add as a flag. At present one can have access at all the elements of the axes and move them around as in #250 , but it's probably not too intuitive. One can also specify order and position of each label and tick with `xValuesAndLabels` (see [here](https://github.com/marcomusy/vedo/blob/master/examples/pyplot/customAxes.py) and [here](https://github.com/marcomusy/vedo/blob/master/examples/pyplot/whiskers.py)).

2. I need to think if this is possible.. but i guess it should.

3. Should also be easy to implement. We could set a variable to define at what fraction (or absolute position?) along the axis the grid should sit.

3. Not doable. This is only possible in `axes=8` mode (which I almost never use as I find it spoils the feeling of spatial orientation).

**Comment by marcomusy** [comment]
1. implemented via `xInvert` keyword or by inverting the range as in matplotlib
2. implemented via `xyShift` as a fractional position along the axis
3. the axis is shifted along with the plane(s) it belongs to
