### ISSUE TITLE
Transform volume data to Hounsfield Units

### ISSUE THREAD

**Issue by AnouarNechi** [marcomusy/vedo#268]
Hello

I have a 3D CT and I am able to have a nice 3D visualization with Vedo. My question is if it is possible to convert the volume to Hounsfield units to get a clearer view of the bone density or it is already in Hounsfield units

```
from vedo import load, datadir, show

vol = load('CT_scan/S4') # returns a Volume
vol.color([(150,"red"), (349,"red"),
           (350,"blue"), (849,"blue"),
           (850,"green"), (1249,"green"),
          ])
# vol.mode('max-projection')
vol.alpha([0., 1.])
vol.alphaUnit(15) # absorption unit, higher factors = higher transparency
vol.addScalarBar3D(title='color~\dot~alpha transfer function', c='k')

# show both Volume and Mesh
show(vol, __doc__, zoom=1.2)
```

![sample1](https://user-images.githubusercontent.com/45290939/102099442-95563180-3e28-11eb-9eb1-17b940e3c45d.JPG)

**Comment by marcomusy** [comment]
If the original data comes from a CT scan my guess is that it already is in the right units.
In any case you can play around with the transparency transfer function to make visible the scalar ranges that you wish.
This is done by setting e.g. `vol.alpha([0,0,1])` where the first 0 is the opacity for the lowest values of the voxel scalar and the last one is the opacity for the highest value. You can add as many opacities values as you like in-between.
Let me know if it's not clear.

- `alphaUnit` is a global absorption factor.

- you can reorient the 3d scalarbar with e.g. `vol.scalarbar.rotateX(90)`
