### ISSUE TITLE
Camera dictionary is getting reset

### ISSUE THREAD

**Issue by icemtel** [marcomusy/vedo#269]
Dunno if this is intended or not, but decided to report it just in case.

`plotter.show(camera=camera) ` would set camera correctly, but afterwards change `camera` to an empty dictionary. See an example below

```
import vedo 

plotter = vedo.plotter.Plotter(interactive=False)

corners = [[-10, -10], [10, 10]]  
plane = vedo.shapes.Rectangle(*corners) 

camera = dict(pos=np.array([-30, 30,15]), viewup=[0,0,1])
plotter.show(camera=camera) 
print(camera)
plotter.close()
```
Quick fix: 

```
plotter.show(camera=dict(camera)) 
```

Right now I have troubles updating, so I am still using older version: `vedo=2020.4.0` and  `vtk=8.2.0`. (sorry if this is fixed already, but didn't see in changelog)

**Comment by marcomusy** [comment]
Thanks for reporting - it's due to the `pop()` inside `show()` will be easily fixed the way you suggested.

**Comment by icemtel** [comment]
Good to know that it's easy to fix. Thanks!
