### ISSUE TITLE
how to render mesh normal

### ISSUE THREAD

**Issue by NaGenhao** [marcomusy/vedo#271]
Hi marcomusy, in the field of 3D reconstruction, it is often necessary to render the normal map. How can I do it easily? Thank you~
![image](https://user-images.githubusercontent.com/56231220/102572531-5c1f0980-4127-11eb-9d86-4f42480a645a.png)

**Comment by marcomusy** [comment]
Hi, that's very easy:
```python
from vedo import *

mesh = Mesh(datadir+'bunny.obj').computeNormals()
scals = dot(mesh.getPointArray("Normals"), [1,0,0])
mesh.cmap('cool', scals).addScalarBar()
# mesh.phong().lighting('plastic')
mesh.show(axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/102610962-61338700-412e-11eb-99cb-3e988c1629a5.png)

**Comment by NaGenhao** [comment]
I can color mesh like the following image in `Blender`, but how to color each point with RGB rather than scalar in `vedo`?
```
    normals[:, :2] = normals[:, :2] / (2.0)
    normals[:, 2] = normals[:, 2] / (-2.0)
    normals = ((normals + 0.5) * 255).astype(np.int)
```
![image](https://user-images.githubusercontent.com/56231220/102678763-71f30400-41e5-11eb-8ba4-976561cb3231.png)

**Comment by marcomusy** [comment]
Probably the best way is to color cells by interpolation **not** the vertices:
```python
from vedo import *

mesh = Mesh(datadir+'bunny.obj').computeNormals()

normals = mesh.getPointArray("Normals")
normals[:, :2] = normals[:, :2] / (2.0)
normals[:, 2] = normals[:, 2] / (-2.0)
normals = ((normals + 0.5) * 255)

# map arrays to cells and recompute normals
mesh.addPointArray(normals, 'mynorms').mapPointsToCells()
cellsRGB = mesh.getCellArray('mynorms')
mesh.cellIndividualColors(cellsRGB).computeNormals()

show(mesh, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/102701786-f0d65400-425a-11eb-8369-fb90b3c530ce.png)
