### ISSUE TITLE
Contour plots of values in 3d networks

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#272]
Hi @marcomusy 

I'd like to know if it is possible to generate contour plots of values corresponding to the coordinate positions of the network generated like this https://github.com/marcomusy/vedo/blob/master/examples/pyplot/graph_network.py.

I've got 3D networks and it is easy to display the values using point and edge cmaps. However, for large networks, l was wondering if it would be possible to generate a 2D contour plot.

Could you please offer some suggestions?

**Comment by marcomusy** [comment]
Hi @DeepaMahm 
the question is not very clear to me.
Contour plots of what scalar field?

For 3D networks what does "2D contour plot" mean? Isosurface?

**Comment by DeepaMahm** [comment]
Hi @DeepaMahm 
> Contour plots of what scalar field?

Sure, I'm sharing an example below to illustrate how the scalar field  is generated for your kind reference.
(I've the node values `vals` and these are interpolated to generate the value of the scalar at all coordinate positions of the 3D graph)
```
import networkx as nx
from vedo import *

G = nx.gnm_random_graph(n=30, m=55, seed=1)
nxpos = nx.spring_layout(G, dim=3)
nxpts = [nxpos[pt] for pt in sorted(nxpos)]

# node values
vals = list(range(10, 10+len(nxpts)))

nx_lines, vals_segments = [], []
for i, j in G.edges():
    nx_lines.append([nxpos[i], nxpos[j]])
    vals_segments += [vals[i], vals[j]]

    nx_pts = Points(nxpts, r=12)
    nx_edg = Lines(nx_lines).lw(2)

    nx_pts.pointColors(vals, cmap='YlGn').addScalarBar()
    nx_edg.pointColors(vals_segments, cmap='YlGn')
    labs = nx_pts.labels(vals, scale=0.03, precision=2).color('white')

show(nx_pts, nx_edg, labs, bg='black', axes=9)
```

> For 3D networks what does "2D contour plot" mean? Isosurface?

I'm sorry for not being clear. Yes, I am referring to isosurface plots. Basically, I've got a 3D network, and I'd like to know if it is possible to generate isosurface plots to visualize the scalar field at different depths z-dimension of the x-slice plane.

**Comment by marcomusy** [comment]
One possible solution is to overlay a transparent volume in composite mode:
```python
import networkx as nx
from vedo import *

G = nx.gnm_random_graph(n=30, m=55, seed=1)
nxpos = nx.spring_layout(G, dim=3)
nxpts = [nxpos[pt] for pt in sorted(nxpos)]

# node values
vals = range(10, 10+len(nxpts))

nx_lines, vals_segments = [], []
for i, j in G.edges():
    nx_lines.append([nxpos[i], nxpos[j]])
    vals_segments += [vals[i], vals[j]]

    nx_pts = Points(nxpts, r=12)
    nx_edg = Lines(nx_lines).lw(2)

    nx_pts.cmap('YlGn', vals).addScalarBar()
    nx_edg.cmap('YlGn', vals_segments)
    labs = nx_pts.labels(vals, scale=0.03, precision=2).c('w')

vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50,50,50))
vol.cmap('YlGn').mode(0).alphaUnit(1).printInfo()

show(vol, nx_pts, nx_edg, labs, bg='w', axes=9)
```
![image](https://user-images.githubusercontent.com/32848391/102818826-b0014b00-43d2-11eb-89cf-91746859d972.png)

OR

Use isosurfaces:
```python
vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50,50,50))
iso = vol.isosurface([15,20,25,30]).alpha(0.1)
show(iso, nx_pts, nx_edg, labs, bg='w', axes=9)
```
![image](https://user-images.githubusercontent.com/32848391/102819643-22bef600-43d4-11eb-97db-829f257709e3.png)

OR 

Use volume slices + optional isolines:
```python
slices = []
for i in range(0,51,10):
    sl = vol.xSlice(i).lighting('off').alpha(0.2)
    slices.append(sl)
    slices.append(sl.isolines(vmin=10, vmax=40))
show(nx_pts, nx_edg, labs, slices, bg='w', axes=9)
```
![image](https://user-images.githubusercontent.com/32848391/102820528-afb67f00-43d5-11eb-9939-3df26444dfcf.png)

They all look a bit "messy" to my taste though :)

**Comment by DeepaMahm** [comment]
Hi @marcomusy 

Thanks so much :)
Unfortunately, I couldn't successfully run the code posted in the first option
```

 vol.cmap('YlGn').mode(0).alphaUnit(1).printInfo()
AttributeError: 'Volume' object has no attribute 'cmap'
```

I also did 
`pip install -U git+https://github.com/marcomusy/vedo.git
`
and still, the attribute error appears.

Could you please explain a bit on what the different colors in the volume slices, displayed in the last image, signify?
I could understand the green scale but the other colors aren't very clear to me.

**Comment by marcomusy** [comment]
Oh try `.c('YlGn')` instead of `.cmap` (Ithink I have changed that in my local..

The colors are just the values of the volume expept i forgot to specify 'YlGn', so it's "jet" colormap.

**Comment by DeepaMahm** [comment]
Hi @marcomusy 
Thank you, .c('YlGn') works.

> The colors are just the values of the volume except I forgot to specify 'YlGn', so it's "jet" colormap.
I tried specifying the color map in the following line

`vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50, 50, 50)).color('YlGn')
`
```
slices = []
for i in range(0, 51, 10):
    sl = vol.xSlice(i).lighting('off').alpha(0.2)
    slices.append(sl)
    slices.append(sl.isolines(vmin=10, vmax=40))
show(nx_pts, nx_edg, labs, slices, bg='w', axes=9)

```

still displays the other colors :-/
![image](https://user-images.githubusercontent.com/29662579/103079648-3a77c380-45fa-11eb-8adb-5013a4bba2d2.png)

Could you please let me know how to fix this? Could you please also explain how the values are set for `dims=(50, 50, 50)`. I coud understand the other params but this one is not very clear to me.

Also, may I know how to plot a single xslice from range(0, 51, 10) e.g. at i = 3?

As always, thanks a lot for the wonderful tool and support.

**Comment by marcomusy** [comment]
add the `cmap()` to the slices not the volume :) 
```python
vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50,50,50))

slices = []
for i in range(0,51,10):
    sl = vol.xSlice(i).lighting('off').alpha(0.2).cmap('YlGn',vmin=10,vmax=40)
    slices.append(sl)
    slices.append(sl.isolines(vmin=10, vmax=40))
show(nx_pts, nx_edg, labs, slices, bg='w', axes=9)
```
![image](https://user-images.githubusercontent.com/32848391/103140490-4f7e5080-46e7-11eb-960f-dfbcaae61447.png)

> As always, thanks a lot for the wonderful tool and support.

You're welcome

**Comment by marcomusy** [comment]
> Could you please also explain how the values are set for dims=(50, 50, 50)?

it's the number of voxels to create the Volume by interpolation of the given values at the points.
So it's 50 voxels in both x, y and z.

**Comment by DeepaMahm** [comment]
Ahh, thank you
I did `sl = vol.xSlice(i).lighting('off').alpha(0.2).color('YlGn') `, my mistake.

I'm sorry for another question,  from what I understand I should vary the number of voxels i.e dim=(50,50,50) depending on the input network?

**Comment by marcomusy** [comment]
> I should vary the number of voxels i.e dim=(50,50,50) depending on the input network?

that is a matter of resolution in the 3 directions. If you have a very long x axis then choose a higher value for dim[0] so that the x-resolution will not be poor.

> plot a single xslice e.g. at i = 3 and extract the data corresponding to a single slice as a numpy array?

`vol.xSlice(3).getPointArray()`

**Comment by DeepaMahm** [comment]
Hi @marcomusy,

 After generating the interpolated volume, I'd like to plot only the slices (i.e. remove the network) . 

`show(labs, slices, bg='w', axes=9)` creates the following 
![image](https://user-images.githubusercontent.com/29662579/110212313-d195ad00-7ec0-11eb-9d95-e1ea5cd4b55d.png)

without the scalarbar since `nx_pts` is removed in `show`. Could you please suggest alternate ways to retain the scalabar in the plot above? I'd like to display the legend.

**Comment by marcomusy** [comment]
If you added the scalarbar to a specific `actor` you should be able to add it this way
`show(myactors, actor.scalarbar, otheractors)`

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

While using `vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50,50,50))`, I would like to know the interoplation is done. 

 For instance, in the image below ([ref](https://github.com/marcomusy/vedo/issues/272#issuecomment-750846369))
![image](https://user-images.githubusercontent.com/29662579/111102168-6f4c4480-8571-11eb-830b-1d6c0aa2d643.png)

could you please explain how the interpolation is done in the region circled in red color?  I found the argument `radius` available in `interpolateToVolume`. But I am not sure how to specify it. Does the `radius` refer to the radius around the point (or node in the network posted above) at which the value of the scalar field is known?

I'm also looking for options that will help in hiding points that are assigned a scalar value below `x` (e.g zero ) and I came across

```
 amap = [0, 1, 1, 1, 1]  # hide low value points giving them alpha 0
 mslices = merge(slices)  # merge all slices into a single Mesh
 mslices.cmap('hot_r', alpha=amap).lighting('off').addScalarBar3D()
```

For instance after creating 
vol = interpolateToVolume(nx_pts, kernel='shepard', N=2, dims=(50,50,50))

```
slices = []
for i in range(0,51,10):
    sl = vol.xSlice(i).lighting('off').alpha(0.2).cmap('YlGn',vmin=10,vmax=40)
    slices.append(sl)
    slices.append(sl.isolines(vmin=10, vmax=40))
```
I couldn't understand how to specify `amap` . In [this](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/slicePlane2.py) example `amap` is a list ` [0, 1, 1, 1, 1]`. Could you please how amap has to be specified for the example posted [here](https://github.com/marcomusy/vedo/issues/272#issuecomment-749188497) ?

**Comment by marcomusy** [comment]
> could you please explain how the interpolation is done in the region circled in red color? 

the interpolation is done the same way in all parts of the volume. Shepard interpolation is described [here](https://en.wikipedia.org/wiki/Inverse_distance_weighting)

> I couldn't understand how to specify amap . In this example amap is a list [0, 1, 1, 1, 1]. Could you please how amap has to be specified for the example posted here ?

`amap` in the examples defines the opacity transfer function between the lower and upper value of the volume scalar.
e.g. Lets say that the scalar range goes from -20 to 120.
Then `amap=[0,1]` will set alpha to zero for the voxels containing low values (-20) and will set 1 (=completely opaque) to high value voxels (120).
If I set `amap=[0,1,1]`, voxels containing value =50 = (-20+120)/2 will also be completely opaque etc.
You can also equivalently specify `amap=[(-20, 0), (50, 1), (120,1)]`

Let me know if it's not clear.
