### ISSUE TITLE
How to make the point looks like 3D ball

### ISSUE THREAD

**Issue by NeuZhangQiang** [marcomusy/vedo#274]
vedo can easily show a point:

```
from vedo import Point, show
p = Point(pos=[0.5, 0.5, 0.5])
show(p)
```

And the result is:

![image](https://user-images.githubusercontent.com/62534955/102734736-8832c880-437b-11eb-829b-6a48c50c12ce.png)

This point looks like a 2D point. How to make it looks like a 3D ball?

**Comment by marcomusy** [comment]
You can either change its lighting:
```python
from vedo import *
s = Sphere()
Points(s.points(), r=30).c('r').lighting('glossy').show()
```
![image](https://user-images.githubusercontent.com/32848391/102804232-c222bf80-43b9-11eb-8f51-2dd8daa538f8.png)
(try pressing `o` repeatedly in the scene to add a light source)

Or you can use a `Sphere()` or `Spheres()` objects directly.

**Comment by NeuZhangQiang** [comment]
Thank you very much. It works.
