### ISSUE TITLE
Radius of points

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#275]
Hi @marcomusy 
`pts = Points(nxpts, r=12)
`
sets uniform radius to all points in a graph. I would like to assign a different radius to each point.
Since `r` accepts a float , I wasn't sure how to get this working if I supply a list. 

Could you please help me with this?

**Comment by marcomusy** [comment]
`Points` object cannot accept an array as radii because `r` is expressed in nr of screen pixels.
In you case you need to use `Spheres`:
https://vedo.embl.es/content/vedo/shapes.html?highlight=spheres#vedo.shapes.Spheres

**Comment by DeepaMahm** [comment]
Hi @marcomusy 
Thank you. I tried the following
```
r = [0.02, 0.02, 0.02, 0.02, 0.02, 0.2, 0.02, 0.02, 0.02, 0.02]
colors = ['r', 'g', 'b', 'r', 'g', 'b', 'r', 'g', 'b', 'k']
pts = Spheres(nxpts, r=r, c=colors)
```
but this causes runtime error. `Radii` works good but the colors don't work for some reason.

**Comment by marcomusy** [comment]
It's only either radii or colors- not both.. it's limitation i'm afraid.
If the nr of spheres you want to draw is less than about 1k I suggest you use `Sphere` instead of `Spheres` in a loop.

**Comment by DeepaMahm** [comment]
> It's only either radii or colors- not both.. it's limitation i'm afraid.

Thanks a lot for the clarification. In that case, may I know if it would be possible to enable a feature that will allow the user to vary the alpha of each sphere. This will help in specifying a list of colors and vary the transparency of the spheres that have to be highlighted from the others instead of varying the radii.

I'm also facing an issue while specifying the labels for spheres (this works fine for Points).
` labs = pts.labels(label, scale=5, font='VictorMono', c='k').addPos(0.05, 0, 0.5)
`

```
txt_lab = str(arr[i])
IndexError: list index out of range
```

**Comment by marcomusy** [comment]
If you are using the `Sphere` class instead of `Spheres` you already can set individual transparencies with `sph.alpha()` as these are individual meshes.

**Comment by DeepaMahm** [comment]
Unfortunately, I couldn't successfully use `Sphere`

I tried
```
G = nx.gnm_random_graph(n=10, m=15, seed=1)
nxpos = nx.spring_layout(G, dim=3, seed=1)

nxpts = [nxpos[pt] for pt in sorted(nxpos)]
nx_lines = [(nxpts[i], nxpts[j]) for i, j in G.edges()]
print(nxpts)
sph = Sphere(nxpts, r=12, c=['r', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g']) #setting uniform radius, coloring different
sph.alpha([1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
edg = Lines(nx_lines).lw(4)

```
```
    self.SetPosition(pos)
TypeError: SetPosition argument %Id: %V

```
However, `sph = SphereS(nxpts) works for `Spheres` . 
`

Could you please suggest how the position argument has to be set?

**Comment by marcomusy** [comment]
..no you cannot! `Sphere` is an individual `Mesh` object so it should be used in a loop to create multiple ones, e.g.:
```python
cols = ['r', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g']
spheres = [Sphere().color(c).pos(np.random.randn(3)) for c in cols]
show(spheres)
```   
![image](https://user-images.githubusercontent.com/32848391/103153349-3e3d4e80-4790-11eb-939e-4fd58d38a37c.png)

**Comment by DeepaMahm** [comment]
Thanks Marco,

So I understand I must be creating `spheres` in following way

spheres = [Sphere().color(c).pos(np.random.randn(3)) for c in cols]

and then do 

```
show(spheres,
     edg,
     )
```
to display the network graph.

**Comment by marcomusy** [comment]
Yes - correct!
