### ISSUE TITLE
Scale/normalize point clouds of different dimensions

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#277]
Hi @marcomusy,

I have two point clouds (see attached file), they are of different dimensions and in different positions (actually in principle room4 is subpart of room6 with a different design). Now I wanted to scale/normalize them so that they are both in the same range e.g. (-1,1) in all three axis and without losing the aspect ratio.

I've tried to use the `normalize()` function but it didn't really do what I want. Thus, I wanted to ask if there is another method which I can use, I did not find something on the documentation and `scale()` doesn't seem to do what I want.
```
import numpy as np
import vedo as vd

room4 = np.genfromtxt('room4.csv', delimiter=',', dtype='float')
room6 = np.genfromtxt('room6.csv', delimiter=',', dtype='float')

pcd4 = vd.pointcloud.Points(room4).normalize()
pcd6 = vd.pointcloud.Points(room6).normalize()



axes4 = vd.addons.buildAxes(pcd4, c='k')
axes6 = vd.addons.buildAxes(pcd6, c='dg')
vd.show(pcd4, pcd6, axes4, axes6, axes=4)
```

 
[rooms.zip](https://github.com/marcomusy/vedo/files/5725498/rooms.zip)

**Comment by marcomusy** [comment]
You can align the bounding boxes like this:
```python
import numpy as np
import vedo as vd

room4 = np.genfromtxt('room4.csv', delimiter=',', dtype='float')
room6 = np.genfromtxt('room6.csv', delimiter=',', dtype='float')

pcd4 = vd.Points(room4).flag('room4')
pcd6 = vd.Points(room6).c('dg').flag('room6')

vd.printc('pcd4.bounds', pcd4.bounds())
vd.printc('pcd6.bounds', pcd6.bounds(), c='g')
# three points are enough to work out the transformation
x40,x41,y40,y41,z40,z41 = pcd4.bounds()
x60,x61,y60,y61,z60,z61 = pcd6.bounds()
p4 = vd.Points([[x40, y40, z40], [x41, y41, z41], [x40, y40, z41]])
p6 = vd.Points([[x60, y60, z60], [x61, y61, z61], [x60, y60, z61]])
T = p4.transformWithLandmarks(p4, p6, rigid=0).transform
pcd4.applyTransform(T)

axes4 = vd.Axes(pcd4, digits=2)
axes6 = vd.Axes(pcd6, digits=2, c='dg')
vd.show(pcd4, pcd6, axes4, axes6, axes=4)
```
![image](https://user-images.githubusercontent.com/32848391/102807607-41ff5880-43bf-11eb-8861-88bd96c4d5ba.png)

Or manually assign positions, scaling and rotations to one or both.

**Comment by ttsesm** [comment]
Thanks for the feedback, the alignment seems to work quite fine based on the bounding boxes (also using `rigid=1` the output seems better for my needs). Another alternative could be to align both point clouds based on all axes to [0,0,0] as reference point with the following function before you make them a vedo `Points` object:
```
def centralize(x, axis=None):
    offset = (np.min(x, axis, keepdims=True) + np.max(x, axis, keepdims=True)) / 2
    return x - offset
```

I am not quite sure though whether this could done directly to vedo point cloud objects, also I do not really understand how to apply the scaling within the desired range. E.g. the following function applies both alignment and scaling based on the `min`, `max`:
```
def scale(x, out_range=(-1, 1), axis=None):
    domain = np.min(x, axis), np.max(x, axis)
    y = (x - (domain[1] + domain[0]) / 2) / (domain[1] - domain[0])
    return y * (out_range[1] - out_range[0]) + (out_range[1] + out_range[0]) / 2
```

The problem with the above is that it squeezes the two point clouds, destroying the aspect ratio. A solution to that it would  be to divide by using the greatest value of the min, max subtraction of all dimensions: `(x_max - x_min)`, `(y_max - y_min)`, `(z_max - z_min)`.  

Thus, is there a way to do that with vedo directly? I know that this might be irrelevant to vedo after all, since someone could easily just use numpy and do his job, but I am just asking from curiosity for the vedo scaling/transformation methods ;-).

Thanks again for your time.

**Comment by marcomusy** [comment]
Hi - thanks for rising the issue. I think it's actually something useful so i've added it as a `vedo.base` method (for the next release):
```python

    def alignToBoundingBox(self, msh, rigid=False):
        """
        Align the current object's bounding box to the bounding box
        of the input object.

        :param bool rigid: allow scaling if set to True

        :Example:

            .. code-block:: python

                from vedo import *
                eli = Ellipsoid().alpha(0.4)
                cube= Cube().pos(3,2,1).rotateX(10).rotateZ(10).alpha(0.4)
                eli.alignToBoundingBox(cube, rigid=False)
                axes1 = Axes(eli, c='db')
                axes2 = Axes(cube, c='dg')
                show(eli, cube, axes1, axes2)
        """
        lmt = vtk.vtkLandmarkTransform()
        ss = vtk.vtkPoints()
        xss0,xss1,yss0,yss1,zss0,zss1 = self.bounds()
        for p in [[xss0, yss0, zss0],
                  [xss1, yss0, zss0],
                  [xss1, yss1, zss0],
                  [xss0, yss1, zss0],
                  [xss0, yss0, zss1],
                  [xss1, yss0, zss1],
                  [xss1, yss1, zss1],
                  [xss0, yss1, zss1],
                 ]:
            ss.InsertNextPoint(p)
        st = vtk.vtkPoints()
        xst0,xst1,yst0,yst1,zst0,zst1 = msh.bounds()
        for p in [[xst0, yst0, zst0],
                  [xst1, yst0, zst0],
                  [xst1, yst1, zst0],
                  [xst0, yst1, zst0],
                  [xst0, yst0, zst1],
                  [xst1, yst0, zst1],
                  [xst1, yst1, zst1],
                  [xst0, yst1, zst1],
                 ]:
            st.InsertNextPoint(p)

        lmt.SetSourceLandmarks(ss)
        lmt.SetTargetLandmarks(st)
        if rigid:
            lmt.SetModeToRigidBody()
        lmt.Update()
        self.applyTransform(lmt)
        self.transform = lmt
        return self
```

You can only keep the aspect ratio if you apply the same scaling in the 3 cartesian coordinates.
If you want the origins to coincide you need to choose which axes to scale to match the target.

**Comment by ttsesm** [comment]
> You can only keep the aspect ratio if you apply the same scaling in the 3 cartesian coordinates.

Yup, that's correct.

> If you want the origins to coincide you need to choose which axes to scale to match the target.

What do you mean with that, can you give an example?

**Comment by marcomusy** [comment]
> > If you want the origins to coincide you need to choose which axes to scale to match the target.
> 
> What do you mean with that, can you give an example?

If you think of matching the origins (3 coords) and directions (3 euler angles) of two triad axes then you are left with a global scaling to be chosen. You can fix it to any value. There will be 3 special values that allow to match either the x, y or z axis of the target.

**Comment by ttsesm** [comment]
I see, thanks.

I think, I will close this now.
