### ISSUE TITLE
not able to close a vedo window

### ISSUE THREAD

**Issue by DSLituiev** [marcomusy/vedo#279]
i'm running vedo from Jupyter on Ubuntu20.04.
I can only launch one visualization in a notebook.
Once it's launched I'm not able to close the window ("vedo 2020.4.2") without killing the Jupyter kernel.

I tried the "Close" button (x) and "Quit" from the menu -- none worked.
There is nothing suspicious printed in the Jupyter console.

I'm using [this code](https://github.com/marcomusy/vedo/blob/master/examples/notebooks/trimesh/ray.ipynb)

**Comment by marcomusy** [comment]
You can try with 
```python
# ...
from vedo import show, closeWindow, embedWindow
embedWindow(False)
show(mesh, ray_visualize, locs, axes=1).close() # option1
# closeWindow() # option2
```
