### ISSUE TITLE
Rotate axis in plot

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#280]
Hi @marcomusy 

I've a plot like the following

![image](https://user-images.githubusercontent.com/29662579/103150683-5ca94700-479c-11eb-8700-7c9e82c2147c.png)
 
```
import networkx as nx
from collections import OrderedDict
from vedo.pyplot import DirectedGraph
from vedo import *


G = nx.gnm_random_graph(n=5, m=10)
nxpos = nx.spring_layout(G, dim=3, seed=1)

nxpts = [nxpos[pt] for pt in sorted(nxpos)]
nx_lines = [(nxpts[i], nxpts[j]) for i, j in G.edges()]
pts = Points(nxpts, r=10).lighting('off')
edg = Lines(nx_lines).lw(5)

weights = [1, .30, .10, .79, .70, .60, .75, .78, .65, .90]
color = colorMap(weights, name="viridis")
edge_w = OrderedDict(zip(G.edges, weights))
nx.set_edge_attributes(G, edge_w, 'weight')

edg.cellColors(weights, cmap='viridis')  #Blues_r
edg.addScalarBar3D(
    title='title',
    titleFont='VictorMono',
    labelFont='VictorMono',
    c='k',
)
edg.scalarbar.addPos(0.1, 0, 0).useBounds()

show(pts,
     edg,
     axes=True,
     sharecam=True,
     bg2="white",
     at=0,
     zoom=1.2,
     )
```
And I'd like to rotate the axes - shift the z-axis in place of the x-axis
e.g.

![image](https://user-images.githubusercontent.com/29662579/103150723-9e39f200-479c-11eb-8b4a-6b56029abf5e.png)

I'd like to know how this can be done so that the axes grid looks like the first plot. I looked at `mesh.py` in the repo that uses `RotateWXYZ`. However, I am not sure how to use it for the example mentioned above.

**Comment by marcomusy** [comment]
you can rotate/move around the scalarbar like any other object with `pos()` and `rotateX()`.
Renaming axes is easy just pass a dictionary of options to `axes` in show:
```python

show(pts,
     edg,
     axes=dict(
                 xtitle='z',
                 ztitle='x',
                 yzGrid=False, # can disable grid wall if desired
              ),
     zoom=1.2,
     )
```
Flipping of the axes is not implemented (see #266 )

**Comment by DeepaMahm** [comment]
Thank you, Marco. I will be happy to know after the flipping of axes is implemented. I'd like to flip the network in my case by flipping the axes.

**Comment by marcomusy** [comment]
Sure - I'll let you know (timescale is about 1 week).

**Comment by marcomusy** [comment]
Check out the latest version with :
`pip install -U git+https://github.com/marcomusy/vedo.git`

and notes:
https://github.com/marcomusy/vedo/blob/master/docs/changes.md

**Comment by DeepaMahm** [comment]
Hi @marcomusy 
sorry for the late post . When I try `pip install -U git+https://github.com/marcomusy/vedo.git`
I am not able to find the latest version of the repo downloaded in my system (Windows) for some reason. I've done this in the past without any issues.

I've version `2020.4.2` installed.


```
(venv) I:\>pip install -U git+https://github.com/marcomusy/vedo.git
Collecting git+https://github.com/marcomusy/vedo.git
  Cloning https://github.com/marcomusy/vedo.git to ###\appdata\local\temp\pip-req-build-vlbad3sw
  Running command git clone -q https://github.com/marcomusy/vedo.git '###\AppData\Local\Temp\pip-req-build-vlbad3sw'
Requirement already satisfied: vtk in c:\users\deepa\python\python36\lib\site-packages (from vedo==2021.0.1) (9.0.1)
Requirement already satisfied: numpy in c:\users\deepa\python\python36\lib\site-packages (from vedo==2021.0.1) (1.17.2)

```

**Comment by marcomusy** [comment]
Have you tried to remove and reinstall ?
`pip uninstall vedo`
`pip uninstall vedo`
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by DeepaMahm** [comment]
Thanks for the reply.  I got it working :) 

Excuse me for a few more questions

I tried the following,
```
G = nx.gnm_random_graph(n=5, m=10)
nxpos = nx.spring_layout(G, dim=3, seed=1)

nxpts = [nxpos[pt] for pt in sorted(nxpos)]
nx_lines = [(nxpts[i], nxpts[j]) for i, j in G.edges()]
pts = Points(nxpts, r=10).lighting('off')
edg = Lines(nx_lines).lw(5)

weights = [1, .30, .10, .79, .70, .60, .75, .78, .65, .90]
color = colorMap(weights, name="viridis")
edge_w = OrderedDict(zip(G.edges, weights))
nx.set_edge_attributes(G, edge_w, 'weight')

edg.cellColors(weights, cmap='viridis')  #Blues_r
edg.addScalarBar3D(
    title='title',
    titleFont='VictorMono',
    labelFont='VictorMono',
    c='k',
)
edg.scalarbar.addPos(0.1, 0, 0).useBounds()

show(pts,
     edg,
     axes=dict(zInverted=False),
     sharecam=True,
     # bg2="white",
     at=0,
     zoom=1.2,
     )
```

I find that the z-axis is inverted (visually) while using the key `zInvereted`. However, I couldn't figure out how to rotate the axis like mentioned in the original post. Could you please suggest if I should be looking at other options in `Axes` ?

**Comment by marcomusy** [comment]
I'm not sure what rotation are you trying to obtain, this is an example where you can manually adjust rotation of any element in the axes assembly:
```python
import networkx as nx
from vedo import *

G = nx.gnm_random_graph(n=5, m=10)
nxpos = nx.spring_layout(G, dim=3, seed=1)

nxpts = [nxpos[pt] for pt in sorted(nxpos)]
nx_lines = [(nxpts[i], nxpts[j]) for i, j in G.edges()]
pts = Points(nxpts, r=10).lighting('off')
edg = Lines(nx_lines).lw(5)

weights = [1, .30, .10, .79, .70, .60, .75, .78, .65, .90]
edg.cmap('viridis', weights, on='cells')
edg.addScalarBar3D(
    title='title',
    titleFont='VictorMono',
    labelFont='VictorMono',
    c='k',
)
edg.scalarbar.addPos(.05,0,0).useBounds()

# create the axes actor to be added like any other object in show()
axes = Axes(edg, zInverted=True, zLabelRotation=0, zTitleRotation=0)
for a in axes.unpack():
    # print(a.name)
    if "zNum" in a.name:
        a.RotateY(-90)

show(pts, edg, axes, zoom=1.2)
```
it can be a bit tricky to find the desired combination of rotations though.

**Comment by DeepaMahm** [comment]
Hi @marcomusy,
I'm sorry, I think I didn't explain clearly before.

When I create the following network, y-axis is pointing in the vertcal direction

![image](https://user-images.githubusercontent.com/29662579/109806346-9b4ef800-7c4a-11eb-902f-090b974629e9.png)

I want to rotate so that the z-axis points in the vertical direction

![image](https://user-images.githubusercontent.com/29662579/109806607-e49f4780-7c4a-11eb-83eb-d4ce148b6dfc.png)

**Comment by marcomusy** [comment]
If it's a "proper" rotation (rotation which does not change handedness) you just need to apply `.rotateX(-90)`, otherwise either:
- rename axes
- use `mirror('y')` + rotation.
I don't think there are other solutions.

**Comment by DeepaMahm** [comment]
Awesome, thanks so much!

Is this a right way to do? Could you please have a look?
```
import networkx as nx
from vedo import *

G = nx.gnm_random_graph(n=5, m=10)
nxpos = nx.spring_layout(G, dim=3, seed=1)
nxpts = [nxpos[pt] for pt in sorted(nxpos)]
nx_lines = [(nxpts[i], nxpts[j]) for i, j in G.edges()]
pts = Points(nxpts, r=10).lighting('off').rotateX(-90)
edg = Lines(nx_lines).lw(5).rotateX(-90)

weights = [1, .30, .10, .79, .70, .60, .75, .78, .65, .90]
edg.cmap('viridis', weights, on='cells')
edg.addScalarBar3D(
    title='title',
    titleFont='VictorMono',
    labelFont='VictorMono',
    c='k',
)
edg.scalarbar.addPos(.05,0,0).useBounds()

# create the axes actor to be added like any other object in show()
axes = Axes(edg, xtitle='y', ytitle='z', ztitle='x')

show(
    pts,
    edg,
    axes,
    zoom=1.2
)
```

**Comment by marcomusy** [comment]
..depending on the meaning of the graph is looks technically reasonable to me! 
:)

**Comment by DeepaMahm** [comment]
I'm saving the screenshots of the images that I generate from vedo to add in my manuscript. `show(pts,edg,axes,zoom=1.2
).screenshot("test.png")`
![test](https://user-images.githubusercontent.com/29662579/109841150-c77c7000-7c6e-11eb-9ef4-6fea3b7873dc.png)

The resolution appears to be low. I'm using 
```
pip list | findstr vedo
vedo                  2021.0.1

```
on Windows. Could you please let me know if there are better ways to save the generated images?

**Comment by marcomusy** [comment]
I see .. the first problem is that your graphic card  seems not be applying antialiasing (which in my system is  caused by vtk9 , whereas in vtk8.1.2 it just works fine).. see #327 
You may make it just a lot bigger with e.g. `screenshot(scale=3)`
and/or play with
`settings.screeshotLargeImage=True`

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

I'm trying rotation on another example
```

import networkx as nx
from vedo import *

G = nx.gnm_random_graph(n=10, m=15, seed=1)
nxpos = nx.spring_layout(G)
nxpts = [nxpos[pt] for pt in sorted(nxpos)]

nx_lines = []
for i, j in G.edges():
    p1 = nxpos[i].tolist() + [0]
    p2 = nxpos[j].tolist() + [0]
    nx_lines.append([p1, p2])

nx_pts = Points(nxpts, r=12)#.rotateX(90)
nx_edg = Lines(nx_lines).lw(2)#.rotateX(90)

# node values
vals = [100, .80, .10, .79, .70, .60, .75, .78, .65, .90]
nx_pts.pointColors(vals, cmap='YlGn', vmin=min(vals), vmax=max(vals)).addScalarBar(title='$\mu$')
show(nx_pts, nx_edg, nx_pts.labels('id'), axes=True, interactive=True, bg='w', title='plot')
```
Original graph:
![image](https://user-images.githubusercontent.com/29662579/110231713-6808b380-7f3f-11eb-84b1-e5dd53045cd8.png)

To obtain the following I tried
```
nx_pts = Points(nxpts, r=12).rotateY(-90)
nx_edg = Lines(nx_lines).lw(2).rotateY(-90)

```
![image](https://user-images.githubusercontent.com/29662579/110231743-938b9e00-7f3f-11eb-82e7-42cd2ee8fe76.png)


Unfortunately, I couldn't get the above output. I'm sorry, I couldn't completely understand how the `rotate` command works. Could you please help me with this?

**Comment by marcomusy** [comment]
if you want to rotate _everything_ why not rotating the camera?
`show(nx_pts, nx_edg, nx_pts.labels('id'), axes=True, bg='w', title='plot', roll=90)`

PS; change `.addScalarBar(title='$\mu$')` to `.addScalarBar(title='\mu')`
