### ISSUE TITLE
labelling while using Sphere/ Spheres

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#281]
Hi @marcomusy 

This is a follow up to the question posted  [here](https://github.com/marcomusy/vedo/issues/275#issuecomment-750790740)

Could you please explain how the labels have to be set while using Sphere/ Spheres?

For points, I do

    pts = Points(nx_pts)
    labs = pts.labels(list(label.values()), scale=5, font='VictorMono', c='k').addPos(0.05, 0, 0.5)
    
but when I try the same for `Spheres`  (`sph = Spheres(nx_pts)`)the following error appears

```
txt_lab = str(arr[i])
IndexError: list index out of range

```

Also, I am not sure how to set the labels for `Sphere`
sph = [Sphere(r=radius[n]).color(color[n]).pos(pos[n]).alpha(alpha[n]) for n in nodes]
 
```
plt.show(
            pts, # or sph
            edg,
            labs)
```

**Comment by marcomusy** [comment]
You have many options:
```python
from vedo import *
import numpy as np

cols = ['r', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g']
spheres = [Sphere(r=0.2).color(c).pos(np.random.randn(3)) for c in cols]
for i in range(len(spheres)):
    spheres[i].name += str(i)

labs = [s.caption(s.name, size=(0.075,0.04)) for s in spheres]
show(spheres, labs, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/103173775-8d9d8080-485d-11eb-8bce-a429cf14bfb9.png)

Or:
`labs = [s.vignette(s.name, s=0.1).followCamera() for s in spheres]`
![image](https://user-images.githubusercontent.com/32848391/103173805-c2113c80-485d-11eb-9ce5-3b6986ef2d52.png)

Or  simply use `Text()` to add individual commentary to any sphere/node.

**Comment by DeepaMahm** [comment]
@marcomusy 
Thanks a lot. I really like the follow camera feature.

To simply add Text to spheres I tried

```
spheres = [Sphere(r=0.2).color(c).pos(np.random.randn(3)) for c in cols]
for i in range(len(spheres)):
    spheres[i].name += str(i)

labs = [s.Text(s.name) for s in spheres]

```
`AttributeError: 'Sphere' object has no attribute 'Text'
`
I'm not sure shape.Text() isn't working :/

**Comment by marcomusy** [comment]
no! `Text` is an object like `Sphere`, not a method.. :) 
```python
from vedo import *
import numpy as np

cols = ['r', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g', 'g']
spheres = [Sphere(r=0.2).color(c).pos(np.random.randn(3)) for c in cols]
for i in range(len(spheres)):
    spheres[i].name += str(i)

labs = [Text(s.name, pos=s.pos()+[.3,0,0], s=0.1, c='k').followCamera() for s in spheres]
show(spheres, labs, axes=1)
```
<img width="334" alt="Screenshot 2020-12-27 at 20 37 25" src="https://user-images.githubusercontent.com/32848391/103178480-62c62300-4883-11eb-8baf-68b4e803326c.png">

**Comment by DeepaMahm** [comment]
Hi @marcomusy 
Thanks so much!

Could you please help me with setting axis limits?
While plotting with `Text` labels for spheres, sometimes the  y-axis includes the y-values for which there is no data

![image](https://user-images.githubusercontent.com/29662579/103191863-8d07f700-48fc-11eb-937b-75ea8ea4312d.png)

So I tried specifying the ylimits

   plt.show(
            pts,
            edg,
            labs,
            ylim=[70, 200]
)

but this doesn't seem to work, unfortunately.

**Comment by marcomusy** [comment]
`ylim` only applies to the `vedo.pyplot.plot()` shortcut.
The syntax is passing to `show` a dictionary of options for axes. E.g.:
```python
show(spheres, labs, axes=dict(xrange=(-5,5),
                              yrange=(-5,5),
                              zrange=(-5,5),
                             ),
     )
```
check all possible options: https://vedo.embl.es/content/vedo/addons.html#axes
or create a custom `Axes()` object, see example: `examples/pyplot/customIndividualAxes.py`
and https://github.com/marcomusy/vedo/blob/master/examples/pyplot/customAxes.py
