### ISSUE TITLE
How to remove a specified Mesh in many meshes without showing it, not really deleting.

### ISSUE THREAD

**Issue by Jesse0818** [marcomusy/vedo#282]
I need to hide a Mesh model on the interface. What should I do?

**Comment by marcomusy** [comment]
you can turn its visibility off:
`mesh.off()`
or remove it form the renderer:
```python
# ...
plt = show(...)
plt.remove(mesh, render=True)
```
or interactively by clicking the mesh and pressing `x`.
the `Mesh` object won't be deleted.
