### ISSUE TITLE
Drag helper to rotate a plane and display info on click of a volume slice

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#286]
I would like to display a helper similar to the ones used for slicing (the sphere that you can drag to slice an object) but instead I would like this to drive the orientation of a plane. Is there something in vedo to do this or should I implement event listeners with mouse down to activate drag, mouse move to update while dragging and mouse up to cancel it?

**Comment by marcomusy** [comment]
Check out the latest version:
`pip install -U git+https://github.com/marcomusy/vedo.git`
has that functionality

**Comment by nantille** [comment]
Great! Is there a way to retrieve the position of the mouse in the volume (in order to get the scalar value pointed by the mouse)?

Also I noticed something strange with the cutter on volume: the inside of the volume appears dark but I know that the cut part has uniform scalar values so it should be colored without some kind of shadowing. Is there a way to raycast/raytrace without shadows?

**Comment by marcomusy** [comment]
> Great! Is there a way to retrieve the position of the mouse in the volume (in order to get the scalar value pointed by the mouse)?

Not sure if it's possible at all - but it's an interesting idea - i need to think about it


> Also I noticed something strange with the cutter on volume: the inside of the volume appears dark but I know that the cut part has uniform scalar values so it should be colored without some kind of shadowing. Is there a way to raycast/raytrace without shadows?

try `volume.mode(1)`, though i dont quite understand the reason- can you post a snapshot?

**Comment by nantille** [comment]
When I set mode(1), I get the default (horrible) output with this dark shadowing.
![Screenshot 2021-01-07 at 16 59 01](https://user-images.githubusercontent.com/10866779/103915817-fe6d5400-510b-11eb-85ed-4b66b177c86c.png)

Zooming in, the same artifact as below appears.
![Screenshot 2021-01-07 at 16 59 35](https://user-images.githubusercontent.com/10866779/103915880-0f1dca00-510c-11eb-9e69-7f8a6a2dac4f.png)


When I use mode(0), I get a flat output but there's no accumulation of transparency. Here I set the color map to 0.5 alpha everywhere but the volume appears uniform. 
![Screenshot 2021-01-07 at 16 57 21](https://user-images.githubusercontent.com/10866779/103915641-c0703000-510b-11eb-8637-405fe34efb04.png)

Also an artifact between region boundaries appears. I had the same issue with vtkImageReslice once but I cannot reproduce it here.
![Screenshot 2021-01-07 at 16 57 32](https://user-images.githubusercontent.com/10866779/103915772-eac1ed80-510b-11eb-8462-97f0e53b1f93.png)

I hope that the above imagers are not raycasting/raytracing because it looks very far from what you can do with Paraview (see image below). Is there an option to enable raytracing on volumes?

In the meantime, I went with another solution using vtkImageReslice. 
![Screenshot 2021-01-07 at 17 13 57](https://user-images.githubusercontent.com/10866779/103916053-44c2b300-510c-11eb-8024-b57dd9d2ff53.png)

But I still need to display volumetric data on top of that, such as with raytracing/raycasting.

For finding where we are in the volume, I guess the approach would be to do raycasting to see where the ray hits on the sliced volume. Not sure how easy this is. Otherwise, using the vtkImageReslice approach, I could find the position on the plane of the image mesh but for some reason, listening to click events does not work on such a mesh (any pointer would be appreciated).

**Comment by marcomusy** [comment]
Added a new [example](https://vedo.embl.es/#gallery) (search "sliceplane")
`pip install -U git+https://github.com/marcomusy/vedo.git`

![Screenshot from 2021-01-08 03-03-10](https://user-images.githubusercontent.com/32848391/103968775-c80ff300-5164-11eb-8f58-fd35910554b1.png)

About the ray casting thing i'll look into it.

**Comment by nantille** [comment]
Thank you, it's a great help. However I found a nasty bug with this: if you set a color map or LUT to the image reslice with alpha (in my case only one LUT value set to alpha 0, the rest to 1), the entire slice becomes disabled even if it is "pickable".
I opened a new ticket here https://github.com/marcomusy/vedo/issues/291
