### ISSUE TITLE
Screenshots and mesh alignment when plotting

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vedo#287]
Hi @marcomusy!
I have been having some issues trying to use the screenshot function in vedo. I am not sure if I am using the function correctly as everytime I run it I get a window with many errors and the kernel needs to be restarted... Here an example of the code I am using. 

vp = Plotter(N=3, axes=7)
text = filename + "\n\n >> Heart layers and chambers"; txt = Text2D(text, c=c, font=font)
vp.show(m_myoc, txt, at=0) 
vp.show(m_endo, at=1)
vp.show(m_cj, at=2, elevation = elevation, azimuth = azimuth, interactive=True)
screenshot(filename='screenshot.png', scale=None, returnNumpy=False)

Another thing I wanted to ask you is if there is a way meshes that are plotted in different subplots, within the same window, can have their own camera centered on each object, but when interacting with either of the plots, all plots get to be moved and rotated in the same way? The reason I am asking this is because I have built different meshes that I would like to compare in the same window, but since they have different shapes and sizes, they all have different centers of mass, and when I plot them, all appear to be centered using the last plotted mesh as the next image shows.
![AlignPlots](https://user-images.githubusercontent.com/10684503/103896752-5dba6c80-50ea-11eb-9b64-534ff66c1ce6.PNG)

Let me know your thoughts, 
Best wishes and happy new year!
Juliana

**Comment by marcomusy** [comment]
Hi Juliana
thanks - Happy New Year to you as well! Have you tried with `sharecam=False` otherwise all renderers use the same, eg:
```python
from vedo import *

settings.useParallelProjection=True
settings.screeshotLargeImage=True

c1 = Cube().scale(1)
c10 = Cube().scale(10).x(10)
c100 = Cube().scale(100).x(100)

show(c1, c10, c100, N=3, sharecam=0, axes=13).screenshot('pic.png')
```
![Screenshot from 2021-01-07 15-13-21](https://user-images.githubusercontent.com/32848391/103902986-96167680-50fb-11eb-9069-b1d04638edce.png)
Another option is to normalize the objects to the same scale

The screenshot looks ok - what error message do you get?

**Comment by jsanchez679** [comment]
Hi @marcomusy , 
The screenshot I sent you was taken using the Snipping tool from windows. 
Looking at the code you just sent, I modified my code like this:

vp = Plotter(N=3, axes=7)
text = filename + "\n\n >> Heart layers and chambers"; txt = Text2D(text, c=c, font=font)
vp.show(m_myoc, txt, at=0) 
vp.show(m_endo, at=1)
vp.show(m_cj, at=2, elevation = elevation, azimuth = azimuth, interactive=True).screenshot(filename='screenshot.png')

and the error I get is: 
'Plotter' object has no attribute 'screenshot'.

Regarding the other question, I have tried using sharecam=False, but in that case I am not able to interact with any object from the subplot and make all the subplots move at the same time in the same way. I think the problem is that the center of each of my objects in the subplots is different. Is there a way I can have a different camera position per subplot and again move all the meshes around their own center when I interact with any of them?
Let me know if this makes sense! 
Thanks,
Juliana

**Comment by marcomusy** [comment]
Hi - you probably have an old version of vedo, try:
`pip install -U git+https://github.com/marcomusy/vedo.git`
You cannot have different cameras moving at the same time - it makes more sense to shift the objects to same place:
```python
from vedo import *

settings.screeshotLargeImage=True

c1 = Cube().scale(1)
c10 = Cube().scale(10).x(10)
c100 = Cube().scale(100).x(100)

cm = c1.centerOfMass()
c1.normalize()
c10.normalize().pos(cm)
c100.normalize().pos(cm)

show(c1, c10, c100, N=3, axes=7).screenshot('pic.png')
```
you can maybe skip the normalize() if the shapes are roughly the same size

**Comment by jsanchez679** [comment]
Hi @marcomusy 
I recently updated vedo from vtkplotter==2020.2.4 wanting to try the screenshot function in the pipeline I have been writing and haven't really managed to make it work. 
I run my programme in Spyder and most of my plots are written this way:
```
    vp = Plotter(N=6, axes=7)
    vp.show(myoc_cut, txt, at=0, zoom=1)
    vp.show(endo_cut, at=1, zoom=1)
    vp.show(myoc_cut_int.color('turquoise'), at=2,  zoom=1)
    vp.show(cj_all.clone().alpha(0.05), at=3,  zoom=1)
    vp.show(myoc_cut.clone().alpha(0.1), endo_cut, cj_all, at=4)
    vp.show(endo_cut_ext.color('orchid'), at=5, zoom=1, interactive=True)

```
I remember I originally tried using the just the `show ` function directly (as in your example) but that has always given me problems, as it blocks the kernel and I have to restart it without giving me an error. 
After updating, I tried adding the part `.screenshot('pic.png')` to the last of my lines, but it is still blocking/freezing the kernel....

Additionally, I used to access the legend/name of a mesh or object using the built-in function `meshX.legend()`, but that is no longer working and it is instead returning the same object, in this example `meshX`. I tried using the function `printInfo()`, as in the previous version I could see the legend of the object with it, but it is also not working.... I know the meshes have a legend as when I plot them the legend appears on the top-right corner, just like in this figure:

![Capture](https://user-images.githubusercontent.com/10684503/105772328-ebef7900-5f59-11eb-91da-0ab1d045442c.PNG)


Finally, is there a way I can control the size of the legend in this kind of plots? The legends appear to be increasing in size if I plot them several times in a row (see picture below as example, this was the second time I run the same plot code). 

![Capture2](https://user-images.githubusercontent.com/10684503/105772533-35d85f00-5f5a-11eb-806a-19b2146b1be9.PNG)

Let me know all your thoughts. 
Thanks in advance!
Juliana

**Comment by marcomusy** [comment]
Hi Juliana,
I would not use the legend anyway because it doesn't behave very well.
The `legend()` method indeed returns the _self_ so that it can be chained. E.g.
```python
from vedo import *

myoc_cut     = Sphere().c('g')
endo_cut     = Cube().c('r').legend('cut(Endo)')
myoc_cut_int = Ellipsoid().legend('IntMyoc(cut)')
cj_all       = Cylinder().alpha(0.5).c('o').legend('CJ')
endo_cut_ext = Pyramid().legend('Ext.Endo(Cut)')
txt          ='LS17_F09_V'

#right before the show command:
settings.legendSize = .3
settings.legendPos = 1
settings.legendFont="Theemim"
embedWindow(False) # maybe this fixes the spyder problem?

vp = Plotter(N=6, axes=7)
vp.show(myoc_cut, txt, at=0)
vp.show(endo_cut, at=1)
vp.show(myoc_cut_int.color('turquoise'), at=2)
vp.show(cj_all.clone().alpha(0.5), at=3)
vp.show(myoc_cut.clone().alpha(0.1), endo_cut, cj_all, at=4)
vp.show(endo_cut_ext.color('orchid'), at=5)
interactive()
```
![image](https://user-images.githubusercontent.com/32848391/105785409-19005380-5f7b-11eb-89b1-c1258050958c.png)

Instead of `legend` you can create a `Text2D()` and add it to the renderer.

**Comment by jsanchez679** [comment]
Hi @marcomusy ,
Thanks for your reply. I think I didn't explain myself very well in my last message. Is there a function I can use where I can get the legend I assigned to a mesh/object in the new version of vedo? The reason I need this is because I am using a for loop to save in memory many different objects and was previously using the output from the mesh.legend() function, which returned a string to get the name of the object and save it using it. 

I'll give it a go to the settings you suggested to avoid the growth of the legends in the plots.
Any additional things to try to get the screenshot function to work? It seems to work fine when recording videos, but not when taking screenshots of the plots.

Let me know, 
Juliana

**Comment by marcomusy** [comment]
Hi Juliana, sorry if I misunderstood

> Is there a function I can use where I can get the legend I assigned to a mesh/object in the new version of vedo

Yes it is internally stored in `mesh._legend` as a text string

> Any additional things to try to get the screenshot function to work? It seems to work fine when recording videos, but not when taking screenshots of the plots.

That's pretty strange because internally the Video class uses `screenshot()`, what is the output?

**Comment by jsanchez679** [comment]
Hi @marcomusy , 
Thanks for your reply. mesh._legend is working perfectly now! Thanks
On the other hand, there is no output if I just use the screenshot function. The kernel just freezes and I have to restart it.

**Comment by marcomusy** [comment]
does this script generate the screenshot?
```python
import vtk

cone = vtk.vtkConeSource()
cone.SetHeight(3.0)
cone.SetRadius(1.0)
cone.SetResolution(10)

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(500, 500)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

renWin.Render()

w2if = vtk.vtkWindowToImageFilter()
w2if.SetInput(renWin)
w2if.ReadFrontBufferOff()  # read from the back buffer
w2if.Update()
writer = vtk.vtkPNGWriter()
writer.SetFileName('screenshot.png')
writer.SetInputData(w2if.GetOutput())
writer.Write()

iren.Start()
```

**Comment by chushan89** [comment]
Hi @marcomusy ,
The VTK one could generate a screenshot. However, when I use `show(c1, c10, c100, N=3, axes=7).screenshot('pic.png')`, there is not figure saved. Do you have a clue to solve this?
best,
Zhiwei

**Comment by marcomusy** [comment]
Hi Zhiwei, 
what is your operative system? can you do
`pip install vedo -U`
and try again?

**Comment by Zhiwei-Zhai** [comment]
Thanks, Marcomusy. It works.
