### ISSUE TITLE
Draw a circle or sphere whenever mouse moves

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#288]
Hello Marco,

Could you guide me a on how to implement something like Meshmixer selection model (see figure below), which a projected circle is shown on a mesh based on the mouse cursor (or a sphere with circle based on mouse cursor)? I am thinking something related to mouseMoveEvent, but I don't know how to get a 3D position from mouse cursor and update the circle and sphere whenever mouse moves.
![image](https://user-images.githubusercontent.com/9615481/103975082-4a86bb80-5141-11eb-8247-6c3f858ba762.png)

**Comment by marcomusy** [comment]
Try the following, related to #286 
```python
"""Slice a Volume with an arbitrary plane
hover the plane to get the scalar value"""
from vedo import *
import vtk

vol = Volume(datadir+'embryo.slc').alpha([0,0,0.8]).c('r').pickable(0)

sl = vol.slicePlane(origin=vol.center(), normal=(0,1,1))
sl.cmap('Purples_r').lighting('off').addScalarBar(title='Slice', c='w')

plt = show(vol, sl, __doc__, axes=9, bg='k', bg2='bb', interactive=False)

def funcMove(iren, event):
    x, y = iren.GetEventPosition()
    picker = vtk.vtkPropPicker()
    picker.PickProp(x, y, plt.renderer)
    mesh = picker.GetActor()
    if not mesh: return
    mesh.picked3d = picker.GetPickPosition()

    ptid = mesh.closestPoint(mesh.picked3d, returnPointId=True)
    val = arr[ptid]
    txt = f"Slice point:\n{precision(mesh.picked3d, 3)}\nvalue = {val}"
    vpt = Sphere(mesh.points(ptid), r=1, c='orange7').pickable(False)
    vig = vpt.vignette(txt, s=7, offset=(-150,15), font=2)#.followCamera()
    msg = Text2D(txt, pos='bottom-left', font="VictorMono")
    plt.remove(plt.actors[-3:], render=False) # remove the last 3
    plt.add([vpt, vig, msg])                  # add the new ones


arr = sl.getPointArray()
plt.actors += [None,None,None] # holds sphere, vignette, text2d
plt.resetcam = False
plt.addCallback('MouseMoveEvent', funcMove)
interactive()
```
![s1](https://user-images.githubusercontent.com/32848391/104026407-26b98900-51c6-11eb-8a82-8ef71081d0cc.gif)

**Comment by Tai-Hsien** [comment]
Hello Marco,
I am not able to reproduce the code. I always got an error as below. Could you help? Many thanks!
```
ptid = mesh.closestPoint(mesh.picked3d, returnPointIds=True)
TypeError: closestPoint() got an unexpected keyword argument 'returnPointIds'
```

**Comment by Tai-Hsien** [comment]
I actually found the spherical cutter example (https://github.com/marcomusy/vedo/blob/master/examples/basic/cutter.py), which is the exact the same thing I would like to do.
However, I am also not able to implement the code. The error is as follows.
```
plt.addCutterTool(s, mode='sphere') #modes= sphere, plane, box
TypeError: addCutterTool() got an unexpected keyword argument 'mode'
```
My vedo version is 2020.4.2. Is there something I did wrong? Thanks for your help.

**Comment by marcomusy** [comment]
you need to do
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by Tai-Hsien** [comment]
Perfect! It solved all issues. I suggest updating the website regarding the "Download & Install", which is only "pip install vedo".
Many thanks again!

**Comment by marcomusy** [comment]
You're welcome.
"pip install vedo" is fine - the thing is that you needed the `dev` version which has been not yet released :)

**Comment by nantille** [comment]
This works at the moment only without alpha in the color map. See https://github.com/marcomusy/vedo/issues/291
