### ISSUE TITLE
Ability to provide vertex normals instead of having them computed

### ISSUE THREAD

**Issue by theponpon** [marcomusy/vedo#290]
Hi there,

I am using vedo more and more as a fast validation / debugging tool and it works really great.
As I am working with meshes coming from the CAD world, it is very important to keep a tight control on the vertex normals provided by the CAD importer instead of having them computed after the mesh creation.
Would be great to extend the trimesh2vedo() function to take directly the vertexNormals array of the trimesh when available instead of recomputing them!

Thanks in advance

Pierre

**Comment by marcomusy** [comment]
Hi Pierre, I'm happy that you find it useful :) 
You can assign any point array to a vedo Mesh with name "Normals", e.g.
```python
import numpy
import trimesh

tmesh = trimesh.primitives.Sphere()

import vedo
vmesh = vedo.trimesh2vedo(tmesh).printInfo()

arr = numpy.ones_like(vmesh.points())

vmesh.addPointArray(arr, "Normals").printInfo().show()
print(vmesh.getPointArray("Normals"))
```

**Comment by theponpon** [comment]
Hi Marco, 
Thanks for the quick answer!
I should have added that I wanted to have a smoothed rendering using these vertex normals.
Today I can have a smooth rendering if I use vedo.mesh.computeNormals(points=True) (as far as I understood).
What I want is the same smoothing but using the vertex normals I provided, not the ones computed.

Note: if I call
    vedo_mesh.computeNormals(points=True, cells=False)
    vedo_mesh.addPointArray(tri_mesh.vertex_normals, "Normals")
I have a crash:
[2021/01/10 13:27:04]     vedo_mesh.addPointArray(tri_mesh.vertex_normals, "Normals")
[2021/01/10 13:27:04]   File "/home/pixyz/anaconda3/envs/visqa/lib/python3.7/site-packages/vedo/base.py", line 888, in addPointArray
[2021/01/10 13:27:04]     raise RuntimeError()

Again, thanks for a great module!

Pierre

**Comment by marcomusy** [comment]
Oh I see what you mean... even if they are called "Normals" the are not used..
You can bypass this with a small hack
```python
import trimesh
import vedo

tmesh = trimesh.primitives.Sphere()

vmesh = vedo.trimesh2vedo(tmesh).lw(0.1).printInfo()

# make an independent copy with normals
vmesh2 = vmesh.clone().computeNormals(points=True, cells=False)
arr2 = vmesh2.getPointArray("Normals") # can be any array
# now attach arr2 as normals to the first vmesh
vmesh.addPointArray(arr2, "Normals")
vmesh.polydata().GetPointData().SetActiveNormals("Normals") # <-hack
vmesh.show()
```

I will add the functionality that if an array is called "Normals" it will be used as ..normals :)

**Comment by theponpon** [comment]
Hi Marco,

Replacing
    vedo_mesh.computeNormals(points=True, cells=False)
with
    vedo_mesh.addPointArray(tri_mesh.vertex_normals, "Normals")
    vedo_mesh.polydata().GetPointData().SetActiveNormals("Normals")  # <-hack

did the trick!
Thanks a lot!

And Happy New Year!

Pierre
