### ISSUE TITLE
Shadows onto a custom plane

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#293]
Hi Marco, 

Happy new year, hope everything's fine with you. 

I have a quick question: is there a method for casting shadows onto a custom plane (as in, not just `mesh.addShadow(x=1)`)?

Here I have 3d trajectories that I'm rendering as `Tube` and a custom `Plane` that is not parallel to any cartesian plane, is there a way to project the shadows of the trajectories onto the plane?

![image](https://user-images.githubusercontent.com/17436313/104227720-bdde4500-5441-11eb-80c5-7090aa81c6d6.png)

**Comment by marcomusy** [comment]
Hi Federico
Happy new year to you as well! Have you tried example `silhouette2` ?

**Comment by FedeClaudi** [comment]
That works beautifully, awesome. 
Love the new website by the way!
