### ISSUE TITLE
Reading point and connectivity information from iges files

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#294]
Hi @marcomusy 

I'd like to extract the points and connectivity information stored in an iges file. In gmsh I could read the geometry entities by importing the mesh file  ([example](https://gitlab.onelab.info/gmsh/gmsh/blob/gmsh_4_7_1/tutorial/python/x1.py)). I'd like to 
do something similar in vedo to parse the node coordinates and links. Could you please suggest how external mesh files can be imported in vedo?

**Comment by marcomusy** [comment]
Hi 
you can access the information of points an connectivity of a mesh with `mesh.point()` , `mesh.faces()` and `mesh.lines()`,
I'm not sure if that answers the question..

**Comment by DeepaMahm** [comment]
Hi @marcomusy 
I'm sorry, I think I wasn't clear 
So I tried saving the mesh information in iges file with .msh extension in gmsh and load the file in vedo to read the point and line data.

```
from vedo import io
f = io.loadGmesh("test2_gmsh.msh")

```
unfortunately, I am facing some issue here 
```
    nnodes = int(lines[index_nodes])
ValueError: invalid literal for int() with base 10: '14 32 1 32\n'
```


[test2_gmsh.msh
](https://github.com/DeepaMahm/misc/blob/master/test2_gmsh.msh)

Could you please help me with this?

**Comment by marcomusy** [comment]
I see.. it looks it's a different format from what `vedo`knows.. but it's readable in `meshio`
```python
import meshio

mesh = meshio.read('test2_gmsh.msh')
print(mesh.points)
print(mesh.cells)

print(mesh.cells[10][0])
print(mesh.cells[10][1])
```
then you can build the `vedo.Mesh` object

**Comment by DeepaMahm** [comment]
Hi @marcomusy 

That was of great help!

I would like to ask for another suggestion 

For instance in gmsh,

![image](https://user-images.githubusercontent.com/29662579/104486272-8615ff80-55f1-11eb-9a09-da4feb72aa76.png)
 
I could specify min/max element size to mesh the original network created from points and lines. I do this to add additional nodes in each edge (or `Line`). I'd like to know if such meshing option is available in vedo for adding nodes to the geometry created using vedo `Points` and `Lines`. Right now I do this externally, save in msh format, get all new points and elements, and recreate in vedo.

Thanks a lot,
Deepa

**Comment by marcomusy** [comment]
Uhm, I'm not sure - you can use the function densify - see `advanced/densifycloud.py`-  to add extra points in space
or use `delaunay2D` to make a mesh out of a cloud of points if it's 2d.
You can also subdivide a mesh (increase the triangulation density) with `mesh.subdivide()` 
I don't know if this is useful..
