### ISSUE TITLE
Volume rendering looks wrong in vedo

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#295]
I mentioned this in #286, volume rendering with a custom color map is wrong. I compared the output between paraview, vedo and pyvista. Only vedo yields these strange results.

I have to mention that my volume actor is scaled up, here by a factor of 100 but that should not be a problem.

Pyvista with color map, mapper set to smart
![Screenshot 2021-01-15 at 11 15 06](https://user-images.githubusercontent.com/10866779/104712568-fcfee580-5722-11eb-820d-16a992ebf2ff.png)

Vedo with same color map, here with mapper in gpu mode
![Screenshot 2021-01-15 at 11 09 40](https://user-images.githubusercontent.com/10866779/104712617-07b97a80-5723-11eb-9162-07fd3fec963d.png)

And here in smart mode
![Screenshot 2021-01-15 at 11 10 31](https://user-images.githubusercontent.com/10866779/104712628-0b4d0180-5723-11eb-9714-143dedd7f5b7.png)

Paraview (not with the same color map) but only to confirm that it's what I should get, also with the box widget clipping for refeference.
![Screenshot 2021-01-07 at 18 57 41](https://user-images.githubusercontent.com/10866779/104712663-19028700-5723-11eb-901d-60064fc0f1cb.png)
![Screenshot 2021-01-07 at 18 58 08](https://user-images.githubusercontent.com/10866779/104712669-1bfd7780-5723-11eb-8c9f-6acba7c51a1c.png)

**Comment by marcomusy** [comment]
Hi Nicolas,
my guess is that it has something to do with the data type.. How do you load the volume ? if it's a file, can you share it (maybe by dropbox)?

**Comment by nantille** [comment]
It is a numpy 3d array of segmented brain regions, here with custom scalar values. Here's the low resolution one attached.
[annotation_100.nrrd.zip](https://github.com/marcomusy/vedo/files/5820650/annotation_100.nrrd.zip)

**Comment by marcomusy** [comment]
I don't understand very well why you get the above.. Can you reproduce this: 
```python
import nrrd
import numpy as np
from vedo import Volume

readdata, header = nrrd.read('annotation_100.nrrd')
print(header)
print(readdata.shape)
print(np.unique(readdata).shape)

vol = Volume(readdata, mapper='gpu', mode=1)
vol.addScalarBar().show(axes=1)
```

![image](https://user-images.githubusercontent.com/32848391/104773426-555ed300-5775-11eb-9e25-e2a3d088692a.png)

**Comment by nantille** [comment]
I get the same result as you do. 
![Screenshot 2021-01-16 at 11 01 10](https://user-images.githubusercontent.com/10866779/104809340-e2913e80-57ec-11eb-902e-c7483db0153e.png)


You can tell the rendering is wrong because light colors are more transparent, which by default should not happen if I haven't set an alpha map for the transfer function. 

I loaded the same volume without any transfer function in pyvista which I suppose assigns a color map like viridis and uses a sigmoid for the alpha. I set the background to white to have a similar comparison. Here's what I get:
![Screenshot 2021-01-16 at 11 14 13](https://user-images.githubusercontent.com/10866779/104809359-0785b180-57ed-11eb-8415-4cea8e209889.png)


I should get the same result with vedo since both projects are an added layer on top of vtk. I tried setting the color map to viridis and here's what I get with vedo:
![Screenshot 2021-01-16 at 11 20 23](https://user-images.githubusercontent.com/10866779/104809368-0fddec80-57ed-11eb-86e5-3e01ed09dce0.png)

Code to reproduce the above:
```
import nrrd
import numpy as np
from vedo import Volume

readdata, header = nrrd.read('annotation_100.nrrd')
print(np.amin(readdata), np.amax(readdata))

# Most of the volume is "opaque" with this, rendering should show that somehow
alpha = np.ones(np.amax(readdata)) * 1.0
alpha[0] = 0.0

vol = Volume(readdata, c='viridis', alpha=alpha, mapper='gpu', mode=1)
vol.addScalarBar().show(axes=1)
```

**Comment by marcomusy** [comment]
I've found the issue .. try:

`pip install -U git+https://github.com/marcomusy/vedo.git`


then

```python
import nrrd, vtk
from vedo import *
from vedo.pyplot import histogram

cmap='coolwarm'

# vedo:
readdata, _ = nrrd.read('data/annotation_100.nrrd')
vol = Volume(readdata, mapper='smart').shade(False)
vol.cmap(cmap).alpha([0,1]).addScalarBar()
#vol.lighting('plastic').jittering(1) # other options
#vol.printInfo().write('annotation_100.vti')

# bare vtk:
vvol = vtk.vtkVolume()
mapper = vtk.vtkSmartVolumeMapper()
mapper.SetInputData(vol.imagedata())
otf = vvol.GetProperty().GetScalarOpacity()
otf.RemoveAllPoints()
otf.AddPoint(   0, 0)
otf.AddPoint(1303, 1)
vvol.SetMapper(mapper)
vvol.GetProperty().SetScalarOpacity(otf)
vvol.GetProperty().SetInterpolationType(2)

show([
      [vol, 'vedo'],
      [vvol,'bare vtk'],
      histogram(vol, logscale=True, bc='white', c=cmap),
     ], N=3, sharecam=False, bg=[82,87,110],
    )
```
![Screenshot from 2021-01-16 14-47-10](https://user-images.githubusercontent.com/32848391/104825004-5bc57b80-5857-11eb-9ca2-644550003d43.png)

I've added a `volume.shade()` method.
 Indeed it now campares with the default paraview:

![Screenshot from 2021-01-15 21-54-48](https://user-images.githubusercontent.com/32848391/104825035-929b9180-5857-11eb-9658-2415c0a7cad6.png)

Thanks a lot for spotting and reporting the problem!
Let me know if anything still doesn't look right.

**Comment by nantille** [comment]
Good job, thank you for handling this. It seems that now that you solved this issue, another one appears (pyvista has the same issue btw) when the volume is scaled and you rotate the camera around it. I opened a new ticket here #296.
