### ISSUE TITLE
Scaling a volume breaks rendering when the camera orbits around the volume

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#296]
Before solving #295, this issue did not exist. Now this is what happens when I scale my volume by a factor of 100.
Pyvista has the very same problem.

When you click and hold the left mouse button, VTK switches to a low-fidelity rendering to go faster but it seems this part is not scaled and it's far away close to the origin at a scale of 1 (that's what I guess is happening).
<img width="712" alt="Screenshot 2021-01-17 at 11 58 42" src="https://user-images.githubusercontent.com/10866779/104838656-bba23d80-58bc-11eb-85c5-58fd4afac9c7.png">

Releasing left mouse button shows the volume correctly.
<img width="712" alt="Screenshot 2021-01-17 at 11 58 45" src="https://user-images.githubusercontent.com/10866779/104838662-c8269600-58bc-11eb-90ed-0c9b8e4807f0.png">

Another view of the same effect:
<img width="712" alt="Screenshot 2021-01-17 at 11 58 28" src="https://user-images.githubusercontent.com/10866779/104838678-d5438500-58bc-11eb-9d95-2956a6ed9aba.png">

<img width="712" alt="Screenshot 2021-01-17 at 11 58 33" src="https://user-images.githubusercontent.com/10866779/104838687-decced00-58bc-11eb-81b2-fc409eb41188.png">

Code to reproduce this:
```
import nrrd
import numpy as np
import vedo

volume_data, header = nrrd.read('./annotation_100.nrrd')
vol = Volume(volume_data, mapper='smart').shade(False)
vol.cmap('viridis').alpha([0,1]).addScalarBar()
vol.scale([100, 100, 100])
vol.show(axes=1)
```

Associated volume data can be found in #295.

**Comment by marcomusy** [comment]
> Now this is what happens when I scale my volume

how do you scale it? does it happen if you set `mapper='gpu'` and/or `vol.shade(1)`? can you post a script?

**Comment by marcomusy** [comment]
It seems that vtk has problems in rendering on the gpu. Instead of scaling the representation of the volume you can scale the underlying dataset.
`vol = vedo.Volume(volume_data, mapper='smart', spacing=(100,100,100)).shade(False)`

**Comment by nantille** [comment]
I thought as much. Rescaling the volume is a possibility but I wanted to avoid costy operations. I don't know what's under the hood in vtk spacing but doesn't that cost more compute-wise if it interpolates with the given spacing?

**Comment by nantille** [comment]
Interestingly, changing the spacing affects rendering with the same transfer function because apparently there are more voxels. It is actually more correct now.
<img width="712" alt="Screenshot 2021-01-17 at 13 55 47" src="https://user-images.githubusercontent.com/10866779/104843643-fbbcec80-58cb-11eb-89d6-3d1906c08b81.png">

Thanks for your help. I'm not sure if you want to add this in vedo but perhaps you could check when gpu mode is set for a volume and the user calls the scale() method, that a warning is shown about this vtk rendering issue.

**Comment by marcomusy** [comment]
It's not at all more costly, because there are the same nr of voxels - it's just that 1 voxel is 100 times bigger.

It is true that the rendering is slightly different , I though this might be due to the `vol.alphaUnit()` but that doesn't seem to be the case.. so I don't quite understand why it's different..

**Comment by nantille** [comment]
Perfect if there's no added computation and memory usage. Do you mean to say that alphaUnit should be also scaled to 100?
Your guess was right, I used alphaUnit(100) and now the rendering looks like when the volume is not scaled ("spaced up").

<img width="712" alt="Screenshot 2021-01-17 at 14 09 11" src="https://user-images.githubusercontent.com/10866779/104843968-ae417f00-58cd-11eb-9b6b-a8a20585cad3.png">

**Comment by nantille** [comment]
I can close this, thank you for your help!
