### ISSUE TITLE
Can this be applied to AR(Augmented reality)？

### ISSUE THREAD

**Issue by Jesse0818** [marcomusy/vedo#300]
Hi, Marc
Whether Vedo can take the 3D model and load it into the picture through the Augmented Reality method.
Please give me an example if you can.
Thank you.

**Comment by marcomusy** [comment]
I know that vtk offert support to VR but this has _never_ been tested in `vedo`... you can give it a try with 
```python
from vedo import settings
settings.useOpenVR=True
# ...
```
but i would be surprised if it actually worked :)
