### ISSUE TITLE
decimate warnings and segfault

### ISSUE THREAD

**Issue by schlegelp** [marcomusy/vedo#301]
Hi! I'm trying to construct a `vedo.Mesh` from a list of vertices + triangle faces to then apply a decimate. But get (a) weird warnings and (b) segfaults with some meshes.

I have attached a mesh that causes warnings + segfaults.

```Python
>>> import vedo
>>> import trimesh as tm
>>> m = tm.load('example_mesh.ply')
>>> vm = vedo.Mesh([m.vertices, m.faces])
>>> dm = vm.decimate(.5)
/Users/prabhu/src/git/VTKPythonPackage/standalone-build/VTK-source/Common/Core/vtkMath.cxx, line 507
Unable to factor linear system

[lots more of these warnings]

Segmentation fault: 11
```

This is with vedo `2020.4.2`. Any thoughts?

Many thanks,
Philipp

[example_mesh.ply.zip](https://github.com/marcomusy/vedo/files/5880188/example_mesh.ply.zip)

**Comment by marcomusy** [comment]
It seems to me that there's something wrong in the polygonal data.. playing with `pymeshfix`:
```python
import vedo
import trimesh as tm

m = tm.load('data/example_mesh.ply')

vm = vedo.Mesh(m).triangulate().smoothLaplacian().computeNormals()

from pymeshfix import MeshFix
meshfix = MeshFix(vm.points(), vm.faces())
meshfix.repair()
repaired = vedo.Mesh(meshfix.mesh)

dm = repaired.decimate(method='pro')
vedo.show(vm, dm, N=2, axes=dict(digits=3))
```
![image](https://user-images.githubusercontent.com/32848391/106007914-14d95080-60b7-11eb-8955-44f852bbe532.png)

the mesh is chopped in at least on point.

**Comment by schlegelp** [comment]
Ah, that's quite possible! This mesh is made from segmentation data (voxels) and is anything but perfect. Thanks for the quick response!
