### ISSUE TITLE
Multiple instances of same mesh

### ISSUE THREAD

**Issue by theponpon** [marcomusy/vedo#305]
Hi there, 
I am having a hard time figuring out if it is possible to have several instances of the same mesh with different transforms.
This is important for rendering speed purposes when you have a LOT of instances of the same mesh (nuts and bolts for example)

Thank you in advance,

Pierre

**Comment by theponpon** [comment]
Hi Marco,

Thank you for the answer.
Unfortunately, I need a different transform matrix for each instance, so the Glyph will not work.
As for the mesh input sharing, it does not speed up the rendering, which is what I am looking for.

It would be great to be able to add a mesh with a list of transforms and let the system understand that it can create instances

Regards,

Pierre

**Comment by marcomusy** [comment]
@theponpon  this is weird.. I posted yesterday a solution and it looks like it disappeared.. i post it again:

```python
from vedo import *
from numpy import random

cone = Mesh(datadir+'shuttle.obj') 

positions = random.rand(5000, 2)*1000
oarr = random.randn(5000, 3)

gl = Glyph(positions, cone, orientationArray=oarr, c=range(len(positions)))
show(gl, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/106588911-a62f4380-654b-11eb-8a03-dfe5c61af83e.png)
