### ISSUE TITLE
GUI transform tool

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#307]
Hello macro,

I am wondering if vedo is able to make a GUI transform tool like Meshmixer does (see example below), which we can use the arrows or curves to translate or rotate the object (e.g., a mesh).
![image](https://user-images.githubusercontent.com/9615481/106625859-16869680-6545-11eb-92ac-5d5987e1d523.png)

Another silly question is do you know how to recover the mesh position after `rotate` function? I can get the original position by `mesh.clone().points()` before rotating, but I don't know how to properly/easily to assign the numpy array (i.e., the output of `points()` function) back to the rotated mesh.

BTW, Thanks for working on vedo. It helps me finish many things in my project! It's really amazing.

**Comment by marcomusy** [comment]
Hi @Tai-Hsien thanks for using `vedo` and for reporting possible problems.
Indeed there is little choice about the style of interaction - but you can pan the whole scene by dragging the mouse while pressing the middle button.
You can zoom in/out with the right-click button +drag.
This is for the whole scene.

If instead you press **a**, you enter in actor mode and you can modify the position of a mesh relative to the axes in the scene (not the whole scene) with the same combinations above.

Press **a** again and you to go back to normal mode.


About the object transformation, you can access the object original and transformed points with:
```python
from vedo import *

cone = Cone().x(100) #Cone(r=0.5, res=50)

print(cone.points(transformed=True)[:10])
print(cone.points(transformed=False)[:10])
print([cone.getTransform()])
```
you can also apply a transformation with `mesh.applyTransform(t)`

**Comment by Tai-Hsien** [comment]
Hello macro,

Switch to TrackballActor might be a good idea, but it looks like this function is disable in Qt? I tried the pyqt example and my own application. None of them can switch to TrackballActor mode by pressing **a**.
In addition, an interactive handle might be easier for users who is not really familiar with using keyboard and mouse together. It could be my personal experience. :)

For the transformation, what if I would like to restore the position of c2 from c1 in the below case?
```
from vedo import *

c1 = Cube()
c2 = c1.clone().c('violet').alpha(0.5) # copy of c1
v = vector(0.2,1,0)
p = vector(1,0,0)  # axis passes through this point
c2.rotate(90, axis=v, point=p)
l = Line(-v+p, v+p).lw(3).c('red')
show(c1, l, c2, axes=1)
```

**Comment by marcomusy** [comment]
- Yes you can do it, check out :
`examples/other/qt_window2.py`

- You can access the current transformation and invert it:
```python
from vedo import *

c1 = Cube()
c2 = c1.clone().c('violet').alpha(0.5) # copy of c1
v = vector(0.2,1,0)
p = vector(1,0,0)  # axis passes through this point
c2.rotate(90, axis=v, point=p)

# invert current transformation, so put back c2 in place
T = c2.getTransform().GetInverse()
c2.applyTransform(T)

l = Line(-v+p, v+p).lw(3).c('red')
show(c1.wireframe().lw(3), l, c2, axes=1)
```

**Comment by Tai-Hsien** [comment]
Hello macro,

Is it possible to get the transform if a mesh is repositioned in TrackballActor model?

**Comment by marcomusy** [comment]
Yes - it's already in place:
```python
from vedo import *

c1 = Cube()
c2 = c1.clone().c('violet').alpha(0.5) # copy of c1
v = vector(0.2,1,0)
p = vector(1,0,0)  # axis passes through this point
c2.rotate(90, axis=v, point=p)

T = c2.getTransform()
print(T)

show(c1.wireframe().lw(3), c2, axes=1) # press a during interaction then q

T = c2.getTransform()
print(T)

show(c1.wireframe().lw(3), c2, axes=1)
```

**Comment by Tai-Hsien** [comment]
Hello Macro,

Sorry that I didn't explain it clearly. What I mean is the way that press **a** to enter in actor mode. Once we reposition it by using mouse, can we also get the corresponding transform made by the mouse operation?

**Comment by marcomusy** [comment]
The second T in the above example gives you the desired result. If you want to have it interactively you need to use `plotter.addCallback()` to have a function which is called while the window is active.
E.g

```python
from vedo import *

c1 = Cube()
c2 = c1.clone().c('violet').alpha(0.5) # copy of c1
v = vector(0.2,1,0)
p = vector(1,0,0)  # axis passes through this point
c2.rotate(90, axis=v, point=p)

def f(evt):
    if not evt.actor: return
    printc(c2.getTransform(), c=evt.actor.color())

plt = Plotter()
plt.addCallback('LeftButtonPress', f)
plt.show(c1, c2, axes=1)
```

**Comment by Tai-Hsien** [comment]
I will play with them! Many thanks!
