### ISSUE TITLE
splitByConnectivity not giving the number of expected meshes

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vedo#308]
Hi @marcomusy !
Hope this message finds you well. 
I have been using the splitByConnectivity funtion and I am not getting the number of meshes I would expect as an output. The code I am using is: 
    `splitem = test_mesh.splitByConnectivity(maxdepth=2)`
Where test_mesh is clearly a mesh that has a gap and thus should be divided into two different meshes (see image below). 
![image](https://user-images.githubusercontent.com/10684503/106739365-f6240e00-6610-11eb-9905-24b8774b9a05.png)
The result of running that line  is just a list containing one mesh, the top one (see image below), so I have been playing with the maxdepth parameter and with different integer values greater than 0 the result is always a list containing the top mesh...
![image](https://user-images.githubusercontent.com/10684503/106739751-63d03a00-6611-11eb-84f9-a9e39bcfcf50.png)

How can I make it to work? 
Find the test_mesh in vtk format in this folder: https://www.dropbox.com/sh/8w8tr5lu08jv2y6/AACIngVE7KsCtvX-igovp_Efa?dl=0

Let me know what you think. 

best, 
Juliana

**Comment by marcomusy** [comment]
Hi - It's a bug!
you can fix it manually by changing 

https://github.com/marcomusy/vedo/blob/b2d34999d45e9802b2351850707b55d51f072218/vedo/mesh.py#L1930

to +1 
or wait for the next release..

![image](https://user-images.githubusercontent.com/32848391/106776305-3d77c200-6644-11eb-8b84-2bcaefd7bb8e.png)

thanks for reporting it.

**Comment by jsanchez679** [comment]
Awesome! I changed it and it worked. Thanks you @marcomusy
