### ISSUE TITLE
How to measure the distance of two points in the mesh?

### ISSUE THREAD

**Issue by NeuZhangQiang** [marcomusy/vedo#309]
If I have a mesh, I pick two points in the mesh. How can I calculate the distance of the two points along the mesh？

In addition, has vedo provided examples for mesh measurement? For example, to calculate the volume, surface area, radius for a closed mesh?

**Comment by marcomusy** [comment]
yes check out https://github.com/marcomusy/vedo/blob/master/examples/advanced/geodesic.py

you can get area and volume by `mesh.area()` and `mesh.volume()` methods.
