### ISSUE TITLE
Error building color scheme with vedo.color.buildPalette

### ISSUE THREAD

**Issue by danhussey** [marcomusy/vedo#310]
Vedo version: 2020.4.2
vtk version: 9.0.1

Hello,

I'm attempting to build a colour palette between two hue values using HSV colour system. When I attempt to use the function vedo.colors.buildPalette, it returns: TypeError: no overloads of RGBToHSV() take 1 argument.

Upon investigating, it seems that in colors.py, hsv2rgb is indeed only passing in one parameter to HSVtoRGB, when vtk.math.HSVtoRGB doesn't only take one parameter and return the RGB, but instead edits a reference passed through a second parameter.

I changed hsv2rgb to:

```
def hsv2rgb(hsv):
    """Convert HSV to RGB color."""
    ma = vtk.vtkMath()
    rgb = [0,0,0]
    ma.HSVToRGB(hsv, rgb)
    return rgb 
```

And that seemed to fix as a workaround.

Thanks,
Daniel

**Comment by marcomusy** [comment]
Hi Daniel
thanks a lot for reporting the issue, it will be fixed in the next release.
Marco
