### ISSUE TITLE
Get clicked element and scalar of a set of lines (and points)

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#312]
Hello,

I'm using a point cloud to group elements and I'd like to retrieve a scalar value (each point has one) when I click on a point.
I'm not sure what is the difference between getPointArray() and getCellArray(), I suppose this is another terminology for points vs polygons in VTK. So if I get a mesh from the click event which is the point cloud, how do I retrieve the right index from getPointArray() data?

Do I have to do a spatial query on top of that or is there a simple way of accessing the point where the click occured?

Any pointer to documentation or examples I might have missed is welcome.

**Comment by marcomusy** [comment]
Hi
Clicking on a point will print the value for the point:
```python
from vedo import *

def onLeftClick(mesh):
    idx = mesh.closestPoint(mesh.picked3d, returnIds=True)
    print(idx, "clicked", mesh.picked3d, values[idx])

plt = Plotter()
plt.mouseLeftClickFunction = onLeftClick

pts = Mesh(datadir+"teapot.xyz").pointSize(10)
pts.cmap('jet', pts.points()[:,2])
print(pts.getArrayNames())
values = pts.getPointArray(0)

plt.show(pts, axes=1)
```
![Screenshot from 2021-02-13 22-35-51](https://user-images.githubusercontent.com/32848391/107862249-db8d3880-6e4b-11eb-8ccf-0041802082ab.png)

BUT: this will likely change in the next release, although in this particular case it should be back compatible.

**Comment by nantille** [comment]
Thanks for your answer.

OK, picked3d was the property I was looking for (I was even using it somewhere in my code).
But when I try to get a picked3d on a line, I either get its start or end point, which is normal because I get a point id.
Is there a way to get the position where I click on the line but also the line itself?

Is this right? `coordinate = mesh.closestPoint(mesh.picked3d, returnPointId=False)` but then how do I get the line itself? I can query the closest point id with 
```
pt_id = mesh.closestPoint(mesh.picked3d, returnPointId=True)
value = mesh.getPointArray(0)[ptid]
```
but let's say I would like to retrieve all points from that line, is there a way to have a reference to the line and its points?

**Comment by nantille** [comment]
Also, is there a list of the new features and breaking changes somewhere?
Last thing, I found Points (2D sprites) and Spheres but for Lines, I couldn't find a corresponding Cylinders class.
I'm interested to know how these object groups work under the hood. Is this similar to a particle system with a mesh instance replicated at every point of the system, with a transformation matrix applied to it and some custom attributes? Or is it simply a group of objects?

**Comment by marcomusy** [comment]
- Simpler than that. The `mesh` variable already contains the `Line` object!
```python
from vedo import *

def onLeftClick(mesh):
    print("clicked", mesh.picked3d, [mesh])

plt = Plotter()
plt.mouseLeftClickFunction = onLeftClick

pts = Line([0,0,0],[1,2,3]).pickable(True).c('r').lw(8)

plt.show(pts, axes=1)
```
and this already returns the point clicked along the line.
You may also use `utils.pointToLineDistance()` if the point you are querying is not on the line.

> Also, is there a list of the new features and breaking changes somewhere?

- I try  do document changes in https://github.com/marcomusy/vedo/blob/master/docs/changes.md 
probably not the best way ..
Also in the code itself I usually add some warning or deprecation..

> I couldn't find a corresponding Cylinders class. I'm interested to know how these object groups work under the hood. 

- it's not a simple group of objects (in that case it would be an `Assembly`).
Instead it's analogous to a glyphed mesh where an imput mesh is repeated at each single vertex with a prescribed local transformation. Check out:
https://github.com/marcomusy/vedo/blob/master/examples/basic/glyphs.py
https://github.com/marcomusy/vedo/blob/master/examples/basic/glyphs_arrows.py
https://github.com/marcomusy/vedo/blob/master/examples/pyplot/glyphs3.py

**Comment by nantille** [comment]
Thanks for the explanations. `utils.pointToLineDistance()` will come in handy.

Does the above code work with Lines, not just Line? If I have many lines, I want to have them grouped as glyphs but still be able to click on them. Is `mesh.picked3d` going to give me the selected glyph?

**Comment by marcomusy** [comment]
> Does the above code work with Lines, not just Line?

Yes - it should, but variable `mesh` in that case will be the whole `Lines` object. You may add a vector of ids to identify the lines individually. You may also use `mesh.addIDs()`.

**Comment by nantille** [comment]
OK that's what I imagined, this is similar to setting a scalar value per line.
Could you tell what to add in the code below to retrieve the ID from the correct line?
```
import vedo
import numpy as np

plot = Plotter()

# Starts and ends are 3D arrays of same length and distances is a 1D array of same length
lines = vedo.Lines(starts, ends).lw(1).cmap('Accent', distances, on='cells')
lines.addIDs(np.arange(len(starts)))

def onLeftClick(mesh):
    line_id = mesh.closestPoint(mesh.picked3d, returnIds=True)
    # Is this correct?
    print('Selected line', line_id, 'from lines grouped as glyphs at', mesh.picked3d)

plot.mouseLeftClickFunction = onLeftClick
plot.add(lines)
plot.show()

**Comment by marcomusy** [comment]
This works even without addIDs:
```python
from vedo import *

pts1 = [(sin(x/8)  , x/5, 0) for x in range(25)]
pts2 = [(sin(x/8)+2, x/5, 0) for x in range(25)]

lines = Lines(pts1, pts2, c='t').lw(8)


def onLeftClick(mesh):
    line_id = mesh.closestPoint(mesh.picked3d, returnIds=True)
    print('Selected cell', line_id, 'at', precision(mesh.picked3d,3))

plot = Plotter()
plot.mouseLeftClickFunction = onLeftClick
plot.show(lines, lines.labels('id', cells=True), axes=1)
```
![Screenshot from 2021-02-16 17-30-01](https://user-images.githubusercontent.com/32848391/108092081-a156ad80-707c-11eb-8678-de6c3361ae1a.png)

**Comment by nantille** [comment]
Thanks Marco. :)
