### ISSUE TITLE
selectCellArray() & selectPointArray() on unstructured triangular mesh from legacy VTK

### ISSUE THREAD

**Issue by adofarsi** [marcomusy/vedo#313]
Hi, I'm importing an unstructured triangular mesh from a legacy vtk file (e.g. _57.vtk, attached):

[_57.vtk.zip](https://github.com/marcomusy/vedo/files/5973008/_57.vtk.zip)

`mesh = load("_57.vtk")`

This contains several point and cell arrays:

`print(mesh.getArrayNames())`

`{'PointData': ['Velocity', 'Displacement', 'RadialDisplacement'], 'CellData': ['ElementNumber', 'S00', 'S11', 'S01', 'PS1', 'PS2', 'PorePressure']}`

It's my understanding that I should be able to select the active array field to be plotted using selectCellArray() and selectPointArray(). For example if I want to plot the cell array called "S11":

`mesh.selectCellArray('S11')`
`mesh.color('jet')`
`show(mesh)`

Instead, no matter which array I activate, it always plots the first point or cell array in the list from mesh.getArrayNames(). In this case it would always print the point array "Velocity", no matter which array I activate with selectCellArray() or selectPointArray():
![image](https://user-images.githubusercontent.com/18035301/107792105-a817b480-6d4c-11eb-869c-e28af9e92d8d.png)

I was able to plot different fields by deleting the first arrays with removePointArray and removeCellArray(), but this is not a very elegant solution to this problem.

Thank you for your help

**Comment by marcomusy** [comment]
Hi Ado,
thanks for pointing out this.. indeed the select thing is a bit misleading.. better to use `cmap()`:
```python
from vedo import *

mesh = Mesh("_57.vtk").lighting('off').lw(0.1)
pts = mesh.points()
print(mesh.getArrayNames())

# velocities as arrows and their magnitude as cmap
name = 'Velocity'
velos = mesh.getPointArray(name)
varrows = Arrows(pts, pts+velos/100).c('k')
mesh.cmap('Reds', mag(velos)).addScalarBar(title=name)
show(mesh, varrows, name, axes=1)

# select cell array
mesh.cmap('viridis', 'S11', on='cells').addScalarBar(title='S11')

show(mesh, 'S11', axes=1, new=True)
```
![Screenshot from 2021-02-13 15-35-55](https://user-images.githubusercontent.com/32848391/107852604-f347cb00-6e11-11eb-830d-cd0555a9cba6.png)
![Screenshot from 2021-02-13 15-39-58](https://user-images.githubusercontent.com/32848391/107852603-f17e0780-6e11-11eb-9e8e-df5c1e95c6e5.png)

**Comment by adofarsi** [comment]
Hi @marcomusy , thank you for your prompt reply!

The velocities as arrows and their magnitude as cmap works well, but when I run the commands for the select cell array I get a different output:

![image](https://user-images.githubusercontent.com/18035301/107947528-64aa8980-6f8a-11eb-9796-27a844c232bd.png)

Whilst I am able to reproduce the correct cell array when I use my previous workaround:

![image](https://user-images.githubusercontent.com/18035301/107947648-93286480-6f8a-11eb-896d-d12b540f80a7.png)

I cannot figure out why. Also, how do you control when to show the mesh (element edges) in the output?

Thank you again!

**Comment by marcomusy** [comment]
Hi Ado, 
that's quite weird.. Can you reproduce this:
```python
from vedo import *
mesh = Mesh("_57.vtk").lighting('off').lw(0.1)
mesh.cmap('viridis', 'S11', on='cells')
show(mesh, axes=1)
```
![Screenshot from 2021-02-15 15-52-39](https://user-images.githubusercontent.com/32848391/107961277-f5db2980-6fa5-11eb-88ac-334a7c45d45f.png)
(press `h` to get details about python , vtk and vedo versions)

The mesh edges visibility is controlled by `.lw()`, equivalent to `lineWidth()`.

**Comment by adofarsi** [comment]
Hi Marco, sorry for the late reply and thank you for your help!
It took me quite a while to realise that the behaviour with the k3d backend in the visualisation window imbedded in the Jupyter Notebook is different from the behaviour with 'embedWindow(False)' in the external window.
- I was able to reproduce your output adding 'embedWindow(False)'. Is there a way to obtain similar behaviour with the k3d backend? It seems to me that with k3d many of the controls (e.g. axes, lineWidth) behave differently or do not work.
- When I use the external window with 'embedWindow(False)' and I try to close the window or I end the cell code, it loads for a while before giving me an error. Is there a way to end a visualisation avoiding this?

Thank you!

![image](https://user-images.githubusercontent.com/18035301/108598316-e3d20000-7384-11eb-9c6b-a3e774fc870e.png)

**Comment by marcomusy** [comment]
Hi Ado, sorry I did not guess that you were using it from jupyter.

1. Indeed the behavior is quite different - I hope I'll be able to improve on this later on (related to #317 )

2. you may try:
`show(mesh, axes=3).close()`
note that `show()` returns the current `Plotter` object (so you can close it later in your script).
