### ISSUE TITLE
Get render window in jupyter and integrate it with ipyvtk

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#317]
Hello,

It seems that ipyvtk-simple supports all vtk-based viewers in jupyter notebooks.
What kind of code would allow embedding a plot made with vedo inside [ipyvtk](https://github.com/Kitware/ipyvtk-simple)?

It seems to work with Paraview and pyvista.
I tried to plug plot.window into ipyvtk but I got none.

Is there a way to retrieve the window from `plot.show()` in jupyter notebook?
```python
from vedo import *
from ipyvtk_simple.viewer import ViewInteractiveWidget
# embedWindow(False) # ideally, we would specify ipyvtk here
plot = Plotter()
obj = load(datadir+"cessna.vtk")
plot.show(obj)
# After show, I should have access to window property
print(plot.window) # yields None
ViewInteractiveWidget(plot.window) # So this won't work obviously
```

**Comment by marcomusy** [comment]
Thanks for pointing this out, tha'ts in my to-do list since a while.
It actually already works out of the box if you uncomment the line embedWindow

![Screenshot from 2021-02-18 15-02-47](https://user-images.githubusercontent.com/32848391/108368265-88740680-71fa-11eb-91d5-0ac8f69abbd4.png)

I need to find the way to avoid popping up the standard rendering window though.
I'm a bit stuck at the moment with other things, i'll be able to try it out only by the end of next week..

**Comment by nantille** [comment]
Ah! I was really close. I thought embed(False) was set by default.

However the whole point of launching this in a jupyter notebook is to interact with it, also with code, calling functions in other cells in the notebook.

If you add a cell below your current notebook and write `obj.c('black')`, the change will not happen before I quit the current window. There's also a bug if I hit Enter or another dummy key when I'm in the window pop-up, it seems to freeze because there is no exit(), so I have to kill the process to terminate this properly.

Is code interactivity going to be supported you think, some way or another?

**Comment by nantille** [comment]
I found out that when I use jupyter notebook from within visual studio, the code launches a vtk pop up and if you click on it and hit Enter, then the same window appears and becomes interactive in the notebook, while the pop up freezes like it's endlessly waiting for an exit.

Then I can run code in other cells of the notebook. But to end the visualization, I've got to kill the pop up or restart the kernel. So I guess we're not far from having vedo nicely integrated within jupyter notebooks.

**Comment by marcomusy** [comment]
Thanks Nicolas for reporting these behaviors.. I need to put some order into the backends and check for various environments (vstudio, spyder etc * OS windows linux mac...)

**Comment by nantille** [comment]
Thanks Marco for looking at this (not until next week I understand :)).
Last detail, for some reason, the embed window in VS is much slower than the initial pop-up. That's maybe due to the frozen pop-up that is waiting for an exit while at the same time being held by interaction in VS (just a hypothesis).

**Comment by nantille** [comment]
Hi Marco, is there a way we can move forward with this? Let me know if I can help, pointing me out to the stuff I could try.

**Comment by marcomusy** [comment]
Hi Nicolas, 
doesn't it work if you set
`embedWindow('ipyvtk')`
in the latest release?

**Comment by nantille** [comment]
It does work! I haven't checked the releases recently so I had no idea. Thanks a lot for making that work!
As a side-note, if like me you have some commented code below the line `ViewInteractiveWidget(plot.window)`, the viewer will not appear in the notebook and instead you will have what's in the comments printed. Just remove any commented below that and it works like a charm.

**Comment by nantille** [comment]
If you want a code example to demo vedo, here's one with a class that works. 
By the way, the window in jupyter notebook is noticeably slower than the standalone window. Do you think there is something that can be improved with vedo or should I rather ask on ipyvtk-simple side? I noticed the same slowdown with other jupyter integrators.

Also, I noticed that when I add a button, slider or something, the viewer pops up a window (that is frozen) and then the viewer appears in jupyter notebook and you can control it normally. When I have no UI, I only see the window in the notebook. Do you know why?

```
import vedo
from ipyvtk_simple.viewer import ViewInteractiveWidget
vedo.embedWindow('ipyvtk')

class Viewer:
    
    def __init__(self):
        self.plot = vedo.Plotter()
        self.obj = vedo.load(vedo.datadir+"cessna.vtk")
    
    def render(self):
        self.plot.show(self.obj, interactive=False)
        # It's necessary to return the result of ViewInteractiveWidget
        # or your window will not be loaded in the notebook
        return ViewInteractiveWidget(viewer.plot.window)
        
viewer = Viewer()
viewer.render()
```

**Comment by marcomusy** [comment]
Thanks! To be honest I have no idea of how ipyvtk works..
One possible slight simplification to the above:
```python
import vedo
vedo.embedWindow('ipyvtk')

class Viewer:
    
    def __init__(self):
        self.plot = vedo.Plotter()
        self.obj = vedo.load(vedo.datadir+"cessna.vtk")
    
    def render(self):
        self.plot.show(self.obj, interactive=False)
        # It's necessary to return the result of ViewInteractiveWidget
        # or your window will not be loaded in the notebook
        return vedo.settings.notebook_plotter
        
viewer = Viewer()
viewer.render()
```
no need to import ipyvtk..
maybe we might give `vedo.settings.notebook_plotter` some better name

**Comment by marcomusy** [comment]
uhm.. wait this already works..:
```python
import vedo
vedo.embedWindow('ipyvtk')

class Viewer:
    
    def __init__(self):
        self.plot = vedo.Plotter()
        self.obj = vedo.load(vedo.datadir+"cessna.vtk")
    
    def render(self):
        plt =self.plot.show(self.obj)
        return plt
        
viewer = Viewer()
viewer.render()
```
would be cool to know how to get rid the popping up window though

**Comment by nantille** [comment]
This is great if we don't have to import ipyvtk and all. Well, for antialiaising, I feel that it doesn't work on lines in standard windows (not on jupyter notebooks), on MacOS.

**Comment by nantille** [comment]
A note here: ipyvtk-simple was renamed to ipyvtklink. Please include the renaming in your next update. :)
