### ISSUE TITLE
Call a function every n millisecond for an animation in an asynchronous/non-blocking way (event loop?)

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#319]
I display a visualization with plot.show(interactive=True) and when the user clicks on some button, I want to play an animation. However I couldn't find the proper mechanism for doing so. I tried using Threads or the scheduler module and then I tried a simple for loop like this:
```python
for i in range(100):
    some_function_that_moves_an_object()
    plot.show()
    # time.sleep(0.1) # Is this useful?
```
But this doesn't work.

Is there a way to have an interactive view and to play an animation at the same time? I see in vedo examples in the tunelling effect demo that a simple for loop calls multiple times plot.show() but in my case there was an initial call to plot.show(interactive=True) so how do I quit this interactive mode to let the animation play, that is, if interactive and animation cannot happen at the same time?

**Comment by marcomusy** [comment]
Hi maybe something like this can work for you:
```python
from vedo import *

plt = Plotter()

msh = Mesh(datadir+"magnolia.vtk").c("v").flat()

def buttonfunc():
    bu.switch() # change to next status
    pb = ProgressBar(0, 200)
    for i in pb.range():
        msh.rotateZ(2)
        #plt.allowInteraction()
        plt.render()
        pb.print()
    bu.switch() # change to next status

# add a button to the current renderer
bu = plt.addButton(
    buttonfunc,
    pos=(0.7, 0.05),  # x,y fraction from bottom left corner
    states=["click to start", " ...running "],
    c=["w", "w"],
    bc=["dg", "dv"],  # colors of states
    font="courier",   # arial, courier, times
    size=25,
    bold=True,
    italic=False,
)

plt.show(msh, axes=1)
```
about interactivity it's a bit tricky and would need some revision as this functionality has never been tested a lot, uncommenting `plt.allowInteraction()` can partially allow for interacting with the scene.

**Comment by nantille** [comment]
Thanks Marco for the suggestion! However this blocks the UI entirely. I need at least to let the user pause the animation whenever she/he feels like it. I'll investigate if delegating this to a separate thread could work. But if you have a better idea, don't hesitate to mention it. :)

**Comment by nantille** [comment]
I solved it. There's some unwanted code in vedo like the "allowInteraction" part in settings.
As I thought, vtk has an accessible internal event loop. I thought listening to TimerEvent was enough but you have to trigger a repeating timer (so the user actually controls it).

In a class, I use the following to have a button that plays an animation:
```
import vtk
import vedo

class Viewer:

    def __init__():
        # your code
        self.plot = None
        self.timer_id = None
        self.button = None
        self.animation_playing = False

    def initialize_app():
        # Not sure what this does but make sure it's set to False (see below)
        # It doesn't keep you from interacting with the plot
        settings.allowInteraction = False
        self.plot = Plotter()
        self.plot.interactor.AddObserver('TimerEvent', self.handle_timer)
        self.button = self.plot.addButton(yourparams)
        # Later on you will call self.plot.show() and interactive()

    def play_time_series(self, widget=None, event=None):
        self.button.switch()
        self.animation_playing = not self.animation_playing

        if self.timer_id is not None:
            self.plot.interactor.DestroyTimer(self.timer_id)
        if self.animation_playing:
            self.timer_id = self.plot.interactor.CreateRepeatingTimer(100)

    def handle_timer(self, iren, event):
        # animate your stuff here
        print('TimerEvent')
```

If `vedo.settings.allowInteraction = True`, then the code below kicks in (from vedo/plotter.py) and kills the app (!) if a TimerEvent is caught.
```
        if settings.allowInteraction:
            self._update_observer = None
            self._update_win_clock = time.time()

            def win_interact(iren, event):  # flushing renderer events
                if event == "TimerEvent":
                    iren.TerminateApp()

            self.interactor.AddObserver("TimerEvent", win_interact)

            def _allowInteraction():
                timenow = time.time()
                if timenow - self._update_win_clock > 0.1:
                    self._update_win_clock = timenow
                    self._update_observer = self.interactor.CreateRepeatingTimer(1)

                    if hasattr(self, 'interactor') and self.interactor:
                        self.interactor.Start()

                    if hasattr(self, 'interactor') and self.interactor:
                        # twice otherwise it crashes when pressing Esc (??)
                        self.interactor.DestroyTimer(self._update_observer)
```

**Comment by marcomusy** [comment]
Thanks Nicolas for this - it looks great!
.. indeed the `iren.TerminateApp()` should rather be `iren.ExitCallback()`

I worked on a bit on your script - here is a version that might serve as a reference example:
```python
import vedo


class Viewer:

    def __init__(self, *args, **kwargs):
        self.dt = kwargs.pop("dt", 100)
        self.timer_id = None
        self.animation_playing = False
        self.counter = 0 # frame counter

        vedo.settings.allowInteraction = False # avoid automatic timer creation
        self.plotter = vedo.Plotter(*args, **kwargs) # setup the Plotter object
        self.timerevt = self.plotter.interactor.AddObserver('TimerEvent', self.handle_timer)

    def initialize(self):
        self.button = self.plotter.addButton( self._play,
                                              states=["|> Play ", "|| Pause"],
                                              font="Calco", size=32,
                                              pos=(0.75, 0.075),
                                            )
        return self

    def _play(self, widget=None, event=None):
        self.button.switch()
        self.animation_playing = not self.animation_playing
        if self.timer_id is not None:
            self.plotter.interactor.DestroyTimer(self.timer_id)
        if self.animation_playing:
            self.timer_id = self.plotter.interactor.CreateRepeatingTimer(self.dt)

    def handle_timer(self, iren, event):
        # animate your stuff here
        self.plotter.actors[0].rotateZ(1) # rotate the Cube
        self.plotter.actors[1].color(self.counter) # change color to sphere
        self.plotter.actors[2].SetText(7, vedo.getColorName(self.counter))
        self.plotter.actors[2].SetText(1, "..press q to quit")
        self.plotter.render()
        self.counter += 1


viewer = Viewer(axes=1, dt=20).initialize()

viewer.plotter += vedo.Cube()
viewer.plotter += vedo.Sphere(r=0.1).x(1.5)
viewer.plotter += "Sphere color is"

viewer.plotter.show()
```
![Screenshot from 2021-03-02 14-16-27](https://user-images.githubusercontent.com/32848391/109654732-d413a200-7b62-11eb-9b31-a610921659db.png)

**Comment by nantille** [comment]
Ah, thanks for the comment. It helps to know it should be ExitCallback()
Good idea to add this as an example to vedo.

**Comment by marcomusy** [comment]
..this is how I thougth of implementing it : 
https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback1.py
https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback2.py
where the first is simplified version of the second.
Let me know if it makes sense to you, thanks!

**Comment by nantille** [comment]
Hey thanks for the examples. If timer_callback1.py looks simpler overall (and I'm for simplicity), it shows some practices that are probably not going to be used in production or more elaborated code (like the global keyword). I think it's better to keep things in a class and instantiate it.

**Comment by marcomusy** [comment]
yeah maybe it's oversimplifying things , i should probably remove it..
