### ISSUE TITLE
Tube Shape Circle Orientation

### ISSUE THREAD

**Issue by JGarrett7** [marcomusy/vedo#321]
While I'm sure building up my own mesh from equations will work, it would be nice if the input to the Tube function could be vectors that defined each circle's orientation rather than just points. While this isn't very useful for the body of the tube, orienting the end circles is necessary for creating an accurate graphic for my colleague's research.

**Comment by marcomusy** [comment]
You can do it by merging circles:
```python
from vedo import *


cs, arrs = [], []
for i in range(-10, 10):
    r = 10 / (i * i + 10)
    v = versor([sin(i/10), i/20, 1])
    p = [0, i/2, i]
    c = Circle(r=i/20+1).pos(p).orientation(v)
    c.lineWidth(3).lineColor('k')
    arrs.append(Arrow(p,p+v))
    cs.append(c)

# create the mesh by merging the ribbon strips
rbs = []
for i in range(len(cs) - 1):
    rb = Ribbon(cs[i], cs[i+1], closed=True, res=(150,5))
    rbs.append(rb)
mesh = merge(rbs).clean().color('limegreen')

show([cs+arrs, mesh], N=2, axes=1, bg2='lb')
```
![Screenshot from 2021-02-23 21-08-23](https://user-images.githubusercontent.com/32848391/108901647-6e339180-761b-11eb-8d97-133f615aad7c.png)

(another option could be to cut a tube with a plane)

**Comment by JGarrett7** [comment]
Much appreciated. Sorry, we couldn't find that on our own. Is there a Reddit or other place those of us who use that can discuss things to see whether a change even needs to be made? It seems wrong to involve the creator every time someone new doesn't know how to properly use something.

**Comment by marcomusy** [comment]
No problem, I'm happy to help.
If you could not find it on your own it means it was not intuitive enough and there's room for improvement :)

I also thought of setting up something like reddit or slack.. honestly i don't know what would be the best choice.. for the moment I'm using this issues and [discussion](https://github.com/marcomusy/vedo/discussions) spaces.
