### ISSUE TITLE
2D shape or text always same size (and properly oriented) wrt camera

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#322]
I would like to have some infographics displayed on top of 3D objects.

If I add a 2D shape like a circle or a text, I want it to be tied to a 3D position and always facing the camera (properly oriented) and to be at the same size, irrelevant of how much I zoom in or out. So when I move the camera field of view out of the 3D position, then the 2D infographic is not displayed.

Is there a way to do that?

**Comment by marcomusy** [comment]
maybe... - search for "caption" in the example gallery https://vedo.embl.es/
