### ISSUE TITLE
Save x3d file

### ISSUE THREAD

**Issue by ssmns** [marcomusy/vedo#324]
when i export to x3d format. 
some times the x3d file missing some tages like </x3d> or </scene> and </Transform>
i wrote a code to verify </x3d> and </scene> tags but for </Transform> i cant find a way how edit x3d exported file.

**Comment by marcomusy** [comment]
sorry I don't understand the question.. (i'm afraid i'm not an expert of x3d anyway.. )

**Comment by ssmns** [comment]
I use Exportwindows  to save current windows and use it in web . 
The exported file is an HTML and x3d file .
X3d file is a XML file and there are many tags. There tag's have a opening and close section like 
<Scene> <\Scene>
When a I export windows, the x3d and HTML files create. But in x3d file content, some tag's dose not closed. 
So I don't understands why this happens or whe, because its a randomly behaviors.

**Comment by marcomusy** [comment]
I've looked into both html and x3d files generated by the `examples/other/export_x3d.py` but i could not see any unclosed tags

**Comment by ssmns** [comment]
Of course, this problem occurs for a large file. For example, when the exported file is about 30 MB, there is just one unclosed tag. for a larger file, there are many unclosed tags.  I wrote the below code to solve the problem, but I know this is not a good solution and have some bugs. 

```
with open('main.x3d') as f:
    for line in f:
        pass
    last_line = line

modified = last_line.split('  ')

loadfile = open('main.x3d','a+')
if modified[-1] == '</Transform>\n':
    for i in range(len(modified)-1-2):
        loadfile.write('</Transform>\n')
    loadfile.write('</Scene>\n')
    loadfile.write('</X3D>')
if modified[-1] == '</Scene>\n':
    loadfile.write('</X3D>')
loadfile.close()

```

**Comment by marcomusy** [comment]
You may want to play around with the settings of the class https://vtk.org/doc/nightly/html/classvtkX3DExporter.html
by making a custom exporter function:
```python
import vtk
from vedo.docs import x3d_html
exporter = vtk.vtkX3DExporter()
exporter.SetBinary(binary)
exporter.FastestOff()
exporter.SetInput(vedo.settings.plotter_instance.window)
exporter.SetFileName(fileoutput)
exporter.Update()
exporter.Write()
x3d_html = x3d_html.replace("~fileoutput", fileoutput)
wsize = settings.plotter_instance.window.GetSize()
x3d_html = x3d_html.replace("~width", str(wsize[0]))
x3d_html = x3d_html.replace("~height", str(wsize[1]))
outF = open(fileoutput.replace('.x3d', '.html'), "w")
outF.write(x3d_html)
outF.close()
print("\save Saved files:", fileoutput, fileoutput.replace('.x3d', '.html'))
```

**Comment by ssmns** [comment]
i check it, i think my solution is a temporary solution if some one have problem with this exporter , so i closed the issue.
