### ISSUE TITLE
Lidar Data sequence Screenshot

### ISSUE THREAD

**Issue by abhigoku10** [marcomusy/vedo#326]
@marcomusy  Thanks for the wonderful library , i am using vedo to plot the lidar point cloud density data , i have few queries 

1. Can we draw bounding box for objects on point cloud data 
2. i am having a sequence of lidar frames i need to set the perceptive and take screenshots without changing the perceptive , i know how to save the screenshot but ech time new data comes in the perceptive is set to default , please share your answers 

Thanks in advance

**Comment by marcomusy** [comment]
Thanks @abhigoku10 I'm glad it's useful to you.
- you can either create a box object explicitly with `mybox = myptcloud.box(scale=1, pad=0)`
- or at the moment of rendering use `show(axes=9)`

**Comment by marcomusy** [comment]
..sorry, I just see I forgot to answer point 2.
You may want to use `show(resetcam=False)`.
You can also pass a camera setup with `show(camera=cam)`  (you can get a `cam` prototype by pressing `C` in the scene)

**Comment by abhigoku10** [comment]
@marcomusy  thanks for ur response i am able to create the required output , thanks a lot for ur support
