### ISSUE TITLE
Segmentation fault with some of the examples

### ISSUE THREAD

**Issue by jamesaisenberg** [marcomusy/vedo#327]
I'm really enjoying vedo, thanks so much!

A few of the examples seg fault immediately after they load. Specifically: align1, align4 and align5 all briefly display a visualization then seg fault. On the other hand, align2 and align3 work just fine. Most (but not all) of the other examples work fine, too.

Vedo version: 2020.4.2
Vtk version: 9.0.1
OS: Ubuntu 20.04.2
Python: 3.8.5

Let me know if there's anything else that would be helpful.

**Comment by marcomusy** [comment]
Hi James, thanks a lot for reporting this.. it's very strange - I've never seen that... could it be because of the `.flag()` thing? what happens if you just remove them?
You may also try the dev version with command
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by jamesaisenberg** [comment]
Cool! Removing .flag() fixed align1 and align5. But align4 has no .flag() and it still seg faults.

This was true for the 2020.4.2 and the dev version.

Btw this isn't a critical bug for me, just sharing it because others might be interested. Happy to try any other diagnostic tests that might be helpful.

Thanks!
-James

**Comment by marcomusy** [comment]
It's very useful to have this feedback! I guess it's something related to vtk9. Would you please try these two scripts and see if they still seg fault at the `show()` call?
```python
from vedo import *
splines = load(datadir+'splines.npy')  # file contains a list of Lines
procus = procrustesAlignment(splines, rigid=False)
alignedsplines = procus.unpack()  # unpack Assembly into a python list
mean = procus.info['mean']
lmean = Line(mean, lw=4, c='b').z(0.001) # z-shift it to make it visible
for l in alignedsplines:
    darr = mag(l.points()-mean)  # distance array
alignedsplines += [lmean]
show([splines, alignedsplines], N=2, sharecam=False, axes=1)
```
and
```python
from vedo import *
splines = load(datadir+'splines.npy')  # file contains a list of Lines
procus = procrustesAlignment(splines, rigid=False)
alignedsplines = procus.unpack()  # unpack Assembly into a python list
mean = procus.info['mean']
lmean = Line(mean, lw=4, c='b').z(0.001) # z-shift it to make it visible
show(splines, axes=1)
```

Thanks for your patience!

**Comment by jamesaisenberg** [comment]
Those two scripts both seg fault on my machine. Happy to try anything else.

Thanks!

**Comment by marcomusy** [comment]
Uhmmm maybe it's something different.. can you try:
```python
from vedo import *
splines = load(datadir+'splines.npy')  # file contains a list of Lines
print("test1")
procus = procrustesAlignment(splines, rigid=False)
print("test2")
alignedsplines = procus.unpack()  # unpack Assembly into a python list
print("test3")
mean = procus.info['mean']
print("test4")
lmean = Line(mean, lw=4, c='b').z(0.001) # z-shift it to make it visible
print("test5")
show(splines, axes=1)
```
to see where it breaks down

**Comment by jamesaisenberg** [comment]
Here's the output (the visualization appears briefly): 

```
jaisenberg@tensorbook:~$ python example3.py 
test1
test2
test3
test4
test5
Segmentation fault (core dumped)

```

**Comment by marcomusy** [comment]
oh ok! so it's probably python 3.8 reading the numpy file (?) what is the output of this:
```python
from vedo import *
splines = load(datadir+'splines.npy')  # file contains a list of Lines
print("test5", [splines])
```

**Comment by jamesaisenberg** [comment]
Here's the output, no seg fault this time:

`test5 [[(Mesh)0x7fce912a6340, (Mesh)0x7fce912a6460, (Mesh)0x7fce912a6580, (Mesh)0x7fce912a66a0, (Mesh)0x7fce912a6820, (Mesh)0x7fce912a6940, (Mesh)0x7fce912a6a60, (Mesh)0x7fce912a6b80, (Mesh)0x7fce912a6ca0, (Mesh)0x7fce912a6dc0, (Mesh)0x7fce912a6ee0, (Mesh)0x7fce912a6e80, (Mesh)0x7fce91278160, (Mesh)0x7fce91278280, (Mesh)0x7fce912783a0, (Mesh)0x7fce912784c0, (Mesh)0x7fce912785e0, (Mesh)0x7fce91278700, (Mesh)0x7fce91278820, (Mesh)0x7fce91278940, (Mesh)0x7fce91278a60, (Mesh)0x7fce91278b80, (Mesh)0x7fce91278ca0, (Mesh)0x7fce91278dc0, (Mesh)0x7fce91278ee0, (Mesh)0x7fce91278e80, (Mesh)0x7fce91206160, (Mesh)0x7fce91206280, (Mesh)0x7fce912063a0, (Mesh)0x7fce912064c0, (Mesh)0x7fce912065e0, (Mesh)0x7fce91206700, (Mesh)0x7fce91206820, (Mesh)0x7fce91206940, (Mesh)0x7fce91206a60, (Mesh)0x7fce91206b80, (Mesh)0x7fce91206ca0, (Mesh)0x7fce91206dc0, (Mesh)0x7fce91206ee0, (Mesh)0x7fce91206e80, (Mesh)0x7fce91124160, (Mesh)0x7fce91124280, (Mesh)0x7fce911243a0, (Mesh)0x7fce911244c0, (Mesh)0x7fce911245e0]]`

**Comment by marcomusy** [comment]
I got it !! this should work now:
```python
from vedo import *
splines = load(datadir+'splines.npy')
[s.flag(False) for s in splines]
show(splines, axes=1)
```
(the 'npy' format allows for setting the flag...)

**Comment by jamesaisenberg** [comment]
That worked!

![image](https://user-images.githubusercontent.com/29736153/109843531-045d4e00-7c00-11eb-893e-3d9acb0c726e.png)

**Comment by marcomusy** [comment]
..the issue remains open on why the `flag()` fails though... I'll have a look into it, in genereal you might get better visualization in vtk 8.1.2 (for example the above image lacks antialiasing which seem not to work well in vtk9) 
thanks again

*in vtk8.1.2 it shows:
![Screenshot from 2021-03-03 18-11-44](https://user-images.githubusercontent.com/32848391/109844029-01884a80-7c4c-11eb-81f7-f907a39a2790.png)

**Comment by jamesaisenberg** [comment]
Interesting, thanks for looking into it! Let me know if I can help out with debugging it.
