### ISSUE TITLE
mesh volume - inconsistent results?

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#328]
Hi Marco, 

I'm using `mesh.volume()` to compute the volume occupied by a mesh, but I'm getting weird results. 

The mesh in question is the red one
![image](https://user-images.githubusercontent.com/17436313/109820482-efe37a80-7c2c-11eb-852f-a3fee22163e8.png)

First probel is that it says that its volume is `622281333.333` which is way larger than what I'd expect (that should be about 62 cubic centimeters, but the mesh represents an object that is at max a few hundred micrometers in width so that can't be right).

The weird thing is that if I use `cutWithMesh` to only consider the part of the red mesh that is in the magenta one (and then `fillHoles` to close the cut mesh) I get a **larger** value for the volume, although the mesh is a subset of the original one:

<img width="817" alt="image" src="https://user-images.githubusercontent.com/17436313/109821256-b3fce500-7c2d-11eb-8f66-5dec217d7447.png">

Any idea what might be going on here?

**Comment by marcomusy** [comment]
very likely to be a bug.. what if you try with this:
```python
    def myvolume(mesh):
        mass = vtk.vtkMassProperties()
        mass.SetGlobalWarningDisplay(0)
        mass.SetInputData(mesh.polydata()) # REMOVE False
        mass.Update()
        v = mass.GetVolume()
        return v
```

**Comment by FedeClaudi** [comment]
No sorry it's the same:
```
Total injection volume: 622281333.333
Injected volume in SCm: 1263109159.658
```

the second value is the volume of the cut mesh.

**Comment by marcomusy** [comment]
Ok - are you sure your surfaces are closed and oriented correctly? (try `mesh.lighting("default")` to see if they are)

**Comment by FedeClaudi** [comment]
This is what it looks like  with `mesh = Mesh("examples/data/CC_134_1_ch1inj.obj").lighting('default').computeNormals()` (I'm loading the mesh from a .obj directly, bypasing brainrender).


<img width="690" alt="image" src="https://user-images.githubusercontent.com/17436313/109838460-1827a500-7c3e-11eb-8c91-2793a42ae03c.png">


 and this is without `computeNormals`:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/17436313/109838330-f62e2280-7c3d-11eb-8a5b-d6627e13da63.png">



Adding the `computeNormals` makes the volumes larger (using the custom function above) for both the intact and the cut mesh, and the cut mesh is still larger than the intact one:
Total injection volume: 708737267.931
Injected volume in SCm: 1355258191.983

**Comment by marcomusy** [comment]
Uhm I wonder if the computeNormals is doing its job... if you can share the obj I can have a closer look.

**Comment by FedeClaudi** [comment]
[CC_134_1_ch1inj.obj.zip](https://github.com/marcomusy/vedo/files/6077719/CC_134_1_ch1inj.obj.zip)

does this work?

**Comment by marcomusy** [comment]
..indeed it looks like the orientation is not quite right so the volume calculation is unreliable...
```python

from vedo import *

mesh = Mesh('CC_134_1_ch1inj.obj').clean().c("g").bc('t')
box = mesh.box()
mesh.computeNormals().flat().lw(0.1)
print(mesh.volume()/1.e+09, '/', box.clone().triangulate().volume()/1.e+09)

mesh.cutWithPlane([9100,0,0], normal=[-1,0,0])

show(mesh, box, axes=1)
```
![Screenshot from 2021-03-03 18-46-09](https://user-images.githubusercontent.com/32848391/109848759-e8ce6380-7c50-11eb-91aa-f5a803e021dd.png)


 to be honest i don't know how this could be fixed.. without some manual editing..

**Comment by FedeClaudi** [comment]
Uh okay, well good to know that the problem is with the mesh and not `vedo`. I like this method of visualizing the normals too, `vedo`is so great :)

Thanks Marco!

**Comment by marcomusy** [comment]
you can also visualize normals more directly with e.g.:
```python
# ...
mesh.cutWithPlane([9100,0,0], normal=[-1,0,0])
ns = mesh.normals(compute=False)*10

show(mesh, Lines(mesh.points()+ns/5, mesh.points()+ns), axes=1)
```
![Screenshot from 2021-03-03 20-16-03](https://user-images.githubusercontent.com/32848391/109859726-98113780-7c5d-11eb-8cf0-21df71f71e97.png)
