### ISSUE TITLE
save to STL file for 3d printing

### ISSUE THREAD

**Issue by ylada** [marcomusy/vedo#329]
Hi, 

This is a question about VEDO, not an 'issue'.
I am completely new to vedo  and VTK.  Following the cutWithMesh example, I created a cube with an isosurface (gyroid). It looks nice. However, how can I export it to an STL file so I can modify in other CAD software and 3d-print it? I looked at IO but did not get any idea. I tried  vedo.io.write(c, 'cube.stl')  but it did not work.

The cutWithMesh example is in the following link.
https://github.com/marcomusy/vedo/blob/master/examples/advanced/cutWithMesh2.py

Thank you!

**Comment by marcomusy** [comment]
Hi, try to see if can reproduce this output
```python
from vedo import *
import numpy as np

x, y, z = np.mgrid[:30,:30,:30] * 0.4
U = sin(x)*cos(y) + sin(y)*cos(z) + sin(z)*cos(x)

s = Volume(U).isosurface(0).smoothLaplacian().lineWidth(1)
c = CubicGrid(n=(29,29,29), spacing=(1,1,1)).alpha(1)

s.cutWithMesh(c).color('silver')  # take what's inside of cube
c.cutWithMesh(s).color('grey')    # take what's inside of isosurface

s.write('gyr.stl')
show(s, axes=1)
```
You can the visualize the STL file from command line with:
`vedo gyr.stl`

NB: for this specific examples 2 meshes are generated, the gyroid internal mesh and a disconnected capping mesh from the cube so you might not be able to 3d-print it..unless you do some other processing. There is another similar example where you have only one mesh: `examples/advanced/gyroid.py`

**Comment by ylada** [comment]
Thank you marcomusy for the prompt and insightful comments. For the CutWithMesh example, s.write() works fine. As you mentioned, s and c are two sets of disconnected meshes that cannot be directly printed. For the spherical gyroid example (gyroid.py), the mesh is almost printable. Meshmixer shows that the spherical gyroid has some holes that need repair. I guess they were from the boolean 'intersect' operation due to precision issues?

Is there a method / operation to create a 3d-object enclosed by several surfaces, which is water tight? I had thought it were a straightforward question but it seems not that easy.  

Thanks again!

**Comment by marcomusy** [comment]
You're welcome. I'm not so surprised that the final mesh has some holes as cutting operations are not so trivial as it might seem. You may want to try the `mesh.fillHoles()` [method](https://github.com/marcomusy/vedo/blob/master/examples/basic/fillholes.py) maybe it helps.. other related examples are boolean [methods](https://github.com/marcomusy/vedo/blob/master/examples/basic/boolean.py).

**Comment by ylada** [comment]
I will play with the methods you mentioned. 

The above is about creating an enclosed volume by isosurfaces and cubic/sphere.  A similar question would be to create a volume by thickening the isosurface (gyroid) . Thinking about extruding the surface to its normal by to a certain amount of value. Could you please shed some lights on how to do this?

Thank you again marcomusy!

**Comment by marcomusy** [comment]
You can extrude a mesh by the normals using `mesh.normals()`
Check out example `examples/advanced/fatlimb.py`

**Comment by ylada** [comment]
Thanks marcomusy! I will look into this.

**Comment by ylada** [comment]
Marcomusy,
It is not related to vedo or even my initial question. Could you please help me understand the concepts of 'mesh' and 'geometry' in VTK? It confuse me that a 'geometry' is different from 'point cloud'. What exactly does a geometry mean in the context of VTK?
Thank you!

**Comment by marcomusy** [comment]
honestly i don't know what "geometry" means for vtk.. it's often used to refer to the outer boundary of a dataset. e.g. in the vtkGeometryFilter algorithm.
In `vedo` a `Mesh` is a surface made of vertices and triangles (or other polygons).
A pointcloud are vertices without polygons, so a mesh is a pointcloud but a pointcloud is not a mesh (like all cats are mammals but mammals are not necessarily cats).

**Comment by ylada** [comment]
Many thanks for your kind inputs, marcomusy!
