### ISSUE TITLE
Return plots from different functions and replot as subplots

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#331]
Hi @marcomusy 

I've two plots generated from different functions `funa` and `funb`.

```
def funa():
      ....
      plt1 = plt.show()

def funb():
      ....
      plt2 = plt.show()

plt1 = funa()
plt2 = funb()

```
I would like to plot plt1 and plt2 in a single figure as subplots. Could you please give some hints on how to do this?
Can I do the following?
```
...
plt.show(plt1, at=0)
plt.show(plt2, at=1)

```

Thanks so much

**Comment by marcomusy** [comment]
Yes you can, but it needs to be a bit more hacky:
```python
from vedo import *

def funa():
      plt1 = Plotter(interactive=False)
      plt1.add(Cube(), render=False)
      # plt1.show()
      return plt1

def funb():
      plt2 = Plotter(interactive=False)
      s = Sphere().lw(1)
      plt2.add([s, Axes(s)], render=False)
      # plt2.show()
      return plt2

plt1 = funa()
plt2 = funb()

plt12 = Plotter(N=2)
show(plt1.actors, at=0)
show(plt2.actors, at=1)
interactive()

# OR:
# settings.plotter_instance=None # avoid automatic picking of the current plotter
# show(plt1.actors+[plt2.actors], N=2)
```
![Screenshot from 2021-03-04 16-43-41](https://user-images.githubusercontent.com/32848391/109989585-eaf3f900-7d08-11eb-89d6-fd821181682f.png)

..if you have scalarbars etc you will need to grab them and add them manually to the list.

**Comment by DeepaMahm** [comment]
perfect! thanks so much. I just had a small problem while trying to add axes in `plt.add()`. So I did `plt_return =   plt.show(pts,edg,arrsv,axes)`.

**Comment by DeepaMahm** [comment]
Hi @marcomusy,

While trying to save the following

```
from vedo import *

def funa():
      plt1 = Plotter(interactive=True)
      # plt1.add(Cube(), render=False)
      plt1.show(Cube())
      return plt1

def funb():
      plt2 = Plotter(interactive=True)
      s = Sphere().lw(1)
      scals = s.points()[:,2]
      s.cmap('jet', scals).addScalarBar3D()
      plt2.add([s, Axes(s)], render=False)
      plt2.show()
      return plt2

plt1 = funa()
plt2 = funb()

plt12 = Plotter(N=2)
plt12.show(plt1.actors, at=0)
plt12.show(plt2.actors, at=1).screenshot("test.png")

```

I see only a blank image. I did face this problem before while using vtk8 which got resolved when I installed version 9. Could you please let me know if the issue is due to something else?

I'm also facing another problem too. When I try saving my actual figure with subplots ([figure](https://github.com/DeepaMahm/misc/blob/master/Untitled.png)), the subplots overlap for some reason :/

**Comment by marcomusy** [comment]
it seems VTK is not so reliable with this thing ...
I'm not able to reproduce the issue as it works ok on my mac and ubuntu with both vtk versions :(
 vedo 2021.0.1 | vtk 9.0.1 | python 3.7

if screengrabbing with some external tools is not an option for you i don't have a good alternative.

**Comment by marcomusy** [comment]
you may try writing a custom function using native vtk:
```python
    import vtk
    # screenshot code:
    w2if = vtk.vtkWindowToImageFilter()
    w2if.SetInput(plotter.window)
    w2if.SetInputBufferTypeToRGB()
    w2if.ReadFrontBufferOff()
    w2if.Update()

    writer = vtk.vtkPNGWriter()
    writer.SetFileName('TestScreenshot.png')
    writer.SetInputConnection(w2if.GetOutputPort())
    writer.Write()
```

**Comment by DeepaMahm** [comment]
Thanks a lot for the suggestions. Unfortunately, I get a blank image with the custom code too.

I had faced this problem before and for this reason, I switched to vtk 9.0.1. But [this ](https://github.com/marcomusy/vedo/issues/280#issuecomment-789940047)issue occurred, andI switched back to vtk 8.1.2 :/

**Comment by marcomusy** [comment]
then that's likely a issue with VTK.. 
if you press `shift-I` when the rendering window is active are getting the pixel color under the mouse pointer as a printout message ?

**Comment by DeepaMahm** [comment]
Hi  @marcomusy ,

I noticed when
 1. settings.screeshotScale = # any value >1 subplots in a figure overlap
2. settings.screeshotLargeImage = False creates a blank image while saving the screenshots.
```

settings.screeshotScale = 1
settings.screeshotLargeImage = True
```
solved the issues reported above :)

**Comment by marcomusy** [comment]
Cool! one extra thing you can do is to set a larger window with `Plotter(size=())`, depending on the physical size of your screen..
