### ISSUE TITLE
Computing Curvatures

### ISSUE THREAD

**Issue by roaasoloh** [marcomusy/vedo#332]
Kindly I'm trying to compute the curvatures (principal, mean, gaussion) of the vertices in my mesh, specifically for special vertices not the whole vertices, is it possible?
I checked this function `addCurvatureScalars`
but I believe it didn't worked like what I want, since it retrieve like this:
```
vtkFollower (0x55a39080f070)
  Debug: Off
  Modified Time: 721
  Reference Count: 1
  Registered Events: (none)
  Dragable: On
  Pickable: On
  AllocatedRenderTime: 10
  EstimatedRenderTime: 0
  NumberOfConsumers: 0
  RenderTimeMultiplier: 1
  Visibility: On
  PropertyKeys: none.
  useBounds: 1
  IsIdentity: true
  Position: (0, 0, 0)
  Orientation: (0, 0, 0)
  Origin: (0, 0, 0)
  Scale: (1, 1, 1)
  Bounds: 
    Xmin,Xmax: (-0.611773, 0.864326)
    Ymin,Ymax: (-0.200548, 0.448087)
    Zmin,Zmax: (-0.238711, 0.345187)
  UserTransform: (none)
  UserMatrix: (none)
  Mapper:
    Debug: Off
    Modified Time: 644
    Reference Count: 3
    Registered Events: (none)
    Executive: 0x55a39076adf0
    ErrorCode: Success
    Information: 0x55a39098ea20
    AbortExecute: Off
    Progress: 1
    Progress Text: (None)
    TimeToDraw: 0.0001
    ClippingPlanes: (none)
    Lookup Table: (none)
    Scalar Visibility: On
    Static: Off
    Scalar Range: (0, 0)
    UseLookupTableScalarRange: 0
    Color Mode: Default
    InterpolateScalarsBeforeMapping: On
    Scalar Mode: UseCellData
    RenderTime: 0
    Resolve Coincident Topology: Off
    CoincidentPointOffset: 0
    CoincidentLineOffset: 0
    CoincidentPolygonOffset: 0
    CoincidentLineFactor: 0
    CoincidentPolygonFactor: 0
    Piece : 0
    NumberOfPieces : 1
    GhostLevel: 0
    Number of sub pieces: 1
  Property:
    Debug: Off
    Modified Time: 384
    Reference Count: 1
    Registered Events: (none)
    Ambient: 0
    Ambient Color: (1, 1, 1)
    Diffuse: 1
    Diffuse Color: (1, 1, 1)
    Edge Color: (0, 0, 0)
    Edge Visibility: Off
    Vertex Color: (0.5, 1, 0.5)
    Vertex Visibility: Off
    Interpolation: VTK_PHONG
    Opacity: 1
    Representation: VTK_SURFACE
    Specular: 0
    Specular Color: (1, 1, 1)
    Specular Power: 1
    Backface Culling: Off
    Frontface Culling: Off
    Point size: 1
    Line width: 1
    Line stipple pattern: 65535
    Line stipple repeat factor: 1
    Lighting: On
    RenderPointsAsSpheres: On
    RenderLinesAsTubes: Off
    Shading: Off
    MaterialName: (none)
    Color: (1, 1, 1)
    EmissiveFactor: (1, 1, 1)
    NormalScale: 1
    OcclusionStrength: 1
    Metallic: 0
    Roughness: 0.5
  BackfaceProperty: (none)
  Texture: (none)
  ForceOpaque: false
  ForceTranslucent: false
  Camera: (none)
```
And if it's for each vertex, what are the formulas you are following for the calculation.

Thank you.

**Comment by marcomusy** [comment]
Try
```python
from vedo import *

elli = Ellipsoid()

elli.addCurvatureScalars().cmap('coolwarm').printInfo()

print(elli.getPointArray("Gauss_Curvature"))

show(elli, axes=1)
```
<img width="299" alt="Screenshot 2021-03-05 at 14 19 23" src="https://user-images.githubusercontent.com/32848391/110120798-cdcd3200-7dbd-11eb-921b-ba20a1f5969b.png">

**Comment by roaasoloh** [comment]
I'm so thankful for your reply :)
Yes, It gives me the curvatures, and I get the specific curvatures by determining the indices needed, after extracting for the full vertices, would be a better way to extract for only specified vertices directly?.
I mean instead of retrieving the curvature for the full mesh (ex. 280 vertexes, I need the curvature for specified already determined 13 vertexes!)
but may you clarify please:
1. what `.getPointArray()` do, and how to know what parameter should I give it?
2. for `kmax` and `kmin` that are available in the `addCurvatureScalars` these refer to that for principal curvature correct?
3. again if you please if I may get the source for the formulas used behind extracting these values.

**Comment by marcomusy** [comment]
there no overhead in retrieving the full array - no problem with that. It's numpy array so you extract from it the interest values the numpy-way: `array(list_of_idx])`

1. it needs the name of the point array, which you get from `.printInfo()` in the example
2. there is no `kmin kmax` in the  `addCurvatureScalars`
2. you should look for documentation of the class [`vtkCurvatures`](https://vtk.org/doc/nightly/html/classvtkCurvatures.html)

**Comment by roaasoloh** [comment]
Sorry but I didn't get your point for this:
```
there no overhead in retrieving the full array - no problem with that. It's numpy array so you extract from it the interest values the numpy-way: array(list_of_idx])
``` 
You mean I have to retrieve all, then the desired ones!

regarding 2, sorry it's miss typing from me, I mean: `2-max, 3-min curvature` from [curvature](https://github.com/marcomusy/vedo/blob/d56e38fc1f397abfacae3d7661419e7a8669a551/vedo/mesh.py#L1240)

Thank you

**Comment by marcomusy** [comment]
> You mean I have to retrieve all, then the desired ones!

Yes, that's correct. It might seem over-killing but it's actually not: numpy takes care of that.

**Comment by roaasoloh** [comment]
Sorry again for re-opining this,
but I was wondering how I may know what to pass for `.getPointArray()` for the `min` and `max`
How I shall know the parameters! since I tried to pass different ones but didn't get the point.
```
print(mesh.addCurvatureScalars(2).printInfo())
print(mesh.getPointArray("Max-Curvature"))
```
similar if I set instead of `2` `3`

**Comment by marcomusy** [comment]
that's shown in the printout..

```python
from vedo import *

elli = Ellipsoid()

m = 3
modes = {0:"Gauss_Curvature",
         1:"Mean_Curvature",
         2:"Maximum_Curvature",
         3:"Minimum_Curvature"}

elli.addCurvatureScalars(m).cmap('coolwarm', modes[m]).printInfo()

print(elli.getPointArray(modes[m]))

show(elli, axes=1)
```
