### ISSUE TITLE
creating subplots

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#333]
Hi @marcomusy ,

I would like to create a figure with subplots (please check below)
![image](https://user-images.githubusercontent.com/29662579/110117753-4f818780-7ddf-11eb-8c11-e6b81036c995.png)
generally, I would do 
plt = Plotter(shape=(3,2)) 

However, I am not sure how to place single figure in the first column. Could you please offer some suggestions?

**Comment by marcomusy** [comment]
You have the option
`plt = Plotter(shape="1|3")`
can shift the vertical separation with
`settings.windowSplittingPosition`
with a value in range [0,1]
