### ISSUE TITLE
drawing a concentric cyliner

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#335]
Hi @marcomusy,
I'm trying to draw a concentric cylinder. I could draw a cylinder in the following way

```
pts = []
for n in nodes():
    if n in c_nodes:
        pts.append(Cylinder(r=radius[n], height=height[n]).pos(pos[n]))

show(pts, edg, axes=True, interactive=True, bg='w', title='plot')
```

I am not sure how to draw a cylinder around `Cylinder`.  I found an example [here](https://github.com/marcomusy/vedo/blob/c2cb3a4128dae6b7ddd144f31792d16080e4558e/examples/other/dolfin/magnetostatics.py) that uses inner circle and outer circle radius. I intend to specify something similar to create the concentric cylinder. Could you please help me with this?

**Comment by marcomusy** [comment]
depending on how or if you wish to cap the cylinders there are at least 2 possibilities:
```python
from vedo import *

cyl1 = Cylinder(cap=1, r=0.5).z(1)
cyl2 = Cylinder(cap=0, r=1).z(1)
cyl = merge(cyl1,cyl2) #optional

disc =Disc(res=(2,30)).extrude(2).lw(1).alpha(0.2)

show(cyl, disc, N=2, axes=1)
```
<img width="523" alt="Screenshot 2021-03-10 at 10 01 21" src="https://user-images.githubusercontent.com/32848391/110603751-a2649180-8187-11eb-8789-dbffa237cafe.png">
