### ISSUE TITLE
How to create the smooth perfect mesh on 3d data points i.e. ply file using vedo 

### ISSUE THREAD

**Issue by nikhilpatil99** [marcomusy/vedo#336]
Respected All,
I have a set of 3D data points which look uniform plane. I want it to be converted to 3D mesh using python. I was researching and found the vedo library. I am very excited to work with this library. Based on this, I tried to do surface reconstruction using the Ball pivot algorithm and also Poisson surface reconstruction. I tried the same using Meshlab software. But, I am unable to do mesh using Vedo. I need smooth mesh since I want to work on further processes using simulation, based on this mesh.
I have attached the link to the ".ply" file. I would like to know how to work with vedo to get such a kind of surface reconstruction. From vedo I am not getting perfect mesh.
[Ply file link](https://drive.google.com/file/d/1qcxoxrEJjJrsRQKMc4YEFkYH-cZnjPgH/view?usp=sharing)
Any leads will be appreciated.
Thanks in advance

**Comment by marcomusy** [comment]
Hi - if the surface is projectable onto a plane - like it seems to be the case of the ply cloud you can use delaunay triangulation which also allows to define boundaries. Try:
`pip install -U git+https://github.com/marcomusy/vedo.git`
and
```python
from vedo import *

pcloud = load("Sample_Plane.ply").pointSize(10).renderPointsAsSpheres()
labels = pcloud.labels('id', scale=0.00005, c='k').shift(0,0,0.00005)

# Use point ids to define boundaries or holes
ids = [[60,61,75,74]]
# ids=[]

dely = delaunay2D(pcloud, mode='xy', boundaries=ids)
dely.color('white').lc('orange').lw(2)

show(pcloud, labels, dely, bg2="lightblue", axes=1, zoom=1.5)
```
![Screenshot from 2021-03-10 14-17-26](https://user-images.githubusercontent.com/32848391/110635431-5f1c1a00-81ab-11eb-9451-543efa4f8dd1.png)

**Comment by marcomusy** [comment]
...another possible solution, by morphing the smoothed version back to the original cloud:
```python
from vedo import *

pcloud = load("Sample_Plane.ply").c('black').pointSize(5).renderPointsAsSpheres()

dely = delaunay2D(pcloud, mode='fit').subdivide(3).smoothLaplacian()
dely.color('white').lc('orange').lw(.1)

sources = []
for p in pcloud.points():
    sources.append(dely.closestPoint(p))

morphed = dely.thinPlateSpline(sources, pcloud)

show(pcloud, morphed, bg2="lightblue", axes=1, zoom=1.5)
```
![Screenshot from 2021-03-10 14-32-17](https://user-images.githubusercontent.com/32848391/110637371-a0152e00-81ad-11eb-96a2-46651600f217.png)

ps: you can also use `vedo` in conjunction with meshlab (see [example](https://github.com/marcomusy/vedo/blob/master/examples/other/pymeshlab1.py)).

**Comment by nikhilpatil99** [comment]
Thank you so much for the answer...its means me a lot... can you please tell me just how to export this mesh in stl format

**Comment by nikhilpatil99** [comment]
> ...another possible solution, by morphing the smoothed version back to the original cloud:
> 
> ```python
> from vedo import *
> 
> pcloud = load("Sample_Plane.ply").c('black').pointSize(5).renderPointsAsSpheres()
> 
> dely = delaunay2D(pcloud, mode='fit').subdivide(3).smoothLaplacian()
> dely.color('white').lc('orange').lw(.1)
> 
> sources = []
> for p in pcloud.points():
>     sources.append(dely.closestPoint(p))
> 
> morphed = dely.thinPlateSpline(sources, pcloud)
> 
> show(pcloud, morphed, bg2="lightblue", axes=1, zoom=1.5)
> ```
> 
> ![Screenshot from 2021-03-10 14-32-17](https://user-images.githubusercontent.com/32848391/110637371-a0152e00-81ad-11eb-96a2-46651600f217.png)
> 
> ps: you can also use `vedo` in conjunction with meshlab (see [example](https://github.com/marcomusy/vedo/blob/master/examples/other/pymeshlab1.py)).

Thank you so much for the answer...its means me a lot... can you please tell me just how to export this mesh in stl format...

**Comment by nikhilpatil99** [comment]
Thank you so much for the answer....its means me a lot...just one thing for larger part of the point cloud files it take to much time..can you please me help to solve it ...and center part of that is also getting meshed...can you help me with this
[ply file ](https://drive.google.com/file/d/1JGk0X1d9fF45losVHBpu0L4pifgrWKWm/view?usp=sharing)

**Comment by nikhilpatil99** [comment]
Thanks you so much for this solution but how to then smooth this mesh...we can't use this above given
..code for this type of mesh...
dely = delaunay2D(pcloud, mode='fit').subdivide(3).smoothLaplacian()
dely.color('white').lc('orange').lw(.1)

sources = []
for p in pcloud.points():
    sources.append(dely.closestPoint(p))

morphed = dely.thinPlateSpline(sources, cloud)


I really appreciate and thanking you from bottom of my heart for giving me reply...thanks again its mean me alot

**Comment by nikhilpatil99** [comment]
> if your cloud is not convex and you don't know the indices of the points that form its boundary (i assume you dont) then i think vtk has no good solution for this.. I suggest you check out `pymeshlab`, this could be a starting point:
> 
> ```python
> import pymeshlab
> import vedo
> 
> ms = pymeshlab.MeshSet()
> ms.load_new_mesh("sample_long.ply")
> 
> r = pymeshlab.Percentage(1)
> ms.apply_filter('surface_reconstruction_ball_pivoting', ballradius=r)
> ms.apply_filter('repair_non_manifold_edges_by_removing_faces')
> ms.apply_filter('re_orient_all_faces_coherentely')
> mlab_mesh = ms.current_mesh()
> 
> vedo_mesh = vedo.Mesh(mlab_mesh).fillHoles().smoothLaplacian()
> vedo_mesh.color('b5').backColor('t').lw(0.1)
> vedo.show(vedo_mesh, axes=1, bg2='blue9')
> ```
> 
> <img alt="Screenshot 2021-03-11 at 15 06 45" width="470" src="https://user-images.githubusercontent.com/32848391/110799406-6874b780-827b-11eb-82bb-fd0864274f96.png">

Thank you so much for this solution but how to then smooth this mesh...we can't use this above given
..code for this type of mesh...
```
dely = delaunay2D(pcloud, mode='fit').subdivide(3).smoothLaplacian()
dely.color('white').lc('orange').lw(.1)

sources = []
for p in pcloud.points():
sources.append(dely.closestPoint(p))

morphed = dely.thinPlateSpline(sources, cloud)
```

I really appreciate and thank you from bottom of my heart for giving me reply...thanks again it's mean me a lot

**Comment by marcomusy** [comment]
> Thank you so much for this solution but how to then smooth this mesh...we can't use this above given
> ..code for this type of mesh...

the `smoothLaplacian()` is already applied in the above code, besides you also have various additional filters in pymeshlab you can explore - you can open an issue [here](https://github.com/cnr-isti-vclab/PyMeshLab) maybe the maintainers have more ideas

> I really appreciate and thank you from bottom of my heart for giving me reply...thanks again it's mean me a lot

you're welcome

**Comment by nikhilpatil99** [comment]
> > Thank you so much for this solution but how to then smooth this mesh...we can't use this above given
> > ..code for this type of mesh...
> 
> the `smoothLaplacian()` is already applied in the above code, besides you also have various additional filters in pymeshlab you can explore - you can open an issue [here](https://github.com/cnr-isti-vclab/PyMeshLab) maybe the maintainers have more ideas
> 
> > I really appreciate and thank you from bottom of my heart for giving me reply...thanks again it's mean me a lot
> 
> you're welcome

Thank you so much for help ...me if knew the contur boundary point of ply file then can we use vedo library for mesh.....as you given first code.....sorry to say and ask but if you are free and don't mind then can we talk or discuss about on an call...? Please...it would be a many much more help.....thanks again

**Comment by marcomusy** [comment]
Yes - If you can identify the boundary then you could use the first script (i don't foresee problems).
Or else you can still use the pymeshlab to get that boundary and then reuse the first script.. but I would still try to do it with pymeshlab (consider that it also has subdivision algorithms that would produce a similar output to the desired one).

**Comment by nikhilpatil99** [comment]
> Yes - If you can identify the boundary then you could use the first script (i don't foresee problems).
> Or else you can still use the pymeshlab to get that boundary and then reuse the first script.. but I would still try to do it with pymeshlab (consider that it also has subdivision algorithms that would produce a similar output to the desired one).

Thanks for reply.....but can you help me to how to find out the boundary point of point of cloud ....in pymeshlab or any other method

**Comment by marcomusy** [comment]
maybe something like this is alreay satifactory for you? (note that the ball pivoting is flipping one triangle and there is one point in the center that is the only connection between the 2 parts of the mesh)
```python
import pymeshlab
import vedo

ms = pymeshlab.MeshSet()
ms.load_new_mesh("data/sample_long.ply")

r = pymeshlab.Percentage(1.1)
ms.apply_filter('surface_reconstruction_ball_pivoting', ballradius=r)
ms.apply_filter('repair_non_manifold_edges_by_removing_faces')
ms.apply_filter('re_orient_all_faces_coherentely')
mlab_mesh = ms.current_mesh()

vmesh = vedo.Mesh(mlab_mesh).fillHoles().clean().subdivide()
vmesh.backColor('tomato').lw(0.1)

vedo_mesh_boundaries = vmesh.boundaries(featureAngle=120).color('b5').lw(4)
boundaries = vmesh.boundaries(featureAngle=120, returnPointIds=True)
# print(boundaries)

bpts = vedo.Points(vmesh.points()[boundaries])

vedo.show(vmesh,
          vedo_mesh_boundaries,
          bpts.labels('id', scale=0.0001),
          axes=1, bg2='blue9'
)
```

![Screenshot from 2021-03-12 03-56-54](https://user-images.githubusercontent.com/32848391/110885388-0f426d80-82e7-11eb-9d86-fc7f154c5785.png)
![Screenshot from 2021-03-12 03-57-08](https://user-images.githubusercontent.com/32848391/110885393-110c3100-82e7-11eb-8cc4-77a47819a89c.png)

**Comment by marcomusy** [comment]
> Sorry for this one last ply file.I am sharing I am trying to do mesh on that file but it is not getting correct ...there are too many gaps. please can you help me with the last of one this ply file with perfect correct mesh and smooth ...please one last time

Maybe a volumetric-based reconstruction is the way to go:
```python
from vedo import *

plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))

vpts = load("data/FInal_last_sample.ply").ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)
vpts_orig = vpts.clone() # make a copy
plt.show(vpts_orig, "original pcloud", at=0)

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.005)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

print("smoothing cloud")
vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
plt.show(vpts, "cloud smoothed", at=1)

# reconstructed surface from point cloud
reco = recoSurface(vpts.points(), dims=[100,20,100], radius=0.002).extractLargestRegion().clean()
reco.subdivide().smoothLaplacian().computeNormals()
# reco.write("result.ply")

plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
```
![Screenshot from 2021-03-12 16-53-59](https://user-images.githubusercontent.com/32848391/110964838-ead0aa80-8353-11eb-8c46-6f9263dab644.png)
![Screenshot from 2021-03-12 16-52-56](https://user-images.githubusercontent.com/32848391/110964858-f15f2200-8353-11eb-9cb0-870ecc1a2713.png)

**Comment by marcomusy** [comment]
ps you may want to remove the vertical lines, if so you can query for the closest point in a loop for each point, and remove the point if it's closer than some threshold

**Comment by nikhilpatil99** [comment]
> > Sorry for this one last ply file.I am sharing I am trying to do mesh on that file but it is not getting correct ...there are too many gaps. please can you help me with the last of one this ply file with perfect correct mesh and smooth ...please one last time
> 
> Maybe a volumetric-based reconstruction is the way to go:
> 
> ```python
> from vedo import *
> 
> plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))
> 
> vpts = load("data/FInal_last_sample.ply").ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)
> vpts_orig = vpts.clone() # make a copy
> plt.show(vpts_orig, "original pcloud", at=0)
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.005)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> print("smoothing cloud")
> vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
> plt.show(vpts, "cloud smoothed", at=1)
> 
> # reconstructed surface from point cloud
> reco = recoSurface(vpts.points(), dims=[100,20,100], radius=0.002).extractLargestRegion().clean()
> reco.subdivide().smoothLaplacian().computeNormals()
> # reco.write("result.ply")
> 
> plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
> ```
> 
> ![Screenshot from 2021-03-12 16-53-59](https://user-images.githubusercontent.com/32848391/110964838-ead0aa80-8353-11eb-8c46-6f9263dab644.png)
> ![Screenshot from 2021-03-12 16-52-56](https://user-images.githubusercontent.com/32848391/110964858-f15f2200-8353-11eb-9cb0-870ecc1a2713.png)

Thank you much again...for this solution its means me a lot...you are great ...!

**Comment by nikhilpatil99** [comment]
> ps you may want to remove the vertical lines, if so you can query for the closest point in a loop for each point, and remove the point if it's closer than some threshold

macro I tried this technique but there is one issues. the extra more mesh part is getting added...the mesh is greater that point of cloud...i tried using if so you can query for the closest point in a loop for each point but its is no getting me...please can you help me ....thanks in advance....!

**Comment by marcomusy** [comment]
This seems to produce reasonable results on the first cloud:
```python
from vedo import *

plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))

vpts = load("data/FInal_last_sample.ply").clean()
# vpts = load("data/Final_sample_2.ply").clean()
vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)

# this block removes the vertical lines
print("before", vpts.N())
newpts =[]
for p in vpts.points():
    cps = vpts.closestPoint(p, N=2)
    for cp in cps:
        if mag(cp-p)<0.0000001: # it's the same point p
            continue
        elif mag(cp-p)>0.0001:  # p is "isolated"
            newpts.append(p)
vpts = Points(newpts).clean()
print("after", vpts.N())

vpts_orig = vpts.clone() # make a copy
plt.show(vpts_orig, "original pcloud", at=0)

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.005)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

print("smoothing cloud")
vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
plt.show(vpts, "cloud smoothed", at=1)

# reconstructed surface from point cloud
reco = recoSurface(vpts.points(), dims=[100,25,100], radius=0.001).extractLargestRegion().clean()
reco.subdivide().smoothLaplacian().fillHoles().computeNormals()
# reco.write("result.ply")

plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
```

For the second mesh it is worse:

```python
from vedo import *

plt = Plotter(N=3, axes=1)

vpts = load("data/Final_sample_2.ply").clean()
vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)

# this block removes the vertical lines
print("before", vpts.N())
newpts =[]
for p in vpts.points():
    cps = vpts.closestPoint(p, N=2)
    for cp in cps:
        if mag(cp-p)<0.0000001: # it's the same point p
            continue
        elif mag(cp-p)>0.0001:  # p is "isolated"
            newpts.append(p)
vpts = Points(newpts).clean()
print("after", vpts.N())

vpts_orig = vpts.clone() # make a copy
plt.show(vpts_orig, "original pcloud", at=0)

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.004)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

print("smoothing cloud")
vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
plt.show(vpts, "cloud smoothed", at=1)

# reconstructed surface from point cloud
reco = recoSurface(vpts, dims=[100,100,25], radius=0.0012, sampleSize=20, holeFilling=1).clean().extractLargestRegion()
# reco.subdivide() # this fails
reco.smoothLaplacian().fillHoles().computeNormals()
# reco.write("result.ply")

plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
```

Note that:
- the boundary method will not work here because there is no 2D plane to project the cloud onto. Also there's no automated way to find boundaries (or at least i cannot think of any)
- the 2 meshes are differently oriented in space
- there is no "perfect" mesh as "perfection" is not defined at all: meshing a generic - non trivial - cloud of points is not a solved problem, there is no exact nor unique solution.
- you need to explore the various parameters to find a solution that is "good enough" for your purposes. Eventually you might need to edit manually (e.g. in a meshlab GUI) the final mesh.

**Comment by nikhilpatil99** [comment]
> This seems to produce reasonable results on the first cloud:
> 
> ```python
> from vedo import *
> 
> plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))
> 
> vpts = load("data/FInal_last_sample.ply").clean()
> # vpts = load("data/Final_sample_2.ply").clean()
> vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)
> 
> # this block removes the vertical lines
> print("before", vpts.N())
> newpts =[]
> for p in vpts.points():
>     cps = vpts.closestPoint(p, N=2)
>     for cp in cps:
>         if mag(cp-p)<0.0000001: # it's the same point p
>             continue
>         elif mag(cp-p)>0.0001:  # p is "isolated"
>             newpts.append(p)
> vpts = Points(newpts).clean()
> print("after", vpts.N())
> 
> vpts_orig = vpts.clone() # make a copy
> plt.show(vpts_orig, "original pcloud", at=0)
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.005)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> print("smoothing cloud")
> vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
> plt.show(vpts, "cloud smoothed", at=1)
> 
> # reconstructed surface from point cloud
> reco = recoSurface(vpts.points(), dims=[100,25,100], radius=0.001).extractLargestRegion().clean()
> reco.subdivide().smoothLaplacian().fillHoles().computeNormals()
> # reco.write("result.ply")
> 
> plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
> ```
> 
> For the second mesh it is worse:
> 
> ```python
> from vedo import *
> 
> plt = Plotter(N=3, axes=1)
> 
> vpts = load("data/Final_sample_2.ply").clean()
> vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)
> 
> # this block removes the vertical lines
> print("before", vpts.N())
> newpts =[]
> for p in vpts.points():
>     cps = vpts.closestPoint(p, N=2)
>     for cp in cps:
>         if mag(cp-p)<0.0000001: # it's the same point p
>             continue
>         elif mag(cp-p)>0.0001:  # p is "isolated"
>             newpts.append(p)
> vpts = Points(newpts).clean()
> print("after", vpts.N())
> 
> vpts_orig = vpts.clone() # make a copy
> plt.show(vpts_orig, "original pcloud", at=0)
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.004)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> print("smoothing cloud")
> vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
> plt.show(vpts, "cloud smoothed", at=1)
> 
> # reconstructed surface from point cloud
> reco = recoSurface(vpts, dims=[100,100,25], radius=0.0012, sampleSize=20, holeFilling=1).clean().extractLargestRegion()
> # reco.subdivide() # this fails
> reco.smoothLaplacian().fillHoles().computeNormals()
> # reco.write("result.ply")
> 
> plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
> ```
> 
> Note that:
> 
> * the boundary method will not work here because there is no 2D plane to project the cloud onto. Also there's no automated way to find boundaries (or at least i cannot think of any)
> * the 2 meshes are differently oriented in space
> * there is no "perfect" mesh as "perfection" is not defined at all: meshing a generic - non trivial - cloud of points is not a solved problem, there is no exact nor unique solution.
> * you need to explore the various parameters to find a solution that is "good enough" for your purposes. Eventually you might need to edit manually (e.g. in a meshlab GUI) the final mesh.
Thank you so much for answer and reply it means me a lot...it was great pleasure of you for guiding me and helping me
