### ISSUE TITLE
getting current camera view by shift-c

### ISSUE THREAD

**Issue by ilorevilo** [marcomusy/vedo#337]
It's mentioned in several locations that pressing Shift-C in interactive mode lists the current cameraview. However I can't get this to work. Pressing Shift-C solely results in an output of several newlines. Is there something I'm overlooking?

The example I'm trying it on is [align2](https://github.com/marcomusy/vedo/blob/master/examples/notebooks/basic/align2.ipynb). I tried it both in jupyter as well as from the console without success. I'm using the current vedo version and py3.8.

**Comment by marcomusy** [comment]
Thanks for reporting this issue, what is your operative system?
in a normal (ubuntu in my case) terminal you should get something like

![Screenshot from 2021-03-12 01-07-25](https://user-images.githubusercontent.com/32848391/110871812-5b81b380-82cf-11eb-8e45-d06572ff1fa9.png)

What if you print this:
```python
from vedo import *
# embedWindow(False)
print("test1")
printc("test2")
printc("test3", c='y')
```

In jupyter it can only work if you add `embedWindow(False)`

**Comment by ilorevilo** [comment]
alright, my os is Win10, I'm running vedo from conda.
Trying your example I get `test1` as output and 2 newlines in both jupyter (with `embedWindow(False)`) and the terminal.

**Comment by marcomusy** [comment]
Should be now fixed. Try
`pip install -U git+https://github.com/marcomusy/vedo.git`

I also added the possibility to globally disable color print with
`settings.enablePrintColor=False`

**Comment by ilorevilo** [comment]
awesome, thanks a lot! My quick workaround was to replace printc with print in the shift-c callback, but that's a proper solution 🥇
