### ISSUE TITLE
difference between ".alpha"

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#340]
data:
[render_alpha.zip](https://github.com/marcomusy/vedo/files/6134473/render_alpha.zip)

code:
```
from vedo import *
settings.useDepthPeeling = True

vp = Plotter()

# method 1
# mesh_1 = load("buff.ply").alpha(0.2)

# method 2
mesh_1 = load("buff.ply")
mesh_1.alpha = 0.2

mesh_2 = load("sphere.ply")

vp.show([mesh_1, mesh_2])
```

result:
method_1
![method_1](https://user-images.githubusercontent.com/34391447/111025952-8deff580-8422-11eb-9538-9a94835276cb.png)

method_2
![method_2](https://user-images.githubusercontent.com/34391447/111025942-7b75bc00-8422-11eb-8a62-460ae15092c8.png)

**Comment by marcomusy** [comment]
"Method 2" is just wrong: in `vedo` there is no method decoration nor property wrapping.

The two methods cannot coexist in python.
