### ISSUE TITLE
minimum opengl version

### ISSUE THREAD

**Issue by bjlittle** [marcomusy/vedo#343]
Hey @marcomusy 

Thanks for such an awesome package :beers: 

Simple question: what is the minimum recommended OpenGL version required by `vedo`?

Many thanks :+1:

**Comment by marcomusy** [comment]
Hi Bill, thanks!
`vedo` builds on top of vtk, so i guess it depends on the vtk version. For version 8.1.2 the minimum required opengl seems to be 1.1 (but might need to recompile vtk using  option VTK_RENDER_BACKEND).

**Comment by bjlittle** [comment]
BTW please do close this issue now. Many thanks! :+1:

**Comment by marcomusy** [comment]
Thanks Bill for your interest! Obviously you're hired! :)
I'm planning to make a new release today if if manage to fix a couple of things.. so probably the best way to start could be to run the already existing examples and check if you can spot anything that seems weird/wrong or simply counter intuitive.
It would be extremely useful to have a "fresh look" from someone who is relatively new to the package!
To upgrade to the dev version:
`pip install -U git+https://github.com/marcomusy/vedo.git`
then
```
cd examples
./run_all.sh
```
feel free to focus only on anything specific you like though! no pressure! :)
Let me know if you need any help,
M.

PS: btw have you used `vedo` for some project already?
