### ISSUE TITLE
Giving  the boundary points of point of cloud can we get perfect mesh, not extra part mesh should be added

### ISSUE THREAD

**Issue by nikhilpatil99** [marcomusy/vedo#347]
Respected Macro,
The vedo meshing code that was provided by you in your libraries I have used it and thank you so much for that... but I have one little request that  I am found one method to find the boundary points of the 3d point of cloud using python. just I want your help that by setting boundary points or defining boundary points can we achieve perfect mesh. please can you help me to add a little feature in the meshing technique. I would like to know how to work with vedo to get such a kind of output. 
Any leads will be appreciated.
Thanks in advance

```
from vedo import *

plt = Plotter(N=3, axes=1)

vpts = load("data/Final_sample_2.ply").clean()
vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)

# this block removes the vertical lines
print("before", vpts.N())
newpts =[]
for p in vpts.points():
    cps = vpts.closestPoint(p, N=2)
    for cp in cps:
        if mag(cp-p)<0.0000001: # it's the same point p
            continue
        elif mag(cp-p)>0.0001:  # p is "isolated"
            newpts.append(p)
vpts = Points(newpts).clean()
print("after", vpts.N())

vpts_orig = vpts.clone() # make a copy
plt.show(vpts_orig, "original pcloud", at=0)

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.004)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

print("smoothing cloud")
vpts.smoothMLS2D(f=0.9)  # smooth cloud by fitting planes recursively
plt.show(vpts, "cloud smoothed", at=1)

# reconstructed surface from point cloud
reco = recoSurface(vpts, dims=[100,100,25], radius=0.0012, sampleSize=20, holeFilling=1).clean().extractLargestRegion()
# reco.subdivide() # this fails
reco.smoothLaplacian().fillHoles().computeNormals()
# reco.write("result.ply")

plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
```

**Comment by marcomusy** [comment]
Hi Nikhil, I still think it's not easily doable because:
- one needs the point IDs of the original mesh forming the boundary (but you may work out this from the point positions in a loop)
- vertical lines get in the way and boundaries do not seem perfect (see picture, eg. bottom-right)
- the pointcloud may look fairly simple, but it's rather non-trivial, in particular it is not projectable onto a plane so you cannot use the initial method (dalauney triangulation)

![Screenshot from 2021-03-19 12-55-46](https://user-images.githubusercontent.com/32848391/111776911-dd1aa800-88b2-11eb-9d8f-5395fb9f1c8e.png)

**Comment by nikhilpatil99** [comment]
> Hi Nikhil, I still think it's not easily doable because:
> 
> * one needs the point IDs of the original mesh forming the boundary (but you may work out this from the point positions in a loop)
> * vertical lines get in the way and boundaries do not seem perfect (see picture, eg. bottom-right)
> * the pointcloud may look fairly simple, but it's rather non-trivial, in particular it is not projectable onto a plane so you cannot use the initial method (dalauney triangulation)
> 
> ![Screenshot from 2021-03-19 12-55-46](https://user-images.githubusercontent.com/32848391/111776911-dd1aa800-88b2-11eb-9d8f-5395fb9f1c8e.png)

thank you for reply......
can you give me code of this mesh which you have done..

**Comment by nikhilpatil99** [comment]
Hello marco....
can you please tell me...?

**Comment by marcomusy** [comment]
Hi Nikhil, 
> can you give me code of this mesh which you have done..

I have no code!  the image above is just the visualisation of your 2 cloud points one on top of the other.. 

> boundary id means..? coordinates or indices of that xyz point..? can you please elaborate ..?

yes - indices.
But keep in mind that , even then, you may not use the delauney triangulation.
