### ISSUE TITLE
Meshing on simple curve uniform plan using vedo

### ISSUE THREAD

**Issue by nikhilpatil99** [marcomusy/vedo#348]
Shared the ply file above.
please can you see add some feature or can check what changes should be done to mesh for this kind of 3d objects.
I tried but I am not getting an perfect mesh. as the plane is curve and uniform so please check it 
[plyfile](https://drive.google.com/file/d/1jMyTh-nhMaGMfdNyXQSCp0U9l_jBG3bp/view?usp=sharing)

```
from vedo import *

plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))

vpts = load("/home/anveshak-nikhil/Only_codes_my/3march_generate_pc/23_march_bound.ply").clean()
# vpts = load("data/Final_sample_2.ply").clean()
vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)

# this block removes the vertical lines
print("before", vpts.N())
newpts =[]
for p in vpts.points():
    cps = vpts.closestPoint(p, N=2)
    for cp in cps:
        if mag(cp-p)<0.00000001: # it's the same point p
            continue
        elif mag(cp-p)>0.00001:  # p is "isolated"
            newpts.append(p)
vpts = Points(newpts).clean()
print("after", vpts.N())

vpts_orig = vpts.clone() # make a copy
plt.show(vpts_orig, "original pcloud", at=0)

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.0005)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

print("smoothing cloud")
vpts.smoothMLS2D(f=0.15)  # smooth cloud by fitting planes recursively
plt.show(vpts, "cloud smoothed", at=1)

# reconstructed surface from point cloud
reco = recoSurface(vpts.points(), dims=[250,36,250], radius=0.002).extractLargestRegion().clean()
reco.subdivide().smoothLaplacian().fillHoles().computeNormals()
# reco.write("result.ply")

plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
```

**Comment by nikhilpatil99** [comment]
> Shared the ply file above.
> please can you see add some feature or can check what changes should be done to mesh for this kind of 3d objects.
> I tried but I am not getting an perfect mesh. as the plane is curve and uniform so please check it
> [plyfile](https://drive.google.com/file/d/1jMyTh-nhMaGMfdNyXQSCp0U9l_jBG3bp/view?usp=sharing)
> 
> ```
> from vedo import *
> 
> plt = Plotter(N=3, axes=dict(zxGrid=True, xyGrid=False))
> 
> vpts = load("/home/anveshak-nikhil/Only_codes_my/3march_generate_pc/23_march_bound.ply").clean()
> # vpts = load("data/Final_sample_2.ply").clean()
> vpts.ps(5).renderPointsAsSpheres().c('k3').alpha(0.6)
> 
> # this block removes the vertical lines
> print("before", vpts.N())
> newpts =[]
> for p in vpts.points():
>     cps = vpts.closestPoint(p, N=2)
>     for cp in cps:
>         if mag(cp-p)<0.00000001: # it's the same point p
>             continue
>         elif mag(cp-p)>0.00001:  # p is "isolated"
>             newpts.append(p)
> vpts = Points(newpts).clean()
> print("after", vpts.N())
> 
> vpts_orig = vpts.clone() # make a copy
> plt.show(vpts_orig, "original pcloud", at=0)
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.0005)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> print("smoothing cloud")
> vpts.smoothMLS2D(f=0.15)  # smooth cloud by fitting planes recursively
> plt.show(vpts, "cloud smoothed", at=1)
> 
> # reconstructed surface from point cloud
> reco = recoSurface(vpts.points(), dims=[250,36,250], radius=0.002).extractLargestRegion().clean()
> reco.subdivide().smoothLaplacian().fillHoles().computeNormals()
> # reco.write("result.ply")
> 
> plt.show(reco, vpts, "reconstruction", at=2, zoom=1.2, interactive=True)
> ```

???

**Comment by marcomusy** [comment]
..well .. there is very little to do there.. the points are very much scattered all around and not lying on any well defined surface:

![Screenshot from 2021-03-24 19-26-54](https://user-images.githubusercontent.com/32848391/112364822-3b8ebe80-8cd7-11eb-9110-8c7e943d4699.png)

**Comment by nikhilpatil99** [comment]
> ..well .. there is very little to do there.. the points are very much scattered all around and not lying on any well defined surface:
> 
> ![Screenshot from 2021-03-24 19-26-54](https://user-images.githubusercontent.com/32848391/112364822-3b8ebe80-8cd7-11eb-9110-8c7e943d4699.png)
Thanks for reply...
Can you please tell and right code or any changes in code or any new features of for the making the mesh perfect ...Waiting for the solution....Thanks in advance

**Comment by marcomusy** [comment]
I cannot see a solution: your point cloud does not define a surface (your points are not on a surface), so no surface is renconstructable.

**Comment by marcomusy** [comment]
you may play with tetrahedral meshes but it's probably not a good solution anyway:
(you won't be able to close holes because the mesh is not manifold)
```python
from vedo import *

plt = Plotter(N=2, axes=dict(zxGrid=True, xyGrid=False))

vpts = load("data/Sample_demo.ply").clean()
vpts.ps(5).c('k3').alpha(0.6)
vpts_orig = vpts.clone() # make a copy

print("Nr of points before cleaning nr. points:", vpts.N())
vpts.clean(tol=0.0005)  # impose a min distance among points
print("after cleaning nr. points:", vpts.N())

# reconstructed surface from point cloud
dela = delaunay3D(vpts, alphaPar=0.0014) # tetrahedral mesh
dela = geometry(dela.inputdata()) # outer Mesh

plt.show(vpts_orig, "original pcloud", at=0)
plt.show(vpts, dela, "reconstruction", at=1, zoom=1.2, interactive=1)
```

![Screenshot from 2021-03-25 02-18-54](https://user-images.githubusercontent.com/32848391/112404346-7cef9000-8d10-11eb-8221-0a2cda097f44.png)

**Comment by larsmacro88** [comment]
> you may play with tetrahedral meshes but it's probably not a good solution anyway:
> (you won't be able to close holes because the mesh is not manifold)
> 
> ```python
> from vedo import *
> 
> plt = Plotter(N=2, axes=dict(zxGrid=True, xyGrid=False))
> 
> vpts = load("data/Sample_demo.ply").clean()
> vpts.ps(5).c('k3').alpha(0.6)
> vpts_orig = vpts.clone() # make a copy
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.0005)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> # reconstructed surface from point cloud
> dela = delaunay3D(vpts, alphaPar=0.0014) # tetrahedral mesh
> dela = geometry(dela.inputdata()) # outer Mesh
> 
> plt.show(vpts_orig, "original pcloud", at=0)
> plt.show(vpts, dela, "reconstruction", at=1, zoom=1.2, interactive=1)
> ```
> 
> ![Screenshot from 2021-03-25 02-18-54](https://user-images.githubusercontent.com/32848391/112404346-7cef9000-8d10-11eb-8221-0a2cda097f44.png)

Thank you so much for your reply... it means me a lot... i apprecticate you...is there not any other solution for this for 3d model...

**Comment by nikhilpatil99** [comment]
> you may play with tetrahedral meshes but it's probably not a good solution anyway:
> (you won't be able to close holes because the mesh is not manifold)
> 
> ```python
> from vedo import *
> 
> plt = Plotter(N=2, axes=dict(zxGrid=True, xyGrid=False))
> 
> vpts = load("data/Sample_demo.ply").clean()
> vpts.ps(5).c('k3').alpha(0.6)
> vpts_orig = vpts.clone() # make a copy
> 
> print("Nr of points before cleaning nr. points:", vpts.N())
> vpts.clean(tol=0.0005)  # impose a min distance among points
> print("after cleaning nr. points:", vpts.N())
> 
> # reconstructed surface from point cloud
> dela = delaunay3D(vpts, alphaPar=0.0014) # tetrahedral mesh
> dela = geometry(dela.inputdata()) # outer Mesh
> 
> plt.show(vpts_orig, "original pcloud", at=0)
> plt.show(vpts, dela, "reconstruction", at=1, zoom=1.2, interactive=1)
> ```
> 
> ![Screenshot from 2021-03-25 02-18-54](https://user-images.githubusercontent.com/32848391/112404346-7cef9000-8d10-11eb-8221-0a2cda097f44.png)

Thank you so much for your reply... it means me a lot... i apprecticate you...is there not any other solution for this for 3d model...
