### ISSUE TITLE
Can I use the tkinter as the GUI app?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#350]
Can I use the tkinter as the GUI app?

**Comment by marcomusy** [comment]
while there can be some option for using tkinter with vtk:
https://github.com/Kitware/VTK/blob/master/Wrapping/Python/vtkmodules/tk/vtkTkRenderWindowInteractor.py

I've never tried it out..

**Comment by timeanddoctor** [comment]
the TK for vtk should be compiled? But the vedo seems to be not compatible with TK.

**Comment by marcomusy** [comment]
`vedo` is built on top of vtk and numpy alone with no other dependencies
