### ISSUE TITLE
Cut a mesh by the distance from its boundaries

### ISSUE THREAD

**Issue by nikhilpatil99** [marcomusy/vedo#351]
Respected @marcomusy ,
I have a  of 3D mesh file which look uniform plane curve. I want to be cut the 3D mesh by 0.09cm by all the boundary points using python. I am very excited to work with this feature in your library. 
I have attached the link to the ".ply" file. I would like to know how to work with vedo to get such a kind of cutting mesh using vedo. 

[Ply file link](https://drive.google.com/file/d/1BwXaB8pYTVOPXeCChL2gK7acjcEVKFpQ/view?usp=sharing)
Any leads will be appreciated.
Thanks in advance

**Comment by marcomusy** [comment]
this is a possible solution:
```python
from vedo import *

msh = Mesh("cut_mesh.ply").clean()

bnd = msh.boundaries(nonManifoldEdges=False, featureAngle=180)

# this creates the blue "tube" which is then used to cut the mesh
modl = bnd.implicitModeller(distance=0.0005, res=(150,50,150), outer=True, bounds=())
msh.cutWithMesh(modl)

show(msh, bnd, modl, axes=dict(zxGrid=True, xyGrid=False))
```
<img width="432" alt="Screenshot 2021-03-26 at 01 48 34" src="https://user-images.githubusercontent.com/32848391/112561386-65c6a600-8dd5-11eb-91a3-98d9902298c8.png">

**Comment by nikhilpatil99** [comment]
> this is a possible solution:
> 
> ```python
> from vedo import *
> 
> msh = Mesh("cut_mesh.ply").clean()
> 
> bnd = msh.boundaries(nonManifoldEdges=False, featureAngle=180)
> 
> # this creates the blue "tube" which is then used to cut the mesh
> modl = bnd.implicitModeller(distance=0.0005, res=(150,50,150), outer=True, bounds=())
> msh.cutWithMesh(modl)
> 
> show(msh, bnd, modl, axes=dict(zxGrid=True, xyGrid=False))
> ```
> 
> <img alt="Screenshot 2021-03-26 at 01 48 34" width="432" src="https://user-images.githubusercontent.com/32848391/112561386-65c6a600-8dd5-11eb-91a3-98d9902298c8.png">
Great Work...! appreciate your efforts.!
Thank you such much it means me a lot for these outstanding results and solution.... appreciate your solution and vedo library .... it was more helpful for me.
