### ISSUE TITLE
AttributeError with mesh isobands

### ISSUE THREAD

**Issue by jonnymaserati** [marcomusy/vedo#352]
Hi there!

I'm getting this error when I try to use the `isobands()` mesh method:

```console
<vedo.plotter.Plotter object at 0x7f6a45f44590>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jonathancorcutt/anaconda3/envs/wellplan/lib/python3.7/site-packages/vedo/mesh.py", line 1814, in isobands
    bcf.GetOutput().GetCellData().GetScalars().SetName("IsoBands")
AttributeError: 'NoneType' object has no attribute 'SetName'
```
I'm loading in a (n, 3) array of vertices and creating a (flat surface) mesh with:
```python
mesh = vedo.delaunay2D(vertices)
```
There's 233,358 vertices and when plotted with:
```python
vedo.show(mesh)
```
They look like this:
![image](https://user-images.githubusercontent.com/41046859/112498630-017cf580-8d87-11eb-83c6-8293e2f044de.png)

But I'd like to shade this surface like this:
![image](https://user-images.githubusercontent.com/41046859/112498817-2bceb300-8d87-11eb-8051-08d77b19feca.png)

It'd also be nice to make the surface a bit smoother.

Any suggeestions? :-)

Jonny

**Comment by marcomusy** [comment]
uhm.. the fact that ` bcf.GetOutput().GetCellData().GetScalars()` is `None` maybe means that you didn't assign a cell-scalar field to the mesh?

**Comment by jonnymaserati** [comment]
Gotcha! I was assuming that it was defaulting to using the z data but I can see why that might not be desirable.

It's not documented in the examples how to assign the scalar since the imported shape already has that data assigned. Reading through the mesh documentation, I can get this working with the following:

```python
mesh.addElevationScalars(lowPoint=(0,0,mesh.GetZRange()[0]), highPoint=(0,0,mesh.GetZRange()[1]))
iso = mesh.isobands()
iso.show()
```
Incidentally, in the [documentation](https://vedo.embl.es/autodocs/content/vedo/mesh.html#vedo.mesh.Mesh.addElevationScalars) there's a mismatch in the parameter names. Anyway, the above code generates this...

![image](https://user-images.githubusercontent.com/41046859/112598239-9545d480-8e0e-11eb-9a07-41bf451d17a3.png)

Which is what I was looking for... thank you!

**Comment by marcomusy** [comment]
looks nice!
If you want to make it look smoother you can play with `mesh.computeNormals().phong().lighting("glossy")`
(for other presets try `vedo -r lightings`)

thanks for reporting the issue in the docs!

**Comment by marcomusy** [comment]
just realized i forgot to answer this

> It's not documented in the examples how to assign the scalar since the imported shape already has that data assigned.

you can assign any number of arrays to points or cells of a mesh with
`mymesh.addPointArray(arr, "arrname")`
and/or
`mymesh.addCellArray(arr, "arrname")`

Also 
`mymesh.cmap("jet", arr, on="points", arrayName="arrname")`
will automatically add it when setting the colormap.

**Comment by jonnymaserati** [comment]
Great, thank you!

I keep learning more and more stuff I can do with this excellent library!
