### ISSUE TITLE
Need restart the spyder after run vedo each time?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#353]
Need restart the spyder after run vedo each time?

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.4.0 -- An enhanced Interactive Python.

**Comment by marcomusy** [comment]
strange.. can you try with
```
from vedo import embedWindow
embedWindow(False)
```

**Comment by timeanddoctor** [comment]
![image](https://user-images.githubusercontent.com/28825816/112739232-1df67900-8fa5-11eb-8b6b-ec90f6b2d654.png)

**Comment by timeanddoctor** [comment]
the picture showed that still error


the dd.py code:
`from vedo import dataurl, Volume
from vedo.applications import IsosurfaceBrowser
from vedo import embedWindow
embedWindow(False)
vol = Volume('head.vti')

plt = IsosurfaceBrowser(vol, c='gold') # Plotter instance

plt.show(axes=7, bg2='lb')`

**Comment by timeanddoctor** [comment]
plt = IsosurfaceBrowser(vol, c='gold').close() # Plotter instance
I changed with this and solved the problem.
But another problem. I tend to run the dd.py with a tk button. and the close seems to be block the tk Gui.

![image](https://user-images.githubusercontent.com/28825816/112739392-aaee0200-8fa6-11eb-8796-387404dcd7a4.png)

**Comment by timeanddoctor** [comment]
def button_command():
      print('run vedo')
      import dd
      dd.main()

**Comment by timeanddoctor** [comment]
the close() will block TK but not the vedo.show?
Maybe I should changeback some varible after close() to let my tk always running.
Which code should I change ?

**Comment by marcomusy** [comment]
Sorry this sounds very confusing to me..
`plt = IsosurfaceBrowser(vol, c='gold').close() # Plotter instance`
is incorrect: you should not close the Plotter before using it..

I made a few tests on my spyder console and couldn't reproduce the issue.
check examples in `examples/other` , but it's about qt - i'm not familiar with tk
