### ISSUE TITLE
citing vedo

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#354]
Hi @marcomusy ,

I am trying to set up the bib entry for citing vedo in the following way,

```
@article{macro2021,
  author = {M. Musy et al.},
  title = {vedo, a python module for scientific analysis and visualization of 3D objects and point clouds},
  year = {2021},
  publisher= {Zenodo},
  doi = {10.5281/zenodo.4287635},
}
```

Is this ok?

**Comment by marcomusy** [comment]
Looks good! Thanks for using `vedo` and for all the feedback which helped on improving the package.
