### ISSUE TITLE
Embedding node/edge features for vtk files

### ISSUE THREAD

**Issue by julim712** [marcomusy/vedo#355]
Hello everyone,

I have been using vedo to convert my csv-based graph files to vtk-files that I can display in Paraview.
Reading the documentation, I have not found a method that allows me to embedd features as a node or edge property.

Did I miss some important part of the documentation or is this not supported (yet?).
If I did miss it, could some share a link?

Best regards
Julian

**Comment by marcomusy** [comment]
Hello, you can use something like `mygraph.addPointArray(myarr1)` for nodes, and  `mygraph.addCellArray(myarr2)` for edges.
