### ISSUE TITLE
'vedo' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by arisliang** [marcomusy/vedo#359]
I installed vedo successfully:
>In [1]: import vedo

>In [2]: vedo.__version__
Out[2]: '2021.0.2'

But not able to run `vedo -r covid19` in terminal as in README described.

OS: windows 10, python 3.8

**Comment by marcomusy** [comment]
That's the windows nightmare of the PATH environment..
you need to know where the installation goes in your system and set the path accordingly..
You may try to follow this recipe: https://github.com/marcomusy/pianoplayer/issues/27

**Comment by arisliang** [comment]
any particular file I should the path contain?

**Comment by marcomusy** [comment]
it should point to the `vedo/bin/vedo` executable
