### ISSUE TITLE
How to fill the bottom gap with mesh using vedo library..?

### ISSUE THREAD

**Issue by emmamuprhy** [marcomusy/vedo#362]
Respected @marcomusy,
It was great to work with vedo I found the expected output and desirable results for meshing by using the vedo method ...
Thank you so much for the awesome library...
Just I want one help i.e fill the gap if is it possible to fill with the mesh by using vedo meshing.
I have attached the ply file and image (the gap in the mesh which I want to fill (marked with the red color))
Any leads will be appreciated.
Thanks in advance
[img_link](https://drive.google.com/file/d/1F2TK0wpdtu-NmSh1M9480C5l4wzKZ613/view?usp=sharing)
[ply file](https://drive.google.com/file/d/1TT36RpKKJj6S8GQsFfbBUyD-7dHB1Hm0/view?usp=sharing)

**Comment by marcomusy** [comment]
Thanks for using `vedo`.
Unfortunately I cannot see any easy solution to this as the problem itself is not well defined (how is the line drawn _exactly_).
I would try to add more points using points near the edges of the shape

**Comment by emmamuprhy** [comment]
> Thanks for using `vedo`.
> Unfortunately I cannot see any easy solution to this as the problem itself is not well defined (how is the line drawn _exactly_).
> I would try to add more points using points near the edges of the shape


The line drawn using paint for your understanding the exact which gap I want to fill using the meshing....can please provide any solution to add more points using near edges or meshing in that red marked part which is drawn

**Comment by marcomusy** [comment]
I understand that you you have drawn the line manually on the imaga... my question was how would you define this line in world-coordinate system.

One possibility you can explore is to create a ribbon-like  strip by using the lower boundary line  and projecting it on the zx plane. To to it you can use `Ribbon()` https://vedo.embl.es/autodocs/content/vedo/shapes.html#ribbon
and then `merge()` with the original mesh.

**Comment by emmamuprhy** [comment]
> I understand that you you have drawn the line manually on the image... my question was how would you define this line in world-coordinate system.
> 
> One possibility you can explore is to create a ribbon-like strip by using the lower boundary line and projecting it on the zx plane. To to it you can use `Ribbon()` https://vedo.embl.es/autodocs/content/vedo/shapes.html#ribbon
> and then `merge()` with the original mesh.

Thanks for the reply @marcomusy ....but just can you please me help out to create the ribbon strip using the lower boundary line ...bcoz I do not have much idea about the ribbon in vedo mesh...
can you give example by doing it .....
Any leads will be appreciated...
Thanks in advance....

**Comment by marcomusy** [comment]
These are two examples from which you can start:
`examples/basic/ribbon.py`
`examples/advanced/contours2mesh.py`

**Comment by emmamuprhy** [comment]
> These are two examples from which you can start:
> `examples/basic/ribbon.py`
> `examples/advanced/contours2mesh.py`

Yup thanks but I quite it is not getting to me...can you please show me how to draw a lower boundary area...using ribbon strip and merge then....

**Comment by emmamuprhy** [comment]
Is there is any possible solution....?
Thanks in advance...

**Comment by marcomusy** [comment]
You need to make a honest attempt at solving the problem before asking for help.
You need to define 2 lines: one is the lower boundary of the mesh (use e.g. `mesh.boundary()` and `cutWithPlane()`)
the other is some projection of this line onto the zx plane.
Once you have these 2 lines you make the Ribbon mesh and `merge()` with the original.
NB: I dont know at all if this will work .. you need to try  it out.

**Comment by emmamuprhy** [comment]
> You need to make a honest attempt at solving the problem before asking for help.
> You need to define 2 lines: one is the lower boundary of the mesh (use e.g. `mesh.boundary()` and `cutWithPlane()`)
> the other is some projection of this line onto the zx plane.
> Once you have these 2 lines you make the Ribbon mesh and `merge()` with the original.
> NB: I dont know at all if this will work .. you need to try it out.

Thanks for the help @marcomusy  thanks its means a lot
