### ISSUE TITLE
Can I cut with the line?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#363]
Can I cut the top(inner) with the line?

**Comment by timeanddoctor** [comment]
pic:
![graycode_394](https://user-images.githubusercontent.com/28825816/114271041-15408100-9a42-11eb-933e-420b4d66d6b6.jpg)

**Comment by marcomusy** [comment]
Yes:

`vedo --edit data/teapot.vtk`

![Screenshot from 2021-04-10 21-55-48](https://user-images.githubusercontent.com/32848391/114282987-9e0deb80-9a47-11eb-8ec1-7cfd72554d11.png)
or check out
`examples/basic/cutFreeHand.py`

**Comment by timeanddoctor** [comment]
Thanks
