### ISSUE TITLE
Retrieve point colors

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#364]
Hi @marcomusy,            

I color the values of nodes in my network using the following.

`pts1 = pts.clone().pointSize(5).cmap('bwr', values)
`

I'd like to know how to get the color assigned to each point  in the above (I want to retrieve the color from here and assign to sphere)

`sph= [Sphere(r=sph_r[n]).color(sph_c[n]).pos(pos[n]) for n in nodes]`

Can I access the color of each point in the following way?

````
  sph_c = []
  for a in pts1.unpack():
        sph_c.append(a.color)

**Comment by DeepaMahm** [comment]
@marcomusy , I would also like to know how to assign scalarbar while using `Sphere`
```
sph= [Sphere(r=sph_r[n]).color(sph_c[n]).pos(pos[n]) for n in nodes]
sph.addScalarBar3D()
```

doesn't work. So I did `vplt.show(sph, pts1.scalarbar)`

**Comment by marcomusy** [comment]
> Hi @marcomusy,
> 
> I color the values of nodes in my network using the following.
> 
> `pts1 = pts.clone().pointSize(5).cmap('bwr', values) `
> 
> I'd like to know how to get the color assigned to each point in the above (I want to retrieve the color from here and assign to sphere)
> 
> `sph= [Sphere(r=sph_r[n]).color(sph_c[n]).pos(pos[n]) for n in nodes]`
> 
use `colorMap()`
https://github.com/marcomusy/vedo/blob/f54c820ee3a53d40b33fe0728c2330ef17d9b7b2/vedo/colors.py#L587


> Can I access the color of each point in the following way?
> 
> ```
>   sph_c = []
>   for a in pts1.unpack():
>         sph_c.append(a.color)
> ```

No!

**Comment by marcomusy** [comment]
> @marcomusy , I would also like to know how to assign scalarbar while using `Sphere`
> 
> ```
> sph= [Sphere(r=sph_r[n]).color(sph_c[n]).pos(pos[n]) for n in nodes]
> sph.addScalarBar3D()
> ```
> doesn't work. 

obviously it doesn't work.. `sph` is a simple python list!!

> So I did `vplt.show(sph, pts1.scalarbar)`. Is there an alternate way?

this looks ok to me
