### ISSUE TITLE
Fill the mesh in gaps

### ISSUE THREAD

**Issue by emmamuprhy** [marcomusy/vedo#366]
Respected @marcomusy 

I tried to fill the gap with two methods:-

1)  I tried with delaunay2D but the extra middle mesh is getting added ..can you please help me to delete that mesh or restrict that extra mesh not to be added
2) As you told using the cutwithplane() but it is not getting the desired output ...please can you help me out..1) method (delaunay2D)
```
from vedo import *
pts = Points("demo.ply").clean(0.009).pointSize(3)
mesh1 = delaunay2D(pts, mode='fit',tol=0.0009).extractLargestRegion().clean()
mesh1 = geometry(mesh1.inputdata()).computeNormals()mesh1.subdivide(1).smoothLaplacian().fillHoles().computeNormals(1)
show(pts, mesh1, N=2, axes=1)

```
The gap is getting filled but the extra mesh is also added in the middle part. Can you please help me to remove that middle extra mesh?
![ss](https://user-images.githubusercontent.com/55427143/114293933-1e6c3500-9ab8-11eb-9639-a15ad2dda695.png)

2) Cut with plane()
```
from vedo import *
msh = Mesh("demo.ply").clean()
bnd = msh.boundaries(boundaryEdges=True,nonManifoldEdges=False,featureAngle=65)msh.cutWithPlane(origin = (1,0,1),normal=(1,0,1),returnCut=False)show(msh, bnd, axes=dict(zxGrid=True, xyGrid=False))
```
The cut is not getting the lower boundary cut.....

Any leads will be appreciated
Thanks in advance..!

![Screenshot from 2021-04-11 10-56-05](https://user-images.githubusercontent.com/55427143/114293937-262bd980-9ab8-11eb-8d60-29342dfb4b90.png)

**Comment by emmamuprhy** [comment]
Respected @marcomusy can you please help me out for this problem,,,,?
it will be great help

**Comment by marcomusy** [comment]
if the ribbon trick doesn't work you can try the following:
1. cut the boundary line with `cutWithPlane()`
2. `extrude()` this line to create a surface (you might need to rotate it because extrude only works along `z` axis)
3. `merge()` this with the original mesh.
4. use `clean()` to remove duplicate points.

**Comment by emmamuprhy** [comment]
> if the ribbon trick doesn't work you can try the following:
> 
> 1. cut the boundary line with `cutWithPlane()`
> 2. `extrude()` this line to create a surface (you might need to rotate it because extrude only works along `z` axis)
> 3. `merge()` this with the original mesh.
> 4. use `clean()` to remove duplicate points.

Thanks I will try with it
