### ISSUE TITLE
How to get the camera angle after rotate like IS/LR?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#367]
How to get the camera angle after rotate like IS/LR?

**Comment by timeanddoctor** [comment]
![image](https://user-images.githubusercontent.com/28825816/114296261-e0cdd300-9adc-11eb-9c3c-2c2a37ad1332.png)

**Comment by marcomusy** [comment]
You should be able to access the camera info with e.g.
```python
from vedo import *
plt = Plotter()
plt.show(Cube(), axes=1, interactive=False)
plt.camera.GetPosition()
plt.camera.GetFocalPoint()
plt.camera.GetViewUp()
plt.camera.GetDistance()
interactive()
```

**Comment by timeanddoctor** [comment]
ok, Thanks. It really helpfull.
and another problem is plotter title, the default is vedo but my window is visualization toolkit....
I try to change the plotter(title='dd').
nothing happen.(win10)
![image](https://user-images.githubusercontent.com/28825816/114503043-46e26380-9c5f-11eb-8fb5-70c21a1234f1.png)

**Comment by marcomusy** [comment]
Yes thanks for drawing my attention to it, i need to fix that..

**Comment by timeanddoctor** [comment]
Thanks
