### ISSUE TITLE
vtkUnstructuredGrid not directly supported

### ISSUE THREAD

**Issue by niveshd** [marcomusy/vedo#368]
vedo.mesh.Mesh class doesn't accept 'vtk.vtkUnstructuredGrid' as input, contrary to the documentation.

```
class Mesh(Points):
    """
    Build an instance of object ``Mesh`` derived from ``PointCloud``.

    Input can be ``vtkPolyData``, ``vtkActor``, or a python list of [vertices, faces].

    If input is any of ``vtkUnstructuredGrid``, ``vtkStructuredGrid`` or ``vtkRectilinearGrid``
    the geometry is extracted.
    In this case the original VTK data structures can be accessed with: ``mesh.inputdata()``.
```

From the source code, the case doesn't seem to be considered. Is this a bug or the documentation needs to be updated?
```
elif isinstance(inputobj, (vtk.vtkStructuredGrid, vtk.vtkRectilinearGrid)):
    if vedo.settings.visibleGridEdges:
        gf = vtk.vtkExtractEdges()
        gf.SetInputData(inputobj)
    else:
        gf = vtk.vtkGeometryFilter()
        gf.SetInputData(inputobj)
    gf.Update()
    self._polydata = gf.GetOutput()
```

Please let me know if you need more info. I just started using vedo (version 2021.0.2) and am rather new to how it works.

If you have any advice on the recommended way to use unstructured grid, please let me know. I couldn't find anything directly in the examples, other than a reference to Fenics which I don't want to use just for visualization. I found that vedo seamlessly support visualization on jupyter and normal python scripts. So I would be glad to somehow make this work!

**Comment by marcomusy** [comment]
Hi - thanks for spotting that... indeed the documentation is incorrect.
You can use the class `UGrid` for unstructured grids.
Find examples in the `examples/volumetric/` area
Note that this class is still a bit experimental..

**Comment by niveshd** [comment]
Thanks for the response. UGrid did work. I guess my requirements for the Jupyter visualization are rather modest! I am happy that it works without me fiddling the code.
