### ISSUE TITLE
Plotter object has no attribute 'addSplineTool'

### ISSUE THREAD

**Issue by sonumathur** [marcomusy/vedo#369]
On the running of code from spline_tool.py in examples

>>> from vedo import Circle, show
>>> pts = Circle(res=8).extrude(zshift=0.5).pointSize(4)
>>> plt = show(pts, __doc__, interactive=False, axes=1)
>>> sptool = plt.addSplineTool(pts, closed=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Plotter' object has no attribute 'addSplineTool'

Why this error...

**Comment by marcomusy** [comment]
You haven't installed the dev version:
`pip install -U git+https://github.com/marcomusy/vedo.git`
