### ISSUE TITLE
Can I get the inner "R" of tube?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#370]
![image](https://user-images.githubusercontent.com/28825816/114525393-a7ca6580-9c78-11eb-9763-7a5cd13686c1.png)

Firstly, I can get the centerline by vedo. (success)
Secondly, I try to calculate the Radius of inner wall and then simulate with a serial of spheres.

**Comment by marcomusy** [comment]
Hi, sorry I don't understand the question.

**Comment by timeanddoctor** [comment]
> Hi, sorry I don't understand the question.

![image](https://user-images.githubusercontent.com/28825816/114656865-6c37a600-9d21-11eb-9252-188225803a53.png)

**Comment by timeanddoctor** [comment]
This is my second question.
I need calculate the circle and the vector.

**Comment by marcomusy** [comment]
you can look at `examples/basic/surfIntersect.py` using a Plane or gridded plane `Grid` objects
