### ISSUE TITLE
vp+= does not work

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#372]
Hi, I am trying to plot different pointclouds and planes and etc in one figure and for that I am trying vp+= the new data 
unfortunately this is not working for me

in addition I have another problem, if I want to use subplots for example #vp = Plotter(N=3, axes=0) this is Always not responding! I have no idea what to do to solve this issue

#vp.show(p1,p2,p3, pts1, pts2, pts3,intersection,l1,l2,l3,l4,l5,l6,l7,l8, __doc__,at=0) 
#vp.show(p1,p2, pts1, pts2, intersection,l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13, __doc__, at=1)
#vp.show(l1,l2,l3,l4,l5,l6,l7,l8,l9,l10,l11,l12,l13,l14,l15, __doc__, at=2)

I would appreciate any guideline in that regard
Best regards
Sahar

**Comment by marcomusy** [comment]
Hi you can have a look at `examples/simulations/aspring.py`
also you should be able to reproduce this
```python
from vedo import *

plt = Plotter(N=2)

plt.add(Sphere(), at=0, render=False) #no need to render
plt.add(Cube(), at=1, render=False)
plt.add(Axes(Cube()), at=1) #renders here

interactive()
```

(but i think it's in general easier to create your objects in andvance and then show them at the end...)
E.g.:
```python
from vedo import *

plt = Plotter(N=2, axes=1, sharecam=False)

s = Sphere()
c = Cube()

plt.show(s, at=0) 
plt.show(c, at=1)

interactive()
```
