### ISSUE TITLE
Can i fit a polygon to my pointdata?

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#375]
I have a set of points projected in 2D and I would like to fit a polygon in a way that I have the shape of my data at the end. Is that possible to do in vedo?
Thanks

**Comment by marcomusy** [comment]
yes:
https://github.com/marcomusy/vedo/blob/master/examples/basic/delaunay2d.py
(you can play with `delaunay2D(alpha=...)`)
https://github.com/marcomusy/vedo/blob/master/examples/advanced/line2mesh_tri.py
https://github.com/marcomusy/vedo/blob/master/examples/advanced/line2mesh_quads.py

you can also use 
https://github.com/marcomusy/vedo/blob/master/examples/advanced/recosurface.py
and
https://github.com/marcomusy/vedo/blob/master/examples/basic/boundaries.py
to detect the boundary domain of the cloud
