### ISSUE TITLE
Can I get the callback fuction in vtk iren?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#377]
I have a vtk app, and I tend to use the vedo in it.
Can I get the callback fuction from vedo in vtk?

cid=plt.addCallback('KeyPress', onLeftClick)

iren = vtk.vtkRenderWindowInteractor()
iren.AddObserver(cid)

But this seems error...
Thanks

**Comment by marcomusy** [comment]
the `plt` variable is of class `Plotter` and it already has a `vtkRenderWindowInteractor` (as `plt.interactor`) , moreover the callback is already added to it.

**Comment by timeanddoctor** [comment]
Thanks.

For example, how can I get the observer(vtkObserver (0000021811E26D80)) from a interactor.

print(interactor)->

vtkWin32RenderWindowInteractor (0000021811DBF070)
  Debug: Off
  Modified Time: 376531
  Reference Count: 2
  Registered Events: 
    Registered Observers:
      vtkObserver (0000021811E26D80)
        Event: 12
        EventName: LeftButtonPressEvent
        Command: 0000021812223760
        Priority: 0
        Tag: 90
      vtkObserver (0000021811E27590)
        Event: 16
        EventName: RightButtonPressEvent
        Command: 0000021812223B60
        Priority: 0
        Tag: 91
      vtkObserver (0000021811E27620)
        Event: 14
        EventName: MiddleButtonPressEvent
        Command: 0000021812223A20
        Priority: 0
        Tag: 92

**Comment by marcomusy** [comment]
you should be able to retrieve it from the `cid` number

**Comment by timeanddoctor** [comment]
from vedo import Plotter
plt=Plotter()
a=plt.interactor
def onLeftClick(evn):
    print('hello!')

cid=plt.addCallback('RightButtonPress', onLeftClick)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

#iren.Enable()
a=plt.interactor.GetCommand(cid)
a.Register(iren)

iren.Start()

But this seems not correct.

**Comment by timeanddoctor** [comment]
> you should be able to retrieve it from the `cid` number
Maybe I should rewrite the observer function in Vtk mainloop?

**Comment by marcomusy** [comment]
This seems to do what it is supposed to do..:
```python
from vedo import Plotter, Sphere, interactive


def onLeftClick(evn):
    print('hello!', evn)

plt = Plotter()

cid = plt.addCallback('RightButtonPress', onLeftClick)
print(cid)

plt.show(Sphere(), axes=1, interactive=False)

command = plt.interactor.GetCommand(cid) # vtkCommand
print([command])

interactive() # start interaction
```

**Comment by timeanddoctor** [comment]
> This seems to do what it is supposed to do..:
> 
> ```python
> from vedo import Plotter, Sphere, interactive
> 
> 
> def onLeftClick(evn):
>     print('hello!', evn)
> 
> plt = Plotter()
> 
> cid = plt.addCallback('RightButtonPress', onLeftClick)
> print(cid)
> 
> plt.show(Sphere(), axes=1, interactive=False)
> 
> command = plt.interactor.GetCommand(cid) # vtkCommand
> print([command])
> 
> interactive() # start interaction
> ```

from vedo import Plotter
plt=Plotter()
a=plt.interactor
def onLeftClick(evn):
print('hello!')

cid=plt.addCallback('RightButtonPress', onLeftClick)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

#iren.Enable()
a=plt.interactor.GetCommand(cid)
a.Register(iren)

iren.Start()


After I get the vtkCommand, I try to use it in the vtk interactor, but this seems not be easy.
I found the b.Excecut(iren,cid,None) and the b.Register(iren) and iren.AddObserver(cid,b), and tried then one by one. never success finnally.

**Comment by timeanddoctor** [comment]
sorry, I am not good at vtk as well.

**Comment by marcomusy** [comment]
The above example is incomplete so I cannot see what are you aiming at..
Also, you do **not** need to create instances of `vtkRenderWindowInteractor` because `Plotter` already creates it and it's exposed as `plt.interactor` (or at least I cannot see why you should need a new one..).

**Comment by timeanddoctor** [comment]
Thank you very much, Professor marcomusy
I had write some code many yeas ago with vtk, but I need and
