### ISSUE TITLE
fitline using for loop

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#378]
Hii, thanks for your very interesting software.
I have a question which will help me alot if you Could response. 
I have several points and I want to fit a line between each of the two points 
however, as I know the indices of the points I want to write a for loop by which I can call the Line function inside the loop and save the information of all these lines in a list/tuple/ or array and then 
trying to plot the lines by calling the lines with indices in vp.show() 
is this possible using vedo? 
I appreciate any help in this regards from your side
thank you

**Comment by marcomusy** [comment]
I dont understand very well the question..
1. you dont need to fit a line btw 2 points :)
2. `Line()` supports multiple points - so it can hold and render a set of contiguous segments (polyline).
3. you can also use `Lines()` for non-connected segments

Check out examples:
```
examples/pyplot/fitPolynomial1.py
examples/pyplot/koch_fractal.py
examples/simulations/volterra.py
examples/advanced/fitspheres2.py
```

**Comment by sahar-github** [comment]
Hi, Thank you for your response
I think its better I explain you what exactly I am doing
I have a point cloud file from an individual building
What I am trying to do is to develop the LOD2 of the 3d reconstructed
building model

The methodology I am using is to extract the footprint of the building, and
planes of the roof and foot and then
I am trying to extract boundary points and then I want to connect all the
extracted points together in a way a 3d shape of the building is created
afterwards
I finally want to save this model as a obj or mesh or las file

Do you have any suggestion to do this steps/ workflow in an easier approach
in vedo? Or any specific suggestion for each of tge steps?
Like drawing the connection lines, etc?


I will send you a link to some examples showing what I am doing in some
minutes

Thank you

**Comment by sahar-github** [comment]
Here is the link to some screenshots of my data and what I am doing.
thanks

Attached is a link to the screenshots of what I am doing currently
Get your files
<https://wetransfer.com/downloads/300d8218baa00d7a3cae983c9f4a42c920210420104035/7584139c207a14a9e63ee0a9b18b6e6720210420104058/a10652?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email>

Download link
https://wetransfer.com/downloads/300d8218baa00d7a3cae983c9f4a42c920210420104035/7584139c207a14a9e63ee0a9b18b6e6720210420104058/a10652

**Comment by marcomusy** [comment]
I understand that LOD2 must be like the one in the scheme:
![image](https://user-images.githubusercontent.com/32848391/115390584-b10a8380-a1de-11eb-9c6b-469a0716b8cd.png)

i'm not expert at all of any methodology in the field , the only thing that comes up to my mind is to fit planes to the point clouds and then find intersections of such planes. If you already have these points or lines you can join them and save the result in any of the supported formats.
If the points you have are not ordered in space but still form a line, you may fit a line through them, then project the points on this line in order to find the ordering.

**Comment by sahar-github** [comment]
Yes exactly
But if I fit plane on the entire pointcloud of the buildings
The planes of the walls and roofs are not actually detected

What will happen in vedo is, i will have as a result of fitplane, a plane
in the center of the gravity of the point cloud
Not on the real planes of the roofs and walls

**Comment by marcomusy** [comment]
> What will happen in vedo is, i will have as a result of fitplane, a plane in the center of the gravity of the point cloud Not on the real planes of the roofs and walls

this is totally expected: you need to find a way to detect multiple planes from a point cloud - you cannot just fit the entire thing to a single plane!
what you're probably after is something like a tensorflow model or pattern recognition.
