### ISSUE TITLE
Can I create a forked tube?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#383]
Can I create a forked tube from this points automatically.

**Comment by timeanddoctor** [comment]
![无标题](https://user-images.githubusercontent.com/28825816/116728462-88715d80-aa18-11eb-883f-02e8771b28ae.png)

**Comment by marcomusy** [comment]
yes , you can try **something** similar using `implicitModeller`:
```python
from vedo import *
import numpy as np

N = 3  # nr. of iterations

# build some initial cloud of noisy points along a line
pts = [ (sin(6*x), cos(2*x)*x, cos(9*x)) for x in np.arange(0,2, .001)]

pts += np.random.randn(len(pts), 3) /40  # add noise

pts = Points(pts, r=5)

show(pts, "noisy cloud", at=0, N=N+1, axes=1)

for i in range(1, N):
    pts = pts.clone().smoothMLS1D(f=0.4).color(i)
    if i == N-1:
        # at the last iteration make sure points
        # are separated by tol (in % of bbox)
        pts.clean(tol=0.01)

    show(pts, f"Iteration {i}, #points: {pts.N()}", at=i)

mdl = Mesh(pts).implicitModeller(distance=0.15,
                                 bounds=[-1.2,+1.2, -2,+1, -1.2,+1.2],
                                 res=(50,50,50),
)
show(mdl, at=N, interactive=1)
```
![Screenshot from 2021-05-01 00-47-14](https://user-images.githubusercontent.com/32848391/116761055-e735d780-aa16-11eb-9cf5-f023503bbe73.png)

**Comment by timeanddoctor** [comment]
[pts.zip](https://github.com/marcomusy/vedo/files/6408707/pts.zip)

**Comment by timeanddoctor** [comment]
I get the pts after 'smoothMLS1D(f=0.4)'
but the result is nothing after run the implicitModeller fun.

**Comment by timeanddoctor** [comment]
maybe the forked line should be made from two tubes.

**Comment by timeanddoctor** [comment]
```
from vedo import *
pts=load('pts.ply')
pc=pts.clone()
for i in range(9):
    pts = pts.clone().smoothMLS1D(f=0.4).color('r').pointSize(5)
mdl = Mesh(pts).implicitModeller(distance=0.15,
                                 bounds=[-1.2,+1.2, -2,+1, -1.2,+1.2],
                                 res=(50,50,50),)  
plt=Plotter()
plt.show(mdl,pts,pc)
```

**Comment by timeanddoctor** [comment]
Can we use vedo to divide these points into two lines

**Comment by timeanddoctor** [comment]
> yes , you can try **something** similar using `implicitModeller`:
> 
> ```python
> from vedo import *
> import numpy as np
> 
> N = 3  # nr. of iterations
> 
> # build some initial cloud of noisy points along a line
> pts = [ (sin(6*x), cos(2*x)*x, cos(9*x)) for x in np.arange(0,2, .001)]
> 
> pts += np.random.randn(len(pts), 3) /40  # add noise
> 
> pts = Points(pts, r=5)
> 
> show(pts, "noisy cloud", at=0, N=N+1, axes=1)
> 
> for i in range(1, N):
>     pts = pts.clone().smoothMLS1D(f=0.4).color(i)
>     if i == N-1:
>         # at the last iteration make sure points
>         # are separated by tol (in % of bbox)
>         pts.clean(tol=0.01)
> 
>     show(pts, f"Iteration {i}, #points: {pts.N()}", at=i)
> 
> mdl = Mesh(pts).implicitModeller(distance=0.15,
>                                  bounds=[-1.2,+1.2, -2,+1, -1.2,+1.2],
>                                  res=(50,50,50),
> )
> show(mdl, at=N, interactive=1)
> ```
> 
> ![Screenshot from 2021-05-01 00-47-14](https://user-images.githubusercontent.com/32848391/116761055-e735d780-aa16-11eb-9cf5-f023503bbe73.png)

**Comment by marcomusy** [comment]
it's because the bounds are **completely** wrong!
```python
from vedo import *

pts = load('data/pts.ply')
pts.clean(0.002).ps(5).c('red5')
r=80

mdl = pts.implicitModeller(distance=0.8,
                           bounds=[-10,18, 17,40, -25,8],
                           res=(r,r,r),
)
mdl.subdivide().smoothLaplacian() # make a better mesh
mdl.lw(0.1).alpha(0.2)
print(mdl.bounds())

show(mdl, pts, axes=1)
```
![Screenshot from 2021-05-01 12-54-44](https://user-images.githubusercontent.com/32848391/116780371-a2448c00-aa7c-11eb-976c-f9ed22e30e93.png)

Please post issues in a more organized and clear way (use the edit option to correct an initial post if needed).
