### ISSUE TITLE
Append multiple vedo objects into an array, and save all into one file

### ISSUE THREAD

**Issue by eivindtn** [marcomusy/vedo#388]
Hi @marcomusy! A question regarding exporting mesh, splines, points, pictures, plots, for later visualization through `show()`. Is it possible to append multiple vedo objects into an array, and save all into one file. Instead of `write()` and `load()` all objects with a supported format?
I tried to `write()` multiple objects with the format `.npz`, but I didnt suceed when trying to `load()`. 

I did look into this example regarding exporting scenes,[examples/other/export_numpy.py](https://github.com/marcomusy/vedo/blob/e594d67184068bc58ded149c450403e4a58da2a6/examples/other/export_numpy.py)
An error did occur when trying to save a image through 'Picture(image)' with a Mesh in a scene with the following line:

``` python
p= show(mesh, Picture(image), axes=1)
exportWindow('scene.npz')
p.close()
```
Error:
`C:\Users\eivin\anaconda3\envs\project\lib\site-packages\vedo\utils.py:342: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  faces = np.array(faces)`

Also, when exporting only a mesh the example did work, but the colors in the pointcloud scene was not the same before and after exporting.

I did read this issue #357 
It is somehow possible to merge multiple objects and then split it afterwards? 

In advance, Thank you @marcomusy!

**Comment by marcomusy** [comment]
Hi - You're right , I was lazy and did not implement dumping of a `Picture` into the npz scene... I'll also try to fix the numpy warning message..
For the moment you may do something like:
```python
from vedo import *
pic = Picture("https://api.time.com/wp-content/uploads/2019/03/kitten-report.jpg")
cube= Cube(side=500)
show(cube, pic, axes=1).export("scene.npz").close()

# recreate the scene
plt = load("scene.npz")
plt += pic
plt.show().close()
````
<img width="320" alt="Screenshot 2021-05-05 at 12 55 00" src="https://user-images.githubusercontent.com/32848391/117131313-9240eb00-ada1-11eb-99f5-3a1bf377c288.png">

**Comment by eivindtn** [comment]
Great @marcomusy ! When should I use load instead of importwindow?
I also would like to export a scene with multiple renders with `N= a number`.
I tried with your exampe above, but doesnt seem to work:
``` python
from vedo import *
pic = Picture("https://api.time.com/wp-content/uploads/2019/03/kitten-report.jpg")
cube= Cube(side=500)
show([[cube, pic],[cube, pic]],N=2 ,axes=1).export("scene.npz").close()

plt = load("scene.npz")
plt.show().close() 
```
![image](https://user-images.githubusercontent.com/70319228/117134439-e221b100-ada5-11eb-9e06-27234062d349.png)

**Comment by marcomusy** [comment]
you need to upgrade vedo:
`pip install vedo -U`

Even so, multiple renderers is also not supported yet.
I was very enthusiastic at first about the possibility to export entire scenes.. but found out that there was not so much interest.. so I limited my efforts to one renderer only :), also the whole thing is not very well tested so you may encounter bugs or missing stuff (like the Picture).

**Comment by eivindtn** [comment]
I understand that :) Appreciate the fast response! Is there a way to export two single renders(two files) and then visualize them as multiple renders after loading?

**Comment by marcomusy** [comment]
> Is there a way to export two single renders(two files) and then visualize them as multiple renders after loading?

what about this:
```python
from vedo import *

pic = Picture("https://api.time.com/wp-content/uploads/2019/03/kitten-report.jpg")
cube= Cube(side=500)
sphere= Sphere(r=250).lw(1)

show(cube,   pic, axes=1).export("scene1.npz").close()
show(sphere, pic, axes=1).export("scene2.npz").close()

######################### load back
plt1 = load("scene1.npz")
plt2 = load("scene2.npz")

plt = Plotter(N=2, axes=1)
plt.show("RENDERER 0", *plt1.actors, pic, at=0)
plt.show("RENDERER 1", *plt2.actors, pic, at=1)
plt.show(interactive=1)

plt.close()
plt2.close()
plt1.close()
```
![Screenshot from 2021-05-05 21-06-15](https://user-images.githubusercontent.com/32848391/117195652-d1912b00-ade5-11eb-9268-af63742e13fd.png)

**Comment by eivindtn** [comment]
Great @marcomusy ! Thank you! This works fine! It is nice to recreate the plots without loading all the files.
