### ISSUE TITLE
Custom histogram plotting

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#391]
Hi @marcomusy,

I am trying to follow the example from [here](https://github.com/marcomusy/vedo/blob/master/examples/pyplot/histo_gauss.py) in order to plot a similar to the following histogram graph:

![image](https://user-images.githubusercontent.com/10189018/117820125-84400e00-b26a-11eb-9d1b-eefa5a93a7da.png)

However, I am not sure whether it is possible to have the range of the bins given. I've tried the following but didn't really work:

```
import os
import numpy as np
import pandas as pd
import vedo as vd
from vedo.pyplot import histogram, plot, settings

LUX_BINS = [100, 250, 500, 750, 1000, 2000, 5000, 10000]

data = pd.read_csv("ls_room_999.csv", header=None, delimiter=',', low_memory=False).to_numpy(dtype='float')

cluster_ids_x = np.digitize(data[:,4].reshape(-1, 1), LUX_BINS)
classes, class_counts = np.unique(cluster_ids_x, return_counts=True)
points_percentage = class_counts * 100 / cluster_ids_x.size

plt = histogram(data[:, 4], title="hist", bins=LUX_BINS, density=False, c='cyan3', aspect=8 / 7)
plt.show(size=(800, 700), zoom=1.2, interactorStyle="Image").close()
```

Is it possible to have the ranges of the bins given and accordingly apply it to the hist?

Thanks.

[ls_room_999.csv](https://github.com/marcomusy/vedo/files/6459084/ls_room_999.csv)

**Comment by marcomusy** [comment]
This is what I would do:
```python

import numpy as np
import pandas as pd
from vedo import precision, Text3D
from vedo.pyplot import histogram, plot

LUX_BINS = np.array([100, 250, 500, 750, 1000, 2000, 5000, 10000])

data = pd.read_csv("ls_room_999.csv", header=None, delimiter=',', low_memory=False).to_numpy(dtype='float')

cluster_ids_x = np.digitize(data[:,4].reshape(-1, 1), LUX_BINS)
classes, class_counts = np.unique(cluster_ids_x, return_counts=True)
points_percentage = class_counts * 100 / cluster_ids_x.size

plt = histogram(  data[:, 4],
                  title="LUX histogram",
                  xtitle="intensity",
                  bins=LUX_BINS,
                  xlim=(0,2500),
                  ylim=(0,11000),
                  c='cyan3',
                  aspect=4/3,
)
frequencies = plt.freqs / plt.yscale # the "/plt.yscale" is actually a BUG and will be fixed in next release!
bincenters = (LUX_BINS[0:7] + LUX_BINS[1:8])/2
xy = np.c_[bincenters, frequencies]

plt += plot(xy, spline=True, lc='tomato', lw=4)

for i in range(5):
    txt = Text3D(precision(points_percentage[i],3)+'%', pos=(bincenters[i], frequencies[i]))
    txt.scale(350).z(10).rotateZ(25, locally=True).shift(50,150).c("blue2")
    plt += txt

plt.show(size=(800, 700), zoom=1.2).close()
```
![Screenshot from 2021-05-11 17-21-22](https://user-images.githubusercontent.com/32848391/117841529-6f20aa80-b27d-11eb-9d12-992fa91a4211.png)

Note that, from a physicist-biased point of view :) you should **not** make bins look equal when they are not!
But in any case this is not supported in vedo unless you do some manual tricks.

The `.z(10)` shifts the text in z so it overlaps the other elements. 
Also in the next release you will not need to divide by "/plt.yscale"!

**Comment by marcomusy** [comment]
Thanks!

> Only one comment, why the `plot.freqs` returns an array of size 7 instead of 8. It should be 8, shouldn't be?

uhm, it looks correct to me, if you have 8 bin edges, this corresponds to 8-1 bin centers and freqs.

**Comment by ttsesm** [comment]
Well the way you got it you are right, however the last bin edge is actually the `inf` so 10000 is the lower limit of the last bin and not the upper one (I think this has to do also how Matlab addresses the bin margins).

Anyways, I will try to play a bit the code now that I have a baseline sample and see what I can do myself and I will let you know.

**Comment by marcomusy** [comment]
Oh OK, you can then use `np.clip(data[:,4], 100, 10000)`

**Comment by ttsesm** [comment]
> Oh OK, you can then use `np.clip(data[:,4], 100, 10000)`

well this will not help much

> Note that, from a physicist-biased point of view :) you should not make bins look equal when they are not!
But in any case this is not supported in vedo unless you do some manual tricks.

Could you possibly elaborate what manual tricks would be needed, possibly apply? Also is it possible to adjust the xticks? 

Ideally as you see in the targeting histogram graph I am not caring too much being graphically correct but rather showing just the distribution in a more compact mode. Thus, I think being able to provide a fixed bin size might be useful. For example in case that I extend the `xlim` in the `histogram()` parameters then I get the following:

![image](https://user-images.githubusercontent.com/10189018/117960261-1c96cb00-b31d-11eb-868a-9989e7173460.png)

which is kind of ugly, and not really easy to read from  the reader's/reviewer's perspective.

**Comment by marcomusy** [comment]
why not plotting the sqrt(intensity) so the scale is not more linear?
```python
import numpy as np
import pandas as pd
from vedo import precision, Text3D
from vedo.pyplot import histogram, plot

LUX_BINS = [100, 250, 500, 750, 1000, 2000, 5000, 10000]

data = pd.read_csv("data/ls_room_999.csv",
                   header=None, delimiter=',', low_memory=False).to_numpy(dtype='float')

cluster_ids_x = np.digitize(data[:,4].reshape(-1, 1), LUX_BINS)
classes, class_counts = np.unique(cluster_ids_x, return_counts=True)
points_percentage = class_counts * 100 / cluster_ids_x.size

plt = histogram(np.sqrt(data[:, 4]),
                title="LUX histogram",
                xtitle="\sqrt(intensity)",
                bins=np.sqrt(LUX_BINS),
                xlim=(9,60),
                ylim=(0,10000),
                c='cyan3',
                aspect=4/3,
)
xy = np.c_[plt.centers, plt.freqs]

plt += plot(xy, spline=True, lc='tomato', lw=4)

for i in range(5):
    value = precision(points_percentage[i], 3)+'%'
    txt = Text3D(value, pos=xy[i], justify="bottom-center", c="blue2")
    plt += txt.scale(250).shift(0,200,1)

plt.show(size=(800, 700), zoom=1.2).close()
```
![Screenshot from 2021-05-15 01-57-48](https://user-images.githubusercontent.com/32848391/118341929-77007900-b521-11eb-9ad6-802ae7e4261f.png)

consider that the orange line in the first matplotlib plot is **completely meaningless** as you are artificially creating categories (where you actually should not!).

**Comment by ttsesm** [comment]
> why not plotting the sqrt(intensity) so the scale is not more linear?
> 
Because I do not really care to the actual range of the values in the x-axis but rather showcasing the distribution per cluster of the different range values. If you see the x-ticks in the initial plot are modified so that they show the different clusters for which I want to show how many points/values I have in each range.

> consider that the orange line in the first matplotlib plot is **completely meaningless** as you are artificially creating categories (where you actually should not!).

Practically yes, but for showcasing/visualizing the amount of points/values per cluster it is not :-). Consider that my number of clusters are fixed (so actually my categories are there), for example in matlab I can set my `LUX_BINS` and create the plot by using the `bar()` function (and not histogram actually) as follows:
```
LUX_BINS = [100 250 500 750 1000 2000 5000 10000 inf];

[N,grps] = histcounts(lsroom999(:,5),LUX_BINS);
centers = [100:100:800];
figure, hb = bar(centers,N,'hist');
```

I can create the similar arrays in python with:

```
LUX_BINS = np.array([100, 250, 500, 750, 1000, 2000, 5000, 10000, 50000]) # I am using 50k or even a bigger number since I cannot set inf

data = pd.read_csv("ls_room_999.csv", header=None, delimiter=',', low_memory=False).to_numpy(dtype='float')

cluster_ids_x = np.digitize(data[:,4].reshape(-1, 1), LUX_BINS)
classes, class_counts = np.unique(cluster_ids_x, return_counts=True)
points_percentage = np.zeros(LUX_BINS.size)
points_percentage[0:classes.size] = class_counts * 100 / cluster_ids_x.size
```

but I am not sure there something similar like `bar()` in vedo so that something similar could be done.

**Comment by marcomusy** [comment]
Ok - so if I cannot convince you there it is:
`pip install -U git+https://github.com/marcomusy/vedo.git`

then:
```python
import numpy as np
import pandas as pd
from vedo import precision, Text3D, colorMap, settings
from vedo.pyplot import plot

settings.defaultFont = "Meson"

LUX_BINS = [100, 250, 500, 750, 1000, 2000, 5000, 10000]
labels   = ['<100', '100-250', '250-500', '500-750', '750-1000', '1000-2000', '>2000']
colors   = colorMap(range(len(labels)), "hot")

data = pd.read_csv("ls_room_999.csv", header=None).to_numpy(dtype='float')

cluster_ids_x = np.digitize(data[:,4].reshape(-1, 1), LUX_BINS)
classes, class_counts = np.unique(cluster_ids_x, return_counts=True)
points_percentage = class_counts * 100 / cluster_ids_x.size
counts, edges = np.histogram(data[:,4], bins=LUX_BINS)

plt = plot([counts, labels, colors],
            mode="bars",
            ylim=(0,10500),
            aspect=4/3,
            axes=dict(htitle="Clusters per lux range",
                      hTitleItalic=False,
                      xLabelRotation=35,
                      xLabelSize=0.02,
                ),
)

for i in range(5):
    value = precision(points_percentage[i], 3)+'%'
    txt = Text3D(value, pos=(plt.centers[i], counts[i]), justify="bottom-center", c="blue2")
    plt += txt.scale(200).rotateZ(0, locally=True).shift(0.075,150,1)

plt.show(size=(800, 700), zoom=1.2).close()
```

![Screenshot from 2021-05-15 16-20-04](https://user-images.githubusercontent.com/32848391/118364977-131a9680-b59b-11eb-94d0-694ab8d4266b.png)

> for showcasing/visualizing the amount of points/values per cluster it is not :-). 

No! the spline is completely meaningless in this case! All spline points in between categories have no defined `x`.

**Comment by ttsesm** [comment]
Scientifically I am 100% with you and I understand your points, but you know non scientific people like figures (and not only) that can understand better.

**Comment by marcomusy** [comment]
You should educate them LOL
Would you mind if I add a simplified version of this among the pyplot examples?

**Comment by ttsesm** [comment]
Νοpe, please feel free.

(I will close this now)
