### ISSUE TITLE
Problem to export from VTK to PLY with colors

### ISSUE THREAD

**Issue by cogitas3d** [marcomusy/vedo#392]
Hey there!

I have a segmented model in VTK with different colors to deifferent teeth:

![Captura de tela_2021-05-12_10-25-53](https://user-images.githubusercontent.com/2422483/117992017-96728880-b30c-11eb-863c-1afaef4902f6.png)

I exported it to PLY using vedo:

> import vedo
mesh = vedo.load("Original.vtk")
vedo.io.write(mesh, "Result.ply", binary=True)

And the Result had only two different colors:

![Captura de tela_2021-05-12_10-30-30](https://user-images.githubusercontent.com/2422483/117992690-1e589280-b30d-11eb-9710-d25599567f0c.png)

Original: 
[Original.zip](https://github.com/marcomusy/vedo/files/6466857/Original.zip)

Result:
[Result.zip](https://github.com/marcomusy/vedo/files/6466858/Result.zip)

Is it possible export it keeping the original colors?

Thanks for your attention.

**Comment by marcomusy** [comment]
Hi Cicero, thanks for your interest.
It looks like this is due to a limitation in the upstream VTK reader for the `ply` format.
https://www.paraview.org/pipermail/paraview/2018-March/042164.html

**Comment by cogitas3d** [comment]
Hi @marcomusy 

Thank you to answer me.

Yes, I read this post in other research I made. Curiously I open the vpt file on Paraview and export like ply with colors. You can do it on that software. But I need a solution based on command line or Python, to increase the addon I develop.

The result manually open and export on Paraview:

![IMG-20210512-WA0008](https://user-images.githubusercontent.com/2422483/118063028-3f999d00-b366-11eb-9f1a-fb6d3f709511.jpg)

Do you think it is possible to convert Scalars to colors with vedo?

A big hug!

**Comment by marcomusy** [comment]
that's an interesting piece of information. I need then to investigate it further.

> Do you think it is possible to convert Scalars to colors with vedo?

yes absolutely, there are various examples to do it , check e.g:
https://github.com/marcomusy/vedo/blob/master/examples/basic/mesh_custom.py
https://github.com/marcomusy/vedo/blob/master/examples/basic/mesh_coloring.py

**Comment by cogitas3d** [comment]
> that's an interesting piece of information. I need then to investigate it further.

This is the original vtp file:
[Arcada_Superior_predicted_refined.zip](https://github.com/marcomusy/vedo/files/6469840/Arcada_Superior_predicted_refined.zip)

And this is the PLY exported from ParaView:
[PARA.zip](https://github.com/marcomusy/vedo/files/6469842/PARA.zip)

I'll and study the files you sent me, thank you!

**Comment by cogitas3d** [comment]
Ready!

Now you can import VTK using OrtogOnBlender add-on and vedo.

YouTube video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/Ip_gYMoFK1E/0.jpg)](https://www.youtube.com/watch?v=Ip_gYMoFK1E)

Next step: Pubblish a book chapter about it, cite the tools and mak the acknoledgements.

Thank you very much @marcomusy !
