### ISSUE TITLE
how to get rotateMatrix for a line.

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#396]
firstly:
I have two points.
points=[[2,2,5],[,12,5,6]]

secondly:
I created a line from the two points.

thirdly:
I tend to get the rotateMatrix which could rotate an origin-line([0,0,0],[0,0,1])  overlap with it.
Thanks.

**Comment by timeanddoctor** [comment]
![image](https://user-images.githubusercontent.com/28825816/118387928-d52d7900-b653-11eb-9361-61f5e4565b77.png)

**Comment by marcomusy** [comment]
Yes, check out
`examples/basic/align5.py`
you can use `s3.getTransform().GetMatrix()` to extract the matrix.

**Comment by timeanddoctor** [comment]
Thanks.
