### ISSUE TITLE
Resolve overlapping faces in the mesh

### ISSUE THREAD

**Issue by emmadavis16** [marcomusy/vedo#397]
Dear @marcomusy,
Is it possible to remove or resolve the overlapping faces in the mesh using vedo library...?
if any possible way. I will be grateful to use it.
Thanks in advance

Regards,
E.davis

**Comment by marcomusy** [comment]
Yes. Use `mymesh.clean()`.

**Comment by emmadavis16** [comment]
> Yes. Use `mymesh.clean()`.

Thanks for the information...I will try it..!!

**Comment by emmadavis16** [comment]
> Yes. Use `mymesh.clean()`.

I tried using  `mesh.clean()` method but still it is not resolving the issue of overlapping faces...is there any other possible solution....

**Comment by marcomusy** [comment]
Hi Emma, I'm afraid you need to provide some reproducible script/dataset otherwise it's difficult to understand where the problem.. is.
