### ISSUE TITLE
surface display is strange, while wireframe display is correct

### ISSUE THREAD

**Issue by qianyizhang** [marcomusy/vedo#402]
any idea what might go wrong?
Im using vedo.__version__ == '2021.0.3' on a laptop with no dedicated graphic card
wireframe display
![image](https://user-images.githubusercontent.com/12500132/119763294-d5463800-bee1-11eb-9d58-eae3861f1cc4.png)
surface display
![image](https://user-images.githubusercontent.com/12500132/119763319-e1ca9080-bee1-11eb-81a1-66dfcf3d0663.png)

**Comment by marcomusy** [comment]
Thanks for reporting it.
That looks pretty strange, are sure you are not overlapping more than one mesh?
Is that only happening on your laptop?
What if you press `p` (point representation)?

**Comment by qianyizhang** [comment]
point representation seems even better.
![image](https://user-images.githubusercontent.com/12500132/119816949-ee6dd980-bf1f-11eb-8a04-3e2bcfcef3c3.png)
in case you are curiour, i was playing around with this repo:
https://github.com/Tai-Hsien/Mesh_Labeler
and narrow down the problem rooted here, perhaps i should report to vtk?

**Comment by marcomusy** [comment]
Hi Keyi, thanks for pointing me to that repo, it looks cool!
Inside that package there is one mesh, and I have no problem visualizing it - so I cannot reproduce the issue unfortunately.
```python 
from vedo import Mesh

Mesh('Example_01.vtp.gz').cmap('prism_r', on='cells').show()
```
![Screenshot from 2021-05-28 12-49-48](https://user-images.githubusercontent.com/32848391/119973234-82d54c00-bfb3-11eb-982d-02e6c575026b.png)
[Example_01.vtp.gz](https://github.com/marcomusy/vedo/files/6560368/Example_01.vtp.gz)

**Comment by qianyizhang** [comment]
It's likely a ENV specific or even hardware specfic problem, I was hoping for some clues/insights from experienced 3d developers XD

**Comment by marcomusy** [comment]
Are you getting the expected output from example
`examples/basic/mesh_coloring.py`

![Screenshot from 2021-05-28 13-05-53](https://user-images.githubusercontent.com/32848391/119974892-89fd5980-bfb5-11eb-8616-0f9389b5b7ce.png)

**Comment by qianyizhang** [comment]
interestingly, the middle one seems fine, while the other 2 are strange
![vedo](https://user-images.githubusercontent.com/12500132/119978574-61448680-bfec-11eb-9379-f199b12f0718.gif)

**Comment by marcomusy** [comment]
not sure if the middle one completely fine.. Can you try this:
```python
from vedo import *

settings.useDepthPeeling = False
settings.multiSamples    = 0  # antialiasing
settings.allowInteraction= False
settings.computeNormals  = False

man3 = Mesh(dataurl+"man_low.vtk")
scals = man3.cellCenters()[:, 2] + 37
man3.cmap("afmhot", scals, on='cells')
man3.show()
```

what VTK version are you using? (press `h` to know it)

**Comment by qianyizhang** [comment]
vedo 2021.0.3 | vtk 9.0.1 | python 3.8
![vedo](https://user-images.githubusercontent.com/12500132/120055262-74486c80-c067-11eb-989c-7d4d15289155.gif)

**Comment by marcomusy** [comment]
uhm... so same problem.... the only idea you may wish to try is to downgrade to python 3.7 + vtk 8.1.2
sorry I cannot think of anything else causing this.

**Comment by qianyizhang** [comment]
thanks for your effort anyway
