### ISSUE TITLE
Show() issue

### ISSUE THREAD

**Issue by dodointhesnow** [marcomusy/vedo#403]
Hi, I’ve tried pretty much everything and am running just the examples but I get an error when I attempt to show the mesh or volume. When I run the command I get “ERROR: OpenGL MAX_3D_TEXTURE_SIZE is -1”. Any clue on what to do to fix this?

**Comment by marcomusy** [comment]
Hi, can you run this script:
```python
import vtk

cone = vtk.vtkConeSource()

coneMapper = vtk.vtkPolyDataMapper()
coneMapper.SetInputConnection(cone.GetOutputPort())

coneActor = vtk.vtkActor()
coneActor.SetMapper(coneMapper)

ren = vtk.vtkRenderer()
ren.AddActor(coneActor)
ren.SetBackground(0.1, 0.2, 0.4)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
renWin.SetSize(500, 500)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

renWin.Render()
iren.Start()
```
or do you get the same error?

**Comment by dodointhesnow** [comment]
Hey I was able to fix it thank you for the help. Believe I was missing something in installation
