### ISSUE TITLE
Rectangle Pyramid

### ISSUE THREAD

**Issue by eivindtn** [marcomusy/vedo#404]
Hi Marco! Is there a way to make the pyramid shape `vedo.shape.Pyramid` with a rectangular form ? It is for making a figure of a field of view for a 3D camera. 
In advance, thank you!

**Comment by marcomusy** [comment]
Hi, you can extrude any line or shape linearly along z and reorient it the way you like, eg.:
```python
from vedo import Polygon
p = Polygon(nsides=4).rotateZ(45)
ep = p.extrude(zshift=3, dR=-1).clean().lw(1)
ep.rotateY(-90)
ep.show(axes=1)
```
<img width="362" alt="Screenshot 2021-06-02 at 11 58 13" src="https://user-images.githubusercontent.com/32848391/120461178-12a33d80-c39a-11eb-8655-2a04ec564125.png">

**Comment by eivindtn** [comment]
Thanks! Regarding your example I doesn't understand how I can make the `nsides` into a rectangular form, since I only can change the radius? But the rotation around the pivoting point is very nice!

**Comment by marcomusy** [comment]
Just change `Polygon` to `Rectangle` or any other 2d shape or line.
Also, `ep.orientation()` I guess can be useful in your case.

**Comment by eivindtn** [comment]
I tried using `v.shapes.Rectangle` instead of the `Polygon`, but I dont get it to be a pivot point.

```python
from vedo import Rectangle
p = Rectangle(p1=(0, 0), p2=(2, 1), c='gray6', alpha=1)
p.origin(1,0.5,3)
ep = p.extrude(zshift=3, dR=-1).clean().lw(1)
ep.show(axes=1).close()
```
![image](https://user-images.githubusercontent.com/70319228/120466892-de328000-c39f-11eb-9d8b-c3110c0d3cc6.png)

**Comment by marcomusy** [comment]
It's probably best then if you define the points and extrude the line:
```python
from vedo import *
pts = [(-2,-1), (2,-1), (2,1), (-2,1)]
p = Line(pts, closed=True).lw(1)
ep = p.extrude(zshift=3, dR=-2).flat()
ep.rotateY(-90)
ep.show(axes=1)
```

**Comment by eivindtn** [comment]
Great @marcomusy ! Thank  you :)
