### ISSUE TITLE
2D, 3D delauny meshing, A question?

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#406]
Hii 
Thanks for your very interesing and useful software

I have a set of points and would like to make the mesh only inside the area of interest both in 2D and 3D. When I use delauny triangulation I see the results are not what I want. I would appreciate if you Could kindly let me know whether there is any possibility to produce delauny mesh like what I explained in the file?  I have shared the explanation of my problem in the below link

https://wetransfer.com/downloads/de73763c89f4cff85ffc379b12a2b96920210604174546/b9aae2451c4de00e074c1d5713c6f1f720210604174546/995e1f 

Thanks a lot for your kind consideration and time. 
Regards
Sahar

**Comment by marcomusy** [comment]
Hi, in 2D it is very easy! Just use 
```python
line = Line(mypts, closed=True)
mesh1 = line.tomesh() # method1
mesh2 = line.triangulate() # method2
```
see example
https://github.com/marcomusy/vedo/blob/master/examples/advanced/line2mesh_tri.py

**Comment by sahar-github** [comment]
oh thanks the first method did not work, but the second one indeed worked really well. thank you

And If I want to do it in 3D also? do you any suggestion for that? I would be really thankful

**Comment by marcomusy** [comment]
I don't quite understand what you mean "in 3D".
Unless the surface is projectable on a 2d plane the problem has no general solution.
