### ISSUE TITLE
save the created mesh from delauny2d and 3d

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#407]
Hii, 
thanks a lot for your effort, which is really useful

How can i save a mesh created by vedo? 
if I use mesh.write("name.ply") this will not work

I can save the point cloud like this, but not the output mesh from triangulation. 
I will get an error message like this

lut = objct.GetMapper().GetLookupTable()

AttributeError: 'vtkmodules.vtkRenderingVolumeOpenGL2.vtkOpenGLProj' object has no attribute 'GetLookupTable'

I would appreciatie any feedback or help
Thanks

**Comment by marcomusy** [comment]
From the error message I think you are trying to save a Volume to a mesh file (ply)?
As a test, this seems to work as expected:
```python
from vedo import *
s = Sphere()
s.write("name.ply")
```

**Comment by sahar-github** [comment]
Thanks for your prompt response. 
What I am doing is something like below:
tmesh = delaunay3D(pts)
tmesh.write('3Dmesh.ply')

and this is not working unfortunately, am I doing something wrong?

**Comment by marcomusy** [comment]
> am I doing something wrong?

Yes :)
You cannot write a tetrahedral mesh to ply (it is not supported afaik).

**Comment by sahar-github** [comment]
Then how can i save it that I can use it in other applications? Do you have any suggestions?
Thanks for your consideration and time

**Comment by marcomusy** [comment]
I guess you can only save it as vtk file (vtkUnstructuredGrid).
