### ISSUE TITLE
Animation of arrows with sliders

### ISSUE THREAD

**Issue by pfisterj** [marcomusy/vedo#408]
Hello,

Thank you for sharing this nice tool, the examples look really promising ! 

I am currently trying to animate a triad of unit vectors using a slider. What I want to control is the position of the starting point and of the end point of each vector. As a first try, I have simply encoded the canonical basis {e1,e2,e3} and I just want to modify the first coordinate of vector e1. My code is below :

```
from vedo import *

def slider(widget, event):
    """modify the norm of vector e1"""
    value = widget.GetRepresentation().GetValue()
    e1.top = [1-value,0,0] # this is what I want to do, but this does nothing on screen
    print(e1.top) # does display variing coordinates as expected
    #e1.pos([1-value,0,0]) # does something on screen, but not what I want !
    #e1.rotateZ(value) # does something on screen, but not what I want !
    
plt = Plotter(axes=True)

e1 = Arrow(startPoint=[0,0,0], endPoint=[1,0,0], s=None, c='red'  )
e2 = Arrow(startPoint=[0,0,0], endPoint=[0,1,0], s=None, c='green')
e3 = Arrow(startPoint=[0,0,0], endPoint=[0,0,1], s=None, c='blue' )

plt.show(e1,e2,e3, at=1) # If I remove 'at=1', then the slider disappears
plt.addSlider2D(slider, 0, 1, value=0, pos="bottom-right", title="a slider")

plt.show(interactive=1).close() # no visible modification of the arrow's length
```

There are two things I do not understand here : 
* As is defined, the slider does not seem to modify the plot. Looking at the Arrow class, there are methods I could use to modify the position and orientation of the arrow on screen, but not really in the way I want. Is there a possibility to somehow change dynamically the startPoint/endPoint of the arrow ?
* in plt.show() I had to pass the argument at=1 to make the slider visible, i don't really understand why... This also raises the warning ```Error in show(): wrong renderer index 1```, any reason for that ?

Any help would be welcome!
Thanks

**Comment by marcomusy** [comment]
Hi, thanks for reporting the problem so clearly.
1. `top` only defines the "natural" (what you consider it to be) orientation of the object in space, but it has no effect here, it' only used by the `orientation()` method.
2. you should add the slider before the `show` command so you don't need two calls to it
3. you missed a `render()` call in the callback slider function.
4. remember that `rotate()` remembers the current transformation so it acts on top of it.

Try this:
 ```python
from vedo import *

def slider(widget, event):
    """modify the norm of vector e1"""
    value = widget.GetRepresentation().GetValue()
    e1.scale([value,1,1], absolute=True)
    e1.x(1-value) 
    #e1.rotateZ(value)  # not sure what are you trying to achieve here
    plt.render()
    
plt = Plotter(axes=True)

e1 = Arrow([0,0,0], [1,0,0], s=0.005, c='red'  )
e2 = Arrow([0,0,0], [0,1,0], s=0.005, c='green')
e3 = Arrow([0,0,0], [0,0,1], s=0.005, c='blue' )

plt.addSlider2D(slider, 0.0, 1.0, value=1, 
	            pos="bottom-right", title="x slider")
plt.show(e1,e2,e3).close()
```
<img width="459" alt="Screenshot 2021-06-05 at 00 17 09" src="https://user-images.githubusercontent.com/32848391/120868030-662cab80-c593-11eb-87c1-e906a08676f8.png">

Let me know if you need additional help.

**Comment by pfisterj** [comment]
Hello, thank you for your quick reply!

Your solution solved my problem for the simple example I gave. This also helped me to generalize to the case of an arbitrary transformation, using the very convenient method ```applyTransform```. The updated code is below (this one moves and rotates the frame according to the slider) :

```
from vedo import *
import numpy as np

def frame_homogeneous_transformation(t):
    """returns an example of some 4x4 homogeneous transformation matrix 
    defining the position and orientation of a frame {O,e1,e2,e3}"""
    c1,s1 = np.cos(t),np.sin(t)
    c2,s2 = np.cos(2*t),np.sin(2*t)
    T1 = np.array([[c1,-s1,0,t/np.pi],[s1,c1,0,0],[0,0,1,0],[0,0,0,1]])
    T2 = np.array([[c2,0,-s2,0],[0,1,0,0],[s2,0,c2,0],[0,0,0,1]])
    return T1.dot(T2)

def slider(widget, event):
    """updates the frame {O(t),e1(t),e2(t),e3(t)}"""
    t = widget.GetRepresentation().GetValue()
    T = frame_homogeneous_transformation(t)
    e1.applyTransform(T)
    e2.applyTransform(T)
    e3.applyTransform(T)
    plt.render()
   
plt = Plotter(axes=True)

# define the initial origin & orientation of the frame
e1 = Arrow([0,0,0], [1,0,0], s=0.005, c='red'  )
e2 = Arrow([0,0,0], [0,1,0], s=0.005, c='green')
e3 = Arrow([0,0,0], [0,0,1], s=0.005, c='blue' )
frame = [e1,e2,e3]

plt.addSlider2D(slider, 0.0, np.pi, value=0.0, 
               pos="bottom-right", title="x slider")
plt.show(frame).close()
```

Thank you for your help :-)
