### ISSUE TITLE
addCallback in qtWidget

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#409]
Hello @marcomusy,

I have been used `addCallback` in vedo2020 version and it worked. Recently, I upgraded my vedo verison to 2021.0.2, and I just found that the `addCallback` function no longer works for my pyqt application. I realized in the 2021 version, you have simplified the `addCallback`. The mousehighlight example works for me. I tried to adjust the related code according to the example, but always get the error as `AttributeError: 'Plotter' object has no attribute '_timer_event_id'`

The related code is something like
```
class Qt_App(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(Qt_App, self).__init__(parent)
        self.setupUi(self)
        
        self.vp = Plotter(qtWidget=self.vtkWidget)
        self.vp.addCallback('LeftButtonPressEvent', self.select)

    def select(self, evn):
        print('hello!', evn)
```

Could you help me figure it out? Many thanks!

**Comment by marcomusy** [comment]
Hi does the same happen in version 2021.0.3?

**Comment by Tai-Hsien** [comment]
Hello @marcomusy,

Just tried it, and yes. The same error message shows up in vedo.2021.0.3.

**Comment by Tai-Hsien** [comment]
Hello @marcomusy,

I just saw you marked this issue as a bug 16 hours ago. Thanks a lot for taking care about it. Just wonder if there is a temporary solution for it. Many thanks.

**Comment by marcomusy** [comment]
Hi Bruce, sorry for the late reply, after:
`pip install -U git+https://github.com/marcomusy/vedo.git`
you should be able to run the example:
https://github.com/marcomusy/vedo/blob/master/examples/other/qt_window1.py

Let me know if you encounter any problems

**Comment by Tai-Hsien** [comment]
Hello @marcomusy,
Thanks a lot. The github version works!
