### ISSUE TITLE
PLY with texture

### ISSUE THREAD

**Issue by dodointhesnow** [marcomusy/vedo#410]
So I have 2 meshes, one of the entire object and one which is a snip of the object which I have colored based of temperature interpolation. When I try to export to ply, I’m unable to preserve the color on the section with merging the meshes. Any suggestions on how to do this? Thanks.

**Comment by marcomusy** [comment]
this is strange.. it works for me:
```python
from vedo import *
s = Sphere().addQuality().cmap("jet", "Quality", on="cells").lw(1)
#s.mapCellsToPoints()
s.write("file.ply").printInfo()
show(s, axes=1)
```
then
```
vedo file.ply
```
<img width="292" alt="Screenshot 2021-06-10 at 10 35 03" src="https://user-images.githubusercontent.com/32848391/121492851-874c2c80-c9d7-11eb-9645-94ab78c64c0c.png">

**Comment by dodointhesnow** [comment]
I figured out the problem. It was trying to view it in PowerPoint and it was not supported to show textures sadly.
