### ISSUE TITLE
Save the assembly mesh

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#411]
Hiii
I am trying to merge some mesh that I created in vedo and after merging them using any of the methods in the below link
https://github.com/marcomusy/vedo/blob/master/examples/basic/mesh_merge_vs_assembly.py
I would like to save this assembly as a .ply file. 
the funstion write() is not working and I have the below error message:

AttributeError: 'Assembly' object has no attribute 'write'
Could you please let me know if there is any other solution or function that I can use to save my merged mesh?
I would appreciate any help in this regard
Thanks
Sahar

**Comment by marcomusy** [comment]
You cannot save an Assembly object because the `ply` format does not support that at all.
you can save the merged mesh or the 2 meshes in 2 separate ply files.
You can also save an Assembly to a `npz` file , but this is only specific for `vedo`.
