### ISSUE TITLE
Can I carve the volume?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#413]
Can I carve the 3d volume(volume rendering reconstructed ) use a brush shpere.
After pick the position, I tend to hide or delete the diferent local points of the 3d volume one by one using a virtual shpere.

**Comment by marcomusy** [comment]
You cannot "carve" a `Volume` object.

**Comment by timeanddoctor** [comment]
ok, thanks.
If I fill a local area with the air (HU:'-3000') by a virtual sphere?  And then the rendering will hide it just like carving effect.
Thank you.

**Comment by marcomusy** [comment]
sorry, I've no idea of what that means..
