### ISSUE TITLE
Function insidePoints

### ISSUE THREAD

**Issue by HakamShams** [marcomusy/vedo#415]
Thank you for the great library!

Cloud you please explain which method is used for **Mesh.insidePoints**?

Thanks in advanced.

**Comment by marcomusy** [comment]
Thanks, you can have a look at example:
`examples/basic/pca.py`

**Comment by HakamShams** [comment]
Sorry, I mean how is it implemented? Which methods does it use? How does it find the points?

**Comment by marcomusy** [comment]
it leverages the class `vtkSelectEnclosedPoints `
in: https://github.com/marcomusy/vedo/blob/3c4142759f940e32251e2ca32290d1f7597c9f12/vedo/mesh.py#L1409

**Comment by HakamShams** [comment]
Ok. Thank you.
