### ISSUE TITLE
can i convert a shape file to a vedo.shape?

### ISSUE THREAD

**Issue by sahar-github** [marcomusy/vedo#420]
Hi, I have a polygon saved in shp format. I would like to try the Extrude in vedo on my polygon. However, it seems I need to convert my shape file to the vedo shape file in order I have the possibility to use the extrude function
Could you please guide me how can I convert my polygon to the vedo shape?
Thanks a lot!

**Comment by marcomusy** [comment]
You can simply create the 2D line from the vertex coordinates and the extrude those, e.g.:
```python 
from vedo import *
import numpy as np
np.random.seed(3)

polygon = Line(np.random.randn(4,2), closed=True)
epoly = polygon.extrude(1.0)
epoly.c("green6").lighting("default").flat()

show(epoly, axes=1)
```
![Screenshot from 2021-06-24 19-47-27](https://user-images.githubusercontent.com/32848391/123309304-0cc9f380-d525-11eb-8e20-92f5965fa49f.png)

**Comment by sahar-github** [comment]
Thank you very much for the response! now I can use it really well
Best
Sahar
