### ISSUE TITLE
How to convert mesh to volume?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#421]
If I have a volume, I can obtain the surface by:

```
surface = Volume(volume).isosurface(val)
```

But, if I have mesh, how to obtain the mask?

My aim is: construct the mesh with some contour, then obtain the mask from the mesh. 

I find a demo from `example/ribbon.py`:

```
from vedo import *
import numpy as np

l1 = [[sin(x), cos(x), 1] for x in np.arange(0,9, 0.1)]
l2 = [[sin(x), cos(x), 2] for x in np.arange(0,9, 0.1)]

t1 = Tube(l1, c="g", r=0.02)
t2 = Tube(l2, c="b", r=0.02)

r12 = Ribbon(l1, l2, res=(200,5)).alpha(0.5)
show(r12, t1, t2, axes=1, viewup="z")
```
And the result is:

![image](https://user-images.githubusercontent.com/29271051/123220640-ba76db80-d500-11eb-872a-37d2cd6cb58a.png)

1. how to add a cap to this mesh?

I have tried: `Ribbon(l1, l2, res=(200,5)).alpha(0.5).cap()`, but the cap is incorrect:

![image](https://user-images.githubusercontent.com/29271051/123221326-6ae4df80-d501-11eb-85ab-e9a48be4421a.png)

2. how to obtain the mask from this mesh?

Thank you very much for any suggestion!

**Comment by marcomusy** [comment]
I dont understand what has to do the isosurfacing of a volume to the capping of a polygonal mesh.
Also I dont' know what a "mask" is.

You can cap only one side of the cylinder:
```python
from vedo import *
import numpy as np

rng = np.linspace(0, 2*np.pi)
l1 = [[sin(x), cos(x), 1] for x in rng]
l2 = [[sin(x), cos(x), 2] for x in rng]

r = Ribbon(l1, l2, res=(200,5)).alpha(0.4).lw(1).cap()
show(r, axes=1)
```

**Comment by zhang-qiang-github** [comment]
@marcomusy  Thank you for your reply about `cap`. 

By `mask`, I mean a matrix including only 0/1. The pixel insided in the mesh has value of 1, and the pixel outsided of the mesh has value of 0.

**Comment by marcomusy** [comment]
You may have a look at:
`examples/volumetric/mesh2volume.py`
Internally the `vtkPolyDataToImageStencil` class is used.

**Comment by zhang-qiang-github** [comment]
Thank you very much. That's what I want~~~
