### ISSUE TITLE
How to use screenshot 

### ISSUE THREAD

**Issue by ssmns** [marcomusy/vedo#429]
hi, 
i need to use screenshot command
in default the screenshot generate from top, but i need to generate screenshot from sides.
how i can generate a screenshot from side (xy,yz,xz planes) or custom point. 

i need to use this option in offscreen=True and interactive = 0.

**Comment by marcomusy** [comment]
Try:
```python
from vedo import *

# settings.useParallelProjection = True

s = Sphere().wireframe()
axes = Axes(s)
camx = dict(pos=(0, -7, 0),
            #focalPoint=(0, 0, 0),
            viewup=(0, 0, 1))
camy = dict(pos=(7, 0, 0),
            #focalPoint=(0, 0, 0),
            viewup=(0, 0, 1))
show(s, axes, camera=camy, offscreen=True).screenshot().close()
```
