### ISSUE TITLE
The Line do not correctly show before a image

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#431]
Now, I want to show a line in a image. And the code is:

```
import vtk
from vtk.util.numpy_support import vtk_to_numpy, numpy_to_vtk
from vedo import *
import numpy as np

def numpyToVTK(data):
    if len(data.shape) == 2:
        data = data[:, :, np.newaxis]
    flat_data_array = data.transpose(2,1,0).flatten()
    vtk_data = numpy_to_vtk(num_array=flat_data_array, deep=True, array_type=vtk.VTK_FLOAT)
    shape = data.shape

    img = vtk.vtkImageData()
    img.GetPointData().SetScalars(vtk_data)
    img.SetDimensions(shape[0], shape[1], shape[2])
    return img

img = np.zeros(shape=[512, 512])

img[0:256, 0:256] = 0
img[0:256, 256:] = 64
img[256:, 0:256] = 128
img[256:, 256:] = 256

img = numpyToVTK(img)

imgActor = vtk.vtkImageActor()
imgActor.SetInputData(img)

line = Line(p0=[0, 0, 0], p1=[512, 512, 0], c='red', lw=5)
renderer = vtk.vtkRenderer()
renderer.AddActor(imgActor)
renderer.AddActor(line)
renderer.SetBackground(0.4, 0.5, 0.6)

renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)
renderWindow.Render()
renderWindowInteractor = vtk.vtkRenderWindowInteractor()
style = vtk.vtkInteractorStyleImage()
renderWindowInteractor.SetInteractorStyle(style)
renderWindowInteractor.SetRenderWindow(renderWindow)
renderWindowInteractor.Initialize()
renderWindowInteractor.Start()
```

And the result is:

![image](https://user-images.githubusercontent.com/29271051/126739477-8b466cf5-03c4-4775-b66e-767d9b9c63ff.png)

We can see that the red line is behind of the image. 

I find that when setting the line width, the `vedo` code is:

```
            self.GetProperty().EdgeVisibilityOn()
            self.GetProperty().SetLineWidth(lw)
```

The `mesh` may need `EdgeVisibilityOn()`, but `Line` may do not need `EdgeVisibilityOn`. 

I modify my code as:

```
line = Line(p0=[0, 0, 0], p1=[512, 512, 0], c='red', lw=5)
line.GetProperty().EdgeVisibilityOff()
```
And I find the result is correct:

![image](https://user-images.githubusercontent.com/29271051/126739979-e8807c1e-b3e2-4ad6-9b6c-1d73856360d6.png)

I don't know why `EdgeVisibilityOn` would make the `Line` show in behind of image.

**Comment by marcomusy** [comment]
I dont think that `EdgeVisibilityOff` has a real effect it probably depends on the machine+vtk version.. (indeed i could not reproduce the above behavior on my ubuntu). You can:
- shift the line by small tolerance with `.z(1)`
- `img[256:,   256:] = 256` should become `img[256:,   256:] = 255`
- the `Picture` already yields a `vtkImageActor` so you don't need all that code

E.g.

```python
from vedo import Picture, Line, show
import numpy as np

img = np.zeros([512,512])
img[0:256, 0:256] =   0
img[0:256,  256:] =  64
img[256:,  0:256] = 128
img[256:,   256:] = 255
img = img.transpose(1,0)

pict = Picture(img)  # pict is a vtkImageActor !
line = Line(p0=[0,0], p1=[512,512], c='red', lw=5).z(1)

show(pict, line, interactorStyle="Image", bg=(0.4,0.5,0.6), axes=1)
```
![Screenshot from 2021-07-23 17-04-19](https://user-images.githubusercontent.com/32848391/126801789-b87397d3-6459-4638-a2c8-dc83d129b9c1.png)

**Comment by zhang-qiang-github** [comment]
@marcomusy Yes, if using `z(1)`, the line would display correctly. 

But, why `z(1)` is necessary? Actually, `pict` is obtain from `Picture(img)`, and the z value of `pict` should be 0. If I draw a line by `Line(p0=[0,0], p1=[512,512], c='red', lw=5)`, I think the red line should appear in the image. 

But, if you display the line by:
```
line = Line(p0=[0,0], p1=[512,512], c='red', lw=5).z(0)
show(pict, line, interactorStyle="Image", bg=(0.4,0.5,0.6), axes=1)
```
The red line would not be correctly display. 

But, the red line would be correctly display using following code:

```
line = Line(p0=[0,0], p1=[512,512], c='red', lw=5).z(0)
line.GetProperty().EdgeVisibilityOff()
show(pict, line, interactorStyle="Image", bg=(0.4,0.5,0.6), axes=1)
```

Why `EdgeVisibilityOff()` make such result?

**Comment by marcomusy** [comment]
> But, why `z(1)` is necessary?

because otherwise the plane of the pict and the plane of the Line coincide and VTK doesn't know what to show in front of the other. Setting the line at z=1 resolves the ambiguity,

> Why EdgeVisibilityOff() make such result?

my guess is that's a glitch in vtk (as cannot reproduce it in linux).

**Comment by zhang-qiang-github** [comment]
Yes, the ubuntu would give the correct result even using `EdgeVisibilityOn()`. I will post a question in vtk forum.
