### ISSUE TITLE
Hope to support ipygany jupyter backend.

### ISSUE THREAD

**Issue by liwind** [marcomusy/vedo#432]
[ipygany](https://github.com/QuantStack/ipygany) is an easy-to-use jupyter interactive widgets library for 3-D mesh analysis. And it support multiple mesh, grid, and point clouds by GPU accelerated rendering.  
I am eager for the jupyter backend of **vedo** to support **ipygany**.

**Comment by marcomusy** [comment]
Hi
I've just pushed a version that supports ipygany
`pip install -U git+https://github.com/marcomusy/vedo.git`
to use it:
```python
from vedo import *

embedWindow('ipygany')

# create a sphere and use z-coords to color vertices
sph = Sphere().cutWithPlane(normal=(1,1,1))
scalars = sph.points()[:,2] 
sph.cmap('viridis', scalars).addScalarBar()

pts  = Points(sph.points()).c('black')
cube = Cube().c("green5").x(2)
axes = Axes(sph+cube, xyAlpha=0.2, c="white")

show(sph, cube, pts, axes, bg='blackboard')
```
I cannot change though the default viridis and the point size is so small that it's hard to see...
I will investigate this with the maitainers.

<img width="845" alt="Screenshot 2021-08-01 at 12 04 45" src="https://user-images.githubusercontent.com/32848391/127767039-0c543790-a9f1-466e-8dc0-5c6b7dbeae40.png">
