### ISSUE TITLE
Enable specification of k3d Points shader option

### ISSUE THREAD

**Issue by max-brambach** [marcomusy/vedo#433]
Hi,
I'm using vedo to visualise large point clouds and 3D networks via a jupyter notebook running on a remote workstation.
When I'm using the k3d backend, the points are rendered using the 'dots' shader per default. In earlier versions (2021.0.1a March 9th and before) the default was '3d', which I really liked. Also, in earlier versions the size of the points was handed over to k3d, while now it is fixed to the value 3.
Would it be possible to allow the specification of these parameters via vedo when using the k3d backend?
Thanks a lot:)

**Comment by marcomusy** [comment]
Hi
I've just pushed a version that supports it
`pip install -U git+https://github.com/marcomusy/vedo.git`
added more customizations eg:
```python
from vedo import settings 
settings.k3dMenuVisibility = True
settings.k3dPlotHeight = 512
settings.k3dAntialias  = True
settings.k3dLighting   = 1.2
settings.k3dCameraAutoFit = True
settings.k3dGridAutoFit= True
settings.k3dAxesHelper = True    # size of the small triad of axes on the bottom right
settings.k3dPointShader= "mesh"  # others are '3d', '3dSpecular', 'dot', 'flat'
settings.k3dLineShader = "thick" # others are 'flat', 'mesh'
```
let me know if encounter any problems.

**Comment by max-brambach** [comment]
Hi, 
This is exactly what I was hoping for. Thanks so much!
Cheers
