### ISSUE TITLE
maintain axes directions

### ISSUE THREAD

**Issue by JacobHA** [marcomusy/vedo#436]
![oriign](https://user-images.githubusercontent.com/42879357/128119254-3fbdb40b-64e9-4276-bf12-73a43a9f2b2d.PNG)

Upon applying a default axes=4 in the show command of a vtk file, I am met with the axes shown in the image attached. I would like to know how to orientate the axes in a fixed "upright" fashion (i.e. y upright, x to the right). Any help on this?

PS - @marcomusy: thank you for the awesome library!

**Comment by marcomusy** [comment]
Thanks for using `vedo`.
Try `show(....., viewup='z')`. The axis triad is anyway linked to the 3d corrdinate system so they'll move accordingly.
For more fancy triads see `examples/other/inset.py`.

**Comment by JacobHA** [comment]
Thanks a bunch! I am trying to programatically rotate the model and it appears the coordinate system stays fixed, which is good. But now I am seeing the following axes:

![image](https://user-images.githubusercontent.com/42879357/128199738-ed8a62fc-3ad0-4e76-ba4e-a968b6ecbf31.png)
(BTW - it is my guess that it is much more efficient to rotate the camera's position rather than the model itself. But I was experiencing some problems with rotating via roll, azimuth, elevation. In particular, roll was not doing much of anything, and elevation seriously changed the zoom... but I'll open another issue later with more details)

**Comment by RubendeBruin** [comment]
Hi @JacobHA 

don't know if this is what you want, but I use the following code to keep the z-axis vertical as much as possible when rotating the model interactively:

```python
camera = plotter.camera

up = camera.GetViewUp()
        if abs(up[2]) < 0.2:
            factor = 1 - (5 * abs(up[2]))
            camera.SetViewUp(
                factor * up[0], factor * up[1], (1 - factor) + factor * up[2]
            )
        else:
            camera.SetViewUp(0, 0, 1)
```

this code is executed in the vtkInteractionEvent callback:

```
iren.AddObserver(vtk.vtkCommand.InteractionEvent, self.keep_up_up)
```

**Comment by JacobHA** [comment]
Hello @RubendeBruin, thanks for the input! Let me try out this code later today.
BTW - how exactly do you rotate the model? Based on your comment it sounds like you rotate the physical model (i.e. with .rotateX, .rotateY, .rotateZ), is that correct?. Is this slow compared to rotating the camera instead?

**Comment by marcomusy** [comment]
@JacobHA 
no, `rotateX()` rotates the object (effectively changes the vertex coordinates) whereas `GetViewUp()` modifies the camera orientation.
To implement Ruben's function you can have a look at `examples/basic/mouseclick.py`

**Comment by JacobHA** [comment]
Unfortunately this did not work for my purposes.
Instead, I'd like the z-axis pointed vertically, the x axis to the right (parallel to edges of window) and y axis into the page.
Is there a way to do this?

**Comment by RubendeBruin** [comment]
@JacobHA do I understand correctly that you want to have your axis fixed: `I'd like the z-axis pointed vertically, the x axis to the right (parallel to edges of window) and y axis into the page` regardless of the rotation of your model?

**Comment by JacobHA** [comment]
@RubendeBruin Yes, that is exactly what I'd like!

**Comment by marcomusy** [comment]
ahhh but then clearly you want to use `rotateX()..` (one you have set up once for all the camera)

**Comment by JacobHA** [comment]
@marcomusy 
Yes, I am already using the rotate methods on the mesh. 
It seems that I was able to get the viewing angle correct by doing `camera position = (0, -15, -1)` but then it destroyed my zooming function (which uses the `zoom `argument in `show()`) - I am guessing because the focal point is now out of whack. So instead of opening that can of worms, for now I am sticking with viewup='z' ...

**Comment by JacobHA** [comment]
Sorry @marcomusy maybe I misunderstood your last comment.. are you suggesting to somehow use a rotate method on say, the camera?

**Comment by marcomusy** [comment]
no, wait... the camera sets the position and orientation of what you are looking at.
if you want to have a sort of fixed view-up setting of the cam you can use viewup='z' and then modify the position and orientation of the object within that reference frame with `myobj.rotateX()` (which will change the vertex coords of the mesh).
Or maybe i'm confused on what you are trying to achieve.

**Comment by JacobHA** [comment]
Hmm.. Maybe I'm not explaining things well.
Basically, I have a model that the user can transform with some custom events. When my model is transformed, the coordinate axes do not (and should not) change.
However, upon using viewup='z', my axes appear as in the second image in this thread, which is close to what I'd like but not quite there. I'd like a fixed axes which are parallel to the window borders.

It's almost as if I'd like to additionally set viewright='x'.
Does this make any sense? Sorry for the confusion!

**Comment by marcomusy** [comment]
what about something like this?
```python
from vedo import *

m = Mesh(dataurl+"cow.vtk")

cam = dict(pos=(0,0,4), focalPoint=(0,0,0), viewup=(0,1,0))

show(m, camera=cam, interactorStyle='Image', axes=4, size=(600,400))
```
![Screenshot from 2021-08-07 18-48-27](https://user-images.githubusercontent.com/32848391/128607797-75e1e0e9-de9a-43fb-963a-4c5b74f12d81.png)

the `interactorStyle` will prevent modifying the axes orientation but still allows zooming.
then you can use ".rotateX().shift()" to move stuff around.

**Comment by JacobHA** [comment]
That's absolutely helpful (I actually wanted `cam = dict(pos=(1,0,0), focalPoint=(0,0,0), viewup=(0,0,1))`) just had to rescale my model appropriately. Thanks a bunch!
