### ISSUE TITLE
Native cross section

### ISSUE THREAD

**Issue by JacobHA** [marcomusy/vedo#438]
Is there currently any more "native" way to take and view cross sections of Mesh objects?
I see the example under trimesh, but I'm having some trouble installing required libraries (particularly shapely gives some trouble, on Windows 64bit).

**Comment by marcomusy** [comment]
you can check out `examples/basic/surfIntersect.py` to obtain a set of lines or can also slice a thin slice with `.cutWithPlane()` method which results in a mesh.
`vedo --search cutWithplane -i`
`vedo --run inset`

**Comment by JacobHA** [comment]
Perfect! It seems you have already made a method for everything 🥇
