### ISSUE TITLE
example can not run

### ISSUE THREAD

**Issue by subenyu** [marcomusy/vedo#439]
when i try run the example, it does not work.
who can tell me the reason?
And i have install it.
<img width="879" alt="22" src="https://user-images.githubusercontent.com/60449974/128636366-bbdbf1f3-e36f-43d0-ae55-d2abb38d7c4d.png">

**Comment by marcomusy** [comment]
Hi, what is your environment? does it work from a normal terminal?
Try:
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by subenyu** [comment]
Hi 
I use the spder to run the codes

**Comment by subenyu** [comment]
<img width="376" alt="444" src="https://user-images.githubusercontent.com/60449974/128636641-6c8f2c4b-abae-41ab-a9ae-82605d291d6a.png">
i install it like this and it is sucessfull

**Comment by subenyu** [comment]
<img width="491" alt="55" src="https://user-images.githubusercontent.com/60449974/128636689-7c618665-825d-461e-a0b7-15ddeffd1034.png">
i used the jupyter like this. And still does not work

**Comment by subenyu** [comment]
And where can i find the examples to run the code in spyder or jupyter?

**Comment by marcomusy** [comment]
Make sure you are not blocking popups on your browser.
Or else try:
![Screenshot from 2021-08-08 17-14-34](https://user-images.githubusercontent.com/32848391/128636921-3d7825c8-ddc6-4b5b-858a-b03ee4445a6a.png)

jupyter notebooks examples are in 
https://github.com/marcomusy/vedo/tree/master/examples/notebooks
be aware that many rendering functionalities are not available in jupyter environment.
Avaliable backends are: `k3d, panel, ipyvtk, ipygany, itk, 2d`.
panel and itk might not even work, the other should!

**Comment by subenyu** [comment]
@marcomusy 
Thank you very much and now it works.
