### ISSUE TITLE
Output Points Number is different from C++ when I decimate a stl model

### ISSUE THREAD

**Issue by dangis-lll** [marcomusy/vedo#442]
In python:
```python
mesh = vedo.load(os.path.join(mesh_path, mesh))
target_num = 10000
ratio = target_num/mesh.NCells() 
mesh_d = mesh.clone()
mesh_d.decimate(fraction=ratio)
```
I got 5380 points.
In C++:
```
vtkNew<vtkDecimatePro> decimate_a;
decimate_a->BoundaryVertexDeletionOn();
decimate_a->SetInputData(stl_reader->GetOutput());
decimate_a->SetTargetReduction(1-ratio_d);
decimate_a->Update();
vtkSmartPointer<vtkPolyData> Polydata_d_a;
Polydata_d_a = decimate_a->GetOutput();
```

I got 5884 points.
And here is my model:
[sample.zip](https://github.com/marcomusy/vedo/files/6979898/sample.zip)

**Comment by marcomusy** [comment]
You need to use the "pro" algorithm (default is "quadric"):
`mesh.decimate(fraction=ratio, method="pro").printInfo()`

also the decimation is related to points not cells.. so the ratio should be calculated based on 
`ratio = target_num/mesh.NPoints()`
