### ISSUE TITLE
Question about example/basic/spline_tool

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#443]
I am very interesting in example/basic/spline_tool, but I am confused about the code. 

1. how to construct the spline line by control points?
2. how to obtain the world coordinate when move the control point?

Could you please tell me where is the call back function for the mouse move? I really can not find it. 

In addition, a bug is reported when run example/advanced/gyroid.py:
```
'Mesh' object has no attribute 'smooth'.
```
My `vedo` version is: 2021.0.3

**Comment by marcomusy** [comment]
Try:
`pip install -U git+https://github.com/marcomusy/vedo.git`

then:
```python
from vedo import Circle, show

# Create a set of points in space
pts = Circle(res=8).extrude(zshift=0.5).pointSize(4)

# Visualize the points
plt = show(pts, "Move nodes", interactive=False, axes=1)

# Add the spline tool using the same points and interact with it
sptool = plt.addSplineTool(pts)

# add a point and remove the point id 2
sptool.add([0.5,0.5,1]).remove(2)
# print(sptool.nodes()) # current position of the nodes

# Switch off the tool
sptool.off()

# Extract and visualize the resulting spline
sp = sptool.spline().lw(4)
# print(sp.points()) # 3d points of the final spline
# print("spline length is", sp.length())
show(sp, "My spline is ready!", interactive=True, resetcam=False)
```

1. control points are `pts` in the example (this can be a `Points` object or a numpy array).
2. with `sptool.nodes()`

> Could you please tell me where is the call back function for the mouse move? I really can not find it.

There isn't (i guess, unless you unpack the vtk widget manually...).

> a bug is reported when run example/advanced/gyroid.py

should be now fixed.

**Comment by zhang-qiang-github** [comment]
How to generate the bspline line using the control points? Where can I find this function?

I think this function would be called in real time when the control point is moved. Am I right? So, where is this function used?

**Comment by marcomusy** [comment]
> How to generate the bspline line using the control points? Where can I find this function?
> 
> I think this function would be called in real time when the control point is moved. Am I right? So, where is this function used?

yes, but that happens inside vtk, so i'm afraid you have to trace it back in the vtk classes..

**Comment by zhang-qiang-github** [comment]
Thank you for your reply~~~
