### ISSUE TITLE
Volume unable to initialise with vtkImageData data type object

### ISSUE THREAD

**Issue by charuu** [marcomusy/vedo#448]
On initialising vedo.volume.Volume(volumeNode.GetImageData()), with a ImageData object i am getting the following error and similar with a numpy array.

IndexError                                Traceback (most recent call last)
In  [68]:
Line 3:     

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/volume.py, in __init__:
Line 1035:  self.mode(mode).color(c).alpha(alpha).alphaGradient(alphaGradient)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/base.py, in color:
Line 1497:  r,g,b = colors.colorMap(x, name=col, vmin=vmin, vmax=vmax)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/colors.py, in colorMap:
Line 657:   return hex2rgb(cmap[n-iv])

IndexError: list index out of range

**Comment by marcomusy** [comment]
Thanks for reporting. Can you reproduce the following example:
```python
from vedo import dataurl, Volume, show

img = Volume(dataurl+"vase.vti").imagedata() # vtkImageData

vol = Volume(img)

# can set colors and transparencies along the scalar range
# from minimum to maximum value. In this example voxels with
# the smallest value will be completely transparent (and white)
# while voxels with highest value of the scalar will get alpha=0.8
# and color will be=(0,0,1)
vol.color(["white", "fuchsia", "dg", (0,0,1)])
#vol.color('jet') # a matplotlib colormap name is also accepted
vol.alpha([0.0, 0.2, 0.3, 0.8])

# a transparency for the GRADIENT of the scalar can also be set:
# in this case when the scalar is ~constant the gradient is ~zero
# and the voxel are made transparent:
vol.alphaGradient([0.0, 0.5, 0.9])
vol.addScalarBar3D()

# show command creates and returns an instance of class Plotter
show(vol, size=(800,600), axes=1)
```
![Screenshot from 2021-09-03 12-50-30](https://user-images.githubusercontent.com/32848391/131994317-a212750a-ee66-4cd2-a5b3-3b0c6fa3551e.png)
if so, does it work with your data set?
what `vedo` version are you using? (try command: `vedo --info`)

**Comment by charuu** [comment]
This is working on my system. I am trying to get the vtkImageData object from slicer library ,which it is not accepting and also the numpy array . 
Below is the configuration:
vedo version      : 2021.0.5   https://vedo.embl.es
vtk version       : 9.0.3
python version    : 3.7.3 (default, Mar 27 2019, 16:54:48) [Clang 4.0.1 (tags/RELEASE_401/final)]

**Comment by marcomusy** [comment]
Ok, try this:
```python
from vedo import *
import vtk

img = Volume(dataurl+"vase.vti").imagedata() # vtkImageData
# plug your img here:
# img = ...

# make sure it is really a vtkImageData
print(isinstance(img, vtk.vtkImageData)) # must print True

vol1 = Volume(img)

# check that the numpy array has meaningful shape
arr = vol1.tonumpy()
print(arr.shape)

vol2 = Volume(arr)
vol2.show()
```

**Comment by charuu** [comment]
It prints true but throws the same error.

True
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
In  [10]:
Line 7:     

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/volume.py, in __init__:
Line 1035:  self.mode(mode).color(c).alpha(alpha).alphaGradient(alphaGradient)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/base.py, in color:
Line 1497:  r,g,b = colors.colorMap(x, name=col, vmin=vmin, vmax=vmax)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/colors.py, in colorMap:
Line 657:   return hex2rgb(cmap[n-iv])

IndexError: list index out of range

**Comment by charuu** [comment]
For array: 

(400, 300, 300)
True
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
In  [12]:
Line 10:    

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/volume.py, in __init__:
Line 1035:  self.mode(mode).color(c).alpha(alpha).alphaGradient(alphaGradient)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/base.py, in color:
Line 1497:  r,g,b = colors.colorMap(x, name=col, vmin=vmin, vmax=vmax)

File /Applications/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/vedo/colors.py, in colorMap:
Line 657:   return hex2rgb(cmap[n-iv])

IndexError: list index out of range

**Comment by marcomusy** [comment]
uhm would you please try:
```
print(type(img), '\n', [img])
```
are you running this in a jupyter session?

**Comment by charuu** [comment]
yes

**Comment by charuu** [comment]
Output : <class 'vtkmodules.vtkCommonDataModel.vtkImageData'> 
 [(vtkmodules.vtkCommonDataModel.vtkImageData)0x155d59648]

**Comment by charuu** [comment]
My aim is to convert the volume rendering in slicer to a 3D Image or a .vtk file. I want to cross check that this library would map the optical properties to the image voxels and we can get the new image ?

**Comment by marcomusy** [comment]
I think you are missing the matplotlib library.
