### ISSUE TITLE
closestPoint method duplicates

### ISSUE THREAD

**Issue by Amin-Fakia** [marcomusy/vedo#452]
is there a way to return the points with no duplicates with this method ? closestPoint()
![image](https://user-images.githubusercontent.com/66644985/132770121-f642cd85-962b-4127-86c0-cbbdf8c3d556.png)
if there is another way that i can code myself i would be gratefull for any help
![image](https://user-images.githubusercontent.com/66644985/132770171-7e2bad17-5dd0-45d5-92e9-e7bac7ca56e1.png)
this is the error i get when i try to compare the values to eliminate the duplicates

**Comment by marcomusy** [comment]
I guess that's not due to `closestPoint()`.
In any case you can either return the points indices (then make a `list(set(idxs))`) or use some numpy np.unique().

**Comment by Amin-Fakia** [comment]
![image](https://user-images.githubusercontent.com/66644985/132844512-f0df004b-d786-42d2-b08b-d1fd68cdfe7b.png)
yeah the issue is that i am trying to loop over some points and find the points that are close to them and some of these points share the same points around them

**Comment by marcomusy** [comment]
Hi, yes - as I said, you should probably use `numpy.unique()`

**Comment by Amin-Fakia** [comment]
Thanks i forgot to add the axes=0 to get multidimensional array xD was confused why it didnt work

**Comment by Amin-Fakia** [comment]
Thanks i forgot to add the axes=0 to get multidimensional array xD was confused why it didnt work
