### ISSUE TITLE
Cell Normals

### ISSUE THREAD

**Issue by hierlm** [marcomusy/vedo#453]
Hello amazing vedo devs,

i need to access the normals of a cell. I looked for any documentation and examples, but only can find the "computeNormals(points=True, cells=True..)" call.

But how can I access the cell normals? Mesh.normals() only shows the normals at points, but not cells.

Thank you very much!

**Comment by marcomusy** [comment]
Thanks! Try this:
`pip install -U git+https://github.com/marcomusy/vedo.git`

then
```python
from vedo import *
s = Sphere([.25,0,0])
m = Mesh([s.points(), s.faces()]) # lets remake it so it has no normals
m.computeNormals(cells=True, points=False).print() # print() shows available arrays
print(m.celldata["Normals"])
```

**Comment by hierlm** [comment]
Thanks for the fast answer! This helped me a lot.
