### ISSUE TITLE
Cannot interactively switch between point data arrays

### ISSUE THREAD

**Issue by kinnala** [marcomusy/vedo#464]
This is my system:
```
_________________________________________________________________
vedo version      : 2021.0.5   https://vedo.embl.es
vtk version       : 9.0.1
python version    : 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]
python interpreter: /home/tom/.conda/envs/vedoenv/bin/python
vedo installation : /home/tom/.conda/envs/vedoenv/lib/python3.8/site-packages/vedo
system            : Linux 5.10.62 posix x86_64

```
Attached is a VTK file with multiple point data arrays. I tried opening it with
```python
from vedo import Plotter
vp = Plotter()
tm = vp.load('fail.vtk')
vp.show([tm]).close()
```
Now according to `h`, I should be able to switch between the data arrays by pressing `4` repeatedly. It prints in the console
```
..active point array set to: skfem:b:left
..active point array set to: skfem:b:right
```
and so on, but nothing happens in the window. I tried making some dirty hacks to `plotter.py` and was able to switch between the arrays, but it was not a clean solution and crashed after each array was shown once. Thus, not PR material.

My guess is that there is something wrong with the logic starting from this line: https://github.com/marcomusy/vedo/blob/master/vedo/plotter.py#L2968

However, I don't know what exactly should be done about it. Maybe there was a change which affected some of the methods used?

Attachment: [fail.zip](https://github.com/marcomusy/vedo/files/7209532/fail.zip)

**Comment by marcomusy** [comment]
Hi Tom,
this is because `load` has no way to know that the file is a unstructured grid. You can try this:
```python
from vedo import *

settings.useDepthPeeling = True  # good for transparent objects
settings.interpolateScalarsBeforeMapping = True # control interpolation behavior

ug = UGrid('fail.vtk')

# make it a polygonal mesh with optional shrinking of faces 
msh = ug.tomesh(shrink=0.8)
msh.print() # print info

print(msh.getPointArray("skfem:b:left")) # note that this will become:
# print(msh.pointdata["skfem:b:left"])

# colorize
# msh.color("blue7").alpha(0.8)
msh.cmap("rainbow", "skfem:b:left").alpha(0.8).addScalarBar("left")

show(msh, axes=1)
```
![Screenshot from 2021-09-22 14-05-42](https://user-images.githubusercontent.com/32848391/134341156-1a43ac84-631e-4e18-af34-f7292b670459.png)

`show()` creates and returns a `Plotter` on the fly but you can create it beforehand, as you have done above.

**Comment by kinnala** [comment]
Thanks, I was not aware of this difference (`UGrid` vs other mesh types). Now it cycles to the second point data array if I press `4`. However, if I press `4` again I get the following error:
```
Traceback (most recent call last):
  File "/home/tom/.conda/envs/vedoenv/lib/python3.8/site-packages/vedo/plotter.py", line 2977, in _keypress
    arnam =  arnames[ia._scals_idx]
IndexError: list index out of range
```

**Comment by kinnala** [comment]
Thanks a lot for your support! I can confirm that it's working.

Background: I included a simple vedo wrapper to the finite element library `scikit-fem` which allows, e.g., the visualization of named boundaries and finite element solutions. We already had a working and tested VTK exporter so I decided to go through a temporary VTK file which is then loaded to vedo as `UGrid`. This VTK file contains any named boundaries as indicator functions: this allows easily checking that the boundary definitions are correct.
```python
m = MeshTet.load('docs/examples/meshes/beams.msh')
m.draw().show()  # draw returns UGrid with an additional attribute show, essentially Plotter.show
```
![screenshot](https://user-images.githubusercontent.com/973268/134462422-b36ec1cf-b7a2-4047-9fb4-fd922430aca3.png)

**Comment by marcomusy** [comment]
Looks cool!
One more thing you can do, if just flagging the boundaries, is to port the point data to cell data:
```python
from vedo import *

ug = UGrid('data/fail.vtk')

# make it a polygonal mesh with optional shrinking of faces 
msh = ug.tomesh(fill=False).mapPointsToCells()
msh.lineWidth(2).lighting('ambient')

# msh.print() # print info
# print(msh.celldata["skfem:b:left"])

msh.cmap("Spectral", "skfem:b:left", on='cells')

show(msh, axes=1)
```
![Screenshot from 2021-09-23 11-42-26](https://user-images.githubusercontent.com/32848391/134486321-0c2ecad6-4839-44bf-8abc-3bbbdec2029d.png)

I've also added a fix in my local so that while pressing `4` the cmap stays the same (now it's "rainbow").
I plan to make a release in ~ 1 week.
