### ISSUE TITLE
Export the mesh material only

### ISSUE THREAD

**Issue by Amin-Fakia** [marcomusy/vedo#466]
Hello,
Is there a way to export the material and mesh as seperate files ? to give it more context: i am trying to import my model into unity 
![image](https://user-images.githubusercontent.com/66644985/134422717-bc4f9063-7f14-4984-baa6-9a5dab7af1d9.png)

**Comment by Amin-Fakia** [comment]
material(MTL) or texture it doesnt really matter

**Comment by marcomusy** [comment]
You may use VTK to write the polydata to file, which can be accessed from vedo as `mymesh.polydata()`.
Check out : https://vtk.org/doc/nightly/html/classvtkOBJWriter.html

**Comment by Amin-Fakia** [comment]
I dont know if you have worked with unity before ? but do you think it would be possible to some how extract the model with the interpolated data and view it in unity ? i am try to think of a way so i dont have to write a parser from scratch, 
P.S. : the reason i need to do it unity is that i want to visualize the project in AR, i have essentially managed to export the file as .ply import it in blender and export it as .fbx to be able to import it in unity

**Comment by marcomusy** [comment]
uhm, no sorry... i'm not familiar with unity!

**Comment by Amin-Fakia** [comment]
is there a way to export object files to .GLTF ? 
thx for your help

**Comment by marcomusy** [comment]
Hi, I will implement it in the next release (1-2 weeks), meanwhile you can extract the polygonal data from the native vtk reader:
https://vtk.org/doc/nightly/html/classvtkGLTFReader.html 
eg
```python
reader = vtk.vtkGLTFReader()
...
poly = reader.GetOuput()
msh = vedo.Mesh(poly)
...
```

**Comment by marcomusy** [comment]
OUCH! sorry you said export not import...
I need to look into it!
