### ISSUE TITLE
Bas Relief from 3D Models 

### ISSUE THREAD

**Issue by sonumathur** [marcomusy/vedo#467]
Hi @marcomusy 
What are the methods in vedo to convert a 3D model to a Bas relief Model by compressing the depth of model as shown in 
[https://www.youtube.com/watch?v=9zurRXrntJs](url)

I want to transfer a 3D model to Planer surface as very low depth as 
![G4](https://user-images.githubusercontent.com/60248559/134478508-a0e2ef2c-3862-4bd7-a5b8-b5feff51e7c4.jpg)
to
![IMG0027A](https://user-images.githubusercontent.com/60248559/134478553-ad2a3788-fd59-4d65-8d72-25b1a5be0e84.jpg)

**Comment by marcomusy** [comment]
It is not so straightforward. You can work out a depth map porting your image to a numpy array and then make a mesh out of it.
Check out: https://github.com/marcomusy/vedo/blob/master/examples/basic/picture2mesh.py
