### ISSUE TITLE
Coloring a mesh based on its point coordinates

### ISSUE THREAD

**Issue by kuzand** [marcomusy/vedo#468]
Is it possible to color a mesh based on its point coordinates as in the following picture:

![Screenshot from 2021-09-23 20-05-39](https://user-images.githubusercontent.com/15230238/134552287-977dba7a-50b7-43e2-8563-707f1af86cc0.png)

I need this to visualize correspondence between two shapes by color.

**Comment by marcomusy** [comment]
Yes, there are many examples for it. Do
`pip install -U git+https://github.com/marcomusy/vedo.git`

then e.g.:
```python
from vedo import *
msh = Mesh(dataurl+"man.vtk")
points = msh.points()
msh.pointdata["myxcoords"] = points[:,0]
msh.cmap("coolwarm", "myxcoords")
show(msh, axes=1)
```
![Screenshot from 2021-09-23 19-25-21](https://user-images.githubusercontent.com/32848391/134555085-3a2f688f-9fdb-4b4d-b164-0e9d7549088a.png)

there are many more examples in `examples/basic`.

**Comment by kuzand** [comment]
@marcomusy In your example the color change is in the x-direction only, but in the example pictures I provided the change is actually in all the directions. This is needed because every point should have different color. So I was wondering if it's possible to do it.

**Comment by marcomusy** [comment]
Yes, but obviously you need to have the information of what point of one mesh corresponds to the one in the other mesh.
If you don't have such information you may try to morph one mesh onto the other based on a few points that you pick manually ... but that's definitely more complicated.

**Comment by kuzand** [comment]
Even if we have one mesh I think it's possible to color it in this way by simply taking the coordinates of each point (x,y,z) as vertex color value (r,g,b). But It's not clear to me how to do it with vedo. The `mesh.color()` gives just one color, but how to set the color for each vertex independently?

**Comment by marcomusy** [comment]
you can colorize mesh cells but not vertices, so you can do something like this:
```python
from vedo import *
import numpy as np

msh = Sphere(quads=True).pos(1,1,1)
arr = msh.points()*126

# make sure it's in range 0-255
print(np.min(arr, axis=0),np.max(arr, axis=0))
arr = arr.astype(np.uint8)

msh.pointdata["myxcoords"] = arr
msh.mapPointsToCells().print()

msh.celldata.select("myxcoords")

show(msh, axes=1)
```
<img width="295" alt="Screenshot 2021-09-24 at 00 29 16" src="https://user-images.githubusercontent.com/32848391/134592336-a34f7841-820a-4354-acfa-cf357ffbc2ac.png">

**Comment by kuzand** [comment]
For some reason I am getting the error "AttributeError: 'Mesh' object has no attribute 'pointdata'".

**Comment by marcomusy** [comment]
You have to do
`pip install -U git+https://github.com/marcomusy/vedo.git`
