### ISSUE TITLE
Automatic transformation matrix

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#471]
Hi @marcomusy,

I have a couple of point clouds (of a similar object but different type, plains in this case) which are randomly positioned. Now I would like to find the transformation matrix so that all the point clouds to have the same orientation/translation:
```
from glob import glob
import natsort
import vedo as vd

pcdFiles = natsort.natsorted(glob('**/*.xyz', recursive=True))

for i, pcdFile in enumerate(pcdFiles):
    print(pcdFile)
    s = vd.Points(pcdFile).alpha(0.2)
    vd.show(s, axes=8)
```

Target position (airplane_0000.xyz):
![image](https://user-images.githubusercontent.com/10189018/135117222-b2654e4d-8cab-4af1-89a9-419716e38088.png)

Transformation to be found:
![image](https://user-images.githubusercontent.com/10189018/135117417-084a7124-0972-4b00-8fc5-752c11bba48a.png)
![image](https://user-images.githubusercontent.com/10189018/135117516-4c3532b9-55ec-47d3-aa13-6b947555ba65.png)
![image](https://user-images.githubusercontent.com/10189018/135117541-70ab9d98-e2c1-49ea-ae27-f77369cee250.png)

I am not sure how easy this can be done, possibly using a shape similarity metric or something similar.

[testing_samples.zip](https://github.com/marcomusy/vedo/files/7245552/testing_samples.zip)

**Comment by marcomusy** [comment]
Hi @ttsesm , that should be easy. there are many examples about aligning things in vedo, see
`examples/basic/align*.py`

**Comment by ttsesm** [comment]
Well in principle it seems easy but it is not really. From the examples the `procrustesAlignment` method demands to have the same amount of point which I do not. On the other hand the Iterative Closest Point algorithm with `alignTo`does not seem to work perfectly.

![image](https://user-images.githubusercontent.com/10189018/135227968-2da063c2-3cf5-43f6-bf8b-edcfb37e6bc5.png)
![image](https://user-images.githubusercontent.com/10189018/135228093-0a691253-b557-4e05-9c8e-23b90ee4d815.png)
![image](https://user-images.githubusercontent.com/10189018/135228278-0168c9d4-e430-4e59-a25e-51fd6369f66a.png)

**Comment by marcomusy** [comment]
By experience there is no blind/automatic alignment algorithm that works 100% of the times on arbitrary point clouds.
You need to start from a reasonable initial alignment. In that case the `alignTo()` will do the rest of the job..

Otherwise you might need to loop over possible initial alignments/rotations and maybe check hausdorf distance e.g.
```python
        vd.show(template, s, f"Before {template.hausdorffDistance(s)}", at=0, N=2, axes=1)
        vd.show(aligned_pts1, template,
                f"After {template.hausdorffDistance(aligned_pts1)}", 
                at=1, interactive=True).close()
```
<img width="795" alt="Screenshot 2021-09-29 at 10 54 57" src="https://user-images.githubusercontent.com/32848391/135236450-b28e4cb0-1fab-417d-983d-5fc256779d15.png">

**Comment by ttsesm** [comment]
Thanks Marco, interesting note regarding the hausdorf distance (I was not aware of it, I knew the chamfer distance) I found also an alternative to ICP which takes into account normals as well https://laempy.github.io/pyoints/tutorials/icp.html#NICP-algorithm.  This might also get into hand.

**Comment by marcomusy** [comment]
you can also compute normals for pure pointclouds with `myptcloud.computeNormalsWithPCA()`.
i don't know how well it works, i've never tested it throughly..
