### ISSUE TITLE
Calculating a volume of a custom mesh using mesh.volume() doesn't work properly

### ISSUE THREAD

**Issue by LukaBlagojevic** [marcomusy/vedo#473]
Hi, I'm currently trying to build tubes and tubelike meshes, that might branch, etc. (I'm aware that there is a Tube shape in the Vedo library). 
I want to cut them and cap them at the places where they have opened up after cutting.  
Additionally, I would like to calculate the total volume enclosed by the mesh before and after the procedure. 
Here's an example below:

```
from vedo import *
import math

r = 1
coord_start_z = 0
coord_end_z = 1
angle = 0
number_of_vertices = 520
start_x = 0
start_y = 0
coordinates_all = []


for i in range(0,number_of_vertices):
    angle = (i/number_of_vertices)*2*3.141592653589793
    coord_x = start_x + r * math.cos(angle)
    coord_y = start_y + r * math.sin(angle)

    coordinates_all.append((coord_x,coord_y,coord_start_z))
    coordinates_all.append((coord_x,coord_y,coord_end_z))

faces = []
faces_base_start = [i for i in range(0,number_of_vertices*2) if i%2 == 0]
faces_base_end = [i for i in range(0,number_of_vertices*2) if i%2 != 0]
for i in range(0,number_of_vertices):
        faces_start = []
        if i + 1 == number_of_vertices:
            faces.append((i*2,i*2+1,1,0))
        else:
            faces.append((i*2,i*2+1,i*2+3,i*2+2))
        
faces.append(tuple(faces_base_start))
faces.append(tuple(faces_base_end))

tube =  Mesh([coordinates_all,faces])
cut_tube = tube.clone().cutWithPlane(origin=(0, 0, 0), normal=(1, 0, 0))
capped_cut_tube = cut_tube.clone().cap()
capped_cut_tube.c('r',alpha=0.5)

print('Volume of the original tube is: ' + str(tube.volume()))
print('Volume of the cut and capped tube is: ' + str(capped_cut_tube.volume()))

show(tube,axes=1,at=0,shape=(2,1))
show(capped_cut_tube,axes=1,at=1,shape=(2,1))
```
Unfortunately, the volume of the first tube is computed as 0 (it should be around 3.141592) and the second one is incorrectly calculated as well (0.8742, even though the volume is roughly halved by the split). 

What could be the issue here?

**Comment by marcomusy** [comment]
You need to make the meshes triangulr to compute volumes and areas.
The volume output is pretty strange because a simple example gives the right result:
```python
from vedo import Tube, show
c = Tube([[0,0,0],[0,0,1]], res=36).triangulate().lw(0.1)
print(c.area(),
      c.volume(),
      c.cutWithPlane().cap().volume(),
)
show(c, c.labels('id'),axes=1)
```

> 12.526547873840881 3.1256671980047477 1.56283359898723


![Screenshot from 2021-10-01 00-09-33](https://user-images.githubusercontent.com/32848391/135536648-fdbf4488-1e19-4d86-aa76-4978a52b4be2.png)

my guess is that something is going wrong with the face orientations

**Comment by marcomusy** [comment]
oh yes, that's why! The way you defined your faces, after `triangulate()` becomes:

![Screenshot from 2021-10-01 00-25-09](https://user-images.githubusercontent.com/32848391/135538130-4d660c9f-7f78-4677-91b5-2e8a02ea955f.png)

So you have [0,1,2] clockwise, then [1,2,3] anticlockwise ...etc, that's why volume return about 0

**Comment by marcomusy** [comment]
This works:
```python
from vedo import Mesh, merge, show
import numpy as np

r = 1
coord_start_z = 0
coord_end_z = 1
angle = 0
number_of_vertices = 20
start_x = 0
start_y = 0
coordinates_all = []

for i in range(0, number_of_vertices):
    angle = (i / number_of_vertices) * 2 * np.pi
    coord_x = start_x + r * np.cos(angle)
    coord_y = start_y + r * np.sin(angle)
    coordinates_all.append((coord_x, coord_y, coord_start_z))
    coordinates_all.append((coord_x, coord_y, coord_end_z))

n = 2*number_of_vertices
faces = [[i, i+1, i+3, i+2] for i in range(0, n-2, 2)]
faces.append([n-2, n-1, 1, 0])

tube = Mesh([coordinates_all, faces]).lw(1).triangulate()

# if you want to cap you need to reverse the face orientations
# cap = tube.cap(returnCap=True).reverse().triangulate()
# tube = merge(tube, cap).clean()

print(tube.area(),
      tube.volume(),
      tube.clone().cutWithPlane().cap().volume(),
      # tube.faces(),
)
show(tube, tube.labels('id'), axes=1)
```

**Comment by LukaBlagojevic** [comment]
Thanks!

**Comment by LukaBlagojevic** [comment]
Hey Marco, I have another, somewhat related question. So I'm building on this example of this "custom" tube that I've made and it was for this reason - I want to create a connected tube that can branch (for example, split a tube into two tubes). 
This is useful for neuron representation and computing its volume. 

So my question is this: Given the merging of meshes that I've had, how do I remove the interior, so I get a hollow mesh, that's capped in the end? More specifically, how do I remove/cut the "interior" mesh that's created at the overlap of two branching tubes?

`from vedo import Mesh, merge, show
import numpy as np

r = 1
coord_start_z = 0
coord_end_z = 1
angle = 0
number_of_vertices = 30
start_x = 0
start_y = 0
coordinates_all = []

for i in range(0, number_of_vertices):
    angle = (i / number_of_vertices) * 2 * np.pi
    coord_x = start_x + r * np.cos(angle)
    coord_y = start_y + r * np.sin(angle)
    coordinates_all.append((coord_x, coord_y, coord_start_z))
    coordinates_all.append((coord_x, coord_y, coord_end_z))

n = 2*number_of_vertices
faces = [[i, i+1, i+3, i+2] for i in range(0, n-2, 2)]
faces.append([n-2, n-1, 1, 0])
tube = Mesh([coordinates_all, faces]).lw(1).triangulate()

coord_start_z_branch = 1
coord_end_z_branch = 2
end_x_1 = -1
end_y_1 = -1
end_x_2 = 1
end_y_2 = 1
coordinates_all_1 = []
coordinates_all_2 = []
for i in range(0, number_of_vertices):
    angle = (i / number_of_vertices) * 2 * np.pi
    coord_x_start_1 = start_x + r * np.cos(angle)
    coord_y_start_1 = start_y + r * np.sin(angle)
    coord_x_start_2 = start_x + r * np.cos(angle)
    coord_y_start_2 = start_y + r * np.sin(angle)
    coord_x_end_1 = end_x_1 + r * np.cos(angle)
    coord_y_end_1= end_y_1 + r * np.sin(angle)
    coord_x_end_2 = end_x_2 + r * np.cos(angle)
    coord_y_end_2 = end_y_2 + r * np.sin(angle)
    coordinates_all_1.append((coord_x_start_1, coord_y_start_1, coord_start_z_branch))
    coordinates_all_1.append((coord_x_end_1, coord_y_end_1, coord_end_z_branch))
    coordinates_all_2.append((coord_x_start_2, coord_y_start_2, coord_start_z_branch))
    coordinates_all_2.append((coord_x_end_2, coord_y_end_2, coord_end_z_branch))


faces_1 = [[i, i+1, i+3, i+2] for i in range(0, n-2, 2)]
faces_1.append([n-2, n-1, 1, 0])
tube_1 = Mesh([coordinates_all_1, faces_1]).lw(1).triangulate()

faces_2 = [[i, i+1, i+3, i+2] for i in range(0, n-2, 2)]
faces_2.append([n-2, n-1, 1, 0])
tube_2 = Mesh([coordinates_all_2, faces_2]).lw(1).triangulate()

final_tube = merge(tube, tube_1,tube_2).clean().alpha(0.8)
# if you want to cap you need to reverse the face orientations
cap = final_tube.cap(returnCap=True).triangulate()
final_tube = merge(final_tube, cap).clean()
#tube_cut = final_tube.clone().cutWithPlane().cap()

print(final_tube.area(),
      final_tube.volume(),
     final_tube.clone().cutWithPlane().cap().volume())
      #tube.faces())
      
show(final_tube , axes=1,at=0, N=1)`

I hope it's clear what I'm talking about.
