### ISSUE TITLE
Delaunay triangulation from voronoi tessellation

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#475]
Hello @marcomusy, 
I would like to know how Delaunay triangulation can be applied to find the connectivity of 
the cells formed by voronoi tessellation in vedo.

The following is the code that I'm using to generate voronoi cells using the scipy library. I'd like to do this in vedo
but I am not sure how to do it.

```
    import numpy as np
    from scipy.spatial import Voronoi, voronoi_plot_2d
    import shapely.geometry
    import shapely.ops
    
    points = np.random.random((20, 2))
    vor = Voronoi(points)
    fig = voronoi_plot_2d(vor)
    plt.show()

```
I would like to know if voronoi tessellation can be generated in vedo and find the cell connectivity by applying
Delaunay triangulation. Here, I am actually looking at applying this to biological cells to find how the biological cells are connected with each other.

Thanks a lot

**Comment by marcomusy** [comment]
Hello @DeepaMahm 

Yes, have a look at: https://github.com/marcomusy/vedo/blob/master/examples/basic/voronoi.py

![Screenshot from 2021-10-02 12-42-38](https://user-images.githubusercontent.com/32848391/135714780-7af865ad-069f-43ac-b93a-ee26a8ef12c0.png)

**Comment by DeepaMahm** [comment]
@marcomusy ,

Thanks a lot. Could you please help me in understanding how  Delaunay triangulation (DT) can be constructed on the Voronoi cells to find how the Voronoi cells are connected?

**Comment by marcomusy** [comment]
Not an expert... I guess you can overlay the DT with `delaunay2D`, which is the "dual" of voronoi, and then use `examples/basic/connVtx.py` to link the voronoi cells.
You maybe still left with the problem that triangulation is a bit arbitrary, so you may end up with different connectivity matrices for very similar point configurations.

**Comment by DeepaMahm** [comment]
@marcomusy 

I see an attribute error while running the code snippet posted above


    vor = vtk.vtkVoronoi2D()
AttributeError: module 'vtk' has no attribute 'vtkVoronoi2D'

**Comment by marcomusy** [comment]
Try `pip install vtk -U`

**Comment by DeepaMahm** [comment]
Thanks a lot! works now :)

**Comment by DeepaMahm** [comment]
@marcomusy ,

Excuse me for another question
I tried 

```
from vedo import Point, Points, voronoi, show
from vedo.pointcloud import delaunay2D
import numpy as np

# voronoi
points = np.random.random((20, 2))
pts = Points(points).clean(0.02) # impose a min distance of 2%
vor = voronoi(pts, pad=0.01)
lab = vor.labels("VoronoiID", cells=True, scale=0.01)
# lab = None
# show(pts, vor, lab, __doc__, axes=1)

# delaunay triangulation
dly = delaunay2D(pts, mode='xy').c('w').lc('o').lw(1)
# show(pts, vor, pts.labels('id').z(0.01), dly)

# visualize
index = 10 # pick one point
pt = pts.points(index)
vtxs = dly.connectedVertices(index, returnIds=False)

apt = Point(pt, c="r", r=15)
cpts = Points(vtxs, c="blue", r=15)
show(vor, dly, apt, cpts, __doc__, bg='bb').close()

```
But I don't see the right set of vertices connected to `apt`
![Untitled](https://user-images.githubusercontent.com/29662579/135755373-579bca32-9318-4de6-970e-230654e53212.png)

I am not sure if I am doing something wrong here

**Comment by marcomusy** [comment]
`pt = pts.points(index)` ->  `pt = dly.points(index)`
VTK scrambles the order of the points for some strange reason.

Try `mode='scipy'`:

```python
from vedo import Point, Points, voronoi, show
from vedo.pointcloud import delaunay2D
import numpy as np
np.random.seed(0)

# voronoi
points = np.random.random((10, 2))
pts = Points(points)
vor = voronoi(pts, pad=0.01).wireframe()

# delaunay triangulation
dly = delaunay2D(pts, mode='scipy').c('w').wireframe()

# visualize
index = 5 # pick one point
pt = dly.points(index)
vtxs = dly.connectedVertices(index, returnIds=False)

print("check order", points, dly.points())

lab = dly.labels("id", scale=0.02, c='w')

apt = Point(pt, c="r", r=15)
cpts = Points(vtxs, c="blue", r=15)

show(vor, dly, apt, cpts, lab, bg='bb').close()
```
![Screenshot from 2021-10-03 17-42-57](https://user-images.githubusercontent.com/32848391/135761476-e3980241-eb77-4be9-8e59-324161106eba.png)

**Comment by DeepaMahm** [comment]
@marcomusy 

In the code shared above
```
from vedo import Point, Points, voronoi, show
from vedo.pointcloud import delaunay2D
import numpy as np
np.random.seed(0)

# voronoi
points = np.random.random((10, 2))
pts = Points(points)
vor = voronoi(pts, pad=0.01).wireframe()

```
we specified the centers of Voronoi cells i.e. coordinate information in `pts`.

I am trying to import the topology information of the biological cell population generated from a multicell modeling tool.
I have the coordinate information of Voronoi cells ( biological cells represented as Voronoi cells ) in an [xml file](https://github.com/DeepaMahm/misc/blob/master/cellpopulation.xml) generated from [Morpheus](https://morpheus.gitlab.io/#about). The xml node
for each Voronoi cell (`<Cell id="1">`)has the following info
```
<Center>72.076388889,81.409722222,0</Center>
<Nodes>68, 75, 0;69, 75, 0;70, 75, 0;71, 75, 0;67, 76, 0;68, 76, 0;69, 76, 0;70, 76, 0;71, 76, 0;72, 76, 0;73, 76, 0;74, 76, 0;75, 76, 0;76, 76, 0;67, 77, 0;68, 77, 0;69, 77, 0;70, 77, 0;71, 77, 0;72, 77, 0;73, 77, 0;74, 77, 0;75, 77, 0;76, 77, 0;77, 77, 0;78, 77, 0;79, 77, 0;66, 78, 0;67, 78, 0;68, 78, 0;69, 78, 0;70, 78, 0;71, 78, 0;72, 78, 0;73, 78, 0;74, 78, 0;75, 78, 0;76, 78, 0;77, 78, 0;78, 78, 0;66, 79, 0;67, 79, 0;68, 79, 0;69, 79, 0;70, 79, 0;71, 79, 0;72, 79, 0;73, 79, 0;74, 79, 0;75, 79, 0;76, 79, 0;77, 79, 0;78, 79, 0;67, 80, 0;68, 80, 0;69, 80, 0;70, 80, 0;71, 80, 0;72, 80, 0;73, 80, 0;74, 80, 0;75, 80, 0;76, 80, 0;77, 80, 0;78, 80, 0;67, 81, 0;68, 81, 0;69, 81, 0;70, 81, 0;71, 81, 0;72, 81, 0;73, 81, 0;74, 81, 0;75, 81, 0;76, 81, 0;77, 81, 0;78, 81, 0;67, 82, 0;68, 82, 0;69, 82, 0;70, 82, 0;71, 82, 0;72, 82, 0;73, 82, 0;74, 82, 0;75, 82, 0;76, 82, 0;77, 82, 0;67, 83, 0;68, 83, 0;69, 83, 0;70, 83, 0;71, 83, 0;72, 83, 0;73, 83, 0;74, 83, 0;75, 83, 0;76, 83, 0;77, 83, 0;68, 84, 0;69, 84, 0;70, 84, 0;71, 84, 0;72, 84, 0;73, 84, 0;74, 84, 0;75, 84, 0;76, 84, 0;68, 85, 0;69, 85, 0;70, 85, 0;71, 85, 0;72, 85, 0;73, 85, 0;74, 85, 0;75, 85, 0;76, 85, 0;68, 86, 0;69, 86, 0;70, 86, 0;71, 86, 0;72, 86, 0;73, 86, 0;74, 86, 0;75, 86, 0;76, 86, 0;69, 87, 0;70, 87, 0;71, 87, 0;72, 87, 0;73, 87, 0;74, 87, 0;75, 87, 0;76, 87, 0;69, 88, 0;70, 88, 0;71, 88, 0;72, 88, 0;73, 88, 0;74, 88, 0;75, 88, 0;70, 89, 0;71, 89, 0;72, 89, 0</Nodes>
```

and it also has grid size (Size ="182,182,0) which can be used in vedo `Grid`

> Center: cell center, center of mass, just informative
> Nodes: list of lattice nodes occupied by the cell (lattice coordinates!)
> 



I can use the value assigned to the center attribute in `pts` field of vedo. But I am not sure how the lattice coordinates occupied by each Voronoi cell can be specified in vedo. Could you please help me with this?


Kindly let me know if I have to add some more details here.

**Comment by marcomusy** [comment]
Hi,

>  I am not sure how the lattice coordinates occupied by each Voronoi cell can be specified in vedo

I don't understand what "specify" means. Those are just coordinates.

- To create a `Mesh` in vedo you need l list of vertices (points) and their index connectivity (faces).

- To associate data to a point cloud you can simply use `mypoints.pointdata['myarray'] = mynumpyarray`.
You can also merge different `Points` objects into one. This will automatically maintain the associated data (for example the constant cellid that one cloud belongs to).

**Comment by DeepaMahm** [comment]
Hi,
`
Nodes: list of lattice nodes occupied by the cell (lattice coordinates!)`

From what I understand, from the description provided in the documentation of Morpheus, the coordinates in `Nodes` field define the size of the voronoi cell. 

 When we specify just the points
`vor = voronoi(pts, pad=0.01).wireframe()
` I am not sure how the size of each voronoi cell is defined.

Alternatively, I also tried to export the cell population in [this vtk file](https://github.com/DeepaMahm/misc/blob/master/plot1_000001.vtk).  I could load and visualize this 
vtk file in Paraview and in vedo I tried the following
```

from vedo import loadStructuredPoints, show
from vedo import load
# g = load("plot1_000001.vtk")
ugrid = loadStructuredPoints("plot1_000001.vtk")
print(ugrid)
print(ugrid.GetNumberOfCells())
print(ugrid.GetCellData())
show(ugrid) # this isn't correct

```

I am not sure what's the right way to plot in vedo

**Comment by marcomusy** [comment]
Try:
```python
from vedo import Mesh, loadStructuredPoints, geometry, show

strpts = loadStructuredPoints("plot1_000001.vtk")

msh = Mesh(geometry(strpts)).lw(0.1)

msh.print()
print(msh.pointdata["cell.id"])

show(msh, axes=1)
```
![Screenshot from 2021-10-16 17-45-54](https://user-images.githubusercontent.com/32848391/137593804-046106ae-56d0-4c32-a1a1-0a00a715d17f.png)

**Comment by marcomusy** [comment]
that's easy, you can compute the center of mass of each voronoi cell:
```python
#...

settings.interpolateScalarsBeforeMapping = False

cids = msh.pointdata["cell.id"].astype(int)
uids = np.unique(cids)

coords = msh.points()
means = []
for u in uids:
    m = np.mean(coords[cids==u], axis=0)
    means.append(m)

cellpts = Points(means)

show(msh, cellpts, axes=1)
```
![Screenshot from 2021-10-16 18-51-31](https://user-images.githubusercontent.com/32848391/137595753-55ea4187-b565-4523-b19a-9ba188dabaf1.png)

**Comment by marcomusy** [comment]
that's simple:
```
myvoronoymesh.cmap('jet', mycellarray, on='cells')
```

**Comment by DeepaMahm** [comment]
@marcomusy,
Thank you.

 I tried

```
    strpts = loadStructuredPoints('input.vtk')
    msh = geometry(strpts).lw(0.1)

    # step 1
    cids = msh.pointdata["cell.id"].astype(int)
    uids = np.unique(cids)
    print('uids:',len(uids))
    coords = msh.points()

    # step 2
    means = []
    for u in uids:
        m = np.mean(coords[cids == u], axis=0)
        means.append(m)
    cellpts = Points(means)
    vor = voronoi(means, method='vtk').c('k').z(1).lw(0.5).wireframe() #.shrink().extrude()
    values = range(0, len(means)) #random.randint(len(means))
    vor.cmap('jet', values, on='cells')
    show(vor, bg='bb')

```
[input.vtk](https://github.com/DeepaMahm/misc/blob/master/input.vtk)

![image](https://user-images.githubusercontent.com/29662579/149288064-1f785dd0-6e47-4a11-8a81-1ccbb60492f4.png)

The cmap is assigned to the  boundaries of the polygon , I am not sure how to color the cells.
I tried `  msh = geometry(strpts).lw(0.1)  msh.cmap('jet', values, on='cells')`  isn't the right thing to do, I understand.

Could you please have a look and suggest how to color the cells?

**Comment by marcomusy** [comment]
simply replace `.wireframe(False)`

<img width="216" alt="Screenshot 2022-01-14 at 01 14 58" src="https://user-images.githubusercontent.com/32848391/149429399-34c88a47-a00c-4225-aeda-d6d5259dad27.png">
