### ISSUE TITLE
Installing Vedo: Is the Cryptography package really necessary?

### ISSUE THREAD

**Issue by CakeUser321** [marcomusy/vedo#476]
Hi,

for installing vedo with pip, one apparently needs the cryptography package. This package seems to be sometimes a bit difficult to install. I needed quite some time to install the VC++ Build Tools, Rust and after that it was additionaly necessary to set the environment variables LIB and INCLUDE in my python IDE to the directories of OpenSSL. Is this cryptography package really necessary for vedo? I think that the installation would be much easier without it.

**Comment by marcomusy** [comment]
Hi, I guess VTK can depend on that, not vedo... but vedo depends on VTK.
I'm not sure why VTK needs that.

what is your OS? Try
`vedo --info`

**Comment by CakeUser321** [comment]
...>vedo --info
_________________________________________________________________
vedo version      : 2021.0.5   https://vedo.embl.es
vtk version       : 9.0.3
python version    : 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
python interpreter: C:\...\Scripts\python.exe
vedo installation : C:\...\lib\site-packages\vedo
system            : Windows 10 nt AMD64

**Comment by RubendeBruin** [comment]
(as a work-around you could install from conda / mamba. Conda will supply pre-build packages such that no compilation is required.)
