### ISSUE TITLE
Overlay a network over voronoi testellation

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#478]
Hi @marcomusy,

I would like to create a geometry like the following in vedo.

[source](https://hatarilabs.com/ih-en/tutorial-to-create-a-geospatial-voronoi-sh-mesh-with-python-scipy-and-geopandas)
![image](https://user-images.githubusercontent.com/29662579/136667355-f8895bb1-6641-438d-aa73-cc743470911c.png)

For this, I would like to use vedo
1.  create a network like this https://github.com/marcomusy/vedo/issues/341
2. overlay a Voronoi tessellation on the network in step 1. https://github.com/marcomusy/vedo/issues/475
3. find the index of the Voronoi cells through which the network edge traverses

I am not sure how to do step 3. Could you please give some ideas and help me with this?

Thanks a lot for all your support

**Comment by DeepaMahm** [comment]
Ahh, thanks a ton! this clarifies my doubts.

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

I have an example in which a network is overlayed on voronoi cells
![image](https://user-images.githubusercontent.com/29662579/137636474-c8ed3455-516f-4d85-a020-7f65b6364aae.png)


```

import matplotlib.pyplot as mplt
import networkx as nx
from vedo import loadStructuredPoints, geometry,\
    show, settings, Points, voronoi, Lines, Plotter
settings.interpolateScalarsBeforeMapping = False
from collections import OrderedDict

G = nx.OrderedGraph()
edges = [(0, 7), (0, 3), (1, 2), (1, 3), (2, 6), (3, 6), (4, 5), (4, 6), (5, 7)]
G.add_edges_from(edges)

pos = OrderedDict()
pos = {0:[64, 10], 1:[81, 78], 2:[17, 88], 3:[23, 33], 4:[40, 18], 5:[100, 63],  6:[12, 55], 7:[59, 50]}
nx.set_node_attributes(G, pos, 'pos')
nx.draw(G, with_labels=True)
mplt.show()
pts = [pos[pt] for pt in sorted(pos)]
lines = [(pos[t], pos[h]) for t, h in G.edges()]
edg = Lines(lines)

pts = Points(pts, c='k', alpha=0.5)
label = [str(node) for node in sorted(G.nodes)]
labs = pts.labels(label, font='VictorMono', c='k').addPos(0.05, 0, 0.5)
plt = Plotter(N=1, size=(100, 100))
strpts = loadStructuredPoints("plot1_000001.vtk")
msh = geometry(strpts).lw(0.1)
msh.print()

cids = msh.pointdata["cell.id"].astype(int)
uids = np.unique(cids)
coords = msh.points()
means = []
for u in uids:
    m = np.mean(coords[cids==u], axis=0)
    means.append(m)
cellpts = Points(means)

vor = voronoi(means, method='vtk').c('k').z(1).lw(0.1).wireframe()
show(pts, edg, labs, msh.lw(0), cellpts, vor, axes=1)
```

I would like to find the ids/index of voronoi cells through which the edge (1,2) and (1,3) passes. 
I am not sure what's the best way to do this. I would like to try the following:
1. find the coordinates of all points that form the line connecting edge (1,2) 
2. find the coordinates of all points that lie within each voronoi cell  ( how to get this information in vedo?)
3. map coordinates that lie on edge e.g. (1,2) to voronoi cell id through which the edge passes

I would like to know if this looks ok or if is there a better way to do this.

Many thanks

**Comment by marcomusy** [comment]
..oh, an idea could be that you make a `Line(p1,p2, res=100)` with a resolution , then for each of the 100 points you query the closest point of the voronoi centers with `.closestPoint(returnPointId=True)` and then retrieve the cell id from that.

**Comment by DeepaMahm** [comment]
Hi,

Thanks so much.  Instead of .closestPoint(returnPointId=True) I tried `returnCellId=True` and this works great :)


```
p1 = pos[1]
p2 = pos[2]
edg12 = Line(p1, p2, res=100)
edg12_pts = edg12.points()
for pt in edg12_pts:
    print('closestPoint', vor.closestPoint(pt, returnCellId=True))

```
