### ISSUE TITLE
How to get the coordinate of area points  with a closed line?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#479]
How to get the coordinate of area points  with a closed line?
![image](https://user-images.githubusercontent.com/28825816/136676072-dee765f7-87c2-4051-aadf-8afedc4a5375.png)
https://github.com/marcomusy/vedo/blob/master/examples/advanced/spline_draw.py
After load a picture, I draw a closed line and I tend to get all coordinate of the area not the spline.
Thanks

**Comment by marcomusy** [comment]
You can simply mesh that area, In the example above add these lines:
```python
def update():
    global spline, points
    plt.remove([spline, points])
    points = Points(cpoints, r=8).c('violet').alpha(0.8)
    spline = None
    if len(cpoints)>2:
        spline = Spline(cpoints, closed=True).c('yellow').alpha(0.8)
        spline = spline.tomesh(50)
        print(spline.area())
    plt.add([points, spline])
```
![Screenshot from 2021-10-10 12-24-54](https://user-images.githubusercontent.com/32848391/136691777-f0de406f-de47-4094-8aa3-c52f31e3d43d.png)
note that the spline must be drawn anticlockwise (or else use `invert=True`)
