### ISSUE TITLE
Offeset Upper Surface 

### ISSUE THREAD

**Issue by padam1kumar** [marcomusy/vedo#489]
can we copy upper surface only to mesh leaving the inside surface
![Temp](https://user-images.githubusercontent.com/60621551/138064496-3be3dcc0-05ce-46f0-a115-c85bea7e77a6.jpg)

[rosette5.zip](https://github.com/marcomusy/vedo/files/7379803/rosette5.zip)

I require only outer surface.

**Comment by marcomusy** [comment]
I already see only an outer surface (flagged with 9 ids).

**Comment by padam1kumar** [comment]
The file attached is a 3D .obj file and has many face inside which are causing error. Provide a method to copy only outer surface information.
