### ISSUE TITLE
"distanceToMesh()" not working properly when meshes are both far away

### ISSUE THREAD

**Issue by LukaBlagojevic** [marcomusy/vedo#495]
Hi, 

I'm trying to compute the distance between two meshes, but I found that this issue occurs even with the two spheres. In this case, there is no issue:

```python
from vedo import Sphere, show
s1 = Sphere(r=12896.0)
s2 = Sphere(pos = (80146.7021484375, 21942.59130859375, 15899.5),r = 12840.5, c='white', alpha=0.4)

s1.distanceToMesh(s2, signed=True, negate=False)

s1.addScalarBar(title='Signed\nDistance')

print(s1.pointdata["Distance"])
show(s1, s2, __doc__ , axes=11).close()
```

As soon as I change the origin of the first sphere, s1.pointdata['Distance'] is an empty list, no distances are computed:

```python
from vedo import Sphere, show
s1 = Sphere(pos = (29744.0, 21995.87841796875, 15836.0), r=12896.0)
s2 = Sphere(pos = (80146.7021484375, 21942.59130859375, 15899.5),r = 12840.5, c='white', alpha=0.4)

s1.distanceToMesh(s2, signed=True, negate=False)

s1.addScalarBar(title='Signed\nDistance')

print(s1.pointdata["Distance"])
show(s1, s2, __doc__ , axes=11).close()
```

What could be the issue here?

**Comment by marcomusy** [comment]
Sorry for the late reply.

> Cannot find command 'git' 

indeed your anaconda might not have git installed...

> somewhat of a similar issue occurring with Box shapes/meshes

the above fix also fixes the box example

<img width="423" alt="Screenshot 2021-11-03 at 01 09 59" src="https://user-images.githubusercontent.com/32848391/139968461-535a7172-1f3e-486b-aac0-4e56a3e3a5bb.png">
