### ISSUE TITLE
Interpolate points of a given mesh from nifti DVF image volume

### ISSUE THREAD

**Issue by isurusuranga** [marcomusy/vedo#497]
Hi,

I have generated a volumetric mesh and saved it as a vtkUnstrcturedGrid (i.e. a .vtk file). Here I extracted a volumetric mesh from a nifti image which has a dimension of (203, 127, 161). I have then applied a non-rigid deformation to this nifti file and saved the deformation vector field as another nifti file. The shape of this DVF nifti mage is (203, 127, 161, 1, 3). Here the deformation field is the final position of the voxel after it has been transformed, i.e. it is the initial position of the voxel + the displacement of the voxel.

Now I need to distort the volumetric mesh based on this deformation vector field and save ita gain as a .vtk file. How can I accomplish this using vedo ? Could you please give an example ? It is possible to attach a sample nifti DVF and a voluemtric mesh for your further reference.

I highly appreciate your willingness to help me out on this issue.

**Comment by marcomusy** [comment]
Hi, that sounds complicated :)
If you already have the displacements you can simply try: 
`myugrid.points(myugrid.points()+displacements)`
E.g.:
```python

from vedo import *

ug1 = UGrid(dataurl+'ugrid.vtk')
# ug1 = UGrid('ugrid_new.vtk')

ug1.points(ug1.points()+[1,1,1])
# print(ug1.points())

# write it as unstructured grid
# import vtk
# writer = vtk.vtkUnstructuredGridWriter()
# writer.SetInputData(ug1._data)
# writer.SetFileName('ugrid_new.vtk')
# writer.Update()
```
