### ISSUE TITLE
viewing the metadata of tif file

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#503]
Hi @marcomusy,

I tried to visualize a 3D volume in vedo. 
After loading the .tif file
 
```
from vedo import *

vol = Volume('3dtif.tif') #.printHistogram(logscale=True)
print(vol)
show(vol, axes=1, viewup='z')
```
I found only a blank volume. So I want to check the contents of the .tif file and I am not sure how to view the metadata
in the tif file. Could you please help me with this?

[3dtif.tif](https://drive.google.com/file/d/1RRiv7Uh6C_gifefMp5bswKH3AFWadK1L/view?usp=sharing)

**Comment by marcomusy** [comment]
your tiff stack is a bit strange to say the least... you may try to open it in fiji... or experiment with this:
```python

from vedo import *
import numpy as np

vol = Volume('/home/musy/downloads/3dtif.tif', spacing=(1,1,0.01)).printHistogram(logscale=True)
# print(np.max(vol.tonumpy()))
arr = vol.tonumpy() / 31092 * 255
# del vol

print(arr.shape)
vol = Volume(arr.astype(np.uint8), spacing=(0.01,1,1))
print(vol.inputdata())
#show(vol, axes=1, viewup='z')
```
![Screenshot from 2021-11-01 13-19-42](https://user-images.githubusercontent.com/32848391/139670424-d8ccdc58-db73-4f09-a1c1-73b503acf696.png)

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

I couldn't visualize the volume in the tif file posted before with the updated code posted above.
I tried with an alternate .tif file  (file [here](https://github.com/DeepaMahm/misc/blob/master/cell.id.tif)) and the volume can be visualized but appears blurred


from vedo import *
import numpy as np

vol = Volume('cell.tif')
show(vol, axes=1, viewup='z')

![image](https://user-images.githubusercontent.com/29662579/140637992-03ea2167-96b1-4475-a832-2ae0005a7619.png)
I view the same blurred volume in Fiji too.
![image](https://user-images.githubusercontent.com/29662579/140637959-9b2c4d82-407d-445a-afb0-09d72261c74b.png)

Could you please let me know if this can be visualized better?

**Comment by marcomusy** [comment]
the visualization is blurred because the data is coarse-grained :)
You can slice your volume and choose some brighter color mapping, look at the examples in `examples/volumetric`.
You can also experiment with command line:

`vedo cell.id.tif`
`vedo cell.id.tif -g`
`vedo cell.id.tif --slicer`

![Screenshot from 2021-11-07 13-02-40](https://user-images.githubusercontent.com/32848391/140644211-d55b5ed8-4142-4393-be8a-a233ddf80e65.png)

**Comment by DeepaMahm** [comment]
@marcomusy Thank you
I tried
vedo cell.id.tif --slicer
and in the pop-up that appears I tried coloring the surface with gold but the color of the volume in the rendered window doesn't change. Also, could you please suggest what's the option that has to be selected to display the color scheme in the 
image posted by you.

Thanks a lot

![image](https://user-images.githubusercontent.com/29662579/140654345-59b7f4aa-fcbd-47a9-9400-6b777c93e1e0.png)

**Comment by marcomusy** [comment]
Hi, sorry - I forgot about this - please send reminders if you see you are not getting an answer... 
You should not get that pop-up with the command:
`vedo cell.id.tif --slicer`
you should get the images I posted.
What happens if you run 
`vedo --info`

If the above doesn't work for you try out this equivalent example:
`examples/volumetric/slicer1.py`

**Comment by DeepaMahm** [comment]
Hi @marcomusy,
 
`examples/volumetric/slicer1.py` helps. I could get the images you had posted via this.

However,  I don't get the images after I run `vedo cell.id.tif --slicer`; only the pop-up appears.

```
 vedo --info
_________________________________________________________________
vedo version      : 2021.0.6dev0   https://vedo.embl.es
vtk version       : 9.0.3
python version    : 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
python interpreter: ..\venv\scripts\python.exe
vedo installation : ..\venv\lib\site-packages\vedo
system            : Windows 10 nt AMD64

```

**Comment by marcomusy** [comment]
I could not reproduce this, might be due to the python 3.6 version (?).
Let me know if the issue still exists.

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,
I couldn't get this working with `vedo cell.id.tif --slicer`. I'll give it a try in other python versions. 

this works
```
vol = Volume('cell.id.tif')

plt = SlicerPlotter(
    vol,
    bg='white', bg2='lightblue',
    cmaps=("gist_ncar_r","jet","Spectral_r","hot_r","bone_r"),
    useSlider3D=False,
   )

```


I am really happy to share with you our recent work which uses `vedo` for visualization of simulation results (full text available here https://www.frontiersin.org/articles/10.3389/fnetp.2021.802881/full).

Wishing you a very happy New Year :)

**Comment by marcomusy** [comment]
Happy new Year! Thanks for the link I will definitely add it to the list of publications leveraging the library!
Thanks also for all useful feedback which helped to improve the software significantly!
