### ISSUE TITLE
Calling show crashes (after VTK update it seems)

### ISSUE THREAD

**Issue by ericdbv** [marcomusy/vedo#518]
My code using Vedo was working correctly last week. I updated vtk today (https://pypi.org/project/vtk/). Since then my code crashes. Running various Vedo examples step-by-step (see below), the execution crashes when calling "show" (Segmentation fault (core dumped)).
When running my code from PyCharm, I get the message :

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Examples I tried to run :

https://github.com/marcomusy/vedo/tree/master/examples/other/icon.py
https://github.com/marcomusy/vedo/tree/master/examples/basic/sliders3d.py

Thank you,
Eric

**Comment by ericdbv** [comment]
On 2021-11-08 15:49, Marco Musy wrote:
> Hi Eric, thanks for reporting, yes it's a bug in the latest vtk
> release... I will make a new release today to fix that!

Thank a lot for being so prompt at answering.

Best regards,
Eric

**Comment by marcomusy** [comment]
Hopefully it's now working after upgrading:
`pip install vedo -U`
Let us know if you encounter any problems,
Cheers
Marco

**Comment by ericdbv** [comment]
Indeed, it works again. Thanks a lot.
Global thanks to the whole team of contributors also.

Best,
Eric
