### ISSUE TITLE
Specular power and the mystery of the disappearing plane

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#519]
Hi @marcomusy , the origin of disappearing plane is probably the specularpower of 0:

See [https://discourse.vtk.org/t/light-disappears-when-camera-view-direction-is-parallel-to-plane/7099/3](https://discourse.vtk.org/t/light-disappears-when-camera-view-direction-is-parallel-to-plane/7099/3)

Shall I do a PR with the default values changed to something small iso 0 ?

**Comment by marcomusy** [comment]
yes! thanks!

**Comment by RubendeBruin** [comment]
#520
