### ISSUE TITLE
Can I use mouse rotate a actor like this

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#525]
https://www.weiy.city/2019/08/vtk-rotate-cone-with-ring/

Thanks.

**Comment by marcomusy** [comment]
yes but you need to write a callback function that detects the position.
check out https://github.com/marcomusy/vedo/blob/master/examples/simulations/drag_chain.py

**Comment by marcomusy** [comment]
E.g.:
```python
from vedo import *

def move(evt):
    if not evt.actor:
        return
    if not "Disc" in evt.actor.name:
    	return
    if evt.angle2d > 0:  # change to your needs
    	cone.rotateZ(1)
    else:
    	cone.rotateZ(-1)
    plt.render()

plt = Plotter()
plt.addCallback("mouse move", move)

cone = Cone().rotateY(90)
disc = Disc(r2=0.8).scale(5).lighting('off')
plt.show(cone, disc, axes=3)
```
<img width="371" alt="Screenshot 2021-11-10 at 11 51 30" src="https://user-images.githubusercontent.com/32848391/141100153-c34e5ee5-f2d6-4c46-ae08-686cddf2598a.png">

**Comment by timeanddoctor** [comment]
from vedo import *

def move(evt):
    if not evt.actor:
        return
    if not "Disc" in evt.actor.name:
        return
    if evt.angle2d > 0:  # change to your needs
        cone.rotateZ(1)
    else:
        cone.rotateZ(-1)
    plt.render()

plt = Plotter()
plt.addCallback("mouse move", move)

cone = Cone().rotateY(90).x(10)
disc = Disc(r2=0.8).scale(5).lighting('off').x(10)
plt.show(cone, disc, axes=3)

Thanks
If the actor have a translate such sa the 'x(10)'. How can I set the rotate with itself center? And another problem is how to define orientation clockwise and anti-clockwise in the 'move' fun.
Thank you very much.

**Comment by timeanddoctor** [comment]
Thanks

**Comment by marcomusy** [comment]
Did you manage to use origin()?

...actually this small example makes me think that I should revise how `origin()` works :(
Maybe this alternative solution is good for you?
```python
from vedo import *
import numpy as np

def move(evt):
    d = evt.actor
    if d and "Disc" in d.name:
        z = np.cross(evt.picked3d-d.pos(),evt.delta3d)
        cone.x(0).rotateZ(2*np.sign(z[2])).x(10)
        plt.render()

plt = Plotter()
plt.addCallback("mouse move", move)

cone = Cone().rotateY(90).x(10)
disc = Disc(r2=0.8).scale(5).lighting('off').x(10)

plt.show(cone, disc, axes=3)
```
<img width="429" alt="Screenshot 2021-11-10 at 15 06 08" src="https://user-images.githubusercontent.com/32848391/141127609-a26c8d78-0c6e-4342-a3c8-5228325ae4cf.png">

**Comment by timeanddoctor** [comment]
Cool，This is so wonderful.

**Comment by timeanddoctor** [comment]
Can I update the realtime orientation of cone.
def move:
'''
print(cone.orientation())

**Comment by timeanddoctor** [comment]
![image](https://user-images.githubusercontent.com/28825816/141130837-85a764be-0f30-4ef9-95b3-945497e7affd.png)

**Comment by marcomusy** [comment]
That's a clever solution! I didn't think of `orientation()`: 

```python
from vedo import *

def move(evt):
    d = evt.actor
    if d and "Disc" in d.name:
        cone.orientation(evt.picked3d-d.pos())
        plt.render()

plt = Plotter()
plt.addCallback("mouse move", move)

cone = Mesh(Cone().rotateY(90)).x(10)
disc = Disc(r2=0.8).scale(5).lighting('off').x(10)

plt.show(cone, disc, axes=3)
```

love when "the student becomes the master"! LOL

**Comment by timeanddoctor** [comment]
Thank you very much.
