### ISSUE TITLE
Question regarding response of button event

### ISSUE THREAD

**Issue by marcomusy** [marcomusy/vedo#528]
### Discussed in https://github.com/marcomusy/vedo/discussions/524

<div type='discussions-op-text'>

<sup>Originally posted by **jkissi** November 10, 2021</sup>
Hi marco 
I tried combining two of your examples for callback events on plots: the button and the return of point coords. The mouse over event seems to work but the button seems completely frozen. It doesn't even change colour when pressed. Here's what I have written:

```
    vp = Plotter()

    def func(evt): # called every time the mouse moves
        # evt is a dotted dictionary
        if not evt.actor:
            return  # no hit, return
        print("point coords =", evt.picked3d)
        # print("full event dump:", evt)

     #add a button to the current renderer (e.i. nr1)
    def buttonfunc():
        #elli.alpha(1 - elli.alpha())  # toggle mesh transparency
        print("Button was pressed")
        bu.switch()                 # change to next status
        printc(bu.status(), box="_", dim=True)


    bu = vp.addButton(
        buttonfunc,
        pos=(0.7, 0.05),  # x,y fraction from bottom left corner
        states=["click to hide", "click to show"],
        c=["w", "w"],
        bc=["dg", "dv"],  # colors of states
        font="courier",   # arial, courier, times
        size=25,
        bold=True,
        italic=False)

    elli = Ellipsoid()
    plt = vp.show(elli, axes=1, interactive=False)
    plt.addCallback('MouseMove', func)
    interactive()
```

Have any ideas where I'm going wrong? 

Also, second question: I would like to implement a "click and drag" functionality to select points. I didn't see that option in the vtk docs or the vedo examples. Is there a specific listener event for that or do I have to combine some other events in some way?

Cheers! 
j

</div>

**Comment by jkissi** [comment]
Damn...basic, should've seen it. How embarrassing! But at least I helped you find a bug, so there's that I guess, haha. 

Anyway, thanks mate!!
j
