### ISSUE TITLE
It can't show the grid line when I use the Grid command like "yzGrid=True" or "xzGrid=True".  

### ISSUE THREAD

**Issue by liuzg-23** [marcomusy/vedo#530]
Hello

It can't show the grid line when I use the Grid command, like "yzGrid=True" or "xzGrid=True". Can you tell me how to solve this problem?

Thanks very much and best regards.

**Comment by marcomusy** [comment]
it should work...:
```python
from vedo import *
show(Sphere(), axes=dict(yzGrid=True, zxGrid=True))
```

<img width="288" alt="Screenshot 2021-11-12 at 20 36 23" src="https://user-images.githubusercontent.com/32848391/141524870-2f1ea09c-03ed-48d6-aaa0-bf5fccbcf9ce.png">

**Comment by liuzg-23** [comment]
Hello,

I got it. If I run the same code by the vedo installed by the command "pip install vedo", it can show the grid line. But if I run it by the vedo installed by the command "conda install vedo", it can't show the grid line.

Thanks

**Comment by marcomusy** [comment]
I wonder then if the conda way installs the more recent vtk 9.1.0 which has a problem with transparent quad-meshes..

**Comment by liuzg-23** [comment]
> I wonder then if the conda way installs the more recent vtk 9.1.0 which has a problem with transparent quad-meshes..

Sorry, I don't know.
