### ISSUE TITLE
How to show the face orientation?

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#532]
Left: in Blender, Right: in MeshLab
![image](https://user-images.githubusercontent.com/34391447/141791763-0f7655a3-db61-47f3-98ac-9afc76b384a5.png)

**Comment by marcomusy** [comment]
Try
```python
mymesh.print()
n = mymesh.celldata["Normals"] # whatever the name is
pts = mymesh.cellCenters()
arrs = Arrows(pts, pts+n*10)
show(mymesh, arrs)
```
Useful methods:
`mymesh.computeNormals(cells=True)`
`mymesh.reverse()`

**Comment by LogWell** [comment]
[Here](https://github.com/marcomusy/vedo/issues/4#issuecomment-674512942) is the solution: 
```
mymesh.c((200, 200, 200))
mymesh.bc((255, 0, 0))
```
![image](https://user-images.githubusercontent.com/34391447/141802763-a26159d9-9c41-437c-9204-e245cab5380c.png)


BTY: how to get the actual number of vertices in `vedo`?

**Comment by LogWell** [comment]
[Here](https://github.com/marcomusy/vedo/issues/4#issuecomment-674512942) is the solution: 
```
mymesh.c((200, 200, 200))
mymesh.bc((255, 0, 0))
```
![image](https://user-images.githubusercontent.com/34391447/141802763-a26159d9-9c41-437c-9204-e245cab5380c.png)


BTY: how to get the actual number of vertices in `vedo`?

**Comment by marcomusy** [comment]
it's simply `mymesh.NPoints()`.

**Comment by LogWell** [comment]
In many cases, `NPoints = NCells * 3`, how can I get a result like `openmesh`?

```
    mesh_om = om.read_trimesh(path_mesh)
    print(mesh_om.n_vertices())  # 49998
    print(mesh_om.n_faces())  # 100024

    mesh_vedo = load(path_mesh)
    print(mesh_vedo.NPoints())  # 300072 = 100024*3
    print(mesh_vedo.NCells())  # 100024
```

**Comment by LogWell** [comment]
In fact, the problem is how to get the real number starting with "v" stored in the `obj` file.

Of course, I can also use `with open` to read and get the length, but there will be one more read operation:
```
data_v = []
with open(path_mesh, "r") as fp:
    for line in fp:
        if line.startswith("#"):
            continue

        values = line.split()
        if not values:
            continue

        if values[0] == "v":
            data_v.append(list(map(float, values[1:4])))
data_v = np.array(data_v)
num_v = data_v.shape[0]
```

[This](https://github.com/mikedh/trimesh/issues/489) issue may be a bit related.

**Comment by marcomusy** [comment]
yes - indeed if you add `mesh1.clean()` you should get the 49998 vertices.
