### ISSUE TITLE
How can I show a slice of tetrahedron mesh in a 2D Cartesian coordinates （just x and z direction）?

### ISSUE THREAD

**Issue by liuzg-23** [marcomusy/vedo#537]
Hello,
I want to know how can I show a slice of tetrahedron mesh in a 2D Cartesian coordinates just x and z direction? The code is shown as follows:

```python
import numpy as np
import wand
from vedo import TetMesh,Box,UGrid,BaseActor,Plotter,Axes,show, screenshot, settings, Picture
settings.defaultFont = 'Theemim'
settings.useParallelProjection = True # avoid perspective parallax
settings.multiSamples=8

tet = TetMesh('initial.vtk')
box = Box(size=(-2000,2000,-2000, 2000, -2000, 2000))
tet.cutWithBox(box)
cell_values=tet.celldata['material']
tet.celldata['material']=np.log10(cell_values)
cut_slice=tet.slice(origin=(0,-2000,0),normal=(0,1,0))
slice=cut_slice.lineWidth(0.1).lineColor('w')
slice.cmap("rainbow", 'material', on='cells',vmin=-12,vmax=0)
```

**Comment by marcomusy** [comment]
you need to manually rotate the object, like any other `vedo` object,  to match your needs with `slice.rotateX()` and/or `slice.shift()`.

**Comment by marcomusy** [comment]
sorry - maybe I misunderstood your question (?) I dont undestand very well what you mean... you slice a tet mesh by defining the normal of the plane and one point in :
`tet.slice(origin=(0,-2000,0),normal=(0,1,0))`

**Comment by liuzg-23** [comment]
Yes, I slice a tetrahedron grid by defining the normal of the plane and one point, and this slice is a 2D Figure.  I want to show this slice in a 2D Cartesian coordinates without the y direction.

**Comment by marcomusy** [comment]
what does "without the y direction" mean? you want to project it or rotate it?
if you want to rotate it use `rotate` around x,y,z or around an axis.

**Comment by liuzg-23** [comment]
I just want to show the slice in x-axis and z-axis.

**Comment by liuzg-23** [comment]
![example](https://user-images.githubusercontent.com/55772432/142327752-d3517343-d432-4bf6-9aa6-5d3172b2779a.png)

**Comment by liuzg-23** [comment]
I am sorry that I can't describe my problem clearly, the Figure is an example that I draw by paraview, I just want to draw a figure like this one by vedo.
![image](https://user-images.githubusercontent.com/55772432/142329284-6d159b6e-8bff-4f87-a767-894883326ade.png)

**Comment by marcomusy** [comment]
..but then it should be trivial...:
`tet.slice(origin=(0,0,0),normal=(0,1,0))`

**Comment by liuzg-23** [comment]
Yes, but I have used some command like "show()", "plot", but they can't work.

**Comment by liuzg-23** [comment]
Can you help me complete the code based on I write?
import numpy as np
import wand
from vedo import TetMesh,Box,UGrid,BaseActor,Plotter,Axes,show, screenshot, settings, Picture
settings.defaultFont = 'Theemim'
settings.useParallelProjection = True # avoid perspective parallax
settings.multiSamples=8

tet = TetMesh('initial.vtk')
box = Box(size=(-2000,2000,-2000, 2000, -2000, 2000))
tet.cutWithBox(box)
cell_values=tet.celldata['material']
tet.celldata['material']=np.log10(cell_values)
cut_slice=tet.slice(origin=(0,-2000,0),normal=(0,1,0))
slice=cut_slice.lineWidth(0.1).lineColor('w')
slice.cmap("rainbow", 'material', on='cells',vmin=-12,vmax=0)

**Comment by marcomusy** [comment]
```python
import numpy as np
from vedo import TetMesh,Box,UGrid,BaseActor,Plotter,Axes,show, screenshot, settings, Picture
settings.defaultFont = 'Theemim'
settings.useParallelProjection = True # avoid perspective parallax
settings.multiSamples=8

tet = TetMesh('final_mesh.1.vtk')

cell_values = np.log(tet.celldata['cell_scalars']+10000)
tet.celldata["myarray"] = cell_values

print(tet.celldata.keys())

cut_slice = tet.slice(origin=(0,6230000,0),normal=(0,1,0))
slc = cut_slice.lineWidth(0.1).lineColor('w')
slc.cmap("rainbow", 'myarray', on='cells').addScalarBar()

show(slc, axes=1, elevation=-90)
```
data in #512
<img width="347" alt="Screenshot 2021-11-18 at 02 23 54" src="https://user-images.githubusercontent.com/32848391/142333931-2d7f5431-d207-4800-b9d3-888969606488.png">

**Comment by liuzg-23** [comment]
Ok, I got it, Thanks very much!
