### ISSUE TITLE
Plotting a CT Scan using PlotterSlicer with additional 3d labels (Segmentations)

### ISSUE THREAD

**Issue by RomStriker** [marcomusy/vedo#538]
Hi, 

I am plotting a CT Scan using plotter slicer using the function:

```python
def show_nifty_volume(file_path):
    volume = load(file_path)
    plt = SlicerPlotter(volume,
                        bg='white', bg2='lightblue',
                        cmaps=("gist_ncar_r", "jet", "Spectral_r", "hot_r", "bone_r"),
                        useSlider3D=False,
                        )
    plt.show().close()
```
![image](https://user-images.githubusercontent.com/45386503/142247748-7c8b8e73-0e37-4175-8afd-068581f74eb4.png)

I also have a segmentation labels for this image, which looks like below:

![image](https://user-images.githubusercontent.com/45386503/142247502-81a257b6-1b1d-4e66-aebd-99648b7f951b.png)

Is it possible to display the labels in the same SlicerPlotter as the CT scan plot as a 3D object such that the 3D label overlaps with the structure in 3 slices? Also I have multiple labels, would it be possible to display one label at a time using a slider?

**Comment by marcomusy** [comment]
In principle it should be possible: `SlicerPlotter` is a `Plotter` object so you can add to the scene anything you like, also other volumes e.g:
`plt += Volume("myfile.tif")`

To swtich label volume I would use a button.

**Comment by RomStriker** [comment]
This does the job. Thank you.
