### ISSUE TITLE
did actor.scalar_colors disappear?

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#545]
I have some old code that used actor.scalar_colors to specify the color for the vertices.
Workes fine in vedo 2021.0.3 but breaks in later versions. Has this been replaced by something else?

**Comment by marcomusy** [comment]
Uhm.. are you sure.. I cannot remember anything called like that.. is actor a Mesh?

**Comment by marcomusy** [comment]
what you can do now is e.g.:
```python
from vedo import *
import numpy as np

settings.interpolateScalarsBeforeMapping=False

s=Sphere().clean().lw(1)
colors = np.random.randint(0,255, size=(s.N(), 3)).astype(np.uint8)

s.pointdata['vertex_colors'] = colors
s.pointdata.select('vertex_colors')

show(s,axes=1)
```

![Screenshot from 2021-11-23 16-02-49](https://user-images.githubusercontent.com/32848391/143049020-ec132260-7fda-434d-8f10-5b2305342f30.png)

**Comment by RubendeBruin** [comment]
> Uhm.. are you sure.. I cannot remember anything called like that.. is actor a Mesh?

sorry, used c.pointColors(scalar_colors) :

Old code
```python
import numpy as np
from vedo import *

c = Cube()

n = len(c.points())
scalar_colors = np.random.randint(0,255, size = (n,1))

c.pointColors(scalar_colors, vmin=-2500, vmax=2500, cmap='rainbow)

show(c)
```

Upgraded to:

```python
import numpy as np
from vedo import *

settings.interpolateScalarsBeforeMapping=False

c = Cube()

n = len(c.points())
scalar_colors = np.random.randint(0,255, size = (n,1))

# c.pointColors(scalar_colors)
c.pointdata['vertex_colors'] = scalar_colors
c.pointdata.select('vertex_colors')
c.cmap('rainbow', vmin=-2500, vmax=2500)

show(c)
```

works, thanks @marcomusy

**Comment by marcomusy** [comment]
If it's a simple scalar to be mapped you can consider the following simplification:
```python
import numpy as np
from vedo import *

np.random.seed(0)
settings.interpolateScalarsBeforeMapping=False

c = Cube()
scalars = np.random.randn(c.NPoints())
c.cmap('flag', scalars).addScalarBar()#.print()
show(c)
```

The array is automatically added with name "PointScalars". Note the effect of `interpolateScalarsBeforeMapping`.

![Screenshot from 2021-11-23 16-50-47](https://user-images.githubusercontent.com/32848391/143057315-9732df41-999b-4286-a417-e0ff7cfe5a2f.png)
