### ISSUE TITLE
Density now showing

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vedo#547]
Hi Marco, 

I'm trying to plot `Points().density()`  following up on this issue: https://github.com/brainglobe/brainrender/issues/107#issuecomment-981112830

When I run the `vedo` [example](https://github.com/marcomusy/vedo/blob/master/examples/pyplot/plot_density2d.py) the density is not shown:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/17436313/143956904-8048a500-0ac2-45cd-abc1-0c9f4494377e.png">

while in brainrender it shows a `Volume` actor like in the issue mentioned above. Previously it would visualize a nice semi-transparent 'heatamap' of density in 3D. Do you know how I can recover that?

**Comment by marcomusy** [comment]
Hi Federico, running
```python
import numpy as np
from vedo import *

settings.useDepthPeeling = True

n = 3000
p = np.random.normal(7, 0.3, (n,3))
p[:int(n*1/3) ] += [1,0,0]       # shift 1/3 of the points along x by 1
p[ int(n*2/3):] += [1.7,0.4,0.2]

pts = Points(p, alpha=0.5)

vol = pts.density().c('Dark2').alpha([0.1,1]).mode(1) # density() returns a Volume

show(pts, vol, axes=True)
```

I get the expected output:

![Screenshot from 2021-11-30 00-17-46](https://user-images.githubusercontent.com/32848391/143957958-21a44a9f-a4ef-4753-b55b-d60a62175568.png)

You may try to add `.mode(1)`.

**Comment by FedeClaudi** [comment]
Thanks, on Max it seems like it needs a bit more work:

This is with `useDepthPeeling = False`:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/17436313/144015015-d6ec7b47-bf9d-4a0a-974e-187868771d1a.png">


while setting it to `True` makes the points disappear:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17436313/144015096-7b2e3c18-4326-4b57-b0a0-5752cd426868.png">

As we discussed before on some other issue, on Mac I needed to set: `settings.multiSamples = 0` before getting the expected results like in your image above, maybe there's a way to warn users/enforce working settings for Mac users?

---
On `brainrender` it still looks odd:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/17436313/144016838-26f43426-42ab-4f9f-bec3-d677a7efe6e6.png">

and I'm creating the `Volume` actor as: 
```python
        volume = vPoints(data).density(
            dims=dims, radius=radius, **kwargs
        ).c('Dark2').alpha([0,.4]).mode(1)  # returns a vedo Volume
```


These are the default settings for `vedo` in `brainrender`:
```python
# ------------------------------- vedo settings ------------------------------ #

vsettings.pointSmoothing = False
vsettings.lineSmoothing = False
vsettings.polygonSmoothing = False
vsettings.immediateRendering = False

vsettings.useDepthPeeling = True
vsettings.alphaBitPlanes = 1
vsettings.maxNumberOfPeels = 12
vsettings.occlusionRatio = 0.1
vsettings.multiSamples = 0 if sys.platform == "darwin" else 8

vsettings.useSSAO = True

# For transparent background with screenshots
vsettings.screenshotTransparentBackground = False  # vedo for transparent bg
vsettings.useFXAA = True  # This needs to be false for transparent bg

```

**Comment by marcomusy** [comment]
that's a bit strange because in the image above the volume still seems to be rendered in `mode(0)` (so called "composite" rendering).
I need to check on my mac (Monterrey) what could be happening..
I would remove in any case
```
vsettings.useSSAO = True
vsettings.useFXAA = True
```

**Comment by FedeClaudi** [comment]
I think I've found the culprit:
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/17436313/144138067-25c0549c-c26a-4874-a6a2-7a7fd70adce7.png">

In brainrender I use a [transform matrix](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/brainrender/render.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L21) to flip all meshes along an axis to keep the coordinates system consistent with other brainglobes applications. 

Normally I then [reverse](https://github.com/brainglobe/brainrender/blob/35ad88466f5f1e6f376ad11d724e0eb4d48ba0b1/brainrender/render.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L129) the actors to make them render normally, but the `Volume` object I'd get from density cannot be reversed the same way. 

The solution is to apply the transform on the coordinates of the points passed to the brainrender `PointsDensity` class before creating a `Volume` actor with `vedo`. 

Thanks for the help

**Comment by marcomusy** [comment]
Sorry for the late reply, this one issue slipped off my attention... can you do `volume.mirror('y')`? You don't need `reverse()` in this case as volumes have no normals.

**Comment by FedeClaudi** [comment]
Hi Marco. I wasn't aware of the `mirror` method, cool. It seems not to be doing exactly what I need here, but it's good to know that it's out there.
My original issue is resolved, so if you'd like we can close this issue.
