### ISSUE TITLE
Textured mesh to colored point cloud

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#548]
Hi @marcomusy,

Do you have any functionality to port a textured mesh to colored point cloud?

I can get the points and normals from the mesh structure but it seems not the color per point (at least not directly):

```
m1 = vd.Mesh("../data/Tombstone1_p1.obj").texture("../data/Tombstone1_low.jpg")

p1 = vd.Points(m1.points())
p1.normals = m1.normals()
```

Thanks.

**Comment by marcomusy** [comment]
you should get the (u,v) coordinate of the point from the texture array and pick the color from the jpg at that location..

`m1.print() # to know the texture array name`
`tarr = m1.pointdata['texturename']`
`colorarray = Picture('Tombstone1_low.jpg').tonumpy()`

**Comment by ttsesm** [comment]
> you should get the (u,v) coordinate of the point from the texture array and pick the color from the jpg at that location..
> 
> `m1.print() # to know the texture array name` 
> `tarr = m1.pointdata['texturename']` 
> `colorarray = Picture('Tombstone1_low.jpg').tonumpy()`

Hhmm, which one corresponds to the texture array name:
```
Mesh/Points 
           file: ../data/Tombstone1_p1.obj
          color: white, rgb=(1.00, 1.00, 1.00), alpha=1.0
         points: 116169
          cells: 38723
       polygons: 38723
       position: (0.0, 0.0, 0.0)
          scale: (1.00, 1.00, 1.00)
 center of mass: (-291, -37.4, -257)
   average size: 190.894
  diagonal size: 583.837
         bounds: x=(-514, -57.2) y=(-86.6, -0.766) z=(-415, -62.0)
    scalar mode: UsePointData   coloring = Default
   active array: material_0 (point data)  MaterialIds (cell data)
     point data: name=material_0 (2 FLOAT, np.float32), range=(9.00e-4,0.999)
     point data: name=Normals (3 FLOAT, np.float32), range=(-1.00,1.00)
      cell data: name=MaterialIds (1 INT), range=(0,0)
      cell data: name=GroupIds (1 FLOAT), range=(0,0)
```
[data.zip](https://github.com/marcomusy/vedo/files/7626778/data.zip)

**Comment by marcomusy** [comment]
Here it is ...the rest is a numpy exercise..:
```python
import vedo

m1 = vedo.Mesh("data/Tombstone1_p1.obj").texture("data/Tombstone1_low.jpg")

texture_arr = m1.pointdata['material_0']

pic = vedo.Picture("data/Tombstone1_low.jpg")
color_arr = pic.tonumpy()

print(pic.bounds())
print(color_arr.shape)

vedo.show(m1, axes=1)
```
![Screenshot from 2021-11-30 16-22-25](https://user-images.githubusercontent.com/32848391/144075451-46445900-5fa7-4cea-9b3d-66ba88205d5f.png)

**Comment by ttsesm** [comment]
And for completeness, for future readers:

```
    m1 = vd.Mesh("../data/Tombstone1_p1.obj").texture("../data/Tombstone1_low.jpg")
    texture_arr = m1.pointdata['material_0']
    pic = vd.Picture("../data/Tombstone1_low.jpg")
    color_arr = pic.tonumpy()

    x_y_coords = np.floor(texture_arr * color_arr.shape[0:2]).astype(int) # pixel_coord = uv_coord * [width, height] (some bilinear filtering might be possible to be applied for reducing the artifacts)
    color = color_arr[x_y_coords[:, 0], x_y_coords[:, 1], :]

    p1 = vd.Points(m1.points(), c=color)
    p1.normals = m1.normals()

    vd.show(m1, "Mesh", at=0, N=2, axes=1)
    vd.show(p1, "PCD", at=1, interactive=1).close()
```

![image](https://user-images.githubusercontent.com/10189018/144089222-cfa90060-34be-4228-bac0-157b31209ef8.png)

**Comment by ttsesm** [comment]
@marcomusy how is this line `texture_arr = m1.pointdata['material_0']` transformed in the newer versions of `vedo`? 
I cannot find something relevant anymore... 🤔

**Comment by marcomusy** [comment]
Hey, the above script still works for me!

**Comment by ttsesm** [comment]
hhhmmm... interesting
On another [mesh](https://filesender.garr.it/?s=download&token=218cfce7-e459-46fd-a874-dedde83eb6cc) that I am trying the following lines:
```
mesh_file = "RPf_00015.obj"
texture_file = "RPf_00015.png"

m = vedo.Mesh(mesh_file).texture(texture_file).lighting("off")
texture_arr = m.pointdata['material_0']
```

`m.pointdata['material_0']` returns `None`... while if I plot the mesh it looks fine... my texture file is a `.png` file though but this
 shouldn't make any difference...

**Comment by ttsesm** [comment]
Hhhhhmmm... another issue that came up with the new mesh is that the mapping seems to be quite off...

![Image](https://github.com/user-attachments/assets/346d50e2-b5fd-4933-b9da-87af22452efe)
```
mesh_file = "RPf_00015.obj"
texture_file = "RPf_00015.png"
m = vedo.Mesh(mesh_file).texture(texture_file).lighting("off")

texture_arr = m.pointdata[0]
pic = vedo.Image(texture_file)
color_arr = pic.tonumpy()

x_y_coords = np.floor(texture_arr * color_arr.shape[0:2]).astype(int)  # pixel_coord = uv_coord * [width, height] (some bilinear filtering might be possible to be applied for reducing the artifacts)
color = color_arr[x_y_coords[:, 0], x_y_coords[:, 1], :]

p1 = vedo.Points(m.points)
p1.pointcolors = color
p1.normals =m.pointdata[1]

vedo.show(m, "Mesh", at=0, N=2, axes=1)
vedo.show(p1, "PCD", at=1, interactive=1).close()
```

any idea what could be the issue... 🤔

**Comment by marcomusy** [comment]
Uhm, it looks to me like a mismatch in the array order.. but i'm not sure.
you can maybe check what happens for some specific points...
