### ISSUE TITLE
2D image embed into the viewer 

### ISSUE THREAD

**Issue by abhigoku10** [marcomusy/vedo#550]
@marcomusy  thanks for the source code , i am using this very well in my project but i am looking for a feature where along with point cloud display i want to embed the 2d image at the sides as show below how can i achieve this , currently i am use plotter.show to display the point cloud data. THanks in adavance 
![image](https://user-images.githubusercontent.com/22094053/144433111-f94ccc40-cfa7-4ec4-b596-7996d272798f.png)

**Comment by marcomusy** [comment]
Hi, maybe you can achieve something similar following the example:
https://github.com/marcomusy/vedo/blob/master/examples/basic/multirenderers.py

remember to set `sharecam=False`
