### ISSUE TITLE
Points on the cone surface but isInside function return 0

### ISSUE THREAD

**Issue by YangfanJiang** [marcomusy/vedo#551]
Hi,

I just want to use isInside to check a point if is on a surface of a cone. I defined a point and visualise it, it is definitely on the surface of the cone. But the isInside function return False (0). Could you please help me with this problem? Thanks!

![vedoCone](https://user-images.githubusercontent.com/72881308/144604009-562acd9c-6fe4-4483-9d84-982aac515cfc.PNG)

![image](https://user-images.githubusercontent.com/72881308/144604024-cef5f787-e136-4b57-b9b2-5f27789cbc4a.png)

**Comment by marcomusy** [comment]
If it is on the surface then it is not inside.. :) so the output is technically correct!
It's probably better if you also check `mag2(p-cone.closestPoint(mypt))`

**Comment by YangfanJiang** [comment]
Hi,

Thank you so much for the reply. I just check the result following your suggestion, it returns 4.2500001239715134e-06.  Does it look right?

**Comment by YangfanJiang** [comment]
The code I used: "vedo.mag2(myCone.closestPoint(myPoint))". myCone is just a Cone object from vedo and my point is a position tuple of x,y,z coordinates.

**Comment by marcomusy** [comment]
you can maybe share your code to check? otherwise it is difficult for me to help..

**Comment by YangfanJiang** [comment]
H = 0.005*0.01/(4*0.005-2*0.002)
H1 = (3 * 0.005 * 0.01 - 2 * 0.002 * 0.01) / (4 * 0.005 - 2 * 0.002)
tcone = Cone(alpha=0.5, r= 0.005, pos=(0, 0, H1), res=120, height=2*H, axis=(0, 0, -1))
position1 = (-0.002 / 2, 0, 0.01 / 2)
tclo = tcone.closestPoint(position1)
print(tclo, position1)
print('inside: ', tcone.isInside(position1))

Thanks!

**Comment by marcomusy** [comment]
the point is almost exactly on one of the **triangular** surfaces of the cone and is technically outside of the cone. Replacing x=-0.00199 brings it inside:
```python
from vedo import *

H = 0.005*0.01/(4*0.005-2*0.002)
H1 = (3 * 0.005 * 0.01 - 2 * 0.002 * 0.01) / (4 * 0.005 - 2 * 0.002)

tcone = Cone(alpha=0.5, r= 0.005, pos=(0, 0, H1), res=120, 
	height=2*H, axis=(0, 0, -1))
position1 = (-0.00199 / 2, 0, 0.01 / 2)

tclo = tcone.closestPoint(position1)

printc(tclo, position1)
printc('inside: ', tcone.isInside(position1))
printc(mag(tclo-position1), c='b')

show(tcone, Point(position1), Point(tclo, c='g'), axes=1)
```
<img width="555" alt="Screenshot 2021-12-03 at 17 51 43" src="https://user-images.githubusercontent.com/32848391/144641135-e5fc2981-8e30-421f-bcd9-8cdee73cc398.png">

**Comment by YangfanJiang** [comment]
Thanks! Is there any other way to solve the problem like this? Because I already tried to improve the resolution of the cone. But still got the same problems。

**Comment by marcomusy** [comment]
the only way I see is to check the distance, and compare it with the face normal. Use `.normals()` and the cross product. To find the cell id use `.closestPoint(pt, returnCellId=True)`.
Let me know if you need further help.

**Comment by YangfanJiang** [comment]
Thanks for the update! I will try the suggestion you provided and close the issue at this point.
