### ISSUE TITLE
Support for higher dimensional (4D or 5D)  volumes? 

### ISSUE THREAD

**Issue by efirdc** [marcomusy/vedo#553]
I am interested in visualizing some higher dimensional volumes. For example, fMRI is 4D since it has 3 spatial dimensions and a time dimension. Is this possible currently with vedo?

**Comment by marcomusy** [comment]
Yes... it depends on the format of the data and the way you wish to visualize is.. (e.g. by a slider, side-by-side etc) 
Take a look at the example gallery at http://vedo.embl.es

**Comment by panangam** [comment]
@marcomusy Would you be able to point to relevant examples? For me, I want to visualize a technically 4D grid either as a 3D grid changing in time or shifting with a slider. How do you change the Volume 3D grid values?

**Comment by marcomusy** [comment]
..well I would create a time serie of volumes like in this [example](https://github.com/marcomusy/vedo/blob/master/examples/pyplot/plot_density4d.py):

![](https://vedo.embl.es/images/pyplot/plot_density4d.gif)
