### ISSUE TITLE
How to Compare result of decimation and interpolation

### ISSUE THREAD

**Issue by sonumathur** [marcomusy/vedo#554]
As per the issue https://github.com/marcomusy/vedo/issues/338#issuecomment-841532621 
I want to compare decimated model and interpolated model as:
![result](https://user-images.githubusercontent.com/60248559/145168762-a712bf15-4c39-4ccb-af1b-cf97d30bc69b.PNG)
 
Decimated and Interpolated are seams to be same, how can be compared.

**Comment by lyfs** [comment]
您好！我是飞哥的邮箱小飞，谢谢您的来信，他会尽快回复的，祝您快乐每一天！！

**Comment by marcomusy** [comment]
the interpolation of #338 refers to the data associated to either vertices or faces of the mesh, **not** the position of vertices, which stays the same.
You are maybe looking for `sphere.smooth()`?

**Comment by sonumathur** [comment]
Actually want to compare smoothness in decimated and interpolated, is there any parameter that can show its effects

**Comment by marcomusy** [comment]
Yes, check out this example:
`vedo -r quality`

**Comment by sonumathur** [comment]
Sir please provide link to example vedo -r quality..

**Comment by marcomusy** [comment]
https://github.com/marcomusy/vedo/blob/master/examples/advanced/meshquality.py

Doesn't it work from command line?

**Comment by sonumathur** [comment]
Thanks a lot..
Checked. Works in PyCharm.
