### ISSUE TITLE
How to create a line that do not change when zoom in/out

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#557]
Please have a look for the following figure:

![image](https://user-images.githubusercontent.com/29271051/145920391-48c68f4c-6eca-4ecd-848f-29fc38682816.png)

When zoom in/out, the green line would change, but the red cross line would not change. 

The green line can be created as:

```
line = Line(p0=[0, 0, 0], p1=[1, 1, 1])
```

But, how can I create the red cross line which do not change when zoom in/out?

**Comment by zhang-qiang-github** [comment]
Yes, I can create 2 crossing red lines with `Lines()`, but this kind of line would change when zoom in/out the window. 

I would like the length of line to be 10 screen pixel unit rather than 10 mm. The 10 mm line would have length of 10 or 100 screen pixel unit when zoom in/out. And the 10 screen pixel unit would always have length of 10 screen pixel unit.

**Comment by marcomusy** [comment]
> but this kind of line would change when zoom in/out the window.

No! it will not scale with zoom. E.g.:
```python
from vedo import *

pic = Picture("https://user-images.githubusercontent.com/29271051/145920391-48c68f4c-6eca-4ecd-848f-29fc38682816.png")

plt = Plotter(bg='black')
plt+=pic
plt+=Line([10,150,1],[250,50,1]).lw(10).c('purple7')
plt.show()
```

![Screenshot from 2021-12-16 14-51-22](https://user-images.githubusercontent.com/32848391/146384306-b38d5d91-4073-4591-a4fe-f7b23633a208.png)

**Comment by zhang-qiang-github** [comment]
The line width will not scale with zoom, but the length of line is actually changed with zoom. 

For example, the length of the purple line is about half of the window size. 

![image](https://user-images.githubusercontent.com/29271051/146876289-09446f0e-3d23-4fb4-9d5e-32945ea2224f.png)

When I zoom in the picture, the length of the purple line is equal with the window size:

![image](https://user-images.githubusercontent.com/29271051/146876427-f9d4c9a8-c37e-48b0-a981-7755e8852bbd.png)

Maybe I do not clearly describe what I need. Please have a look at the following figure:

![image](https://user-images.githubusercontent.com/29271051/146876747-282402f4-0761-46f0-a357-162082eea265.png)

The read sphere looks much bigger than the green point. The green point would not scale with zoom but the sphere would. Then, I zoom out the window:

![image](https://user-images.githubusercontent.com/29271051/146876897-217886c6-2b82-4b2b-bc6e-c843c0d0fe16.png)

In the above figure, the read sphere look the same size of the green point. I want a line actor which behave like `Point` rather than the `Sphere`.

**Comment by marcomusy** [comment]
> I want a line actor which behave like Point rather than the Sphere.

.. it already does! Your example with `Point` and `Sphere` shows the expected behaviour.
The purple line does not change its thickness because this is expressed in units of pixels. So it already behaves like `Point`.
It's length is not changed (in world coords).. or are you looking for a 2d object that does not change at all with user scene interaction?

Sorry if I cannot interpret your question correctly.

**Comment by zhang-qiang-github** [comment]
Yes, I want a 2d line that does not change the length (units of pixels) at all with user scene interaction.

Currently, the length is not changed in world coordinate, I want the length is not changed in screen coordinate. Is that possible?

**Comment by marcomusy** [comment]
uhm.. you may have a look at `examples/other/clone2d.py`.

**Comment by zhang-qiang-github** [comment]
Yes, that's what I am looking for. Thank you very much.
