### ISSUE TITLE
How to pick one object in a group meshes

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#558]
I use `Assembly` to group some mesh. Then, I want to know which object has been picked.

For example:

```
from vedo import *

l1 = Line(p0=[0, 0, 0], p1=[1, 0, 0]).lw(10).c('r')
l2 = Line(p0=[0, 0, 1], p1=[1, 0, 1]).lw(10).c('g')
l = l1 + l2

def onLeftClick(mesh):
    print(mesh)


vp = Plotter(bg='black')
vp.mouseLeftClickFunction = onLeftClick
vp.show(l)

```

In the `onLeftClick`, the mesh is a `vtkAssembly`, how can I know which object (`l1` or `l2`) has been picked?

**Comment by marcomusy** [comment]
maybe the best way is to check the distance to the closest point to both, by unpacking the Assembly:
```python
from vedo import *

l1 = Line(p0=[0, 0, 0], p1=[1, 0, 0]).lw(10).c('r')
l2 = Line(p0=[0, 0, 1], p1=[1, 0, 1]).lw(10).c('g')
l = l1 + l2

def onLeftClick(evt):
    if not evt.isAssembly: 
    	return
    lines = evt.actor.unpack()
    # print(lines, evt.picked3d)
    for l in lines:
    	d = mag2(l.closestPoint(evt.picked3d) - evt.picked3d)
    	print(d)

plt = Plotter(bg='black')
plt.addCallback("mouse click", onLeftClick)
plt.show(l)
```

**Comment by zhang-qiang-github** [comment]
If I add `line`, and `point`, I want to pick the point. For example: 

```
from vedo import *


l1 = Line(p0=[0, 0, 0], p1=[1, 0, 0]).lw(10).c('r')
p1 = Point(pos=[1, 0, 0], c='y', r=50)
l = l1 + p1

def onLeftClick(evt):
    if not evt.isAssembly: 
    	return
    lines = evt.actor.unpack()
    # print(lines, evt.picked3d)
    minDis = 9999
    closeActor = None
    for l in lines:
    	d = mag2(l.closestPoint(evt.picked3d) - evt.picked3d)
    	if d<minDis:
            minDis = d
            if l == l1:
                closeActor = 'line'
            else:
                closeActor = 'point'
    print(closeActor)

plt = Plotter(bg='black')
plt.addCallback("mouse click", onLeftClick)
plt.show(l)

```

I can only pick the `line`. 

In the `closestPoint` method, `self.cell_locator.FindClosestPoint(pt, trgp, cid, subid, dist2)` always return `dist2=-1` if I pick the point.

**Comment by marcomusy** [comment]
This seems to be a genuine bug which only shows up when `Points()` is called with a single point..
I can only offer you a temporary hack:
```python
from vedo import *

l1 = Line(p0=[0,1,0], p1=[1,1,0]).lw(10).c('r')

# p1 = Point(pos=[2,0,0], c='y', r=50)
p1 = Points([[0,0,0],[1e-10,0,0]], c='y', r=50).pos([2,0,0])
p1.name = "TestObj"

l = l1 + p1

def onLeftClick(evt):
    if evt.isAssembly: 
        pt = evt.picked3d
    else:
        pt = plt.computeWorldPosition(evt.picked2d)
    minDis = 9999
    closeActor = None
    for o in l.unpack():
        d = mag(o.closestPoint(pt) - pt)        
        if d<minDis:
            minDis = d
            closeActor = o
    print(closeActor.name)

plt = Plotter(bg='black')
plt.addCallback("mouse click", onLeftClick)
plt.show(l, axes=1)
```
<img width="423" alt="Screenshot 2021-12-31 at 19 26 14" src="https://user-images.githubusercontent.com/32848391/147835526-3021af7b-51db-4667-ab82-08ecd2835c35.png">

I'll fix this in the next release. Thanks for spotting and reporting the issue.

**Comment by zhang-qiang-github** [comment]
Sorry, but `p1 = Points([[0,0,0],[1e-10,0,0]], c='y', r=50).pos([2,0,0])` do not give the correct result. Could you please have a try for `p1 = Points([[0,0,0],[1e-10,0,0]], c='y', r=50).pos([0,1,0])`. I can not pick the point, but only the `line` can be picked.

**Comment by marcomusy** [comment]
You are picking in the loop the first point in the line which coincides with the `Point` position!

**Comment by zhang-qiang-github** [comment]
> You are picking in the loop the first point in the line which coincides with the `Point` position!

Yes, that's the reason. But, I except I can pick the `point` if the icon is located in the yellow circle just like the green arrow in the following figure.

![image](https://user-images.githubusercontent.com/29271051/148147516-5eb0a677-0e25-46b2-abfb-a55b6c8798d5.png)

Do you have some suggestions? I can also have a try.

**Comment by marcomusy** [comment]
The point size is a sort of "fake" size in the world coordinates, there might be some clever way of passing from screen and world coordinates but honestly I don't know how to do it..

**Comment by marcomusy** [comment]
Fixed in the next release.
