### ISSUE TITLE
Intrude mesh boundary by a given distance

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#561]
Hi @marcomusy,

I am trying to intrude part of the given mesh by following your example [here](https://github.com/marcomusy/vedo/issues/351#issuecomment-807845671):

```
m1 = vd.Mesh("./frag_1_final.ply").c("gray")
# vd.show(m1, __doc__, axes=1, viewup='z').close()

bnd = m1.boundaries(nonManifoldEdges=False, featureAngle=180)
# this creates the blue "tube" which is then used to cut the mesh
modl = bnd.implicitModeller(distance=0.0005, res=(150, 50, 150), bounds=())
m1.cutWithMesh(modl)

vd.show(m1, bnd, modl, axes=1, viewup='z').close()
```
![image](https://user-images.githubusercontent.com/10189018/146195888-1a860529-62fa-4a67-ba0a-25c2593069f1.png)

The boundaries that are extracted are the following:
![image](https://user-images.githubusercontent.com/10189018/146196086-531f3bcf-338f-4888-8bfe-1df9279cac7e.png)

The modeller with the `0.0005` distance seems to be empty:
![image](https://user-images.githubusercontent.com/10189018/146196369-d2ba85d4-60cd-4c66-a723-2f98d63a8ddc.png)
then I increased it to `1` and I've got the "tube" that you are mentioning but as you can see there are some discontinuity in between:
![image](https://user-images.githubusercontent.com/10189018/146201604-9f1c478d-cdf3-4fd0-a655-59d40bbe4d3d.png)
![image](https://user-images.githubusercontent.com/10189018/146201919-a62eb7ad-effa-4f73-a6b9-21c0d7397bdf.png)

So I have the following questions, first I would like to keep only the biggest boundary and not the smaller ones, in the linked example I could see that there was an `outer=True/False` parameter which is not available anymore and I guess it was doing this job. Moreover, could you elaborate a bit on the parameters of the `implicitModeller()` and what each corresponds to. I guess `distance=` is the distance you want to cut from the boundary, but it is measured in? then for `res=`, `bounds=` and `maxdist=` is not clear what are about. Why there is this parts in the modeller where there are gaps?

[frag_1_final.ply.zip](https://github.com/marcomusy/vedo/files/7719950/frag_1_final.ply.zip)

**Comment by ttsesm** [comment]
> i would rotate the object so you do not need a lot of resolution.. 
> 
Hhmm, I am not sure I can rely on this, since I have multiple meshes to process which come in different orientations. Thus, rotating to a specific angle it might work on some but not in others. 
> Parameter `res` tells what is the desired resolution along x,y,z of the volume which embeds `bnd`. `distance`is expressed in the same units as x y and z. Even so it takes a few minutes to run.
>
I see, considering the above issue (i.e. meshes loaded in different orientations) is there any other way to optimize resolution? It seems to be quite important, also for the process timing.

Maybe orienting the mesh based on the largest boundary to one of the x,y,z planes and then I can have a fixed `res`?

**Comment by marcomusy** [comment]
> I have multiple meshes to process which come in different orientations.

You may fit an ellipsoid to find the principal axes and rotate accordingly (with `pcaEllipsoid()`) or just use more memory and CPU  time :)

> is there any other way to optimize resolution?

No, because to create the model you need to create a cube-shaped volumetric grid.

> Maybe orienting the mesh based on the largest boundary to one of the x,y,z planes and then I can have a fixed res?

yes - but that is what I was suggesting above.

**Comment by marcomusy** [comment]
..it's an exercise of linear algebra :) I guess you need to invert the matrix:
```
[axis1,
 axis2, 
 axis3]
```
remember to normalize axes and check for the determinant to be positive to avoid improper rotations (mirroring), in that case you need to reorder the matrix lines. Once you have the matrix you can do `mymesh.applyTransform(M)`.

**Comment by ttsesm** [comment]
> remember to normalize axes and check for the determinant to be positive to avoid improper rotations (mirroring)
>
Can you elaborate a bit on this, because indeed just inverting the matrix gives a strange result:
```
vd.settings.useDepthPeeling = True

m1 = vd.Mesh("../data/box_8/frag_1_final.ply")#.rotateX(50)
m2 = m1.clone()

elli = vd.pcaEllipsoid(m1, pvalue=0.5)

transf = np.array([elli.axis1, elli.axis2, elli.axis3])

vd.show(m2.applyTransform(np.linalg.inv(transf)), axes=1, viewup='z').close()
```

![image](https://user-images.githubusercontent.com/10189018/146547115-bf5060fe-df8b-4d75-83e3-6587a939ae71.png)

**Comment by marcomusy** [comment]
Consider the following example:
```python
from vedo import *
import numpy as np

settings.useDepthPeeling = True

m1 = Mesh("data/frag_1_final.ply").c("k4")#.rotateY(-60)
cm = m1.centerOfMass()

elli = pcaEllipsoid(m1, pvalue=0.5).alpha(0.7)
m2 = m1.clone().shift(-cm)

a1 = Arrow(cm,elli.axis1, c='r')
a2 = Arrow(cm,elli.axis2, c='g')
a3 = Arrow(cm,elli.axis3, c='b')

ax1 = versor(elli.axis1-cm)
ax2 = versor(elli.axis2-cm)
ax3 = versor(elli.axis3-cm)

T = np.array([ax1,ax2,ax3])  # the transposed matrix is already the inverse
# print(T)
# print(T@ax1)

m2.applyTransform(T)
b1 = a1.clone().shift(-cm).applyTransform(T)
b2 = a2.clone().shift(-cm).applyTransform(T)
b3 = a3.clone().shift(-cm).applyTransform(T)

show([[m1, a1,a2,a3, elli],
      [m2, b1,b2,b3]], N=2, sharecam=False, axes=1)
```
![Screenshot from 2021-12-17 18-38-11](https://user-images.githubusercontent.com/32848391/146586466-4c5104ff-c5f8-461a-848a-17cbb4bad54e.png)
