### ISSUE TITLE
fill holes with color?

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#563]
Hi @marcomusy,

Does the `fillHoles()` function support color? Because what I get is black spots:
![image](https://user-images.githubusercontent.com/10189018/146573222-b2816d9d-b648-4e2e-b512-f3178ca1e6cf.png)

Checking on the doc, I did not find something but I might have overlooked at it.

**Comment by marcomusy** [comment]
It does not support it, you may try to recompute normals with `mymesh.computeNormals()`.
Or you may try to interpolate the (u,v) texture corrodinates from the original mesh onto the closed one:
`filledmesh.interpolateDataFrom(originalmesh)`

Check out example `examples/advanced/interpolateScalar1.py`.

**Comment by ttsesm** [comment]
I see, instead of doing what you are suggesting would be possible to use the [pymeshlab framework](https://github.com/marcomusy/vedo/blob/master/examples/other/pymeshlab2.py) to fill the holes with the close holes filter?

Doing it in manually in meshlab, it seems work quite nicely:
![image](https://user-images.githubusercontent.com/10189018/146678912-d5f8361e-ac5d-4e59-a842-a366faf51ddf.png)

I am not sure though yet that pymeshlab supports meshes with color.

**Comment by marcomusy** [comment]
I guess so... but I'm not at all an expert in meshlab..

**Comment by ttsesm** [comment]
Ok, this seems to work:

![image](https://user-images.githubusercontent.com/10189018/146776129-ccfab68a-431c-4a1c-b2f4-8ca9653b7325.png)

```
m1 = vd.Mesh("../data/hole_filling_samples/frag_11.ply")
m = pymeshlab.Mesh(vertex_matrix=m1.points(), face_matrix=m1.faces(), v_normals_matrix=m1.pointdata["Normals"], v_color_matrix=np.insert(m1.pointdata["RGB"]/255, 3, 1, axis=1))

ms = pymeshlab.MeshSet()
ms.add_mesh(m)
ms.close_holes(maxholesize=30, newfaceselected=False)
# ms.save_current_mesh("ftest.ply")

mlab_mesh = ms.current_mesh()

reco_mesh = vd.Mesh(mlab_mesh)

vd.show(reco_mesh, axes=True, interactive=True).close()
```

My only problem is how to retrieve back the color from the `pymesh.Mesh` to the `vedo.Mesh`, I've tried:
```
color = mlab_mesh.vertex_color_matrix()[:, 0:-1]
reco_mesh = vd.Mesh(mlab_mesh, c=(color*255).astype(int)) # this works for the vd.Points()

self.property.SetColor(c)
TypeError: SetColor argument 1: expected a sequence of 3 values, got 216150 values
```

but it doesn't seem to work.

**Comment by marcomusy** [comment]
try:
`reco_mesh.pointdata["RGB"] = (color*255).astype(np.uint)`

**Comment by ttsesm** [comment]
Nope, it still gives me a textureless output:
![image](https://user-images.githubusercontent.com/10189018/146908623-1fadd323-da8c-4598-97d2-9a5ebd688175.png)

Though the `reco_mesh.print()` output has the color data:
```
Mesh/Points 
          color: gold, rgb=(1.00, 0.843, 0), alpha=1.0
         points: 1659264
          cells: 3310153
       polygons: 3310153
       position: (0.0, 0.0, 0.0)
          scale: (1.00, 1.00, 1.00)
 center of mass: (96.7, -14.1, 431)
   average size: 89.3928
  diagonal size: 329.789
         bounds: x=(-40.6, 229) y=(-68.9, 46.1) z=(349, 501)
    scalar mode: UsePointData   coloring = Default
   active array: 
     point data: name=RGB (3 UNSIGNED_LONG_LONG, np.uint64), range=(14.0,255)
```
It seems that it is not active, but using the `reco_mesh.select("RGB")` gives me `{AttributeError}'Mesh' object has no attribute 'select'`

**Comment by ttsesm** [comment]
ok, the correct command is `reco_mesh.pointdata.select("RGB")` and the type should `np.uint8` instead of `np.uint`:
![image](https://user-images.githubusercontent.com/10189018/146912456-7b946c36-7e40-4e5b-b517-75dbcff7568b.png)

Thanks, @marcomusy as usual really helpful :+1:

**Comment by marcomusy** [comment]
ops sorry I wrote my answer in a hurry and missed those two things!
