### ISSUE TITLE
reconstruct a mesh by points or cells with vertices

### ISSUE THREAD

**Issue by MianMianMeow** [marcomusy/vedo#566]
Hi Macro,
  I have some points with coordinates in numpy array, such as 

points = np.array([[x1, y1, z1], 
              [x2, y2, z2], 
               [x3, y3, z3], 
               [x4, y4, z4], 
               ...])

and cells with their vertices, such as

cells = np.array([[x11, y11, z11],[[x12, y12, z12],[[x13, y13, z13]],
                          [[x21, y21, z21],[[x22, y22, z22],[[x23, y23, z23]],
                          [[x31, y31, z31],[[x32, y32, z32],[[x33, y33, z33]],
                          ...])

Do you have any hints or are there any examples for reconstructing a mesh by these points or cells with vertices? Really appreciate for your reply.

**Comment by marcomusy** [comment]
Hi, You can simply do eg.:
```python
from vedo import *
msh = Mesh([points, cells]).color("blue")
show(msh, axes=1)
```

Check out for more examples like [examples/basic/buildmesh.py](https://github.com/marcomusy/vedo/blob/master/examples/basic/buildmesh.py).

**Comment by MianMianMeow** [comment]
Wow~This works for me perfectly.Thanks a lot.
