### ISSUE TITLE
How to show video frame by frame but also in vedo with interactive mode on?

### ISSUE THREAD

**Issue by Arthur151** [marcomusy/vedo#568]
Hi, @marcomusy. Long time no see. Vedo is quite nice! My user asks [a question](https://github.com/Arthur151/ROMP/issues/2#issuecomment-1002608338) that I don't know how...

Hi, wanna ask you a question. Do u know how to show video frame by frame but also in vedo with interactive mode on?

Something like I can switch the camera angle while predict realtime on videos.

**Comment by timeanddoctor** [comment]
yes, I think you can read this vedio as a numpy picture(opencv) and then show it in vedo with a timer obverser to refresh.

**Comment by marcomusy** [comment]
Hi @Arthur151 if you set `show(..., interactive=True)` vedo will show and then wait for interaction with user (like rotating the scene) and the python program flow will hang until user presses `q` or `spacebar`.
If you need the program to continue I would go with @timeanddoctor suggestion to create a time observer, see an example here:
https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback1.py
https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback2.py

**Comment by Arthur151** [comment]
@timeanddoctor @marcomusy Thanks for your reply! 
We will try it. 
Best,
Yu
