### ISSUE TITLE
Downsapling mesh data

### ISSUE THREAD

**Issue by Vaveyla95** [marcomusy/vedo#571]
hello developers

First of all I'm new and sorry my lack of experience. I have labeled 3D tooth model as vtp format I want to downsample these files and want to create a downsapled 3D tooth model data. How can i do?

**Comment by marcomusy** [comment]
hello user :)
you can do it with `mymesh.decimate()` method (see options in the [docs](https://vedo.embl.es/autodocs/content/vedo/mesh.html?highlight=decimate#vedo.mesh.Mesh.decimate)).

**Comment by Vaveyla95** [comment]
I did it for an sample. Do you think it is true?

```
import vedo
from vedo import *

mesh = vedo.load("/content/drive/MyDrive/tez/meshsegnet/Data/labeled/Sample_01.vtp")
output_save_path = '/content/drive/MyDrive/tez/meshsegnet/Data/downlabeled'
output_file_name = 'Sample_01_d.vtp'
if mesh.NCells() > 10000:
                print('\tDownsampling...')
                target_num = 10000
                ratio = target_num/mesh.NCells() # calculate ratio
                mesh_d = mesh.clone()
                mesh_d.decimate(fraction=ratio)
                vedo.io.write(mesh_d,  os.path.join(output_save_path, output_file_name))
```

**Comment by marcomusy** [comment]
Seems correct. You probably don't need to clone it and the double import looks a bit strange :)

> Will my labeled dataset still be labeled if the downsampling is done?

Yes.

**Comment by Vaveyla95** [comment]
How can I install vedo '2020.4.2' version using anaconda prompt

i think this code doesn't work
`conda install -c conda-forge vedo=2020.4.2`

**Comment by marcomusy** [comment]
it should work.. try otherwise
`pip install vedo==2020.4.2`
are you sure you need an old version?

**Comment by Vaveyla95** [comment]
Yeah. Unfortunately, I need to use this version for another project. Thank you for pip install vedo==2020.4.2

**Comment by mikkelmedm** [comment]
Hi @marcomusy 

Seems .decimate() destroys whatever labels are attributed to the mesh. 
When doing: 
`
vedo_mesh = vedo.utils.trimesh2vedo(mesh)
        
target_num = 16000
ratio = target_num/vedo_mesh.ncells
mesh_d = vedo_mesh.clone()
#mesh_d.cell_individual_colors(labels)
mesh_d.celldata["Label"]=labels
                
print(mesh_d.celldata["Label"]) 
mesh_d.decimate(fraction=ratio)

print(mesh_d.celldata["Label"]) `

The first print returns list of Labels, the latter print returns None.
Is there any way to hack this? Saw #620 did something similar, but for pointclouds only. 

Hope you can help

Cheers,
Mikkel

**Comment by marcomusy** [comment]
Hi Mikkel
here is a workaround to the fact that the upstream VTK is not preserving the cell information properly:
```python

from vedo import *

s = Sphere().linewidth(1)

# create some dummy cells colors as RGB
cols = np.array(color_map(s.cell_centers()[:,2]))* 255

s.cellcolors = cols
s.celldata["tmpcols"] = cols

print("--------- BEFORE decimate")
s.print()

s.map_cells_to_points()  ##TRICK

s.decimate(0.5, method="pro")  # kills celldata data only

s.map_points_to_cells()  ##TRICK

s.cellcolors = s.celldata["tmpcols"]
s.celldata.remove("tmpcols") # not needed anymore

print("--------- AFTER decimate")
s.print()

s.show(axes=1)
```

![Screenshot from 2022-12-15 17-44-43](https://user-images.githubusercontent.com/32848391/207924856-0fe44378-5392-422f-a441-e1364c1e415b.png)


Hope this works for you.
