### ISSUE TITLE
Zooming into image without smoothing

### ISSUE THREAD

**Issue by pauljurczak** [marcomusy/vedo#572]
I'm using Ubuntu 20.04.3, Python 3.8.10 and vedo 2021.0.7. I would like to run this code snippet:
```
from vedo import Picture

pic = Picture('lena.bmp')
pic.show()
```
and zoom into image without smoothing. I can't find relevant information in the documentation.

**Comment by marcomusy** [comment]
You may transform the image into a quad-mesh:
```python
from vedo import Picture

pic = Picture('https://people.math.sc.edu/Burkardt/data/bmp/lena.bmp')
msh = pic.tomesh().mapPointsToCells()#.lw(0.1)
msh.show(mode='image')
```
<img width="393" alt="Screenshot 2022-01-07 at 15 17 50" src="https://user-images.githubusercontent.com/32848391/148556960-a7e6cea4-3d96-4461-9282-9c02f0ebf639.png">

**Comment by pauljurczak** [comment]
Thank you, it works. Initially, I tried `tomesh()`, but didn't know about `mapPointsToCells()`.

**Comment by marcomusy** [comment]
Yes, that interpolates data (in this case rgb values) from mesh vertices to cells (pixels).
