### ISSUE TITLE
Batch mode for large number of text labels

### ISSUE THREAD

**Issue by pauljurczak** [marcomusy/vedo#573]
Running this code snippet:
```
import sys, itertools, vedo
from numpy.core.multiarray import arange
from time import perf_counter
from vedo import Picture, Text3D

pic = Picture('lena.bmp')
mesh = pic.tomesh().mapPointsToCells()
labels = []
t0 = perf_counter()

for x, y in itertools.product(arange(0.3, 99, 1), arange(0.4, 99, 1)):
  labels.append(Text3D('42', (x, y, 0), s=0.2))

t1 = perf_counter()
print(f'{t1-t0:.6f}s')
vedo.show(mesh, labels)
```
takes 3.7s to construct all text labels. 10K labels makes zoom a bit laggy on my PC. 1K labels take 0.5s to create and zoom is very smooth. Is there a way. e.g. batch mode, to create these labels faster and perhaps make display smoother?

**Comment by marcomusy** [comment]
Consider this variation:
```python
...
for x, y in itertools.product(arange(0.3, 99, 1), arange(0.4, 99, 1)):
  labels.append(Text3D('42', (x, y, 0), s=0.2))
labels = vedo.merge(labels) # this merges them into a single object
labels.write("mylabels.ply") # this saves them so you don't need to recreate
# labels = vedo.Mesh("mylabels.ply", c='black')
```

should solve both problems.

**Comment by pauljurczak** [comment]
Thank you. `vedo.merge` indeed makes zoom very smooth with large number of labels. Saving them to file is a good advice, but my use case is too dynamic for that. Is there a way to create a single object from the start, instead of applying `vedo.merge` to the list? 

Since the default font is pretty high quality, which I don't need, is there a simpler font, faster to create labels with? Even a line font would work.

**Comment by marcomusy** [comment]
If labels can be grouped like eg 2k are 42 you can create a Gliph()

**Comment by pauljurczak** [comment]
Unfortunately, the labels will have a large range of values. My example was just a quick and lazy first draft.

Using `VTK` font is almost 2x faster.

BTW, searching for `Gliph` produces no results: https://vedo.embl.es/autodocs/search.html?q=Gliph&check_keywords=yes&area=default

**Comment by pauljurczak** [comment]
You meant `Glyph`, most likely.

**Comment by marcomusy** [comment]
Yes sorry `Glyph()` but if labels are very different it will not help I'm afraid.. I' will think of a different solution.
Also check out the method `msh.labels(..., font="VTK")` could be slightly faster.

**Comment by pauljurczak** [comment]
I don't see `labels()` method on https://vedo.embl.es/autodocs/content/vedo/mesh.html. Am I looking at a right place?

Also, I tried 256K labels, and it brought Ubuntu to a standstill, so I had to reboot after waiting a few minutes. I have 32 GB of RAM and 6-core modern CPU.

**Comment by marcomusy** [comment]
If you use the search field (top-left) in the docs page you will find it:
https://vedo.embl.es/autodocs/content/vedo/pointcloud.html?highlight=labels#vedo.pointcloud.Points.labels

The labelling is thought to only render a few polygonal labels in the scene (say <1k), I don't think there is a viable way in vedo/VTK to render as many as 256k.. are you sure you need those? Wouldn't it be better generate them on the fly in a smaller area by clicking in the scene (?).

**Comment by pauljurczak** [comment]
> Wouldn't it be better generate them on the fly in a smaller area by clicking in the scene (?).

Of course. That's what I'm doing in my C++ visualization. I don't know how to accomplish it with vedo/VTK, though. Didn't know it was even possible. Can you point me to relevant documentation?

**Comment by marcomusy** [comment]
Maybe this example works for you, by clicking you visualize on the fly the pixel number within a radius:
```python
import vedo

pic = vedo.Picture('https://people.math.sc.edu/Burkardt/data/bmp/lena.bmp')
msh = pic.tomesh().mapPointsToCells()
cnt = msh.cellCenters()
pts = vedo.Points(cnt)
labels = None

def onclick(event):
  global labels
  if event.picked3d is None: 
      return
  ids = pts.closestPoint(event.picked3d, radius=10, returnPointId=True)
  ps = vedo.Points(cnt[ids])
  plt.remove(labels)
  labels = ps.labels(ids, scale=.15, font="Calco", justify="center").z(0.01).c('red5')
  plt.add(labels)

plt = vedo.Plotter()
plt.addCallback("mouse click", onclick)
plt.show(msh, labels)
```
<img width="814" alt="Screenshot 2022-01-08 at 18 24 25" src="https://user-images.githubusercontent.com/32848391/148653651-34364601-6eee-48a3-9c59-c78e4fc77ff1.png">

**Comment by pauljurczak** [comment]
Fantastic! I will do a few experiments with it. Thanks a lot.
