### ISSUE TITLE
Is there a way to change the color of a single mesh/vertice?

### ISSUE THREAD

**Issue by sherkt1** [marcomusy/vedo#575]
Just a simple call - or do we have to create an entire cmap and change one value?

Thanks.

**Comment by marcomusy** [comment]
If you already have a color array (per vertex or per face) you need to reassign it to the mesh object.

**Comment by sherkt1** [comment]
> If you already have a color array (per vertex or per face) you need to reassign it to the mesh object.

What variable should it be assigned to (example: vertices -> pts, faces -> faces)

**Comment by marcomusy** [comment]
Check out #555 
Instead of `celldata` you can use `pointdata`.
If you just need to highlight a specific point I would simply add a `Point()` object to the scene, and you choose its color.

**Comment by sherkt1** [comment]
Is celldata initialized when you create a mesh object? I'm looking at the documentation - pointdata and celldata exist but when I call, say, m = vedo.Mesh([vertices,faces]) and then call m.pointdata or m.celldata I get the message: 'Mesh' object has no attribute 'pointdata'

**Comment by marcomusy** [comment]
You may be using an old version?
This works for me:
```python

from vedo import Mesh, show
import numpy as np

verts = [(50,50,50), (70,40,50), (50,40,80), (80,70,50)]
faces = [(0,1,2), (2,1,3), (1,0,3)]

# Build the polygonal Mesh object:
mesh = Mesh([verts, faces])

mesh.celldata['mycolors']= np.array([[255,0,0],[0,255,0],[0,0,255]]).astype(np.uint8)
mesh.celldata.select('mycolors')

show(mesh, viewup='z', axes=1).close()
```
![Screenshot from 2022-01-10 17-45-05](https://user-images.githubusercontent.com/32848391/148804271-3ecc0e30-5c12-4bfb-bd29-09c66a7b783c.png)

**Comment by sherkt1** [comment]
`from vedo import Mesh, show
import numpy as np

verts = [(50,50,50), (70,40,50), (50,40,80), (80,70,50)]
faces = [(0,1,2), (2,1,3), (1,0,3)]

# Build the polygonal Mesh object:
mesh = Mesh([verts, faces])

mesh.celldata['mycolors']= np.array([[255,0,0],[0,255,0],[0,0,255]]).astype(np.uint8)
mesh.celldata.select('mycolors')

show(mesh, viewup='z', axes=1).close()
Traceback (most recent call last):

  File "<ipython-input-29-227f9d089e23>", line 10, in <module>
    mesh.celldata['mycolors']= np.array([[255,0,0],[0,255,0],[0,0,255]]).astype(np.uint8)

AttributeError: 'Mesh' object has no attribute 'celldata'`

**Comment by sherkt1** [comment]
This is the error that I am getting.

**Comment by marcomusy** [comment]
Try:
`pip install vedo -U`

**Comment by sherkt1** [comment]
Works now, thanks!
