### ISSUE TITLE
How to generate a curved plane by points?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#577]
I want to cut a surface into two parts. Then, I draw a line in the surface, for example:

![image](https://user-images.githubusercontent.com/29271051/149049043-d3a07eae-39c0-41cb-b298-95c25016a301.png)

As we know, three points are used to define a plane (`ax+by+cz=d`), and we can only fit it for more than 3 points. But, I want a curved plane for the drawn points. The curved plane can be a poly data rather than `ax+by+cz=d`. Is it possible?

Moreover, is it possible to edit this curve plane? Just like:

![image](https://user-images.githubusercontent.com/29271051/149049747-619d9ce0-ade5-4975-b05c-47a80bea2bc7.png)

Any suggestion is appreciated~~~

**Comment by marcomusy** [comment]
Hi have you already tried these examples:
```
examples/basic/cutFreeHand.py
examples/advanced/cutWithPoints1.py
examples/advanced/cutWithPoints2.py
```
