### ISSUE TITLE
Add noise to point cloud

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#580]
Hi @marcomusy,

Does vedo have any similar functionality to [this](https://github.com/tom-uchida/Add_Noise_to_Point_Cloud)?

So that someone could create some random noise on a point cloud either based on gaussian or outlier points:
![image](https://user-images.githubusercontent.com/10189018/150122193-3887c8f3-2163-49d7-8ec7-fc2ea2788f8f.png) 
![image](https://user-images.githubusercontent.com/10189018/150122279-2249af45-888c-40bc-9dd2-be55d77b01f9.png)

**Comment by marcomusy** [comment]
yes, try e.g.:
```python
from vedo import Mesh, show, dataurl
import numpy as np
mesh = Mesh(dataurl+'bunny.obj')
mesh.cmap('viridis', np.random.randn(mesh.N()))
cld = mesh.clone().subdivide(3).pointGaussNoise(2).ps(2).alpha(0.1)
show(mesh, cld, bg='k1')
```
![Screenshot from 2022-01-19 13-13-18](https://user-images.githubusercontent.com/32848391/150127395-956e1fa1-742b-48e4-aef2-3cd64403e683.png)

for the other you can use https://github.com/marcomusy/vedo/blob/b7a6a8a1ab7d9cb05f0cf725de9fff808939e9e5/vedo/mesh.py#L1403

**Comment by ttsesm** [comment]
Perfect!!!

For the outlier I did not mean whether a point is inside/outside a mesh but it seems to be a kind of noise type like Gaussian (see the second image in my initial message, or the link) where as I understand it the noise is just randomly around the initial points.
