### ISSUE TITLE
save mesh covered by texture as png file

### ISSUE THREAD

**Issue by ganjbakhshali** [marcomusy/vedo#582]
hello
I tend to save my mesh, that covered by texture, as a png file.
here is my code to load texture on obj file:
```
from vedo import *

mesh = Mesh("data/10055_Gray_Wolf_v1_L3.obj",) 

mesh.texture("data/10055_Gray_Wolf_Diffuse_v1.jpg", scale=0.1)

mesh.show()
```

Any help, Please.
I prefer to save png without background.

**Comment by marcomusy** [comment]
Just add
```
settings.screenshotTransparentBackground = True
# ...
mesh.show().screenshot('mypicture.png')
```

**Comment by ganjbakhshali** [comment]
That's very nice.
but I currently work with servers, and I cannot run show mesh and screenshot. (just accessing with ssh)
is there any other solution?

**Comment by marcomusy** [comment]
Try `offscreen` mode, eg:
```python
import vedo
mesh = vedo.Sphere()
plt = vedo.Plotter(offscreen=True, bg='lightblue', bg2='blue3')
plt += mesh
plt.show().screenshot()
```
![screenshot](https://user-images.githubusercontent.com/32848391/150638661-45e44b59-235b-4e49-a9d2-e3bf090f2c7c.png)

**Comment by ganjbakhshali** [comment]
Many thanks, but I cannot show anything on the server as I told you before.
Is there any way?

**Comment by marcomusy** [comment]
this will not show anything just dump a file named `screenshot.png`.

**Comment by ganjbakhshali** [comment]
Thank again.
it works on my local system but on the server; I got `Aborted (core dumped).`
anyway, I will find the solution.

**Comment by zhangsanfeng86** [comment]
> 

@ganjbakhshali  "it works on my local system but on the server; I got Aborted (core dumped)."

**Comment by ganjbakhshali** [comment]
I just leave this library and work with bpy lib

**Comment by marcomusy** [comment]
> > 
> 
> @ganjbakhshali "it works on my local system but on the server; I got Aborted (core dumped)." how do you solved?

I hope this will wok for you too:
https://github.com/marcomusy/vedo/discussions/621#discussioncomment-2481423

**Comment by kevink2424** [comment]
> > @ganjbakhshali "it works on my local system but on the server; I got Aborted (core dumped)." how do you solved?
> 
> I hope this will wok for you too: [#621 (comment)](https://github.com/marcomusy/vedo/discussions/621#discussioncomment-2481423)

@marcomusy  thank you  for ur reply
Could you show it in detail?

**Comment by marcomusy** [comment]
Please try:


1. install `libgl1-mesa` and `xvfb`:
```
 sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx  xvfb
```

2. execute on startup:
```bash
#!/bin/bash
# 
set -x
export DISPLAY=:99.0
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
sleep 3
set +x
exec "$@"
```

3.  save the bash script above as  `/etc/rc.local` (or any other file to be called) and use `chmod +x` to make it executable.
```python
plt = vedo.Plotter(offscreen=True)
plt += vedo.Cube()
plt.show()
plt.screenshot(filename)
```

**Comment by ganjbakhshali** [comment]
I will test it and let you know about the result.
Thanks again.
