### ISSUE TITLE
Line color not set correctly 

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vedo#583]
When attempting to create a red line using

```
from vedo import *

p = Plotter()
l = Line((0,0,0),(1,1,1))
l.lineWidth(10)
l.lineColor((1,0,0))

l.GetProperty().SetColor(1,0,0)

p += l

p.show()
```

I get a gray line (default):
<img width="326" alt="image" src="https://user-images.githubusercontent.com/34062862/151509044-bd8a528d-76b2-4680-aa4b-8875bd59c5f9.png">

To color the line red I need to call 
`l.GetProperty().SetColor(1,0,0)` while `mesh.lineColor` uses `SetEdgeColor()`.

So a simple fix for this case it to replace SetEdgeColor with SetColor, but this will probably break other uses.

**Comment by RubendeBruin** [comment]
`l.color((1,0,0))` does work. So maybe it is good the way it is now. It is just that previously the lineColor did work, but that may have been a bug.

**Comment by marcomusy** [comment]
Yes - i guess it makes sense to override `lineColor()` and `lc()` to call `color()` for `Line` objects... I'll give it a try!

**Comment by marcomusy** [comment]
..now this should work:
```python
from vedo import *
Line((0,0,0),(1,1,1)).lw(10).lc((1,0,0)).show()
```
so I close the issue for the moment!
