### ISSUE TITLE
Vertex color to texture

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#584]
Hi Marco,

I have some meshes in .ply format which contain the color information as a vertex color property. Is it possible to map this color as texture map and save these meshes as .obj files with the corresponding .mtl and texture map images as .png or .jpg files.

**Comment by marcomusy** [comment]
uhm ... creating a texture map from point-associated rgb data is not a trivial operation... it is not a simple conversion! What you can try is to create a `Picture` from a numpy square grid containing the colors and save it with `pic.write('mytexture.png')`.

**Comment by ttsesm** [comment]
hhmm, well it seems that Trimesh has already this functionality but I am facing the same issue as in https://github.com/mikedh/trimesh/issues/1289

For some reason the visual are getting lost after the porting.

**Comment by marcomusy** [comment]
..after having a second look at it I think there is no error... yet it cannot work because VTK is trying to interpolate distant values in the UV texture map, in spite of the interpolate=False directive
```python
import vedo
import numpy as np

vedo.settings.interpolateScalarsBeforeMapping=False

res=4

s = vedo.Sphere(res=res).lw(1)#.ps(20)
pts = s.points()
red = np.abs(pts[:,0])*255
gre = np.abs(pts[:,1])*255
blu = np.abs(pts[:,2])*255

s.pointdata["RGBA"] = np.c_[red,gre,blu].astype(np.uint8)
s.pointdata.select("RGBA")

n  = len(pts)
sn = int(np.sqrt(n))+1

gr = vedo.Grid(resx=sn, resy=sn).pos(0.5,0.5).wireframe(False)
rgb = np.zeros([gr.N(), 3]).astype(np.uint8)
rgb[:n] = s.pointdata["RGBA"]
gr.pointdata["RGBA"] = rgb
gr.pointdata.select("RGBA")

arr = np.flip(rgb.reshape([sn+1,sn+1,3]), axis=0)
pic = vedo.Picture(arr).write("t.png")

s2 = vedo.Sphere(res=res).lw(1)#.ps(20)
tcoords = gr.points()[:,(0,1)] + (0.0,0.0)
print(tcoords[:n])
s2.texture("t.png", tcoords=tcoords[:n], 
  interpolate=False, repeat=False,
)

vedo.show(
  s+s.labels('id'), 
  gr+gr.labels('id').c('white'), 
  pic,
  s2+s2.labels('id'), 
  N=4, sharecam=0, axes=1,
)
```
<img width="448" alt="Screenshot 2022-01-29 at 11 53 58" src="https://user-images.githubusercontent.com/32848391/151658392-7588eb9c-c393-4c7f-b1af-273c802fb550.png">

**Comment by ttsesm** [comment]
Hi Marco,

Thanks for the examples. What about trying to save the mesh as .obj file with an .mtl and the .png and then use the .obj loader to load everything? So I guess you can skip the VTK loading part? So in principle you can load the file with another program as well like a normal .obj mesh (I will need that, in any case).

I am not sure if what I am saying makes sense though but it should be possible. Did you check how the trimesh lib does that? It seems that it has the functionality there but the tiling of the colors seems to be mixing.

**Comment by ttsesm** [comment]
Here is also how he creates the data for the [`.mtl`](https://github.com/mikedh/trimesh/blob/dca5750c61c59ab537232188263e3a247c124342/trimesh/exchange/obj.py#L770) file in case you can understand a bit more.

**Comment by marcomusy** [comment]
the texture is already being saved as `t.png` in the above example, with vedo you cannot save the mesh as obj... so I guess you may need to use trimesh or that..
sorry if i cannot be more helpful than this...

**Comment by ttsesm** [comment]
Thanks Marco.
I will close this for now and I will update in case I have any progress.
