### ISSUE TITLE
extract a network from image

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#587]
Hi @marcomusy ,

I would like to create a graph network from the below image 
![image](https://user-images.githubusercontent.com/29662579/151651703-34ff50d3-7049-4809-83da-d780a2c275ac.png)

After loading the image file in vedo , I am not really sure how to proceed next. 
I want to remove the hexagonal cells and then binarize the image to extract the network.

```
from vedo import *
from skimage.io import imread


if __name__ == '__main__':
    f = os.path.join("input.png")
    raw = load(f)
    show(raw)


```
[image file](https://github.com/DeepaMahm/misc/blob/master/Fig4a.png) ([image source](https://static-curis.ku.dk/portal/files/243061789/PhysRevLett.124.208101.pdf))

Your suggestions will be really helpful.

**Comment by marcomusy** [comment]
..from a png image? you cannot!
what you can do is to create small tool which draws line segments on top of the image by clicking on it. From the clicked point coords and connectivity you may then recreate a network.
Check `examples/advanced/spline_draw.py`

**Comment by DeepaMahm** [comment]
Hi @marcomusy,

I'm sharing an example available in this [link](https://community.wolfram.com/groups/-/m/t/1555948) where a blood vessel network has been skeletonized and converted to a network from a jpeg file. Here the background is black.

In the example that I posted here, if I could convert the background (i.e hexagonal cells) to white I could proceed next.

**Comment by marcomusy** [comment]
..that's easier to do:
```python
from vedo import *
import numpy as np

pic1 = Picture("https://raw.githubusercontent.com/DeepaMahm/misc/2dfa555ea8a102fde0c644b6669428f0759a9dd5/Fig4a.png")

rgb = pic1.tonumpy()
intensity = np.sum(rgb, axis=2)/3

mask = np.where(intensity<150)
data = np.zeros_like(intensity).astype(np.uint8) 
data[mask] = 255

pic2 = Picture(data).write("mypic.png")
show(pic1, pic2, N=2, sharecam=0, axes=1)
```
<img width="666" alt="Screenshot 2022-01-29 at 14 24 44" src="https://user-images.githubusercontent.com/32848391/151662782-e08cec1f-9fb5-4cff-a048-30bbda351443.png">

image on the right is saved as `mypic.png`.

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,
Could you please let me know how to add a ScalarBar for the left image?
