### ISSUE TITLE
AttributeError: 'ViewInteractiveWidget' object has no attribute 'addCallback'

### ISSUE THREAD

**Issue by Davi93** [marcomusy/vedo#594]
Dear users,

I am using vedo to plot some scans of human heads, collected with an MRI scanner.  I threshold the data to keep only voxels associated to the head model, and remove noise.  I would like to get the xyz coordinates of where I click / where I place my mouse.  I have seen that there is an example, in 2d, that does something similar ([this one](https://github.com/marcomusy/vedo/blob/master/examples/volumetric/slicePlane1.py)).

I have tried to adapt it to my case but it doesn't run, it says:

```
AttributeError: 'ViewInteractiveWidget' object has no attribute 'addCallback'
```
And actually none of the examples that use a callback actually work.

The code in which I'd like to implement a callback that gives me the coordinates of the first non-zero voxel where I place my mouse on is:

```
from vedo import *
data_matrix = T1.get_fdata()[:,:,:,0].T

data_matrix = np.where(data_matrix > 200, data_matrix, 0)

vol = Volume(data_matrix, c='Greys')
vol.addScalarBar3D()

plt = show(vol, __doc__, axes=7, interactive = True)
plt
```

Thanks a lot

**Comment by marcomusy** [comment]
Hi, that happens because you are in a jupyter environment. Try:
`pip install -U git+https://github.com/marcomusy/vedo.git`
then
`plt = show(vol, __doc__, axes=7, backend=False)`
should pop up the opengl rendering window.

Does it work anyway running it from terminal?
