### ISSUE TITLE
Finding percentage and removing overlaping points in multiple point clouds

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#595]
Hi @marcomusy,

Is it possible to use vedo to find the percentage of overlapping points and remove them from multiple loaded point clouds?

For example in the image below:
![image](https://user-images.githubusercontent.com/10189018/153902106-5852cd00-7e49-47d2-b44a-79b8e695621d.png)
I have loaded 3 different point clouds (i.e. red, orange, yellow) which they overlap to each other. Then I would like to find how much do they overlap and keep only the points where there is not overlapping area.

```
import numpy as np
import vedo as vd
import natsort
from wcmatch import glob

folder = ./7-scenes-redkitchen/'
pcd_files = natsort.natsorted(glob.glob(folder + '**/*.ply', flags=glob.BRACE | glob.GLOBSTAR))

tranf_files = natsort.natsorted(glob.glob(folder + '**/*.txt', flags=glob.BRACE | glob.GLOBSTAR))

pcds = []
for i, input_path in enumerate(pcd_files):
    t = np.loadtxt(tranf_files[i], skiprows=1)
   pcd = vd.Points(input_path).color(i).applyTransform(t, reset=True)
   pcds.append(pcd)

   vd.show(pcds, axes=1).close()
```
[7-scenes-redkitchen.zip](https://github.com/marcomusy/vedo/files/8062413/7-scenes-redkitchen.zip)

**Comment by ttsesm** [comment]
I cannot find any `distanceTo()` method for the point clouds class :thinking:

**Comment by marcomusy** [comment]
you may need to 
`pip install -U git+https://github.com/marcomusy/vedo.git`
yet it will not work... I just remembered that at least one of the two object must have polygonal faces...

Luckily `closesPoint` can be fast enough (?)

```python
from vedo import *

pc1,pc2,pc3 = load('cloud_bin_?.ply')

#pc1.distanceTo(pcs2)  # not working
#pcs1.distanceTo(Sphere()) # ok but useless

dists12 = []
pb = ProgressBar(0, pc1.N())
for p in pc1.points():
    dists12.append(mag2(p-pc2.closestPoint(p)))
    pb.print()
pc1.cmap('Reds', dists12, vmin=0).addScalarBar()

show(pc1,pc2,pc3, N=3, axes=1)
```
![Screenshot from 2022-02-14 18-20-45](https://user-images.githubusercontent.com/32848391/153914120-1f6b8202-1c68-4354-bcf7-30b207821153.png)

**Comment by marcomusy** [comment]
with `2022.0.1.dev7` I get this error message:

`pc1.distanceTo(pc2)  # not working`

```
2022-02-14 18:32:36.040 (   0.566s) [        423DE740]vtkDistancePolyDataFilt:88     ERR| vtkDistancePolyDataFilter (0x55f02fa6fea0): No points/cells to difference from
```

**Comment by ttsesm** [comment]
Btw, in this version of vedo I noticed that the `vd.show().close()` doesn't seem to release the closed window. I do not know if this is  bug or something changed.

**Comment by marcomusy** [comment]
the close() thing is a bug in the vtk https://discourse.vtk.org/t/vtk9-1-0-problems/7094/3
I just pushed a new version where this should not happen and added a temporary settings option
`settings.hackCallScreenSize = True`
to control it better.

You are right about the Msh/Point issue, I completely forgot that I had already implemented it in the `Points` class:

```python
from vedo import *

pc1 = Points('cloud_bin_0.ply')
pc2 = Points('cloud_bin_1.ply')

pc1.distanceTo(pc2).addScalarBar()
print(pc1.pointdata.keys(), pc1.pointdata['Distance'].shape)

show(pc1, pc2, N=2, axes=1).close()

Sphere().show().close() # test
```
![Screenshot from 2022-02-14 19-07-26](https://user-images.githubusercontent.com/32848391/153925036-1191ea3f-2c04-4424-bf55-9fe694eff7fa.png)

**Comment by ttsesm** [comment]
Hhmm interesting, do you understand why after applying the transformations to each point cloud so that they align the `distanceTo()` returns nothing?
```
from vedo import *
import numpy as np

pc1 = Points('cloud_bin_0.ply').applyTransform(np.loadtxt('cloud_bin_0.txt', skiprows=1), reset=True)
pc2 = Points('cloud_bin_1.ply').applyTransform(np.loadtxt('cloud_bin_1.txt', skiprows=1), reset=True)

pc1.distanceTo(pc2).addScalarBar()
print(pc1.pointdata.keys(), pc1.pointdata['Distance'].shape)
```

**Comment by marcomusy** [comment]
oh that's really fishy... i need to investigate why is that!
as a temp workaround try:
```python
from vedo import *
import numpy as np

pc1 = Points('cloud_bin_0.ply').applyTransform(np.loadtxt('cloud_bin_0.txt', skiprows=1), reset=True)
pc2 = Points('cloud_bin_1.ply').applyTransform(np.loadtxt('cloud_bin_1.txt', skiprows=1), reset=True)

pc1a = Points(pc1)
pc1a.distanceTo(pc2).addScalarBar()
show(pc1a, pc2, axes=1)
```

**Comment by marcomusy** [comment]
This should now be fixed on the master branch, thanks again for reporting the issue which led to important revision of core aspects of the code.

**Comment by ttsesm** [comment]
Not to open another issue, is there a way to obtain the scale ratio between two pcds (or meshes) so that I can scale one to the same space as the other. I guess I could use their bounding boxes for that? Is there anything already implemented in vedo?

**Comment by marcomusy** [comment]
yes, you may use `mypcl.averageSize()` or `mypcl.diagonalSize()`

**Comment by ttsesm** [comment]
Lovely thanks, I am closing this now.
