### ISSUE TITLE
plotter's closeWindow() broken since version 2021.0.6?

### ISSUE THREAD

**Issue by ziruiw-dev** [marcomusy/vedo#596]
Hi,

I recently updated `vedo` from 2021.0.6 to the latest 2022.0.1 and found the `closeWindow()` function is kind of broken?

I am plotting things in a for loop like this:

```python
geometry_list = [a, b, c]

for g in geometry_list
    plt = vedo.Plotter()
    plt.show(g, interactive=True)
    plt.closeWindow()
```

this code works fine in version 2021.0.6, but fail to close the window in later versions (I tried 2021.0.7 and 2022.0.1). 

---
Specifically, in the latest version, the `show()` function still plot things, but `closeWindow()` doesn't close the previously opened window (the previous windows become frozen after a new one is created). As a result, we got more and more windows in this for loop.

I have pasted a minimal example below (modified from the [cube colour example](https://github.com/marcomusy/vedo/blob/master/examples/basic/colorcubes.py)):

```python
"""Show a cube for each available color name"""
import vedo

print(__doc__)
from vedo import Cube, settings
from vedo.colors import colors
from operator import itemgetter

sorted_colors = sorted(colors.items(), key=itemgetter(0))
cbs = []
for sc in sorted_colors:
    cname = sc[0]
    if cname[-1] not in "123456789": continue
    cb = Cube().lw(1).lighting('off').color(cname)
    cbs.append([cname, cb])

print(vedo.__version__)
for cb in cbs:
    plt = vedo.Plotter()
    plt.show(cb, interactive=True)
    plt.closeWindow()
```

I was wondering is it a bug or I am using it in a wrong way?

Best,
Ryan

**Comment by marcomusy** [comment]
Hi, thanks for reporting, indeed there is a problem see( [#595](https://github.com/marcomusy/vedo/issues/595#issuecomment-1039421590))
Try
`pip install -U git+https://github.com/marcomusy/vedo.git`

then

```python
import vedo
vedo.settings.hackCallScreenSize = True # true by default
vedo.Sphere().c('green').show().close()
vedo.Sphere().c('red4').show().close()
```
you should be able to close the windows

**Comment by ziruiw-dev** [comment]
Hi @marcomusy,

Thanks a lot for the prompt reply. Works like a charm! 

Best,
Ryan
