### ISSUE TITLE
Undesired warnings

### ISSUE THREAD

**Issue by nantille** [marcomusy/vedo#601]
With the recent release, some warnings are popping up and we want to have a way not show them.
Example: 
```
[vedo.utils.py:243] WARNING: you are setting non-existing alphaBitPlane to 1
[vedo.utils.py:243] WARNING: you are setting non-existing fonts_path to /opt/anaconda3/envs/iblviewer/lib/python3.8/site-packages/iblviewer_assets/fonts
```

**Comment by marcomusy** [comment]
You should remove the cause :)

Still you can access the logger and set the level you wish with e.g.:
`vedo.logger.setLevel(30)`

**Comment by nantille** [comment]
You are right. :) But the cause was unreported in earlier versions so it's better if we have control over this rather than users having warnings all over the place every time the tool is running.
