### ISSUE TITLE
Collapse short edges

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#607]
Hi @marcomusy,

Do you have any similar functionality to [this](https://pymesh.readthedocs.io/en/latest/api_local_mesh_cleanup.html#collapse-short-edges) in vedo?

Here is also the corresponding source code: https://github.com/PyMesh/PyMesh/blob/main/python/pymesh/meshutils/collapse_short_edges.py

Thanks.

**Comment by marcomusy** [comment]
Hi, no we do not.
A similar functionality would be offered by `.decimate()` but it's not the same thing.
It would not be difficult to implement it though - you just check the length of the face edges and move the 2 points to the average position in 3d, finally you make a call to `.clean()`.

**Comment by ttsesm** [comment]
> The functionality will be available in the next release.

Perfect, thanks Marco. 

I will close the issue then.
