### ISSUE TITLE
Curvature range

### ISSUE THREAD

**Issue by jo-mueller** [marcomusy/vedo#610]
I am playing around with the vedo library a bit and find it super helpful to work with surfaces. In particular, I turn point clouds into surfaces with `recoSurface()` and then measure curvatures with the `addcurvatureScalar()` function and the Gaussian curvature method.

The visualized surface looks like this:

![Screenshot 2022-03-04 145827](https://user-images.githubusercontent.com/38459088/156776693-9f213154-20ff-43e1-8884-5cf4fe2cc1d9.jpg)

According to the definition of the curvature method, the algorithm takes into account the edges connecting an individual vertex with its neighbours. I was wondering if it was possible to increase the range within which points will be considered as neighbours and thus calculate the curvature in a bit more global fashion? Because for a sufficiently large amount of points, any surface will appear locally flat (as in the screenshot), but I'm more interested in the larger-scale curvatures.

Do you have a suggestion on how to do this? Any tips are greatly appreciated :)

**Comment by marcomusy** [comment]
Hi, Thanks for your interest!

There are 3 different metrics for curvature but as you say they mostly grab the local curvature of the neighbor vertices.
So I see a few options to get a sort of "wider-range" measurement.

One could be to smooth out your mesh surface to make the neighbor vertices more representative of the average region around them. This can be done with `mesh.smooth()`. You can also `subdivide()` your mesh which has a similar effect (check out `examples/advanced/mesh_smoother2.py`.

There is also the possibility to explicitly fit a sphere to a 3d point cloud (this is done analytically in `vedo` so it's very fast), from that you can extract the curvature (inverse of the radius) of any region of your choice, here you have an example with a random mesh (actually a mouse limb shape). Click on the surface to fit 20 points:

```python
from vedo import *
from vedo.pyplot import histogram

#msh = Torus()
msh = Mesh(dataurl+'290.vtk').scale(100)

msh.addCurvatureScalars( method=2 ).print()
name = 'Maximum_Curvature' # names: Gauss_Curvature Mean_Curvature Maximum_Curvature
msh.cmap('PRGn', name, vmin=-0.01, vmax=0.01)
msh.addScalarBar()

txt = Text2D(bg='yellow', font='Calco')

arr = msh.pointdata[name] # numpy array
histo = histogram(arr, bins=50)

def func(event):
    p = event.picked3d
    if p is None:
        return
    pts = msh.closestPoint(p, N=20)
    pts = Points(pts, r=6)  # make it a vedo object
    s = fitSphere(pts).alpha(0.1)
    txt.text(f'radius: {s.radius}\nresidue: {s.residue}')
    plt.add([s, pts])

plt = Plotter(N=2, sharecam=False)
plt.addCallback('mouse click', func)
plt.show(msh, txt, at=0)
plt.show(histo, at=1)
plt.interactive().close()
```
![Screenshot from 2022-03-04 15-50-06](https://user-images.githubusercontent.com/32848391/156786161-79b4c619-8265-44eb-ac5f-4d46bf1217a5.png)

**Comment by marcomusy** [comment]
> I would like to keep the surface density of vertices constant; I currently do this with the `densify()` function.

oh clever! Aside from (or along with) `densify()` you can also use `clean(tol=...)` with tol being a fraction of the bounding box size (a meaningful value is typically around 0.02) with ensure that any 2 points in the pointcloud will be at least separated by that distance... this will make the cloud very nice and uniform!

**Comment by jo-mueller** [comment]
> I could then iterate over all the vertices on the surface, extract all neighbors within a defined range and fit a sphere to these. I'll try this and let you know 👍

This is where I end up with this, which is pretty much what I had in mind:

![Screenshot 2022-03-04 145827](https://user-images.githubusercontent.com/38459088/156799475-b9997d33-25a6-422f-a954-92e963a67e69.jpg)

Would you be interested in having this included as a small example script on the documentation pages?

> you can also use clean(tol=...) with tol being a fraction of the bounding box

I tried that, too, like this:
```Python
pts4vedo = vedo.Points(my_point_array).clean(tol=0.02).densify(targetDistance=0.25)
```

but I'm receiving a warning there:

```
[vedo.pointcloud.py:1581] WARNING: clean(tol=...), please use subsample(fraction=...)
```

Can I ignore/turn off this warning somehow? I assume that subsample operates on the point cloud such that it removes every k-th vertex whereas clean operates on a distance criteria so the distance-based operation would be the way to go for me.

Also, another follow-up question: It should be possible to determine the sign of the curvature from the curve-fitting approach from above by comparing the normal vector at the point of interest `n_i` with the vector of the fitted sphere towards this point `v`. The sign of `np.dot(n_i, v)` should correspond to the sign of the curvature - right? Or is there a simpler way to do this in vedo?

**Comment by marcomusy** [comment]
> Would you be interested in having this included as a small example script on the documentation pages?

Sure - feel free to submit a PR.

> I'm receiving a warning there:

oh OK you are already using the latest version... so forget `clean()` it's just a renaming.

> It should be possible to determine the sign of the curvature 

Yes! You can do it the way you just describe using the normals (`mesh.computeNormals()` and `mesh.normals()` to get the numpy array).

**Comment by marcomusy** [comment]
BTW, be careful that in the transition from positive to negative radii there is a ..zero! You will notice that if you try fitting a very flat region you actually get a small (and unstable) radius. That's why you may also want to consider the fit residue.

**Comment by ttsesm** [comment]
@jo-mueller I am also interested in this. I would be happy if you could share an example for this.

**Comment by jo-mueller** [comment]
There goes :) I'm not so seasoned on visualizing with vedo, though.
