### ISSUE TITLE
Can vedo be used in server/docker without desktop and ui?

### ISSUE THREAD

**Issue by ZhengdiYu** [marcomusy/vedo#614]
I got would always get 'aborted' before I call `plt.show(camera=camera_pose).screenshot() #elevation=10,azimuth=0,,bg=self.bg_path`

**Comment by joshy** [comment]
See issues https://github.com/marcomusy/vedo/issues/88 and https://github.com/marcomusy/vedo/issues/609

**Comment by ZhengdiYu** [comment]
Thanks
