### ISSUE TITLE
Changes in Function Names

### ISSUE THREAD

**Issue by mirickmi** [marcomusy/vedo#617]
Hi, 

I tried to reproduce the simple Point Cloud to Mesh Example (https://github.com/marcomusy/vedo/blob/master/examples/advanced/recosurface.py). However, several functions are not recognised, e.g. at() from the Plotter() class and addGaussNoise() from the Points() class. Looking into the module "pointcloud.py" file I noticed that addGaussNoise() was renamed to pointGaussNoise(). The docs (https://vedo.embl.es/autodocs/content/vedo/pointcloud.html) list the function addGaussNoise() while the example displays pointGaussNoise(). I cannot access deprecated function names. 
I'm using vedo v2022.1.0

**Comment by marcomusy** [comment]
Hi, yes, sorry i'm in a transition, if you do from command line
`vedo --run recosurface`
should pick your local version.

Or - maybe simpler -  you can update to the dev version with:
`pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by mirickmi** [comment]
Sorry, I'm fairly new to Python. Thank you kindly!
