### ISSUE TITLE
Disable transformation in actor mode

### ISSUE THREAD

**Issue by thatuserb** [marcomusy/vedo#618]
Is there a way to disable the transformation of one specific actor in actor mode?

#### Background
I am trying to implement a simpler version of the [CutterTool](https://github.com/marcomusy/vedo/blob/master/examples/basic/cutter.py) because the on-the-fly calculations limit the usability for very large meshes. So instead of showing the cutting effect and updating the large mesh, I only want to move a simple mesh, whose interior will be selected later.
I thought about using the actor mode for this, because retrieving the final transformation is easy. The problem is that the user would also be able to move the large mesh this way. Is there any way to disable the transformation for one specific actor only or a different approach to achieve this behavior?

**Comment by marcomusy** [comment]
yes, use `mesh_not_to_move.pickable(False)`.
