### ISSUE TITLE
Error when running examples 

### ISSUE THREAD

**Issue by NahomKidane** [marcomusy/vedo#619]
Hi 
I am trying to run the examples and am getting this error. Any idea? 

AttributeError: 'vtkRenderingOpenGL2Python.vtkWin32RenderWindowInte' object has no attribute 'SetDone'

**Comment by marcomusy** [comment]
Uhm interesting .. what version of vtk are you running?

Try to remove the call to `.close()` in the example.

**Comment by NahomKidane** [comment]
edit:
oh. well, that didn't work. still getting the same error.

Graphic window pops for second and closes back and I get 'vtkRenderingOpenGL2Python.vtkWin32RenderWindowInte' object has no attribute 'SetDone'.

removing close makes the screen visible but it crushes
