### ISSUE TITLE
Keep the labels when downsampling dan upsampling

### ISSUE THREAD

**Issue by s-triar** [marcomusy/vedo#620]
Hi I have vtp data with labels in it. 
I did downsampling, but the labels was gone.
I think everything in celldata is gone because the labels is in celldata['labels']

**Comment by s-triar** [comment]
sorry I am late. The email notification did not come to my laptop. It needed to re-authenticate apparently.
the code you suggested is working. However, my labels are on celldata not point data.

> Hi thanks for reporting, I think there is a bug in the upstream vtk.. if change the method it should work though
> 
> ```python
> from vedo import Sphere
> 
> s = Sphere().lw(1)
> 
> pts = s.points()
> s.pointdata['labels'] = pts[:,0]
> s.pointdata.select('labels')
> 
> s.show(axes=1) # press q
> 
> s.decimate(method='pro')
> s.show(axes=1)
> ```

**Comment by marcomusy** [comment]
..uhm even stranger the filter works with point data but not celldata.. you can still use this trick:
```python

from vedo import Sphere

s = Sphere().lw(1)

pts = s.cellCenters()
s.celldata['labels'] = pts[:,0]
s.mapCellsToPoints()
s.pointdata.select('labels')
s.print()
s.show(axes=1) # press q

s.decimate(method='pro')
s.mapPointsToCells()
s.print()
s.show(axes=1)
```
<img width="432" alt="Screenshot 2022-04-10 at 16 38 54" src="https://user-images.githubusercontent.com/32848391/162624682-97176f17-521f-49bb-af8f-6e0c09c6dd8b.png">

**Comment by s-triar** [comment]
It works like a magic. But, the labels are like this after decimation. For me it is okay because the majority of the labels is on the right place.
![image](https://user-images.githubusercontent.com/34316314/162648399-771bd323-ee5f-4a0e-8b58-e56a9217e44e.png)

**Comment by marcomusy** [comment]
I think what happens is that for close-by cells at the boundary of 2 regions the interpolations goes continuously from one value to the other instead of jumping..

**Comment by s-triar** [comment]
Oh I see
