### ISSUE TITLE
Boolean ("intersect") returns error when one shape completely encloses the other.

### ISSUE THREAD

**Issue by MPBAUSER** [marcomusy/vedo#623]
Hey, sorry to bother again. 
If I try to get the intersection of a cylinder thats completly enclosed by a sphere I get the following error:

`2022-04-09 17:44:59.152 (   0.694s) [                ]    vtkPointLocator.cxx:845    ERR| vtkPointLocator (000002BB44D86EE0): No points to subdivide`
`2022-04-09 17:44:59.208 (   0.750s) [                ]vtkIntersectionPolyData:2410  WARN| No Intersection between objects `
`2022-04-09 17:44:59.214 (   0.755s) [                ]vtkDistancePolyDataFilt:82     ERR| vtkDistancePolyDataFilter (000002BB44DA4D00): No points/cells to operate on`
`2022-04-09 17:44:59.219 (   0.761s) [                ]vtkDistancePolyDataFilt:82     ERR| vtkDistancePolyDataFilter (000002BB44DA4D00): No points/cells to operate on`

My code looks like this:

`from vedo import *`
`shape1 = Cylinder(pos=(0.2,0.2,0.2), r=0.25, height= 0.7).triangulate()`
`shape2 = Sphere(pos=(0,0,0), r =2).triangulate()`
`intersection = shape2.boolean("intersect", shape1)`
`plt = Plotter(shape=(2,2), axes=3,)`
`plt.show(shape1, "cylinder", at=0)`
`plt.show(shape2, "Sphere", at=1)`
`plt.show(shape1, shape2, "sphere_and_cylinder", at=2,)`
`plt.show(intersection, "Intersection", at=3)`
`plt.interactive().close()`

In this case, can I receive the complete cylinder as an output?
Thanks a lot in advance.

**Comment by marcomusy** [comment]
for some reason the filter needs that there is at least an intersection.. to avoid the warning you can check that shape2 is inside shape1 with `insidePoints()` e.g.

`print(shape2.insidePoints(shape1.points()).N()==shape1.N())`

**Comment by MPBAUSER** [comment]
Well thats quite the simple solution should have thought of that myself. Thanks a lot for answering anyways.
