### ISSUE TITLE
key error in jupyter notebook using brainrender

### ISSUE THREAD

**Issue by Thimotek** [marcomusy/vedo#625]
Hello,

I am very new to these things thus sorry if I am not giving you enough informations about the issue !

to resume

I am trying to plot the coordinate of a group of cells in a 3D brain by using brainrender with jupyter notebook

I am using an anaconda environnement with the version 3.7.0 of python and the version of my anaconda navigator is 1.9.6.

my scirpt is working until this entry :
```
---
#Get a numpy array coordinates of some labelled cells
scene = Scene(title='area_cell') 
MOx = scene.add_brain_region("MO", alpha=0.15)
SSx = scene.add_brain_region("SS", alpha=0.15)
VISx = scene.add_brain_region("VIS", alpha=0.15)
#STRx = scene.add_brain_region("STR", alpha=0.15)
```
and this is my error message : 
```
---
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16228\2284008602.py in <module>
      1 #Get a numpy array coordinates of some labelled cells
----> 2 scene = Scene(title='area_cell')
      3 MOx = scene.add_brain_region("MO", alpha=0.15)
      4 SSx = scene.add_brain_region("SS", alpha=0.15)
      5 VISx = scene.add_brain_region("VIS", alpha=0.15)

~\Anaconda2\envs\plot3Dbrain\lib\site-packages\brainrender\scene.py in __init__(self, root, atlas_name, inset, title, screenshots_folder, plotter, title_color)
     48             f"Creating scene with parameters: root: {root}, atlas_name: '{atlas_name}'', inset: {inset}, screenshots_folder: {screenshots_folder}"
     49         )
---> 50         JupyterMixIn.__init__(self)
     51 
     52         self.actors = []  # stores all actors in the scene

~\Anaconda2\envs\plot3Dbrain\lib\site-packages\brainrender\_jupyter.py in __init__(self)
     10     def __init__(self):  # pragma: no cover
     11         # keep track if we are in a jupyter notebook
---> 12         if vedo.settings.notebookBackend == "k3d":
     13             self.backend = "k3d"
     14         elif vedo.settings.notebookBackend == "itkwidgets":

~\Anaconda2\envs\plot3Dbrain\lib\site-packages\vedo\utils.py in __getattr__(self, k)
    236 
    237     def __getattr__(self, k):
--> 238         return self[k]
    239 
    240     def __setattr__(self, k, v):

KeyError: 'notebookBackend'
--- 
```
I tried unsuccessfully to understand what was going wrong and to find someonne with the same issue, thus if you have idea it would be great !

also let me know if you need more informations,

Thanks

**Comment by marcomusy** [comment]
Have you tried already:
```
pip install vedo==2021.0.5
```

**Comment by Thimotek** [comment]
Hello, 
it worked thanks ! 

now i have this error : 

---
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15740\1447920217.py in <module>
----> 1 coordinates1 = get_points_in_region(MOx , pts1)
      2 coordinates2 = get_points_in_region(SSx, pts1)
      3 coordinates3 = get_points_in_region(VISx, pts1)
      4 #coordinates4 = get_points_in_region(STRx, pts1)

~\AppData\Local\Temp\ipykernel_15740\1525844472.py in get_points_in_region(region, pts1)
      6 
      7     ipts = region.insidePoints(pts1).points()
----> 8     return np.vstack(ipts)

<__array_function__ internals> in vstack(*args, **kwargs)

~\Anaconda2\envs\plot3Dbrain\lib\site-packages\numpy\core\shape_base.py in vstack(tup)
    280     if not isinstance(arrs, list):
    281         arrs = [arrs]
--> 282     return _nx.concatenate(arrs, 0)
    283 
    284 

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: need at least one array to concatenate

---
 for this part of the script 

---
coordinates1 = get_points_in_region(MOx , pts1)
coordinates2 = get_points_in_region(SSx, pts1)
coordinates3 = get_points_in_region(VISx, pts1)
#coordinates4 = get_points_in_region(STRx, pts1)
---

I guess this is just about how I am trying to concatenate my data, actually it is like this 

---
#getting row and column size information in a panda dataframe
import pandas as pd
df=pd.read_csv("C:/Users/thimo/Desktop/mémoire/distribution/coordinate/nkxcre/p21/521/NkxcreRCE-APP-Brain1.2.csv")
cells = pd.DataFrame(dict(x=df.iloc[1:8361,8], y=df.iloc[1:8361,7], z=df.iloc[1:8361,6]))
#cells = pd.DataFrame(dict(x=df['ML_location'], y=df['DV_location'], z=df['AV_location']))

index = cells.index
number_of_rows = len(index)
print(number_of_rows)

import numpy as np
pts = cells.to_numpy() #converting the variable cells to an array call points
type(pts)

---
 I think I can fix it but if you have any ideadwould be cool !

**Comment by marcomusy** [comment]
Sorry I have no idea - this is not related to vedo but to `brainrender`.

Please use triple-inverted quotes to format your post correctly so they are easier to read!
