### ISSUE TITLE
How to extract binary mask from points?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#627]
I have a region of interesting (some points), and I want extract the binary mask from these points. 

For example:

![image](https://user-images.githubusercontent.com/29271051/163401430-7d07b5df-fddc-484d-9a4d-82bf1d37e901.png)

I have the points (red line), and I want to obtain the binary mask under these points. 

How can I implement this require using `vedo`?

**Comment by marcomusy** [comment]
hi did you close the issue because you solved it already?

**Comment by zhang-qiang-github** [comment]
Because I find another way to exclude this requirement. Or, could you please have some time to tell me how can I implement this requirement using `vedo`? So I can have a deeper understand into `vedo`.

**Comment by marcomusy** [comment]
it looks doable, a wise combination of [frehandcutplotter](https://github.com/marcomusy/vedo/blob/master/examples/basic/cutFreeHand.py) and `volume.binarize()` should do the job :)
