### ISSUE TITLE
Get the color value of the vertices 

### ISSUE THREAD

**Issue by Amin-Fakia** [marcomusy/vedo#637]
Hello,
is there a way to get the color values (in RGBA) from the mesh after applying the color map ? if not, i have a list of the scalar values, is there anyway to convert them into color values ?
thanks for your time
![image](https://user-images.githubusercontent.com/66644985/166461624-b0592850-127d-482f-969f-5ed226a66390.png)

**Comment by marcomusy** [comment]
Hi - it's an interesting addition, in the meanwhile you can do:
```python

from vedo import *

def getRGB(actor, alpha=True, on='points'):
    lut = actor.mapper().GetLookupTable()
    poly = actor.polydata(transformed=False)
    if 'point' in on:
        vscalars = poly.GetPointData().GetScalars()
    else:
        vscalars = poly.GetCellData().GetScalars()
    cols =lut.MapScalars(vscalars, 0,0)
    arr = utils.vtk2numpy(cols)
    if not alpha:
        arr = arr[:, :3]
    return arr

s = Sphere()
s.pointdata['TestArrayPoints'] = s.points()[:,2]
s.celldata['TestArrayCells'] = s.cellCenters()[:,2]

s.pointdata.select("TestArrayPoints")
s.cmap("bone")

print(getRGB(s, on="points"))
s.show(axes=1)
```

**Comment by Amin-Fakia** [comment]
thank you so much, i have eventually figured the code out on myself, but this is definitly a much better version
