### ISSUE TITLE
mesh texture 

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#638]
DATA(rename `txt` to `zip`):
[mesh_tex.txt](https://github.com/marcomusy/vedo/files/8618771/mesh_tex.txt)

CODE:

```
from vedo import *

path_pfx = "/home/lab0/Pictures/mesh_tex"
path_obj = path_pfx + "/pro_img_ds_HR_00000_0.obj"
path_ply = path_pfx + "/cv_img_du_00000_0_mesh_inC.ply"
path_opt = path_pfx + "/pro_img_ds_HR_00000_0_opt.ply"
path_tex = path_pfx + "/img_c_ortho_HR_00000_0.png"

plt = Plotter(shape=(1, 3), size=(800, 600))
M1 = Mesh(path_obj).texture(path_tex)
M2 = Mesh(path_ply).c((200, 200, 200))
M3 = Mesh(path_opt).c((200, 200, 200))
plt.show(M1, at=0)
plt.show(M2, at=1)
plt.show(M3, at=2)
plt.show(interactive=True, zoom=1.0)
```

RESULT:

![screenshot](https://user-images.githubusercontent.com/34391447/166645228-b36cae54-4551-4ada-976d-b12e5aea1bcb.png)

QUESTIONS:

1. how to fix the texture mapping
2. how to remove the two vertical lines (borderless mode)
3. how to set zoom to fit the height like the following (I adjust it manually)

![screenshot](https://user-images.githubusercontent.com/34391447/166645593-89b650ce-06f4-4fda-be49-0ca26428bd03.png)

**Comment by marcomusy** [comment]
I would write it this way:
```python
from vedo import *

path_pfx = "."
path_obj = path_pfx + "/pro_img_ds_HR_00000_0.obj"
path_ply = path_pfx + "/cv_img_du_00000_0_mesh_inC.ply"
path_opt = path_pfx + "/pro_img_ds_HR_00000_0_opt.ply"
path_tex = path_pfx + "/img_c_ortho_HR_00000_0.png"

settings.rendererFrameAlpha = 0

plt = Plotter(shape=(1, 3), size=(800, 600))

M1 = Mesh(path_obj)
tcoords = M1.pointdata["Material"]
M1.texture(path_tex, tcoords=tcoords)

M2 = Mesh(path_ply).c((200, 200, 200))
M3 = Mesh(path_opt).c((200, 200, 200))
cam = dict(  # press shift-C in the scene to dump these numbers
    pos=(6.743e-3, -0.09617, 1.069),
    focalPoint=(6.743e-3, -0.09617, -2.190),
    viewup=(0, 1.000, 0),
)
plt.at(0).show(M1)
plt.at(1).show(M2)
plt.at(2).show(M3, camera=cam)
plt.interactive().close()
```
<img width="404" alt="Screenshot 2022-05-04 at 11 41 28" src="https://user-images.githubusercontent.com/32848391/166658348-a5f79047-0ab7-45c5-917c-705257a2631f.png">

It would be nice to have tcoords accept a string - so I will add this as enhancement feature so that the above can become
`M1.texture(path_tex, tcoords="Material")`

**Comment by ttsesm** [comment]
Hi @marcomusy not to open another issue, I also have a problem loading my texture. For example the loaded texture in Meshlab looks like this:

![image](https://user-images.githubusercontent.com/10189018/166660307-7d600da2-16a0-4264-87db-5036ec457573.png)
but then in vedo I am getting the following result:
![image](https://user-images.githubusercontent.com/10189018/166660512-b52aa95d-238b-4e25-aeb6-2d88fa744ac9.png)

I used the code that you have above or `msh = Mesh("path_to_file.obj").texture("path_to_file.png")` but didn't work. Example sample you can download from [here](https://filesender.garr.it/?s=download&token=2fe3e2ff-3ead-42e5-becb-fcb4c1862ebd).

**Comment by marcomusy** [comment]
@ttsesm  The same code works for you as well!
```python
from vedo import *

M1 = Mesh("RPf_00204.obj").print()
tcoords = M1.pointdata["material_0"]
M1.texture("RPf_00204.png", tcoords=tcoords)

show(M1).interactive().close()
```

<img width="366" alt="Screenshot 2022-05-04 at 12 06 49" src="https://user-images.githubusercontent.com/32848391/166662515-13e4f3b6-83d6-4a20-b0e1-ef3c09f06d5d.png">

**Comment by ttsesm** [comment]
Yes, you are right. My apologies, I was not using the correct "key" name from the pointdata.

**Comment by marcomusy** [comment]
> Yes, you are right. My apologies, I was not using the correct "key" name from the pointdata.

no worries! :)
