### ISSUE TITLE
Inpainting missing texture

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#639]
Hi Marco,

Do you by any chance have any idea whether there is the possibility to fill/impaint a missing part of a texture?

For example in the [following mesh](https://filesender.garr.it/?s=download&token=2fe3e2ff-3ead-42e5-becb-fcb4c1862ebd) you can see that the bottom part is missing the bottom part:
![processed_](https://user-images.githubusercontent.com/10189018/166701821-4477315d-ffc8-4343-a982-f39a6b549a39.gif)

any idea if I could impaint this part from the surrounding existing texture?

**Comment by marcomusy** [comment]
cool gif !
No, i'm afraid yuo would need to provide the texture coordinates that are appropriate for the texturing, i see no "automatic" way of doing it.

**Comment by ttsesm** [comment]
I see. Yes it is not an easy task, but I just wanted to ask in case you were aware of something.

Thanks.
