### ISSUE TITLE
howo to repaire the isosurface result?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#641]
I use `isosurface` to display the vessel in brain, and the result is:

![image](https://user-images.githubusercontent.com/29271051/167248700-58c6e36d-2ce1-4ff8-aa1a-b2835829842d.png)

In theory, the vessel should be a tube thing. But the `isosurface` extracted result has some hole. 

Is there any method to repaire the result? Manual or automatical is acceptable.

**Comment by marcomusy** [comment]
Hi, there is a `.fillHoles()` method but in your case it would be useless.
Your mesh is quite irregular, I don't think there exist an automated way to fill _just_ that part without creating artefacts elsewhere..
_Maybe_ you dont need that! ... maybe in your analysis pipeline you can create a tube by the centerline? if that's the case, you can either do it manually (in vedo by clicking points) or automatically with a number of tools that exist (outside vedo).

**Comment by zhang-qiang-github** [comment]
Thank you for your suggestions.
