### ISSUE TITLE
rendering & area & overlap

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#646]
How to calculate the ratio of the rendered depth map to the entire mesh?

**Comment by LogWell** [comment]
[This](https://github.com/prs-eth/OverlapPredator/blob/770c3063399f08b3836935212ab4c84d355b4704/scripts/cal_overlap.py#L31) is a little simple and rough.

**Comment by marcomusy** [comment]
Not sure if I understand what you are after .. maybe this is relevant:
https://github.com/marcomusy/vedo/blob/9eae35cfe4f58897dff378f02123f3828a92fe49/vedo/pointcloud.py#L41
