### ISSUE TITLE
Vedo with vtk 9.1

### ISSUE THREAD

**Issue by p-j-smith** [marcomusy/vedo#647]
Hi, I would like to use vedo with either PyQt6 or PySide6. However, vtk < 9.1 does not support Qt6. I'm wondering whether it would be possible to bump the required vtk version to include 9.1.0?

Thanks!

**Comment by marcomusy** [comment]
Hi, I restricted the vtk version because the rendering of transparent objects is poor in vtk 9.1, but in principle you can force it with 
`pip install vtk==9.1.0` 
and vedo should work ok with that too, just ignore the warnings.
I hope those issues will be fixed in the coming vtk version.

**Comment by p-j-smith** [comment]
okay great, thanks for the quick response :)
