### ISSUE TITLE
Mesh merge(Flag=True) doesn't keep the original coloring of individual meshes

### ISSUE THREAD

**Issue by lukablagoje** [marcomusy/vedo#652]
Hi, 

When I use the merge function for a colored list of meshes, the meshes change their original color (even if flag=True). Example code:

```
from vedo import show,Tube,merge

color_list = ['#FF0000','#1CE6FF']
tube_list = []
points_start = [[0,0,0],[30,30,30]]
points_end = [[25,25,25],[50,50,50]]
for i in range(0,2):
    tube_list.append(Tube([points_start[i],points_end[i]],c=color_list[i],r=8,res=30))


merged_tube = merge(tube_list,flag=True)
```

If I use show with a list:
`show(tube_list)`

The color of individual tubes is different when the merged mesh is shown:
`show(merged_tube)`

How can I keep the original colors before the merge is applied?

Thanks

**Comment by lukablagoje** [comment]
Thanks, I have a follow-up question - If I want to do this for the case of multiple tubes:

`from vedo import Tube, merge, show, buildLUT

color_list = ["#FF0000", "#1CE6FF",'#FF34FF']
tube_list = []
points_start = [[0, 0, 0], [30, 30, 30],[60,60,60]]
points_end = [[25, 25, 25], [50, 50, 50],[80,80,80]]
for i in range(0, 3):
    t = Tube([points_start[i], points_end[i]], c=color_list[i], r=8, res=30)
    tube_list.append(t)

merged_tube = merge(tube_list, flag=True)
merged_tube.print()

show(tube_list).close()

c1, c2, c3= color_list
lut = buildLUT([[0, c1], [1, c2],[2,c3]])
merged_tube.cmap(lut)

show(merged_tube).close()
`
How do I create a color map that can achieve this (in this case, 0 integer color is kept, while everything else is the other color)?

Thanks again!

**Comment by lukablagoje** [comment]
Hi, thanks for the comprehensive responses. I managed to create a merged meshed (composed of other colored meshes). 

The final problem I'm encountering in my project is that I cannot correctly save the mesh. I've tried many formats, it seems that ".vtp" saves the colors, but it changes some of the colors when it's loaded. 

Any suggestions in this regard, what's the best file format to save and load these merged and colored tubes?

**Comment by marcomusy** [comment]
as vtp/vtk it just saves the arry but it cannot know how to map those scalars to an actual RGB, so it uses the default color map (jet).

probably you may use `ply`, I need to check if it saves direct colors.

**Comment by lukablagoje** [comment]
So ".ply" saves the colors, but it changes the tubes (created by Tube() function) to circles. Examples of what I'm saving below:

Original mesh (bunch of colored tubes):
![image](https://user-images.githubusercontent.com/52599010/170792870-3b998e92-f334-4e4b-84c7-94bb2bd573cd.png)

When saved and loaded as ".ply" (bunch of circles):

![image](https://user-images.githubusercontent.com/52599010/170793104-7c27da08-a9de-441a-93e4-ec43c455c4be.png)

**Comment by lukablagoje** [comment]
Hello, 

Sorry if you have been busy and haven't had the time to check, but is there any resolution to this? 

Can I somehow save colored tubes?

**Comment by marcomusy** [comment]
hi, sorry, i forgot to answer you.
Have you checked that you are saving triangular meshes?
you can use `.triangulate()` before saving to ply.

**Comment by lukablagoje** [comment]
Thanks, this worked for saving to ply. 

But is it possible to obtain materials from the object? 

So for example, can I write my mesh to both .obj and .mtl file formats?

**Comment by marcomusy** [comment]
> can I write my mesh to both .obj and .mtl file formats?

obj and mtl file go along together. 
The creation of a mtl file is not implemented in vedo, so you need to create it manually.

**Comment by lukablagoje** [comment]
Thanks for all the help!
