### ISSUE TITLE
Is there a way I can save the render window as an image and store it?

### ISSUE THREAD

**Issue by nmarmatak** [marcomusy/vedo#653]
I can't seem to find anything like this in the documentation, I was thinking of screenshoting the render window but sadly that didn't work. Any advice?

**Comment by marcomusy** [comment]
yes, obviously you can do it:
```
plt  = Plotter()
...
plt.screenshot("mypic.png")
```

**Comment by nmarmatak** [comment]
lmao this is actually the dumbest question anyone has ever asked, but where does it save?

**Comment by marcomusy** [comment]
no dumb question:) it saves it in the same dirctory you run the script

**Comment by nmarmatak** [comment]
![Screen Shot 2022-05-25 at 12 41 19 AM](https://user-images.githubusercontent.com/71342805/170137118-346588bb-7ca9-4e5b-836e-ca0ee8a4875e.png)
well uh thats the dumb part of it, sorry for your time

**Comment by nmarmatak** [comment]
right, I figure I forgot to add plt.render(), but the output appears to be a blank image
![Screen Shot 2022-05-25 at 12 46 22 AM](https://user-images.githubusercontent.com/71342805/170137718-403d1abf-a5c2-4e39-a4f0-eb3bdee4db1a.png)

**Comment by marcomusy** [comment]
can you reproduce this
```python
from vedo import *
sph = Sphere()
plt = Plotter()
plt.show(sph) # press q to continue
plt.screenshot("test.png")
plt.close()
```

**Comment by nmarmatak** [comment]
Works perfectly! Thanks man. although is there a way to bypass pressing q and having the process? It's fine if not but it would be a huge addition

**Comment by marcomusy** [comment]
yes, sure try:
`plt.show(sph, interactive=False)`
you can later reactivate the interactivity with
`plt.interactive()`

**Comment by nmarmatak** [comment]
This is exactly what I was looking for. Thank you man, you really made my day. Good luck with this, it's very very helpful. (i'll also try not to bother you any more)

**Comment by marcomusy** [comment]
no worries, let me know if you have any doubts
