### ISSUE TITLE
Mesh texture gives ValueError for numpy.ndarray for tname

### ISSUE THREAD

**Issue by MesoBolt** [marcomusy/vedo#657]
Since I have updated vedo from 2021.0.7 to the newest version 2022.2.3 I get a ValueError when I want to create a texture on the Earth object by defining tname=numpy.ndarray-like texture. Could it be a bug? 

The Shape of my texture array is (n,m,3). It has three dimensions due to the RGB-color values.

  File "C:\Python\Python390\lib\site-packages\vedo\mesh.py", line 431, in texture
    if not tname:  # disable texture
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

My vedo info from `vedo --info` is:

vedo version      : 2022.2.3   https://vedo.embl.es
vtk version       : 9.0.3
python version    : 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
python interpreter: c:\python\python390\python.exe
vedo installation : c:\python\python390\lib\site-packages\vedo
system            : Windows 10 nt AMD64

Thanks in advance.

**Comment by MesoBolt** [comment]
Thank for your answer. Well, the above error does not occur anymore but others appear:

```
[vedo.pointcloud.py:2428] ERROR: cannot find any active Point array ...skip coloring.
[vedo.pointcloud.py:2579] ERROR: nr. of scalars 0 != 1 nr. of cells ...skip coloring.
```

**Comment by marcomusy** [comment]
OK, the new errors are not related to texture I think.
The first means that you are trying to colorize a mesh but there is no data associated to points.
The second is likely related to the first.
