### ISSUE TITLE
Normalized diverging colormap for Volume object

### ISSUE THREAD

**Issue by MesoBolt** [marcomusy/vedo#658]
I want to plot a volume object with a diverging colormap of unequal positive and negative fraction. In the case of a 2D plot with python matplotlib I would create the colormap with the "LinearSegmentedColormap" function from "matplotlib.colors", e.g.:

```python
data = np.random.random([100, 100]) * 100 - 70

minimum = data.min()
maximum = data.max()
absmax = np.abs(data).max()
absmin = np.abs(data).min()

val = -minimum/(maximum - minimum)

m = LinearSegmentedColormap.from_list(
    "mycolormap",
    colors = [
        (0.0, [0.0,0.0,1.0]),
        (val, [1.0,1.0,1.0]),
        (1.0, [1.0,0.0,0.0])
    ]
)

plt.figure(figsize=(7, 6))
plt.pcolormesh(data, cmap=m)
plt.colorbar()
plt.show()
```

![grafik](https://user-images.githubusercontent.com/43699766/172553691-ef5fcac4-7c61-42e7-bae1-6391b4e369e3.png)

However, if I create the same colormap "m" for a 3D-Volume "vol" object and use it with "vol.cmap(m)" there is just a black-white coloring of the Volume and the colorbar is black, so fully transparent I would guess. 

![grafik](https://user-images.githubusercontent.com/43699766/172554339-cd56d85b-d2e4-45c2-8b96-d8eea114adf2.png)

My questions are:
1. How can I create the diverging colormap for the Volume object?
2. How can I set the transparency of the colorbar to zero (or equally alpha to 1)?
3. How can I fix the colormap at a specific position of the screen (so it does not move with the 3D-view)?

**Comment by marcomusy** [comment]
Hi, try:
```python
from vedo import Volume
import numpy as np

val= 35

arr = np.zeros(shape=(50,50,50))
for i in range(50):
    for j in range(50):
        for k in range(50):
            arr[i,j,k] = j

vol = Volume(arr).mode(1)
vrange = vol.scalarRange()
colors = [
    (vrange[0], [0.0,0.0,1.0]),
    (val,       [1.0,1.0,1.0]),
    (vrange[1], [1.0,0.0,0.0])
]
vol.cmap(colors, alpha=[0,1])
vol.addScalarBar("value", useAlpha=False)
vol.show(axes=1)
```
![Screenshot from 2022-06-08 12-44-15](https://user-images.githubusercontent.com/32848391/172597839-7997c6b9-b433-46f6-b536-f546e6e60f49.png)

**Comment by MesoBolt** [comment]
Thank you for your fast response. This worked out if I select the minimum and maximum value as boundaries. But how can I norm the colorbar in a range spanning from another custom range which does not reaches to the min and max values (e.g. 5 to 40)? So that finally the colorbar only shows values in the custom range of e.g. 5 to 40. Is it possible to mask the volume to show only values which are in this range?

**Comment by marcomusy** [comment]
You can play with ranges with eg:
```
vol.cmap(colors, vmin=5, vmax=40)

mask = np.ones(50)*0.1
mask[:5] = 0.
mask[40:] = 0.01
vol.alpha(mask)
```
note that alpha maps the full range linearly.
For some combinations of parameters the result might not look good (this is not bacuse of vedo but a problem in the upstream vtk) so you may need to experiment with `.mode(0)`.

For volume masking you can also check out
https://github.com/marcomusy/vedo/issues/630
