### ISSUE TITLE
How to reset the Cutter's position?

### ISSUE THREAD

**Issue by zgtan** [marcomusy/vedo#664]
Sometimes the cutter's box has been manipulated to an angle that hard to continue, I want to reset the cutter to the original position. Is it possible? 
how to do it in code?

**Comment by marcomusy** [comment]
hi, sorry for the late reply, say your mesh is called `msh` and eg. `plt = Plotter()` then try
```python
wd = plt.widgets[-1]
wd.PlaceWidget (msh.bounds())
plt.render() # if necessary
```
this might go in a callback or in the program flow.
