### ISSUE TITLE
Using vedo within WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by rafaelmarch3** [marcomusy/vedo#671]
Hello, 

I'm trying to use vedo within WSL. I have an issue with the function "show". When I try to show any 3D model, I get a very simple error message: "Aborted". Note I am using XMING as a x11 server to forward the plot GUI to my Windows system. Using XMING, I am able to use Matplotlib without any issues. Any clue what might be happening?

Thanks, 
Rafael.

**Comment by marcomusy** [comment]
Hi Rafael,
are you sure you have openGL capability in your system?
you may also have a look at #64 if that applies.
One quick test to see if the upstream vtk is working is to run this as a test:
```python
import vtk

source = vtk.vtkCubeSource()
mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(source.GetOutputPort())
actor = vtk.vtkActor()
actor.SetMapper(mapper)

renderer = vtk.vtkRenderer()
renderer.AddActor(actor)

renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renderWindow)
iren.Initialize()
renderer.ResetCamera()
renderWindow.Render()
iren.Start()
```

**Comment by rafaelmarch3** [comment]
Hi, thanks for the quick reply. I get the following error when trying to run the simple vtk example. What are the right opengl libraries to install? Thanks!


2022-07-19 15:39:43.227 (   0.157s) [        68B08740]vtkXOpenGLRenderWindow.:251    ERR| vtkXOpenGLRenderWindow (0x2427b80): Could not find a decent config

2022-07-19 15:39:43.227 (   0.158s) [        68B08740]vtkXOpenGLRenderWindow.:468    ERR| vtkXOpenGLRenderWindow (0x2427b80): Could not find a decent visual

Aborted

**Comment by marcomusy** [comment]
Hi, sorry I'm not familiar with xming.. maybe you can try something like:
https://stackoverflow.com/questions/106201/how-can-i-run-an-opengl-application-installed-on-a-linux-machine-from-my-windows

**Comment by rafaelmarch3** [comment]
Will give it a go! Thanks Marco!
