### ISSUE TITLE
Dead Kernel JupyterHub/Podman container

### ISSUE THREAD

**Issue by isara-j** [marcomusy/vedo#673]
I'm trying to use vedo in a Jupyter notebook running inside of a podman container, which is spanned by JupyterHub. 
Every backend besides k3d results in dead kernel warnings at the creation of the Plotter instance: 
plot = Plotter(backend='ipyvtk')
plot = Plotter(backend='itk')
plot = Plotter(backend=None)

Similar to https://github.com/marcomusy/vedo/issues/37 specifying the screensize fixes the crash.
The following code snippets don't crash the kernel: 
vp = Plotter(backend='ipyvtk',screensize=(500,500))
vp = Plotter(backend='itk',screensize=(500,500))
vp = Plotter(backend=None, screensize=(500,500))

However when trying to plot anything the kernel crashes again. 
This simple example crashes with ipyvtk/None/itk, while it works with k3d:

from vedo import *
plot = Plotter(backend='ipyvtk')
obj=Cube()
plot.show(obj)

Versions:
vedo                    2022.2.3
K3D                     2.7.4
ipyvtklink              0.2.2
ipygany                 0.5.0
itk                     5.2.1.post1
itk-core                5.2.1.post1
itk-filtering           5.2.1.post1
itk-io                  5.2.1.post1
itk-meshtopolydata      0.8.1
itk-numerics            5.2.1.post1
itk-registration        5.2.1.post1
itk-segmentation        5.2.1.post1
itkwidgets              0.32.2

**Comment by marcomusy** [comment]
Hi - thanks for reporting - I must say I'm not familiar with podman containers at all.. Would you try to run this, to understand if the upstream vtk works in your case:
```python
import vtk

source = vtk.vtkCubeSource()
mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(source.GetOutputPort())
actor = vtk.vtkActor()
actor.SetMapper(mapper)

renderer = vtk.vtkRenderer()
renderer.AddActor(actor)

renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)

#on vtk9.1.0 hangs, on vtk9.0.3 needs this line to make window close
ss = renderWindow.GetScreenSize()
print('ScreenSize =', ss)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renderWindow)
iren.Initialize()
renderer.ResetCamera()

for i in range(30):
  renderer.GetActiveCamera().Azimuth(10)
  renderWindow.Render()
iren.Start()
```

**Comment by isara-j** [comment]
Sorry for the late reply. 
This crashes at `ss = renderWindow.GetScreenSize()` for me. 
Or later at  `iren.Initialize()`, if I comment out 
`#ss = renderWindow.GetScreenSize()`
`#print('ScreenSize =', ss)`
