### ISSUE TITLE
Clear previous frame from video pipeline

### ISSUE THREAD

**Issue by ttsesm** [marcomusy/vedo#675]
Hi Marco,

I am trying to create a video sequence from some pcds that I am loading each time based on the tutorials, however the viewer and the output video file just puts the new pcds on top of each other so it accumulates all the scenes. Is it possible to clear the previous loaded pcd before I show the new one and added to the video output as a new frame.

Code snippet:
```
cam = dict(
        pos=(-3.373, -1.983, -3.673),
        focalPoint=(-0.3201, -0.2132, 1.150),
        viewup=(0.1560, -0.9551, 0.2518),
        distance=5.976,
        clippingRange=(2.888, 9.879),
    )
vp = vd.Plotter(axes=0, interactive=0, sharecam=False)

video = vd.Video("elephant.mp4", backend='ffmpeg')  # backend='opencv'

for i, pcd in enumerate(scanned_pcds):
    p = vd.Points(pcd)
   
    vp.show(p.lighting(style='metallic'), elevation=1, azimuth=2, camera=cam)  # render the scene
    video.addFrame() # add frame

video.close()
vp.show().close()
```

Thanks.

**Comment by marcomusy** [comment]
Hi
what if you remove it explicitly:
```
    vp.show(p.lighting(style='metallic'), elevation=1, azimuth=2, camera=cam)  # render the scene
    vp.remove(p)
```

**Comment by ttsesm** [comment]
> Hi what if you remove it explicitly:
> 
> ```
>     vp.show(p.lighting(style='metallic'), elevation=1, azimuth=2, camera=cam)  # render the scene
>     vp.remove(p)
> ```

I've tried this as well as the `vp.show(....).clear()`, which I guess it does the same, but then the video is blank/empty it doesn't show anything :thinking:

**Comment by marcomusy** [comment]
uhm , I should fix the clear() method is not doing good...
what if
`    vp.remove(p, resetcam=True)`

**Comment by ttsesm** [comment]
Same behavior... :-(

**Comment by marcomusy** [comment]
what about
```python
from vedo import *

scanned_pcds = [Points(np.random.rand(100,3)), Points(np.random.rand(100,3)+0.5)]

vp = Plotter()

vp.show(Axes(scanned_pcds[0]))

for i, pcd in enumerate(scanned_pcds):
    pcd.lighting(style='metallic')
    vp.add(pcd)
    vp.screenshot(f'm{i}.png') # or add frame
    vp.remove(pcd)

vp.interactive()
```

**Comment by ttsesm** [comment]
> Hi what if you remove it explicitly:
> 
> ```
>     vp.show(p.lighting(style='metallic'), elevation=1, azimuth=2, camera=cam)  # render the scene
>     vp.remove(p)
> ```

ok Marco, sorry my bad. This actually works, you just need to add the `video.addFrame()` before the remove:

```
vp.show(p.lighting(style='metallic'), camera=cam)  # render the scene
video.addFrame()
vp.remove(p)
```

My apologies. Pfff, long day at work...
