### ISSUE TITLE
reconstructSurface does not work on simple box.

### ISSUE THREAD

**Issue by MPBAUSER** [marcomusy/vedo#677]
I have been using reconstructSurface on several more complex (nearly equidistant and manifold) Point Clouds and it worked fine.
However I did not manage to reconstruct the Surface of a simple cube or a icosahedron (https://people.sc.fsu.edu/~jburkardt/data/ply/icosahedron.ply).

I also tried reconstructing the box with a radius of 0.2, 0.51, 1.01, 1.74
I'm very sorry if I missed anything obvious. Thanks in advance.

`from vedo import *`
`plt = Plotter(shape=(1,3), axes=3)`
`#mesh1 = Mesh("https://people.sc.fsu.edu/~jburkardt/data/ply/cube.ply")`
`mesh1 = Box(pos=(0,0,0), length= 1, width = 1, height= 1)`
`plt.show(mesh1, "First mesh before reco", at=0)`
`pts1= Points(mesh1, r=3)`
`reco1 = pts1.reconstructSurface(dims=100, radius=None, holeFilling=True).c("gold")`
`plt.show(mesh1, at=0)`
`plt.show(pts1, at=1)`
`plt.show(reco1, at=2)`
`plt.interactive().close()`

**Comment by marcomusy** [comment]
The `reconstructSurface` method is only applicable to large pointclouds,
 for small convex objects you can use `ConvexHull` eg.
```python
from vedo import *

plt = Plotter(shape=(1,3), axes=3)

mesh1 = Mesh("https://people.sc.fsu.edu/~jburkardt/data/ply/icosahedron.ply")
#mesh1 = Box(length= 1, width = 1, height= 1)
plt.show(mesh1, "First mesh before reco", at=0)

pts1 = Points(mesh1, r=10)

reco1 = ConvexHull(pts1).c("green5").alpha(1)
plt.show(mesh1, at=0)
plt.show(pts1, at=1)
plt.show(reco1, at=2)
plt.interactive().close()
```
<img width="852" alt="Screenshot 2022-08-19 at 02 51 08" src="https://user-images.githubusercontent.com/32848391/185519147-f56892bb-4d84-4450-9080-c84cf135b603.png">

for non-convex objects there is no well defined solution.

**Comment by MPBAUSER** [comment]
Thanks a lot!
