### ISSUE TITLE
Problem on alpha test

### ISSUE THREAD

**Issue by GabbyYam** [marcomusy/vedo#686]
I wonder if there's a way to do alpha test
when i try to render my mesh with alpha less than 1.0 and volume object whthin a same Plotter, the volume simply always be rendered but mesh didn't
Is there any solution for it? thanks

**Comment by marcomusy** [comment]
Have you tried
`settings.useDepthPeeling = True`

**Comment by GabbyYam** [comment]
> Have you tried `settings.useDepthPeeling = True`

Not working tho...

**Comment by marcomusy** [comment]
Can you post an screenshot of what you observe? What is your OS?
