### ISSUE TITLE
Supress warning when 2 meshes don't intersect

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#690]
I'm using vedo to get the intersection points between a lot of pairs of meshes using intersectWith().

Now, when 2 meshes don't intersect, i get the following message:

`2022-09-12 23:39:58.016 (2936.989s) [                ]    vtkPointLocator.cxx:845    ERR| vtkPointLocator (00000261522F5010): No points to subdivide`
`2022-09-12 23:39:58.020 (2936.993s) [                ]vtkIntersectionPolyData:2410  WARN| No Intersection between objects`

This is perfectly expected since many of the meshes combinations don't intersect (and checking if they do is part of the point of this), my question is, is there any way to just supress this warning? I'm testing a lot of meshes and it's really annoying to flood the terminal with thousands of warnings.

I think there must be some arg to just make the output less verbose, but haven't been able to find it.

**Comment by marcomusy** [comment]
Hi, I just pushed a version where the warning is silenced.
`pip install -U git+https://github.com/marcomusy/vedo.git`
let me know if it works for you.

**Comment by ManuGraiph** [comment]
Give me a bit please, when trying to uninstall vedo it broke my entire env.

**Comment by ManuGraiph** [comment]
I'm getting an error when trying to install:

`ERROR: Could not find a version that satisfies the requirement vtk<9.1.0 (from vedo) (from versions: 9.2.0rc1, 9.2.0rc2)`
`ERROR: No matching distribution found for vtk<9.1.0`

**Comment by ManuGraiph** [comment]
Don't worry, i just defined/adapted the function myself and added the `bf.SetGlobalWarningDisplay(0)`.

**Comment by marcomusy** [comment]
Oh ok - vedo can work with vtk9.2 as well,
you would need to add `--no-deps` to pip.
