### ISSUE TITLE
Generate isosurface per class label

### ISSUE THREAD

**Issue by ivan-marroquin** [marcomusy/vedo#694]
Hi,

thanks a lot for making available such a great package! It is so cool, in relative few lines of code I can get to display my numerical data. I am using Python 3.9.0 and vedo 2022.3.0 on a computer running Ubuntu.

In the attached file, you will find a Python script and input data that I want to use in the following manner. I would like to get an isosurface for each class label. So then, I have a 3D expression of the occurrence of each class label within a volume.

I would like to ask you some questions:
1) I get this error message and I was not able to find the source of the problem:
[vedo.plotter.py:2536] ERROR: cannot understand input in show(): <class 'method'>

2) in the command "isosurface(threshold= None)". how the threshold is used? drop values above or below the threshold? is there a maximum threshold value? is there a way to estimate an optimal value?

3) the generated plot suggests that the occurrence of class labels is almost identical. However, the count of class labels indicates the contrary. Am I missing something in my code?

I thank you in advance for your comments/suggestions.

Ivan

[classification_vedo.zip](https://github.com/marcomusy/vedo/files/9592237/classification_vedo.zip)

**Comment by marcomusy** [comment]
Hi Ivan,
thanks I'm happy that you find the library useful.
1. you just forgot the parentheses in  `box()`
2. probably what you are looking for is not just `isosurface()` but rather `threshold()` method to isolate each individual label and visualize those independently
3. see 2.

My version of your code would be:
```python
from vedo import *
from vedo.pyplot import plot

def get_iso(n, thres):
    # generate isosurface for class 1
    #
    # get indices for class labels higher than 1
    loc = datos
    idx_class = np.where(loc > n)

    # combine indices
    idx_class = np.dstack((idx_class[0], idx_class[1], idx_class[2]))
    idx_class = np.squeeze(idx_class, axis=0)

    # class labels higher than 1 are assigned 0
    for ielem in range(0, len(idx_class)):
        loc[tuple(idx_class[ielem])] = 0

    # get volume for class
    vol = Volume(loc).dilate(neighbours=(2, 2, 2))

    # generate mesh
    iso = vol.isosurface(thres).smooth().flat()
    return iso


datos = np.load("PDFextract_classification.npy")
u, c = np.unique(datos, return_counts=True)

iso_1 = get_iso(1, 0.95).color([248, 114, 81])
iso_2 = get_iso(2, 0.85).color([42, 187, 237])
iso_3 = get_iso(3, 0.65).color([150, 131, 91])
iso_4 = get_iso(4, 0.65).color([0, 129, 49])
iso_5 = get_iso(5, 0.65).color([255, 255, 0])

# generate viewer
show(iso_1, iso_2, iso_3, iso_4, iso_5, N=5, axes=1).close()
plot(u, c, "*-r", title="class labels and counts").show().close()
```

<img width="787" alt="Screenshot 2022-09-17 at 21 06 40" src="https://user-images.githubusercontent.com/32848391/190872731-8d2e341a-91fa-4631-962f-970e86cd47bd.png">

note that the volume is always the same and hence the isosurface for the same threshold.

**Comment by ivan-marroquin** [comment]
Hi Marco,

Many thanks for your prompt reply and suggestions.

Ivan
