### ISSUE TITLE
Problem at using 2D slider on a volume

### ISSUE THREAD

**Issue by ivan-marroquin** [marcomusy/vedo#699]
Hi,

Many thanks for making available this great package!

I am using vedo 2022.3.0 and python 3.9.0.

I would like to use a 2D slider the pane through the volume along x-axis. So then, I can visualize a yz-plane showing the volume values extracted on that plane.  To generate the volume, I am using isosurface to represent the presence of class labels [1 to 6] inside background values "0".

The attached script shows my attempt to achieve this goal. Unfortunately, I keep getting this error message:
Traceback (most recent call last):
  File "/home/ivan/python_fun/extract_pdf/test.py", line 75, in slider
    iso_t.applyTransform(T)
  File "/home/ivan/python_3.9.0/lib/python3.9/site-packages/vedo/base.py", line 541, in applyTransform
    self.SetUserTransform(T)
TypeError: SetUserTransform argument 1: method requires a VTK object

Many thanks for your comments/suggestions.

Ivan

[test_script.zip](https://github.com/marcomusy/vedo/files/9641473/test_script.zip)

**Comment by marcomusy** [comment]
Hi, the numpy `.tolist()` method is not operating in-place so you need to do:

`iso_t.applyTransform(T.tolist())`

I will change `applyTransform()` to accept any sequence types.

**Comment by ivan-marroquin** [comment]
Thanks for the comment!

The transformation works fine. Unfortunately, it is not my desired result. 

I would like to be able to use a 2D slider to move a plane along the x-axis. So at different positions of the plane, I will see the intersection of the plane with "iso_t".

Since "iso_t" is a combination of several isosurfaces (iso_1 to iso_6), this object became an Assembly one. And all my efforts to try to cut through have been unsuccessful.

I was hoping that you may have another alternative.

thanks again for all  your help,

Ivan

**Comment by ivan-marroquin** [comment]
The code below shows my last efforts - I just updated the code for this function, the remaining of the code is still the same:

def slider(widget, event):
    """
    updates the frame
    """
    
    t= widget.GetRepresentation().GetValue()
    print("plane position {}".format(int(t))) 
    
    new_datos= datos[int(t):,:,:].copy()
    print("orig shape {} new shape {}".format(datos.shape, new_datos.shape))
    
    new_iso_1= get_iso(new_datos, 1, 0.95).color([248, 114, 81]).alpha(0.55)
    new_iso_2= get_iso(new_datos, 2, 0.95).color([42, 187, 237]).alpha(0.55)
    new_iso_3= get_iso(new_datos, 3, 0.95).color([127, 0, 255]).alpha(0.65)
    new_iso_4= get_iso(new_datos, 4, 0.95).color([0, 129, 49]).alpha(0.85)
    new_iso_5= get_iso(new_datos, 5, 0.95).color([255, 255, 0]).alpha(0.85)    
    new_iso_6= get_iso(new_datos, 6, 0.95).color([121, 128, 144]).alpha(0.85)
    iso_new= new_iso_1 + new_iso_2 + new_iso_3 + new_iso_4 + new_iso_5 + new_iso_6
     
    plt.pop().add(iso_new, render= True, resetcam= True)
    
    plt.render()

**Comment by marcomusy** [comment]
Hi sorry for the late reply, creating an assembly looks not the best way to do it, you can merge the meshes into a single one and then create a working copy to cut into the callback function to generate on the fly a thin slice:
```python
from vedo import *


def get_iso(X, n, thres):
    loc = X.copy()

    # find indices for class labels other than "n"
    idx = np.where(loc != n)

    # combine indices
    idx = np.dstack((idx[0], idx[1], idx[2]))

    idx = np.squeeze(idx, axis=0)

    # other class labels than "n" are assigned class label "0"
    for ielem in range(0, len(idx)):
        loc[tuple(idx[ielem])] = 0

    # find indices for class "n"
    idx = np.where(loc == n)

    # combine indices
    idx = np.dstack((idx[0], idx[1], idx[2]))

    idx = np.squeeze(idx, axis=0)

    # class label "n" is converted to class "1"
    # generate a binary volume
    for ielem in range(0, len(idx)):
        loc[tuple(idx[ielem])] = 1

    vol = Volume(loc).dilate(neighbours=(6, 2, 2))

    # generate mesh
    iso = vol.isosurface(thres).smooth().fillHoles().flat()
    return iso


def slider(widget, event):
    """
    updates the frame
    """
    t = int(widget.GetRepresentation().GetValue())
    iso_new = iso_t.clone()
    iso_new.cutWithPlane(origin=[t-5,0,0], normal='+x')
    iso_new.cutWithPlane(origin=[t+5,0,0], normal='-x')
    iso_new.name = "iso_t"
    plt.remove("iso_t").add(iso_new, resetcam=False)

datos = np.load("PDFextract_classification.npy")

u, c = np.unique(datos, return_counts=True)

print("classe labels {} and thier counts {}".format(u, c))

iso_1 = get_iso(datos, 1, 0.95).color([248, 114, 81]).alpha(0.55)
iso_2 = get_iso(datos, 2, 0.95).color([42, 187, 237]).alpha(0.55)
iso_3 = get_iso(datos, 3, 0.95).color([127, 0, 255]).alpha(0.65)
iso_4 = get_iso(datos, 4, 0.95).color([0, 129, 49]).alpha(0.85)
iso_5 = get_iso(datos, 5, 0.95).color([255, 255, 0]).alpha(0.85)
iso_6 = get_iso(datos, 6, 0.95).color([121, 128, 144]).alpha(0.85)

iso_t = merge(iso_1, iso_2, iso_3, iso_4, iso_5, iso_6).color("red5")
iso_t.name = "iso_t"

settings.defaultFont = "Kanopus"

axes = Axes(
    iso_t,
    htitle="Number Pages",
    xtitle=' ',
    ztitle=' ',
    hTitleRotation=-90,
    textScale=1.5,
    hTitleColor="k",
    hTitleOffset=(0, 0.75, 0),
    hTitleJustify="bottom-center",
    # showTicks=False,
    xyGrid=False,
)

# show(iso_1, iso_2, iso_3, iso_4, iso_5, iso_6, N=6).close()

plt = Plotter(bg=[250, 249, 246], size=(1900, 800))
plt.addSlider2D(slider, xmin=0, xmax=460, pos="bottom-right", title="x-slider")
plt.show(iso_t, axes, elevation=60, zoom=2).close()
```
![Screenshot from 2022-10-01 18-51-53](https://user-images.githubusercontent.com/32848391/193419907-01bf3786-f8c2-4e06-844b-5d574084459e.png)

if you need to colorize each separate mesh, then do not use `merge()` but cut individually all the 6 meshes in the callback function.

**Comment by ivan-marroquin** [comment]
Hi @marcomusy 

Many thanks! It runs like a champ. I attached the final version of my script hoping that it can help new users of this great package.

Ivan

[test_script.zip](https://github.com/marcomusy/vedo/files/9690954/test_script.zip)
