### ISSUE TITLE
mesh.addQuality doesn't work anymore with vedo 2022.4.1

### ISSUE THREAD

**Issue by haesleinhuepf** [marcomusy/vedo#714]
Hi @marcomusy ,

I'm just trying to update code to use vedo 2022.4.1 . Apparently, the function `mesh.addQuality` (e.g. used [here](https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/b1eee0567e9b879e8c873d7fc3c0a01752df039c/napari_process_points_and_surfaces/_quantification.py#L58)) was removed. But also `add_quality` does not work. 

Was this function entirely removed? I cannot find it in the [documentation](https://vedo.embl.es/autodocs/content/vedo/mesh.html#vedo.mesh.Mesh) and/or [release notes](https://github.com/marcomusy/vedo/releases).

Any hint is welcome. Thanks!

Best,
Robert

**Comment by marcomusy** [comment]
Yes, sorry I forgot to add the deprecation message for that one!
You should use
https://github.com/marcomusy/vedo/blob/cf356c051afb851ca5f8eca06d8bd710d057b59a/vedo/mesh.py#L1105

**Comment by haesleinhuepf** [comment]
Awesome, that works. Thanks for the lightspeed response! 🤩
