### ISSUE TITLE
Issue with the module optics_base

### ISSUE THREAD

**Issue by alex0631** [marcomusy/vedo#719]
https://github.com/marcomusy/vedo/blob/b91f22967d494730a7a13075ff6fda97925e1bbb/examples/simulations/optics_main2.py#L5

I don't manage to download the optics_base module, if someone could help me.

Thank you.

**Comment by marcomusy** [comment]
It's in the same examples directory:

https://github.com/marcomusy/vedo/blob/master/examples/simulations/optics_base.py
