### ISSUE TITLE
Issue Mirror and diagonal size 

### ISSUE THREAD

**Issue by alex0631** [marcomusy/vedo#720]
https://github.com/marcomusy/vedo/blob/b91f22967d494730a7a13075ff6fda97925e1bbb/examples/simulations/optics_base.py#L189

I have this error after using a Mirror as an element. 'Mirror' object has no attribute 'diagonal_size'.

Thank you.

**Comment by marcomusy** [comment]
I think you need to upgrade vedo with:
`pip install vedo  -U`
