### ISSUE TITLE
Question about "cutting" a mesh

### ISSUE THREAD

**Issue by ManuGraiph** [marcomusy/vedo#723]
Hi!

I have a mesh formed by a lot of triangles. I want to know if it's possible to "cut/subset" the faces and points of that mesh with certain position criteria, for example, all faces above z = 1000 or similar.

Thx in advance!

**Comment by marcomusy** [comment]
Yes, sure.

You can either sharp-cut the mesh:
```
msh.cut_with_plane(normal="z", origin=(0,0,1000))
```
(this will create new small triangles that come from the partially cut triangles at z=1000)

Or, you can associate data to your mesh and then use it to threshold it:
```python
msh.pointdata["myzelevation"] = msh.points()[:,2]
msh.threshold("myzelevation", above=1000)
```
