### ISSUE TITLE
How to render multiple arranged meshes of fixed height

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#727]
I want to arrange multiple meshes in order along the x-axis to render an image with a fixed height. The width of the image is calculated according to the length of the mesh after arrangement, and I want these grids to occupy the whole picture.

I have many different meshes, so I want to deal with this problem in a more determined way, rather than by setting the zoom parameters.

[data](https://github.com/marcomusy/vedo/files/9943488/for_vedo_20221105.txt)(replace ".txt" with ".zip")

code:
```
import igl
from vedo import *

settings.rendererFrameAlpha = 0
settings.useParallelProjection = True  # avoid perspective parallax

color_meshlab = [
    "#C0C0C0",
    "#C0C0C0",
    "#C0C0C0",
]

# path_mesh = "/home/lab0/Pictures/for_vedo_20221105/CCD_mesh_d_ortho_00000_0_opt_0.ply"
path_mesh = "/home/lab0/Pictures/for_vedo_20221105/CCD_mesh_d_ortho_00003_0_opt_0.ply"

path_mesh_1 = path_mesh
path_mesh_2 = path_mesh
path_mesh_3 = path_mesh
path_mesh_4 = path_mesh

v0, f0 = igl.read_triangle_mesh(path_mesh_2)
v1, f1 = igl.read_triangle_mesh(path_mesh_2)
v2, f2 = igl.read_triangle_mesh(path_mesh_3)
v3, f3 = igl.read_triangle_mesh(path_mesh_4)

mean0 = v0.mean(0)
max0 = v0.max(0)
min0 = v0.min(0)

d = max0 - min0
dx = d[0]  # width of mesh
ddx = 0.1  # Gaps between meshes, here we set as 0.1m

# Decentralization
if True:
    v0 -= mean0
    v0 -= min0

    v1 -= mean0
    v1 -= min0

    v2 -= mean0
    v2 -= min0

    v3 -= mean0
    v3 -= min0

# Arrange along the x-axis
if True:
    v1[:, 0] += (dx + ddx) * 1
    v2[:, 0] += (dx + ddx) * 2
    v3[:, 0] += (dx + ddx) * 3

M0 = Mesh([v0, f0])
M1 = Mesh([v1, f1])
M2 = Mesh([v2, f2])
M3 = Mesh([v3, f3])

M1.c(color_meshlab[0])
M2.c(color_meshlab[1])
M3.c(color_meshlab[2])

M0.lighting("ambient")
M1.flat()
M2.smooth()
M3.flat()

# dx ddx-dx ddx-dx ddx-dx
h = d[1]
w = 4 * dx + 3 * ddx
h += 0.2  # margin
w += 0.2

# Fixed height, the width is calculated according to the x-axis length of the meshes
h0 = 800
hw = h0
ww = int(h0 * w / h)

show([M0, M1, M2, M3], zoom=1.0, size=(ww, hw), offscreen=0)
screenshot("/home/lab0/Pictures/check_0.png")
```

result:
![check_0](https://user-images.githubusercontent.com/34391447/200113311-b14106ba-da37-4dec-9c97-d5b70875b665.png)

desired:
![check_0](https://user-images.githubusercontent.com/34391447/200113339-0fd30dfc-5f81-4711-8211-e405bc976821.png)

**Comment by marcomusy** [comment]
have you tried
```
show(..., zoom="tight")
# or
show(..., zoom="tightest")
```

you may need to update vedo with:
```
pip install vedo -U
```

**Comment by LogWell** [comment]
many thanks

**Comment by LogWell** [comment]
In addition, how should I set the mesh normal (such as reading from a file), so I can set different shading to the same mesh?

**Comment by marcomusy** [comment]
yes
Or what about
`m.compute_normals()`

**Comment by LogWell** [comment]
It seems that `settings.useParallelProjection = False` and `show(..., zoom="tight")` are in conflict.

**Comment by LogWell** [comment]
How to close the split line in `Plotter(shape=(1, 4)...`?
![image](https://user-images.githubusercontent.com/34391447/200158907-308db249-1409-4d00-b781-f993ca9b8c19.png)

**Comment by marcomusy** [comment]
You may want to use `reset_camera()`:

```
pip install vedo -U`
```

then
```python
from vedo import *
m = Mesh(dataurl+"bunny.obj").c("blue8")

plt = Plotter(shape=(1, 4), offscreen=0)
plt.at(0).show(m)
plt.at(1).show(m)
plt.at(2).show(m)
plt.at(3).show(m)
plt.reset_camera(tight=0.05)
plt.interactive().close()
```
![Screenshot from 2022-11-06 14-37-27](https://user-images.githubusercontent.com/32848391/200174024-c76a933b-2332-4685-b7fc-a4706f8162a4.png)

**Comment by LogWell** [comment]
But I still have 3 questions. 
1. Can the split line pointed by the arrow be closed?
2. I found `cam.SetParallelProjection(True)` in `reset_camera`, does this mean I can only set the `ParallelProjection`?
3. How to fix the height of the screenshot image?
![image](https://user-images.githubusercontent.com/34391447/200174858-5535ac61-dbcc-4c8a-8fc5-0f1a286963a9.png)

**Comment by marcomusy** [comment]
1. You mean removed? Then use `settings.renderer_frame_alpha = 0`
2. Yes, using `tight=...` automatically sets parallel projection mode.
3. I don't understand the question

**Comment by LogWell** [comment]
I made some modifications to `plotter.py` to accommodate the perspective camera  (Looks pretty good at the moment)
```
                x0, x1, y0, y1, z0, z1 = self.renderer.ComputeVisiblePropBounds()

                cam = self.renderer.GetActiveCamera()

                self.renderer.ComputeAspect()
                aspect = self.renderer.GetAspect()
                angle = np.pi * cam.GetViewAngle() / 180.0
                dx, dy = (x1 - x0) * 0.999, (y1 - y0) * 0.999
                dist = max(dx / aspect[0], dy) / np.sin(angle / 2) / 2

                cam.SetViewUp(0, 1, 0)
                cam.SetPosition(x0 + dx / 2, y0 + dy / 2, dist * (1 + tight))
                cam.SetFocalPoint(x0 + dx / 2, y0 + dy / 2, 0)
                self.renderer.ResetCameraClippingRange(x0, x1, y0, y1, z0, z1)
```

What's the difference between `plt.show(interactive=1).close()` and `plt.interactive().close()`? 
(The results are different)


```
from vedo import *
settings.renderer_frame_alpha = 1
settings.use_parallel_projection = 0

m = Mesh(dataurl+"bunny.obj").c("blue8")

p = m.points()
bbox = p.max(0) - p.min(0)
w = bbox[0]
h = bbox[1]
hw = 600
ww = int(w / h * hw) * 4

plt = Plotter(shape=(1, 4), size=(ww, hw), offscreen=0)
plt.at(0).show(m)
plt.at(1).show(m)
plt.at(2).show(m)
plt.at(3).show(m)
plt.reset_camera(tight=0.1)
# plt.show(interactive=1).close()  <<< here
plt.interactive().close()
```

![image](https://user-images.githubusercontent.com/34391447/200183747-df01229a-4ae4-472e-9d3f-57bb89c02ba2.png)

![image](https://user-images.githubusercontent.com/34391447/200183755-fdb5cc3a-278e-40bc-8624-15fbda358790.png)

**Comment by marcomusy** [comment]
Nice, you are very welcome to make a pull request if you wish!

The difference is that `show()` by default makes a call to `reset_camera()` so it nullifies the first call to it. The equivalent would be:
`plt.show(interactive=True, resetcam=False)`
