### ISSUE TITLE
Whether to support sun type lighting

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#729]
Can I change the light like in MeshLab with `Ctrl + Shift + Left Click`?
The yellow line should be sun type lighting.

![image](https://user-images.githubusercontent.com/34391447/200738835-f0385e88-794f-44f5-9074-f295c9c74c4a.png)

**Comment by marcomusy** [comment]
Press `o` in the viewer multiple times to rotate the source and `O` (shift-o) to disable.

**Comment by Geniussh** [comment]
@marcomusy I found the default positions of the light source after pressing `o` is perfect for my visualization but how can I know which position it's been put? I could't find the source code that implements the behaviors of pressing `o` in the repo. Could you point me to it?

**Comment by marcomusy** [comment]
You can find it here:
https://vedo.embl.es/autodocs/content/vedo/vedo/plotter.html#Plotter-4364

```py
   plt = Plotter()
   # ...
        if key == "O":
            plt.renderer.RemoveLight(extralight)

        elif key == "o":
            vbb, sizes, _, _ = addons.compute_visible_bounds()
            cm = np.array([(vbb[0] + vbb[1]) / 2, (vbb[2] + vbb[3]) / 2, (vbb[4] + vbb[5]) / 2])
            if not extralight:
                vup = plt.camera.GetViewUp()
                pos = cm + np.array(vup) * utils.mag(sizes)
                extralight = addons.Light(pos, focal_point=cm, intensity=0.4)
                plt.renderer.AddLight(extralight)
            else:
                cpos = np.array(extralight.GetPosition())
                x, y, z = extralight.GetPosition() - cm
                r, th, ph = transformations.cart2spher(x, y, z)
                th += 0.2
                if th > np.pi:
                    th = np.random.random() * np.pi / 2
                ph += 0.3
                cpos = transformations.spher2cart(r, th, ph).T + cm
                extralight.SetPosition(cpos)
```
