### ISSUE TITLE
Converting a DICOM volume to STL (or any other appropriate 3D file format)

### ISSUE THREAD

**Issue by emmanuel-nwogu** [marcomusy/vedo#730]
I have a DICOM series that I would love to convert to a 3D file format while preserving the entire volume. I do prefer the STL format. 

I tried converting the volume to a mesh using iso-surfacing and the entire scalar range but I get a blank white screen.
Here's the code I used for that:
```python
from vedo import load, show

# tmpdirname is a DICOM folder
dcm_volume = load(tmpdirname)
# I have to comment out this show for the next one to work :(
show(dcm_volume)
scalar_range = dcm_volume.scalar_range()
print(scalar_range)
iso = dcm_volume.isosurface()
show(iso)
```

Here's a screenshot of the volume:
![image](https://user-images.githubusercontent.com/60305705/201005631-e978a415-2bf1-4ea2-a703-c71c00616e38.png)

Thanks in advance. :)

**Comment by marcomusy** [comment]
Hi Emmanuel , 
I updated your code above. You should set a specific value of the threshold in-between the range (or leave it black for an automatic choice).
If you give it the extremes it will necessarily output a blank mesh (no points and no faces).
You can also pass a list of values all of them in the same range.

Let me know if anything is not clear.

**Comment by emmanuel-nwogu** [comment]
Thanks for the reply :)

Just to confirm, does leaving `isosurface()` blank preserve the entire volume when converted to a mesh?

**Comment by marcomusy** [comment]
What do you mean with "preserve"?
isosurface gives a **polygonal mesh** which spans the space points that have the same value of the scalar (the value that you can specify with isosurface(value)).

**Comment by emmanuel-nwogu** [comment]
I have a solid volume loaded from a DICOM series/folder. Now, I want to save this volume in a 3d format which is why I am converting to mesh with isosurface and then saving as STL. 
With my limited knowledge of isosurface, I believe I'm trying to "preserve" all the scalars present in the volume while converting to mesh. If there's a better method for saving this volume as STL, please let me know.

**Comment by marcomusy** [comment]
Uhm, note that STL has nothing to do with DICOM as they are different types of data (polygonal vs volumes), I'm not sure if STL allows storing the scalars ... you can try with:
```python
from vedo import *
vol = load(...)
iso = vol.isosurface(some_value)
iso.print() # this will show what scalar data is contained
iso.write("file.stl")

# check
msh = Mesh("file.stl")
msh.print()
```

**Comment by emmanuel-nwogu** [comment]
Thanks for the reply. :)

I have a question about the threshold parameter. What happens when I pass a list to it? Would all the space points that match each value in this list be used in the conversion to mesh?
Also, the name "threshold" is confusing to me. As you said earlier, this is simply an isovalue, right? The name to me implies that all scalars greater than or equal to the passed value will be used in the conversion to mesh.

**Comment by marcomusy** [comment]
> I have a question about the threshold parameter. What happens when I pass a list to it? Would all the space points that match each value in this list be used in the conversion to mesh?

isosurfaces will be generated at the given values in the list.
Note that the output is a single polygonal mesh object even if surfaces are physically disconnected.

>  the name "threshold" is confusing to me. As you said earlier, this is simply an isovalue, right? The name to me implies that all scalars greater than or equal to the passed value will be used in the conversion to mesh.

You are absolutely right! I will change that to "value", thanks for making me notice it.

**Comment by emmanuel-nwogu** [comment]
>isosurfaces will be generated at the given values in the list.

I'm considering passing a list of values in a wide range with a very small step value. E.g. [-400, -399, -398,...,100]. As I said earlier, my main goal is to retain as many scalars as I can during the conversion to mesh. Is there a way to obtain all the scalars in a volume alongside their frequencies of occurrence?

> You are absolutely right! I will change that to "value", thanks for making me notice it.

No problem, good luck! :)

**Comment by emmanuel-nwogu** [comment]
Lol, I see. Also, thanks for being very patient, I appreciate it.

Also, I think our agreement on the `threshold` value earlier may be false. It does seem to be an actual threshold parameter. When I start at `scalar_range[0]`, I get a blank white screen. However, when I start at `scalar_range[0] + 1`, I get a mesh that seemingly contains all the scalars by visual inspection. As I increase the threshold value toward `scalar_range[1]`, I get fewer and fewer details in the mesh with a final blank white screen at `scalar_range[1]`.

**Comment by marcomusy** [comment]
No worries.

I still think you were right in saying that I was wrong :)
What you describe is indeed compatible with a value-defined function: few points in the volume will have a scalar value close to the range boundaries (hence the blank screen).
