### ISSUE TITLE
How to construct tetrahedron using vessel surface?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#731]
Please have a look at following picture:

![image](https://user-images.githubusercontent.com/29271051/200995988-bf4e2bde-71c9-4277-80b1-278ab8874508.png)

If I have a 3D vessel surface (the black), how to construct the inside tetrahedron just like the red color.

**Comment by marcomusy** [comment]
There are many tools to create a tetmesh (eg TetGen), vedo can also do it:
```python
from vedo import Tube, Sphere, show

surf = Sphere(quads=True, res=15)
# surf = Tube([(0,0,0), (1,1,1), (2,3,4)], res=15)

tmesh = surf.tetralize(side=0.025, debug=True)
#tmesh.write('mytetmesh.vtk')  # save to disk!

show(tmesh.tomesh().alpha(1), axes=1)
```
![Screenshot from 2022-11-10 15-51-55](https://user-images.githubusercontent.com/32848391/201123934-646182d5-09b7-4e2e-9b4e-c0b69c56e7be.png)

check also
https://github.com/marcomusy/vedo/blob/master/examples/volumetric/tetralize_surface.py

**Comment by zhang-qiang-github** [comment]
Thank you very much ~~~

**Comment by zhang-qiang-github** [comment]
For `tmesh.tomesh()`, how to set `alpha=0` for face, but `alpha=1` for all lines? In this way, I want to see only the line.

**Comment by marcomusy** [comment]
use `.wireframe()` instead.

**Comment by zhang-qiang-github** [comment]
thx~~~
