### ISSUE TITLE
Parameters of Arrow

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#733]
Can I change the arrow type like in PPT
![image](https://user-images.githubusercontent.com/34391447/201964123-b8122258-79d7-4a2f-9e95-8ccf0bf5be53.png)
![image](https://user-images.githubusercontent.com/34391447/201964137-b2211a35-ff27-4319-9f2c-bcf14122e7e4.png)

The arrow obtained by the following code is too long,
```
        Ax = Arrow((-2, 0, 0), (2, 0, 0), s=0.001, res=8, c="r")
        Ay = Arrow((0, -2, 0), (0, 2, 0), s=0.001, res=8, c="g")
        Az = Arrow((0, 0, -2), (0, 0, 2), s=0.001, res=8, c="b")
        S = Sphere(O, 1, alpha=0.35, c="grey")
```
![image](https://user-images.githubusercontent.com/34391447/201964352-e5c50ed9-2a3e-4d37-bf74-277dd464860e.png)

Of course, the `axes=2` looks pretty good
![image](https://user-images.githubusercontent.com/34391447/201964944-52810f06-0223-4a48-adb3-3a1583e09868.png)

No relevant settings were found in the source code
```
class Arrow(Mesh):
   
    def __init__(self, start_pt=(0, 0, 0), end_pt=(1, 0, 0), s=None, c="r4", alpha=1, res=12):

```

**Comment by marcomusy** [comment]
You are right, I've added new kwargs:
- install head version then

```python
from vedo import *

arropt = dict(
    shaft_radius=0.0075, 
    head_length=0.1, 
    head_radius=0.02, 
    res=8,
)
Ax = Arrow((-2, 0, 0), (2, 0, 0), **arropt, c="r")
Ay = Arrow((0, -2, 0), (0, 2, 0), **arropt, c="g")
Az = Arrow((0, 0, -2), (0, 0, 2), **arropt, c="b")
S = Sphere(alpha=0.35, c="grey")

show(Ax,Ay,Az, S, axes=1)
```
<img width="348" alt="Screenshot 2022-11-15 at 22 19 53" src="https://user-images.githubusercontent.com/32848391/202033322-d7c239e1-a6b4-4fb8-b1e0-eb6356caf5bf.png">
