### ISSUE TITLE
Making Mesh.binarize() faster and better

### ISSUE THREAD

**Issue by vfmatzkin** [marcomusy/vedo#735]
Hello. I'm working with meshes of ~8k points and used vedo.Mesh.binarize() to convert to volume. Even if it is a very great method, it lacks some features that can be implemented as the custom spacing setting:

- Set custom dimensions (not using the mesh bounds)
- Set custom origin.
- Set custom direction matrix (useful for setting a custom orientation).

Other not very important (as setting a custom foreground value) could be easily implemented as default params of the method.

I wanted to do this since I start with volumes, get meshes of things on its surface, and then I want to save the binarized version of them in the same space as the input volumes, and using .binarize() produces a volume in a completely different space.

Finally, a small detail I've noticed and produces the same results (but in milliseconds vs minutes) is replacing these lines:

```
        count = whiteImage.GetNumberOfPoints()
        for i in range(count):
            whiteImage.GetPointData().GetScalars().SetTuple1(i, inval)
```

with

```
    whiteImage.GetPointData().GetScalars().Fill(inval)
```

This removes the bottleneck and produces the result almost instantly.

I'm not an expert in vtk though, I see (and hope) the results remain the same 👍🏽

**Comment by marcomusy** [comment]
Thanks a lot! I didn't know of the Fill method, would you like to make a PR with this as you seem to have clear ideas of what's needed?
