### ISSUE TITLE
lighting('off') do not work

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#743]
The code to reproduce my question is:

```
from vedo import Tube, Sphere, show

surf = Sphere(quads=True, res=15)

mesh = surf.tetralize(side=0.025, debug=False).tomesh().lighting('off').alpha(0.01)

show(mesh, axes=1)
```

and the result is:

![image](https://user-images.githubusercontent.com/29271051/204736722-cb348b1e-05d2-44b0-b948-e989e437cec6.png)

I hope it can obtain the `lightingOff` result.

**Comment by marcomusy** [comment]
by looking at your image it seems to me that it is already working!
infact if you set alpha(1) you should see a uniform yellow color sphere without lighting effects.

You may also need to play with 
`settings.use_depth_peeling = True`
for alpha < 1.

**Comment by zhang-qiang-github** [comment]
`settings.use_depth_peeling = True` helps.
