### ISSUE TITLE
Boolean failed

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#744]
Sorry for asking a more question. The code to reproduce is:

```
from vedo import *

s1 = Sphere(pos=[-0.7, 0, 0], c="red5", alpha=0.5)
s2 = Sphere(pos=[0.7, 0, 0], c="green5", alpha=0.5)

b3 = s1.boolean("minus", s2).c('r')
b4 = s1.boolean("minus", b3)

show(b4)
```

A bug is reported: `Process finished with exit code -1073741819 (0xC0000005)`

The version is: `2022.4.1`

I want to obtain `b4`, which belong to `s1` and included by `s2`. Is there any solution? 

Thx for any suggestion~~~

**Comment by marcomusy** [comment]
hi,
no, `s1-b3` is not the blue, it is all that is red minus all that is green.
it's like removing or take out from s1 what belongs to b3.

**Comment by zhang-qiang-github** [comment]
Please have a look at following picture.

![image](https://user-images.githubusercontent.com/29271051/205441913-056cb0a0-8242-4c76-9b1c-a140c86019dd.png)

The  `s1` should be the left circle, and `b3` should be the black part. 

> it's like removing or take out from s1 what belongs to b3.

The b3 is the black part. If remove the black part from s1, only the blue part remain. So the blue part should be the `s1-b3`. What's wrong with this processing?

**Comment by marcomusy** [comment]
it's wrong because the black part is not inside the green, so it's not removed.
in your scheme `red - green = black`, that's how the `-` operation is defined.
let me know if it's not clear

**Comment by zhang-qiang-github** [comment]
> in your scheme red - green = black, that's how the - operation is defined.

Is `red - black=blue` correct? How to obtain the blue part?

**Comment by marcomusy** [comment]
yes, that would be:
`s1.boolean("intersect", s2)`

**Comment by marcomusy** [comment]
In the new release I added `boolean(..., method=1)` you can experiment with.
