### ISSUE TITLE
How to cut a plane with a mesh?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#747]
I have a mesh and plane. I am failed to cut the plane with the mesh.

The code I am testing is:

```
from vedo import *

c = Cylinder(pos=[0, 0, 0], r=10, height=10)

verts = [(-20, -20, 0), (20, -20, 0), (20, 20, 0), (-20, 20, 0)]
faces = [(0,1,2, 3)]

mesh = Mesh([verts, faces])

ret = mesh.clone().cutWithMesh(c)

show([(c, mesh), ret], N=2)
```

And the result is empty (right):

![image](https://user-images.githubusercontent.com/29271051/206178141-80d6e0fb-90de-4cf8-91e8-a5ee97283be1.png)

I expect the following result:

![image](https://user-images.githubusercontent.com/29271051/206178589-78ac1342-f3e4-4722-952d-c97c37b1025c.png)

How can I implement this requirement? Any suggestion is appreciated~~~

**Comment by marcomusy** [comment]
To cut a mesh you need to have vertices inside the cutting object. You can obtain this by subdividing the square into smaller elements:
```
pip install vedo -U
```
then:
```python
from vedo import *
verts = [(-20, -20, 0), (20, -20, 0), (20, 20, 0), (-20, 20, 0)]
faces = [(0,1,2, 3)]
mesh = Mesh([verts, faces]).subdivide(4, method=1).lw(1)
c = Cylinder(pos=[0, 0, 0], r=10, height=10)
ret = mesh.clone().cut_with_mesh(c)
# c = None
# ret = mesh.clone().cut_with_cylinder([0,0,0], axis=[0,0,1], r=10) # much faster
show([(c, mesh), ret.c("red4")], N=2)
```
![Screenshot from 2022-12-07 13-34-28](https://user-images.githubusercontent.com/32848391/206180882-c6cfd6bd-2679-4774-8f23-3b8f71a710ff.png)

**Comment by zhang-qiang-github** [comment]
Thank your very much for the kindly reply.

![image](https://user-images.githubusercontent.com/29271051/206189404-1b8ff50c-93d4-4093-8765-034d523fcd2d.png)

I want to know what's the meaning of `4` in `subdivide(4, method=1)`. The function explanation shows: `n: number of subdivisions`.  I find there are 16 squares in the yellow plane. How to understand the `4&16`?

**Comment by marcomusy** [comment]
method=1 subdivides the mesh by splitting elements in 2 each time, so 16 = 2^n = 2^4.

**Comment by zhang-qiang-github** [comment]
In addition, when I rotate it, a strange thing happen:

![image](https://user-images.githubusercontent.com/29271051/206190569-0ec4bd18-4361-444e-bbc8-c44df016ab80.png)

Is it a bug?

**Comment by marcomusy** [comment]
No, it's probably the visualization that clips in the range of the object - click on the renderer then press `r`
