### ISSUE TITLE
View from Front

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#754]
How can I quickly align the angle of view through the numeric keypad like in blender or meshlab?

**Comment by marcomusy** [comment]
It's a nice addition, I will put it in the next release. 
If you use vtk 9.2 then you also have `axes14` active option:

```python
from vedo import *

def reset_viewup(evt):
    if evt.keypress == "v":
        x0,x1, y0,y1, z0,z1 = plt.renderer.ComputeVisiblePropBounds()
        mx, my, mz = (x0+x1)/2, (y0+y1)/2, (z0+z1)/2
        d = np.sqrt((x1-x0)**2+(y1-y0)**2+(z1-z0)**2) * 2
        vui = np.argmax(np.abs(plt.camera.GetViewUp()))
        viewups = [(0, 1, 0), (0, 0, 1), (1, 0, 0)]
        positions = [(mx, my, mz+d), (mx, my-d, mz), (mx, my-d, mz)]
        plt.camera.SetViewUp(viewups[vui])
        plt.camera.SetPosition(positions[vui])
        plt.renderer.ResetCameraClippingRange(x0, x1, y0, y1, z0, z1)
        plt.render()

settings.use_parallel_projection = True

plt = Plotter(axes=14, bg='black')
plt.add_callback("key press", reset_viewup)
m = Mesh(dataurl+"panther.stl")
plt.show(m, Axes(m))
```

pressing `v` will snap to the next viewup.

![Screenshot from 2022-12-13 20-22-46](https://user-images.githubusercontent.com/32848391/207426219-ed965e20-081f-496c-9923-55dfbb3b6c25.png)

**Comment by marcomusy** [comment]
Just added method `plt.reset_viewup().render()` which snaps the camera to the closest orthogonal view.
Pressing `"R"` will automatically trigger it.

**Comment by LogWell** [comment]
Thank you very much. 

I hope to support all view functions in meshlab, including rotating a certain angle around the axis (currently, the main function of the numeric keypad is cycle axes style), which is very friendly for browsing and comparing meshes.

**Comment by LogWell** [comment]
In addition, after selecting an object in `blender`, you can zoom in to the center through `.`. Double clicking on a point in `meshlab` has a similar function so that I can quickly locate the area of interest.

Hopes similar functions can be added~

**Comment by marcomusy** [comment]
Added `'.'` to fly to to the last clicked point and zoom in.

I would not add more options unless they are well motivated to avoid bloating..
