### ISSUE TITLE
Strange rendering in numpy2volume2  example

### ISSUE THREAD

**Issue by LindyBalboa** [marcomusy/vedo#756]
Hi, when I run the numpy2volume2 example, I would expect the shapes to have relatively smooth surfaces, instead I get these odd stripes. I would appreciate an explanation and suggestion if it is possible to get a more uniform color that is just directly from the color array?

Stationary
![image](https://user-images.githubusercontent.com/20605205/207536256-292dc45d-f878-4b77-9c1d-1bef5e657d82.png)

Rotating with mouse
![image](https://user-images.githubusercontent.com/20605205/207536781-6dc4c3ad-63b4-493c-b61a-e316028d44ca.png)

**Comment by marcomusy** [comment]
You can play with different modes of visualisation, have you tried
`vol.mode(1)`
The default is 0 which adds some reflection effect which for simple volumes like the one above is not ideal.

<img width="310" alt="Screenshot 2022-12-14 at 10 54 43" src="https://user-images.githubusercontent.com/32848391/207565604-04463b9b-db03-4165-a646-ca4141eaba46.png">

**Comment by LindyBalboa** [comment]
That is better, but is there anywhere to retain the edges?

**Comment by marcomusy** [comment]
The thing is that there are no "edges"! this is a volumetric dataset so the edges would be the isosurfaces at a specific set of values (not lines).
