### ISSUE TITLE
fit_plane creates a plane centered at origin

### ISSUE THREAD

**Issue by jcoronel** [marcomusy/vedo#757]
The function fit_plane fits a plane, given a set of points, but the result is centred at origin of coordinates.

Code to reproduce the behaviour:

ptosN = np.array([[0.6,	20.7,	-43.9,	0,	0],
                [0.8,	-21.5,	-44.1,	0,	0],
                [43.7,	20.6,	-43.5,	0,	0],
                [43.5,	-22.1,	-43.5,	0,	0]])
nortePL = v.fit_plane(ptosN)

To solve this behaviour, you simply have to position the plane at the sample points mean, this way:
nortePL.pos(np.mean(ptosN[:,0]), np.mean(ptosN[:,1]), np.mean(ptosN[:,2]))

Where np is for numpy library.

I am not sure if this is a desired behaviour or not, so I comment this here, just in case.
I am newbie using GitHub, so please correct me if this way of doing things is not right.

**Comment by jcoronel** [comment]
Ciao Marco,

Sorry for my mistake. Of course, you have to take only 3 axes, not 5 as i
wrote (I am working with a 5 axes robot).

Anyway, I am getting a very different result:
[image: screenshot.png]
I get the same as you after repositioning the plane... This is very
weird....
I use Python 3.9.16, Vedo 2022.4.1, vtk 9.0.3 and numpy 1.23.2
I have just checked the code of the function at pointcloud.py in my
library. It is the same as the version at GitHub. I guess this could be
something related to Single Value Decomposition on Numpy.

**Comment by marcomusy** [comment]
Unfortunately I cannot see your screenshot!
My system is
```
_________________________________________________________________
vedo version      : 2022.4.1.dev10   https://vedo.embl.es
vtk version       : 9.0.3
numpy version     : 1.21.6
python version    : 3.9.13 (main, Aug 25 2022, 23:26:10) [GCC 11.2.0]
python interpreter: /home/musy/soft/anaconda3/bin/python
```

You may try
```
pip install -U git+https://github.com/marcomusy/vedo.git
```
to make sure we are on the same page.

**Comment by jcoronel** [comment]
I have edited my last post. Now you can check the image there (including images via e-mail answer does not work).
I have tried to downgrade Numpy, but I had got the same result. So I reinstalled Numpy  1.23.2 and installed Vedo version as you recommended. Now it works perfectly.
I suppose that the error comes from any issue on the version installed by pip. I upgraded from an earlier version of Vedo about a week ago.
Marco, thanks a lot for your help.!
Ciao

**Comment by marcomusy** [comment]
I'm glad it finally works, it's a bit weird that a different numpy can cause that..

**Comment by jcoronel** [comment]
Yes it is, but I have suffered so many weird things using Python... ;-)
