### ISSUE TITLE
Multi windows generation

### ISSUE THREAD

**Issue by FrancoisMasson1990** [marcomusy/vedo#76]
Is it possible to generate multiple windows at the same time ?
For exemple with *.dcom files open at the same time --ray_cast_mode and --slicer mode ?

Thanks

**Comment by marcomusy** [comment]
aside from the obvious invoking multiple times `vtkplotter --ray_cast_mode dir.dcom` and `vtkplotter --slicer dir.dcom`
an other way of having multiple windows is by writing a small script like this:
```python
from vtkplotter import load, show
d1 = load('first.dcom')
d2 = load('second.dcom').isosurface()
vp1 = show(d1, interactive=False)
vp2 = show(d2, newPoltter=True, pos=(200,200), interactive=True)
# ...
# vp are different instances of the Plotter class
```
but the --slicer option is only available in the bash script at the moment.

**Comment by FrancoisMasson1990** [comment]
Thanks and do you know when it will be possible to call slicer and visualize it via a Plotter class ?

**Comment by marcomusy** [comment]
I'm not 100% sure if it is possible to include it, I'll think about it for the next release (one week or so..).

**Comment by marcomusy** [comment]
I close this as it is now implemented in `vedo.applications`
