### ISSUE TITLE
about fill_holes()

### ISSUE THREAD

**Issue by rlczddl** [marcomusy/vedo#760]
Hi, the filled triangular by mesh.fill_holes() have different direction than original mesh's triangulars, how to fix?
Before fill：
![image](https://user-images.githubusercontent.com/21055131/207795937-c23ce6af-892e-46e8-b6d2-223076ecb81e.png)

After fill:
![image](https://user-images.githubusercontent.com/21055131/207796153-467777d9-3a48-4ce9-84c0-df233c9c6473.png)
![image](https://user-images.githubusercontent.com/21055131/207796244-89614645-af89-4d21-8aae-485dad101e76.png)

**Comment by marcomusy** [comment]
Have you tried `mesh.compute_normals()` ?

**Comment by rlczddl** [comment]
> 

Thanks a lot, it fixed the problem!!!
