### ISSUE TITLE
isosurface shows unexpected figure

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#761]
I am using a tool (3D Slicer) to make a binary volume mask. The tool shows the result as:

![image](https://user-images.githubusercontent.com/29271051/208010991-e53fdd14-7212-411a-bd53-2baa10308cca.png)

Then, I export this binary volume mask, and show it with `vedo`, and the result is:

![image](https://user-images.githubusercontent.com/29271051/208011093-629731ed-cf45-49e8-80a9-2b385e9b9340.png)

In this figure, the black part is unexpected. 

My code is:

```
from vedo import *
image_array = np.load('image.npy')
vol = Volume(image_array).isosurface(1).alpha(1)
show(vol)
```

Data is:

[image.zip](https://github.com/marcomusy/vedo/files/10242257/image.zip)

How to make the figure all blue? Any suggestion is appreciated~~~

**Comment by zhang-qiang-github** [comment]
Is it possible to keep `lighting on` and remove the black part in the same time?

**Comment by marcomusy** [comment]
you can try with `.compute_normals()` but where the mesh is non-manifold it may still fail..
