### ISSUE TITLE
Plot show viewup not implemented

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#764]
Hi, 

I want to plot a 3D shape with from vis3d perspective automatically.
from documentation i found that 
```
viewup: str, list
        either ['x', 'y', 'z'] or a vector to set vertical direction
```
but in code i do not find implementation of the "vector" option.

Am I missing something or is this indeed not implemented (if the latter is true could this be implemented)? :)

Best

Paul

**Comment by marcomusy** [comment]
You're right!
I've modified the behavior of `viewup`. Eg:

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then

```python
import vedo
vedo.settings.use_parallel_projection = True
m = Mesh(dataurl+"bunny.obj")
m.texture("texture_8k.png")
m.show(axes=1, viewup=[1,1,0])
```

<img width="427" alt="Screenshot 2022-12-18 at 21 44 34" src="https://user-images.githubusercontent.com/32848391/208318555-22a39d28-aedd-437b-8058-66237937a2c3.png">

note that this keyword is only meant to get a "quick and dirty" meaningful orientation of the camera - to get proper control of it please use `show(camera=...)` (press `Shift-C` to get a template code printout).

**Comment by paul0noah** [comment]
Thanks a lot, this is what i need! :)
