### ISSUE TITLE
Large Texture Distortion using mesh.texture('texture.png')

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#765]
Hi, 

I want to apply a checkerboard texture (click on image for full res):
<img width="250" alt="texture_8k.png" src="https://user-images.githubusercontent.com/38716946/208310038-5ee0369f-398f-4d63-8aaf-8e6880929834.png">
to a shape. From tutorials i found that textures can be applied to meshes via 
```
mesh.texture('texture_8k.png')
```
Unfortunately, i find the current results not pleasing as there is a lot of distortion:
<img width="400" alt="cat" src="https://user-images.githubusercontent.com/38716946/208310122-9bb988b0-8d3a-4fa8-ab76-7f78a2702d72.png">

Am I missing something here which allows to improve the results? :)

Thanks a lot!

Paul

**Comment by marcomusy** [comment]
It's unavoidable unless you can define the (u,v) texture coordinates for the mesh.
