### ISSUE TITLE
how to display selected 3d point?

### ISSUE THREAD

**Issue by rlczddl** [marcomusy/vedo#766]
How to display selected 3d point using the mouse event on the render window? 
Here is code:
```
SELECT_CLICK_Point = [0, 0, 0]

def  onLeftClick(event):
    global SELECT_CLICK_Point
    SELECT_CLICK_Point = event.picked3d
    print("clicked: ", event.picked3d)

def click_point(vs, fs):
    mesh = to_vedo(vs, fs)
    plt = vedo.Plotter()
    plt.add_callback('LeftButtonPress', onLeftClick)
    plt.show(mesh)
    select_point_id = mesh.closest_point(SELECT_CLICK_Point, return_point_id=True)
    return select_point_id
```

**Comment by rlczddl** [comment]
It can be done by plt.add(Point(event.picked3d)) on the callback  function. Another question: can i pass external parameter to the callback function, such as this example's the plt object(vedo.Plotter()) and the SELECT_CLICK_Point object?

**Comment by marcomusy** [comment]
> can i pass external parameter to the callback function

No, but you can create a class and make those parameters members of the class (this is what I usually do).

**Comment by marcomusy** [comment]
Also in your code above you dont need to wrap `to_vedo()`, you can call directly `Mesh([vs,fs])`.

The block 
```
    plt = vedo.Plotter()
    plt.add_callback('LeftButtonPress', onLeftClick)
    plt.show(mesh)
```
should be outside of the callback (should be in the main).

**Comment by rlczddl** [comment]
> > can i pass external parameter to the callback function
> 
> No, but you can create a class and make those parameters members of the class (this is what I usually do).

ok，I see.


> Also in your code above you dont need to wrap `to_vedo()`, you can call directly `Mesh([vs,fs])`.
> 
> The block
> 
> ```
>     plt = vedo.Plotter()
>     plt.add_callback('LeftButtonPress', onLeftClick)
>     plt.show(mesh)
> ```
> 
> should be outside of the callback (should be in the main).

Yes, I have done it.
