### ISSUE TITLE
Direction of shadow in mesh not implemented

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#767]
Hi Marco, 

Looking into the code of the `vedo.mesh` class i found that it is possible to add shadows via `add_shadows` function (which is already very nice thing to have as one does not have to add a plane on which the shadow casts!).
I want to cast a shadow in a specific [direction](https://github.com/marcomusy/vedo/blob/3a7f7f6de10d3536a66da3283693bd8962e5c5e8/vedo/mesh.py#L1272-L1273) but i found from the code that this is not possible as one has to specify positional argument `plane` which results in that the [else](https://github.com/marcomusy/vedo/blob/3a7f7f6de10d3536a66da3283693bd8962e5c5e8/vedo/mesh.py#L1302-L1303) case cannot be reached (which would generate the projection).

Things which are not yet clear to me:  will the direction cast the shadow onto the plane with normal `direction` or will it cast the shadow with a different direction on the e.g. the 'z' plane (i would be interested in the latter).

Thanks a lot for the great work!

Paul

**Comment by marcomusy** [comment]
Try
```python
from vedo import *

settings.use_depth_peeling = False # depending on your system

plt = Plotter(axes=8)

msh = Mesh(dataurl+"man.vtk").c("k5")

plane = Plane(pos=(0,0,-1.6), normal=(0,0,1), s=[7,7]).alpha(0.2)

shad = msh.clone().project_on_plane(plane, direction=(0.5,1,-1))
shad.c("k7").alpha(1).lighting("off").use_bounds(False)

plane.shift(0,0,0.001) # a small tolerance to avoid coplanarity with shad

plt.show(msh, plane, shad).close()
```
![Screenshot from 2022-12-19 12-08-16](https://user-images.githubusercontent.com/32848391/208414200-95b8dc1d-c804-40f8-8c4d-4c443c42108e.png)

**Comment by paul0noah** [comment]
Awesome! Especially when using 
```
plt.show(msh, shad).close() # don't plot the plane
```
Allows me to generate nice plots without having the issue that the plane is blocking the view from the underside of the mesh :) Maybe you can integrate sth like this into the example section!
