### ISSUE TITLE
Animations not working

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#768]
Hey Marco, 

I tried to run the example [airplane1.ply](https://github.com/marcomusy/vedo/blob/master/examples/simulations/airplane1.py) but discovered that i do not get an animated plot but rather only the last frame. In other words, the plot-window is only opening for the last frame whenever plot.interactive is called.
I am running the code in pycharm with anaconda environment on mac os (arm processor).

Any tips how i can make this work?

Thanks a lot!

Paul

**Comment by marcomusy** [comment]
Hi Paul, Yes this is a problem with OSX.. you need to make a call to `plt.interactive()` the press `q`:
```
...
# Setup the scene
plt = Plotter(axes=1, interactive=False)
plt.show(world).interactive() ###############

for t in np.arange(0, 3.2, 0.02):

    plane.pos(9*t-15, 2-t, sin(3-t)).rotate_x(0+t) # make up some movement

    plt.show(world, plane, __doc__, viewup="z")
    if plt.escaped:
        break  # if ESC button is hit during the loop

**Comment by paul0noah** [comment]
Thanks, this works for me!
Is it possible to code input q? so i dont need interaction from user?

**Comment by marcomusy** [comment]
I think I managed to find a better solution, check out the dev version and look at
https://github.com/marcomusy/vedo/blob/master/examples/simulations/airplane1.py
https://github.com/marcomusy/vedo/blob/master/examples/simulations/airplane12py

**Comment by paul0noah** [comment]
I installed dev version and verified in code that I am indeed using dev version via 

```
vedo.version._version # evaluates to "2022.4.2.dev3"
```

But the behavior is still the same as before (plot window only opens when animation is done or rather when call to interactive() happens)

**Comment by marcomusy** [comment]
Yes, sorry I just disabled it.. I need to understand better how this can work (it does ok in OSX but not in ubuntu)...

**Comment by paul0noah** [comment]
no problem, let me know if you figured it out, i am happy to test it

**Comment by j042** [comment]
I had a same issue with macos - arm processor.
If you add 
```python
        else:
            self.process_events()
```
to https://github.com/marcomusy/vedo/blob/0f3688a04571c9d890bb53135502bc3dbabd7682/vedo/plotter.py#L3138 if-block, examples (airplane1, airplane2, tunnelling1, epicycles, gas, org_maps2d, ...) run properly for me. Would this have any unexpected side-effects @marcomusy?

**Comment by marcomusy** [comment]
Hi @j042 - yes it seems to work fine on OSX system but not on linux.
In fact you don't to change the source code, just add in 
https://github.com/marcomusy/vedo/blob/master/examples/simulations/airplane1.py

```python
...
    plt.show(world, airplane, __doc__, viewup="z", resetcam=False)
    plt.process_events()
```

**Comment by paul0noah** [comment]
> Hi @j042 - yes it seems to work fine on OSX system but not on linux. In fact you don't to change the source code, just add in https://github.com/marcomusy/vedo/blob/master/examples/simulations/airplane1.py
> 
> ```python
> ...
>     plt.show(world, airplane, __doc__, viewup="z", resetcam=False)
>     plt.process_events()
> ```

This works for me on OSx, thanks :)
