### ISSUE TITLE
How to speed up subdivide & cut_with_mesh

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#771]
My purpose: I have a mesh, and I want the intersect polygon between the mesh and a plane.

I want to implement it by `cut_with_mesh`. And my code is:

```
from vedo import *
import time

path = 'polydata.stl'
mesh = Mesh(path).alpha(0.3).c('b')

verts = [(98.8976, 63.9544, -25.9882), (98.8976, 63.9544, -53.3378), (98.8976, 36.6048, -53.3378), (98.8976, 36.6048, -25.9882)]
faces = [(0,1,2, 3)]

start = time.time()
plane = Mesh([verts, faces]).subdivide(n=4, method=1).lw(1)
ret = plane .clone().cut_with_mesh(mesh)
end = time.time()
print(end-start)
show([(plane, mesh), ret.c("red4")], N=2)
```

[polydata.zip](https://github.com/marcomusy/vedo/files/10293258/polydata.zip)

The result is:

![image](https://user-images.githubusercontent.com/29271051/209292412-bc6267f0-503f-43cd-b51b-6e9c9b3ba067.png)

The red part in the right figure is the intersect polygon, and the result is poor. The reason is the resolution of `plane` is poor, which `subdivide` only 4. If I improve it to 7, the result is:

![image](https://user-images.githubusercontent.com/29271051/209292749-848d929c-72e0-4005-aee5-29641bea0161.png)

The result is still not perfect (please see the green arrow).  But the computation time is 0.23s.

Even though the `subdivide(n=10)` may solve this problem, but the computation time should be huge.

How can I speed up this process? Any suggestion is appreciated~~~

**Comment by marcomusy** [comment]
I would do:
```python
from vedo import *
path = 'polydata.stl'
mesh = Mesh(path).alpha(0.3).c('b')
ret = mesh.clone().intersect_with_plane(origin=(98,0,0), normal=(1,0,0))
ret = ret.join().triangulate().c("red4")
show(mesh, ret, axes=1)
```

<img width="281" alt="Screenshot 2022-12-23 at 16 13 36" src="https://user-images.githubusercontent.com/32848391/209358148-5deef06c-022c-4628-86e9-a7410bdbaa3c.png">

**Comment by zhang-qiang-github** [comment]
Thank you very much for kindly reply~~~
