### ISSUE TITLE
Can I set the rotate center to a point not the center of  render view?

### ISSUE THREAD

**Issue by timeanddoctor** [marcomusy/vedo#773]
```
from vedo import Plotter, Cube

def callbck(evt):
    if evt.actor:
        #plt.fly_to(evt.picked3d)
        plt.camera.SetFocalPoint(evt.picked3d)

plt = Plotter(axes=1)
plt.addCallback("LeftButtonPress", callbck)

c1 = Cube()
plt.show(c1)
```

If I changed the focal of the camera but the render would fly to the center of point.

**Comment by timeanddoctor** [comment]
![image](https://user-images.githubusercontent.com/28825816/209900325-5b1b8460-e37e-4c0f-bd67-d5286c3a2d1e.png)

**Comment by timeanddoctor** [comment]
Can I set the rotate center not as the camera focal position?

**Comment by marcomusy** [comment]
Uhm - sorry I not sure I understand what you're trying  to achieve, but I cannot see a different of doing it other than setting the camera properties (`SetFocalPoint` etc) as you are already doing it.
You can change to 
`plt.add_callback("Interaction", callbck)`
to trigger the callback continuously (comment out the if statement too).
