### ISSUE TITLE
Why volume center is diffrent with 3DSlicer center

### ISSUE THREAD

**Issue by zyy13579** [marcomusy/vedo#778]
I use vedo convert the nifti label volume to obj mesh,by this code
```
vol = load(label_path)
m = vol.isosurface(1)
write(m, obj_file_path)
```
but,the coverted obj file center,is diffrent with 3DSlicer convert obj file
![WX20230105-144752](https://user-images.githubusercontent.com/3821208/210718838-78379fc0-ee10-4ddb-89e4-bbe2b770fe4e.png)

So I try to change the volume center,but I saw the code of fucntion center is this
```
def center(self, center=None):
        """Set/get the volume coordinates of its center.
        Position is reset to (0,0,0)."""
        if center is not None:
            cn = self._data.GetCenter()
            self._data.SetOrigin(-np.array(cn) / 2)
            self._update(self._data)
            self.pos(0, 0, 0)
            return self
        return np.array(self._data.GetCenter())
```
the center paramter is not use.
Is set center any problem?Thanks a lot

**Comment by zyy13579** [comment]
I mean the mesh convert by vedo,have a diffrent coordinate with the 3dslicer covert, image origin has been changed
I want use vtkjs show the mesh(by vedo convert),and draw some measureline,
so I find  coordinate is not right,the center of vedo have a offset compare by slicer
[obj_file.zip](https://github.com/marcomusy/vedo/files/10543521/obj_file.zip)

**Comment by marcomusy** [comment]
Uhm , I'm not sure why you get a different a shifted and rotated image in slicer3d, it looks correct here:
```python
from vedo import *
vol = Volume("all_vessel.nii")
iso = vol.isosurface()
iso.write("iso.obj")
iso2 = Mesh("iso.obj")  # read back
show(vol, iso, iso2, N=3, axes=1)
```
<img width="793" alt="Screenshot 2023-02-02 at 14 26 53" src="https://user-images.githubusercontent.com/32848391/216337771-e3ddec18-f9c0-473d-bcba-2404b5af24fc.png">

**Comment by zyy13579** [comment]
I think,when vedo load volume,the origin offset has been made.
![image](https://user-images.githubusercontent.com/3821208/216505243-f083f413-96e7-4883-8b25-303e7a9b5a1d.png)
so I try to change center of volume by this code,but failed
`  label_img = sitk.ReadImage(volume_path)
    raw_origin = label_img.GetOrigin()
    print(raw_origin)
    print(label_img.GetSpacing())
    print(label_img.GetSize())
    vol = load(label_path)
    print(vol.origin())
    print(vol.spacing())
    print(vol.dimensions())
    print(vol.center())

    vol = vol.origin(raw_origin)
    vol = vol.center([0,0,0])
    # vol = vol.center(ci)
    print(vol.origin())
    print(vol.center())
    print(vol.origin())`

**Comment by marcomusy** [comment]
thanks for drawing my attention to it... it should be now fixed in the master:

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then
```python
import SimpleITK as sitk
from vedo import Volume, show

volume_path = 'data/all_vessel.nii'

print(" ----- SimpleITK")
label_img = sitk.ReadImage(volume_path)
raw_origin = label_img.GetOrigin()
print(label_img.GetOrigin())
print(label_img.GetSpacing())
print(label_img.GetSize())

print(" ----- vedo")
vol = Volume(volume_path)
vol.origin(raw_origin)
vol.print()

iso = vol.isosurface().print()
show(vol, iso, N=2, axes=1)
```
![Screenshot from 2023-02-03 15-22-47](https://user-images.githubusercontent.com/32848391/216628806-7a994b4a-bccb-4483-bfcc-f313ba91f561.png)

**Comment by zyy13579** [comment]
thanks a lot,great job!
