### ISSUE TITLE
mesh to volume failed

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#786]
I have a mesh, and I want to convert it to volume. The reference code is: `examples/volumetric/mesh2volume.py`.

My mesh is a vessel tree, and it looks like:

![image](https://user-images.githubusercontent.com/29271051/211249198-d7264af1-d413-4593-a168-1320b5fb62f9.png)

The original data is:

[vessel.zip](https://github.com/marcomusy/vedo/files/10373424/vessel.zip)

However, the converted volume is:

![image](https://user-images.githubusercontent.com/29271051/211253974-8016d1ab-4289-4b4a-b1fa-65cf8dadbb5c.png)

There is some incorrectly part.

The complete code to reproduce my problem is:

```
from vedo import Mesh, show, Volume
vessel = Mesh('vessel.obj').smooth().c('b').alpha(0.3)

vol = vessel.binarize(spacing=[0.01, 0.01, 0.01])
suf = Volume(vol).isosurface(255).c('b').alpha(0.3)
show(suf)
```

How can I correctly convert this mesh to volume? Any suggestion is appreciated~~~

**Comment by zhang-qiang-github** [comment]
I find it may be a `vtk` bug, and I have also post a issue for vtk.

**Comment by marcomusy** [comment]
Cleaning smoothing and capping seems to improve the result though:
```python
from vedo import Mesh, show, Volume
vessel = Mesh('data/vessel.obj').clean().smooth().cap()
vol = vessel.binarize(spacing=[0.01, 0.01, 0.01])
suf = Volume(vol).isosurface(255).c('blue5')
show(suf, axes=1)
```
![Screenshot from 2023-01-09 15-12-10](https://user-images.githubusercontent.com/32848391/211327830-7624bec1-1904-4f2a-825e-5f90a8fe184c.png)

**Comment by zhang-qiang-github** [comment]
Thanks for kindly reply.
