### ISSUE TITLE
How to get a slider plot showing a sequence of different meshes

### ISSUE THREAD

**Issue by TasminSarkany** [marcomusy/vedo#789]
I have a sequence of meshes for which I have vertices and faces and I would like to be able to make an interactive plot with a slider like the one here https://vedo.embl.es/fearless/#/1/1 where each value of the slider shows a different mesh on the same axes.

I have tried to make a slider plot using the `add_slider`  and `add_slider3d` functions but I'm having trouble because each mesh has separate vertices and faces and I can't work out how to change them for every value on the slider. Any help would be much appreciated!

**Comment by marcomusy** [comment]
The slider you quote in the link works on a web server only.
If you wish to create a local interactive application you can check out examples

`examples/basic/slider_browser.py`

with

```python
...
objs = load("mymesh_*.stl")  # load a list of meshes
...
```

you don't need to do anything about vertices or faces,
hope this helps!

**Comment by TasminSarkany** [comment]
That worked, thanks very much!
