### ISSUE TITLE
Having issues rendering anything with vedo

### ISSUE THREAD

**Issue by daniel-a-diaz** [marcomusy/vedo#792]
I had to do a clean install of my Ubuntu with WSL2 and Windows 11 and I have had issues in rendering things with vedo. It has worked fine in the past on the same computer. My new install didn't have libGL.so.1 installed so I did `apt-get install libgl1-mesa-glx libgl1-mesa-dri`. I have the same issue with PyVista rendering, but Matplotlib works fine. Do you have any ideas I could try to fix this issue? Or what information might be helpful? Thanks.

**Comment by marcomusy** [comment]
Hi, I'm i'm not mistaken the very latest Ubuntu doesn't use OpenGL as a default, which is the base of VTK, unfortunately I have (yet) no experience with that... did you manage to make it work after installing `libgl1` etc ?

**Comment by daniel-a-diaz** [comment]
It let me actually import vedo once I installed the `libgl1` but it still doesn't show anything. I did another install of Ubuntu 20.04.5 LTS, and while I didn't have any `libgl1` problems, it still doesn't show anything. I also tried completely uninstalling WSL and starting from scratch, but that still doesn't fix the issue.

**Comment by marcomusy** [comment]
Try this simple script:
```python
import vtk

cone = vtk.vtkConeSource()

mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(cone.GetOutputPort())

actor = vtk.vtkActor()
actor.SetMapper(mapper)

ren = vtk.vtkRenderer()
ren.SetBackground(0.1, 0.2, 0.4)
ren.AddActor(actor)

renWin = vtk.vtkRenderWindow()
renWin.SetSize(500, 500)
renWin.AddRenderer(ren)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

renWin.Render()
iren.Initialize()
iren.Start()
```

if it gives the same behavior i'm afraid it's general  vtk problem with the OS and/or the graphic card settings, I suggest to post an issue at https://discourse.vtk.org/

**Comment by daniel-a-diaz** [comment]
So updated my Intel graphics driver and now instead of showing nothing, the GUI window immediately closes after opening when I try anything from Visual Studio Code. When I run glxgears from the terminal it does the same thing, window closes immediately, and the output says "Segmentation fault". So I'm guessing something to do with my graphics driver or WSL.

Also previously, running things in jupyter notebook produced the same result as originally described in my first post. Now PyVista is rendering things fine, but when I try rendering with vedo, of the vtk script you suggested, I get the following.

```
[I 12:32:33.320 NotebookApp] KernelRestarter: restarting kernel (2/5), keep random ports
WARNING:root:kernel 38cfbcc2-7079-44c6-ae2a-5a0b7fdb60c8 restarted
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

Thanks for the link for vtk support.

**Comment by marcomusy** [comment]
Hi - it looks really like a fundamental problem with openGL rendering (i guess it can work in jupyter because opengl is not used in some cases depending on the backend you specify).

**Comment by daniel-a-diaz** [comment]
Finally coming back to this. It ended up being a driver issue that was fixed with an update from Intel. Thanks for the help in figuring this out.
