### ISSUE TITLE
make geojson support conditional

### ISSUE THREAD

**Issue by drew-parsons** [marcomusy/vedo#793]
vedo supports geojson files file VTK's vtkmodules.vtkIOGeoJSON.  But this VTK module is not built by default, and it's a fair bit of effort to find how to build it.

Can vedo make the geojson support conditional so that the vedo build doesn't break against standard VTK installations?

**Comment by marcomusy** [comment]
Ouch.. that was there by mistake, it's not even used, the import line in settings.py can be dropped.
