### ISSUE TITLE
Volumetric examples don't work - AttributeError: 'Volume' object has no attribute 'add_scalarbar3d'

### ISSUE THREAD

**Issue by lukablagoje** [marcomusy/vedo#795]
Hi,

I tried several examples with scalar bars and they don't work.

https://github.com/marcomusy/vedo/blob/master/examples/volumetric/numpy2volume1.py

This error appears: AttributeError: 'Volume' object has no attribute 'add_scalarbar3d'

Best,
Luka

**Comment by marcomusy** [comment]
That's weird! Have your tried
```
pip install vedo -U
```
and
```
vedo --info
```

**Comment by lukablagoje** [comment]
It worked! 

I've tried reinstalling initially, but it didn't work, so after a confirmed update, it's all good. 

Thanks!
