### ISSUE TITLE
Plot surface into variable with out showing result

### ISSUE THREAD

**Issue by haesleinhuepf** [marcomusy/vedo#802]
Hi @marcomusy ,

I'm trying to plot a surface mesh into a variable/pillow-image/mumpy-array that I can post-process. I saw `vedo.Plotter()` has two functions `.show()` and `.screenshot()`. When calling `show()` from a juypter notebook, the result is immediately shown. I was now wondering if it is possible to draw a plot of a surface without showing it and retrieving the plot in a numpy array or Pillow Image instead. 

Background: I would like to have the screenshot in a variable and build some stuff around before showing it, similar to [`stackview.insight()`](https://github.com/haesleinhuepf/stackview#static-insight-views) but with surfaces instead of images...

Any hint is welcome. Thanks!

Best,
Robert

**Comment by marcomusy** [comment]
Hi Robert,
Sure! Here goes an example script using `offscreen` and `asarray` keywords in `Plotter` class:
```python
from vedo import Plotter, Axes, Sphere

plt = Plotter(offscreen=True, size=(1000,1000))
sph = Sphere().lw(1)
axes = Axes(sph)
arr = plt.show(sph, axes).screenshot(asarray=True)
print("arr.shape", arr.shape)
plt.close()

# Read back test:
from vedo import Picture
Picture(arr).show(bg='black').close()
```
![Screenshot from 2023-02-04 14-41-19](https://user-images.githubusercontent.com/32848391/216770949-fe828649-b7cd-4a58-ae01-2c9f0752cef8.png)

Hope this helps.

**Comment by haesleinhuepf** [comment]
Amazing, thanks for the instant reply @marcomusy!

I had to add `N=2` to `Plotter(...)` to prevent this error popping up:
```
[vedo.io.py:1716] ERROR: in screenshot(), rendering window is not present, skip.
```

Otherwise, it works like a charm!

```
import numpy as np
import stackview

def do_show(image, mesh, zoom:float = np.exp(1), azimuth:float = 0, elevation:float = 0, roll:float = 0):
    from vedo import Plotter
    plt = Plotter(offscreen=True, size=[600,400], N=2)
    plt.show(mesh, zoom=np.log(zoom), azimuth=azimuth, elevation=elevation, roll=roll)
    return plt.screenshot(asarray=True)

stackview.interact(do_show, np.ones((10, 10)), mesh, continuous_update=True)
```


https://user-images.githubusercontent.com/12660498/216772377-2ab3c2bc-051b-4b34-ab7f-538a231fbb8e.mp4



Big thanks again!

**Comment by marcomusy** [comment]
Nice :)

> I had to add `N=2` to `Plotter(...)` to prevent this error popping up:

I need to fix that bug :)

**Comment by marcomusy** [comment]
Uhm what about this:

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

I added a new settings option, then you can do in jupyter:
```python
from vedo import Plotter, Axes, dataurl, Mesh, settings

settings.backend_autoclose = False   # do not close Plotter after show()

def showme(color):
    mesh.rotate_x(25).color(color)
    plt.show()

mesh = Mesh(dataurl+"bunny.obj").color("green")
plt = Plotter(size=[200,200], axes=1)
plt.show(mesh)
print("shape =", plt.screenshot(asarray=True).shape)

for i in range(3):
    showme(i)
```
![Screenshot from 2023-02-04 16-32-19](https://user-images.githubusercontent.com/32848391/216775895-a420a6d3-b978-49a4-a846-b0aeec8d84fe.png)

then you should be able to rewrite your original script as:
```python

import numpy as np
import stackview
from vedo import Plotter, settings

settings.backend_autoclose = False    # do not close Plotter after show()

def do_show(image, mesh, zoom:float = np.exp(1), azimuth:float = 0, elevation:float = 0, roll:float = 0):
    plt.show(mesh, zoom=np.log(zoom), azimuth=azimuth, elevation=elevation, roll=roll)
    # or plt.render() # which is faster
    return plt.screenshot(asarray=True)

plt = Plotter(size=[600,400])  # not inside do_show() anymore!
plt.show(mesh)

stackview.interact(do_show, np.ones((10, 10)), mesh, continuous_update=True)
```

hope this makes sense!
