### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'polydata'

### ISSUE THREAD

**Issue by Alirezaml78** [marcomusy/vedo#804]
Hi there,
I wrote a code in order to show the obj file from my own
the first time I was successful with another obj file, but unfortunately, the second time mentioned error has been driving me crazy
What can I do further?

the code is:

from vedo import Mesh

mesh = Mesh("3dobjtest.obj")

mesh.show()

Error:AttributeError: 'NoneType' object has no attribute 'polydata'

Powered by a cup of coffee

**Comment by marcomusy** [comment]
Uhm that is quite strange I see no resaon why it would not work, unless the file has some problems (?).

**Comment by Alirezaml78** [comment]
Thanks, Marco;

I have tried too many times and encountered this issue. I don't even understand why this is the case. Could you please test it? or would I have a chance to contact the VEDO TEAM to inform them about this error?

Bests

**Comment by Alirezaml78** [comment]
Dear Marco;

Thanks for your kindness, I'll contact you by email
sorry for that I was just stressed out :)

**Comment by Alirezaml78** [comment]
Dear Marco;

I totally don't understand what happened, but I was going to send you the project, out of the blue, It was solved. :| (MAGIC)
Anyway, I appreciate your swift replies and kind response

with bests

**Comment by marcomusy** [comment]
Happy to hear that! You might get that type of error message when the file you try to load is missing for some reason..
