### ISSUE TITLE
cut_with_point_loop not removing all cells

### ISSUE THREAD

**Issue by kman750** [marcomusy/vedo#805]
Hi Marco,

I'm using the `cut_with_point_loop` function to remove cells from a 2D mesh. The points for the loop are taken as the `.boundaries()` of another mesh. 

Some times it's very close:
![image](https://user-images.githubusercontent.com/73371848/217030466-fc85f64e-f89f-40dc-a1ad-8ed7249a4b52.png)

Others not so much:
![image](https://user-images.githubusercontent.com/73371848/217030671-5f8450c7-d2c6-493c-9c81-4b3394f1a348.png)

Do you have any feedback or suggestions what may be causing the issue?

Thanks!

**Comment by marcomusy** [comment]
Hi @kman750 you need to check that the vertex numbering is continuos , try with `boundary.labels2d("id")` to check that points form a line.
Can also try `.subdivide(method=1)` in the case of the square..
Not sure if it will do the job ...

**Comment by kman750** [comment]
This is the numbering I get for the purple loop:
![image](https://user-images.githubusercontent.com/73371848/217079505-5cd599a2-e282-4513-9df6-0811b287336c.png)

If I understand you correctly, the numbering of the points in the loop needs to be sequential (ex. 1, 2, 3, 4, 5, ...) around the loop for this method to work? If so, is there a function/tool you can recommend to renumber them?

Thanks for the quick rely! much appreciated!

**Comment by marcomusy** [comment]
try

`.join(reset=True)`

**Comment by kman750** [comment]
Oh! that definitely fixed the issue of leaving random cells within the point loop!
![image](https://user-images.githubusercontent.com/73371848/217084746-f184f67f-d511-4849-89c1-60d9eedbe9d3.png)

I do however notice that it's much more "aggressive" with removing cells which shouldn't have been. I also notice that by adding the `.join(reset=true)` 1 point is numbered twice? I'm not sure if this may be causing the aggressive removal of cells?

**Comment by marcomusy** [comment]
> I do however notice that it's much more "aggressive" 

LOL, yes :)
that shouldn't be happening obviously..  to sure why, what if you add `boundary.clean()`

**Comment by marcomusy** [comment]
...what about this
```python
from vedo import *
grid = Grid().wireframe(False)
square = Grid().scale(0.3).rotate_z(10).shift(.1,.2)
bb = square.boundaries().join(reset=True)
grid.cut_with_line(bb, invert=True)
show(grid, square, bb, axes=8)
```
<img width="365" alt="Screenshot 2023-02-06 at 23 05 35" src="https://user-images.githubusercontent.com/32848391/217098262-789ba61a-aa6f-4036-955f-92544ab6e56a.png">

**Comment by kman750** [comment]
Adding `.clean()` to the boundary fixed it!
![image](https://user-images.githubusercontent.com/73371848/217297064-a3de3ea0-9425-413a-b262-66e4a5a01b40.png)

It seems to work perfectly with rectangular shapes now! Triangular is a bit more of a hit or miss around the corners, but for my current use case I think that's acceptable.
![image](https://user-images.githubusercontent.com/73371848/217297924-3b1d682d-73ad-4d7d-ab05-03fe6d173d55.png)

Do you have a brief explanation of why `.join()` and `.clean()` seem to solve the issue? I'm wondering if I should be using them more frequently throughout my code.

Thanks so much for the help Marco!!

**Comment by kman750** [comment]
Hi Marco,

I had a question about a variation of this. If instead of removing the cells I'd like to assign them a specific `.celldata` value (ex. inside the loop `.celldata['x'] = 1`, and outside the loop `.celldata['x'] = 0`.) What would be the best method to do this?

I recall seeing an example similar to this, but can't seem to find it any more.

Thanks!

**Comment by marcomusy** [comment]
..first thing that comes up to my mind:
```python
from vedo import *
grid = Grid().wireframe(False)
square = Rectangle().extrude(0.5).scale(0.4).rotate_z(20).shift(0,0,-.1)
square.alpha(0.3)
centers = grid.cell_centers()
ids = square.inside_points(centers, return_ids=True)
arr = np.zeros(centers.shape[0]).astype(np.uint8)
arr[ids] = 1
grid.celldata["myflag"] = arr
grid.cmap("rainbow", "myflag", on='cells')
show(grid, square, axes=8)
```
![Screenshot from 2023-02-10 21-08-15](https://user-images.githubusercontent.com/32848391/218187918-a471a0e2-5f83-46e2-bffe-cf8553d29840.png)

i think this is not the only way to do it.... but i cannot remember what was the other...

**Comment by marcomusy** [comment]
Oh.. another one could be to add a cell id array at the beginning with `.add_ids()` and then cut..

**Comment by kman750** [comment]
Your first proposed method actually worked very well! Though it's exhibiting similar issues as I first showed, but less severe. 
![image](https://user-images.githubusercontent.com/73371848/218195990-c0419392-3fc6-4dc8-8133-2421f06b9163.png)
 
I'm guessing this may be another case of adding `.join(reset=True).clean()` ? What are your thoughts?

**Comment by marcomusy** [comment]
> I'm guessing this may be another case of adding `.join(reset=True).clean()` ? 

in this case that should be completely irrelevant (which might be an advantage..).
What join does is to join contiguous segments and optionally reset the vertex numbering to start from zero.

**Comment by kman750** [comment]
I see. What may you suggest as a solution to the blue cells which are touching the boundary but are not selected (i.e. yellow)?

**Comment by marcomusy** [comment]
if you want to include the boundary cells with this method you should apply `inside_points()` to all the vertices instead of cell centers, then for each cell check if the cells contains _at least_ one of the selected vertices you paint it yellow / delete it.

**Comment by kman750** [comment]
Since the previous cutting method worked perfectly once we added `.join()` and `.clean()`. My plan was to use it to isolate the cells, then get their ids and continue mid way with your idea using those ids. https://github.com/marcomusy/vedo/issues/805#issuecomment-1426292209. 

I thought using `.add_ids()` would return an array of ids which I could use, but this doesn't seem to be the case. How can I return an array of all the point or cell ids? Similar to what's occurring here `.inside_points(centers, return_ids=True)`

**Comment by marcomusy** [comment]
Anything that starts with `add_()` adds an array to the points or to the cells data. 
To check what is there you can print any object with eg.:
`mymesh.print()`
and/or access the data directly like in a dictionary:
`mymesh.pointdata["some_array_name"]`
or
`mymesh.pointdata[0]  # the first in the list`

You can also do 
`mymesh.pointdata.keys()`
remove, assign, select etc. Eg.
`mymesh.celldata["mynewarray"] = np.zeros(ncells) + 42`

You can also store metadata (numeric or string data not associated to anything), eg.
`mymesh.metadata["myinfo"] = "this mesh is fun"`

**Comment by 19kdc3** [comment]
Thanks for the detailed response!
