### ISSUE TITLE
Plotter cannot export html scene

### ISSUE THREAD

**Issue by fvallee-bnx** [marcomusy/vedo#808]
I  was using an older version of vedo and it was working fine, but with releases 2022.4.2 or release 2023.4.3 I can't export a scene in html anymore. 
Minified code (works fine using python 3.8, vedo 2022.3.0 + vtk 9.0.3 + k3d 2.15.2)

```
import vedo

if __name__ == "__main__":
  vedo.Plotter(interactive=False, offscreen=True).export(filename="scene.html", binary=False)
````

=> generates a scene.html (empty in that case, but it doesn't matter)

vtk is 9.0.3 is not supported by python3.11, I need to update to python3.11, vedo 2023.4.3 + vtk 9.2.5 + k3d 2.15.2

First Error is:

```
File "XXX/lib/python3.11/site-packages/vedo/io.py", line 1569, in export_window
TypeError: get_notebook_backend() takes from 0 to 1 positional arguments but 3 were given
```

get_notebook_backend has been changed in commit 946bfb3, where parameters have been removed but looks like io.py has not been updated

2nd error is 

`[vedo.backends.py:64] ERROR: Unknown jupyter backend: vtk
`

in io.py, export_window is setting  vedo.notebook_backend = "k3d" before calling get_notebook_backend but it's not working.

As a workaround, I've tried to set the default_backend instead and it's doing the trick:
```
  vedo.settings.default_backend = "k3d"
  plt = vedo.backends.get_notebook_backend(vedo.plotter_instance.actors)
```

**Comment by marcomusy** [comment]
Thanks for the detailed report, try
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then the example script `examples/other/export_x3d.py` is producing this output:
https://vedo.embl.es/test/embryo.html

Let me know if you problems in reproducing it.
(vedo 2023.4.3.dev13 | vtk 9.2.5 | numpy 1.21.6 | python 3.9)

**Comment by fvallee-bnx** [comment]
@marcomusy I don't reproduce the issue when generating embryo.x3d from examples/other/export_x3d.py, but I do reproduce the issue if I request ton export directly to html  (i.e. **plt.export('embryo.html', binary=False)** )

Issue is only in the ".html" part (k3d):
https://github.com/marcomusy/vedo/blob/40a08ccb5b1cb364e7ac040b0ba0b26097028447/vedo/io.py#L1575

Here is the workaround I'm using:
[k3d_patch.txt](https://github.com/marcomusy/vedo/files/10741519/k3d_patch.txt)

( I get "WARNING: Only k3d version 2.7.4 is currently supported" but seems it's working anyway)

**Comment by marcomusy** [comment]
Fixed in the master!
