### ISSUE TITLE
a document bug in Plotter

### ISSUE THREAD

**Issue by lyfs** [marcomusy/vedo#816]
![image](https://user-images.githubusercontent.com/11625259/220268296-0e516cb8-97f8-4f45-adc3-5d2304fa0521.png)
 Plotter.show have no shape attributes

**Comment by lyfs** [comment]
and here is another question:
![image](https://user-images.githubusercontent.com/11625259/220268960-0a5c744b-9a65-4cfa-8482-37ed70ef184f.png)
when i set 9 render in a plotter, and make sharecam is False
![image](https://user-images.githubusercontent.com/11625259/220269169-76f48e03-53ad-4feb-a51d-60088215d1fd.png)
then  i set plt.show(zoom="tight")
it's only works on the first renderer

**Comment by marcomusy** [comment]
Thanks for reporting the bug in the docs.

> and here is another question: when i set 9 render in a plotter, and make sharecam is False then i set plt.show(zoom="tight") it's only works on the first renderer

You may try to select a renderer number with:
```
plt = Plotter(interactive=False)
plt.at(7).show(...., zoom="tight")`
plt.at(3).show(...., zoom="tight")`
plt.interactive()
```

**Comment by lyfs** [comment]
thanks : )
