### ISSUE TITLE
Make drilled mesh using two boundary points..

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#817]
I try to make drilled mesh.
i find boundary points in two separate stl files.
![image](https://user-images.githubusercontent.com/73815944/220281142-9a69004d-14d2-447a-9dc2-a95ab097f794.png)

And i want to connect this separate stl files.
I used delaunay2d() and reconstruct_surface().

dealunay2d() is make like this.
![image](https://user-images.githubusercontent.com/73815944/220282494-2ecc3cf2-8014-4cac-95b8-4e159d1c03b2.png)
it was not drilled and That's not what I wanted.

reconstruct_surface() is make like this.
![image](https://user-images.githubusercontent.com/73815944/220283568-d8f84e44-3f8a-49c1-9b49-b7f9cf7f85d5.png)
It's made similar to what I want.
but it was over the boundary. and created holes..

i want uncovered cylinder shape using tow boundary points...
Any advice or new ideas?

**Comment by marcomusy** [comment]
This might be one of those problems which _look easy_ but infact can be hard..
Is there any known correspondence between the 2 boundaries?
If not are boundary points ordered or do they form a line?

**Comment by HyungJoo-Kwon** [comment]
it has not correspondence points.
i extract boundary points using boundaries() function.
this function not return unordered boundary points. Only return points.

how to change unordered boundary points to ordered boundary points.

**Comment by marcomusy** [comment]
You can use the function
```
mesh.boundaries().join(reset=True)
```
but you probably need to define some sort of correspondence of points.
You can visualize the point ids with
```
myids = boundary.labels2d("id")
show(...., myids)
```

**Comment by HyungJoo-Kwon** [comment]
Thanks !
If i have correspondence of points between 2 boundaries, how to make uncovered cylinder shape mesh that i want.. or how to connect separate mesh?

If i have two 3d splines that create ordered boundaries, how to make uncovered cylinder shape mesh that i want.. or how to connect separate mesh?

**Comment by marcomusy** [comment]
Hi have you tried `Ribbon()` class? See example https://github.com/marcomusy/vedo/tree/master/examples/advanced/contours2mesh.py

Alternatively you can use a registration method to bring one mesh border to match (exactly or not) the first one.
Check out 
`examples/basic/align*.py`
and/or
`examples/advanced/wapr*.py` (for non linear methods)

**Comment by HyungJoo-Kwon** [comment]
Thank you for your answer.

Ribbon() worked well. but i have small problem.
order of results of join(reset=True) function was the opposite.

result is 
![image](https://user-images.githubusercontent.com/73815944/221450180-5e8103a5-cd6d-4c1f-8336-7927b988dadb.png)
it's mean 
![image](https://user-images.githubusercontent.com/73815944/221450302-34928781-0433-48e1-82d1-029c2a561ef4.png)

How can i fixed it?

**Comment by marcomusy** [comment]
try adding `.reverse()`

**Comment by HyungJoo-Kwon** [comment]
one more thing!
After combining the three meshes, and i using fill_holes()
but not merDo I have to connect them all manually?
Is there a way to connect automatically?ged at boundary

**Comment by marcomusy** [comment]
try `newmesh = merge(m1,m2,m3).clean()`

**Comment by HyungJoo-Kwon** [comment]
Finally, i made uncovered cylinder shape mesh that i want.

using Ribbon(mode = 0) is made like this.
![image](https://user-images.githubusercontent.com/73815944/221798659-dc3fc8f8-a64e-4968-82b3-ada26f3e96fa.png)
It came out similar to the shape I wanted. In right image, create holes after merge.
I tried to fill the hole, but it was impossible because the boundary was created like the red line in the left image.
It seems that hole is generated by point sampling.

using Ribbon(mode = 1) is made like this.
![image](https://user-images.githubusercontent.com/73815944/221799946-744249ee-dac1-4113-a231-0f0984ddfbe3.png)
this case not create holes and boundary after merge. but mesh is unnatural than previous case.

Can I change Ribbon(mode=0) case to a full mesh with no holes and no boundary?
and is there a way to change the natural mesh?

Thank you always.!!

**Comment by marcomusy** [comment]
Hi @HyungJoo-Kwon i think the second image is not good because you can see self-intersecting triangles.. 
Is your mesh manifold? `.is_manifold()`
Have you tried `merge(ribbon, mesh).clean().non_manifold_faces(remove=True, tol=0).fill_holes(somevalue)` ?
If everything fails I would try with `pymeshfix` library, we have an example [here](https://github.com/marcomusy/vedo/blob/master/examples/other/remesh_meshfix.py).

**Comment by HyungJoo-Kwon** [comment]
Hi, I using vedo 2023.4.3
but occur AttributeError that Mesh object has no attribute 'is_manifold' and 'non_manifold_faces'

so i try pymeshfix library that you suggest
Result is like this image.
![image](https://user-images.githubusercontent.com/73815944/222319007-673765a4-27a7-4c81-940d-242577ad2a13.png)
Maybe, it seem not work.

Could you check what is problem, when you have time?
I will attach the data I use.

[check.zip](https://github.com/marcomusy/vedo/files/10867170/check.zip)

**Comment by HyungJoo-Kwon** [comment]
``
lower_data = vedo.load(lower_path)
upper_data = vedo.load(upper_path)
lower_boundary = lower_data.boundaries().join(reset=True) # crown
upper_boundary = upper_data .boundaries().join(reset=True) # root
``

**Comment by marcomusy** [comment]
I dont think you can achieve it by trying to connect 3D points which are so badly jagged:


![Screenshot from 2023-03-05 17-28-31](https://user-images.githubusercontent.com/32848391/222973063-4de1675d-6500-4202-8148-bf1d9af56252.png)

Smoothing can be an option in such a case:
```python
from vedo import *

lower_data = Mesh("/home/musy/downloads/check/lower_source.stl")
upper_data = Mesh("/home/musy/downloads/check/upper_source.stl")
lower_data.smooth(niter=20, boundary=True, edge_angle=130)
upper_data.smooth(niter=20, boundary=True, edge_angle=100)

lower_boundary = lower_data.boundaries().join(reset=True)
upper_boundary = upper_data.boundaries().join(reset=True)

# Change the boundary index order because upper boundary direction
# and lower boundary direction are different,
upper_boundary = Line(np.flipud(upper_boundary.points()))

ubp = upper_boundary.points()
lbp = lower_boundary.points()

first_idx = upper_boundary.closest_point(lbp[0], return_point_id=True)

# To match the starting point of the boundary.
upper_pts = np.concatenate((ubp[first_idx:], ubp[:first_idx]), axis=0)

connector = Ribbon(upper_pts, lower_boundary, mode=1, closed=True)

result = merge(lower_data, upper_data, connector).clean()
result.color("k5").backcolor("red5")

print(result.is_closed())
print(result.is_manifold())

show(result, result.boundaries())
```
![Screenshot from 2023-03-05 17-27-05](https://user-images.githubusercontent.com/32848391/222973092-3874a92f-09bf-4ecb-8721-9b65aec2de7b.png)

But the original 2 meshes will be (slightly) modified.

**Comment by HyungJoo-Kwon** [comment]
Thank you for all your assistance !
I really appreciate your help in resolving the problem. 👍
