### ISSUE TITLE
cutWithMesh return a weird result

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#824]
I am using `cutWithMesh` method, but the result is weird. 

![image](https://user-images.githubusercontent.com/29271051/222913288-6429a57c-9bd1-4fc3-9e7b-d66dfd70a7f0.png)

In the above figure, the left shows the original two polydata, and the right is the result. In the  right result, there are some weird holes. 

My code is:

```
from vedo import *

actor1 = Mesh('poly1.obj')
actor2 = Mesh('poly2.obj')

ret = actor1.clone().cutWithMesh(actor2)

show(actor1, actor2, at=0, N=2)
show(ret, at=1, interactive=True)
```

And the data is:
[data.zip](https://github.com/marcomusy/vedo/files/10888918/data.zip)

Is it a bug?

**Comment by marcomusy** [comment]
No, I think this is because the `poly2` mesh is not really closed, although `.cap()` seems to do the job..:
```python
from vedo import *

m1 = Mesh('poly1.obj').bc("red5")
m2 = Mesh('poly2.obj').bc("green7").cap()

ret = m1.clone().cut_with_mesh(m2)

show(m1, m2, m2.boundaries(), at=0, N=2)
show(ret, at=1, interactive=True)
```
<img width="264" alt="Screenshot 2023-03-04 at 19 12 27" src="https://user-images.githubusercontent.com/32848391/222922081-1cc17579-9830-456c-897d-3e51cbd9f33f.png">

**Comment by zhang-qiang-github** [comment]
Thanks for kindly reply. 

The `cap` method works for this data. However, it failed for other data:

[data2.zip](https://github.com/marcomusy/vedo/files/10890777/data2.zip)

The result is:

![image](https://user-images.githubusercontent.com/29271051/222941626-4d2a2dd0-9175-469d-bf00-b0e1f7c9f8b6.png)


And I find the `stl` file may work for `clip` method. For example:

```
from vedo import *
import vtkmodules.all as vtk
actor1 = Mesh('poly1.obj')
writer = vtk.vtkSTLWriter()
writer.SetInputData(actor1.polydata())
writer.SetFileName('poly1.stl')
writer.Write()
actor1 = Mesh('poly1.stl')


actor2 = Mesh('poly2.obj')
writer = vtk.vtkSTLWriter()
writer.SetInputData(actor2.polydata())
writer.SetFileName('poly2.stl')
writer.Write()
actor2 = Mesh('poly2.stl')

ret = actor1.clone().cutWithMesh(actor2)

show(actor1, actor2, at=0, N=2)
show(ret, at=1, interactive=True)
```
Firstly, I load the `obj` file, then save it to `stl`. Then, I load it to `Mesh`, and the `cutWithMesh` works. 

I don't know why `stl` work but `obj` do not work. It is weird.

**Comment by marcomusy** [comment]
For some reason the STL merges coincident points when saving.
Update your `vedo` version and try:
```python
from vedo import *

actor1 = Mesh('poly1.obj').c("white")
actor2 = Mesh('poly2.obj').c("white")
actor2.clean()  # merge coincident points

ret = actor1.clone().cut_with_mesh(actor2).bc('red5')

show(actor1, actor2, actor2.boundaries(), at=0, N=2)
show(ret, at=1, interactive=True)
```

the undesired result you get is correct because the cutting mesh is not closed on the long edge.

**Comment by zhang-qiang-github** [comment]
Thank you very much~~~
