### ISSUE TITLE
Create a mesh in the y-axis direction with partial mesh.

### ISSUE THREAD

**Issue by ack9437** [marcomusy/vedo#825]
Hi, I looked at the mesh generation method I wanted.
![image](https://user-images.githubusercontent.com/127063018/222998312-79e3ab7d-5b17-49b7-a885-d9cc50d08df0.png)

Can I use this library to make a part of the mesh full? Like the image above.
Or is it using AI?
Or Is there a way to create the mesh above?

I attach the sample file.
[sample.zip](https://github.com/marcomusy/vedo/files/10893568/sample.zip)

**Comment by zhang-qiang-github** [comment]
`vedo` provide a `cap` method. But, it is hard to generate the shown result.

**Comment by marcomusy** [comment]
I think you must have a "model" which informs how to complete/extend  the original object (there is no magic wand.. also AI would need input)

**Comment by ack9437** [comment]
Thanks. I'll check more.
