### ISSUE TITLE
'Mesh' object has no attribute 'generate_mesh'

### ISSUE THREAD

**Issue by zhang9song** [marcomusy/vedo#830]
Hi，guys

When I run example line2mesh_tri.py， I got a error 'Mesh' object has no attribute 'generate_mesh'.
Do I need to install some libary?
![image](https://user-images.githubusercontent.com/24886269/223900117-5e70a527-dd9f-4b39-86f0-8113e21e61ce.png)

**Comment by marcomusy** [comment]
Hi - yes - sorry the github examples work with the dev version only, to update do:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by zhang9song** [comment]
Thanks.
