### ISSUE TITLE
extract silhouette outline.

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#833]
I checked silhouette2.py
Can I get the 3d hollow outline of the silhouette?

Like the red line of the image below,
![image](https://user-images.githubusercontent.com/73815944/225225408-4d26d193-aa41-44e0-9a80-b825ce4bf158.png)

**Comment by marcomusy** [comment]
Uhm no, i'm afraid the only 2 options are these:
```python
from vedo import *

s = Hyperboloid().rotate_x(20).rotate_y(10)

sx = s.clone().project_on_plane('x').c('r').x(-3)
sy = s.clone().project_on_plane('y').c('g').y(3)

show(s,
     sx, sx.silhouette('2d'), # 2d objects dont need a direction
     sy, sy.silhouette('2d', border_edges=False),
     viewup='z', axes=1
).close()
```
![Screenshot from 2023-03-15 12-31-53](https://user-images.githubusercontent.com/32848391/225296849-06baf297-7796-4515-a324-66e48eda5578.png)

**Comment by HyungJoo-Kwon** [comment]
Thanks !
