### ISSUE TITLE
Is there an AxesHelper shape?

### ISSUE THREAD

**Issue by district10** [marcomusy/vedo#835]
![image](https://user-images.githubusercontent.com/5262037/226173114-1dd7799c-5d44-453e-9119-c89b8c7a1654.png)

Currently I'm using:

```python
def buildAxesHelper(pose: np.ndarray, *, scale: Union[float, Tuple[float, float, float]] = None):
    '''
    pose: 4x4 matrix, (pose@local_xyz.T).T -> global_xyz
        [ |  ,   | ,  |  ,  |     ]
        [xdir, ydir, zdir, center ]
        [ |  ,   | ,  |  ,  |     ]
        [ 0  ,   0 ,  0  ,  1     ]
    '''
    xdir = pose[:3, 0]
    ydir = pose[:3, 1]
    zdir = pose[:3, 2]
    center = pose[:3, 3]
    if scale is None:
        sx, sy, sz = 1.0, 1.0, 1.0
    elif isinstance(scale, (list, tuple)):
        sx, sy = scale[:2]
        sz = scale[2] if len(scale) > 2 else 1.0
    else:
        sx, sy, sz = scale, scale, scale
    ax = Arrow(center, center + sx*xdir, c='r')
    ay = Arrow(center, center + sy*ydir, c='g')
    az = Arrow(center, center + sz*zdir, c='b')
    return ax + ay + az
```

**Comment by marcomusy** [comment]
what you have looks ok to me :)
you may also create the Assembly of the 3 arrows and rotate it as a single object... if it's more convenient in your specific case.

**Comment by district10** [comment]
Okay. Thank you. Just make sure I'm not missing something. I'll assembly three axes. or even skip using Arrow & using 3 line segments.

Closing for now.

**Comment by district10** [comment]
Another version:

```python
def __AxesHelper():
    ax = Arrow([0, 0, 0], [1, 0, 0], c="r")
    ay = Arrow([0, 0, 0], [0, 1, 0], c="g")
    az = Arrow([0, 0, 0], [0, 0, 1], c="b")
    return ax + ay + az


def buildAxesHelper(
    pose: np.ndarray, *, scale: Union[float, Tuple[float, float, float]] = None
):
    """
    pose: 4x4 matrix, (pose@local_xyz.T).T -> global_xyz
        [ |  ,   | ,  |  ,  |     ]
        [xdir, ydir, zdir, center ]
        [ |  ,   | ,  |  ,  |     ]
        [ 0  ,   0 ,  0  ,  1     ]
    """
    if scale is not None:
        if isinstance(scale, (list, tuple)):
            sx, sy = scale[:2]
            sz = scale[2] if len(scale) > 2 else 1.0
        else:
            sx, sy, sz = scale, scale, scale
        pose = np.copy(pose)
        pose[:, 0] *= sx
        pose[:, 1] *= sy
        pose[:, 2] *= sz
    arr = __AxesHelper()
    arr.apply_transform(pose)
    return arr
```

`arr.apply_transform(pose)` may not be correct, applied to child actors? I'd like to setup `arr.transform` but failed...

**Comment by district10** [comment]
I have many camera/imu poses (4x4 matrix) and I'd like to draw some camera frames, IMU frames in vedo, something like <https://peterfalkingham.com/2017/04/04/photogrammetry-testing-8-colmap>. How cloud I setup transform? (tried to search `.transform = `, `set_transform` in this repo but no example found)

A close example is `vedo -r glyphs.py` (but I don't know how to integrate these 4x4 matrices)

I tried something like this:

```python
from scipy.spatial.transform import Rotation as R
qx, qy, qz, qw = R.from_matrix(pose[:3, :3]).as_quat()
tx, ty, tz = pose[:3, 3]
import vtk
T = vtk.vtkTransform()
T.Identity()
T.Translate(tx, ty, tz)
T.RotateWXYZ(qw, qx, qy, qz)
arr.transform = T
```

But not working.

I should read these docs I guess.

- https://www.programcreek.com/python/example/12960/vtk.vtkTransform
- https://vtk.org/doc/nightly/html/classvtkHomogeneousTransform.html

**Comment by marcomusy** [comment]
Have you tried something like `mymesh.apply_transform(T)` as in

https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.apply_transform

**Comment by district10** [comment]
> Have you tried something like `mymesh.apply_transform(T)` as in
> 
> https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.apply_transform

I saw this example and tested it in my "Another version". It works, visually.

But is this the right way to do it. I'd like to use one geometry and place it at many position+orientations, `apply_transform` sounds like would change `self.actors`' geometry. Because I tested these:

```
from vedo import Cube, show
c1 = Cube()
print('---------init')
print(c1.get_transform())
T = c1.get_transform(invert=True)
c1.rotate_z(5).x(2).y(1)
print('---------rot trans')
print(c1.get_transform())
T = c1.get_transform(invert=True)
c1.apply_transform(T)
print('------------ get back')
print(c1.get_transform())
```

![image](https://user-images.githubusercontent.com/5262037/226503522-779c796d-6ca5-4fc1-8e53-7808209dfdf6.png)

![image](https://user-images.githubusercontent.com/5262037/226503570-3f14e5e4-90fe-458b-8294-4892704f939c.png)

![image](https://user-images.githubusercontent.com/5262037/226503604-3206e39e-ca86-4a0e-9d08-3b367cff51b0.png)

**Comment by district10** [comment]
I think I should set transform to the Assembly, not to it's child actors.

**Comment by district10** [comment]
😅 My mistake. I should use `c2.apply_transform(T, concatenate=True)` here. It works as expected now:

```python
from vedo import Cube, show
c1 = Cube()
print('---------init')
print(c1.get_transform())
c1.rotate_z(5).x(2).y(1)
print('---------rot trans')
print(c1.get_transform())
T = c1.get_transform(invert=True)
c1.apply_transform(T, concatenate=True)
print('------------ get back')
print(c1.get_transform())
```

Doc: https://vedo.embl.es/docs/vedo/pointcloud.html#Points.apply_transform

**Comment by marcomusy** [comment]
cool, keep  in mind you can convert to numpy with
```
print(vtk2numpy(c1.get_transform()))
```

```
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```
