### ISSUE TITLE
.getCellArray('labels')

### ISSUE THREAD

**Issue by giuliarubiu** [marcomusy/vedo#838]
After the mesh loading when I try to use the attribute getGetArray('labels') it gives me the following error:
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_101534/645426849.py in <module>
----> 1 mesh.getCellArray("labels")

AttributeError: 'Mesh' object has no attribute 'getCellArray'

I want to know if this attribute was in some way deprecated or something

**Comment by marcomusy** [comment]
yes, please update your vedo version with
```bash
pip install vedo -U
```

then you can access any array like a dictionary:
```python
myarr = mesh.celldata["labels"]
```

**Comment by giuliarubiu** [comment]
Thank you! I have the same issue with: addCellArray(..), what should I use in this case?

**Comment by marcomusy** [comment]
exactly the same as for a dictionary
```
mesh.celldata["new_labels"] = myarr
```
