### ISSUE TITLE
A possible bug for split

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#841]
The code to use `splite`:

```
from vedo import dataurl, Volume, show, Mesh

em = Mesh('tofVessel.stl')
splitem = em.split(maxdepth=40)[0:9]

show(em, at=0, N=2)
show(splitem, at=1, interactive=True)
```

The test data is:
[tofVessel.zip](https://github.com/marcomusy/vedo/files/11068996/tofVessel.zip)

The result is:

![image](https://user-images.githubusercontent.com/29271051/227720056-832ff2d3-0762-4de7-b361-e343e2171776.png)

The `split` result miss lots of mesh. 

The version of `vedo` is `2023.4.4`.

**Comment by marcomusy** [comment]
It seems 40 is not enough. Consider one of 2 options:

```python
from vedo import *
em = Mesh('tofVessel.stl')
# splitem = em.split(maxdepth=150)
splitem = em.split(flag=True).cmap("Set1")
show(splitem)
```
<img width="294" alt="Screenshot 2023-03-25 at 16 28 56" src="https://user-images.githubusercontent.com/32848391/227726812-e0e0da59-5a4a-4431-8478-ef2670934d81.png">

**Comment by zhang-qiang-github** [comment]
So, the mesh return by `split` do not has the top `maxdepth` largest area. 

Thanks very much. And, I think it is better to give some explanation for this point.
