### ISSUE TITLE
Cropping mesh

### ISSUE THREAD

**Issue by fedeface98** [marcomusy/vedo#844]
Hi, 
I need to do some data augmentation by cropping meshes along specific planes. Is there a vedo's function to do this? 

Thank you so much in advance.

**Comment by marcomusy** [comment]
Sure! Check out:
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_plane
and
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_planes
