### ISSUE TITLE
Some questions about polyscope example

### ISSUE THREAD

**Issue by district10** [marcomusy/vedo#849]
There is a polyscope example: https://github.com/marcomusy/vedo/blob/master/examples/other/vpolyscope.py

`polyscope` is just accepting some data loaded by vedo? And `polyscope.show()` and `vedo.show` are two windows one after another.

Is there any example with vedo 3d + polyscope UI (it's IMGUI part are good), they should show in one window.

vedo + imgui (polyscope or [imgui_bundle](https://github.com/pthom/imgui_bundle)) will be so good for prototyping. 😅

**Comment by marcomusy** [comment]
Hi - the example is vary basic one - just to show how to visualize a vedo mesh in polyscope..
If you are looking into integration with GUI the only option is with Qt (you can find examples in `examples/other/qt*.py`).

Integration with imgui would be supercool but the upstream VTK is currently not supporting it afaik.
