### ISSUE TITLE
how to find intersection between the spline and a mesh

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#854]
i used intersect_with(), intersect_with_plane(), intersect_with_line().
but can't find intersection between the spline and mesh.

Is there a way to resolve this problem?

**Comment by marcomusy** [comment]
Hi, I think the best option is to go through the segments of the spline eg:
```python
from vedo import *

msh = ParametricShape("RandomHills").scale(2)

spline = Spline([[1,1,-1], [0,2,0], [1,3,3]]).lw(3)

pts = spline.points()
cpts = []
for i in range(spline.npoints-1):
    p = pts[i]
    q = pts[i+1]
    ipts = msh.intersect_with_line(p, q)
    if len(ipts):
        cpts.append(ipts[0])

cpts = Points(cpts, r=12)

show(msh, spline, cpts, axes=1, viewup="z")
```
<img width="376" alt="Screenshot 2023-04-25 at 22 18 38" src="https://user-images.githubusercontent.com/32848391/234395010-f93633e4-1b34-45bd-b5ab-87783f2b495d.png">

**Comment by HyungJoo-Kwon** [comment]
Thanks for kindly reply. !!
