### ISSUE TITLE
Question: Slicer3DPlotter Example with aspect ratio scaling

### ISSUE THREAD

**Issue by ivankqw** [marcomusy/vedo#855]
Hi, 

I'd like to use Slicer3DPlotter on a Volume. My volume was created with DICOM files. 

I need to scale the xy, yz, and zx axes respectively based on the aspect ratio of these planes. The plot currently looks slightly off due to the aspect ratios not being correct.

Here's what I tried: 
- I tried to instantiate a Volume with custom dimensions as such:
`vol = Volume(img3d, dims=(int(pixel_spacing[0]/slice_thickness), int(pixel_spacing[1]/slice_thickness), 1))`

And got this error:
`UNSUPPORTED (log once): POSSIBLE ISSUE: unit 2 GLD_TEXTURE_INDEX_3D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
2023-04-26 17:00:42.347 python[14922:11117832] GLDRendererMetal command buffer completion error: Error Domain=MTLCommandBufferErrorDomain Code=1 "Discarded (victim of GPU error[/recovery](https://file+.vscode-resource.vscode-cdn.net/recovery)) (00000005:kIOGPUCommandBufferCallbackErrorInnocentVictim)" UserInfo={NSLocalizedDescription=Discarded (victim of GPU error[/recovery](https://file+.vscode-resource.vscode-cdn.net/recovery)) (00000005:kIOGPUCommandBufferCallbackErrorInnocentVictim)}`

- I tried to use Volume.scale to scale the respective axes. Scaling calculated as such:
`scaling = (pixel_spacing[0] * axial_aspect, pixel_spacing[1] * sagittal_aspect, slice_thickness * coronal_aspect)`
`vol.scale(scaling, reset=True)`

The output plot still remains the same.

Thanks for the help!

**Comment by marcomusy** [comment]
`CallbackErrorInnocentVictim`? :)
that's quite weird... I don't recognise it or understand what it means..
Have you tried your script with a test volume like [this](https://vedo.embl.es/examples/data/embryo.slc)?
Normally you set physical dimensions by specifying the `spacing` (size of voxel):
```
Volume(..., spacing=[..., ..., ...])
```

Also i'm surprised that one of the dimensions is 1.  that means it a simple image?

**Comment by ivankqw** [comment]
Yes, I think I made a mistake somewhere there.

Specifying the size of voxel via `spacing` worked for me. Thank you!
