### ISSUE TITLE
Cutting a textured Mesh creates artifacts

### ISSUE THREAD

**Issue by marcomusy** [marcomusy/vedo#856]
Naively cutting a texture mesh reassigns vertices IDs because a clean cut of a Mesh need the creation of new points.
Hence non-contigous regions of the uv-mapping need interpolation which leads to annoying "seams" in the final result:

```
pip install -U git+https://github.com/marcomusy/vedo.git
```

Then

```py
from vedo import *


def func(widget, e):
    x = widget.value
    m = msh.clone().cut_with_plane(origin=[x, 0, 0])
    m.texture(msh.GetTexture())
    plt.remove("frog").add(m).render()


msh = Mesh("frog.obj").texture("frog.jpg")
msh.name = "frog"

plt = Plotter(axes=1)
plt.add_slider(func, xmin=-3, xmax=3, value=-3)
plt.show(msh.clone())
plt.close()
```

![Screenshot from 2023-04-26 23-55-04](https://user-images.githubusercontent.com/32848391/234712378-3e54ec57-7224-45db-8622-682a3d1439a4.png)

Second option is to convert the texture to a RGBA direct coloring of the mesh vertices:
```py
from vedo import *


def func(widget, e):
    x = widget.value
    m = msh.clone().cut_with_plane(origin=[x,0,0])
    m.pointdata.select("PointsRGBA")
    plt.remove("frog").add(m).render()


msh = Mesh("frog.obj")
pic = Picture("frog.jpg")
msh.name = "frog"

# convert texture to RGBA direct colors
uvpts = msh.pointdata['Frog'] * pic.shape
uvpts = Points(uvpts).interpolate_data_from(pic.tomesh(), n=1)
msh.pointcolors = uvpts.pointdata["RGBA"]

# show(pic, msh, msh.clone().texture("frog.jpg"), N=3, sharecam=0).close()

plt = Plotter(axes=1)
plt.add_slider(func, xmin=-6, xmax=3, value=-6)
plt.show(msh)
plt.close()
```

but the price to pay is that the interpolation can be much less precise (low-res) than the original texture image:

![Screenshot from 2023-04-26 23-54-03](https://user-images.githubusercontent.com/32848391/234712637-ad6e69be-c9c3-40c7-aad6-333b6ec0c872.png)

Third option is to cut off the whole cells without modifying the vertices at all:
```py
from vedo import *


def func(widget, e):
    x = widget.value
    m = msh.clone()
    ids = m.find_cells_in(xbounds=(-10,x))
    m.delete_cells(ids)
    plt.remove("frog").add(m).render()


msh = Mesh("frog.obj").texture("frog.jpg")
msh.name = "frog"

plt = Plotter(axes=1)
plt.add_slider(func, xmin=-6, xmax=3, value=-6)
plt.show(msh)
plt.close()
```

Here the price to pay is that the cut is "crinckled", ie. not smooth.

![Screenshot from 2023-04-26 23-55-30](https://user-images.githubusercontent.com/32848391/234713313-0e1a9dd3-839b-4103-b409-ca1be3d08331.png)

[frog.zip](https://github.com/marcomusy/vedo/files/11337666/frog.zip)

References: 
https://forum.image.sc/t/cropped-mesh-shows-up-strange/80431
https://discourse.vtk.org/t/unwanted-interpolation-in-vtktexture/5556

**Comment by ttsesm** [comment]
@marcomusy I am actually having the same issue in my case.

My question is there an direct way to get all the points (point ids) bellow (or above) a cut plane. 
Currently, to delete all the faces bellow the cut plane I was using the center of the cut plane and I was selecting them by setting the threshold as anything bellow that point but if the cut plane is not flat and there is an angle this doesn't work properly since the points that are above the cut plane but still lower than the center point of the cut plane will deleted.

**Comment by marcomusy** [comment]
Hi if it's along one of the cartesian axes you can work that out in numpy? Eg:
```py
from vedo import *

s = Sphere()

pts = s.points
mask = pts[:, 2] > 0.5
ids = np.linspace(0, len(pts) - 1, len(pts), dtype=int)[mask]
print(ids)
```

**Comment by marcomusy** [comment]
Try this:
```py
from vedo import *

plane_point = np.array([0, 0, 0.1])  # point on the plane
normal = np.array([0, 0.7, 1])  

s = Cube().clean().lighting("off").c("blue5", 0.8).lw(1)
plane = Plane(normal=normal).scale(2)
plane.pos(plane_point)

normal = normal / np.linalg.norm(normal)
vectors = s.points - plane_point
dot_products = np.dot(vectors, normal)
indices = np.where(dot_products > 0)[0]
print(f"Indices of points above the plane: {indices}")

show(
    s,
    s.labels2d("id"),
    plane,
    axes=1,
    viewup="z",
)
```

![Image](https://github.com/user-attachments/assets/bf9db554-503c-48b9-bde0-57b9ca4feb62)

**Comment by ttsesm** [comment]
Thanks @marcomusy, this did the trick.
