### ISSUE TITLE
Fill in empty space in open mesh

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#858]
![image](https://user-images.githubusercontent.com/73815944/237020363-fba07136-ff66-4787-8415-8b23208da87a.png)
Hi, I have open mesh and want to fill some space.
So, I try to create points about empty space. And using reconstruct_surface() to create a mesh filled whit empty space.

I want to get points for empty space through plane slicing (intersect_with_plane()) and create spline.

The result is similar to the image below.
![image](https://user-images.githubusercontent.com/73815944/237020196-919d403f-6fe8-4aef-a767-dc1be08457a8.png)
The line was recognized individually and there was no order for the direction, making it impossible to fill the empty space through the splines.

![image](https://user-images.githubusercontent.com/73815944/237018043-26922bea-222a-420c-8cb2-7222c929a2a9.png)
Can we order multiple lines made through intercept_with_plane() ? Like the image above

Or Is there any other way to fill in the empty space?

**Comment by marcomusy** [comment]
Hi , hi think this is really a hard problem.. 
1. you may try to pick a few points of these outlines, re-order them manually in phi angle and then draw a close spline through them with high resolution, finally you use `reconstruct_surface` as you said.
2. create a binary volume of the inside/outside of surface and then isosurface this same volume.

Example:
```py
from vedo import *

# create a test surface
h1 = Paraboloid(pos=(0,0,.10), height=2, c='red').scale([2,1,1])
h2 = Paraboloid(pos=(0,0,0), height=3, c='green')
h1.cut_with_mesh(h2).smooth()

planei = h1.intersect_with_plane(origin=(0,0,-0.5), normal=[0,0,1])
show(h1, planei, axes=1, viewup='z')

vol = h1.compute_normals().binarize(invert=1,spacing=[0.005,.005,.005])
iso = vol.isosurface().c('gold').alpha(0.5)
show(iso, axes=1, viewup='z').close()
```
![Screenshot from 2023-05-09 16-54-19](https://github.com/marcomusy/vedo/assets/32848391/b5fe92b5-fc3a-4181-bfdc-b48ff59f9bb7)

**Comment by HyungJoo-Kwon** [comment]
Thank you for your kind answer.

I have one more question.

During the test, there was a difference in size between original mesh and reconstruct_surface() mesh that using original point.
reconstruct_surface() is slightly bigger than original mesh..

Is there a detailed way to reduce this difference as much as possible?
 ( ex - upsampling and adjust parameter of reconsturct_suface() )

**Comment by marcomusy** [comment]
You may consider scaling it around a suitable point, or warp it:
you `subsample()` the reconstructed mesh to reduce it to a few points (~50) then find the closest points from these points to the original surface and then warp the mesh with `warp()`

**Comment by HyungJoo-Kwon** [comment]
Thank you for your answer. I'll test it.
