### ISSUE TITLE
smooth shading

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#859]
how to set smooth shading?

**Comment by marcomusy** [comment]
try `.phong()`

**Comment by LogWell** [comment]
```
from vedo import load
m = load("SMPL_A.obj")
m.phong()
m.show()
```

![image](https://github.com/marcomusy/vedo/assets/34391447/1380e751-04d9-442b-822b-0bcb28c5952f)


Still does not work.
Besides, I found that
```
k: cycle available lighting styles
K: cycle available shading styles (no action)
```

**Comment by marcomusy** [comment]
Phong shading need the normals to be present. Try:
```py
m = Mesh("SMPL_A.obj").compute_normals().phong()
m.show()
```

**Comment by LogWell** [comment]
[SMPL_A0.txt](https://github.com/marcomusy/vedo/files/11471281/SMPL_A0.txt)
[SMPL_A1.txt](https://github.com/marcomusy/vedo/files/11471282/SMPL_A1.txt)

A0: only `v` and `f`
A1: include `vt`

`.compute_ normals(). phone()` is not applicable for "A1".
