### ISSUE TITLE
Unwanted part is selected when cut_with_point_loop()

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#861]
1.
![image](https://github.com/marcomusy/vedo/assets/73815944/2728e8d4-dbae-4814-9d87-24cd57bb478c)
I try to use the boundaries of a particular mesh to cut another mesh.
I used closest_point(), geodesic(), spline(smooth=1, degree=5), and change parameter of method .. 
But unwanted part is selected and cutted.

Like this
![image](https://github.com/marcomusy/vedo/assets/73815944/f753b59b-7217-498f-9a4e-596d747d69c2)

I think there was a problem because angular splines were created when creating splines
I think I need to modify it from an angled boundary to a soft boundary, but I don't know how.

Is this the right cause?
Please give me some advice to solve this problem.

2. Can I know the cellid (in original mesh) selected through the point loop?
    I think it's vtkselectdata(), but vtk is too hard to use. 😂😢

**Comment by HyungJoo-Kwon** [comment]
Can I know the index of the cell set to cut_with_point_loop()?

**Comment by marcomusy** [comment]
Hi, i'm not sure about your question but you can always get the cellid of the closest point with `closest_point(..., return_cell_id=True)`
Hope this helps!

**Comment by HyungJoo-Kwon** [comment]
I was mistaken. I solved it Thank you.

**Comment by HyungJoo-Kwon** [comment]
My question example is
red part : original_mesh, ncells = 10000
blue part : cutted_mesh,  ncells = 100

I wanted Index in source cell about cutted mesh..
Cell corresponding to the cutted mesh in the source cell

I checked cell_center value. Like this.. 
```
intersect_idx = []
original_cell = original_mesh.cell_centers()
cutted_cell = cutted_mesh.cell_centers()
for i in range(cutted_cell.shape[0]):
    idx = np.where((original_cell ==cutted_cell[i]).all(axis=-1))[0][0]
    intersect_idx.apped(idx)
```

But If the number of mesh cells increases, it takes too long.
if there's a way to extract this index quickly ?

**Comment by marcomusy** [comment]
You can create an extra array with the original values and then cut the object. The original values should be preserved in the cut region:

```py
from vedo import *

settings.use_depth_peeling = True

s = Sphere().lw(1).compute_normals()
s.celldata["cellsource_id"] = list(range(s.ncells))

# pick a few points on the sphere
sc = s.points()
pts = Points([sc[10], sc[15], sc[129], sc[165]], r=12)

#cut loop region identified by the points
scut = s.clone().cut_with_point_loop(pts, invert=False)
scut.c('blue', 0.5).scale(1.02)

# add labels
labs_0 = s.labels("cellid")
labs_1 = scut.labels("cellsource_id", on='cells')

show(s, pts, scut, labs_0, labs_1, axes=1)
```
![Screenshot from 2023-05-18 11-40-49](https://github.com/marcomusy/vedo/assets/32848391/3cae709c-2cbb-4830-b6d3-2bbb48a0bc62)

and can be accessed with `s.celldata["cellsource_id"]`

**Comment by HyungJoo-Kwon** [comment]
ah.. i realize..
Really thanks !
