### ISSUE TITLE
I wonder about plt.show()

### ISSUE THREAD

**Issue by jamja11** [marcomusy/vedo#863]
Hello, Thank you for your effort. 
I'm so curious about plt.show() 
```py
plt = vedo.Plotter()
plt.add(vedo.load(vedo.dataurl+'shark.ply').c('cyan'))
plt.show(viewup=[0,100,-1])
plt.look_at(plane='xy').show()
plt.show(viewup=[0,100,-1])  # no change
```

Why are the second and last results the same? 

I ran the first line and rotated it. And in the second line, it was rotated again based on the xy plane. finally, I expected the same result as the first line, but it was not. Why?

I want to use show(view up=[0, 100, -1]) multiple times not only once.

**Comment by marcomusy** [comment]
Hi thanks for reporting, originally this was an intended behavior but I understand it's counterintuitive so I going to flag it as bug and see if I can rethink the API.. 
In principle you should call `show()` only once and then call `render()` in either loops or callback functions to update the scene, eg:
```py
import vedo
plt = vedo.Plotter()

plt.add(vedo.load(vedo.dataurl+'shark.ply'))
plt.show(viewup=[0,100,-1], axes=1)

plt.look_at(plane='xy').render()
plt.interactive()

plt.look_at(plane='xz').render()
plt.interactive()
```

**Comment by megajh96** [comment]
Is there a way to rotate an axis other than viewup?

**Comment by megajh96** [comment]
Thank you for your prompt reply. 
I solved it another way.

plt.look_at(plane='xy').show() # anterior
plt.look_at(plane='zy').show(roll=90) # left
plt.look_at(plane='xz').show(axes=1, roll=-90, azimuth=-90) # right
