### ISSUE TITLE
Is there any method to expand a mesh?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#868]
`Mesh.shrink` can shrink a mesh. Is there any method to expand a mesh?

**Comment by marcomusy** [comment]
the `shrink()` method shrinks the individual polygonal faces of the mesh.
You ca make a mesh bigger or smaller with `.scale()` or "expand" it by manually moving the vertices along the normals (for convex shapes), using (`mesh.points(new_points_array)`).

**Comment by zhang-qiang-github** [comment]
@marcomusy Thanks for kindly reply.

But, what I want is different from the `scale` . Please have a look for the following picture:

![image](https://github.com/marcomusy/vedo/assets/29271051/77c2d0be-7835-429f-8483-e44ccea2a993)

Let's say the black object is the current object, and the red (left) is the result of `scale`, the green (right) is the result of `expand`. 

The `expand` is not only a matter of moving the vertices along the normal, and it should also need to merge some points to one point which means it would change the topology. 

What I expected is similar to the dilate operation for a mask:

![image](https://github.com/marcomusy/vedo/assets/29271051/c4387b5f-6d0f-481c-837d-c37d796e8793)

Is there any method in `vedo` to implement it? Thanks very much in advance.

**Comment by marcomusy** [comment]
Hi, yes you can `binarize(0` the surface (fill the volume with a constant value) and then `dilate()` and optionally `erode()` the volume, finally isosurfacing the result:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

then

```py
from vedo import *
iso = Volume(dataurl+'embryo.tif').isosurface()
vol = iso.binarize(spacing=(100, 100, 100)).pad(10) # add 10 voxels of padding to allow expansion
vol.dilate([15,15,15])#.erode([10,10,10])
show(iso, vol.isosurface(), N=2, axes=1)
```
![Screenshot from 2023-05-25 20-18-21](https://github.com/marcomusy/vedo/assets/32848391/9a242e04-619d-42bd-87b7-af57b6ad7ba6)

**Comment by marcomusy** [comment]
.. I just realised that you dont really need to binarize.. this already does the job:
```py
from vedo import *
vol = Volume(dataurl+'embryo.tif').pad(10)
vol2 = vol.clone().dilate([15,15,15])#.erode([10,10,10])
show(vol.isosurface(), vol2.isosurface(), N=2, axes=1)
```

**Comment by zhang-qiang-github** [comment]
> .. I just realised that you dont really need to binarize.. this already does the job:
> 
> ```python
> from vedo import *
> vol = Volume(dataurl+'embryo.tif').pad(10)
> vol2 = vol.clone().dilate([15,15,15])#.erode([10,10,10])
> show(vol.isosurface(), vol2.isosurface(), N=2, axes=1)
> ```

The `dilate` effect is what I want. But, I want to use `Mesh` rather than `Volume` as the input. Is it possible?

**Comment by marcomusy** [comment]
> @marcomusy The effect of `dilate` is what I want. But, I want to use `Mesh` rather than `Volume` as the input. I want to directly `expand` the `Mesh`. Is it possible?

No, it cannot be possible in general.
But - if you want to maintain the original Mesh structure - you can still  `binarize()` the input mesh, expand it "a bit" then find the closest points of the first mesh onto the second and update its vertices, iteratively.
Keep in mind this will only work for relatively small deformations.

**Comment by zhang-qiang-github** [comment]
> if you want to maintain the original Mesh structure 

Actually, I don't want to maintain the structure. I hope the structure should be changed if the mesh is `expand`.  Is there any method in `vedo`?

**Comment by marcomusy** [comment]
But then  the example above already does it! Use:
```py
expanded_mesh = mymesh.binarize().dilate().isosurface()
```
