### ISSUE TITLE
Plotter screenshot scale has no effect

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#869]
Hi Marco, 

I was installing newest version (`'2023.4.4'`) of vedo through pip and noticed that my rendered images degraded in quality.
I found that the `scale` parameter in `screenshot` function of plotter has no effect if `asarray=True`, ie if i get the following output
```
>> plt.screenshot(asarray=True, scale=2).shape
(1920, 1920, 3)
>> plt.screenshot(asarray=True, scale=5).shape
(1920, 1920, 3)
```
When `asarray=False` in the function call and i specify a filename the scale parameter works just fine 👍 

I downgraded vedo to version `'2023.4.3'` and there everything related to this bug works fine.

**Comment by marcomusy** [comment]
Hi Paul, thanks for reporting this, it was done for speed but I put it back for the case when one wants a scale >1, so I hope this now works with the master version:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```
