### ISSUE TITLE
How to make arrows scalar bar follow provided input arrays used in cmap

### ISSUE THREAD

**Issue by XushanLu** [marcomusy/vedo#871]
Hi Marco,

I am trying to plot some vectors to represent the electric field. For the color map, I want to use an array that stores the amplitude of the electric field. For the orientation, I just provided the starting and ending point based on the actual orientation of the electric field. 

However, I am seeing two problems with the code (data provided in the zip file): 
[test.zip](https://github.com/marcomusy/vedo/files/11578473/test.zip)

- Problem 1: `[vedo.pointcloud.py:2836] ERROR: in cmap(), nr. of input points scalars 500 != 30500 ...skip coloring.` This seems to be suggesting that the number of points (in my case should be equal to the number of arrows) is different from the number of points obtained from an inquiry function from VTK. This is strange but probably not critical. 
- Problems 2: I cannot use the `input_array` to show the colors for my color bar when using the function `add_scalarbar3d`. I think the color in the picture may be correct but the values in the color bar are just nonsense. I am expecting something close to 1e-6 rather than a few hundred.

![electric_field](https://github.com/marcomusy/vedo/assets/7824380/5fee9d39-12db-4ea5-86c6-5f30080eb58b)

**Comment by XushanLu** [comment]
I just realized the colors shown on these arrows are also wrong but they are consistent with the scalar bar: they are showing the indices of the arrows (from 1 to 500).

**Comment by marcomusy** [comment]
Hi Xushan
please check if this gives you a correct visualization:
(need to install the master version)

```py
#!/usr/bin/env python3
#
from vedo import *

settings.default_font = 'Theemim'
settings.multi_samples=8

filename = 'obs_xyz.dat'
xyz = np.loadtxt(filename, dtype=np.float64)
xyz = xyz[1:, :] - np.array([0, 20, 0])
n_obs, n_col = xyz.shape

# Read the coordinates of all receiver
x = xyz[:, 0]
x = np.ascontiguousarray(x)
y = xyz[:, 1]
y = np.ascontiguousarray(y)
z = xyz[:, 2]
z = np.ascontiguousarray(z)

# Read in the data
num_field = np.loadtxt('tmp_field.txt', dtype=np.float64)
numx = num_field[:, 0]
numy = num_field[:, 1]
numz = num_field[:, 2]

vec_x = np.ascontiguousarray(numx[:])
vec_y = np.ascontiguousarray(numy[:])
vec_z = np.ascontiguousarray(numz[:])
amp = np.zeros(n_obs, dtype=np.float64)
for iobs in range(n_obs):
    tmp = num_field[iobs, :]
    amp[iobs] = np.sqrt(tmp.dot(tmp))

amp = np.ascontiguousarray(amp)
vec = (vec_x, vec_y, vec_z)

# Plot the current density using vedo
points = Points(xyz)
vec_vedo = np.c_[vec_x / amp, vec_y / amp, vec_z / amp]
# Create a colormap using matplotlib with "coolwarm" based on log(amp)

# Assuming that you have already calculated the value of log(amp) and stored it in a variable called log_amp
# You can create a colormap using matplotlib with "coolwarm" based on log(amp) as follows:

# Define the minimum and maximum values of log(amp)
amp_min = np.min(amp)
amp_max = np.max(amp)

# We need to create a few slices from the original arrays
# First create a mask array to mark all receiver points with x = -10, 0, 10
x_mark = [-19.5, -9.236842110, 1.026315790, 11.289473680, 19.5]
y_mark = [-4.5, 4.5]
mask = np.zeros(n_obs, dtype=bool)

# We need to create a mask array to mark all receiver points with x being
# any of x_mark and y being any of y_marko
for x_m in x_mark:
    mask_local = np.abs(x - x_m) < 1e-6
    mask = np.logical_or(mask, mask_local)

# Create an Arrows object for all the receivers where mask is True
start = xyz[mask, :]
end = start + vec_vedo[mask, :] * 2

print(mag(end-start).min(), mag(end-start).max())
vrange = (amp.min()*1e06, amp.max()*1e06)
print(vrange)

marker = Arrow([0,0,0], [2,0,0])
arrows = Glyph(
    start, 
    marker,
    c="viridis",
    orientation_array=end-start,
    color_by_vector_size=True,
)

pos = (-5, -11, -30)
scalarbar = ScalarBar(
    vrange,
    title='E (V/m)',
    c="viridis",
    # title_rotation=180,
    # title_size=2, 
    # title_xoffset=-3,
    # label_rotation=-90,
    # label_offset=1,
    # label_size=2,
    # pos=pos,
    # s=(1, 20),
    # nlabels=5,
    size=(100,1000),
)

# scalarbar.rotate_z(90, around=pos)

size = (3920, 2160)
plt = Plotter()

axes = Axes(
    arrows, 
    xtitle='Easting (m)',
    ytitle='Northing (m)',
    ztitle='Elevation (m)',
    xtitle_position=0.55,
    xlabel_size=0.018,
    xtitle_offset=0.05,
    ytitle_position=0.69,
    ylabel_rotation=-90,
    ylabel_size=0.018,
    ytitle_rotation=180,
    y_values_and_labels=[(-5, "-5"), (0, "0"), (5, "5")],
    axes_linewidth=4,
    xrange=arrows.xbounds(),
    yrange=arrows.ybounds(),
    zxgrid2=True,
    zshift_along_y=1,
    zaxis_rotation=-70,
    ztitle_size=0.02,
    xyframe_line=True,
    grid_linewidth=2,
)
cam = dict(
    position=(-58.8911, -54.5234, 8.63461),
    focal_point=(-5.25549, -0.0457020, -23.8989),
    viewup=(0.248841, 0.304150, 0.919549),
    distance=83.0844,
    clipping_range=(34.8493, 143.093),
)
fig_name = 'electric_field.png'
plt.show(arrows, axes, scalarbar, interactive=1)
screenshot(fig_name)
plt.close()
```

**Comment by XushanLu** [comment]
Hi Marco,

Thanks very much for your prompt response. Unfortunately, I think the arrows were still colored by the arrow indices rather than the actual electric-field value. 

I have cleaned up the code a little bit:

```python
from vedo import settings, Plotter, Points, Arrow, Glyph, screenshot, \
    ScalarBar3D, Axes, mag, ScalarBar
import numpy as np

settings.default_font = 'Theemim'
settings.multi_samples=8

filename = 'obs_xyz.dat'
xyz = np.loadtxt(filename, dtype=np.float64)
xyz = xyz[1:, :] - np.array([0, 20, 0])
n_obs, n_col = xyz.shape

# Read in the data
num_field = np.loadtxt('tmp_field.txt', dtype=np.float64)
amp = mag(num_field)

field = np.c_[xyz, num_field, amp]
np.savetxt('tmp_field_amp.txt', field, fmt='%18.8e', delimiter=' ')

# Plot the current density using vedo
points = Points(xyz)

# We need to create a few slices from the original arrays
# First create a mask array to mark all receiver points with x = -10, 0, 10
x_mark = [-19.5, -9.236842110, 1.026315790, 11.289473680, 19.5]
y_mark = [-4.5, 4.5]
mask = np.zeros(n_obs, dtype=bool)

# We need to create a mask array to mark all receiver points with x being
# any of x_mark and y being any of y_marko
for x_m in x_mark:
    mask_local = np.abs(xyz[:, 0] - x_m) < 1e-6
    mask = np.logical_or(mask, mask_local)

# Create an Arrows object for all the receivers where mask is True
start = xyz[mask, :]
# orientation = vec_vedo[mask, :]
orientation = num_field[mask, :]
amp_mask = amp[mask]

vrange = (amp_mask.min(), amp_mask.max())

marker = Arrow([0,0,0], [2,0,0])
arrows = Glyph(
    start, 
    marker,
    c="jet",
    orientation_array=orientation,
    color_by_vector_size=True,
    # scale_by_vector_size=True,
)

pos = (-5, -11, -30)
scalarbar = ScalarBar(
    vrange,
    title='E (V/m)',
    c="jet",
    font_size=22, 
    pos=(0.7, 0.25),
    size=(60,600),
)

# scalarbar = ScalarBar3D(
#     vrange,
#     title='E (V/m)',
#     c="jet",
#     # title_rotation=180,
#     title_size=14, 
#     # title_xoffset=-3,
#     # label_rotation=-90,
#     # label_offset=1,
#     # label_size=2,
#     # pos=pos,
#     # s=(1, 20),
#     # nlabels=5,
#     # s=(100,1000),
# )

# scalarbar.rotate_z(90, around=pos)

size = (3920, 2160)
plt = Plotter(size=size)

axes = Axes(
    arrows, 
    xtitle='Easting (m)',
    ytitle='Northing (m)',
    ztitle='Elevation (m)',
    xtitle_position=0.60,
    xlabel_size=0.018,
    xtitle_offset=0.15,
    ytitle_position=0.85,
    ylabel_rotation=-90,
    ylabel_size=0.02,
    ytitle_rotation=180,
    y_values_and_labels=[(-5, "-5"), (0, "0"), (5, "5")],
    axes_linewidth=4,
    xrange=arrows.xbounds(),
    yrange=arrows.ybounds(),
    zxgrid2=True,
    zshift_along_y=1,
    zaxis_rotation=-70,
    ztitle_size=0.02,
    ztitle_position=0.68,
    xyframe_line=True,
    grid_linewidth=2,
)
cam = dict(
    position=(-58.8911, -54.5234, 8.63461),
    focal_point=(-5.25549, -0.0457020, -23.8989),
    viewup=(0.248841, 0.304150, 0.919549),
    distance=83.0844,
    clipping_range=(34.8493, 143.093),
)
fig_name = 'electric_field.png'
plt.show(arrows, axes, scalarbar, interactive=1, camera=cam)
screenshot(fig_name)
plt.close()
```

As you can see in the `tmp_field_amp.txt` file, the arrows that are showing deep blue colors should actually have larger amplitudes. This is also expected from the physics that I am modeling. I don't think the code is honoring the size of the vectors passed in with the array `orientation`.

**Comment by marcomusy** [comment]
Hi Xushan, in fact i think it's not possible to do with the Glyph object.. but luckily you dont have so many points so you can create an `Assembly` (a group) from a set of individual arrows that you can colorize at will, what about this:

```py
import numpy as np
from vedo import settings, Plotter, Arrow, screenshot, \
    ScalarBar3D, Axes, mag, color_map, Assembly, Line

settings.default_font = 'Theemim'
settings.multi_samples=8

filename = 'obs_xyz.dat'
xyz = np.loadtxt(filename, dtype=np.float64)
xyz = xyz[1:, :] - np.array([0, 20, 0])
n_obs, n_col = xyz.shape

# Read in the data
num_field = np.loadtxt('tmp_field.txt', dtype=np.float64)
amp = mag(num_field)

# We need to create a few slices from the original arrays
# First create a mask array to mark all receiver points with x = -10, 0, 10
x_mark = [-19.5, -9.236842110, 1.026315790, 11.289473680, 19.5]
y_mark = [-4.5, 4.5]
mask = np.zeros(n_obs, dtype=bool)

# We need to create a mask array to mark all receiver points with x being
# any of x_mark and y being any of y_marko
for x_m in x_mark:
    mask_local = np.abs(xyz[:, 0] - x_m) < 1e-6
    mask = np.logical_or(mask, mask_local)

# Create an Arrows object for all the receivers where mask is True
start = xyz[mask, :]
orientation = num_field[mask, :]
orientation = orientation / mag(orientation)[:, None] # normalize
amp_mask = amp[mask]
vrange = np.array([amp_mask.min(), amp_mask.max()])

arrs = []
for i in range(start.shape[0]):
    arr = Arrow(start[i], start[i] + orientation[i] * 4)
    color = color_map(
        amp_mask[i], "jet", 
        vmin=vrange[0], vmax=vrange[1],
    )
    arr.color(color).lighting('off')
    arrs.append(arr)
arrows = Assembly(arrs)

# create a 2D scalarbar
# scalarbar = ScalarBar(
#     vrange,
#     title='E (V/m)',
#     c="jet",
#     font_size=22, 
#     pos=(0.7, 0.25),
#     size=(60,600),
# )

# create a dummy line to use as a 3D scalarbar
pos = (-10, -17, -30)
line = Line([0, 0], [1, 0]).cmap("jet", vrange*1e6)
scalarbar = ScalarBar3D(
    line,
    c="k",
    title='E (:muV/m)',
    title_rotation=180,
    title_size=4, 
    title_xoffset=-4,
    label_rotation=-90,
    label_offset=1,
    label_size=2,
    pos=pos,
    s=(1, 20),
    nlabels=5,
)
scalarbar.rotate_z(90, around=pos)

size = (3920, 2160)
plt = Plotter()

axes = Axes(
    arrows, 
    xtitle='Easting (m)',
    ytitle='Northing (m)',
    ztitle='Elevation (m)',
    xtitle_position=0.60,
    xlabel_size=0.018,
    xtitle_offset=0.15,
    ytitle_position=0.85,
    ylabel_rotation=-90,
    ylabel_size=0.02,
    ytitle_rotation=180,
    y_values_and_labels=[(-5, "-5"), (0, "0"), (5, "5")],
    axes_linewidth=4,
    xrange=arrows.xbounds(),
    yrange=arrows.ybounds(),
    zxgrid2=True,
    zshift_along_y=1,
    zaxis_rotation=-70,
    ztitle_size=0.02,
    ztitle_position=0.68,
    xyframe_line=True,
    grid_linewidth=2,
)
cam = dict(
    position=(-58.8911, -54.5234, 8.63461),
    focal_point=(-5.25549, -0.0457020, -23.8989),
    viewup=(0.248841, 0.304150, 0.919549),
    distance=83.0844,
    clipping_range=(34.8493, 143.093),
)
fig_name = 'electric_field.png'
plt.show(arrows, axes, scalarbar, interactive=0, camera=cam)
# screenshot(fig_name)
plt.interactive().close()
```

<img width="432" alt="Screenshot 2023-05-27 at 22 14 47" src="https://github.com/marcomusy/vedo/assets/32848391/98321e95-08f1-4eca-9ea8-34fb6445557b">

**Comment by marcomusy** [comment]
ps:
if you keep the scalrabar3d you may want to re-orient it:
```py
# create a dummy line to use as a 3D scalarbar
pos = (-10, -14, -32)
line = Line([0, 0], [1, 0]).cmap("jet", vrange * 1e6)
scalarbar = ScalarBar3D(
    line,
    # c="white",
    title="E (:muV/m)",
    title_size=3,
    title_xoffset=3,
    label_rotation=90,
    label_offset=.5,
    label_size=2,
    pos=pos,
    s=(1, 20),
    nlabels=5,
)
scalarbar.rotate_z(-90, around=pos)
```

Also consider `Arrow2D` instead of `Arrow`, especially if you like a dark theme:

<img width="480" alt="Screenshot 2023-05-27 at 23 45 06" src="https://github.com/marcomusy/vedo/assets/32848391/8f6819f5-f41d-4fad-92e8-72c8f9ddbe1a">

**Comment by XushanLu** [comment]
Hi Marco,

Thanks very much for coming up with this brilliant solution. Yes, I do not have a terrible amount of arrows and I am happy to do whatever works. I've never fully understood the Glyph thing. I managed to plot similar things with Paraview in the past and I could not do it anymore with the version I have on my computer because the orientation is always wrong no matter what I do. Anyways, time to adopt a fully vedo workflow.

I've changed your code a little bit and re-oriented the color bar (I really prefer 3D over 2D). I have also put the lighting back. I like it! Since I am using this plot for a publication, I'd stick to the light background. Here's what I have now:

![electric_field](https://github.com/marcomusy/vedo/assets/7824380/e2705c40-6a9c-473f-84ac-07b055f76c73)

Thanks very much. I am not sure whether the reason why the original code did not work is because of a bug. I do not think I need to figure that out anymore. Please close this issue if you think that is not a bug.

**Comment by marcomusy** [comment]
Looks great! Indeed I think it's not a real bug - just the fact that it's not possible to color glyphs independently from they being scaled.. so it's a different usecase..

**Comment by XushanLu** [comment]
Sorry, there is just one minor thing that I still want to improve. I read in your comments for function `make_ticks` from `utils` that it is not an easy thing to get really nice tick labels and locations automatically. The algorithm indeed looks very complex. 

In the above code, I only provided the data for one time instant to plot the electric field for simplicity reasons. However, when I wanted to plot the electric field for 29 instants, the dynamic range can get pretty large so I have to use scientific notation for all the values in the scalar bar. But below is what I get:

![electric_field_01](https://github.com/marcomusy/vedo/assets/7824380/f4b01a18-9ff1-4452-8fea-d5678517fc63)

Can we change that dot in the middle to 'x'? Also, is there a way to use log scale in ScalarBar3D? While function `make_tick` accepts a parameter `logscale`, that parameter is passed in in function `ScalarBar3D` by checking the value of `lut.GetScale` which I do not what is the return value:

https://github.com/marcomusy/vedo/blob/787680ca92d80049d22d09c590758ea6f7d23d55/vedo/addons.py#L1106-L1114

Here is the code I used for the `ScalarBar3D` function:

```python
    #create a dummy line to use as a 3D scalarbar
    pos = (0, -15, -32)
    line = Line([0, 0], [1, 0]).cmap("jet", vrange)
    scalarbar = ScalarBar3D(
        line,
        c="k",
        title='E (V/m)',
        # title_rotation=180,
        title_size=2, 
        title_xoffset=-3,
        label_rotation=90,
        label_offset=1,
        label_size=2,
        label_format=":.1e",
        pos=pos,
        s=(1, 30),
        nlabels=3,
    )
    scalarbar.rotate_z(-90, around=pos)
```

**Comment by marcomusy** [comment]
> Can we change that dot in the middle to 'x'? Also, is there a way to use log scale in ScalarBar3D? 

you can modify any `vedo.Assembly` by unpacking it and access any individual object like any usual vedo object, eg:
```py
from vedo import *

settings.default_font = "Theemim"

pts = [(0, 0), (1, 0), (1, 1), (0, 1), (0, 0.5)]
data = [1, 10, 100, 1000, 10000]
scalarbar = None

line = Line(pts, c="k", lw=10)
line.pointdata["mydata"] = data

line.cmap("jet", "mydata", logscale=True)

# automatic add scalarbar
# line.add_scalarbar(title="mydata", size=(100,800))
# line.add_scalarbar3d(title="mydata", nlabels=4)
#
# Or manual add scalarbar
# scalarbar = ScalarBar(line, title="mydata", size=(100,800))
scalarbar = ScalarBar3D(line, title="mydata", 
                        c='black', nlabels=4, label_format=":.1e")
# modify the text of the scalarbar
for e in scalarbar.unpack():
    if isinstance(e, Text3D):
        txt = e.text().replace(".0e+0", " x10^")
        if "x10" in txt: # skip the title
            e.text(txt)  # update new text
            e.scale(0.02)

plt = Plotter()
plt += [line, line.labels("mydata", scale=.02), scalarbar]
plt.show()
```

![Screenshot from 2023-05-28 13-34-43](https://github.com/marcomusy/vedo/assets/32848391/8000bc7f-036d-4145-b663-b1ea9c2eb2a4)

Suggestion from an old-school physicist: muV/m is better than x10^-6,
also consider avoiding jet cmap (it's considered a [bad choice](https://jakevdp.github.io/blog/2014/10/16/how-bad-is-your-colormap/) for visualization at least in some cases).

**Comment by XushanLu** [comment]
Hi Marco,

Thanks very much for the example! Well, while it works for the values you used in your example, the `replace` operation could fail for more general cases. For example:

```bash
before:  5.0e-07
after:  5 x10^-07
before:  1.0e-06
after:  1 x10^-06
before:  1.5e-06
after:  1.5e-06
before:  E (V/m)
after:  E (V/m)
```

This comes back to the comment you made 
> Suggestion from an old-school physicist: muV/m is better than x10^-6,

I guess I agree with you on this but my problem is the dynamic range which can be many orders of magnitude for a simulation. Well, I can still use mu V/m and let the numbers drop but it does not help with the `replace` operation.

I had a look at the code and I think you always replace `e` to `dotsep` which eventually equals to `~.`:
https://github.com/marcomusy/vedo/blob/3fc8b717062f460f792d98d37c217af60c28ea18/vedo/shapes.py#L4230-L4244

I am not sure why the dot is preferred over the multiplication symbol. I like the latter better and I just hacked the code to use the multiplication symbol for `dotsep` in function `_get_text3d_poly` for now:
```python
          dotsep = '\u00D7'
```

Also thanks very much for pointing out the issue with `jet`. I guess I like it because of the exact reason why we should avoid it: it exaggerates things too much. I found that I can even use the [scientific color maps](https://www.fabiocrameri.ch/colourmaps/):

```python
from cmcrameri import cm as cmc
    # c_map = 'viridis'
    c_map = cmc.batlow
    arrs = []
    for i in range(start.shape[0]):
        arr = Arrow(start[i], start[i] + orientation[i] * 2.5)
        color = color_map(amp_mask[i], c_map, vmin=vrange[0], vmax=vrange[1])
        # arr.color(color).lighting('off')
        arr.color(color)
        arrs.append(arr)

    arrows = Assembly(arrs)

    pos = (-5, -11, -30)

    bounds = [-20, 20, -5, 5, -30, -10]
    box = Box(size=bounds, c='lightgray').wireframe(True).lw(3)

    # create a dummy line to use as a 3D scalarbar
    pos = (0, -15, -32)
    line = Line([0, 0], [1, 0]).cmap(c_map, vrange)
```
 And here is how it looks like:
![electric_field_01](https://github.com/marcomusy/vedo/assets/7824380/d3fc5273-9495-4e6e-9ebd-8325e8183066)
`
I guess it's much less dramatic than the `jet` colormap but I should follow the best practices.

Any comments on how to make it possible to use log scale in `ScalarBar3D`? Here it does not matter too much since each plot does not have a large range but I can easily see the dynamic range gets too large and a log scale becomes better elsewhere.

Thanks a lot, Marco!

**Comment by marcomusy** [comment]
Holy cow.. I forgot you can simply do:
```py
settings.default_font = "Theemim"
settings.font_parameters["Theemim"]["dotsep"] = '\u00D7'
```
I will make it the default as you're right it's more readable.

To be fair I think the jet looks better after all! :)

> Any comments on how to make it possible to use log scale in ScalarBar3D?

the example I sent already uses log-scale.

**Comment by XushanLu** [comment]
Oh, that's a much more elegant solution.

>the example I sent already uses log-scale.

That's right, but it was impossible in my case as the colors were added to each arrow. I realized I could simply pass log values as the color and replace the text with their actual values. Tried that and it turns out to be much worse than just using the normal values. But I can use this trick for later.

**Comment by marcomusy** [comment]
you mean
```py
        color = color_map(np.log10(amp_mask[i]), c_map, vmin=np.log10(vrange[0]), vmax=np.log10(vrange[1]))
```
is what i would do.

**Comment by XushanLu** [comment]
Yes. I would also need to change the `vrange` used here:

```python
    line = Line([0, 0], [1, 0]).cmap(c_map, vrange)
```

Eventually, this will give me values in the scalar bar in the log space and I could simply convert them back to the normal values and then replace the text using the method you provided above. But would you think it's a good idea to add the optional parameter `logscale` in the `ScalarBar3D` function? What the if statement in the following code does anyways?

https://github.com/marcomusy/vedo/blob/3fc8b717062f460f792d98d37c217af60c28ea18/vedo/addons.py#L1106-L1114

**Comment by marcomusy** [comment]
uhm no, the only change should be in `color = color_map(np.log10(...` and all the rest will match..

> would you think it's a good idea to add the optional parameter logscale in the ScalarBar3D function? What the if statement in the following code does anyways?

the `cmap()` builds a LUT (look-up-table) which ScalarBar3D picks up automatically so no `logscale` keyword is necessary.

**Comment by XushanLu** [comment]
> uhm no, the only change should be in color = color_map(np.log10(... and all the rest will match..

If so, this would be what I get:

![electric_field_01_log](https://github.com/marcomusy/vedo/assets/7824380/0d405c44-6c53-4012-aa2c-49c5056efe84)

And the scalar bar is basically the same as the previous one:
![electric_field_01_original](https://github.com/marcomusy/vedo/assets/7824380/8e4e66f9-5f2d-4161-9ef8-2d2451f77764)
 
But the colors of the arrows are very different. While also changing `vrange` give me this:
![electric_field_01](https://github.com/marcomusy/vedo/assets/7824380/820b127f-0b1a-474f-98a5-aaca12d37082)

**Comment by marcomusy** [comment]
wait... i'm confused... the right combination should be:
`color = color_map(np.log10(amp_mask[i]), c_map, vmin=np.log10(vrange[0]), vmax=np.log10(vrange[1]))`
(this builds the right RGB color for each arrow)

and 
`line = Line([0, 0], [1, 0]).cmap(c_map, vrange, logscale=True)`
(this builds the scalarbar as log-scaled)

you should double check that what you see is correct by looking at a few points and their colors..

**Comment by XushanLu** [comment]
You are right! It's that `logscale=True` matters! I did not do that...
