### ISSUE TITLE
post rendering how do i get intensity of light on the mesh surface

### ISSUE THREAD

**Issue by hariharan382** [marcomusy/vedo#872]
I could get access to the property of mesh and find colour in it( which was the default set colour) , but I need to estimate the colour intensity at the surface of the mesh, how do i compute that

**Comment by marcomusy** [comment]
While pointing the mouse press `Shift-I`.

**Comment by hariharan382** [comment]
I dont want rendered pixel value, but a actual intensity of light incident at the sphere mesh

**Comment by marcomusy** [comment]
There is nothing like that, you need to compute it manually from the face normals and the position from the light source(s).

**Comment by hariharan382** [comment]
There is already rendering engine is computing it right for visual aspect , so what you are saying i cant access that?

**Comment by marcomusy** [comment]
because it's done on the GPU.
I'm not aware of any standard ways to retrieve some precomputed illumination per face.
