### ISSUE TITLE
impossible to use interactor_modes submodule

### ISSUE THREAD

**Issue by MiticoDan** [marcomusy/vedo#873]
Hi,

When I try to import the submodule interactor_modes, Python returns the error message 

> "NameError: name 'interactor_modes' is not defined."

I noticed that on the GitHub repository, there is a file named "vedo/interactor_modes.py", but it is not present in the virtual environment I created today. I installed vedo using pip, and I have version 2023.4.4.
If I try to manually place that file in the "myenv/lib/site-packages/vedo" folder, I get the following error:

>  File "myenv\lib\site-packages\vedo\interactor_modes.py", line 16, in <module> class MousePan(vtk.vtkInteractorStyleUser): AttributeError: module 'vedo.vtkclasses' has no attribute 'vtkInteractorStyleUser'. Did you mean: 'vtkInteractorStyleImage'?

Thank you for this fantastic library.

**Comment by marcomusy** [comment]
Thanks!

can you try:
```
pip uninstall vedo
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by MiticoDan** [comment]
Thanks for your reply!

After I tried to install as you instructed, now the import of the submodule is successful. However, unfortunately, when I interact with the scene, I receive the following error:


> File "myenv\lib\site-packages\vedo\interactor_modes.py", line 137, in _mouse_move
>     self.mouse_middle_move()
> AttributeError: 'MousePan' object has no attribute 'mouse_middle_move'. Did you mean: '_mouse_middle_move'?

So, I opened the file and made the suggested modification to this part of the code (line 133-139 of the interactor_modes.py file):

Before modification:
```
def _mouse_move(self, w, e):
        if self.left:
            self.mouse_left_move()
        if self.middle:
            self.mouse_middle_move()
        if self.right:
            self.mouse_right_move()
```


# After modification:
```
def _mouse_move(self, w, e):
        if self.left:
            self._mouse_left_move()
        if self.middle:
            self._mouse_middle_move()
        if self.right:
            self._mouse_right_move()
```

I'm not sure if it's a bug or something similar, but I hope I have been helpful and haven't wasted too much of your time, thanks!

**Comment by marcomusy** [comment]
Thanks for spotting the bug! Just fixed:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```
