### ISSUE TITLE
Mesh area not calculated for 4 point elements

### ISSUE THREAD

**Issue by 19kdc3** [marcomusy/vedo#874]
Hi Marco,

I'm trying to use the `.area()` function for a 2D mesh object made of elements with 4 points (ie. quad elements). I've noticed that when this is done, although the mesh appears to be constructed properly, when I try to get the area of it using `.area()`, it returns 0.

I modified your [example ](examples/basic/buildmesh.py) to construct the mesh using quads and was able to reproduce the bug.

    # Define the vertices and faces that make up the mesh
    verts = [(0,0,0), (50,0,0), (50,50,0), (0,50,0)]
    faces = [(0,1,2,3)]

    # Build the polygonal Mesh object from the vertices and faces
    mesh = vd.Mesh([verts, faces])

    #get area
    surf_area = mesh.area()

Thanks for the help!

**Comment by marcomusy** [comment]
Hi, it only works for triangular meshes so you nee to change it to:
```py
mesh = vd.Mesh([verts, faces]).triangulate()
```

**Comment by 19kdc3** [comment]
I see, thanks for the help!
