### ISSUE TITLE
isosurface() error in Tetmesh

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [marcomusy/vedo#881]
File "c:\Users\for\Desktop\vedo\examples\other\test.py", line 29, in <module>
    mesh = mesh.isosurface()
  File "C:\Users\for\anaconda3\envs\vedo\lib\site-packages\vedo\tetmesh.py", line 474, in isosurface
    scrange = self._data.GetPointData().GetScalars().GetRange()
AttributeError: 'NoneType' object has no attribute 'GetRange'

Is there a solution ?

**Comment by marcomusy** [comment]
the error message says you have and invalid `mesh` object in
```
mesh = mesh.isosurface()
```
also variable naming looks confusing..

**Comment by marcomusy** [comment]
Also, check out example
`examples/volumetric/tet_isos_slice.py`

**Comment by HyungJoo-Kwon** [comment]
Thanks, i'll try it
