### ISSUE TITLE
how to set the font size for the simple ruler of the window?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#883]
For `show(..., axes=13)`, it would show a ruler. For example, 

![image](https://github.com/marcomusy/vedo/assets/29271051/cf888988-20ed-43ad-8afd-86a892c5e629)

I want to know how can I set the font size for the ruler? Any suggestion is appreciated~~~

**Comment by marcomusy** [comment]
I suggest:

```py
settings.default_font = "Calco"

plt = show(mymesh, axes=13, interactive=False).parallel_projection(True)

plt.axes_instances[0].SetBottomBorderOffset(50)
plt.axes_instances[0].GetBottomAxis().GetProperty().SetLineWidth(2)
plt.axes_instances[0].GetBottomAxis().SetFontFactor(1.2)

plt.interactive()
plt.close()
```

Note that a 2D ruler only makes sense in parallel projection mode.
