### ISSUE TITLE
triangulate failed

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#896]
I use `triangulate` in my project, but it failed. 

The code to reproduce the problem is:

```
from vedo import *
tube = Tube([[69.495, 74.495, 39.663], [69.495, 64.495, 39.663]], r=[2.5, 1.7], res=40).triangulate().alpha(0.3)
contour = tube.intersect_with_plane(origin=[0, 0, 39.663],normal=[0, 0, 1])
m = contour.clone().triangulate().c('r')
show(tube, contour, axes=1, at=0, N=2)
show(m, at=1).interactive()
```

The result is:

![image](https://github.com/marcomusy/vedo/assets/29271051/de867bd2-6563-4a5e-9596-660a5a3d002c)

In the left picture, the black line is the result of `intersect_with_plane`, and I want to make it triangulated. The right picture is the triangulation result. But it obviously is wrong, it should be a trapezoid.

My environment is: 

```
vedo 2023.4.4
vtk 9.2.6
```

Is there anything wrong with my code?

**Comment by marcomusy** [comment]
Update with 
```
pip install vedo -U
```

then `clean()` seems to do the job:
```py

from vedo import *
tube = Tube([[69.495, 74.495, 39.663], [69.495, 64.495, 39.663]], r=[2.5, 1.7], res=40)
tube.triangulate().alpha(0.3)
contour = tube.intersect_with_plane(origin=[0, 0, 39.663],normal=[0, 0, 1]).clean()
m = contour.clone().triangulate().c('red5')
show(tube, contour, contour.labels2d('id'), axes=1, at=0, N=2)
show(m, at=1).interactive()
```

**Comment by zhang-qiang-github** [comment]
Thanks~~~~
