### ISSUE TITLE
Per Vertex Color not working starting from 2023.4.5

### ISSUE THREAD

**Issue by paul0noah** [marcomusy/vedo#898]
Hi Marco, 

i have a colormap for every individual vertex of my triangle mesh and i apply the per-vertex coloring as follows:

```python
mesh.pointdata['vertex_colors'] = np.array(cmap).astype(np.uint8) #cmap of same shape as mesh.points()
mesh.pointdata.select('vertex_colors')
```

Until version `2023.4.4` this results in colorful  renders of the shape but starting from version `2023.4.5` the mesh renders only in pure white.

**Comment by marcomusy** [comment]
Hi, thanks for reporting, does this work for you?
```py
from vedo import *
mesh = Points(np.random.rand(1000, 3), r=15)
cols = np.random.rand(mesh.npoints, 3) * 255
mesh.pointcolors = cols
show(mesh)
```

<img width="300" alt="Screenshot 2023-07-17 at 13 29 28" src="https://github.com/marcomusy/vedo/assets/32848391/cfdea3cf-8264-4439-9790-86b160ec61fa">

can you take a screenshot of your output?

What is your OS? Try
```bash
vedo -i
```
Thanks!

**Comment by paul0noah** [comment]
Hey Marco, 

I am on MacOs. Just replaced my code
```
mesh.pointdata['vertex_colors'] = np.array(cmap).astype(np.uint8) #cmap of same shape as mesh.points()
mesh.pointdata.select('vertex_colors')
```
with your code
```
mesh.pointcolors =  np.array(cmap).astype(np.uint8) 
```
and it works like a charm. 

This is the output of your code:

<img width="592" alt="Screenshot 2023-07-17 at 14 29 09" src="https://github.com/marcomusy/vedo/assets/38716946/9bc59967-c499-46ec-809a-08762a51e694">
