### ISSUE TITLE
Color mesh based on regions

### ISSUE THREAD

**Issue by ilsemeijer99** [marcomusy/vedo#901]
Hi Marco,

I am trying to color my surfacemesh based on distinct regions, by creating a lookup table with category names. However, when there is a border between two regions that do not have adjacent values (e.g. region 0 and 2) the color of region 1 is depicted between the two, as some kind of interpolation (see picture).

![Naamloos](https://github.com/marcomusy/vedo/assets/73226038/ab8e7bf5-b6e0-4ba4-8101-3425fbba7725)

A snippet of the code I use:
lut_table = [(1, 1, 1, "Region 1"), (2, 2, 1, "Region 2"), (3, 3, 1, "Region 3"), (4, 6, 1, "Region 4"), (5, 5, 1, "Region 5")] #value, color,   alpha, category_label
lut = build_lut(lut_table, interpolate=True)
vmesh.cmap(lut, c).add_scalarbar3d(title="Regions", categories=lut_table)

I have tried to change interpolate to False but this only makes the result worse.

I hope you can help me with this!

Thank you in advance, Ilse

**Comment by marcomusy** [comment]
Hi Ilse, if you associate data to points (vertices) then some level of interpolation is unavoidable on mesh faces..
One thing you can try is to map the data onto faces , and only colorize those, with:
https://vedo.embl.es/autodocs/content/vedo/vedo/base.html#BaseActor.map_points_to_cells
(see also the given example in the docs, you may need to change to `cmap(..., on="cells")`)

**Comment by ilsemeijer99** [comment]
Oh ofcourse, thank you that works!
