### ISSUE TITLE
Downsample mesh with updated connected faces

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#903]
Hi, is there an easy solution for removing multiple points in a mesh and then updating the faces so connected vertices are still joined? i.e. recalculating the vertices in each face after the removal of a vertex. Using `delete_cells_by_point_index` seems to remove all faces containing the indices I provide. I want to use a farthest sampling algorithm to determine the points and get a subsample back with an exact amount of vertices, and the faces of the sample. Connected vertices should remain connected.

Is there a simple solution to this?

`subsample` and `decimate` are inconsistent (I believe due to my 3D mesh being made up via photogrammetry; completely disconnected vertices are pruned beforehand).

**Comment by marcomusy** [comment]
Hi Jeffrey, if I understand you correctly the combination of  `delete_cells_by_point_index().clean()` should do the job..

**Comment by JeffreyWardman** [comment]
Hi Marco, for a mesh with 80,000 points, if I run it with 5000 indices, I expect to get back 75,000 points, however, instead I get 0.

**Comment by marcomusy** [comment]
well there must be something else going wrong.... can you reproduce this
```py
from vedo import *

msh = Mesh(dataurl+'apple.ply')
msh.c('lightgreen').bc('tomato').lw(0.1)

pt = [1, 0.5, 1]
R = 1
ids = msh.closest_point(pt, radius=R, return_point_id=True)

printc('#points before:', msh.npoints, len(ids), c='g')
msh.delete_cells_by_point_index(ids)
msh.clean()
printc('#points after :', msh.npoints, c='g')

sph = Sphere(pt, r=R, alpha=0.1)
show(Point(pt), sph, msh, axes=1).close()
```

<img width="277" alt="Screenshot 2023-07-23 at 16 17 42" src="https://github.com/marcomusy/vedo/assets/32848391/9e09466b-ee95-4f25-8186-552db8a44fa3">

**Comment by JeffreyWardman** [comment]
That works fine. My mesh is not fully connected like a sphere which may cause issues. My model has some holes too but I've tried the below with `fill_holes()` before `delete_cells_by_point_index()` but that didn't improve results. 

```
mesh_partial = mesh.clone().delete_cells_by_point_index(indices_to_remove).clean()

# farthest point sampling of 8000 indices --> indices_to_remove are the indices not selected by the sampling.

indices_to_remove
array([    0,     1,     2, ..., 84965, 84966, 84967])

len(indices_to_remove)
76968

mesh.npoints
84968

mesh_partial.npoints
336
```

**Comment by marcomusy** [comment]
Hi Jeffrey, sorry for the late reply.
could it be that your initial mesh already contains duplicate points?
if not can you share a sample of your mesh to try to reproduce the issue?
The fact that it is not fully connected should not matter.

**Comment by JeffreyWardman** [comment]
Closing this issue unless I run into the issue again.
