### ISSUE TITLE
button call_back in plotter problem

### ISSUE THREAD

**Issue by smoothumut** [marcomusy/vedo#905]
Hi Marco,
I have been trying to implement button function in plotter using your 2 examples. One is buttons.py the other one is qt_windows1.py examples.
Somehow, button's callback in plotter is not triggered when qt is being used ! 

Here is my code...
      
      import sys
      from PyQt5 import Qt
      from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
      from vedo import Plotter, Cone, printc
      
      class MainWindow(Qt.QMainWindow):
      
          def __init__(self, parent=None):
      
              Qt.QMainWindow.__init__(self, parent)
              self.frame = Qt.QFrame()
              self.layout = Qt.QVBoxLayout()
              self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
      
              # Create renderer and add the vedo objects and callbacks
              self.plt = Plotter(qt_widget=self.vtkWidget)
              # self.id1 = self.plt.add_callback("mouse click", self.onMouseClick)
              # self.id2 = self.plt.add_callback("key press",   self.onKeypress)
              self.plt += Cone().rotate_x(20)
      
              def buttonfunc():
                  print("btn is clicked...")
      
              self.btn_both = self.plt.add_button(
                  buttonfunc,
                  pos=(0.7, 0.05),  # x,y fraction from bottom left corner
                  states=["click to hide", "click to show"],  # text for each state
                  c=["w", "w"],     # font color for each state
                  bc=["dg", "dv"],  # background color for each state
                  font="courier",   # font type
                  size=25,          # font size
                  bold=True,        # bold font
                  italic=False,     # non-italic font style
              )
      
      
              self.plt.show()                  # <--- show the vedo rendering
      
              # Set-up the rest of the Qt window
              button = Qt.QPushButton("My Button makes the cone red")
              button.setToolTip('This is an example button')
              button.clicked.connect(self.onClick)
              self.layout.addWidget(self.vtkWidget)
              self.layout.addWidget(button)
              self.frame.setLayout(self.layout)
              self.setCentralWidget(self.frame)
              self.show()                     # <--- show the Qt Window
      
          def onMouseClick(self, evt):
              printc("You have clicked your mouse button. Event info:\n", evt, c='y')
      
          def onKeypress(self, evt):
              printc("You have pressed key:", evt.keypress, c='b')
      
          @Qt.pyqtSlot()
          def onClick(self):
              printc("..calling onClick")
              self.plt.actors[0].color('red').rotate_z(40)
              self.plt.interactor.Render()
      
          def onClose(self):
              #Disable the interactor before closing to prevent it
              #from trying to act on already deleted items
              printc("..calling onClose")
              self.vtkWidget.close()
      
      if __name__ == "__main__":
           app = Qt.QApplication(sys.argv)
           window = MainWindow()
           app.aboutToQuit.connect(window.onClose) # <-- connect the onClose event
           app.exec_()
      

how can I resolve this problem or create a workaround?
thanks in advance 
Regards

**Comment by marcomusy** [comment]
Thanks @smoothumut for spotting the bug, this should be now fixed with:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

Test with:
```py
import sys
from PyQt5 import Qt
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from vedo import Plotter, Cone, printc


class MainWindow(Qt.QMainWindow):
 
    def __init__(self, parent=None):

        Qt.QMainWindow.__init__(self, parent)
        self.frame = Qt.QFrame()
        self.layout = Qt.QVBoxLayout()
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)

        # Create renderer and add the vedo objects and callbacks
        self.plt = Plotter(qt_widget=self.vtkWidget)
        self.plt += Cone().rotate_x(20)

        self.button = self.plt.add_button(
            self.buttonfunc,
            pos=(0.7, 0.05),  # x,y fraction from bottom left corner
            states=["click to green"],  # text for each state
            c=["w"],  # font color for each state
            bc=["dg"],  # background color for each state
            font="courier",  # font type
            size=25,  # font size
            bold=True,  # bold font
            italic=False,  # non-italic font style
        )

        self.plt.show()  # <--- show the vedo rendering

        # Set-up the rest of the Qt window
        button = Qt.QPushButton("My Button makes the cone red")
        button.setToolTip("This is an example button")
        button.clicked.connect(self.onClick)
        self.layout.addWidget(self.vtkWidget)
        self.layout.addWidget(button)
        self.frame.setLayout(self.layout)
        self.setCentralWidget(self.frame)
        self.show()  # <--- show the Qt Window

    def buttonfunc(self, event):
        print("btn is clicked...")
        self.plt.actors[0].color("green5").rotate_z(40)
        
    @Qt.pyqtSlot()
    def onClick(self):
        printc("..calling onClick")
        self.plt.actors[0].color("red5").rotate_z(40)
        self.plt.render()


if __name__ == "__main__":
    app = Qt.QApplication(sys.argv)
    window = MainWindow()
    app.exec_()
```
![Screenshot from 2023-07-25 17-52-29](https://github.com/marcomusy/vedo/assets/32848391/3c7a96f7-a8eb-4c52-af2e-77bfd8ac7022)

Note that you need to have `event` in the callback:
`    def buttonfunc(self, event):`
Also I'm not completely positive that this can work on OSX due to a bug in the upstream VTK (not depending on vedo, hopefully to be fixed in the near future).

**Comment by smoothumut** [comment]
OMG Finally I saw the breakpoint on "btn is clicked" line : ) 

Thank you very much for this great library and your precious support Marco.

The spectacular library vtk would stay as a gem under ground without your library and examples in python perspective. They give a lot of ideas about functions and let us see how they can be used in python

I feel very grateful, Thanks and have a good day

**Comment by smoothumut** [comment]
Hi Marco, I have noticed that if there are multiple buttons in plotter, then when one of them is clicked, then the other ones are also triggered. here is the example

      import sys
      from PyQt5 import Qt
      from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
      from vedo import Plotter, Cone, printc
      
      class MainWindow(Qt.QMainWindow):
      
          def __init__(self, parent=None):
      
              Qt.QMainWindow.__init__(self, parent)
              self.frame = Qt.QFrame()
              self.layout = Qt.QVBoxLayout()
              self.vtkWidget = QVTKRenderWindowInteractor(self.frame)
      
              # Create renderer and add the vedo objects and callbacks
              self.plt = Plotter(qt_widget=self.vtkWidget)
              # self.id1 = self.plt.add_callback("mouse click", self.onMouseClick)
              # self.id2 = self.plt.add_callback("key press",   self.onKeypress)
              self.plt += Cone().rotate_x(20)
      
      
      
              self.btn_both = self.plt.add_button(
                  self.buttonfunc1,
                  pos=(0.7, 0.05),  # x,y fraction from bottom left corner
                  states=["click to hide", "click to show"],  # text for each state
                  c=["w", "w"],     # font color for each state
                  bc=["dg", "dv"],  # background color for each state
                  font="courier",   # font type
                  size=16,          # font size
                  bold=True,        # bold font
                  italic=False,     # non-italic font style
              )
      
              self.btn_both = self.plt.add_button(
                  self.buttonfunc2,
                  pos=(0.3, 0.05),  # x,y fraction from bottom left corner
                  states=["click to hide", "click to show"],  # text for each state
                  c=["w", "w"],     # font color for each state
                  bc=["dg", "dv"],  # background color for each state
                  font="courier",   # font type
                  size=16,          # font size
                  bold=True,        # bold font
                  italic=False,     # non-italic font style
              )
      
      
              self.plt.show()                  # <--- show the vedo rendering
      
              # Set-up the rest of the Qt window
              button = Qt.QPushButton("My Button makes the cone red")
              button.setToolTip('This is an example button')
              button.clicked.connect(self.onClick)
              self.layout.addWidget(self.vtkWidget)
              self.layout.addWidget(button)
              self.frame.setLayout(self.layout)
              self.setCentralWidget(self.frame)
              self.show()                     # <--- show the Qt Window
      
          def buttonfunc1(self,event):
              print("btn1 is clicked...")
      
          def buttonfunc2(self,event):
              print("btn2 is clicked...")
      
          def onMouseClick(self, evt):
              printc("You have clicked your mouse button. Event info:\n", evt, c='y')
      
          def onKeypress(self, evt):
              printc("You have pressed key:", evt.keypress, c='b')
      
          @Qt.pyqtSlot()
          def onClick(self):
              printc("..calling onClick")
              self.plt.actors[0].color('red').rotate_z(40)
              self.plt.interactor.Render()
      
          def onClose(self):
              #Disable the interactor before closing to prevent it
              #from trying to act on already deleted items
              printc("..calling onClose")
              self.vtkWidget.close()
      
      if __name__ == "__main__":
          app = Qt.QApplication(sys.argv)
          window = MainWindow()
          app.aboutToQuit.connect(window.onClose) # <-- connect the onClose event
          app.exec_()

**Comment by smoothumut** [comment]
I think that clicking to the plotter triggers the functions attached

**Comment by marcomusy** [comment]
Hi thanks a lot for your nice words! Your feedback motivates me improving the library!

After the usual
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

Try:
```py
import sys
from PyQt5 import Qt
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from vedo import Plotter, Cone, printc

class MainWindow(Qt.QMainWindow):

    def __init__(self, parent=None):

        Qt.QMainWindow.__init__(self, parent)
        self.frame = Qt.QFrame()
        self.layout = Qt.QVBoxLayout()
        self.vtkWidget = QVTKRenderWindowInteractor(self.frame)

        # Create renderer and add the vedo objects and callbacks
        self.plt = Plotter(qt_widget=self.vtkWidget)
        self.plt += Cone().rotate_x(20)

        self.btn_both1 = self.plt.add_button(
            self.buttonfunc1,
            pos=(0.3, 0.05),  # x,y fraction from bottom left corner
            states=["show1", "hide1"],  # text for each state
            c=["w", "w"],     # font color for each state
            bc=["dg", "dv"],  # background color for each state
            font="courier",   # font type
            size=16,          # font size
            bold=True,        # bold font
            italic=False,     # non-italic font style
        )

        self.btn_both2 = self.plt.add_button(
            self.buttonfunc2,
            pos=(0.7, 0.05),  # x,y fraction from bottom left corner
            states=["show2", "hide2"],  # text for each state
            c=["w", "w"],     # font color for each state
            bc=["dg", "dv"],  # background color for each state
            font="courier",   # font type
            size=16,          # font size
            bold=True,        # bold font
            italic=False,     # non-italic font style
        )

        self.plt.show()                  # <--- show the vedo rendering

        # Set-up the rest of the Qt window
        button = Qt.QPushButton("My Button makes the cone red")
        button.setToolTip('This is an example button')
        button.clicked.connect(self.onClick)
        self.layout.addWidget(self.vtkWidget)
        self.layout.addWidget(button)
        self.frame.setLayout(self.layout)
        self.setCentralWidget(self.frame)
        self.show()                     # <--- show the Qt Window

    def buttonfunc1(self, event):
        if event.actor == self.btn_both1:
            print("btn1 is clicked...")
            self.btn_both1.switch() # switch state

    def buttonfunc2(self, event):
        if event.actor == self.btn_both2:
            print("btn2 is clicked...")
            self.btn_both2.switch() # switch state

    def onMouseClick(self, evt):
        printc("You have clicked your mouse button. Event info:\n", evt, c='y')

    def onKeypress(self, evt):
        printc("You have pressed key:", evt.keypress, c='b')

    @Qt.pyqtSlot()
    def onClick(self):
        printc("..calling onClick")
        self.plt.actors[0].color('red').rotate_z(40)
        self.plt.interactor.Render()

    def onClose(self):
        #Disable the interactor before closing to prevent it
        #from trying to act on already deleted items
        printc("..calling onClose")
        self.vtkWidget.close()

if __name__ == "__main__":
    app = Qt.QApplication(sys.argv)
    window = MainWindow()
    app.aboutToQuit.connect(window.onClose) # <-- connect the onClose event
    app.exec_()
```

Let me know if encounter any problems.

**Comment by smoothumut** [comment]
Thank you very much again Marco, it works great : )
Now I can move forward
Regarding feedbacks, no problem at all, The other 1.6k people watching this library also feel the same with me. 
But most people doesnt like to put their feelings into words. 
I do : )
Thanks, thanks again for quick help and have a great day
