### ISSUE TITLE
How to visualize a 3D array

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#907]
I think visualization 3D array is helpful for `understanding dimensions` and `calculating indexes`. May I ask how to present the array content in voxel and view the value of a slice

I found some related functions here:
- Plotting: plot numpy arrays

```
import numpy as np
from vedo.pyplot import matrix
from vedo import show

data = np.arange(0, 60).reshape(5, 12)
mat = matrix(data, scale=0.2, lw=2)
show(mat).close()
```

![image](https://github.com/marcomusy/vedo/assets/34391447/7923d7df-912a-44c9-ad48-fafbad1af9c8)

- Volumetric: slice a volume
```
import numpy as np
from vedo import Volume
from vedo.applications import Slicer3DPlotter
data = np.arange(0, 60).reshape(5, 3, 4)
plt = Slicer3DPlotter(Volume(data), cmaps=("gist_ncar_r", "jet",))
plt.close()
```
![image](https://github.com/marcomusy/vedo/assets/34391447/53b72ad8-a3ad-43df-97ad-cf58d6033b66)

**Comment by marcomusy** [comment]
Hi, sorry this is precisely what you have done in the second case I believe.
If you want to slice a volumetric dataset with a generic plane or even with a mesh you can also do it - check examples:
```
vedo/examples/volumetric/slice_mesh.py
vedo/examples/volumetric/slice_plane1.py
vedo/examples/volumetric/slice_plane2.py
```
