### ISSUE TITLE
Crop fails after rotating object

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#911]
I'd like to crop an object along its major axis. However, if I run:

```
mesh_rotated = mesh.rotate_x(20).rotate_y(10).rotate_z(5)
mesh.crop(top=20).points()
```
returns an empty array.

**Comment by marcomusy** [comment]
Thanks for spotting the bug.
After:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

try eg:
```py
from vedo import *
mesh = Mesh("https://vedo.embl.es/examples/data/panther.stl")
mesh.rotate_x(20).rotate_y(10).rotate_z(5)
mesh.crop(top=0.25)
show(mesh, axes=1)
```

![Screenshot from 2023-08-23 21-21-16](https://github.com/marcomusy/vedo/assets/32848391/c58e77ad-a355-4734-87f3-ff57e0d061ab)


note that `top=...` is expressed in fractional units.

**Comment by JeffreyWardman** [comment]
Works great, thanks! 

Do you know a simple way to keep the partial faces that end up being entirely cropped? i.e. if there's a face that isn't entirely cropped, can the vertex be shifted to the boundary so the face remains? I assume crop_by_plane would have the same affect as the example you have where there'd be holes around the panther's left legs.

**Comment by marcomusy** [comment]
Yes - it's called `.cut_with_plane()`
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#Points.cut_with_plane
