### ISSUE TITLE
linewidth in silhouette

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#912]
problem: how to close linewidth in silhouette

mesh: [SMPL_A.txt](https://github.com/marcomusy/vedo/files/12273512/SMPL_A.txt)

code:
```
from vedo import settings, Plotter, Mesh

settings.use_depth_peeling = True

plt = Plotter()

path_mesh = "SMPL_A.obj"
mesh = Mesh(path_mesh).lighting("off").c("pink").alpha(0.5)

plt.show(
    mesh,
    mesh.silhouette(border_edges=True, feature_angle=False).linewidth(3).color("dr"),
)

plt.close()
```

result:
![image](https://github.com/marcomusy/vedo/assets/34391447/2172c29d-fd1e-4dbb-a6f2-dc9bceef2bb6)

**Comment by marcomusy** [comment]
Sorry for the late reply, unfortunately I don't quite understand what you mean by "how to close linewidth"!

**Comment by LogWell** [comment]
What I mean is to turn it off and not show it.

**Comment by marcomusy** [comment]
try `linewidth(0)`
