### ISSUE TITLE
Is vedo implement the mesh deformable algorithm?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vedo#914]
For example, I have a face mesh, and there are eye, nose in the face mesh. 

Now, I have the key point of eye, and I want to make the eye bigger. So, I want to deform this mesh according with the key point of eye. Is vedo implement some related algorithm?

Thanks in advance~~~

**Comment by marcomusy** [comment]
yes there are a number of examples for mesh warping, eg
`examples/advanced/warp2.py`

try:
```
vedo --search warp
```
