### ISSUE TITLE
how to compose multiple Volume into a single one

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vedo#915]
For example, I have 4 volumes (128x128x128), and I can show them in four windows together, but how to compose them into a single one and mark each component a different color?
![image](https://github.com/marcomusy/vedo/assets/34391447/6e76023c-cee9-42a2-a75c-d99c0b83f130)

**Comment by marcomusy** [comment]
Sorry I overlooked your issue.
You want to overlap them on top of each other? Or one next to the other in the same rendering window?
Is `show(vol1, vol2, vlo3, .., )` not working?

**Comment by LogWell** [comment]
In short, each voxel records its distance to the front, back, left, and right views of a mesh. I want to visualize this quantity and expect it to have a blending effect.
