### ISSUE TITLE
Allow vedo.load to load mesh from bytes

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#922]
Feature request:

- Allow a user to open an STL file without having to write it to a file

```
with open(stl_path, "rb") as f:
    stl_bytes = f.read()
vedo.load(stl_bytes) # or vedo.load(io.BytesIO(stl_bytes))
```

**Comment by JeffreyWardman** [comment]
A quick fix would be to further enhance the numpy2vtk such that it allows meshes from `numpy-stl`. 
Inspiration can be from that library with `https://numpy-stl.readthedocs.io/en/latest/stl.html?highlight=load#stl.Mesh.load` which takes in the buffered reader from `open(path)`.

E.g.
```
from stl.mesh import Mesh
mesh = Mesh.load(open(path, "rb"))
vedo_mesh = vedo.utils.numpy2vtk(mesh)
```
However, I believe this doesn't work with PLY files for instance, which retain color information.

**Comment by JeffreyWardman** [comment]
A workaround is:

```
import vedo
import numpy as np
import stl
import io

def bytes_to_vedo(mesh_bytes: bytes) -> vedo.Mesh:
    stl_mesh = stl.mesh.Mesh.load(io.BufferedReader(io.BytesIO(mesh_bytes)))
    faces = stl_mesh[1]["vectors"]
    points = np.unique(faces.reshape(-1, faces.shape[-1]), axis=0)
    point_to_index = {tuple(point): index for index, point in enumerate(points)}
    face_indices = np.array([[point_to_index[tuple(point)] for point in face] for face in faces])

    mesh = vedo.Mesh([points, face_indices])
    return mesh
```
However, the normals seem to be incorrect. I used the default cube in blender to test it.

**Comment by marcomusy** [comment]
Hi Jeffrey, sorry I don't understand very well the problem.. in `vedo` you can already load binary stl format, eg.:
```python
from vedo import *

msh = Mesh("Cube_3d_printing_sample.stl")  # or
# msh = Mesh("https://ozeki.hu/attachments/116/Cube_3d_printing_sample.stl")

show(msh)
```

https://ozeki.hu/attachments/116/Cube_3d_printing_sample.stl

**Comment by marcomusy** [comment]
Oh sorry I see you want to have it from bytes... yes I guess the only feasible otpion is what you suggested, normals look ok to me though

![Screenshot from 2023-09-06 17-09-20](https://github.com/marcomusy/vedo/assets/32848391/a3d8d243-4f69-4f66-8a37-6ada9b898bf9)
