### ISSUE TITLE
Mesh is not rendered properly

### ISSUE THREAD

**Issue by MartensCedric** [marcomusy/vedo#930]
I have a mesh that looks fine in MeshLab
![image](https://github.com/marcomusy/vedo/assets/18620025/52de0f57-66d6-4a07-9b5f-9c8d4bb9b823)

But looks terrible in vedo:
![image](https://github.com/marcomusy/vedo/assets/18620025/650a639e-14d5-468e-98e8-98cf31c3f183)

I have attached a .zip containing a single .obj file which is that mesh:
[min_surface.zip](https://github.com/marcomusy/vedo/files/12599634/min_surface.zip)

I'm on version 2023.4.6

**Comment by marcomusy** [comment]
Hi, it looks ok to me:
```py
from vedo import *
msh = Mesh("min_surface.obj").c("gold")
show(msh, axes=3)
```

![Screenshot from 2023-09-13 18-02-26](https://github.com/marcomusy/vedo/assets/32848391/51a94bb1-ab14-4a47-be42-44bba40949af)

Try:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

also:
```
vedo --info
```

**Comment by MartensCedric** [comment]
Ah, I figured out the issue, I was actually importing V and F from a scipy.io mat file, however the MATLAB indexing is off by 1
