### ISSUE TITLE
Figure window not display

### ISSUE THREAD

**Issue by CyberFork** [marcomusy/vedo#932]
I'm new to vedo, so I ran the "manypoints" demo using "vedo -r manypoints", and a figure showed up. However, when I copied the code and tried to run it, nothing happened, which left me very confused.

```
"""Colorize a large cloud of 1M points by passing
colors and transparencies in the format (R,G,B,A)"""
import time
from vedo import *

N = 1000000

pts = np.random.rand(N, 3)
RGB = pts * 255
Alpha = pts[:, 2] * 255
RGBA = np.c_[RGB, Alpha]  # concatenate

t0 = time.time()

# passing c in format (R,G,B,A) is ~50x faster
pts = Points(pts, r=2, c=RGBA)

t1 = time.time()
print("-> elapsed time:", t1-t0, "seconds for N:", N)

show(pts, __doc__, axes=True).close()
```

**Comment by marcomusy** [comment]
well the good news is that everything works fine otherwise you  would not see it the first way :) 
Are you trying to run in inside of an IDE?
Or from command line with something like 
```
python my_script.py
```

**Comment by CyberFork** [comment]
> well the good news is that everything works fine otherwise you would not see it the first way :) Are you trying to run in inside of an IDE? Or from command line with something like
> 
> ```
> python my_script.py
> ```

thank u, it's worked
