### ISSUE TITLE
vedo2meshlab cannot handle "RGB" attribute, nor retain "Normals"

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#934]
vedo version: 2023.4.6+dev11
pymeshlab version: 2022.2.post4

mesh.vedo2meshlab() silently exits (crashes) with  k = "RGB".

Error is in the `elif`
```
    for k in vmesh.celldata.keys():
        data = vmesh.celldata[k]
        if data is not None:
            if data.ndim == 1:  # scalar
                m.add_face_custom_scalar_attribute(data.astype(np.float64), k)
            elif data.ndim == 2 and k != "Normals":  # vectorial data
                m.add_face_custom_point_attribute(data.astype(np.float64), k)
```

I want to be able to use pymeshlab's [face_curvature_principal_dir1_matrix](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html#pmeshlab.Mesh.face_curvature_principal_dir1_matrix) and [vertex_curvature_principal_dir1_matrix](https://pymeshlab.readthedocs.io/en/latest/classes/mesh.html#pmeshlab.Mesh.vertex_curvature_principal_dir1_matrix). These both fail when commenting out the `elif`. I assume the normals are needed. Is there a way to keep this information in the pymeshlab Mesh?

Errors in pymeshlab for those functions - probably due to missing normals:
```
Missing Component Exception -PerFaceCurvatureDir- 
Missing Component Exception -PerVertexCurvatureDir- 
```

**Comment by JeffreyWardman** [comment]
Because Normals isn't stored, there's also this error:
```
pymeshlab.pmeshlab.PyMeshLabException: Error while creating mesh: the number of face normals is different from the number of faces.
```

**Comment by marcomusy** [comment]
Hi Jeffrey - sorry I was away.. by chance do you have a minimal working example to reproduce the issue?
it's a bit difficult for me to fix this otherwise..

**Comment by JeffreyWardman** [comment]
Trying to recreate it with public data but stuck along the way with this example:

```
import numpy as np
import pymeshlab
import vedo

mesh1 = vedo.Mesh(vedo.dataurl + "bunny.obj").clean()
mesh1.pointdata["RGBA"] = np.asarray([[0, 0, 0, 0]] * mesh1.npoints)
mesh1.pointdata["Normals"] = mesh1.normals()

m1 = vedo.vedo2meshlab(mesh1)
```

It crashes at  vedo/utils::2536
```
            elif data.ndim == 2:  # vectorial data
                if "tcoord" not in k.lower() and k not in ["Normals", "TextureCoordinates"]:
                    m.add_vertex_custom_point_attribute(data.astype(np.float64), k)  # <-----
```

RGBA should expect 4 columns but I get this TypeError:
```
add_vertex_custom_point_attribute(): incompatible function arguments. The following argument types are supported:
    1. (self: pymeshlab.pmeshlab.Mesh, attribute_values: numpy.ndarray[numpy.float64[m, 3]], attribute_name: str) -> None

```

If I give 3 columns, I get "corrupted size vs. prev_size" and Python crashes for RGB and RGBA.

---
Versions:
```
vedo: 2023.4.6+dev14
pymeshlab: 2022.2.post4
```

Note: running `m1.face_curvature_principal_dir1_matrix()` should work but I'm currently getting a MissingComponentException which may be due to loss of information in the conversion.

**Comment by marcomusy** [comment]
Yes I can confirm that I get this too, adding a printout at line 2536:
```py
    for k in vmesh.pointdata.keys():
        data = vmesh.pointdata[k]
        if data is not None:
            if data.ndim == 1:  # scalar
                m.add_vertex_custom_scalar_attribute(data.astype(np.float64), k)
            elif data.ndim == 2:  # vectorial data
                if "tcoord" not in k.lower() and k not in ["Normals", "TextureCoordinates"]:
                    print("data.shape", data.shape, data.dtype)
                    m.add_vertex_custom_point_attribute(data.astype(np.float64), k)
```

pymeshlab crashes:
```
data.shape (2503, 3) float64
free(): corrupted unsorted chunks
Aborted (core dumped)
```
But the input to `add_vertex_custom_point_attribute()` looks correct to me.

Unfortunately this seems to be an issue in `pymeshlab` I cannot do much about it... maybe you can open an [issue](https://github.com/cnr-isti-vclab/PyMeshLab/issues) there?

Also it looks like that 3 is the only dimensionality the method accepts..

**Comment by JeffreyWardman** [comment]
Thanks for confirming. Created the issue.
