### ISSUE TITLE
How to extract points from a specific view..

### ISSUE THREAD

**Issue by hjo111** [marcomusy/vedo#941]
Hello,
I want to extract the points only from the part that is currently visible. 
 Like a 2D image..  but with 3D coordinates..

 Is there a good way?

![image](https://github.com/marcomusy/vedo/assets/78400725/7acc62c6-01fb-457f-988d-76f34a75e936) 
![image](https://github.com/marcomusy/vedo/assets/78400725/1b80c8d7-e808-4387-8c95-38a0f2eedd87)

**Comment by marcomusy** [comment]
Hi, sure you can use
`settings.use_parallel_projection = True  # if desired`
then
https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#visible_points

**Comment by hjo111** [comment]
Thank [you!](url)
The example code works fine..  
from vedo import *

# settings.use_parallel_projection = True  # if desired

from vedo import Ellipsoid, show, visible_points
# s = Ellipsoid().rotate_y(30)
s = Mesh(dataurl+"man.vtk")
# s= load('./a.stl')

#Camera options: pos, focal_point, viewup, distance,
camopts = dict(pos=(0,0,25), focal_point=(0,0,0))
show(s, camera=camopts, offscreen=True)

m = visible_points(s)
#print('visible pts:', m.points()) # numpy array
show(s, m, new=True, axes=1) # optionally draw result on a new window
print(m.points()) 

![image](https://github.com/marcomusy/vedo/assets/78400725/ae968f09-eed8-4219-ac19-4149660a652f)

but my stl file(a.stl) result is strange... 
![image](https://github.com/marcomusy/vedo/assets/78400725/86ef372a-ef76-45cc-baaa-314919fd0792)

**Comment by hjo111** [comment]
Thank you!
acutally, I want to extract the surface...  Is there a good way?
![image](https://github.com/marcomusy/vedo/assets/78400725/c0901a5a-0f77-4205-a2bc-773b93aefb0d)

**Comment by hjo111** [comment]
[s2.zip](https://github.com/marcomusy/vedo/files/12812672/s2.zip) 

this is above picture file...  Thank you..

**Comment by hjo111** [comment]
[code]
s2= load('s2.stl')
camopts = dict(pos=(0,0,500), focal_point=(0,0,100)) # 
show(s2, camera=camopts, offscreen=True)
m = visible_points(s2)
show(m, new=True, axes=1) 
 
It's a pity that the side surfaces are not fully visible What should I do?..

**Comment by marcomusy** [comment]
Hi, I'm afraid this is not a well defined problem! Or at least I cannot think of a meaningful or unique way to do it ..
