### ISSUE TITLE
Extract and save separate mesh from existing mesh with certain "label" data

### ISSUE THREAD

**Issue by priyabiswas12** [marcomusy/vedo#951]
hello,

I would like to extract and save a mesh in stl format, from a bigger mesh that has certain mesh.celldata['Label'] information.
 May I know how this can be done?
Thank you for your time

**Comment by marcomusy** [comment]
Hi, you can do it with `.threshold()` check out:
`examples/basic/mesh_threshold.py`

**Comment by priyabiswas12** [comment]
hmm im still not sure how to do it using that function. I currently have a mesh and would only like to extract the part of the mesh where mesh.celldata['Label']==3 and save it as a seprate mesh. May I please know how to do this?
thank you so much

**Comment by marcomusy** [comment]
Try:
```py
from vedo import *

man = your_Mesh

scals = mesh.celldata['Label']
print(scals) # to check it's there

# make a copy and threshold the mesh
cutman = man.clone().threshold("Label", 2.9, 3.1, on='cells')
cutman.write('my_cut_mesh.stl')
show(man, cutman, N=2)
```

**Comment by priyabiswas12** [comment]
Oh i see, thank you so much!
