### ISSUE TITLE
Timer callback examples not working (Windows?)

### ISSUE THREAD

**Issue by jonaslindemann** [marcomusy/vedo#952]
Hi!

I am trying to implement animation using timer callbacks, but the examples don't work. 

In the example, 

https://github.com/marcomusy/vedo/blob/master/examples/advanced/timer_callback0.py

the timer callback is never called. The other example crash with missing enable_picking=False option. If you remove the option it runs, but crash when clicking on a button in the window.

I am running the latest version of Vedo. 

Jonas

**Comment by marcomusy** [comment]
Hi, that's weird.. have you tried to update vtk
`pip install vtk -U`

**Comment by jonaslindemann** [comment]
It is the latest version:

pip install -U vtk
Requirement already satisfied: vtk in c:\users\miniconda3\envs\compute-env\lib\site-packages (9.2.6)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from vtk) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (1.0.5)
Requirement already satisfied: cycler>=0.10 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (1.4.4)
Requirement already satisfied: numpy>=1.20 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (1.25.2)
Requirement already satisfied: packaging>=20.0 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (23.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from matplotlib>=2.0.0->vtk) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\miniconda3\envs\compute-env\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.0.0->vtk) (1.16.0)

**Comment by jonaslindemann** [comment]
Thanks!

**Comment by marcomusy** [comment]
I think Windows wants the interactor initialized. As a fix try add this:
```py
...

plt = Plotter(axes=1)
plt.interactor.Initialize() #####
plt.add_callback("timer", loop_func)
plt.timer_callback("start")
plt.show(msh, txt)
plt.close()
```

**Comment by jonaslindemann** [comment]
It works!

Thanks.
