### ISSUE TITLE
AttributeError: module 'vtkmodules.all' has no attribute 'vtkFlagpoleLabel'

### ISSUE THREAD

**Issue by LiB98** [marcomusy/vedo#955]
I just use "pip install vedo"; and when I  "import the vedo", the error occurs; How to solve it, thank you

**Comment by marcomusy** [comment]
Hi, try
```
pip install vtk -U
```
to update vtk.

**Comment by LiB98** [comment]
> Hi, try
> 
> ```
> pip install vtk -U
> ```
> 
> to update vtk.

Requirement already satisfied: vtk in /data/Tools/anaconda/envs/vnet/lib/python3.7/site-packages (8.2.0)
It doesn't help

**Comment by marcomusy** [comment]
That is strange .. what is your operative system? because 8.2 is already quite old..
Try
```
pip install vtk==9.2.6
```
this will probably fail but will tell you what vtk version are available for your system.

**Comment by LiB98** [comment]
> That is strange .. what is your operative system? because 8.2 is already quite old.. Try
> 
> ```
> pip install vtk==9.2.6
> ```
> 
> this will probably fail but will tell you what vtk version are available for your system.

Wow this works, thank you!
