### ISSUE TITLE
Boundary points of 2D geometry

### ISSUE THREAD

**Issue by DeepaMahm** [marcomusy/vedo#959]
Hi @marcomusy,

I want to find the coordinates of the boundary points to specify boundary conditions for 2D geometry like the below (geometry generated by specifying point cloud)

![image](https://github.com/marcomusy/vedo/assets/29662579/c36c117f-bcef-466f-9e27-b2464daab1e9)

I am unsure how to get the coordinates of boundary points for the two ends of the geometry. On one end , I have to specify the Dirichlet and Neumann on the other end in `deepxde` library; so I need  the boundary coordinates separately.

Could you please give some suggestions on how we could get the boundary coordinates in `vedo`?

**Comment by marcomusy** [comment]
Hi, you can try to use https://vedo.embl.es/autodocs/content/vedo/vedo/pointcloud.html#delaunay2d
and then https://vedo.embl.es/autodocs/content/vedo/vedo/mesh.html#Mesh.boundaries

**Comment by DeepaMahm** [comment]
Hi @marcomusy,

Sorry for the late reply. 

Thanks a lot for the suggestions. I could use delaunay and mesh boundaries; it works great!

<img width="347" alt="vedo" src="https://github.com/marcomusy/vedo/assets/29662579/5c3e16c2-a492-43e1-a7e2-f6b602c0f32e">

I could get all the boundary points (colored red in the above image). I would like to get the indices/labels of the boundary points which lie within the square boxes.

Could you please suggest how we can get those labels?

**Comment by marcomusy** [comment]
Hi Deepa, you can create a small 3D box and use `box.inside_points()`.
if you already know their positions the ids are in the same order as the points/vertices.

Btw, If you upgrade you vedo version you will need to change 
    b = delaunay2d(pts, mode='xy').c('w').lc('o').lw(1)
to
    b = pts.generate_delaunay2d(mode='xy').c('w').lc('o').lw(1)

**Comment by DeepaMahm** [comment]
Thank you, I have the positions but those are the coordinates of all the boundary points.
Could you please let me know how to create the 3D box after plotting the geometry (`show`) ? Can we mark the box interatively in the plot window that appears?

Updated : `b = pts.generate_delaunay2d(mode='xy').c('w').lc('o').lw(1)`, thank you.

**Comment by marcomusy** [comment]
in your code `pids` and `pts.vertices` are 2 aligned numpy array if i understand correctly so you can extract/slice the pids array the way you like?

> how to create the 3D box after plotting the geometry (show) ? Can we mark the box interactively in the plot window that appears?

yes, you need to create a callback function that generates a new box and place it where you click.. unless you have to do this repeatedly it's probably overkilling :)
i can help you with that if needed.

**Comment by DeepaMahm** [comment]
> in your code `pids` and `pts.vertices` are 2 aligned numpy array if i understand correctly so you can extract/slice the pids array the way you like?

![image](https://github.com/marcomusy/vedo/assets/29662579/3f4faa9b-ae5f-4ae5-bdeb-764b4ddd2623)

I tried to visually readout the vertex labels of boundary points on one end of the geometry (to use `pids` and `pts.vertices`  and get the vertices of selective boundary pids). The label overlaps and I couldn't read it clearly (unfortunately print(lables) didn't work, since it is a mesh object) and by changing scale (`labels = boundary_pts.labels('id', scale=0.5).z(0.01)`) I couldn't reduce the font size of the text that appears for labels.

> yes, you need to create a callback function that generates a new box and place it where you click.. unless you have to do this repeatedly it's probably overkilling :) i can help you with that if needed.

Agree :) For now , I need to do this only once. Thank you

**Comment by marcomusy** [comment]
try `labels2d()` instead.

**Comment by marcomusy** [comment]
Consider this option:

```py
from vedo import *

circle = Circle(res=36)

mesh = circle.generate_mesh()
labels = mesh.labels2d('id')

# Add a pointdata array to the mesh to store the point IDs
mesh.add_ids()
mesh.color('green9').lc("white")

mboundaries = mesh.boundaries()
print(mboundaries)

pids = mboundaries.pointdata["PointID"]
print("PIDS   = ", pids)
print("POINTS = ", mesh.vertices[pids])

show(mesh, mboundaries, labels).close()
```


![Screenshot from 2023-11-16 16-09-40](https://github.com/marcomusy/vedo/assets/32848391/db75d37f-8333-48cf-8520-a6e9c2464c74)




![Screenshot from 2023-11-16 16-07-31](https://github.com/marcomusy/vedo/assets/32848391/34f09eb9-9a31-4404-9992-77ffaacd989b)

**Comment by marcomusy** [comment]
Yes, try
```py
from vedo import *

circle = Circle(res=36)
mesh = circle.generate_mesh()

# Add a pointdata array to the mesh to store the point IDs
mesh.add_ids()
mesh.color('green9').lc("white")

mboundaries = mesh.boundaries()
print(mboundaries)

pids = mboundaries.pointdata["PointID"]
print("PIDS   = ", pids)
print("POINTS = ", mesh.vertices[pids])
labels = mboundaries.labels("PointID")

show(mesh, mboundaries, labels).close()
```
![Screenshot from 2023-11-17 15-41-28](https://github.com/marcomusy/vedo/assets/32848391/90a3f823-3b56-4df0-8589-aed85f97aa9e)

**Comment by DeepaMahm** [comment]
Thank you so much.

`mesh.add_ids()
`
helps!

Unfortunately, I've the same issue again; the labels aren't clearly readable.

![image](https://github.com/marcomusy/vedo/assets/29662579/d91e1ae6-7b06-4dd1-bfd6-b32be560b6c1)

I tried to check if
 `
labels = boundary_pts.labels2d('id', on="points", scale=0.5)`

works with `mesh.add_ids()`. But `labels2d` add labels for the boundary points from 0 ...

Could you please suggest if there is an alternative?
Thanks so much for your kind attention

**Comment by marcomusy** [comment]
No worries, in fact there is a bug in `labels2d()`, add
```
settings.use_parallel_projection = False
```
then make the labels smaller so they dont overlap eg  `scale=0.25`.

**Comment by DeepaMahm** [comment]
Hello @marcomusy ,

Instead of circle, I am now trying to create a rectangle geometry.

I tried, 

```
from vedo import *

 rectangle = Rectangle([0.0, 0.0], [5.0, 1.0])
 mesh = rectangle.generate_mesh()

# Add a pointdata array to the mesh to store the point IDs
mesh.add_ids()
mesh.color('green9').lc("white")

mboundaries = mesh.boundaries()
print(mboundaries)

pids = mboundaries.pointdata["PointID"]
print("PIDS   = ", pids)
print("POINTS = ", mesh.vertices[pids])
labels = mboundaries.labels("PointID")

show(mesh, mboundaries, labels).close()

```

However, `print( mesh.vertices)` displays only 5 points and I see a warning (` vtkDelaunay2D.cxx:1419  WARN| vtkDelaunay2D (00000175765CA0F0): Edge not recovered, polygon fill suspect`)
```
[[2.5012121 1.014475  0.       ]
 [5.        1.        0.       ]
 [5.        0.        0.       ]
 [0.        0.        0.       ]
 [0.        1.        0.       ]]
```
whereas, while using `Circle`, I could get all the points on the surface (vtkDelaunay2D).


Could you please let me know how to create ``Rectangle` and `generate_mesh()`?

I also tried, 

 ```
polygon = [
         [(82, 92, 47), (87, 88, 47),  # x,y,z of vertices
          (93, 95, 47), (88, 99, 47)],
         [[0, 1, 2, 3]],  # vertex connectivity
     ]
 mesh = Mesh(polygon)

```
Unfortunately, this also returns only 5 points when I try mesh.vertices.

**Comment by marcomusy** [comment]
Hi, what about triangulating a simple grid:

```py
from vedo import *

mesh = Grid(s=[np.arange(0,5, 0.2), np.arange(0,1, 0.2)]).triangulate()

# Add a pointdata array to the mesh to store the point IDs
mesh.add_ids()
mesh.color('green9').lc("white")

mboundaries = mesh.boundaries()
print(mboundaries)

pids = mboundaries.pointdata["PointID"]
print("PIDS   = ", pids)
print("POINTS = ", mesh.vertices[pids])
labels = mboundaries.labels("PointID")

show(mesh, mboundaries, labels).close()
```

<img width="328" alt="Screenshot 2023-12-12 at 14 29 53" src="https://github.com/marcomusy/vedo/assets/32848391/f7e6e8be-4fe7-4804-a6d5-4361d3aea472">

**Comment by DeepaMahm** [comment]
Thanks a lot; it works great!

I could get
![image](https://github.com/marcomusy/vedo/assets/29662579/e4b70b9e-798a-4735-95a5-b9b9df399d72)

Could you please let me know if we can create fine mesh? i.e. I would like to get more points/vertices in the domain and boundary

**Comment by marcomusy** [comment]
Hi, you can change the numpy array to any spacing `np.arange(0,5,  x)`

**Comment by DeepaMahm** [comment]
Hi @marcomusy ,

For a geometry like the following 

![image](https://github.com/marcomusy/vedo/assets/29662579/cf090d7f-9fda-4b9a-8bcc-43aff95f8098)

I would like to get all the boundaries (please refer to the lines marked with black and indicated with arrows).

Using,

    b = pts.generate_delaunay2d(mode='xy').c('w').lc('o').lw(1)
    b.add_ids()
    #vplt.show(pts, labels, dly, __doc__, bg="Mint").close()
    b.compute_normals().clean().linewidth(0.1)
    boundary_pts = Points(b.points()[pids], r=10, c='red5')

I could obtain the points marked with red dots as boundaries.

Could you please help me with obtaining all the boundary points (i.e. including boundaries inside the domain)?

The original geometry is added here ([image](https://github.com/DeepaMahm/misc/blob/master/Bagah.jpeg)) for your kind reference and I would like to get the boundary points of all the vessel branches.
