### ISSUE TITLE
vtkplotter with PyQt5: Windows vs Linux

### ISSUE THREAD

**Issue by Yoorthiziri** [marcomusy/vedo#96]
In the examples of embedding vtkplotter in PyQt window, I noticed that in Windows we can use the usual keyboad  keys to insteract with the mesh (e.g: `w` to display wireframe, `s` for surface, ...etc). But in linux (Ubuntu) these keys don't work.

Why there is such a difference between Windows and Linux? is it due to vtk library itself?

Thanks

**Comment by marcomusy** [comment]
Yes, I think it's because of the vtk library... in the latter case i'm afraid you will need write an observer.
