### ISSUE TITLE
Making animations using interpolate_data_from

### ISSUE THREAD

**Issue by sshsphere** [marcomusy/vedo#960]
Hello! I am trying to create an animation with the interpolate_data_from method for meshes. My current solution is to reload the whole mesh everytime I want to change its color, which might cause performance issues. Is there a better way to do this?

This is my current solution (animated version of `interpolate_scalar1.py`)
```python
def loop_func(plt, mesh, points):
    time_s=time.time_ns()/ (10 ** 9)
    if(time_s-loop_func.last_update>0.5):
        points.points(random.sample(list(mesh.points()),100))

        #These lines are necessary
        #Simply writing mesh.interpolate_data_from(points, n=5).cmap('rainbow') does not work
        plt.pop()
        mesh=Mesh(mesh)
        mesh.interpolate_data_from(points, n=5).cmap('rainbow')
        plt+=mesh

        plt.render()
        loop_func.last_update=time_s

loop_func.last_update=0
plt = Plotter(size=(1050, 600))
mesh = Mesh(dataurl+"bunny.obj")
points = Points(random.sample(list(mesh.points()),100), r=10).cmap('rainbow', np.random.randint(45,123, 100))
plt+=points
plt+=mesh

plt.add_callback("timer", lambda _: loop_func(plt, mesh, points))
plt.timer_callback("start")
plt.show().close()
```

**Comment by marcomusy** [comment]
Hi, try this:

```py
from vedo import *
import random

def loop_func(evt):
    points.points(random.sample(list(mesh.points()), 100))
    # mesh.pointdata.remove("MyScalars")
    mesh.interpolate_data_from(points, n=5).cmap("rainbow")
    plt.render()

mesh = Mesh(dataurl + "bunny.obj").c("white")

pts = random.sample(list(mesh.points()), 100)
scalars = np.random.randint(45, 123, 100)
points = Points(pts).point_size(10)
points.cmap("rainbow", scalars, name="MyScalars")

plt = Plotter(size=(1050, 600))
plt.add_callback("mouse right click", loop_func)
plt.show(points, mesh, "Right-Click Me!").close()
```
![Screenshot from 2023-11-07 20-58-03](https://github.com/marcomusy/vedo/assets/32848391/1449e29b-411a-4787-8447-b79ae2ceb14d)

Note that you cannot change the signature of the callback function, it must be `loop_func(event)`.
Also I had never seen this:
`loop_func.last_update=0` 
I didn't know it was valid python... I guess it is :)

**Comment by sshsphere** [comment]
It seems that only the points change and not the color of the mesh, I've attached a video of the issue. I am also currently running this on WSL, could that be causing issues?

https://github.com/marcomusy/vedo/assets/47260097/e501ce8b-8d0c-419a-bf3c-75d50feff121

**Comment by marcomusy** [comment]
Can you try:
```
pip install -U git+https://github.com/marcomusy/vedo.git
```

**Comment by sshsphere** [comment]
Still the same problem. Does it work on your end?

**Comment by marcomusy** [comment]
Hi sorry I might have made a mistake.. no indeed it does not work, can you try by uncommenting 
```    
# mesh.pointdata.remove("MyScalars")
```

**Comment by sshsphere** [comment]
That fixed it! Thank you so much for your help

**Comment by marcomusy** [comment]
Thanks for drawing my attention to it , I will investigate if there is a bug - i'm not sure right now..
