### ISSUE TITLE
get_transform() return identity matrix

### ISSUE THREAD

**Issue by Tai-Hsien** [marcomusy/vedo#962]
Hello,

My vedo is 2023.4.6.

I just found that get_transform() for a mesh always return identity matrix for both invert=True or False. I checked the the matrix from GetMatrix() of the vtk object which has the right transformation matrix.

Thanks again for working on vedo!

**Comment by marcomusy** [comment]
Hi Bruce, thanks for reporting!
these problems with transformations should be resolved in the coming release of vedo, you can already try it out with
```
git clone https://github.com/marcomusy/vedo.git
cd vedo
git checkout restruct_mem
pip install -e .
```

with this you will have `vedo 2023.5.0+dev31a`. You will be then able to access the transformation with

```py
myobject.transform         # a vedo.LinearTransformation or
myobject.transform.matrix  # a 4x4 numpy matrix
```
