### ISSUE TITLE
cut_with_point_loop does not keep pointdata information

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#964]
A mesh with RGBA information loses its color when running `mesh.cut_with_point_loop(pts, invert=True)`. The RGBA key becomes `None`. It seems that each time the function is called, a pointdata key is removed if it is not `Normal`. For instance, I had a key called `Label` which remained after the first function call but was lost after the second. The RGBA was lost after the first (and was at the top of the list of keys).

I'd like to keep all pointdata, including RGBA.

**Comment by marcomusy** [comment]
Hi, I think this is a vtk bug and they fixed it in vtk 9.3.0

**Comment by JeffreyWardman** [comment]
Can confirm upgrading VTK from 9.2.6 to 9.3.2 resolved this. Thanks!
