### ISSUE TITLE
curvature-adaptive least-squares smoothing

### ISSUE THREAD

**Issue by jo-mueller** [marcomusy/vedo#966]
Hi @marcomusy ,

I am looking for a way to use the moving leastsquares 2d smoothing that would allow me to specify a neighborhood radius individually for each point in the pointcloud. In short, my application would be to use a slightly smaller neighborhood radius in strongly curved regions than in weakly curved regions. I have a semi-good estimation technique at hand, all I would need would be to be able to pass an array of radii to the [smooth_mls_2d](https://vedo.embl.es/docs/vedo/pointcloud.html#Points.smooth_mls_2d) function.

The implementation could be relatively cheap by adding a type check [here](https://vedo.embl.es/docs/vedo/pointcloud.html#Points.smooth_mls_2d-3530) that checks if radius has a `len()`. What do you think? I'd be happy to try myself at implementing it :)

**Comment by marcomusy** [comment]
Hi @jo-mueller yes- that could be a cool idea! provided you have an independent way to estimate the local radius.
You just need to check - as you said - with `utils.is_sequence(radius)`

**Comment by jo-mueller** [comment]
Nice, thanks for the feedback! Will try myself at implementing it :)

**Comment by jo-mueller** [comment]
PR opened :)

**Comment by jo-mueller** [comment]
Awesome, thanks @marcomusy !
