### ISSUE TITLE
How to avoid copying pointdata when extruding mesh?

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#967]
When I extrude a mesh, the pointdata is copied. Is there a way to extrude and set a default value for each pointdata/set to None?

**Comment by marcomusy** [comment]
well you can remove any array with `myobj.pointdata.remove(arr_name)`.

**Comment by JeffreyWardman** [comment]
Sorry, what I meant was I want to retain the existing array, and append to it a default value (e.g. None or -1). For instance if I create a key called "Shoe" and it's values are True if the vertex is part of a shoe and False if it's not, then I want the shoe vertices to still be True, and the rest be False (including the new points). If the extrusion is done with shoe vertices (True), then I want the new points to be False, rather than copying the True value.

**Comment by marcomusy** [comment]
No, that is not feasible.
But you can still do it by combining that information with a new scalar which would be the z coordinate of the point itself.

**Comment by JeffreyWardman** [comment]
Great. Thanks for your help!
