### ISSUE TITLE
'Box' object has no attribute 'origin'

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#972]
I assume this is a bug in 2023.5.0 as it's not mentioned in the release changes.
Origin seems to be removed from the documentation completely as well. Is there a replacement variable or is it expected to run `mesh.box().vertices.mean(axis=0)` each time instead?

**Comment by marcomusy** [comment]
Yes, or `mesh.box().center_of_mass()` or `mesh.box().pos()`.

**Comment by JeffreyWardman** [comment]
Okay thanks. center of mass != origin (e.g. horseshoe shapes). I found origin to be a nicer naming convention than pos but it does the job. Thanks.
