### ISSUE TITLE
Plane.clone() got an unexpected keyword argument 'transformed'

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#973]
In 2023.5.0, is it still required to include `transformed=True` to copy the mesh with the transforms? Is this replaced entirely with `deep=True`? The information isn't in the release docs.

**Comment by marcomusy** [comment]
Yes, thanks for pointing out these problems in the documentation.
No more transformed keyword is required.

**Comment by JeffreyWardman** [comment]
No worries. Glad to help!
