### ISSUE TITLE
Extruding a set of lines does not store cells

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#975]
Extruding `mesh.boundaries()` no longer creates faces/cells in 2023.5.0.

```
import vedo
boundaries = vedo.load("boundaries.vtk")
assert boundaries.extrude(2).cells != []
```
[boundaries.zip](https://github.com/marcomusy/vedo/files/13384935/boundaries.zip)

**Comment by marcomusy** [comment]
Oh I know why.. triangle strips are no more automatically converted to polygons. You need to add
```py
import vedo
boundaries = vedo.load("boundaries.vtk")
mex = boundaries.extrude(2).triangulate().print()
plotter = vedo.Plotter(axes=1)
plotter.show(mex)
```

**Comment by JeffreyWardman** [comment]
This resolves the cells. I've gone further and it looks like lines and normals aren't updated either.

**Comment by JeffreyWardman** [comment]
`compute_normals()` doesn't add the normals either for the boundaries mesh example.

**Comment by marcomusy** [comment]
Just pushed a fix, try:
```py
from vedo import *

boundaries = Mesh("boundaries.vtk")

mex = boundaries.extrude(5)
# mex.triangulate() # not needed
mex.compute_normals()
mex.pointdata.select("RGBA")
print(mex)

v = mex.vertices
n = mex.vertex_normals
arrs = Arrows(v, v + n)

show(mex, arrs, axes=1).close()
```
![Screenshot from 2023-11-17 17-45-36](https://github.com/marcomusy/vedo/assets/32848391/36eb46c0-7d3b-4527-8f56-d50fda771c6a)

note that normals must be recomputed (if they are needed).

**Comment by JeffreyWardman** [comment]
Great! It works now. Thanks!

**Comment by JeffreyWardman** [comment]
Apologies, I realised I had the code commented out... 

It works with your example but it seems to be due to boundaries being a Mesh. In my code, the dtype is Mesh but it seems to act differently. I was able to reproduce my results with this:


```
boundaries = vedo.Rectangle().boundaries()
boundaries.compute_normals()
print(boundaries.vertex_normals)
```

**Comment by JeffreyWardman** [comment]
Here's another example (which for some reason doesn't work even if loaded from a file. It was created by mesh.clone().boundaries().clone(deep=True) for the same mesh as the previous example (boundaries.vtk): 
[boundaries2.zip](https://github.com/marcomusy/vedo/files/13405205/boundaries2.zip)

The issue might lie in the `mesh.boundaries()` function.

**Comment by JeffreyWardman** [comment]
@marcomusy do you know how I can generate the normals of the vertices of the boundary lines? Unfortunately I haven't been able to migrate to the latest version of vedo due to this.

**Comment by marcomusy** [comment]
Hi Jeffrey - sorry I forgot this one.
I think you cannot recompute normals from the outline alone without polygons. But you can save and access the normals after extracting the boundaries. Consider these examples:
```py
from vedo import *
mesh = Mesh("data/boundaries.vtk")
mesh = mesh.clone().boundaries().clone(deep=True) 
mesh.write("a.vtk") # test write and read back
mesh = Mesh("a.vtk")
boundaries = mesh.boundaries()
print(boundaries)
v = boundaries.vertices
n = boundaries.vertex_normals
arrs = Arrows(v, v + n)
show(mesh, arrs, axes=1).close()
```
![Screenshot from 2023-11-28 12-57-50](https://github.com/marcomusy/vedo/assets/32848391/8ae3a7a1-0797-4471-9ec7-8182c469452d)


```py
from vedo import *
mesh = Polygon(nsides=12).triangulate().add_gaussian_noise()
mesh.compute_normals()
boundaries = mesh.boundaries()
boundaries.compute_normals()
print(boundaries.vertex_normals)
v = boundaries.vertices
n = boundaries.vertex_normals
arrs = Arrows(v, v + n/2)
show(mesh.lw(1), boundaries, arrs, axes=1).close()
```

![Screenshot from 2023-11-28 12-56-43](https://github.com/marcomusy/vedo/assets/32848391/66048b8c-66b6-4d73-943b-d7fcb8becfe8)

```py
from vedo import *
mesh = Mesh(dataurl+'290.vtk').alpha(0.2)
mesh.compute_normals()

# Get the point IDs on the boundary of the mesh
pids = mesh.boundaries(return_point_ids=True)
print(pids)

# OR, get the boundary of the mesh as a new Mesh object
boundaries = mesh.boundaries()
print(boundaries)

# OR, get the boundary of the mesh as a new Mesh object
# with an extra array containing the point IDs of the original mesh
# boundaries = mesh.add_ids().boundaries()
# print(boundaries)

v = boundaries.vertices
n = boundaries.vertex_normals
arrs = Arrows(v, v + n*100)
show(boundaries, mesh, arrs, axes=1).close()
```
![Screenshot from 2023-11-28 12-51-07](https://github.com/marcomusy/vedo/assets/32848391/9ef4e9a2-8fcc-4f8c-ae79-0a7766c08c9d)

**Comment by JeffreyWardman** [comment]
Awesome, thanks for your help! That resolved it! It must be related to VTK not reading in the normals... Thanks for helping me resolve all my issues migrating to the latest version.
