### ISSUE TITLE
Feature Request: vedo2madcad

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#976]
Creating a separate issue to reflect discussion in https://github.com/marcomusy/vedo/issues/968.

Want: To be able to convert easily with pointdata attributes to and from the `madcad` library.

**Comment by marcomusy** [comment]
Just implemented `utils.madcad2vedo()` with an example in `examples/other/madcad1.py`.

**Comment by JeffreyWardman** [comment]
Awesome, thanks!!!

**Comment by JeffreyWardman** [comment]
@marcomusy reopening as I noticed there isn't an implementation of `madcad2vedo`, just `vedo2madcad`. It'd be good to be able to convert to madcad with a `vedo2madcad` function, run `madcad.thicken` and then convert back without losing the RGBA information in pointdata.

**Comment by marcomusy** [comment]
As you are familiar with madcad would you give it a try creating a `vedo2madcad()` function?

**Comment by JeffreyWardman** [comment]
Sure thing!

**Comment by JeffreyWardman** [comment]
PR up. FYI it doesn't look like they support vertex colour, just the mesh as a whole.
