### ISSUE TITLE
Loading TetMesh in v2023.0.5

### ISSUE THREAD

**Issue by RobinEnjalbert** [marcomusy/vedo#977]
Hi @marcomusy,

Thanks for the new release, I am currently going through the changes in my personal code base.

I found that is it no longer possible to create a `TetMesh` like so:
```python
mesh = vedo.Mesh('tetra_mesh_file.vtk')
```
I liked being able to create any mesh - in this case tetra meshes - from a unique class `Mesh`.

In the previous version, if the mesh was loaded from a file, the mesh type was checked to see if it is a `TetMesh` ([here in the code](https://github.com/marcomusy/vedo/blob/af74a6f676a932ad312ce374c8ebc75fbb2f1a00/vedo/mesh.py#L161)). 
I wonder why this disappeared in the new version ? Do we have to create a `TetMesh` only from this class ?

**Comment by marcomusy** [comment]
Hi @RobinEnjalbert 
yes that was removed because I think it was "too automatic".. polygonal meshes and tet-meshes are very different objects.
So in your code it should become `mesh = vedo.TetMesh('tetra_mesh_file.vtk').tomesh()`.

**Comment by RobinEnjalbert** [comment]
Thanks !
