### ISSUE TITLE
Spammed with warning message when reading OBJ files containing normals

### ISSUE THREAD

**Issue by JeffreyWardman** [marcomusy/vedo#980]
```
2023-11-20 13:54:20.008 (  76.838s) [    7F1A24E29000]       vtkOBJReader.cxx:215   WARN| vtkOBJReader (0x55c3b64fb7b0): unexpected data at end of line in OBJ file L.164377
```

I didn't get this warning in 2023.4.6. The pointcloud looks normal generally but not sure if there's information lost. It seems to hang after this if running multiple on different threads. It also prints this out for at least thousands of lines, if not all.

---

So it's when the obj has the vertices and normals in the same line, e.g.:

```
v -3.63908441 0.54718045 -98.45739205 0.50196078 0.50196078 0.50196078
```

This issue doesn't occur with the classic `bunny.obj` which has just `v x y z`. It also only occurs on the vertex lines, not the faces. I'm not sure if this issue would extend to other file readers.

**Comment by JeffreyWardman** [comment]
@marcomusy the issue isn't fixed as of https://github.com/marcomusy/vedo/commit/b27e279f7547aa5e0b2e1fc447bed6f1c96e60df

**Comment by marcomusy** [comment]
It should be now..

**Comment by JeffreyWardman** [comment]
Updating vedo (2023.5.0+dev3 b27e279 -> 2023.5.0+dev3 391ce9c) doesn't print the error anymore nor does it hang in a Jupyter notebook but it also doesn't store the vertex normals.

**Comment by marcomusy** [comment]
I'm afraid this is related to some problem in the upstream vtk not vedo..

**Comment by JeffreyWardman** [comment]
I can't see an issue relating to this. Do you know if one exists?
