### ISSUE TITLE
Link to examples broken

### ISSUE THREAD

**Issue by jo-mueller** [marcomusy/vedo#981]
Hi @marcomusy ,

very minor issue: I found the link to the `surfIntersect.py` example broken (it's now called `surf_intersect.py`) - where could I fix this in the repo? If I stumble over these matters in the futures I can then simply send a small PR :)

Best, Johannes

**Comment by marcomusy** [comment]
Hi! that is in a js file on the server.. in fact it would be good to have it in the `docs/` so I will put a copy there, meanwhile I fixed it manually :)
