### ISSUE TITLE
Can't set up the camera to render Mesh

### ISSUE THREAD

**Issue by vitalii-p** [marcomusy/vedo#987]
I tried to set camera parameters for triangular mesh rendering, but seems like those parameters don't affect the output image.
Here is my code for setting up the camera

```py
   def setup_plotter(mesh: Mesh, camera_params: CameraParams):

    plotter = Plotter(offscreen=True, size=(camera_params.size, camera_params.size),bg='white')`

    plotter.add(mesh)

    camera = plotter.camera
    camera.SetPosition(*camera_params.position)  # Set the position of the camera
    camera.SetFocalPoint(*camera_params.look_at)  # Set the focal point of the camera
    camera.SetViewUp(*camera_params.up)  # Set the up vector of the camera
    camera.SetViewAngle(camera_params.fov())


    return plotter
```
  
  Then I call 
```
plotter.show().screenshot(out_filename)
```
Despite of changing SetPosition or SetFocalPoint - output image is still the same.

Currently I use **vedo==2023.4.6**, 
tried with 2023.5.0 - issue with the camera remains, but in addition I got wrong transformations when applied the same matrices via `mesh.apply_transform`.

Could you help me with camera setup? Thanks in advance!

**Comment by marcomusy** [comment]
Hi, you can setup the camera more simply by passing a dictionary:
```py
###################################################
## Template python code to position this camera: ##
cam = dict(
    position=(44.1916, -32.0029, 19.2009),
    focal_point=(-1.21754, 9.83238e-4, -2.27213e-4),
    viewup=(0, 0, 1.00000),
    roll=-77.0346,
    distance=58.7786,
    clipping_range=(21.9889, 105.231),
)
show(mymeshes, camera=cam)
```

Also - if you change some settings you should call `plotter.render()` to update the scene.

About the second problem - i cannot help without a specific reproducible example. In vedo 5.0 there is a better management of transformations so I hope you should now get the correct behavior.
