### ISSUE TITLE
Cloth Simulation

### ISSUE THREAD

**Issue by Rama144** [marcomusy/vedo#99]
I need to know  whether there is any cloth simulation method to make a mesh into a cloth .Could any one help me pointing out one. And I was not sure whether this is the right spot to  ask questions. If not please direct me to the right place.

**Comment by marcomusy** [comment]
If by cloth simulation you mean anything like [this](https://threejs.org/examples/webgl_animation_cloth.html) then no.. if you just want to deform a part of a mesh you can do it with moving mesh points directly or morphing it e.g. with _thin plate splines_:
```python 
import numpy as np
from vtkplotter import *

mesh = load(datadir+'bunny.obj')

# pick a few points of the mesh inside and outside of a cylinder region
cyl = Cylinder(pos=(0.0026,0.076,0.057), r=0.015, height=0.02).wireframe()
inpts  = cyl.insidePoints(mesh.clone().clean(0.02))
outpts = cyl.insidePoints(mesh.clone().clean(0.1), invert=True)

shifted_inpts = np.array(inpts) + [0, 0, 0.02]

arrs = Arrows(inpts, shifted_inpts, c='w')

sources = inpts + outpts
targets = shifted_inpts.tolist() + outpts
T = thinPlateSpline(mesh, sources, targets).getTransform()
warped_mesh= mesh.clone().transformMesh(T)

show([(mesh, arrs, cyl), warped_mesh], N=2)
```
![image](https://user-images.githubusercontent.com/32848391/72893729-10e35780-3d1a-11ea-8a7e-d9691b53eb45.png)

see [example](https://github.com/marcomusy/vtkplotter-examples/blob/master/vtkplotter_examples/advanced/thinplate_morphing.py).

**Comment by Rama144** [comment]
Thankyou so much for the response .
I have a 3d garment model I need to place that on different 3d human models . It will be time consuming to make size adjustments for each and every size human models . Is there any way to acheive this . 

I either need a way to feature match fit the 3d model 

![p2-01](https://user-images.githubusercontent.com/50174542/72902023-c7622f00-3d50-11ea-9293-6ec59674fdce.jpg)

or Place the 3d garment as it is by merging both meshes . 

![penetration](https://user-images.githubusercontent.com/50174542/72901669-2d9a8200-3d50-11ea-880f-22da65dc9ee4.jpg)

But I do get penetration of body mesh over cloth mesh .
Is there a  way to make the human mesh as a collision target as non-penetrable 
or move the cloth mesh point over the body model only in those penetrating places.

![hqdefault](https://user-images.githubusercontent.com/50174542/72901668-2d9a8200-3d50-11ea-86fe-d7c761b1f67c.jpg)


Could you please help me with this any small help or reference would be of great use ...

**Comment by marcomusy** [comment]
If you need to take into account the rigidity of the cloth (as it forms folds like the ones in the green hat in the first picture) then the problem is way more difficult, because you would need a proper simulation of the mechanical properties of the cloth.
If you only need to displace a few problematic regions then you can apply the mesh morphing as in my first example..

**Comment by Rama144** [comment]
Okie thanks will try out in the first way . Is there any method to make them collision detector to find out the regions in the cloth mesh to be displaced.

**Comment by marcomusy** [comment]
maybe these two examples can help:
https://github.com/marcomusy/vtkplotter-examples/blob/master/vtkplotter_examples/basic/distance2mesh.py

https://github.com/marcomusy/vtkplotter-examples/blob/master/vtkplotter_examples/basic/surfIntersect.py

**Comment by yeugiyoul** [comment]
I'm not sure why there's an error with the Stanford bunny.obj in vtkplotter sample code . Could you help me understand the reason?
